### ISSUE TITLE
Import a function throws type error exception

### ISSUE THREAD

**Issue by Rumpelstinsk** [cypress-io/cypress#7036]
### Current behavior:

Importing a function from a diferent file throws a type error

### Test code to reproduce

I want to test a page wich uses basic auth. So I write this line on a test:

```js
cy.visit("/my_url", { auth:{
      username: Cypress.env("BASICAUTH_USERNAME"),
      password: Cypress.env("BASICAUTH_USERNAME")
    } });
```

This line works with no problem. However, I want to test other pages with basic auth too. So, in order to avoid repeating this object I made a function to retrieve it:

```js
//Auth.js"
export default {
  basicAuth: () => {
    return {
      username: Cypress.env("BASICAUTH_USERNAME"),
      password: Cypress.env("BASICAUTH_USERNAME")
    };
  }
};
```

Then I import it on my original test file:

```js
import { basicAuth } from "./Auth";

//other lines here:

cy.visit("/my_url", { auth:basicAuth() });
```

Then when I run the code, I get a Type error on console:

```
> TypeError: Auth_1.basicAuth is not a function
      at xxxxxxx (#URL-Here#/__cypress/tests?p=test/app.spec.js-193:74:26)
      at Context.<anonymous> (#URL-Here#/__cypress/tests?p=test/app.spec.js-193:29:13)
```

### Versions

Cypress/included:4.4.0  from https://github.com/cypress-io/cypress-docker-images

**Comment by jennifer-shehane** [comment]
This is a regression introduced in 4.4.0. I'm able to replicate this with the code below:

`cypress/integration/spec.js`

```js
import { getUrl } from "./url"

//other lines here:
it('tests', () => {
  cy.visit({ url: getUrl() })
})
```

`cypress/integration/url.js`

```js
export default {
  getUrl: () => {
    return "https://example.cypress.io"
  }
}
```

### 4.3.0

<img width="790" alt="Screen Shot 2020-04-17 at 4 57 57 PM" src="https://user-images.githubusercontent.com/1271364/79559945-9e8dd380-80cc-11ea-8ebb-323a4b1881c4.png">

### 4.4.0

This throws an error, notice the attribution to `url_1.js`, which is...not the name of the file?

<img width="790" alt="Screen Shot 2020-04-17 at 4 55 41 PM" src="https://user-images.githubusercontent.com/1271364/79559750-4fe03980-80cc-11ea-8338-69a619f63996.png">

**Comment by jennifer-shehane** [comment]
This fails with function being called in the `options` object, may be related to cloning the options? https://github.com/cypress-io/cypress/pull/6459

The only other big change in 4.4.0 was the TypeScript support. https://github.com/cypress-io/cypress/pull/5906

Any of these PRs could effect this @sainthkh?

**Comment by sainthkh** [comment]
I'll check it out.

**Comment by sainthkh** [comment]
The cause was the typo in the code I wrote. Because of that, typescript was used to parse your file. To make it work, the code had to be written like `import { default as { getUrl } } from './url'`. It's not intuitive.

#7072 fixes the problem and babel parser will be used when you didn't include typescript inside your project like before.

If you're trying to adopt TypeScript, your code won't work. It is recommended to use named export instead like below:

```ts
export const basicAuth = () => {
    return {
      username: Cypress.env("BASICAUTH_USERNAME"),
      password: Cypress.env("BASICAUTH_USERNAME")
    };
  }
```
