### ISSUE TITLE
Test files from symlinked dirs are not detected

### ISSUE THREAD

**Issue by cristian-spiescu** [cypress-io/cypress#7038]
### Current behavior:

In my project I have a a symlinked directory w/ sources. Cypress doesn't see the test files from that linked dir.

### Desired behavior:

Cypress should allow users to have linked dirs which contain tests. #3482 may also be related to this.

### Versions

Cypress v4.3.0; Windows 10

Thank you!

**Comment by BlueWinds** [comment]
Going to close this as duplicate in favor of https://github.com/cypress-io/cypress/issues/3482
