### ISSUE TITLE
Cypress installation fails with CYPRESS_INSTALL_BINARY set to external URL 

### ISSUE THREAD

**Issue by osmanamjad** [cypress-io/cypress#7046]
### Current behavior:

I'm attempting to install Cypress from an external URL using the `CYPRESS_INSTALL_BINARY` environment variable. On the CLI I ran the following commands

1. `SET CYPRESS_INSTALL_BINARY=http://artifactory:8081/Cypress/4.4.0/cypress.zip`
2. `npm install cypress`

This is the output shown on the CLI:

```
> cypress@4.4.0 postinstall C:\EverythingCypress\node_modules\cypress
> node index.js --exec install

‼ Warning: Forcing a binary version different than the default.

  The CLI expected to install version: 4.4.0

  Instead we will install version: http://artifactory:8081/Cypress/4.4.0/cypress.zip

  These versions may not work properly together.

Installing Cypress (version: http://artifactory:8081/Cypress/4.4.0/cypress.zip)

  √  Downloaded Cypress
  ×  Unzipping Cypress
    → Cypress Version: 4.4.0
     Finishing Installation
The Cypress App could not be unzipped.

Search for an existing issue or open a GitHub issue at

https://github.com/cypress-io/cypress/issues

----------

Error: end of central directory record signature not found

----------

Platform: win32 (10.0.17763)
Cypress Version: 4.4.0
npm WARN enoent ENOENT: no such file or directory, open 'C:\EverythingCypress\package.json'
npm WARN EverythingCypress No description
npm WARN EverythingCypress No repository field.
npm WARN EverythingCypress No README data
npm WARN EverythingCypress No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@4.4.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@4.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mamjad\AppData\Roaming\npm-cache\_logs\2020-04-16T22_38_51_614Z-debug.log
```

### Desired behavior:

When I use the same `cypress.zip` locally, there is no issue in installing cypress with the same commands listed above with the `CYPRESS_INSTALL_BINARY` variable set to the local path to the zip file. After it worked locally I uploaded this zip file to my company's artifactory. I wish to be able to install with the `CYPRESS_INSTALL_BINARY` set to the external URL i specified. I've verified the URL is correct and the zip file exists there. 

I read that the `CYPRESS_INSTALL_BINARY` did not support URLs that begin with `http`, but that issue seems to have been resolved, I believe.

**Comment by jennifer-shehane** [comment]
@osmanamjad Could you run Cypress install in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
