### ISSUE TITLE
cy.route() doesn't catch network calls as expected

### ISSUE THREAD

**Issue by canbal** [cypress-io/cypress#7047]
### Current behavior:

When logged in to www.periscope.tv and tried to play a video, the network calls aren't intercepted by the route. When logged out, or if the domain doesn't contain a path, the route works as expected.

### Desired behavior:

On www.periscope.tv, for a logged in user, the network calls should still be intercepted by the router.

### Test code to reproduce

https://github.com/canbal/cypress-test-tiny/blob/master/cypress/integration/failing.js

In the attached code, you can change the value of the variable `condition` as `{0, 1, 2}` to test for failing/working conditions.

### Versions

Cypress Version 4.4.0 | Chrome 80 (reproducible in the embedded Electron browser as well)

**Comment by jennifer-shehane** [comment]
I'm not able to see this not working - when the test clicks the video, the video plays and the test passes. 

<img width="1463" alt="Screen Shot 2020-08-19 at 4 41 32 PM" src="https://user-images.githubusercontent.com/1271364/90628061-f25b2580-e242-11ea-8b24-e29228e4b799.png">

Please provide a complete failing example of the issue so we can look further into the issue and we will consider reopening.
