### ISSUE TITLE
Cypress Helper - Extreme CPU, RAM, Energy Usage Hours after Cypress is not Running

### ISSUE THREAD

**Issue by EfstathiadisD** [cypress-io/cypress#7050]
### Current Behavior:

I have seen an extreme amount of CPU and RAM Usage when Cypress is `RUNNING`. On top of that, even when I have closed Cypress for Hours, `cypress-helper` is not shutting down.

That makes my 15' MacBook Pro, ramp up the fans constantly and Energy Consumption is ridiculous.

---
The following numbers are after I have shut down Cypress for 4+ hour.
- [x] CPU: 75% -135% Regular Spikes
- [x] Memory: 1.3Gb - 2.0Gb
- [x] Energy: 25,9 In the last 12 Hours (`🚧 This is Ridiculous. Why??`)

### Desired behavior:
What I would consider acceptable would be the following:
- [ ] CPU: `When I close thee Cypress Runner (UI or CLI), this should not run`.
- [ ] Memory: `When I close the Cypress Runner (UI or CLI), I shouldn't have Memory used`.
- [ ] Energy: `When I close the Cypress Runner (UI or CLI), I shouldn't have my Laptop drained of battery`.

### Versions
I am using `Cypress` Vesion `3.7.0`. I tried with the latest version as well, but with no Luck. I am running on `Chrome`, and I am on MacOS Version `10.15.3`

> One note here. This happens on both UI and CLI usages of Cypress.

**Comment by francisu** [comment]
I have reproduced this, and run the profile debug tracing with these results below.

Steps are simple:

1) Clone this repo: https://github.com/francisu/test-material-ui
2) yarn install
3)  DEBUG=cypress:server:util:process_profiler yarn cypress open-ct

You don't even need to run any tests. Just let it sit for30 seconds or so and then exit by closing the window. Not that it will not exit (has to be control-c'ed). 


`
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                pids                 │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'Chrome'      │      5       │ '85115, 85130, 85128, 85126, 85125' │    12.6    │      12.6      │  396.02  │    396.02    │   396.02    │
  cypress:server:util:process_profiler │    1    │     'plugin'      │      1       │               '85096'               │   534.9    │     330.8      │  304.72  │    219.54    │   304.72    │
  cypress:server:util:process_profiler │    2    │     'cypress'     │      1       │               '85018'               │    67.4    │     74.63      │  197.08  │    154.73    │   197.08    │
  cypress:server:util:process_profiler │    3    │ 'electron-shared' │      2       │           '85028, 85022'            │     0      │       0        │  44.11   │    44.13     │    44.15    │
  cypress:server:util:process_profiler │    4    │      'other'      │      2       │           '85154, 85155'            │     0      │       0        │   2.14   │     2.1      │    2.14     │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      11      │                 '-'                 │   614.9    │     299.37     │  944.07  │    464.62    │   944.07    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +11s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                pids                 │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'Chrome'      │      5       │ '85115, 85130, 85128, 85126, 85125' │     0      │      6.3       │  375.52  │    385.77    │   396.02    │
  cypress:server:util:process_profiler │    1    │     'plugin'      │      1       │               '85096'               │   386.7    │     349.43     │  309.86  │    249.65    │   309.86    │
  cypress:server:util:process_profiler │    2    │     'cypress'     │      1       │               '85018'               │    62.4    │     71.58      │  197.25  │    165.36    │   197.25    │
  cypress:server:util:process_profiler │    3    │ 'electron-shared' │      2       │           '85028, 85022'            │     0      │       0        │   44.1   │    44.12     │    44.15    │
  cypress:server:util:process_profiler │    4    │      'other'      │      2       │           '85158, 85160'            │     0      │       0        │   2.1    │     2.1      │    2.14     │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      11      │                 '-'                 │   449.1    │     336.8      │  928.83  │    580.67    │   944.07    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +11s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                pids                 │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'plugin'      │      1       │               '85096'               │   338.6    │     346.73     │  309.88  │    264.7     │   309.88    │
  cypress:server:util:process_profiler │    1    │     'Chrome'      │      5       │ '85115, 85130, 85128, 85126, 85125' │     4      │      5.53      │  245.08  │    338.87    │   396.02    │
  cypress:server:util:process_profiler │    2    │     'cypress'     │      1       │               '85018'               │    75.8    │     72.42      │  197.39  │    171.77    │   197.39    │
  cypress:server:util:process_profiler │    3    │ 'electron-shared' │      2       │           '85028, 85022'            │     0      │       0        │  44.09   │    44.11     │    44.15    │
  cypress:server:util:process_profiler │    4    │      'other'      │      2       │           '85178, 85179'            │     0      │       0        │   2.11   │     2.1      │    2.14     │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      11      │                 '-'                 │   418.4    │     353.12     │  798.54  │    624.24    │   944.07    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +11s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬──────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │             pids             │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼──────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'plugin'      │      1       │           '85096'            │   400.2    │     357.42     │  309.88  │    273.74    │   309.88    │
  cypress:server:util:process_profiler │    1    │     'Chrome'      │      4       │ '85115, 85128, 85126, 85125' │     0      │      4.15      │  244.99  │    315.4     │   396.02    │
  cypress:server:util:process_profiler │    2    │     'cypress'     │      1       │           '85018'            │    76.2    │     73.05      │  198.08  │    176.15    │   198.08    │
  cypress:server:util:process_profiler │    3    │ 'electron-shared' │      2       │        '85028, 85022'        │     0      │       0        │  44.09   │    44.11     │    44.15    │
  cypress:server:util:process_profiler │    4    │      'other'      │      2       │        '85197, 85198'        │     0      │       0        │   2.08   │     2.1      │    2.14     │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      10      │             '-'              │   476.4    │     373.67     │  799.12  │    653.39    │   944.07    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴──────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +11s
^C
`
