### ISSUE TITLE
Feature Request configurable hooks for around request-middlewarw

### ISSUE THREAD

**Issue by matdumsa** [cypress-io/cypress#7053]
### Current behavior:

Developers needing specific authentication mechanism need to spin off their own proxy server, ie [cypress-ntlm-auth](https://github.com/bjowes/cypress-ntlm-auth/tree/master/src) which raises the complexity of custom authentication solution. 

### Desired behavior:

Cypress lets me configure intercept for http header and exposes the full request object to me. Some authentication mechanism like SigV4 require hashing of secrets w/ headers / body. This can be used moving forward by multiple custom authorization providers.

### Test code to reproduce
```js
Cypress.on("before-request", function(req, callback) {
  req.proxyToServerRequestOptions.headers['newHeader'] = getNewHeader(req.proxyToServerRequestOptions) 


  // note that this operation can result in service call / asynchronous processing to get a secret so the request should be sent when that callback is executed.
  callback();
});

```
### Versions

Version 4.4.0

**Comment by jennifer-shehane** [comment]
This will be possible after work for #687 is done, not exactly the way you've proposed, but it should be possible.

As a current workaround, you could likely install a Chrome extension on the Cypress browser that is capable of rewriting headers of all requests.

**Comment by jennifer-shehane** [comment]
Closing as this should now be possible.
