### ISSUE TITLE
Allow skipping snapshot tests in GUI

### ISSUE THREAD

**Issue by coderica** [cypress-io/cypress#7058]
### Current behavior:

The Cypress GUI is a really convenient way to run tests and can be faster than running them in the terminal. However, our team, like many I'm sure, use a docker image to create snapshots that can be reliable and stable both locally and in CI. For this reason, snapshots should not be generated by the GUI and always fail on existing ones.

### Desired behavior:

For the reasons stated above, it would be really nice to have a feature which allows me to skip all snapshot testing in the GUI without having to add `.skip` or just ignoring the tons of errors generated by failing snapshot tests.

**Comment by jennifer-shehane** [comment]
Cypress does not come with snapshot testing built into our product, so you may be using some 3rd party tool to compare snapshots? https://on.cypress.io/visual-testing

Cypress would have no knowledge of which tests are being used for snapshots and which are not. 

But, assuming your snapshots rely on `cy.screenshot()` in some manner, you could overwrite the `screenshot` command with something like shown in this example: https://on.cypress.io/browser#Screenshot-only-in-headless-browser This example would only take screenshots when running tests in a `headless` browser for example.
