### ISSUE TITLE
Cypress scrolls elements beyond what they're capable of

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#706]
Internally Cypress uses `element.scrollIntoView()` to deterministically ensure we scroll elements the same way before interacting with them.

This has an unfortunate side effect. The browser will sometimes scroll the offset parents beyond what they're capable of.

Here's a demonstration.

http://jsfiddle.net/LEqjm/258/

We could switch to using `element.scrollIntoView(false)` else we're going to have to write our own algorithm. The above example is way too simple. Elements could be nested in scrollable containers within other scrollable containers within the window which is scrolled.

The browser normally ensures every parent is scrolled appropriately, but we'd have to implement this logic ourselves.

/cc @paulfalgout (this is the issue you've been describing)

**Comment by paulfalgout** [comment]
False would be an improvement at least

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by paulfalgout** [comment]
I haven't used the project in a while that it was happening on.  I imagine it is still happening, but at most it was a minor annoyance on an edge case.  However I don't know what the downside would be to using `element.scrollIntoView(false)`
