### ISSUE TITLE
Proposal: detect that users have improperly chained commands at runtime and error

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#707]
We see new users to Cypress writing the following code:

```js
cy.visit('http://localhost:8080/creditApp/index')

var address = '123 Main Street'
var addressInput = cy.get('#address1')
console.log(addressInput)
addressInput.type(address)

var zip = cy.get('#zip')
zip.click()
addressInput.should('have.value', address)
```

Because Cypress code looks somewhat synchronous, users think they can just write synchronous code.

### Why you can't do this

1. Cypress commands run async and retry potentially many times. They cannot be assigned to a synchronous variable.
2. Cypress returns a "chainer" instance so we can understand the relationship of chained commands, especially for commands which can be used both to start a chain of commands, or chain off an existing one like `cy.contains()`
3. There is only ever a single concept of a "subject" that is mutated and flows forward with each subsequent command. Why?
4. Because the DOM and everything under the hood is mutable. Even if we did synchronize the relationship between chainers and their subject and enable you to pluck them out, these would go immediately stale and not do what you expect them to do.

## A short example 
This demonstrates exactly why we've built our API's this way. While it seems limiting - it is actually internally preventing flake that ravages modern test suites.

```js
// this illustrates the re-rendering
// of modern frameworks but with
// plain JS
$('#zip').on('click', () => {
  // remove the old address element
  $('#address1').remove()

  // "re-render" it with by inserting the same
  // element, but really its a new one
  $('<input id="address1" />').appendTo($('form'))
})

// hold reference to address chainer and eventual subject
var addressInput = cy.get('#address1').type(address)

// hold reference to zip chainer and eventual subject
var zip = cy.get('#zip').click()

addressInput.should('have.value', ...) // BOOM

// this will fail because this chainer points to the old
// <#address1> subject, which has been removed 
// from the DOM and will never be updated, ever.
//
// the user sees the address input 'change' on the screen
// and thinks Cypress is busted. Cypress continues to tell
// you the address has been removed from the DOM but
// you can clearly see it in the DOM - unbeknownst to you
// this is no longer the same element.
```

### How you can rewrite this

**Simple**
```js
var address = '123 Main Street'

cy.visit('http://localhost:8080/creditApp/index')
cy.get('#address1').type(address)
cy.get('#zip').click()
cy.get('#address1').should('have.value', address) // requery for the address, the old one may be gone
```

**Using Aliases**
```js
var address = '123 Main Street'

cy.visit('http://localhost:8080/creditApp/index')
cy.get('#address1').as('addr').type(address)
cy.get('#zip').click()
cy.get('@addr').should('have.value', address) // requery for the address, the old one may be gone
```

**Using closures**
```js
var address = '123 Main Street'

cy.visit('http://localhost:8080/creditApp/index')
cy.get('#address1').type(address).then(($address) => {
  cy.get('#zip').click()

  // this will only work if $address is not rerendered and has
  // not been removed from the DOM - else this will fail
  // which is why we suggest just requerying for it as 
  // demonstrated above
  cy.wrap($address).should('have.value', address)
```

## The Proposal moving forward

Cypress internally knows and understands which command is current and how it is chained.

It could detect that if you "broke" the chain and tried to chain off of a previously finished chain of commands it would error.

```js
var address = '123 Main Street'

// chainer1 (subject is window)
cy.visit('http://localhost:8080/creditApp/index') 

// chainer2 (subject is <#address1>)
var addressInput = cy.get('#address1') 

// still chainer2 - this would not break since the `type`
// is the next command and its attached to the previous
// subject is still <#address1>
addressInput.type(address) 

// chainer3 (subject is now <#zip>)
var zip = cy.get('#zip')

// still chainer3 - same principle as above
zip.click()

addressInput.should('have.value', address) // BOOM

// we can now give you a great error message. Why? 
// because you've taken chainer2 and added a 
// new command to it - cy.should()
// we can detect this because the last chainer
// to run was chainer3
//
// the internals of cypress only carry 1 subject forward
// at a time (because everything in the DOM is mutable)
// and what actually happens is that the .should('have.value')
// would receive the subject of <#zip> and not <#address>
//
// chaining is all about relationships, but subjects simply 
// flow from one command to the next because we don't
// enable you to 'break up' chains of commands

```

**Comment by brian-mann** [comment]
## Alternatively

It is possible for us to actually make the above work by removing the concept of a single 'global' subject and instead of using the current one, we'd always flow the subject from the chainer into the subsequent command.

That **would** work but it would come at a cost - that you are essentially trying to write synchronous code that mostly does what you expect, but it doesn't work the same. We may be robbing peter to pay paul by supporting this.

### Upsides for changing our API's to support this
- Cypress is less intimidating to start
- Users could use primitives and non mutable objects successfully
- Code works *about* the way it works in synchronous land
- It pairs better with how native Promises work
- We error only when the subject becomes stale
- Errors may become more precise but its going to be a lot of work

For errors to be better we'd not only have to detect that the element became stale (which is easy we already do that) but we'd likely also need to check to see if you're chaining off of a 'broken chain' and that's *likely* the reason its not working the way you expect.

### Downsides for changing it
- You're still using it wrong
- It's a completely unnecessary pattern
- You're potentially creating opportunities for flake to leak in
- Code becomes seriously ugly and wayyyy less readable

## An Example

```js
const str = cy.wrap('foobarbaz')

cy.get('element')

str.then((str) => {
  // str is foobarbaz and is not mutable
  // there's no harm in this use case 
  // because its impossible for the string
  // to change
})
```

**Comment by avanslaars** [comment]
> Users would likely assume values really are synchronous and write busted code like this

I think this is the strongest argument against doing this.

I think education about how Cypress works and the way tests _should_ be written is a better approach than trying to bend and warp the code to make asynchronous code fit a synchronous mindset.

I think this will just lead to more flake, edge cases and frustration in the long run.

learning not to store things in a `var` and to just use an alias is far better experience than dealing with the fact that a synchronous looking approach works sometimes and not other times. One of the big strengths of Cypress is the lack of flake in tests, introducing more potential for this goes against one of the main goals of the project.

The trade-off (if you can really call it that) to get the reliability and readability that Cypress provides, is using it the way it's intended. I don’t think that’s too much to ask in return for the value you get.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
