### ISSUE TITLE
Cypress randomly failing with `exit event with signal SIGSEGV`

### ISSUE THREAD

**Issue by hindsc52** [cypress-io/cypress#7073]
### Current behavior:

Cypress exiting with the error

```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
```

Cypress generally exits with this error when the test suite is nearing completion or has finished, The test report shows all tests have passed

### Versions

Cypress: 4.4.0,
Operating System: Ubuntu Linux - 18.04

**Comment by jennifer-shehane** [comment]
Duplicate of #7048

**Comment by Onkar1992** [comment]
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Platform: darwin (20.1.0)
Cypress Version: 5.6.0
 
Cypress is failing on macOS Big Sur 11.0.1

**Comment by jennifer-shehane** [comment]
@Onkar1992 Please see other SIG errors for similar issues: https://github.com/cypress-io/cypress/labels/topic%3A%20SIG%20errors 

There is also an issue for Big Sur. It would be helpful if you could provide an example there: https://github.com/cypress-io/cypress/issues/9195
