### ISSUE TITLE
Cypress does not recognize exported env vars at the CLI

### ISSUE THREAD

**Issue by adokania** [cypress-io/cypress#708]
- Operating System: mac os 
- Cypress Version: 0.19.4
- Browser Version: 

### Is this a Feature or Bug?
Bug 

### Current behavior:
The exported env vars are not recognized when running cypress through cli. I get an error that reads: `Error reading from : <file path >/cypress.env.json`

### How to reproduce:
`Export vars you need`
`cypress run <file name>`
you receive an error
#### Test code:

```js

```

**Comment by jennifer-shehane** [comment]
`cypress run` does not accept the spec file as a default argument, it optionally accepts the project directory. This is why it's trying to read the `cypress.env.json` file from your JavaScript spec file (because it thinks this is your project path). 

What you want: `cypress run --spec <file name>`
