### ISSUE TITLE
How to stub OData queries?

### ISSUE THREAD

**Issue by jberthe** [cypress-io/cypress#7080]
### Current behavior:

I would like to stub OData queries with `cy.route()`

In some case, the query is send with **$batch** option in which all the requests are embedded inside the request payload. 

If I understood well, the stubbing process start when we set an URL + a response to the `cy.route()`.

### Desired behavior:

What I would expect, is, in the `onRequest` callback function, having something to filter which request in the payload we want to stub.

For instance, in a **/$batch** request you can have 2 payload requests :
```

> --batch_7df2-992d-537d
> Content-Type: application/http
> Content-Transfer-Encoding: binary
> 
> GET SoftwareComponents(Generate='0002',Id='0004')/to_packages?$skip=0&$top=10&$orderby=IsFrentEnd%20asc&$select=DevPackage%2cFcDevPackage%2cIsFrentEnd%2cFcIsFrentEnd%2cGenerate%2cScId&$inlinecount=allpages HTTP/1.1
> sap-cancel-on-close: true
> sap-contextid-accept: header
> Accept: application/json
> Accept-Language: fr-FR
> DataServiceVersion: 2.0
> MaxDataServiceVersion: 2.0
> x-csrf-token: uDm4KNv7nmdWIaO5GfIGNw==
> 
> 
> --batch_7df2-992d-537d
> Content-Type: application/http
> Content-Transfer-Encoding: binary
> 
> GET SoftwareComponents(Generate='0002',Id='0004')/to_roles?$skip=0&$top=10&$select=Role%2cScId%2cGenerate&$inlinecount=allpages HTTP/1.1
> sap-cancel-on-close: true
> sap-contextid-accept: header
> Accept: application/json
> Accept-Language: fr-FR
> DataServiceVersion: 2.0
> MaxDataServiceVersion: 2.0
> x-csrf-token: uDm4KNv7nmdWIaO5GfIGNw==
> 
> 
> --batch_7df2-992d-537d--

```
How to stub the second GET query but not the second?

### Versions
Version 4.4.0

**Comment by jennifer-shehane** [comment]
This is not currently supported. This may be possible after work for #687 is done.

**Comment by flotwig** [comment]
Please try using [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept), it has full support for dynamic request stubbing. Closing since this is now possible with #687.
