### ISSUE TITLE
cypress 4.4.0 install error on Teamcity

### ISSUE THREAD

**Issue by huantaoliu** [cypress-io/cypress#7081]
### Current behavior:
Error on Teamcity: (local machine looks fine)
 

### Test code to reproduce

>  Installing Cypress (version: 4.4.0)
16:22:37
  
16:22:37
   [?25l[16:22:37]  Downloading Cypress     [started]
16:23:02
  [16:23:02]  Downloading Cypress     [completed]
16:23:02
  [16:23:02]  Unzipping Cypress       [started]
16:23:02
  /usr/local/TeamCity/buildAgent/work/c9f3a9b03e88b7fc/node_modules/cypress/lib/tasks/unzip.js:130
16:23:02
            sp.stdout.on('data', function (data) {
16:23:02
                      ^
16:23:02
  
16:23:02
  TypeError: Cannot read property 'on' of undefined
16:23:02
      at unzipWithUnzipTool (/usr/local/TeamCity/buildAgent/work/c9f3a9b03e88b7fc/node_modules/cypress/lib/tasks/unzip.js:130:21)
16:23:02
      at /usr/local/TeamCity/buildAgent/work/c9f3a9b03e88b7fc/node_modules/cypress/lib/tasks/unzip.js:187:20
16:23:02
      at /usr/local/TeamCity/buildAgent/work/c9f3a9b03e88b7fc/node_modules/yauzl/index.js:37:7
16:23:02
      at /usr/local/TeamCity/buildAgent/work/c9f3a9b03e88b7fc/node_modules/yauzl/index.js:141:16
16:23:02
      at /usr/local/TeamCity/buildAgent/work/c9f3a9b03e88b7fc/node_modules/yauzl/index.js:631:5
16:23:02
      at /usr/local/TeamCity/buildAgent/work/c9f3a9b03e88b7fc/node_modules/fd-slicer/index.js:32:7
16:23:02
      at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
16:23:05
  npm WARN @activia/cm@51.0.0-rc-1 No repository field.
16:23:05
  npm WARN The package @ngneat/transloco is included as both a dev and production dependency.
16:23:05
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/webpack-dev-server/node_modules/fsevents):
16:23:05
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any

### Versions
4.4.0

**Comment by xshyne88** [comment]
Same issue, what was the fix?

**Comment by huantaoliu** [comment]
my problem was that node version was too old on Teamcity
