### ISSUE TITLE
Cannot read property 'split' of undefined (works 4.3.0, fails 4.4.0)

### ISSUE THREAD

**Issue by grivard** [cypress-io/cypress#7082]
### Current behavior:

The very first thing I do in every test is to visit the `baseUrl` (before even logging in), use `cy.get()` to extract a string, and then while chained off of the `cy.get` I send that string to a function.  If I do `cy.log` (and only that) within that function, the string is logged correctly.  But that function calls `.split` on that parameter and that line fails because, it says, the parameter is undefined.

This worked in 4.3.0, exact same code.

### Desired behavior:

`.split` works when chained like in 4.3.0.

### Test code to reproduce

https://github.com/grivard/cypress-test-tiny

I changed two files from the originals created by the fork.
`spec.js` and `commands.js`

The bug manifests in `commands.js`, line 37.  Toggling between `true (fail)` and `false (succeed)` on line 31 toggles the bug on and off.  This stripped down version works in 4.3.0 but not in 4.4.0.  

You will not be able to access our `baseUrl`, but I included a comment with an example of the string that would be returned.

### Versions

Windows 10 Pro 1903, Chrome 81.0.4044.113 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
This is fixed in 4.4.1. Please update to the [current version of Cypress](https://on.cypress.io/changelog).
