### ISSUE TITLE
cypress verify gets confused by extra debug output

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#709]
If we run `DEBUG=* cypress verify` the spawned process outputs extra debug output, which confused the verify because it tries to match the output exactly.
Should instead match one of the output lines. Something like this should find the expected value `221`

```
DEBUG.....
DEBUG...
221
DEBUG....
```

**Comment by brian-mann** [comment]
The code for this is merged, but it has not been released yet.

**Comment by brian-mann** [comment]
Fixed in [`0.20.2`](https://docs.cypress.io/guides/references/changelog.html#0-20-3).
