### ISSUE TITLE
Cypress client don't show my test files

### ISSUE THREAD

**Issue by julianmendonca** [cypress-io/cypress#7099]
### Current behavior:

I installed cypress manually downloading the .zip file, i unzip it and opened it.
I opened a project folder wich had al the standar examples one and one test file that i created.
When i open the directory it shows all examples exe

![image](https://user-images.githubusercontent.com/31936866/79932440-e04bb080-8423-11ea-85a2-613c115189ea.png)

![image](https://user-images.githubusercontent.com/31936866/79932450-e8a3eb80-8423-11ea-9e40-a957eeda98a9.png)

The path is the correct one

When i drag the file to the client it shows:

![image](https://user-images.githubusercontent.com/31936866/79932663-6831ba80-8424-11ea-852d-27cdcb6e2d77.png)

### Desired behavior:

Show my test files

### Test code to reproduce

my test file is this:

```js
import "cypress-localstorage-commands";

describe('Gondolas en Musimundo', function () {

    Cypress.on('uncaught:exception', (err, runnable) => {
        return false
    })

    it('Trae la gondola en home', function () {
        cy.visit('https://www.musimundo.com/');
        cy.wait(8000);
        cy.get('.braindw_owl-carousel .owl-stage-outer .owl-stage').should('be.visible');
    })

    it('Trae la gondola en categoria', function () {
        cy.get('#NotebooksMainBarComponent').click();
        cy.wait(8000);
        cy.get('#carousel-braindw_1').should('be.visible');
    })

    it('Trae la gondola de producto', function () {
        cy.get('.mus-product-box-out a').first().click();
        cy.wait(8000);
        cy.get('#braindw_container').should('be.visible');

    })
})

describe('Gondolas en Arredo', function () {

    Cypress.on('uncaught:exception', (err, runnable) => {
        return false
    })

    it('Trae la gondola en home', function () {
        cy.visit('https://www.arredo.com.ar/');
        cy.wait(8000);
        cy.get('#main_braindw_slider').should('be.visible');
    })

    it('Trae la gondola en categoria', function () {
        cy.get('.boton-slide').first().click();
        cy.wait(8000);
        cy.get('.braindw_bigbannercategoria').contains('Agregar');
    })

    it('Trae la gondola de producto', function () {
        cy.get('.product-link').first().click();
        cy.wait(8000);
        cy.get('._braindw_slider').first().contains('AGREGAR');

    })
})

describe('Gondolas en Locatel', function () {

    Cypress.on('uncaught:exception', (err, runnable) => {
        return false
    })


    it('Trae la gondola en home', function () {
        cy.visit('https://www.locatelcolombia.com/');
        cy.wait(8000);
        cy.get('#braindw_Gondola').contains('AGREGAR');
    })

    it('Trae la gondola en categoria', function () {
        cy.visit('https://www.locatelcolombia.com/drogueria/vitaminas?&utmi_p=_drogueria&utmi_pc=Html&utmi_cp=drogueria');
        cy.wait(8000);
        cy.get('#braindw_Gondola').contains('AGREGAR')
    })

    it('Trae la gondola de producto', function () {
        cy.get('.product-name').first().click();
        cy.wait(8000);
        cy.get('.related-products').contains('Agregar');

    })
})
```

**Comment by jennifer-shehane** [comment]
You need to add the project root directory to open (the one typically containing your `package.json` file and all your code), not the directory within `cypress/integration`. Your project should look something like this:

```
📁 my-app
- 📁 cypress
 - 📁 integration
   - 📁 examples
   - 📄 actions.spec
- 📁 src
- 📄 package.json
- 📄 cypress.json
```

In this example you would drag the `my-app` directory into Cypress to open the project - *never* the `cypress` folder or the `integration` folder and *never* any files. It requires a directory.

**Comment by conversayShawn** [comment]
**Update if you are experiencing this issue in v10.0.0+:**

In Cypress versions [10.0.0+](https://docs.cypress.io/guides/references/changelog#10-0-0), the default test location for end-to-end testing has been moved to `cypress/e2e` folder: https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0
 
That being said, I would like to provide two options:

- The easiest is to move your test spec to the `cypress/e2e` folder where the examples specs are located
- You also have the option of leaving your spec where it is, however, you will need to update the default `specPattern` in your `cypress.config.js`: https://docs.cypress.io/guides/references/configuration#e2e

If you are still experiencing this issue, kindly open a new GitHub issue
