### ISSUE TITLE
Issue with 3.2.1 upgrade

### ISSUE THREAD

**Issue by GregGriffith86** [cypress-io/cypress#710]
- Operating System: 
- Cypress Version: 3.2.1
- Browser Version: Chrome 62.0.3202.38 (Official Build) beta (64-bit)

### Current behavior:
When logging into our cypress website, we are getting the message "The backend processes for setting up test and peforming measure calculations are not running. Please refer to the Cypress Installation manual for instructions on starting the processes." I see this message and cannot find what services it is referencing. I also cannot login with any of the accounts we've used in the past. 

### Desired behavior:
Ability to start the services to get this to work

### How to reproduce:
Unable to provide these steps as we upgraded to 3.2.1 from 3.1. We did run into issue with our hdd space being full during the upgrade which caused issues. Unsure if this is releated.

#### Test code:

```js

```

**Comment by brian-mann** [comment]
`3.2.1` is not a version we have ever released, and those errors messages are not something we've written. Are you sure we're talking about the same Cypress project? We are https://cypress.io - maybe you're using a different product

**Comment by GregGriffith86** [comment]
Sorry Brian, This is for project cypress. I thought I had placed this in that forum. Sorry for the confusion.
