### ISSUE TITLE
'Run all specs' only runs specs of a single file

### ISSUE THREAD

**Issue by NikhilNanjappa** [cypress-io/cypress#7109]
### Current behavior:

When I fire the `cypress open` command (locally installed) and click on the "Run all specs" button, I expect all my integration tests to run (all the tests shown in image1) but what actually happens is that - it only runs tests of one file (highlighted in image1 .ie. only tests under `offer-full.js` run)

> **Important: It initially used to run all the specs before. That changed when one of the days I selected the `offer-full.js` file to run only its tests. Since then, whenever I click the "Run all specs", it always fires tests of that file only. I've already tried clearing cypress cache but that didn't help.**

<img width="797" alt="cypress-image1" src="https://user-images.githubusercontent.com/5576981/80000674-59dfaf00-84b5-11ea-87f8-b6e0a3b9cf70.png">

Below image shows the output after I click "Run all specs":

![cypress-image2](https://user-images.githubusercontent.com/5576981/80000691-5ea46300-84b5-11ea-8d3f-eb509340b3a3.png)

### Desired behavior:

When I click the "Run all specs" button, I would expect all the specs under the `cypress` folder run. In other words all the tests shown in image1.

### Versions

Cypress: 3.6.1
OS: macOS Cataline 10.15.1
Browser: Chrome 80.0.3987.163 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
I see that the Cypress page is navigating to the `__all` route, which is the correct route for running all specs. 

Have you verified that there is not an `.only` defined within the `offer-full.js` file. This would cause only those specs to run. 

I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by NikhilNanjappa** [comment]
Thanks @jennifer-shehane for the reply. Will check on the points you mentioned and update this comment.

But wouldn't `.only` also run only those specs on `cypress run` too ? .ie. `cypress run` runs all but `cypress open` runs only few specs.

**Comment by jennifer-shehane** [comment]
`cypress open` with 'run all specs' basically combines all the specfiles into one big one and runs it - so an only will only run one spec. 

`cypress run` will run each specfile in isolation, so it would run all the tests in all spec files and then the one specfile that has the only - it would run that one specfile's .only test.
