### ISSUE TITLE
I cannot run all scenarios located in different packages

### ISSUE THREAD

**Issue by eGoudi** [cypress-io/cypress#7119]
Hi,

I have two Folders : `01administrationTask` , `02AccessManagement`

The next command : `npx cypress run` is supposed to run all scenarios located in Folders 

`01administrationTask`  and  `02AccessManagement`.

 I get an error in 02AccessManagement (ERROR ABORT LOADING) : 

```
 Running:  02AccessManagement/01TestCaseprofileAdminRightAccess.feature                   (2 of 30)
ERR_ABORTED (-3) loading "Https/OUrWebsite?login ......."
```

**Comment by eGoudi** [comment]
after running  npx cypress run  I get the same result : 

MBP-y$ npx cypress run

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.8.2                                                                              │
  │ Browser:    Electron 78 (headless)                                                             │
  │ Specs:      30 found (01AdministrationTask/administrationtask.feature, 02AccessManagement/01Te │
  │             stCaseprofileAdminRightAccess.feature, 02AccessManagement/02TestCaseprofileIssuerR │
  │             ightAccess.feature, 02AccessManagement/03TestCaseprofileOriginatorRIghtAccess.feat │
  │             ure, 02Acce...)                                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                   
  Running:  01AdministrationTask/administrationtask.feature                                (1 of 30)


  Administration Tasks
    ✓ Admin can create a Legal Entity (LEI) and link its"admin_1 which is "admin_1"  , "Entity_99" (3598ms)
    ✓ Fill LEI Form (7748ms)
    ✓ Admin_1 can update a Legal Entity (LEI) which is the "investor_1" (2047ms)
    ✓ Admin_1 can delete a LEI (2031ms)
    ✓ Admin_1 can create an user , update and delete (4596ms)
    1) Check Edit


  5 passing (25s)
  1 failing

  1) Administration Tasks Check Edit:
     CypressError: Timed out retrying: Expected to find element: 'select[name="RoleAAA *"]', but never found it.
      at Object.cypressErr (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:86206:11)
      at Object.throwErr (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:86161:18)
      at Object.throwErrByPath (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:86193:17)
      at retry (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:76849:16)
      at onFailFn (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:65634:16)
      at tryCatcher (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:120669:23)
      at Promise._settlePromiseFromHandler (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:118605:31)
      at Promise._settlePromise (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:118662:18)
      at Promise._settlePromise0 (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:118707:10)
      at Promise._settlePromises (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:118782:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:115394:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:115404:10)
      at Async.drainQueues (https://www.staging.forgecapitalmarkets.com/__cypress/runner/cypress_runner.js:115278:14)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        6                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     24 seconds                                                                       │
  │ Spec Ran:     01AdministrationTask/administrationtask.feature                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  cypress/screenshots/01AdministrationTask/administrationtask.feature/Administrati     (1280x720)
     on Tasks -- Check Edit (failed).png                                                            


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                    
  -  Finished processing: cypress/videos/01AdministrationTask/administrationtask.feat    (2 seconds)
                          ure.mp4                                                                  


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                   
  Running:  02AccessManagement/01TestCaseprofileAdminRightAccess.feature                   (2 of 30)
ERR_ABORTED (-3) loading 'https://forgecapitalmarkets.eu.auth0.com/authorize?client_id=Jpb6B_MzE8m01vP2dOpQ9maVNMk9XBVa&response_type=token%20id_token&redirect_uri=https%3A%2F%2Fwww.staging.forgecapitalmarkets.com%2Fcallback%3FauthMethod%3Dauth0&scope=openid%20email%20profile%20read%3Amessages&audience=https%3A%2F%2Fforgecapitalmarkets.eu.auth0.com%2Fapi%2Fv2%2F&state=dGE0GHbtybGeaisQYQZxXHGRN7QVaSxr&nonce=BF4FYiUaSPu~mEtg5Ff7OOcPuJFJT0rh&auth0Client=eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOS4xMi4yIn0%3D'
Error: ERR_ABORTED (-3) loading 'https://forgecapitalmarkets.eu.auth0.com/authorize?client_id=Jpb6B_MzE8m01vP2dOpQ9maVNMk9XBVa&response_type=token%20id_token&redirect_uri=https%3A%2F%2Fwww.staging.forgecapitalmarkets.com%2Fcallback%3FauthMethod%3Dauth0&scope=openid%20email%20profile%20read%3Amessages&audience=https%3A%2F%2Fforgecapitalmarkets.eu.auth0.com%2Fapi%2Fv2%2F&state=dGE0GHbtybGeaisQYQZxXHGRN7QVaSxr&nonce=BF4FYiUaSPu~mEtg5Ff7OOcPuJFJT0rh&auth0Client=eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOS4xMi4yIn0%3D'
    at rejectAndCleanup (electron/js2c/browser_init.js:5881:21)
    at WebContents.navigationListener (electron/js2c/browser_init.js:5908:20)
    at WebContents.emit (events.js:203:13)

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
