### ISSUE TITLE
Set-Cookie response header is not present in route

### ISSUE THREAD

**Issue by Kimserey** [cypress-io/cypress#7131]
I am trying to stub a `/logout` route which would normally clear the cookies by providing a `set-cookie` header in the response.

So I am trying to stub with the following route:

```js
cy.route({
  method: 'POST',
  url: '/api/auth/logout',
  status: 200,
  response: { logout: true },
  headers: {
    'set-cookie': 'csrf_access_token='
  }
});
```
### Current behavior:

From the console, I don't see the cookie, I can only see the following headers:

```
connection: "keep-alive"
content-length: "15"
content-type: "application/json; charset=utf-8"
date: "Fri, 24 Apr 2020 12:36:53 GMT"
vary: "Accept-Encoding"
```

### Desired behavior:

I expected to see the header as:

```
set-cookie: "csrf_access_token="
```

### Test code to reproduce

[GitHub Repository](https://github.com/Kimserey/cypress-test-issue/blob/upgrade-4/cypress/integration/examples/querying.spec.js#L18)

- Branch `upgrade-4`,
- Test in `integration/examples/querying.spec.js`.

### Versions

- Cypress version `4.3.0`
- Running on Chrome 81

**Comment by Kimserey** [comment]
I've accidentally submitted without finishing to complete the description.
I'll reopen once I've completed the description.

Thank you.

**Comment by jennifer-shehane** [comment]
I do see the `set-cookie` header in the response in the DevTools for the `logout` request from the example you provided in 4.3.0.

<img width="1080" alt="Screen Shot 2020-04-27 at 4 38 58 PM" src="https://user-images.githubusercontent.com/1271364/80360620-9fc9b800-88a5-11ea-8ed0-2f9409e5f3eb.png">

**Comment by Kimserey** [comment]
Ah indeed, no wonder it was actually working.

The part that confused me is when clicking on the route from the Cypress Chrome test runner, it will print it in the debugger console and the header will not be inside.

Clicking from here:

<img width="589" alt="Screenshot 2020-04-28 at 15 42 33" src="https://user-images.githubusercontent.com/2263777/80501071-e7fcdf00-8966-11ea-8cb2-e70765ff6e94.png">

The header is missing in the response:

<img width="574" alt="Screenshot 2020-04-28 at 15 42 22" src="https://user-images.githubusercontent.com/2263777/80501087-ec28fc80-8966-11ea-9c71-a0d842f7c762.png">

**Comment by jennifer-shehane** [comment]
I'm not sure why that's not included in the `xhr.response` printed in the console. Code is here to just print `xhr.response`. 

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/xhr.js#L129:L129
