### ISSUE TITLE
Incorrect document.domain for subdomains

### ISSUE THREAD

**Issue by manevpe** [cypress-io/cypress#7132]
### Current behavior:

We are using different sub-domain for different testing environments - example:
```
ci1.mycompany.com
stg1.mycompany.com
```
etc.

When you start the browser from cypress and navigate to our web app on such a subdomain, open DevTools Console and execute the JavaScript "document.domain". We get only the domain name, without the sub-domain - ex. "mycompany.com".

Try the same thing from a normal browser, outside of cypress - we get a correct result "stg1.mycompany.com"

### Desired behavior:

`document.domain` to show the correct value, including the sub-domain.

### Test code to reproduce
```js
cy.visit('https://<sundomain>.<domain>.<top-domain>/')
console.log(document.domain)
```

Example:
```js
cy.visit('https://maps.google.com/')
console.log(document.domain);
```

### Versions
Cypress 4.4.1
Windows 10
Chrome 81 / Firefox 72

Why is this a blocker issue for us?

We use a pretty old jsp library for CSRF protection: https://github.com/pstibrany/OWASP-CSRFGuard

Inside, it has a JS that checks whether the web app is loaded from the correct domain, in order to prevent hijacking attacks - something like (simplified for better readability):

```js
if(document.domain == "<jsp_dynamically_generated_string_of_the_full_domain_name>")) {
    // Handle CSRF tokens
} else {
    alert("OWASP CSRFGuard JavaScript was included from within an unauthorized domain!");
}
```

When we load the app in cypress, we get this alert with this error.

This is currently blocking us from using cypress to test out app.

Turning off CSRF check on the server, fixes the issue and the app loads normally, but we'd rather not do that.

**Comment by Songyu-Wang** [comment]
I had a similar issue before, my workaround is to manually modify the cookies in test code

**Comment by manevpe** [comment]
Thanks @Songyu-Wang - unfortunately in this case the document.domain is not a mutable property.

**Comment by Songyu-Wang** [comment]
@manevpe Oh sorry, I didn't realize the check is on the client-side... probably should read more carefully...

**Comment by Songyu-Wang** [comment]
but if that is the case, cant you do some hack around to bypass this check?

**Comment by jennifer-shehane** [comment]
Duplicate of #2193 

See this explanation for workarounds to this issue https://github.com/cypress-io/cypress/issues/2193#issuecomment-525037125
