### ISSUE TITLE
Continuing problems with cy.request and cookies

### ISSUE THREAD

**Issue by VesterDe** [cypress-io/cypress#7133]
### Current behavior:

I originally commentend on the now closed issues #6628 that I was getting the same problem, but only in CI, and only about 5% of of time.

This problem has not gone away, and we are still seeing cy.request have problems settings cookies, because (I can only assume) or login request redirects several times before it is finished. 

### Desired behavior:

For cookies to always set correctly on request calls.

### Test code to reproduce

Now, I can't provide test code because of how rare the issue is, and becase It's an enterprise app that I can't disect and take out just a small part of the code from.

I do however have verbose debug logs from several occurences of this bug, where in each run a different test file failed for the same reason, and all others worked. I can redact those a bit and sent them over to you are interested in following up on this.

I can also jump on a call to try and explain what we are seeing.

For now we have reverted to logging in visually, by going through the UI, and this has made the e2e part of our testing battery much slower than others, since logging in adds 10 seconds to each file.
### Versions

Cypress 3.5.X - 4.4.X.
AWS Codebuild
Chrome

**Comment by flotwig** [comment]
Hey @VesterDe, to make sure I understand, you're having an issue where cookies that should have been set in the browser by a `cy.request` aren't being sent along with a subsequent `cy.visit` command, but only ~5% of the time?

Can you describe the redirect flow that you're using `cy.request` for? We've had issues with redirects in the past that have been fixed, but there could be an edge case in your setup.

Please share the debug logs and let me know which cookie to look for that isn't being set.

**Comment by VesterDe** [comment]
Hey @flotwig 

Here's what we're doing:

We want to login via cy.request() instead of cy.visit(), which proved to be about 90% faster.

This means sendings a username and password via post to our login route. The redirects that happen as a result are (and would be the same via a cy.visit() and submit path) like this:

- The original post request 304s to some generic /home route, that is only available to logged in users.
- That route figures out which company the user belongs to, and 304s to a more specific /company/:id/home route.

The logged in cookie should be set, and is in the header of the initial 304, but somehow the request to where 304 was pointing sometimes (this is the 5% chance) has no such cookie set. It smells like a race condition, but I'm not really qualified to interpret the logs.

I'll work on annotating the logs a bit for readability, could you provide an email I could send them to?

**Comment by flotwig** [comment]
Ok, so the flow is like this, with the issue happening after the first redirect?

1. POST username+password to `/login`
2. 304 to `/home` (~5% of the time, there is no Cookie header sent with this request and it fails here)
3. 304 to `/company/:id/home`
4. 200 OK

Are all of these URLs on the same domain?

You can send the logs to the email on my GitHub profile, or you can attach a txt file to your comment here.

**Comment by VesterDe** [comment]
@flotwig Yes, that's about it.

I'll send the logs over.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
