### ISSUE TITLE
Cypress does not pick the string value from Cypress command

### ISSUE THREAD

**Issue by gitanshumalhotra** [cypress-io/cypress#7134]
I have a custom cypress command like:

**In commands.js**
```js
Cypress.Commands.add('newCommand', (text) => { 
  cy.log(text) // Gives output as "SomeValue"
  cy.get('.some-random-class:contains(text)') //Gives output as "('.some-random-class:contains(text))
});
```

**In spec file**
```js
cy.newCommand("SomeValue")
```

The output of `cy.log` is `"SomeValue"`

But inside the command, it still shows as `"cy.get('.some-random-class:contains(text)')`  while executing. The keyword text should be replaced by actual value.

**Comment by Songyu-Wang** [comment]
Because you input `.some-random-class:contains(text)` as a string instead of interpolated string?

**Comment by jennifer-shehane** [comment]
`text` is a string, not the value of `text`. 

```js
Cypress.Commands.add('newCommand', (text) => { 
  // evaluate text - don't just look for 'contains(text)`
  cy.get(`.some-random-class:contains(${text})`)
});
```
