### ISSUE TITLE
Typings for cy.task when chaining with .then

### ISSUE THREAD

**Issue by kevin-wittmer** [cypress-io/cypress#7136]
### Current behavior:
The function passed to `.then` after calling `.task` must have its parameter typed as `undefined` when writing the code in Typescript. Ideally, the function's parameter would match the return type of the task. As a workaround, the function's parameter can be explicitly marked as `any` then dynamically cast to the desired type, but this goes against Typescript best practices.

### Desired behavior:
There are probably a few different ways of accomplishing this, but one that comes to mind is:
```js
// In this example, val would have type MyType
cy.task<MyType>("task").then((val) => ...);
```

### Test code to reproduce
```js
// In this example, val is typed as undefined
cy.task("task").then((val) => ...);
```

### Versions
Cypress 4.4.0

**Comment by calummoore** [comment]
In the mean time you can overwrite the type to:

```typescript
/// <reference types="cypress" />

declare global {
  namespace Cypress {
    interface Chainable<Subject = any> {
      task<T>(event: string, arg?: any, options?: Partial<Loggable & Timeoutable>): Chainable<T>
    }
  }
}

export {}

```
