### ISSUE TITLE
Var lost in different tests

### ISSUE THREAD

**Issue by karlhan628** [cypress-io/cypress#7142]
### Current behavior:

The var is lost in the second test after cy.visit()

### Desired behavior:

The var should be saved. 

### Test code to reproduce

```js
describe('', () => {
  var url;

  it('', () => {
    cy.visit(url1).then(() => { get url2 }
    url = url2;
  })
  
  it('', () => {
    cy.log(url). // this works, I can see the url
    cy.visit(url) // error in this step, said url is null
  })
})
```

**Comment by jennifer-shehane** [comment]
Please follow this workaround: https://on.cypress.io/task#Save-a-variable-across-non-same-origin-URL-visits
