### ISSUE TITLE
Changing currentTime of HTMLVideoElement in Cypress always sets to 0 (Chrome/Electron)

### ISSUE THREAD

**Issue by alessiojorge** [cypress-io/cypress#7150]
### Current behavior:

In the application I am currently working on, we allow users to change the current time of a video according to a keyframe, which they can click on. Each keyframe has a corresponding timestamp, which then with a click event will set the video elements `currentTime` to this timestamp (in seconds)

I can confirm that this feature works in Firefox/Chrome browsers. 

We are using Cypress to ensure that when clicking on a keyframe, the video players `currentTime` is set correctly in the UI. 

However when trying to change the `currentTime` inside of Chrome/Electron within the Cypress environment the `currentTime` is always set to `0`. There doesn't appear to be any issues when running Cypress with Firefox. 

### Desired behavior:

When setting the `currentTime` property of a `HTMLVideoElement`. It should be set correctly, and not always to `0`. 

### Test code to reproduce

Unfortunately due to the project not being open-source, I cannot post screenshots, or code directly from the project. 

- The test should be reproducible by loading any MP4 into a html video element (I tried with a variety of different test videos found [here](https://gist.github.com/jsturgis/3b19447b304616f18657)
- Setting the `currentTime` with an on `click` event, should always set `currentTime = 0` even though the value > 0. 

Here is a Typescript code snippet of the function we're calling: 

```ts
const setTime = ({ player, begin }: { player: HTMLVideoElement, begin: number }) => {
    if (player && begin != null) {
      player.currentTime = begin;
    }
  }
```

### Versions

Cypress v4.4.1
Browsers: Chrome/Electron

**Comment by jennifer-shehane** [comment]
Can you provide an example against an HTML file with Cypress tests. Like an `index.html` containing the video element + `spec.js` file that calls `cy.visit('index.html`)` to test the video element with the calls your making. 

For me to reproduce this out of the information provided, I'll be making a *lot* of assumptions about your test code and the html element which likely won't result in the same behavior you're seeing. Thanks!

**Comment by theinfoarchitect** [comment]
Hi Jennifer - thanks for the response. 

Here is the **index.html** file: 

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>title</title>
  </head>
  <body>
    <div>
      <video id="video" width="720" preload="auto" controls>
        <source
          src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
          type="video/mp4"
        />
      </video>

      <button id="button" onclick="changeTime()">
        Change currentTime to 30th second
      </button>
    </div>

    <script>
      function changeTime() {
        const video = document.getElementById("video");
        video.currentTime = 30;
      }
    </script>
  </body>
</html>
```

Here I went for the simplest example to imitate the behaviour - its just a video player with a button that will change the currentTime to the 30th second. 

Here is the **video-test.spec.ts** file: 

```ts
describe("Video Player", () => {
  it("sets the video player's currentTime to 30 seconds", () => {
    cy.visit("/test");

    cy.get("#button").click();

    cy.get("#video").then(($video: JQuery<HTMLVideoElement>) => {
      const video = $video.get(0);

      expect(video.currentTime).to.equal(30);
    });
  });
});
```
Here I visit the test page, which serves the index.html file. I click on the button, then I expect the currentTime to be 30. 

Results in Firefox 75: 

<img width="1437" alt="Screenshot 2020-05-04 at 12 08 29" src="https://user-images.githubusercontent.com/42744349/80955719-0435cb80-8e00-11ea-8218-0622f153e272.png">

Here you can see the currentTime was set correctly. 

Results in Chrome 81 and Electron 80 respectively: 

![Screenshot 2020-05-04 at 11 54 18](https://user-images.githubusercontent.com/42744349/80954973-b076b280-8dfe-11ea-8c9e-47ab60e164ac.png)

<img width="1438" alt="Screenshot 2020-05-04 at 12 00 54" src="https://user-images.githubusercontent.com/42744349/80955118-f469b780-8dfe-11ea-94e6-a9a3459c3b2f.png">

As you can see the test fails, currentTime is set to 0.

I can confirm that you can change the currentTime when opening the page directly in the Chrome browser Version 81.0.4044.129 (Official Build) (64-bit)

Any assistance would be greatly appreciated.

**Comment by theinfoarchitect** [comment]
@jennifer-shehane any feedback you could give me?

**Comment by ttraenkler** [comment]
I am having the same issue, seems to affect only Chrome.

**Comment by jennifer-shehane** [comment]
I can confirm this behavior with the example provided. It happens in Chrome, not Firefox. 

This example works though if you reference the video to a local video file. 

This got me thinking that we are encountering this bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1018533 where setting the currentTime will not work if the video's server does not include the range headers. But, it looks like the Accept-Range header is present in Cypress (although the headers are lowercased). 

### In Cypress

<img width="686" alt="Screen Shot 2020-08-21 at 3 18 23 PM" src="https://user-images.githubusercontent.com/1271364/90871827-b3071300-e3c1-11ea-95ef-87475e725ff4.png">

### Outside of Cypress

<img width="968" alt="Screen Shot 2020-08-21 at 3 17 23 PM" src="https://user-images.githubusercontent.com/1271364/90871865-bf8b6b80-e3c1-11ea-948d-c0f4a8d408d5.png">

So, I'm not totally sure that's the issue or not.


`index.html`

```html
<html>
<body>
  <div>
    <video id="video" width="720" preload="auto" controls>
      <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
        type="video/mp4" />
    </video>
    <button id="button" onclick="changeTime()">
      Change currentTime to 30th second
    </button>
  </div>

  <script>
    function changeTime() {
      const video = document.getElementById("video");
      video.currentTime = 30;
    }
  </script>
</body>
</html>
```

`spec.js`

```js
it("sets the video player's currentTime to 30 seconds", () => {
  cy.visit("index.html")
  cy.get("#button").click()
  cy.get("#video").then(($video) => {
    const video = $video.get(0)
    expect(video.currentTime).to.equal(30)
  })
})
```

### Chrome

<img width="1209" alt="Screen Shot 2020-08-21 at 3 08 47 PM" src="https://user-images.githubusercontent.com/1271364/90870866-3b84b400-e3c0-11ea-8d55-29b3f39a89d2.png">

### Firefox

<img width="1261" alt="Screen Shot 2020-08-21 at 3 09 19 PM" src="https://user-images.githubusercontent.com/1271364/90870933-50614780-e3c0-11ea-8e60-616fcb657bca.png">

**Comment by zachstence** [comment]
> This got me thinking that we are encountering this bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1018533 where setting the currentTime will not work if the video's server does not include the range headers. But, it looks like the Accept-Range header is present in Cypress (although the headers are lowercased).

@jennifer-shehane Thank you so much for pointing me in the right direction! I've been banging my head against the wall for far too long trying to figure out why I couldn't seek a video in a Cypress test.

For me, the solution was to add the following headers on my media intercept that loads a local file
```ts
cy.intercept('GET', 'https://example.com/video.mov', {
  statusCode: 200,
  fixture: 'media/video.mov,null',
  headers: {
    'Accept-Ranges': 'bytes',                   // <--
    'Content-Length': '6994770',                // <--
    'Content-Range': 'bytes 0-6994770/6994771', // <--
  },
})
```
Where `6994770` is the size of the file in bytes, and `6994771` is that size in bytes plus one.

I feel like Cypress should definitely be including these headers automatically. But anyways, thanks again!
