### ISSUE TITLE
Debugging high CPU usage in Cypress Helper

### ISSUE THREAD

**Issue by sgronblo** [cypress-io/cypress#7157]
### Current behavior:

When running a test case in headful Chrome and checking in "Activity Monitor", Cypress Helper is hovering above 200% constantly even after the test has finished running.

There are probably multiple possible causes for this, so I am opening this issue as an exploration into what options users have when faced with this problem.

### Desired behavior:

The CPU usage of Cypress Helper should be under 100% when Cypress is not seemingly doing anything obvious.

### Test code to reproduce

This is hard to say. I think Cypress was working ok for me earlier, but in the last few months it started exhibiting this problem. I am not creating this issue to resolve this specific instance anyway, but to find a way that anyone can use to get some ideas of what the cause could be.

### Versions

Cypress: 3.8.3
MacOS: Catalina 10.15.3
Browser: Chrome 81

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog). Your issue may have already been fixed.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. There is no exploration to be had without an example. There could be 1,000 things affecting the CPU for your particular usecase.

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by jennifer-shehane** [comment]
Also see issues labeled 'performance', your issue may already be open https://github.com/cypress-io/cypress/labels/type%3A%20performance%20%F0%9F%8F%83%E2%80%8D%E2%99%80%EF%B8%8F

**Comment by sgronblo** [comment]
Ok. I know that the issue is non-specific. I am not raising the issue to solve this specific instance of the problem. I will definitely try a newer version of Cypress.

But do you have any suggestion how this kind of problem would best be dealt with in the future? It might not be fixed by the latest version. It might come back in a new version. It's probably related to my local environment. As it is, it is unclear to me where to start to collect more information to either fix the problem, or turn it into a more well defined issue.

**Comment by jennifer-shehane** [comment]
@sgronblo You can get CPU logs from the Cypress related processes by following these directions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage

DEBUG logs in general may be helpful also depending. https://on.cypress.io/troubleshooting#Print-DEBUG-logs

Sometimes it's not specific to the Cypress product itself, like if you see the Plugins process going through the roof - it may be a cypress plugin or something in your plugins file for example.

**Comment by OtmarJoseph** [comment]
one way Cypress uses or consumes a high consuming CPU is what your test runs in parallel on one instance (one machine and many tests) another way is a test run with many threads See the documentation https:// docs.cypress.io/guides/guides/parallelization#What-you-ll-learn
