### ISSUE TITLE
Build separate 32bit and 64bit builds for Windows, don't ship ffmpeg twice

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#716]
Currently we only build `32bit` Windows, but we ship two versions of `ffmpeg` for both `32bit` and `64bit` Windows. 

This inflates the binary by almost 100mb O_O.

Need to build separate Windows arch. We've already updated the CLI and the download server to account for this.

**Comment by flotwig** [comment]
Also, in 3.1.5, there are copies of ffmpeg for every target architecture in the Windows download adding about 150mb:

![image](https://user-images.githubusercontent.com/1151760/54288306-a439f100-457d-11e9-97c8-2c1bb22ffc90.png)
