### ISSUE TITLE
Cypress Open command not working anymore

### ISSUE THREAD

**Issue by shikharq7** [cypress-io/cypress#7165]
Current behavior:

Hi, I had a fully functional cypress testrunner which stopped working all of a sudden, when I try to open test runner via command - `node_modules.bin\cypresss open` , it gives me the following error :

![image](https://user-images.githubusercontent.com/53361847/80568044-9a9d7200-8a39-11ea-9ee2-81c525ba3f8d.png)

~~~~~~~~~
node_modules.bin\cypresss : The module 'node_modules' could not be loaded. For more information, run 'Import-Module node_modules'.
At line:1 char:1

node_modules.bin\cypresss open

CategoryInfo : ObjectNotFound: (node_modules.bin\cypresss:String) [], CommandNotFoundException
FullyQualifiedErrorId : CouldNotAutoLoadModule
~~~~~~~~~~
However, if I add in the command - "test": "cypress open" in package.json and then execute the command - npm run test , it works. Any clue how to resolve this issue ?

![image](https://user-images.githubusercontent.com/53361847/80568420-4777ef00-8a3a-11ea-99db-d8579b38bb88.png)

![image](https://user-images.githubusercontent.com/53361847/80570076-7e9bcf80-8a3d-11ea-84cc-b99a0f32e07d.png)

### Desired behavior:

executing command - node_modules.bin\cypresss open  opens the test runner

### Test code to reproduce
Execute command : node_modules.bin\cypresss open

~~~~~~~~~~~~~~~~~~~~~~~~~~
PS C:\Users\shisharma\CypressAutomation> node_modules\.bin\cypresss open
node_modules\.bin\cypresss : The module 'node_modules' could not be loaded. For more information, run 'Import-Module node_modules'.
At line:1 char:1
+ node_modules\.bin\cypresss open

    + CategoryInfo          : ObjectNotFound: (node_modules\.bin\cypresss:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule
~~~~~~~~~~~~~~~~~~~~~~~~~~

### Versions

Cypress -4.4.0
OS - Windows 10
Browser - Chrome 78

**Comment by jennifer-shehane** [comment]
You've misspelled `cypress` in your command `node_modules\.bin\cypresss open` with 3 s's instead of 2.
