### ISSUE TITLE
Number inputs that are manually focused do not respect the caret position during `cy.type()`

### ISSUE THREAD

**Issue by madebysid** [cypress-io/cypress#7170]
### Current behavior:

I've set up a small repro app (link below) that has a button. When clicking on this button, an `<input type="number" value="1" />` is created and manually focused (by calling `focus()` on it).

In my test, I click on this button, wait for the input to show up, and then attempt to type something into this input. Instead of appending typed characters to the end of the input (where the cursor is), Cypress appends them to the beginning of the input.

### Desired behavior:

I expect the the typed character to be appended to the end of the input (where the cursor is), and the written test to pass. 

### Test code to reproduce

I've set up this repo that is a simplified version of my app and exhibits the issue:
https://github.com/madebysid/cypress-input-focus-issue

(I can fork https://github.com/cypress-io/cypress-test-tiny and set this up there instead if you prefer, but it seems very similar to what I have)

### Versions

Cypress: 4.5.0
OS: macOS
Browser: Electron

Curiously enough, the test behaves as I expect (and passes) on Cypress 3.7.0. Cypress 3.8.0+ have this issue.

**Comment by jennifer-shehane** [comment]
This behavior happening all the way back to 3.4.1, so was not introduced in a recent version. 

*Note:* You never need to write ``should('exist')`, this is asserted by default for any `cy.get()` command. 

## To reproduce

`index.html`

```html
<html>
<body>
  <button onclick="onClick()">Show input</button>
  <script>
    function onClick() {
      let input = document.createElement('input')
      // The type has to be a `number` for the test to fail
      input.type = 'number' 
      input.value = 1

      document.body.appendChild(input)

      // The input needs to be forcibly focused for the test to fail
      document.querySelector('input').focus() 
    }
  </script>
</body>
</html>
```

`spec.js`

```js
it('can type in a number field correctly', () => {
  cy.visit('./index.html')
  cy.get('button').click()
  cy.get('input')
    .type('2')
    // fails
    .should('have.value', '12')
})
```


![](http://g.recordit.co/CWm7I5qi6a.gif)

<img width="806" alt="Screen Shot 2020-04-30 at 4 19 07 PM" src="https://user-images.githubusercontent.com/1271364/80697020-588a3400-8afe-11ea-8f73-2ae509e9ac11.png">
