### ISSUE TITLE
Test results commented to wrong Repo/PR

### ISSUE THREAD

**Issue by pranaysahith** [cypress-io/cypress#7171]
### Current behavior:
we have 2 github repos enabled with github integration in Cypress project.
When a PR from 1 repo executes the cypress tests, it is sometimes commenting the test results in PR/Issue of another repository.

### Desired behavior:
When multiple github projects are enabled for integration, PR from that repo which triggered tests should only receive test results comment.

### Test code to reproduce
Enable github integration for 2 github repos and create a PR in repo A which runs the tests.
Make sure there is an issue or a PR in repo B which has same number as PR in repo A.

### Versions
OS: Linux Debian - 9.9
Browser: Chrome 77.0.3865.90
Cypress: v4.4.1

**Comment by jennifer-shehane** [comment]
Hey @pranaysahith, sorry for the delay. Can you email us at support@cypress.io detailing what organization and project this is occurring under? You can locate and send over the OrgId as explained here: https://on.cypress.io/organizations#Organization-ID

**Comment by pranaysahith** [comment]
closing the issue as this is fixed, we can no longer choose 2 git repos for a single cypress project.
