### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state. Randomly Facing this error and hence failing the Cypress Tests

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#7180]
### Current behavior:
When we execute our cypress test, it randomly throws the below error

```
WebSocket is already in CLOSING or CLOSED state. 
```

As per our flow, if out automation steps gets pass we execute a cypress Tasks to update the result file for the TestCase status (Pass or Fail). In that Tasks there isn't any database connection. Its just simply uses node command to update a file in fixture folder to set status as pass or fail.

Randomly, when this task is executed the cypress hangs there and end up in a error with WebSocket is already in Closing or Closed State+

We found that after upgrading to latest version 4.4.0 and more It runs very slowly and when executed cy.task() it stucks there randomly. If we revert back to 3.4.1 then its stable. Working normally.

### Desired behavior:
The tests should not hold and throws any error like Websocket

### Test code to reproduce
Random failure. We are trying to reproduce the steps. But didn't knew how. 
https://github.com/cypress-io/cypress/pull/6945
https://github.com/cypress-io/cypress/issues/6458

We have gone through the above issues but didn't get success. Also, have read other socket problem but got fail on each. 

### Versions
After 3.4.1 to latest version 4.5.0

Operating System : Windows 10 
Browser: Chrome, Electron

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-98) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Please provide a reproducible test suite to show the issue - including the `cy.task()` code you are mentioning where this hangs. 

Unfortunately we have to close this issue if a way to reproduce this is not provided as there will be no path forward for investigation.

**Comment by Prashant-Kan** [comment]
Sure Jennifer. 

We are working on the reproducible steps Will share when we find that. 
As its random, so hard to find the exact reproducible steps. 

Can you give any reference where the random bug has a reproducible steps ?

meanwhile, 
cy.task() is to execute the node command to write the result of the executed testcase in (*.md) file.

import * as fs from "fs";
import * as path from "path";
const resultFile = path.join(#FolderPath#, mdFileNameWithExtension);
ensureFolder()
if (fs.existsSync) then read 
else create new file 

read and fill the file content 
and finally using fs.writeFileSync write the file content

**Comment by flotwig** [comment]
Most likely, this regex needs to be updated to handle "WebSocket is already in CLOSING or CLOSED state" as well. We want to retry on these errors instead of failing.

https://github.com/cypress-io/cypress/blob/8b0d0d8e03b6c6c8838faa8fd6f8e78a9e1f5dbd/packages/server/lib/browsers/cri-client.ts#L14-L14

**Comment by testtek** [comment]
Having same issue 
https://github.com/cypress-io/cypress/issues/7180#issue-609322131
