### ISSUE TITLE
Testing via Cyress returns 401 error when calling an API

### ISSUE THREAD

**Issue by shikharq7** [cypress-io/cypress#7193]
Hi! 
Thank you looking into my issue. I am trying to test a website using Cypress. One of the testcases involves, after logging in > selecting a date range and clicking the 'Refresh' button. This makes a call to the an API which returns the data into a field. 

However, what is happening is when testing through Cypress, clicking on the 'Refresh'button results in 401 code ( unauthorised) . I am not sure what is causing this issue as it is not happening when I run the same flow outside cypress in chrome browser. 

![image](https://user-images.githubusercontent.com/53361847/80780419-3f42bf80-8bb2-11ea-8d29-969eeb08e139.png)

![image](https://user-images.githubusercontent.com/53361847/80780484-7022f480-8bb2-11ea-8ee4-33dbf8c21f42.png)

This is how the API service is being called :

![image](https://user-images.githubusercontent.com/53361847/80780473-61d4d880-8bb2-11ea-9c26-352ffa939d8c.png)

### Desired behavior:

Clicking on 'Refresh' button should load the data without any issues.

### Test code to reproduce

~~~~~~~~
it('ProfileTest', () => 
    {
        cy.get('---Locator----').click()
        cy.get('-----Locator-------').type('2017-01-01')
        cy.get('-----Locator-------').type('2020-01-01')
        cy.get('-----Locator-------').click()
     }
~~~~~~~~

### Versions

Cypress -4.4.0
Windows -10
Chrome - 78

**Comment by njevdjo** [comment]
Try with "Cookies Preserve Once" 

```javascript
Cypress.Cookies.preserveOnce('my_custom_session_id')
```
Read more on [Cypress > Cookies > Perserve Once](https://docs.cypress.io/api/cypress-api/cookies.html#Preserve-Once)

**Comment by shikharq7** [comment]
Thanks @njevdjo . This worked. 
Closing the issue
