### ISSUE TITLE
React boundary catches an error but fails the test if test continues

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7196]
Cypress v4.5.0

Example repo https://github.com/bahmutov/test-custom-error-boundary

```
npm install
npm run dev
```

Run the integration spec - one will fail and another is successful

<img width="1044" alt="Screen Shot 2020-05-01 at 10 45 49 AM" src="https://user-images.githubusercontent.com/2212006/80814064-3265a200-8b99-11ea-81da-4d108a08d7fd.png">

The interesting part: the custom React boundary catches the error, and if use the app manually after the test is finished, it works just fine without throwing

```js
describe('app', () => {
  // but then fails the test
  it('catches an error', () => {
    cy.visit('http://localhost:3000')
    cy.get('.pokemonName-input').type('unknown')
    cy.contains('Submit').click()
    // currently fails
    cy.contains('Try again').should('be.visible')
  })

  it('catches an error and all is good', () => {
    cy.visit('http://localhost:3000')
    cy.get('.pokemonName-input').type('unknown')
    cy.contains('Submit').click()
    // you can click "Try again manually"
  })
})
```

The second test is happy and no errors leak

<img width="1050" alt="Screen Shot 2020-05-01 at 10 57 02 AM" src="https://user-images.githubusercontent.com/2212006/80814805-86bd5180-8b9a-11ea-92fa-e64357e51234.png">

**Comment by chrisbreiding** [comment]
Trying to reproduce this with that repo, but I get the following error if I run `npm run dev` or `npm run build` in it:

```
Could not find a required file.
  Name: index.html
  Searched in: /Users/chrisbreiding/Dev/cypress/test-custom-error-boundary/public
```

**Comment by bahmutov** [comment]
Sorry about that - my git has public folder on ignore so I need to remember to add force it. I added public folder and pushed

**Comment by chrisbreiding** [comment]
It looks like React still bubbles up the error to `window.onerror`, which is where Cypress catches it and why it fails the test. You can even see that it displays Cypress's error because we return that error from `window.onerror`. 

It happens as a result of submitting the unknown pokemon name, but in the second test, it's too late to trigger failing the test, since it has already passed. It only fails the first test because there are further commands.

There's room for debate on this, but I think Cypress is doing the right thing. The error hits `window.onerror`, so it's natural for Cypress to think that something went wrong. That's why Cypress gives you a way to turn off failing on uncaught exceptions:

```javascript
// in test that exercises error boundary
cy.on('uncaught:exception', () => false)
```

Another option is defining your own `window.onerror` handler in your app code. Then it overrides Cypress's handler and, so, won't fail the test.

**Comment by bahmutov** [comment]
Ughh, it is still hard to say what React is doing, and if it bubbles up.

https://reactjs.org/docs/error-boundaries.html

Closing for now

**Comment by rafahuaman** [comment]
This is a description of

**Comment by rafahuaman** [comment]
I found this description of what React does.

https://github.com/facebook/react/issues/12897#issuecomment-410036991

> In development environment, React uses a trick: caught exceptions are thrown inside a fake DOM event which makes them reported by window.onerror, but then React actually catches them so that they don't propagate up (in case there is an error boundary — otherwise they are rethrown).
> 
> In production errors caught by error boundaries stay caught.

**Comment by felippepuhle** [comment]
Is there anything we can do to handle this?

**Comment by martijnsenden** [comment]
> Is there anything we can do to handle this?

I'm also curious about a solution for this.

**Comment by chrisbreiding** [comment]
This can be solved by using [the `uncaught:exception` event](https://docs.cypress.io/api/events/catalog-of-events#App-Events). I'd recommend [using it per-test](https://docs.cypress.io/api/events/catalog-of-events#To-catch-a-single-uncaught-exception) like in the following:

```javascript
it('hits a react error boundary', () => {
  cy.on('uncaught:exception', (err) => {
    // update this to apply to the error your application throws
    if (err.message.includes('part of error message')) {
      // returning false keeps Cypress from failing the test
      return false
    }
  })

  // action that causes error
  cy.get('button').click()
  // test the error boundary
  cy.contains('There was an error')
})
```

**Comment by nemonemi** [comment]
I have tried it, however, it had no impact. The exception still gets thrown, and the test fails / pipeline gets broken.
