### ISSUE TITLE
No longer running unit tests

### ISSUE THREAD

**Issue by scottdavis** [cypress-io/cypress#72]
Admittedly when loren sit up the environment for me he said unit testing was sort of a hack. I noticed today with one of the later releases of cypress it no longer runs the unit tests and is giving me a no tests found in x file message. I only have one unit tests file right now and it looks like this:

``` coffeescript
#= require ../../../app/bower_components/jquery/dist/jquery.js
#= require ../../../.tmp/scripts/app.js
#= require ../../../app/bower_components/angular-mocks/angular-mocks.js
#= require ../../../app/bower_components/sinon-1.12.2/index.js
describe "Timer", ->
 ....Tests Here...
```

![Imgur](http://i.imgur.com/ft0EdhE.png)

**Comment by brian-mann** [comment]
This actually looks like its most likely due to a syntax error in coffeescript. When Cypress fails to transpile your `.coffee` files the spec ends up being blank which is why you get that message.

Can you come into the gitter channel so we can talk about this?

https://gitter.im/cypress-io/cypress

**Comment by jennifer-mann** [comment]
This issue is more accurately described and will be handled in #318
