### ISSUE TITLE
Chromium Renderer process crashes on every Jenkins run

### ISSUE THREAD

**Issue by zac11** [cypress-io/cypress#7200]
### Current behavior:

Running Cypress Tests on local Jenkins installation is failing, and the Chromium render process crashes with this following error-

```
[745:0429/144950.758921:FATAL:memory.cc(22)] Out of memory. size=96002048

We detected that the Chromium Renderer process just crashed.
```
All the tests are passing as expected on local machine.

### Desired behavior:

Tests should run without any issue, and `mochawesome` report generated

### Test code to reproduce

To reproduce this steps, use the `Jenkinsfile` from this repo -[Git Repo]( https://github.com/zac11/iCinema)

- Clone repository

-  run `npm i` from project root.

- cd `client` and then do a `npm i`

- Run `npm start` to start server.

- Run `npm test:ci` for all tests

### Versions

Cypress Version - `4.4.0`

### Additional Information

Jenkins installation has been done through docker with the steps mentioned in this file from the Kitchen Sink CI [link](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/Jenkinsfile)

Command to install Jenkins. - 

`docker run --ipc=host --shm-size=512M -u root -d --name blue-ocean -p 8080:8080 -v jenkins-data:/var/jenkins_home -v npm-cache:/root/.npm -v cypress-cache:/root/.cache -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean:latest`

I have added `--ipc=host` as mentioned By Brian in this issue [here](https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772) and changed the `--shm-size` as mentioned in the same issue [here](https://github.com/cypress-io/cypress/issues/350#issuecomment-353572782)

I have also changed the base cypress image to `cypress/browsers:node12.13.0-chrome80-ff74`  and the added the solution mentioned [here](https://github.com/cypress-io/cypress/issues/3602#issuecomment-591531887) to disable shm usage. But none of them work.

### Log
The terminal output from the failed run is given here in this gist - [https://gist.github.com/zac11/f899c8e95c095c606b2c12db4c952d0e](url)

**Comment by jennifer-shehane** [comment]
Can you try to `disable-dev-shm-usage` as described here? https://on.cypress.io/continuous-integration#In-Docker

**Comment by zac11** [comment]
Thanks for the response Jennifer. I have implemented a portion of the solution mentioned in the `cypress/plugins` directory but I see that it is checking for Chrome browser only. 
I'll try the solution mention and update the story.

**Comment by zac11** [comment]
I'm still getting the same error as before after adding the command mentioned. 
```
Landing on the Dashboard

[761:0504/172331.870341:FATAL:memory.cc(22)] Out of memory. size=96002048

We detected that the Chromium Renderer process just crashed.
```

I have added this in the `cypress/plugins/index.js` -->
```
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      launchOptions.args.push('--disable-dev-shm-usage')
    }

    return launchOptions
  })
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
}
```
If I change the browser to Chrome in the cypress run command to 
`cypress run --headless --browser chrome --spec cypress/integration/cinema/*.js`

Then I am able to see that the above error is not happening and the tests are run in the Jenkins pipeline.

**Comment by moncapitaine** [comment]
Worked for me. I guess this one can be closed?

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
