### ISSUE TITLE
Cypress wait on aliased route times out after first one in each test file on CircleCI/GitHub Actions but works fine locally (MacBook Pro 16)

### ISSUE THREAD

**Issue by dphang** [cypress-io/cypress#7207]
Hi,

I am having an issue while waiting for aliased routes that strangely only happens on CircleCI and GitHub Actions (haven't tried other CI providers yet) but works fine on my MacBook Pro 16. Within each test file, only the first test that waits for an aliased route is succeeding, and subsequent tests are timing out while waiting.

Sample test I created that repros this issue:

```js
describe("Test with no beforeEach", function() {
  it("should be able to ping an API", function() {
    cy.server();

    // Delay of 2 seconds
    cy.route("POST", "https://www.mocky.io/v2/5185415ba171ea3a00704eed?mocky-delay=2000ms").as("sample");
    cy.visit("/");

    cy.get("[data-cy=button]").click();
    cy.wait("@sample");
    cy.get("@sample").should("have.property", "status", 200);
  });

  it("should be able to ping an API a second time", function() {
    cy.server();

    // Delay of 2 seconds
    cy.route("POST", "https://www.mocky.io/v2/5185415ba171ea3a00704eed?mocky-delay=2000ms").as("sample");
    cy.visit("/");

    cy.get("[data-cy=button]").click();
    cy.wait("@sample");
    cy.get("@sample").should("have.property", "status", 200);
  });

  it("should be able to ping an API a third time using a different alias", function() {
    cy.server();

    // Delay of 2 seconds
    cy.route("POST", "https://www.mocky.io/v2/5185415ba171ea3a00704eed?mocky-delay=2000ms").as("anotherSample");
    cy.visit("/");

    cy.get("[data-cy=button]").click();
    cy.wait("@anotherSample");
    cy.get("@anotherSample").should("have.property", "status", 200);
  });

  it("should be able to stub a response with status 400", function() {
    cy.server();

    cy.route({
      method: "POST",
      url: "https://www.mocky.io/v2/5185415ba171ea3a00704eed?mocky-delay=2000ms",
      response: {"stubbed": "stubbed"},
      status: 400,
    }).as("sample");
    cy.visit("/");

    cy.get("[data-cy=button]").click();
    cy.wait("@sample");
    cy.get("@sample").should("have.property", "status", 400);
  });
});
```

### Current behavior:

On GitHub Actions/CircleCI, only the first test in each test file succeeds waiting for an aliased route. The other ones time out with the following error or similar:

```
  1) Test page should be able to ping an API a second time:
     CypressError: `cy.wait()` timed out waiting `15000ms` for the 1st request to the route: `sample`. No request ever occurred.
      at cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:146180:16)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:146114:11)
      at Object.retry (http://localhost:3000/__cypress/runner/cypress_runner.js:139807:19)
      at checkForXhr (http://localhost:3000/__cypress/runner/cypress_runner.js:136125:17)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:136126:28
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9059:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:6333:29)
      at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:140268:21)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:140303:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:139847:16
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9059:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:6994:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:7051:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:7096:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:7176:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:7120:18)
```

Locally on the MBP 16, all tests are successful.

### Desired behavior:

On GitHub Actions/CircleCI, all tests should succeed and no timeouts while waiting for aliased routes.

### Test code to reproduce

I created a repo here that reproduces the issue 100% on CircleCI/GitHub Action builds: https://github.com/dphang/cypress-test. It is a simple NextJS 9.3.0 React app that has a button that makes a POST to mocky.io. This returns a 200 response with body {"hello":"world"} after 2 seconds.

There are three test specs under here: https://github.com/dphang/cypress-test/tree/master/cypress/integration. They organize the tests differently and even try changing the alias in one case.

I am running tests using the two commands:
`yarn run dev` (starts NextJS dev server, but also prod server fails)
`yarn run test-cypress` 

Locally, all tests succeed (MBP 16) but on CircleCI/GitHub Actions, only the first test in each test file succeeds. The other tests time out while waiting for the aliased route.

Example failing builds (check build artifacts for the video):

CircleCI: https://circleci.com/gh/dphang/cypress-test/24

GitHub Actions (Ubuntu): https://github.com/dphang/cypress-test/runs/639492718
Cypress Video: https://github.com/dphang/cypress-test/suites/648310763/artifacts/5523999

GitHub Actions (Mac OS) also fails: https://github.com/dphang/cypress-test/runs/639492714

### Related Issues

Issues that I found that may be related:

https://github.com/cypress-io/cypress/issues/3585 (was closed due to no reply from original author / no repro)
https://github.com/cypress-io/cypress/issues/3427

### Versions

I am running Cypress tests on a NextJS 9.3.0 app (React framework). Using TypeScript 3.8.3.

The app uses fetch APIs, so in Cypress I override `window.fetch` with `unfetch` in order to use the aliased routes: https://github.com/dphang/cypress-test/blob/master/cypress/support/index.ts

**Local (successful):**
MacBook Pro 16 with Catalina 10.15.14
Node v13.13.0
Cypress 4.5.0
Electron80

**GitHub Actions (failing):** 
ubuntu-latest (right now, it is same as ubuntu-18.04)
Node v12.x
Cypress 4.5.0
Electron80

**CircleCI (failing):**
Using docker image cypress/browsers:node13.6.0-chrome80-ff72
Node v13.6.0
Cypress 4.5.0
Electron80

Thanks for your help!

**Comment by jennifer-shehane** [comment]
So this is an async issue with the code you've written to override fetch. 

Basically, there's no guarantee the response was completed in this code https://github.com/dphang/cypress-test/blob/master/cypress/support/index.ts before the visit since it’s async. This was happening before every window:before:load and just happened to fail sometimes. 

Async issues are more likely to exhibit themselves on slower machines which is likely the case here. You just need to fetch the thing once and then handle it after. I didn't run the code below, but it'd be something like this:

```js
let resp
 
Cypress.on("window:before:load", win => {
 (win as any).eval(resp);
 (win as any).fetch = (win as any).unfetch;
});
 
describe('Openning Sprinklr App', () => {
 before(() => {
   return fetch("https://unpkg.com/unfetch/dist/unfetch.umd.js")
     .then(stream => stream.text())
     .then(response => {
       resp = response
     });
 })
 
 it('tests', () => {
   cy.visit('...')
 })
})
```

**Comment by dphang** [comment]
Thanks for the tip, that solved it!
