### ISSUE TITLE
type() error:is being covered by another element:

### ISSUE THREAD

**Issue by sharpboy2008** [cypress-io/cypress#7209]
### Current behavior:

 Timed out retrying: cy.type() failed because this element:

<input type="text" id="username" name="username" value="" maxlength="50" style="color: rgb(153, 153, 153);">

is being covered by another element:

<div id="TB_overlay" class="TB_overlayBG"></div>

Fix this problem, or use {force: true} to disable error checking.

### Desired behavior:

login successful or wrong user name and password

### Test code to reproduce

   cy.visit('https://hr.wkinfo.com.cn/?lang=en_US')
            cy.contains('Login').click()
            cy.get('#username').click({force: true}).type("username");
            cy.get('#password').click({force: true}).type("password");
             cy.get(' #TB_ajaxContent > div > form > p:nth-child(6) > input').click()
            cy.wait(3000)

**if i changed to the following,**

  it('cctaa website', function () {
            cy.visit('https://hr.wkinfo.com.cn/?lang=en_US')
            cy.contains('Login').click()
            cy.get('#username').type("username",{force: true});
            cy.get('#password').type("password",{force: true});
            cy.get(' #TB_ajaxContent > div > form > p:nth-child(6) > input').click()

**it says user name and password can not be empty.**

### Versions

chrome:81
cy:4.5
OS:windows 10

**Comment by nemanjamilosavljevic-newtron** [comment]
Why is this bug closed? Has it been resolved, and if so, how?

I am experiencing the same problem.
I have described it here: https://github.com/cypress-io/cypress/issues/14921
