### ISSUE TITLE
Cookie header in `cy.request` is concatenated with browser cookies

### ISSUE THREAD

**Issue by andsnpl** [cypress-io/cypress#7210]
I've read #5894 and #5559 but I don't believe they are describing this issue. Haven't found any other issues describing this behavior, but it's likely I've missed something.

This behavior was reproduced in 3.4.1 and 4.4.1.

### Current behavior:

If a Cookie header is supplied to `cy.request`, the browser cookies will be naively concatenated to the header provided. For example:

```js
cy.setCookie('foo', 'bar')
cy.request({ url: 'https://example.com', headers: { Cookie: 'foo=baz' } })
// Cookie header received by server: "foo=baz;foo=bar"
```

Because this can result in duplicate values for the same name, the server has to interpret this when parsing the header value. Some servers seem to take the first instance of a name. Our production app takes the latest. (Some googling shows that neither behavior is strictly correct according to http, but it's what happens.)

### Desired behavior:

A cookie name provided explicitly to `request` should override the value of that cookie in the browser.

### Test code to reproduce

https://github.com/andsnpl/cypress-request-cookies-demo

### Versions

This behavior was reproduced in 3.4.1 and 4.4.1.

**Comment by jennifer-shehane** [comment]
I'm able to recreate this behavior from the repo provided.

**Comment by tonylawrence-outreach** [comment]
Has there been any progress with resolving this behavior? I see the issue still occurring even though its been almost over a year now.

**Comment by amartinez1558** [comment]
This can help address https://github.com/cypress-io/cypress/issues/8909 as well
