### ISSUE TITLE
Issue with Blur on form with single input in Vue.

### ISSUE THREAD

**Issue by WayneHiller** [cypress-io/cypress#7218]
I have a Vue SPA application. An edit page with a form and one text input. I cy.Type into the input then click a button. In the Vue script I have a watch on the record and if any changes happen on any of the fields it sets a dirty property on the record object. When running cy tests the dirty property is never set after clicking the Save button (the same button posts the record to the server via AJAX).

If the form has more than one or two inputs and I cy.Type into all of them it works as expected. It seems like maybe it is a timing issue? Executing cy.Get(...).click() on the button might not be firing the blur event on the input, not sure how I can test that?

Cypress 4.5.0, Win 10 x64, Chrome.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
