### ISSUE TITLE
Trying to use lodash from a local file just produces an error

### ISSUE THREAD

**Issue by ManchoBlanko** [cypress-io/cypress#7229]
I am trying to convert my system from underscore to lodash having used underscore flawlessly for quite a long time.  I installed lodash with npm and required it in the server which seems to be running perfectly. I then downloaded `lodash.js` and embedded it in some html files in a tag. When I try to load the web page I get an error - 

```
"ReferenceError: _ is not defined".
```

If I change the `<script>` tags to load the cloudflare cdn file it seems to work perfectly.

I really want to use a downloaded `lodash.js` file rather than having to download it every time a page loads but I just cannot get it to recognise "_". I have tried every suggestion I have come across so far (including lodash's noconflict code) without success. I would appreciate any help you may offer, I don't have that much hair left to tear out now!

Apologies for lack of evidence, all my attempts to upload image captures failed too!  However all the evidence I have is the quoted error message (above) every time I try to load a web page containing `<script src="../JS/lodash.js"></script>`.

Thank you in advance.

**Comment by jennifer-shehane** [comment]
Hey @ManchoBlanko, I'm not understanding what your described situation has to do with Cypress exactly. Please provide the test code from Cypress that is failing.

Also when opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
