### ISSUE TITLE
.should("be.visible") doesn't interpet elements with " style='transform: scale(0,0)' " correctly

### ISSUE THREAD

**Issue by mellogarrett** [cypress-io/cypress#723]
### Current behavior:
`.should('be.visible')` recognizes elements with `style="transform: scale(0,0)"` as being visible.

### Desired behavior:
`.should('be.visible')` should determine that elements with `style="transform: scale(0,0)"` are actually not visible

### How to reproduce:
1) create an element on a page that has `style="transform: scale(0,0)"`
2) write test that checks that element's visibility like so: `cy.get('#el').should('be.visible');`

### Additional Info (images, stack traces, etc)
<img width="1384" alt="screen shot 2017-10-10 at 4 08 01 pm" src="https://user-images.githubusercontent.com/9908831/31408091-578019c0-add5-11e7-811d-ae498e67889e.png">

- Operating System: Mac OS Sierra
- Cypress Version: 1.0.1
- Browser Version: Chrome 61

**Comment by jennifer-shehane** [comment]
Can recreate with following code. The span should clearly not be visible as it cannot be seen. 

## index.html

```html
<!DOCTYPE html>
<html>
<head></head>
<body>
  <div style="transform: scale(0,0)">
    <span id="transform-scale">TRANSFORMERS</span>
  </div>
</body>
</html>
```

## spec file

```js
it('should not be visible', function () {
  cy.visit('index.html')

  cy.get('#transform-scale').should('be.visible')
  cy.get('#transform-scale').should('not.be.visible')
})
```

Added a failing test here: https://github.com/cypress-io/cypress/pull/4421

**Comment by jennifer-shehane** [comment]
There's an edge case where this falsely evaluates an element as invisible when the parent has height: 0 that this does not cover. The example is given here: https://github.com/cypress-io/cypress/issues/5974#issuecomment-566897559
