### ISSUE TITLE
access cache on run mode is different from open

### ISSUE THREAD

**Issue by nitzanashi** [cypress-io/cypress#7231]
### Current behavior:

running test on `run` mode does not have the same result as `open`, I'm trying to test if a file does not exist in my cache, could figure out a way to handle the async issue from #4742, and while on headed, test is working perfectly, on headless the test is not accessing the cache storage

### Desired behavior:

`run` and `open` have the same result for accessing cache

### Test code to reproduce

```js
    it('does not caching token', () => {
        /**
         * @see https://googlechrome.github.io/samples/service-worker/window-caches/
         * dig down into cache to check that token was never cached
         */
        cy.window().then((window) => {
            /**
             * @see https://github.com/cypress-io/cypress/issues/4742
             * we're using wrap here because Assertion failure in async test case does not fail test
             */
            cy.wrap(
                window.caches.keys().then((cacheNames) => {
                    cacheNames.forEach((cacheName) => {
                        cy.wrap(
                            window.caches.open(cacheName).then((cache) => {
                                return cache.keys();
                            }).then((requests) => {
                                requests.forEach((request) => {
                                    expect(request.url).to.match(/token-[^-]*\.json/);
                                });
                            }),
                        );
                    });
                }),
            );
        });
    });
```

on run:
![image](https://user-images.githubusercontent.com/13871150/81122094-7ad1e680-8f30-11ea-8c8c-6a126bf2fda8.png)

on open:
![image](https://user-images.githubusercontent.com/13871150/81122443-3135cb80-8f31-11ea-8fb7-a95e49ff2b20.png)

### Versions

Cypress 3.8.3 and 4.5.0

**Comment by jennifer-shehane** [comment]
I would suggest following on recommendations on troubleshooting why tests are fail in `cypress run` but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI Also check your `.gitignore`, maybe the file doesn't exist on the machine during `cypress run` due to this. 

Otherwise I will need a fully reproducible example. This doesn't recreate because the robots.txt never exists when I run this.

**Comment by nitzanashi** [comment]
it is somehow solved now, might be something with my setup, thank's for responding @jennifer-shehane 👍🏻
