### ISSUE TITLE
Can't override default values using env array in configFile

### ISSUE THREAD

**Issue by mwren-mshanken** [cypress-io/cypress#7241]
### Current behavior:

If I attempt to overwrite a default value, like baseUrl, in a configFile, the value is not overwritten.

From:  https://docs.cypress.io/guides/guides/environment-variables.html#Setting 

> baseUrl can be set in your configuration file (cypress.json by default) - and then you can use an environment variable to override it.

If I attempt to do this in a configFile:

```
{
   "env": {
       "baseUrl": "www.mynewurl.com"
     }
}
```

if I try to visit

`cy.visit("/")`

I visit "/"

### Desired behavior:

Overwriting baseUrl with an environmental variable should work, even if the environmental variable comes from a configFile.

### Test code to reproduce

```
{
   "env": {
        "baseUrl": "www.mynewurl.com"
   }
}
```

### Versions

Cypress 4.5.0

**Comment by jennifer-shehane** [comment]
>baseUrl can be set in your configuration file (cypress.json by default) - and then you can use an environment variable to override it.

This is refering to an OS level environment variable, **not** a Cypress environment variable. See the code example below the linked doc for an example of setting an OS level environment variable. 

```
CYPRESS_BASE_URL=https://staging.app.com cypress run
```

**Comment by jennifer-shehane** [comment]
I've updated the docs to be more specific here https://github.com/cypress-io/cypress-documentation/commit/d700192682cc1afef1123e4e90f2a8d6cb79f6b5

**Comment by mwren-mshanken** [comment]
Thanks for the explanation! Would it be possible, in a future release, so set baseUrl from an env array in my configFile?

My use case is that I am moving my tests to CI, and replacing _all_ of my calls to Cypress.config with Cypress.env would save a ton of time, since I could search and replace, then just move most of my config file into an env{} array within it.

**Comment by jennifer-shehane** [comment]
You can use the env keys for whatever you want, so if you want to use them for urls, you can do that. 

```js
{
   "env": {
       "myDevUrl": "https://dev.mynewurl.com",
       "myStagingUrl": "https://staging.mynewurl.com",
       "myProdUrl": "https://prod.mynewurl.com",
     }
}
```

```js
cy.visit(Cypress.env('myDevUrl'))
cy.visit(Cypress.env('myStagingUrl'))
cy.visit(Cypress.env('myProdUrl'))
```

The baseUrl is convenient for checking that the server is running before starting (Cypress will error if it's not) and Cypress will also reroute to the baseUrl a little bit quicker if it knows it ahead of time - so you'd lose those 2 things not using a baseUrl key specifically.
