### ISSUE TITLE
Unable to open cypress UI

### ISSUE THREAD

**Issue by thecodejack** [cypress-io/cypress#7243]
### Current behavior:

We are having a VM machine which multiple users connect. Multiple users also use cypress. Now problem is when I run `cypress open`. Cypress is trying to access/create folder named `/tmp/cypress` and place a lock file there. But if another user runs same command after folder is created, it throws following error

```
[OperationalError: EACCES: permission denied, open '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'

] {  cause: [Error: EACCES: permission denied, open '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'    ] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'
  },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'
}
Error: EACCES: permission denied, open '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'
```

### Desired behavior:

A way where this error doesn't occur. Possible solutions that come to my mind are
- config 
- automatically try creating another folder proably `/tmp/cypress01` 
- create cypress folder with access to all groups and users of the machine.

**Comment by jennifer-shehane** [comment]
Cypress requires root access, you'll need to install it accordingly and make sure you have the proper permissions set. See https://github.com/cypress-io/cypress/issues/1281

**Comment by Saibamen** [comment]
@jennifer-shehane So maybe we need to add check if we have root access and throw better error message?

**Comment by thecodejack** [comment]
@jennifer-shehane 

this seems to be bit different to what discussion is happening in #1281 . Probably root access will helps but if cypress can create folder and set permissions right in `/tmp/cypress`, this can be resolved easily.


I think you should add also root access issue to trade-offs if can't be fixed. This is kind of a blocker that can make developers/companies rethink about cypress before committing.

**Comment by jennifer-shehane** [comment]
Some of this will be addressed in https://github.com/cypress-io/cypress/pull/7126
