### ISSUE TITLE
cy.visit() qs parameter appends query parameters incorrectly when passed a url containing "/#/"

### ISSUE THREAD

**Issue by dsesami** [cypress-io/cypress#7246]
### Current behavior:
1. Configure Cypress.config.baseUrl as `https://localhost:3000`
2. Perform a `cy.visit()` like this, doesn't matter what application it is since we're just looking at the URL bar.

```js
cy.visit({
  url: '/#/users'
  qs: {'name': 'foo'}
})
```

The URL visited when this occurs is:
```
https://localhost:3000/?name=foo#/users
```
### Desired behavior:
The URL should be:
```
https://localhost:3000/#/users?name=foo
```
### Test code to reproduce
Here's a fork of the tiny test repo you can just run and look at the URL with
https://github.com/dsesami/cypress-test-tiny/blob/master/cypress/integration/spec.js

### Versions
Chrome/Fedora 31/Cypress 4.5.0 and also Cypress 3 does this as well

**Comment by dsesami** [comment]
as an addendum: 

cy.hash() gets this value, but there isn't a way to set it in cy.visit, either directly through visit() or by setting it as a `hash` value in the optional parameters.

**Comment by jennifer-shehane** [comment]
I can recreate this without the need for a `baseUrl`

`spec.js`

```js
it('works', () => {
  cy.visit('https://example.cypress.io/#/somesite', { 
    qs: { 'name': 'foo' } 
  })
})
```

![Screen Shot 2020-05-07 at 4 59 57 PM](https://user-images.githubusercontent.com/1271364/81284514-36575f80-9084-11ea-9bee-ddbdec585d04.png)

The current implementation of the `qs` option is here: https://github.com/cypress-io/cypress/pull/5040 Likely the `mergeUrlWithParams` needs to be updated to take this url structure into account. https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/location.coffee#L127:L127

**Comment by jennifer-shehane** [comment]
Well, I actually think this is how URLs are meant to be formed - with the hash fragment following the query params. I'm not totally sure we will support this since this would break implementations that use hash tags as normal fragments. I would suggest passing in the fully formed URL you want if you use hashtag URLs in this way. https://tools.ietf.org/html/rfc3986#section-4.1

**Comment by dsesami** [comment]
@jennifer-shehane good point on the workaround for just writing out the entire query string that way. I should mention that hash-based URLs do work this with the way many react apps work, for better or worse (see people talking about it in https://github.com/ReactTraining/react-router/issues/665). it might be worth documenting this case, regardless, if it's a `wontfix`.
