### ISSUE TITLE
Installing cypress through yarn / npm takes forever 

### ISSUE THREAD

**Issue by recitogigih** [cypress-io/cypress#7251]
### Current behavior:
I tried to install cypress through yarn / npm but it just takes forever, sometimes it works sometimes not, after googling an issue [1188](https://github.com/cypress-io/cypress/issues/1188 ) happened also in installing binary from korea , my location right now in indonesia. is this has any correlation with asia area? this is really drives me crazy. my connection is just fine

![image](https://user-images.githubusercontent.com/38373538/81266626-46b10f80-906f-11ea-87cf-6790728aec26.png)

### Desired behavior:

I just want it can be installed smoothly. not sometimes can be installed, sometimes not.

### Test code to reproduce

yarn add cypress --dev or
npm install cypress --save-dev

### Versions

cypress 4.5.0, mac os catalina 10.15.4, google chrome

**Comment by jennifer-shehane** [comment]
- How many mbps is your dl running a speed test? https://fast.com/
- How long is 'forever'? How long does it take to download completely?
- Is it completely failing to install sometimes?

After downloading the first time, the binary should be cached so you don't need to install again until an upgrade.

I live in asia also and it takes about 1min total to download, unzip, and install and I don't have the best internet download speed tbh.

**Comment by zac11** [comment]
Hmmm. I have installed it multiple times today and I do not see any such issue. I was able to finish the process in 3-4 mins max. Are you behind any proxy?

**Comment by rucciva** [comment]
I'm experiencing this too. i live in Indonesia

<img width="1084" alt="Screen Shot 2020-05-27 at 17 41 47" src="https://user-images.githubusercontent.com/4647473/83009718-5bb30a00-a041-11ea-84d4-e1688054ddba.png">

**Comment by bekicot** [comment]
I also from Indonesia. I'm using Indihome. After switching to Indosat network, cypress installation is reasonably fast. On Indihome, it stuck at 3%.

**Comment by recitogigih** [comment]
> I'm also live in Indonesia. I'm using Indihome. After switching to Indosat network, cypress installation is reasonably fast. On Indihome, it stuck at 3%.

thank you for the solution, so the problem is in the internet service provider

**Comment by rucciva** [comment]
But it could be the problem with the CDN right? i've seen similar [old issue](https://github.com/cypress-io/cypress/issues/1188#issuecomment-395446977)

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by dlodeprojuicer** [comment]
Having the same issue. I am in South Africa

**Comment by geoyws** [comment]
Having the same issue. Sometimes it takes 3+ minutes which is unusual when running `yarn`. I am in Kuala Lumpur.

**Comment by trainoasis** [comment]
Same here - Central Europe

**Comment by jennifer-shehane** [comment]
We believe this issue to be a problem localized to the network where Cypress is installed under and not an issue directly with Cypress.

**Comment by recitogigih** [comment]
@jennifer-shehane but i don't have any issue with another npm / yarn install

**Comment by RomanDavlyatshin** [comment]
Experiencing the same problem as well :(
Download speed (both with `npm install` and direct CDN download) is around 50-60kbps, this is unbearable.
![image](https://user-images.githubusercontent.com/34244611/128536914-9a3f72f3-faf0-47c5-bd26-4e64922e8f5b.png)
I am experiencing no issues with other packages/resources, my bandwidth is around 80Mbps
> We believe this issue to be a problem localized to the network where Cypress is installed under and not an issue directly with Cypress.

@jennifer-shehane Are you able to provide more info on the issue, please?
**Disclaimer:** I do understand that this is not something **every** member of the development team might  be aware of. I am asking just in case you are.

**Comment by RomanDavlyatshin** [comment]
As mentioned earlier, the speed test shows decent download speed (33-34mbps)
But cypress download is abysmally slow (~10% per 5 minutes)
So it's almost a one-hour installation, sometimes it gets worse, closer to 1h 30m
**Screenshot1** - Timer against `npm install cypress` log
![image](https://user-images.githubusercontent.com/34244611/133646102-a9c07a85-f3b6-4003-8b3a-2637ddc2fe53.png)
**Screenshot2** - Speed test results
![image](https://user-images.githubusercontent.com/34244611/133644327-4cabe96b-39a3-4257-ad30-f95954e7bd6a.png)

@jennifer-shehane can we count on any follow-up on the situation? 😭

**Comment by TheDiveO** [comment]
Cleared yarn cache, tried, tried at other times, but Cloudflare is a complete snail. Around 1mbit/s, with a 100mbit/s link. Other sites deliver as expected. Cloudflare does NOT.

**Comment by RomanDavlyatshin** [comment]
@TheDiveO @paul-vd There is a workaround: 
1. Download Cypress binaries from their CDN **once**
> - See [this docs page](https://docs.cypress.io/guides/getting-started/installing-cypress#Direct-download) for the link to the latest version of Cypress. Edit the version/platform parts of the URL `https://cdn.cypress.io/desktop/12.5.1/win32-x64/cypress.zip` manually to get earlier versions.
2. Upload these to the hosting of your choice (e.g. I've used GitHub: [windows](https://github.com/Drill4J/heisenbug-moscow-2021-workshop/releases/download/binaries/cypress-8.4.0-win32-x64.zip), [linux](https://github.com/Drill4J/heisenbug-moscow-2021-workshop/releases/download/binaries/cypress-8.4.0-linux-x64.zip), [macos](https://github.com/Drill4J/heisenbug-moscow-2021-workshop/releases/download/binaries/cypress-8.4.0-darwin-x64.zip))
3. **Prior** to running `npm install` set the npm config variable.
```
npm config set CYPRESS_INSTALL_BINARY "https://github.com/Drill4J/heisenbug-moscow-2021-workshop/releases/download/binaries/cypress-8.4.0-linux-x64.zip"` 
// mind the double quotes around URL
// note that the value is set in .npmrc and forces cypress to download the specific version
```
❗ EDIT ❗ A better solution (to allow Cypress to "autodetect" the appropriate platform/ use version from package.json) would probably be to [set a mirror url](https://docs.cypress.io/guides/getting-started/installing-cypress#Mirroring) and upload binaries for the required platforms/versions 
Reference in [Cypress docs](https://docs.cypress.io/guides/getting-started/installing-cypress#Environment-variables)

**Comment by BasixKOR** [comment]
![image](https://user-images.githubusercontent.com/7413880/152994515-a44430fd-8b53-48e8-b87d-28448fb6d5b7.png)

I was affected by this issue as well. My internet speed is fine as you can see above but it literally takes 16min+ to download this.

**Comment by jps** [comment]
I don't see why this is closed when this is clearly still an issue, it just too me 18mins, I'm on WSL also
![image](https://user-images.githubusercontent.com/350953/199333002-0d120c4d-3fb4-4360-b63e-b3c226bbe35b.png)

For reference I can download a 3.6gb ubuntu iso is 1min 30secs

**Comment by richardeschloss** [comment]
For me, I'm able to download cypress, it hangs on the linking step:

> cypress@npm:10.11.0 must be built because it never has been before or the last one failed

**Comment by BlessTheBoy** [comment]
I'm currently experiencing the same issue. Cypress installation getting stuck.
![image](https://user-images.githubusercontent.com/33803889/216672474-84f0825c-b21d-4513-a212-f886082751dd.png)

**Comment by RomanDavlyatshin** [comment]
@BlessTheBoy @BasixKOR @jps @tim-rohrer it seems Cypress team won't fix the issue 😞
I suggest using a workaround posted above
https://github.com/cypress-io/cypress/issues/7251#issuecomment-1008785294

**Comment by ihsanberahim** [comment]
Download from this repo. Click tab 'Code' > 'Releases' > choose latest zip released. ;)

**Comment by 1mehdifaraji** [comment]
I had the same issue but the network speed was the issue and later on cypress was installed successfully .

**Comment by tim-rohrer** [comment]
Doesn't sound like the same issue. At least in my case, the network & speeds were good.
