### ISSUE TITLE
CDP - Support for sessionId

### ISSUE THREAD

**Issue by EtienneBruines** [cypress-io/cypress#7256]
# Feature-Request

### Current behavior:

`Cypress.automation('remote:debugger:protocol', {})` supports two parameters:
- `command: string`
- `params: Object`

### Desired behavior:

An additional, optional parameter:
- `sessionId: string`

This way targets that are exposed via `Target.attachToTarget` can be reached. 

See https://github.com/aslushnikov/getting-started-with-cdp/blob/master/README.md#targets--sessions for details. 

### Test code to reproduce

N/A

### Versions

N/A

**Comment by flotwig** [comment]
@EtienneBruines Target selection will be implemented as part of #7942 so I am going to close this issue.
