### ISSUE TITLE
Cypress stdout undefined in upzip.js in unziptool during installation

### ISSUE THREAD

**Issue by xshyne88** [cypress-io/cypress#7261]
### Current behavior:
Unzip.js fails

```
/mnt/c/Users/foob/node_modules/cypress/lib/tasks/unzip.js:130
          sp.stdout.on('data', function (data) {
                    ^

TypeError: Cannot read property 'on' of undefined
    at unzipWithUnzipTool (/mnt/c/Users/foob/node_modules/cypress/lib/tasks/unzip.js:130:21)
```
### Desired behavior:
I'd like this to be able to unzip.

### Versions

OS: Windows 10 Running WSL Ubuntu 18.04
Node: 10.20.1
npm: 6.9.0
Cypress: 3.8.3

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by fruitbat2000** [comment]
@xshyne88 did you manage to get this working? I'm experiencing the same error with the latest version of Cypress (4.10.0)

**Comment by xshyne88** [comment]
Hey sorry for the late response, I actually did not get it working. The problem is that I can't bump the version since I am working on a pre existing code base. I've had to work around it for the time being.

@fruitbat2000 If you find a solution please DM me :)

**Comment by simrit-ibm** [comment]
@xshyne88 Hey, I am also facing the same error with Cypress(4.4.1). 
Can you please tell what did you do to get around this problem, is it something we can use as well?

**Comment by xshyne88** [comment]
Like I said above I did not get it working - I wasn't able to bump versions on the codebase I am working on since I do not have permissions to do so. My Cypress install fails and I've been just working around it for now.

@skribm9 @fruitbat2000  
Are you guys also using WSL? Maybe there's commonality between our specs.

**Comment by fruitbat2000** [comment]
@skribm9 @xshyne88 Rather embarrassingly for me, I'd forgotten that I'd switched to an older version of node for a client project. Reverting back to the latest stable node version (13.0.1) did the trick!

**Comment by xshyne88** [comment]
Yup I just tried Node 12.18 and it worked for me as well.
That was the solution, I was running Node on 10.x as well when it wasnt working

As a side note: 
Stdout being undefined is rather unusually which is why I ask if anyone else is using WSL, node finding stdout should be trivial - even on Node 10. I didn't pull up the offending unzip.js file to have a look but that would be my guess. 

@skribm9

**Comment by xshyne88** [comment]
@jennifer-shehane I think you can close this issue or resolve it being that cypress requires a version of node greater than 10.x

Thanks

**Comment by skribm9** [comment]
Thanks @xshyne88. 
Unfortunately, I cannot update node as Kibana requires Node 10.21.

**Comment by fruitbat2000** [comment]
@xshyne88 FWIW, yes, I'm running on WSL2

**Comment by xshyne88** [comment]
@skribm9 

lol aren't JS dependencies just the absolute best?
I wouldn't know how to solve that one. 

Our cypress runs on frontend repos,
Kibana is exclusively on our backend, unless you are using logstash or something like that?

I wish you luck - someone smarter than me will have to figure that out.

**Comment by skribm9** [comment]
@xshyne88 I am porting Kibana on s390x so will either drop support for RHEL 7.6/7.7, these are the only distros having this problem, else will patch the kibana to support node 12.18. 
Cypress install is working with Node 12.18. Thanks for this tip!

**Comment by jennifer-shehane** [comment]
@xshyne88 We actually only require Node 8 as of today (Cypress 5 will require Node 10+), but I bet we are not testing Node 8 + WSL combo.

**Comment by gpowers01** [comment]
I was having the same issue on WSL2 with Ubuntu 18.04 LTS distro.

OS Details:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎2/‎4/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0
Windows 10 Professional 

The project currently uses Node v10.19.0.

When trying to install cypress 6.3.0 (defined in package.json, installed with npm install from root of source tree), I would see the same errors as reported above:

```
/user/srcpathroot/node_modules/cypress/lib/tasks/unzip.js:130
          sp.stdout.on('data', function (data) {
                    ^

TypeError: Cannot read property 'on' of undefined
```

Looking at the cypress source for [unzip.js](https://github.com/cypress-io/cypress/blob/436ddfae833a64d19b17227768037466d8501c52/cli/lib/tasks/unzip.js#L102-L132), it appears to be spawning the system unzip command at unzip.js:102.  If the unzip binary is not on the system or in $PATH, unzipping will fail resulting in the error  on unzip.js:130.


The solution for us to continue using Node v10 was to install the unzip apt package in Ubuntu 18.04 LTS WSL2 distribution ( `apt install unzip` )

Upgrading Node to version greater than v12 also seems to work as previously reported, which _does not require_ installing the unzip apt package.
