### ISSUE TITLE
Public Cypress onError method

### ISSUE THREAD

**Issue by brentbaum** [cypress-io/cypress#727]
### Is this a Feature or Bug?

Feature

### Current behavior:

Cypress only detects errors that reach window.onerror

### Desired behavior:

Expose a public method on Cypress which allows you to throw errors into it.

Something like:
```
Cypress.onError(new Error("This will cause the current test to fail"));
```

**Comment by jennifer-shehane** [comment]
Closing. We are refactoring many of these error handlers and how you can listen to them in 4.0

**Comment by sharmadeepak43** [comment]
Hey @jennifer-shehane, Do we have that feature like Cypress.onError now ? Thanks!!
