### ISSUE TITLE
Recording video missing when opening a new link

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#7271]
Recording video missing when opening a new link on a new tab

```js
cy.visit('text1')

cy.wait(1000)
cy.get('li:nth-child(3) > span.t').trigger('mouseenter', {force: true})

cy.wait(1000)
cy.xpath('//a[text()="aaa"]').click()

cy.visit('text2')
```

### Versions
cypress： 4.0.1
system: linux
borwers: chrome 81

**Comment by jennifer-shehane** [comment]
Cypress does not support opening multiple tabs. See https://on.cypress.io/trade-offs#Multiple-tabs
