### ISSUE TITLE
Firefox flaky internal test: reload errors having no done() callback invoked.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7277]
### Current behavior:

Our internal test `src/cy/commands/navigation #reload errors logs once on failure - logs once on failure` fails sometimes when running in Firefox

<img width="1084" alt="Screen Shot 2020-05-08 at 4 47 19 PM" src="https://user-images.githubusercontent.com/1271364/81396611-bc8aa900-914b-11ea-868c-fbdd340b8b0a.png">

**CI Error**: https://circleci.com/gh/cypress-io/cypress/319161#tests/containers/3
**Test Code:** https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/commands/navigation_spec.coffee#L114:L114

```
     CypressError: Timed out after `100ms`. The `done()` callback was never invoked! (and Mocha's done() called multiple times)
  cypressErr@cypress:///../driver/src/cypress/error_utils.js:243:16
  errByPath@cypress:///../driver/src/cypress/error_utils.js:298:10
  patchRunnableResetTimeout/Runnable.prototype.resetTimeout/this.timer<@cypress:///../driver/src/cypress/mocha.js:178:27
```

### Desired behavior:

No flaky internal tests so I don't have to rerun status checks.

### Versions

`develop`

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by karem63** [comment]
Hi @jennifer-shehane, we are facing similar issue with out organization automation when running in chrome browser.

![image](https://user-images.githubusercontent.com/56069690/106775731-0c02f480-664c-11eb-8b15-8224278b6486.png)

**Comment by jennifer-shehane** [comment]
@karem63 The original issue was about our interneal tests - please open a new issue with a reproducible example.
