### ISSUE TITLE
cy.wait() does not resolve when the XHR contains static resource-like text in the XHR's query params or hash (like `.js`, `.html`, `.css`)

### ISSUE THREAD

**Issue by hudsonsdad** [cypress-io/cypress#7280]
### Current behavior:

Discovered this while trying to test for ad requests for my employer. When a URL with file extension, like .html, and a question mark (for a query string parameter) is visited, the request that is listened for is no longer detected. Remove the question mark, and the request is detected.

### Desired behavior:

Before promoting a build in production, we test the build using a query-string parameter, so the wish is for this to work when a query-string parameter is present in the visited URL.

### Test code to reproduce

```js
describe("Oregon Live Ads", () => {
  it("test cy.route()", () => {
    cy.viewport(1500, 1024);

    Cypress.on('uncaught:exception', () => {
      return false;
    });

    cy.server();

    cy.route({
      url: /gampad\/ads\?/,
    }).as("waitForAd");

    cy.visit(
      "https://www.oregonlive.com/news/2019/12/vaping-related-lung-illness-epidemic-has-likely-peaked-feds-say.html"
      , {qs: {answer: "42"}}  // When this is commented out, the test passes.
    );

    cy.wait("@waitForAd").then((req) => {
      expect(true).to.equal(true);
    });
  });
});
```
### Versions

Cypress Version: Cypress 4.2.0
OS: MacOS Catalina 10.15.2
Browser: Default Chrome browser that is built into Cypress

**Comment by jennifer-shehane** [comment]
Comparing the screenshots of commands when the test fails versus passes shows that the request for the `gampad/ads` XHR is not made when the site is visited with query params present.

Have you checked that this behavior actually works within the website (outside of Cypress) when query params are present?

*with query params*

<img width="1679" alt="Screen Shot 2020-05-11 at 5 53 47 PM" src="https://user-images.githubusercontent.com/1271364/81556641-ad586500-93b0-11ea-9c81-07b415f989dc.png">

*without query params*

<img width="1679" alt="Screen Shot 2020-05-11 at 5 54 07 PM" src="https://user-images.githubusercontent.com/1271364/81556665-b77a6380-93b0-11ea-9830-445abf66642b.png">

**Comment by hudsonsdad** [comment]
Hello, yes, when query params are present ads are still loaded through XHR requests.

![image](https://user-images.githubusercontent.com/58046999/81567271-18327d80-936a-11ea-9397-a48c1d053613.png)

**Comment by hudsonsdad** [comment]
> Comparing the screenshots of commands when the test fails versus passes shows that the request for the `gampad/ads` XHR is not made when the site is visited with query params present.
> 
> Have you checked that this behavior actually works within the website (outside of Cypress) when query params are present?
> 
> _with query params_
> 
> <img alt="Screen Shot 2020-05-11 at 5 53 47 PM" width="1679" src="https://user-images.githubusercontent.com/1271364/81556641-ad586500-93b0-11ea-9c81-07b415f989dc.png">
> 
> _without query params_
> 
> <img alt="Screen Shot 2020-05-11 at 5 54 07 PM" width="1679" src="https://user-images.githubusercontent.com/1271364/81556665-b77a6380-93b0-11ea-9830-445abf66642b.png">

Hello, yes, when visiting the URL with query params, the request for ads is still XHR requests w/ `gampad/ads` in the route.

![image](https://user-images.githubusercontent.com/58046999/81572918-d279b300-9371-11ea-89cb-59b923591ba0.png)

**Comment by hudsonsdad** [comment]
@jennifer-shehane, is there anything that I can do to help for this?

**Comment by hudsonsdad** [comment]
When the same test is run against a CNN article, because CNN uses an html file extension in their content URLs, if a query string is present, ad requests are not detected.  When the query string is removed, the ad requests are detected.

With Query String
![image](https://user-images.githubusercontent.com/58046999/83309503-75865580-a1d7-11ea-8914-84a6181ccb8e.png)

```
describe("CNN Ads", () => {
  it("test cy.route()", () => {
    cy.viewport(1500, 1024);

    Cypress.on('uncaught:exception', () => {
      return false;
    });

    cy.server();

    cy.route({
      url: /gampad\/ads\?/,
    }).as("waitForAd");

    cy.visit(
      "https://www.cnn.com/2020/05/29/politics/george-floyd-protests-american-racism/index.html"
      , {qs: {answer: "42"}}  // When this is removed, the test passes.
    );

    cy.wait("@waitForAd").then((req) => {
      expect(true).to.equal(true);
    });
  });
});
```

The same CNN article is tested without a query string...
![image](https://user-images.githubusercontent.com/58046999/83309724-0c531200-a1d8-11ea-8837-0a6ac3399765.png)

```
describe("CNN Ads", () => {
  it("test cy.route()", () => {
    cy.viewport(1500, 1024);

    Cypress.on('uncaught:exception', () => {
      return false;
    });

    cy.server();

    cy.route({
      url: /gampad\/ads\?/,
    }).as("waitForAd");

    cy.visit(
      "https://www.cnn.com/2020/05/29/politics/george-floyd-protests-american-racism/index.html"
      , {qs: {answer: "42"}}  // When this is removed, the test passes.
    );

    cy.wait("@waitForAd").then((req) => {
      expect(true).to.equal(true);
    });
  });
});
```


The BBC does not have an html file extension in their URLs, so the test passes regardless of whether or not a query parameter is present.

![image](https://user-images.githubusercontent.com/58046999/83309427-37893180-a1d7-11ea-9450-0398df29802b.png)


```
describe("BBC Ads", () => {
  it("test cy.route()", () => {
    cy.viewport(1500, 1024);

    Cypress.on('uncaught:exception', () => {
      return false;
    });

    cy.server();

    cy.route({
      url: /gampad\/ads\?/,
    }).as("waitForAd");

    cy.visit(
      "https://www.bbc.com/news/world-middle-east-52847175"
      , {qs: {answer: "42"}}  // The test passes for the BBC with and without this line of code.
    );

    cy.wait("@waitForAd").then((req) => {
      expect(true).to.equal(true);
    });
  });
});
```

**Comment by jennifer-shehane** [comment]
This fails regardless of the `qs` option being passed to the URL (just to rule out an issue with the `qs` option itself). So if you just type the query string in the `cy.visit()` url directly - it will also fail.

I didn't see any evidence of this being a regression.

`spec.js`

```js
it('test cy.route()', () => {
  cy.on('uncaught:exception', () => {
    return false;
  });
  cy.viewport(1500, 1024)
  cy.server()
  cy.route(/gampad\/ads\?/).as('waitForAd')
  cy.visit('https://www.oregonlive.com/news/2019/12/vaping-related-lung-illness-epidemic-has-likely-peaked-feds-say.html'
  , { qs: { answer: 42 }} // comment out this line to pass test
  )
  cy.wait('@waitForAd')
})
```

You can see that the request is made in both situations, just one does not get picked up by our `cy.wait()`. So this is not affecting the behavior of the site itself, just making it so you cannot use `cy.wait()` for this specific request.

**Comment by hudsonsdad** [comment]
@jennifer-shehane - yes, this fails when going through qs or when the query param is in the visited URL. A key/value pair doesn't even need in the query param. The question mark, alone, at the end of the visited URL with a file extension will cause the test to fail.

**Comment by jennifer-shehane** [comment]
We've identified why this is happening in your case. 

The presence of query params in the visited URL essentially changes some of the query params in the request made by the securepubads ad. 

Cypress inherently hides non XHR resources from the Command Log and from being recognized by `cy.route()`/`cy.wait()`. We do this by looking at the request URL and ignoring URLs that seemingly are static resources (containing things like `.html`, `.js`, `.css`, etc. 

The XHR request you wanted to listen to in your case contained some of the keywords we're looking to ignore in the query params of the request (only matching when the main URL contained query params) like below:

>https://securepubads.g.doubleclick.net/gampad/ads?...&url=https://www.oregonlive.com/news/2019/12/vaping-related-lung-illness-epidemic-has-likely-peaked-feds-say.html

I've opened a pull request to first remove anything from the query params and the hash before Cypress looks for resources to ignore. https://github.com/cypress-io/cypress/pull/7742 This fixes your issue. 

### Reproducible example

A better reproducible example of the original issue: 

```js
it('test cy.route()', () => {
  cy.server()
  cy.route(/url-with-query-param/, { foo: 'bar' }).as('getQueryParam')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    // our XHR has `.js` in it, which we normally ignore as XHR resource
    xhr.open('GET', '/url-with-query-param?resource=foo.js')
    xhr.send()
  })
  cy.wait('@getQueryParam')
})
```

**Comment by hudsonsdad** [comment]
Thank you very much, @jennifer-shehane!
