### ISSUE TITLE
Generating SecurityError when trying to visit a site

### ISSUE THREAD

**Issue by llopez1** [cypress-io/cypress#7285]
### Current behavior:
When I run those code on my local, I get a security error message. I am new to Cypress, so I was following a tutorial video on Youtube (link: https://www.youtube.com/watch?v=yzfp85bVUjY&list=PLUDwpEzHYYLu4jKg-rNSKH3aJeBinlPXp&index=12) and on 4:19 the instructor runs the code without any errors, but in my example when i have the same code I get a security error. 

Code used: 
```js
/// <reference types="Cypress" /> 

describe('Suite Name', function() {
    it('Alerts', function() {
        cy.visit('https://mail.rediff.com/cgi-bin/login.cgi')
        cy.get('input[type=submit]').click()
    }) 
})
```

<img width="1206" alt="Screenshot 2020-05-08 at 1 35 39 am" src="https://user-images.githubusercontent.com/26658575/81430225-f344cd00-9113-11ea-90aa-efea5404ea00.png">

### Desired behavior:
I expect the test to pass with out any errors

### Test code to reproduce
```js
/// <reference types="Cypress" /> 

describe('Suite Name', function() {
    it('Alerts', function() {
        cy.visit('https://mail.rediff.com/cgi-bin/login.cgi')
        cy.get('input[type=submit]').click()  
    }) 
})
```

### Versions

Operating system:  macOS 10.14 Mojave,
Browser: Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
Duplicate of #4220
