### ISSUE TITLE
Types not exported in .d.ts

### ISSUE THREAD

**Issue by pedroclayman** [cypress-io/cypress#7309]
### Current behavior:
The  types declared in cypress-npm-api.d.ts cannot be used by calling code since they are not being exported. 

### Desired behavior:
The types should be exported in order to be usable.

### Test code to reproduce
N/A

### Versions
Cypress 4.5.0

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-167) by [Unito](https://www.unito.io/learn-more)

**Comment by kyrstenkelly** [comment]
I also see this and it is causing issues.

**Version:** Cypress 4.5.0

Trying to record results via the Module API and running into this: 
```ts
cypress.run({ env })
    .then((results: Cypress.CypressRunResults) => {
      logger.info(results.totalTests);
      logger.info(results.totalFailed);
    });
```
Results in:

```bash
error - Namespace 'Cypress' has no exported member 'CypressRunResults'.
```

**Comment by MCFreddie777** [comment]
Can we get an update on this? It's been already few minor versions since...

**Comment by jennifer-shehane** [comment]
We're open to PRs to implement this. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).
