### ISSUE TITLE
Unexpected behavior in internal scripts when passing empty --spec CLI argument

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7311]
Internal build scripts, notice the only different is presence of `--spec` argument without a value

<img width="1111" alt="Screen Shot 2020-05-12 at 10 33 42 AM" src="https://user-images.githubusercontent.com/2212006/81704641-10430e00-943c-11ea-84c8-74d312960912.png">

**Comment by jennifer-shehane** [comment]
This now fails with a more correct error - indicating that the `--spec` argument is missing. 

<img width="796" alt="Screen Shot 2020-07-14 at 4 57 36 PM" src="https://user-images.githubusercontent.com/1271364/87415535-324f3d00-c5f3-11ea-9467-a31054e7fc99.png">
