### ISSUE TITLE
Cookies cleared after beforeEach instead of before

### ISSUE THREAD

**Issue by markjackson02** [cypress-io/cypress#7312]
In the docs for the `clearCookies()` command, it mentions that cookies are cleared automatically before each test. I noticed this happens after the `beforeEach()` runs, but I think it should happen before. I can't think of any scenario where it would make sense for someone to use the previous cookies in the `beforeEach()` of the following test.

This would remove redundancy in my code. The first step of all my tests in my spec file is to navigate to the same page so I would like to put the `cy.visit()` in the `beforeEach()`. But this causes problems because the `cy.visit()` runs with the cookies from the previous test. My current workaround is to run `clearCookies()` manually in the `beforeEach()` before `cy.visit()`.

### Current behavior:

Cookies cleared after `beforeEach()`

### Desired behavior:

Cookies cleared before `beforeEach()`

### Test code to reproduce

N/A

### Versions

4.5.0

**Comment by jennifer-shehane** [comment]
Cookies are cleared within the `test:before:run:async` event which runs before the `beforeEach`. If you're experiencing behavior different than this, please provide a reproducible example.

```js
localStorage.debug = 'cypress:driver:runner'

describe('tests', () => {
  beforeEach(() => {
    console.log('BEFORE EACH')
  })

  it('test 1', () => {
    console.log('TEST 1')
  })

  it('test 2', () => {
    console.log('TEST 2')
  })
})
```

<img width="576" alt="Screen Shot 2020-05-14 at 12 15 07 PM" src="https://user-images.githubusercontent.com/1271364/81897424-9d24cd80-95dc-11ea-9871-fad15ae3ecbf.png">
