### ISSUE TITLE
Error: Timed out retrying: Expected to find element: .blockbuilder-content-tool-name, but never found it.

### ISSUE THREAD

**Issue by bilal-bin-zafar** [cypress-io/cypress#7316]
Error: Timed out retrying: Expected to find element: .blockbuilder-content-tool-name, but never found it.
Find all the screen shots of code, error message, html and config.
![web element](https://user-images.githubusercontent.com/33050731/81748002-88541700-94c2-11ea-92e7-a8fa560e8439.png)
![code](https://user-images.githubusercontent.com/33050731/81748009-8b4f0780-94c2-11ea-9f1e-9ff342addedc.png)
![error log](https://user-images.githubusercontent.com/33050731/81748017-8e49f800-94c2-11ea-9f0b-af3be42d9e15.png)
![config](https://user-images.githubusercontent.com/33050731/81748236-ef71cb80-94c2-11ea-85e3-df478f556985.png)

**Comment by jennifer-shehane** [comment]
The React Email Editor uses iframes to display most of the content within their page, including the `.blockbuilder-content-tool` element. 

Cypress does not have full support for querying elements within iframes via `cy.get()`. See https://github.com/cypress-io/cypress/issues/136 for workarounds on how to access the iframe elements.

**Comment by bilal-bin-zafar** [comment]
@jennifer-shehane Thanks alot it worked!
