### ISSUE TITLE
Click function does not respect coordinates (x, y) if they are 0

### ISSUE THREAD

**Issue by panzarino** [cypress-io/cypress#7319]
### Current behavior:

`cy.click` will not respect either coordinate option if it is passed as 0. This is because a truthy comparison is used to set the default option, when it should really check if it is a finite number.

This issue is most likely present on right click and double click as well.

### Desired behavior:

`x` and `y` parameters can be 0 and the function will behave as it does for all other number values (and click the top left of the element).

### Test code to reproduce

```javascript
it('can specify x and/or y to be 0', () => {
  const $btn = $('<button id="click-button">clicking button</button>')
  .prependTo(cy.$$('body'))

  const position = $btn.offset()

  cy.on('log:changed', (log, attr) => {
    if (log.name === 'click' && attr._emittedAttrs.coords) {
      const args = attr._emittedAttrs.message.split(', ').map((i) => parseInt(i))
      const coords = attr._emittedAttrs.coords

      expect(coords.x).to.equal(coords.left)
      expect(coords.y).to.equal(coords.top)
      expect(coords.x).to.equal(position.left + args[0])
      expect(coords.y).to.equal(position.top + args[1])
    }
  })

  cy.get('#click-button').click(2, 2)
  cy.get('#click-button').click(0, 0)
  cy.get('#click-button').click(0, 2)
  cy.get('#click-button').click(2, 0)
})
```

**Comment by jennifer-shehane** [comment]
I was a little unsure what the behavior was before from the description, but basically it would click 'center' which is the default position and ignore all coords. Example:

```js
it('click 0 x coord', () => {
  cy.visit('https://example.cypress.io//commands/actions')
  cy.get('#action-canvas').click(0, 20)
});

it('click 0 y coord', () => {
  cy.visit('https://example.cypress.io//commands/actions')
  cy.get('#action-canvas').click(20, 0)
});

it('click 0 x 0  coord', () => {
  cy.visit('https://example.cypress.io//commands/actions')
  cy.get('#action-canvas').click(0, 0)
});
```

<img width="1345" alt="Screen Shot 2020-05-14 at 1 59 31 PM" src="https://user-images.githubusercontent.com/1271364/81905787-3f4bb200-95eb-11ea-810e-f41ebd01454f.png">
