### ISSUE TITLE
unable to call windows system env inside cypress

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#7325]
i was starting using cypress recently, and was trying to use process.env.MY_VAR that i was using in protractor before to call MY_VAR that is stored in windows, i keep getting undefined after checking some cypress documentation i saw that Cypress.env('MY_VAR') is alternative way 

so how exactly i can call system variable store in my machine either windows or bashrc for linux..etc 

```
const TEST_USER = Cypress.env('TEST_USER');

    proceed_to_login () {
        emailInput().should('be.visible').type(TEST_USER);
}
```

**Comment by davidlinse** [comment]
You'll have to setup a `cypress.env.json` or an `env` key in your `cypress.json`

best regards
~david

**Comment by Amrkamel1** [comment]
> You'll have to setup a `cypress.env.json` or an `env` key in your `cypress.json`
> 
> best regards
> ~david

could you elaborate more or provide sample, how this can be done

**Comment by Amrkamel1** [comment]
solved by adding 

module.exports = (on, config) => {
  config.env.E2E_ENV = process.env.E2E_ENV;
  return config
};

in plugin/index.js
