### ISSUE TITLE
Problem setting attribute

### ISSUE THREAD

**Issue by Eduardo-Carneiro-CM** [cypress-io/cypress#7332]
### Current behavior:
Cypress is not adding the new attribute to an element.

### Desired behavior:
When I run this line in Cypress code nothing happens but when I do it in DevTools it works:
```js
Cypress.$(stringButton).attr("markerBtn", "x")
```

I would like to be able to set this new attribute in the code, because I need to look for it later in the test

**Comment by jennifer-shehane** [comment]
The examples below work. Please provide a fully failing example. Make sure to [this section of our docs](https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous) noting that `Cypress.$()` runs synchronously.

```js
it('adds attr',  () => {
  cy.visit('https://example.cypress.io/commands/querying')
  cy.get('button').first().then(($btn) => {
    $btn.attr('markerBtn', 'x')
  })
  cy.get('button').first().should('have', 'attr', 'markerBtn', 'x')
})

it('adds attr', () => {
  cy.visit('https://example.cypress.io/commands/querying')
  cy.wrap(Cypress.$('button')).invoke('attr', 'markerBtn', 'x')
  cy.get('button').first().should('have', 'attr', 'markerBtn', 'x')
})
```
