### ISSUE TITLE
GUI - Folder/File sorting by type then by alphanumeric

### ISSUE THREAD

**Issue by Mat-Longinow** [cypress-io/cypress#7334]
### Current behavior:

Currently right now the GUI sorts items purely by alphabetical which is contrary to what you will find in IDE's. This becomes more problematic the more items you add to the mix.

![Screen Shot 2020-05-13 at 10 00 47 AM](https://user-images.githubusercontent.com/6404079/81842826-8bbac300-9501-11ea-9e49-fdf93cff69b8.png)

### Desired behavior:

Match how IDE's sort, first by type, then by alphanumeric.

**Comment by bhavish23** [comment]
Hii @jennifer-shehane, can I work in this issue.

**Comment by seongwon-kang** [comment]
I'm working on this.
