### ISSUE TITLE
Trying to add a command that already exists should throw an error

### ISSUE THREAD

**Issue by vitmalina** [cypress-io/cypress#7342]
There are many cy commands. It is easy to overwrite one unintentionally

### Current behavior:

```js
Cypress.Commands.add('click', { prevSubject: true }, (subj) = {
   cy.log('error')
}) => {})
```

Allows to overwrite click.

### Desired behavior:

it should throw an error saying that command exists and you should do .overwrite()

### Test code to reproduce

```js
Cypress.Commands.add('click', { prevSubject: true }, (subj) => {
   cy.log('error')
})
```

### Versions

Cypress: Version 4.4.0 (4.4.0.300671)
MacOS Catalina
Chrome: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
Yah, this is unexpected. 

```js
Cypress.Commands.add('click', { prevSubject: true }, (subj) => {
  cy.log('MY CLICK')
})

it('test', () => {
  cy.visit('https://example.cypress.io/commands/querying')
  cy.get('button').first().click()
});
```

<img width="447" alt="Screen Shot 2020-05-14 at 1 35 08 PM" src="https://user-images.githubusercontent.com/1271364/81903414-bed78200-95e7-11ea-8a57-e1d0588c557f.png">

**Comment by emilyrohrbough** [comment]
In Cypress 11.0, this is not longer an issue. Using the example provided, I received this error:
<img width="769" alt="Screen Shot 2022-11-16 at 4 19 49 PM" src="https://user-images.githubusercontent.com/14099737/202306906-7e67352e-52b1-43e4-a140-44a49cfacd0f.png">
