### ISSUE TITLE
For inline elements that wrap lines, the click funtion misses when the first child element has no width

### ISSUE THREAD

**Issue by panzarino** [cypress-io/cypress#7343]
### Current behavior:

For inline elements that wrap lines, sometimes the center of the bounding rect is not actually part of the element. So the first client rect is used in order to ensure that the `click` function does not miss when it attempts to click the element. In rare cases, this element may actually have no width, which results in a missed click as well.

### Desired behavior:

The `click` function should always properly click the element.

### Test code to reproduce

```html
<div style="width: 30px; line-height: 2;">
  <a href="#" id="overflow-link-width">
    <i style="display: inline-block;"></i>
    foofoofoofoofoo bar
  </a>
</div>
```

```javascript
cy.get('#overflow-link-width').click()
```

### Versions

4.5.0

**Comment by jennifer-shehane** [comment]
@panzarino Is this not this issue? https://github.com/cypress-io/cypress/issues/7012

**Comment by panzarino** [comment]
@jennifer-shehane Yeah that's the issue, Brian had indicated I had to open a new issue but I guess I was mistaken. I can close this issue and link the PR to that one.

**Comment by Bkucera** [comment]
Fixed in #7344

**Comment by Saibamen** [comment]
If fixed - close this bug report

**Comment by panzarino** [comment]
The code for this is done in [cypress-io/cypress#7344](https://github.com/cypress-io/cypress/pull/7344), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
