### ISSUE TITLE
the dashboard can't catch the last request

### ISSUE THREAD

**Issue by GongJS** [cypress-io/cypress#7347]
when i run the test, i find the dashboard can't catch the last request, this is my code:
```js
const getIframeDocument = () => {
    return cy
        .get('iframe[id="login-iframe"]')
        .its('0.contentDocument').should('exist')
}

const getIframeBody = () => {
    // get the document
    return getIframeDocument()
        // automatically retries until body is loaded
        .its('body').should('not.be.undefined')
        // wraps "body" DOM element to allow
        // chaining more Cypress commands, like ".find(...)"
        .then(cy.wrap)
}

const username = Cypress.env('username')
const password = Cypress.env('password')
context('Misc', () => {
    beforeEach('test', () => {
        cy.visit('.........GOUT=&loginChannel=PC')
    })
    it('test', () => {
        getIframeBody().find('.domain-body-input-control-username').should('exist').type('gong.gjs')
        getIframeBody().find('.domain-body-input-control-userpass').should('exist').type(password)
        getIframeBody().find('.domain-body-submit-control-submit').should('exist').click()
        cy.wait(5000)
        cy.visit('https://kbservcenter.alipay.com/sale/index.htm#/shop?_k=efixxr')
        cy.get('.anticon-qrcode').should('exist')
    })
})
```
the test result:

![06D50A84-9CA5-4FAB-8F58-D38BCC1D48CD](https://user-images.githubusercontent.com/25744301/81935008-81441a80-9622-11ea-88c9-336087d15ea2.png)

![9E808C6C-8B6C-4C7C-AFBC-6A5A06274943](https://user-images.githubusercontent.com/25744301/81934559-bdc34680-9621-11ea-9da1-31f36cacac51.png)

**Comment by jennifer-shehane** [comment]
Is this request made on the same domain? Is this request initiated from within the iframe?

**Comment by GongJS** [comment]
> Is this request made on the same domain? Is this request initiated from within the iframe?
 yes, it is, as you can see:
![image](https://user-images.githubusercontent.com/25744301/82230087-d901bf00-995d-11ea-8716-c21738051912.png)

![image](https://user-images.githubusercontent.com/25744301/82230183-f8005100-995d-11ea-83f1-cd675da2395d.png)

![image](https://user-images.githubusercontent.com/25744301/82230276-19613d00-995e-11ea-9e2e-2bd85505ebb0.png)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
