### ISSUE TITLE
`cy.spread` doesn't work on selections

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#735]
- Operating System: OSX Sierra
- Cypress Version: 1.0.1
- Browser Version: Chrome 61

### Is this a Feature or Bug?
Bug

### Current behavior:
`cy.spread` doesn't work when I pass a `cy.get` selection of multiple elements.

### How to reproduce:
Create a table to test:
```html
<table><thead><tr>
  <th>First</th>
  <th>Second</th>
  <th>Third</th>
</tr></thead></table>
```

Test:
```js
cy.get('table thead th').spread((first, second, third) => {
});
```

![image](https://user-images.githubusercontent.com/963136/31503725-b33365aa-af70-11e7-8b61-96252dda5e73.png)

**Comment by jennifer-shehane** [comment]
The code for the spread command: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/connectors.coffee#L266

`.spread()` initially does a check using Lodash `_.isArray()` and throws the error you saw above if it returns false: `cy.spread() requires the existing subject be an array.` 

We should probably loosen up the `.spread()` command to work on 'array-like' objects.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/783
