### ISSUE TITLE
Is there a way to proxy mocked routes

### ISSUE THREAD

**Issue by liamkeily** [cypress-io/cypress#7350]
I know you can mock routes with  `cy.route('GET', 'settings', 'fixture:settings/index.json');`

We are running a OpenAPI Mock Server ([Prism](https://stoplight.io/open-source/prism/)) which returns deterministic examples. We would like to use these responses as our fixtures if possible so we don't need to maintain a separate set of fixtures.

It would be great if we could do something like `cy.route('GET', 'settings', 'proxy:http://localhost:4041/settings')` in our tests which proxies the requests (including body & headers).

Is there anything like this in Cypress? Or an API that i might be able to use to implement something like this

**Comment by flotwig** [comment]
Hey @liamkeily, Cypress has support for HTTP proxies, so you should be able to use Prism's HTTP proxy with it like so on macOS/Linux:

```shell
HTTP_PROXY=http://localhost:4041 cypress run ...
```

Otherwise, #4176 will add support for users to dynamically proxy/handle mocked routes at the HTTP level.
