### ISSUE TITLE
scrollIntoView randomly not being called

### ISSUE THREAD

**Issue by TheDutchCoder** [cypress-io/cypress#7351]
### Current behavior:
Unfortunately this bug is random (in my experience).
Sometimes `.scrollIntoView()` seem to simply not get executed. Neither does the scroll occur, nor does the log show it was called, even though it's in the code.

### Desired behavior:
To actually work all the time.

Here's a screenshot of the code and the log:
![image](https://user-images.githubusercontent.com/1668207/81962702-1672ef00-95e2-11ea-99f6-71ed3fca6e27.png)

![image](https://user-images.githubusercontent.com/1668207/81962629-fe02d480-95e1-11ea-801d-e039d9b7338a.png)

### Test code to reproduce
I'm not sure how easy this is to reproduce, I'm hoping it's replicable at all.

### Versions

Cypress: 4.5.0
Mac OS: Mojave 10.14.6
browser: Chrome 81

**Comment by TheDutchCoder** [comment]
To add to this, I seem to be experiencing issues when using `await` after the scroll.
If I remove that it seems to get called, if I leave it, the entire statement is for some reason skipped.

**Comment by jennifer-shehane** [comment]
There's no reason to use `await` with Cypress in this way. The `cy.get()` command will not execute until all previous Cypress commands are done executing. See this issue: https://github.com/cypress-io/cypress/issues/1417

If you need a specific command to check longer than the default 4 seconds, increase the timeout. `cy.get('el', {timeout: 10000})`.

I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [commands being async/serial](https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous).
