### ISSUE TITLE
Tests fail in headless chrome and firefox but pass in headless electron

### ISSUE THREAD

**Issue by eabusharkh0** [cypress-io/cypress#7354]
### Current behavior:

When I run a specific test in headless in either chrome 81 or firefox it fails after it clicks on the button, but when I run the same test headless with electron it passes.

### Desired behavior:

Tests should pass in headless mode regardless of the browser being used.

### Test code to reproduce

```js
import "../../../support/commands";

describe("Edit Company Profile", () => {
  beforeEach(() => {
    Cypress.on("window:before:load", (win: any) => {
      win.usabilla_live = win.usabilla_live || function () {};
    });
  });
  it("Edit Company Profile", function () {
    const env = Cypress.env();
    cy.clearCookies();
    Cypress.config("pageLoadTimeout");
    Cypress.config("defaultCommandTimeout");

    cy.loginMear(
      env.usernameAdmin,
      env.passwordAdmin,
      env.mearUrl + "/daf/servlet/DAFctrl?op=1163"
    );

    cy.get('#groupName').type("EssamGP1");
    cy.get('#search-button').click();

    cy.get('#editCompanyInfo').click();
    cy.get('#companyInfoLabel_1').clear().type('Automation Company');
    cy.wait(3000);
    cy.get('#companyInfoLink_1').clear().type('www.dice.com');
    cy.wait(3000);
    //cy.wait(10000);
    cy.get('#companyInfoCPsubmit-button').click({ force: true });

//Assertion
    cy.get('#companyInfoLinks > li > a').should('have.text', 'Automation Company');

    cy.get('#editCompanyOverview').click();
    cy.get('#companyOverviewText').clear().type('Essam Company is currently accepting resumes for a variety of positions. Please review the database of positions that we are seeking to fill and contact us for additional information about any specific opportunity.');
    //cy.wait(10000);
    cy.get('#companyOverviewCPsubmit-button').click({ force: true });
//Assertion
    cy.get('#networkCompanyOverview').should('contain', 'Essam Company is currently accepting resumes for a variety of positions. Please review the database of positions that we are seeking to fill and contact us for additional information about any specific opportunity.');

    cy.get('#editCompanyVideos').click();
    cy.get('#companyVideo_1').clear().type('www.dice.com');
    //cy.wait(10000);
    cy.get('#companyVideosCPsubmit-button').click({ force: true });

//Assertion
    cy.get('#VideoOutputDiv1 > a').should('have.text', 'www.dice.com');

  });
});
```

**Comment by eabusharkh0** [comment]
video attached.

[EditCompanyProfile.spec.ts.zip](https://github.com/cypress-io/cypress/files/4630585/EditCompanyProfile.spec.ts.zip)

**Comment by jennifer-shehane** [comment]
It may be just a difference in execution of timing where the test will randomly fail at times when executed with different timings. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

None of the provided code is runnable - there is no url to visit provided and I'm not sure where the failure is in the tests provided. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by eabusharkh0** [comment]
@jennifer-shehane 
sorry, totally forgot to include the url and user and password.  Replace the username with 'essam.abusharkh@dhigroupinc.com' and password with 'Smart-tiger1'.  Also replace the URL with 'https://employer.dicepilot.com/daf/servlet/DAFctrl?op=1163'.  The login command in the commands file is down below.  Please let me know if you need additional information for me to provide, I'll need to reset the password after we are done resolving this issue.
Cypress.Commands.add(
  "login",
  (email: string, password: string, url: string) => {
    cy.log(email);
    cy.log(password);
    const env = Cypress.env();
    cy.request({
      method: "POST",
      url: env.employerUrl + "/ajaxLogin",
      body: {
        username: email,
        password: password
      },
      headers: {
        Accept: "application/json",
        "Content-Type": "application/x-www-form-urlencoded"
      }
    });
    cy.visit(url);

      cy.wait(10000);

          cy.get('body').then(($body) => {

                  if ($body.find('.usabilla__overlay > iframe').length == 0) {
                      //cy.wait(1000);
                      cy.log('usabilla not found');
                      cy.log('inside if');
                  } else {
                      cy.get(".usabilla__overlay > iframe").then(frame => {
                          const iframe = frame.contents();
                          const close = iframe.find("#close");
                          cy.wrap(close).click();
                      });
                  }
          });
      }

);

**Comment by eabusharkh0** [comment]
you can also replace pageLoadTimeout and defaultCommandTimeout with '60000'.
