### ISSUE TITLE
Count active ajax requests

### ISSUE THREAD

**Issue by eduardo-dias2020** [cypress-io/cypress#7358]
# Current behavior:

`$.active` is always returning 0, so I searched for other method

### Desired behavior:

I have tried to use this function on DevTools and it works perfectly but in Cypress it never works, I tried to add it on `Cypress.on('document:after:load', document)`.

```javascript
$(function() {
    $(document).ajaxSend(function() {
        ajaxCounter++;
        console.log("New Request! There are " + ajaxCounter + " requests running.");
    }).ajaxComplete(function() {
        ajaxCounter--;
        console.log("Request finished! There are " + ajaxCounter + " requests running.");
    });
});
```

I would like to be able to count the active ajax requests, and the function should be added after each page load.

Chrome

**Comment by jennifer-shehane** [comment]
If you believe this to be a bug in Cypress, can you provide a fully reproducible example - with code that fires ajax requests that are not being counted? A repo would be ideal. 
Unfortunately we'll have to close this issue without a full repro.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by eduardo-dias2020** [comment]
Unfortunately I can't provide the code, but I believe this can be tested with any repo
