### ISSUE TITLE
Installing Cypress without a package.json leads to a dead end.

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress#736]
- Operating System: MacOS Sierra (10.12.5)
- Cypress Version: 1.0.1
- Browser Version: N/A

### Is this a Feature or Bug?

Bug

### Current behavior:

Running `npm install cypress` in an empty directory or a directory without a `package.json` file
displays confusing output. 
1. Instead of installing in the current directory, it appears to install in the home directory
1. Text is displayed saying I can open cypress by running `node_modules/.bin/cypress open` which will not work since it is not installed in the current directory

### Desired behavior:

Cypress to install in the current directory or error out saying that it can't install because it's an empty directory. Perhaps then guide someone to the global install.

### How to reproduce:

Run `npm install cypress` in an empty directory 

### Additional Info (images, stack traces, etc)

![screenshot 2017-10-12 12 33 09](https://user-images.githubusercontent.com/51821/31507689-8765bb98-af49-11e7-8637-2d1b5b60a71a.png)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
