### ISSUE TITLE
`cy.fixture()` timed out waiting `60000ms` to receive large fixture files.

### ISSUE THREAD

**Issue by mykhalchuk18** [cypress-io/cypress#7365]
When I run tests, sometimes it fails with such an error =>

![image](https://user-images.githubusercontent.com/40005510/82061336-3d5c1e80-96d1-11ea-89e9-35d3955ed18c.png)

This is my code:

```javascript
before(() => {
  cy.fixture("monitors/monitorsTestIds.json").then((data) => {
    testIds = data;
  });
  cy.fixture("monitors/monitorsHelpIds.json").then((data) => {
    monitorsHelpIds = data.activeFan;
  });
  cy.fixture("monitors/activeMonitors/monitorsData.json").then((data) => {
    fanActiveMonitorData = data.activeFan;
    generalInfo = data.generalInfo;

    cy.deleteMonitorIfExistsAPI(fanActiveMonitorData.defaultMonitorConfig.name, generalInfo.monitorActiveType);
  });
  cy.fixture("monitors/activeMonitors/ciscoSnmpObjects.json").then((data) => {
    snmpObjects = data;
  });
  cy.fixture("monitors/activeMonitors/device.json").then((data) => {
    mimicDevice = data;
  }).then(() => {
    let networkAddress = mimicDevice.templates[0].interfaces[0].networkAddress;
    cy.deleteDevicesIfExist(networkAddress);
    cy.initMimic(networkAddress, mibs, ifName).then((agentNumber) => {
      Cypress.env('fanTestAgentNumber', agentNumber);
    });
  });
  cy.patch_request(Cypress.env('baseApiUrl') + deviceTemplateUrl, deviceTemplatePath, Cypress.env('token')).then((response) => {
    Cypress.env('deviceIdToBeTested', response.responseBody.data.idMap[0].resultId);
  });
});
```

Maybe I'm doing something wrong or could you please help me to overcome this issue ?

**Comment by panzarino** [comment]
@mykhalchuk18 There is an option to increase the timeout, which you can pass as `{timeout: 100000}`.

See https://on.cypress.io/fixture#Arguments

**Comment by jennifer-shehane** [comment]
Are you generating the fixture files at some point within your tests? 

The only reason this should timeout is if the file was not found at the location - is it possible the file doesn't exist at some times or are they statically always existing within that directory?

**Comment by mykhalchuk18** [comment]
@jennifer-shehane The fixture files are statically always existing within that directory.

**Comment by krutztq** [comment]
We have the same problem. The fixture command gets a timeout infrequently even if the file is found with cy.exec(ls file).
Here is the relevant code:
```
Cypress.Commands.add("upload", (selector, url) => {
	const fileName = url.substring(url.lastIndexOf('/')+1);

	cy.exec(`wget ${url} -O ${Cypress.config('fixturesFolder')}/${fileName}`);
	cy.exec(`ls ${Cypress.config('fixturesFolder')}/${fileName}`)
	cy.fixture(fileName, 'base64').as('imageFile');
	...
    });
})

describe('Test', () => {
    describe('Test 1', () => {
	it('should be done successfully', () => {
		cy.upload(...)
		...
	})
    })

    describe('Test 2', () => {
	it('should fail', () => {
		cy.upload(...)
		...
	})
    })
})
```

Possible Workaround:
Currently this strange behavior could not be reproduced if I use separate files for 'Test 1' and 'Test 2'.

**Comment by jennifer-shehane** [comment]
I think this may occur if the fixture file is very large, where the file will not load within 60secs. Is your fixture file a larger file? 

I can recreate this with an 11mb file, for example, setting the commandTimeout to be a bit lower. I'm not sure how big a file would have to be to not load in 60 seconds. 

```js
it('large fixture', () => {
  cy.fixture('large_11mb', {timeout: 10000}).then((data) => {
    console.log(data)
  })
})
```

<img width="523" alt="Screen Shot 2020-08-12 at 3 04 29 PM" src="https://user-images.githubusercontent.com/1271364/89993791-3f705200-dcad-11ea-8c33-8c7f14fcd6dd.png">

**Comment by krutztq** [comment]
In fact, the error is more common with large files. Our file has a size of ~80 MB.

**Comment by xumepadismal** [comment]
I have the same problem. Sometimes it can handle it properly within 10 secs but if it fails then it fail even with timeout `240_000ms`… My file is 60MB (flac) and it statically stored in "fixtures" folder.

**Comment by webnexusmobile** [comment]
I found a workaround by circumventing cy.fixture() with a task

```
//cy.fixture(filename).then(jsonPayload => {
cy.task('readBigFile', 'cypress/fixtures/big_file.json).then(jsonFile => {
  cy.wrap(JSON.parse(jsonFile)).then(jsonPayload => {
    cy.request({
        method: 'POST',
        url: '/import',
        body: jsonPayload,
        timeout: 120000
      })
  })
}
```
plugins/index.js
```
const fs = require('fs')
//...
  on('task', {
    readBigFile (filename) {
      if (fs.existsSync(filename)) {
        return fs.readFileSync(filename, 'utf8')
      }
      return null
    }
  })
```
But this was only semi successfull because the task takes quite some time and the request occasionally runs into timeout when sending the big JSON as a payload :( This might be connected to this issue: https://github.com/cypress-io/cypress/issues/6385

**Comment by rh4ll** [comment]
I get the same with a 100k .jpg

**Comment by lorenzogrv** [comment]
Has anyone got a similar problem with directories containing large number of small fixture files?
