### ISSUE TITLE
cypress screenshot naming not matching with mochaawesome naming 

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#7369]
im trying to generate mocha awesome report with attached screenshot on failure but picture is not appearing, as there is differences in naming as shown below

how to make both naming matching

![image](https://user-images.githubusercontent.com/32042806/82072860-a1361580-96d8-11ea-936d-269374784caa.png)

```js
const titleToFileName = (title) => title.replace(/[:\/]/g, '');

Cypress.on('test:after:run', (test, runnable) => {
    if (test.state === 'failed') {
        const filename = `${titleToFileName(runnable.parent.title)} -- ${titleToFileName(test.title)} (failed).png`;
        addContext({ test }, `../screenshots/${Cypress.spec.name}/${filename}`);
        addContext({ test }, `../videos/${Cypress.spec.name}.mp4`);
    }
});

```

**Comment by jennifer-shehane** [comment]
You'll want to use the `after:screenshot` task to get the accurate name of the screenshot taken within Cypress for any manipulation of the files. https://on.cypress.io/after-screenshot-api#Syntax

If an assertion failed in a hook, there is no associated test title so the title is generated differently.
