### ISSUE TITLE
VS Code terminal detects different browsers than OS terminal

### ISSUE THREAD

**Issue by ianschmitz** [cypress-io/cypress#7374]
### Current behavior:

`npx cypress info` in my project returns different detected browser results when running from the Ubuntu default terminal, versus VS Code's built in terminal. It took me quite a while to figure out why i couldn't launch Chromium when running my Cypress tests from VS Code.

From VS Code terminal:

```bash
$ npx cypress info
Displaying Cypress info...

Detected 1 browser installed:

1. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 76.0.1
  - Executable: firefox
  - Profile: /home/ian/.config/Cypress/cy/production/browsers/firefox-stable

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: /home/ian/.config/cypress/cy/development
Browser Profiles: /home/ian/.config/cypress/cy/development/browsers
Binary Caches: /home/ian/.cache/Cypress

Cypress Version: 4.5.0
System Platform: linux (Ubuntu Linux - 20.04)
System Memory: 16.8 GB free 8.66 GB
```

From Ubuntu terminal:

```bash
$ npx cypress info
Displaying Cypress info...

Detected 2 browsers installed:

1. Chromium
  - Name: chromium
  - Channel: stable
  - Version: 81.0.4044.138
  - Executable: chromium
  - Profile: /home/ian/snap/chromium/current

2. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 76.0.1
  - Executable: firefox
  - Profile: /home/ian/.config/Cypress/cy/production/browsers/firefox-stable

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser chromium
- cypress run --browser firefox

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: /home/ian/.config/cypress/cy/development
Browser Profiles: /home/ian/.config/cypress/cy/development/browsers
Binary Caches: /home/ian/.cache/Cypress

Cypress Version: 4.5.0
System Platform: linux (Ubuntu Linux - 20.04)
System Memory: 16.8 GB free 8.68 GB
```
I also tried explicitly passing in the `--browser` CLI argument in VS Code as such:

```bash
$ which chromium
/snap/bin/chromium
$ npx cypress run --browser /snap/bin/chromium
We could not identify a known browser at the path you provided: `/snap/bin/chromium`

The output from the command we ran was:
```

I'm not confident this is an issue with Cypress. Would be great to hear if anyone else is running into this, and at the very least this provides a work around.

### Desired behavior:

Browsers are correctly detected in both terminals.

### Test code to reproduce

I don't believe there's anything unique to my system that should make this hard to reproduce. I have the same issue across two different systems running relatively fresh installs of Ubuntu 20.04 LTS.

I wonder if there may be something going on with the behavior of both VS Code and Chromium being installed as snap packages? Let me know if there's anything i can do from my end to help debug.

### Versions

Cypress - 4.5.0
OS - Ubuntu 20.04
VS Code - 1.45.1 installed via snap
Chromium - 81.0.4044.138 installed via snap

**Comment by jennifer-shehane** [comment]
We recently had to update our code on how to determine snap Chrome installations - relevant code here: https://github.com/cypress-io/cypress/pull/7039/files#diff-61793cc57b4986c5b424d5bfc4764327R47 

Does `os.homedir()` return a different path when within VS Code and outside? https://nodejs.org/api/os.html#os_os_homedir

The path you pass should include the home directory `/home/ian/snap/chromium/current`, not just `snap/chromium/current`.

**Comment by ianschmitz** [comment]
Both return the same result:

```bash
~$ node -e 'console.log(require("os").homedir())'
/home/ian
```

Trying to include the home dir in both terminals resulted in:

```bash
$ npx cypress run --browser /home/ian/snap/chromium/current
We could not identify a known browser at the path you provided: `/home/ian/snap/chromium/current`

The output from the command we ran was:

 spawn /home/ian/snap/chromium/current EACCES
```

Even though that dir exists and is a symlink:

```bash
~/snap/chromium$ ll
total 20
drwxr-xr-x 5 ian ian 4096 May 22 13:17 ./
drwxr-xr-x 9 ian ian 4096 May 13 10:02 ../
drwxr-xr-x 6 ian ian 4096 May 13 09:48 1144/
drwxr-xr-x 6 ian ian 4096 May 22 13:17 1155/
drwxr-xr-x 3 ian ian 4096 Nov 22 10:20 common/
lrwxrwxrwx 1 ian ian    4 May 22 13:17 current -> 1155/
```

I'll do some more digging this weekend at the changes you pointed out and see what the diff is between terminals if possible.

Thanks for the help so far!

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
