### ISSUE TITLE
Cypress no longer ships with referenced types

### ISSUE THREAD

**Issue by agar23** [cypress-io/cypress#7376]
### Current behavior:
 Somewhere between v4.1 and 4.3 cypress stopped shipping with the typings it references on this [file](https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts#L14). This is causing errors such as: 
```
TS2304: Cannot find name 'beforeEach'.
````
since tsc cant find the respective typing files. 

This probably works fine if you use npm and add `@types/mocha` to your dependencies. Is the expectation to include these typing separately?  

This is breaking with pnpm since dependencies are not flat but rather nested. 

### Desired behavior:

Cypress supports using its Typings without added packages. 

### Versions 
4.3+

**Comment by Pictor13** [comment]
yes, on VSCode I solved by manually installing types:
```
npm install @types/cypress --save-dev
npm install @types/mocha --save-dev
```

Not sure why Cypress doesn't directly include them :shrug:
