### ISSUE TITLE
Cypress:Not able to upload a PDF file whose type is "text" and the attachment button is of tag img 

### ISSUE THREAD

**Issue by AkramPasha** [cypress-io/cypress#7385]
Hi,

I am trying to upload a pdf file using cypress.  where the HTML code is of not type 'file' it's 'text'

i have tried with following code for uploading the pdf file .

```js
cy.get("input[placeholder='No Files selected']").invoke('attr', 'type', 'file')
 const fileName = "sample.pdf"   // pdf is saved under fixture folder
 cy.fixture(fileName).then(fileContent => {
   cy.get('[type="file"]').eq(1).upload({ fileContent, fileName, mimeType: 'application/pdf' });
 })
```

it does not give any error but also it does not upload anything.

![image](https://user-images.githubusercontent.com/17572477/82176128-7a9ff680-98f3-11ea-96a6-3f820d0865d2.png)

The HTML code for the following image is 
![image](https://user-images.githubusercontent.com/17572477/82176486-8213cf80-98f4-11ea-9ccf-b914fd777dc6.png)

cypress version: 4.1.0

Thanks

**Comment by jennifer-shehane** [comment]
File upload is not natively supported in Cypress. I would see #170 for any recommended workarounds.
