### ISSUE TITLE
Getting blank page in cypress UI ,after running 2-3 steps of my test cases.

### ISSUE THREAD

**Issue by Gaurav98990** [cypress-io/cypress#7391]
### Current behavior: 

Getting blank page in cypress UI ,after running 2-3 steps of my test cases.

### Desired behavior: 

before 15th May 2020 it was working fine

### Test code to reproduce

I can't provide you with my code due to company policy 
this issue seems to be with many people [around](url)
![20200517_002521](https://user-images.githubusercontent.com/52884861/82194685-c8375600-9929-11ea-8abe-f04fcf06a16c.jpg)

### Versions 

cypress **version 3.8.3**

Electron

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed.

I would also track down exactly what changed in your project or your environment on May 15. Cypress is downloaded on your computer, so none of the Cypress app could have actually changed on May 15, it must be something else changed.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
