### ISSUE TITLE
Double Dock icons display for Cypress app

### ISSUE THREAD

**Issue by emijmker** [cypress-io/cypress#7393]
### Current behavior:
I just downloaded and installed Cypress 4.5.0 and when I start it, 2 icons are in the Dock. When I'm in the testrunner and I click the left one nothing happens, when I click the right one, then I'll get the overview of the integration tests on my screen. When closing them, again the left one does nothing, the right one dissappears including with the test runner.

![afbeelding](https://user-images.githubusercontent.com/35372494/82198603-d622b200-98fc-11ea-9db9-c7ba161c6d7d.png)

First time I'm seeing this, issue didn't occur in 4.1.0 or before that.
I made sure to close any older versions and remove those from the Dock first.

### Desired behavior:
Start up 1 instance of Cypress

### Test code to reproduce
Not test related, it's the GUI.

### Versions
Cypress 4.5.0
MacOs 10.14.6
Chrome 81.0.4044.138
Since it mattered in a previous issue, I downloaded 4.5.0, put it in Applications (Programma's) folder and renamed it with the version.
<img width="1182" alt="afbeelding" src="https://user-images.githubusercontent.com/35372494/82199007-695be780-98fd-11ea-8d60-67af5ca178b7.png">

**Comment by jennifer-shehane** [comment]
Can you be sure to kill all Cypress processes? `pkill -f cypress` 

How are you starting Cypress?

No one else has reported this issue, so I think this may be relevant to something on your machine.

**Comment by emijmker** [comment]
From the root or somewhere else? Tried it from the root, no change. I cleared up all Cypress stuff in Applications, first tried https://docs.cypress.io/guides/references/troubleshooting.html#To-clear-App-Data, then later just cleaned up Library/Application Support/Cypress entirely. Redownloaded and reinstalled again (desktop app, from https://www.cypress.io/). Start it from Applications by double clicking Cypress.app. First I see 1 Dock item, after the popup are you sure you want to open something from internet, the 2nd Dock icon pops up. Didn't do any renaming this time. I have no idea what else I can do 😅 , do you have some inspiration left?

**Comment by jennifer-shehane** [comment]
Is this showing up within your 'recent applications' portion of the dock? https://www.techjunkie.com/recent-applications-extra-icons-mojave-dock/ May be something similar to what happens with VSCode https://github.com/microsoft/vscode/issues/60579 but we're not likely to spend much time investigating truthfully unless more users run into this.

**Comment by helenakindred** [comment]
I have seen this issue from 4.3.0, also with 4.6.0. My colleague with a Mac has the same problem. Doesn't happen with 4.1.0, but I don't have other versions in between those 2.

**Comment by marc-guenther** [comment]
I'm on MacOS 10.12.6, and have exactly the same behavior.

- Download `cypress.zip` from www.cypress.io
- Double click to extract.
- Double click the resulting `Cypress.app`
- One Dock icon appears, and the warning about download from internet
- After clicking OK, a second identical Dock icon appears.

Second Dock icon has the main window, first icon only has a menu.

- When I quit the second Dock icon, both icons disappear
- When I quit the first Dock icon, the second one stays around

I have never experienced this before, because I install and run Cypress through `npm`:
```
npm install -D cypresss
npx cypress open
```
I do NOT get a second Dock icon in this case.

**Comment by ianrossd** [comment]
I also have this problem on v4.8. Though, I remember seeing this happening on v4.5 as well. I'm running MacOS 10.14.6 and checking Activity Monitor shows that the 1st instance's Parent Process is **launchd** and the 2nd one's is **Cypress**. I've also tried the troubleshooting steps on a previous version of Cypress as @emijmker, clearing everything and reinstalling but to no success.

**Comment by emijmker** [comment]
> Is this showing up within your 'recent applications' portion of the dock? https://www.techjunkie.com/recent-applications-extra-icons-mojave-dock/ May be something similar to what happens with VSCode [microsoft/vscode#60579](https://github.com/microsoft/vscode/issues/60579) but we're not likely to spend much time investigating truthfully unless more users run into this.

The show recent applications in Dock is unchecked. If I check it, the double icons appear in the recent applications portion of the dock. The VSC thread isn't helping. Something changed in the Cypress app causing this, since it didn't happen in 4.1.0.

Can confirm as well it's happening in 4.8.0.

**Comment by Meenakshi2018** [comment]
I am also seeing this issue since quite some time, it's really annoying and still happening with the latest version 4.11.0.

<img width="407" alt="Screenshot 2020-08-03 at 14 46 33" src="https://user-images.githubusercontent.com/35925081/89189731-52da3980-d598-11ea-9e4b-b22af0512539.png">

**Comment by attheshow** [comment]
I've had the same issue with 2 dock icons since I installed Cypress last year. Not a huge deal since I can just quit one of them and the other one that actually has the menu continues to operate. I also install using the .zip file (instead of npm) and I'm on version 6.5.0.

**Comment by lauhon** [comment]
Also experiencing it on a mac (M1).

For everytime I run cypress a new chrome icon gets added to the dock and it stays even after I kill cypress.
I kill cypress by pressing `cmd+c` in the terminal i ran cypress in

Not a big deal but i tiny bit annoying
