### ISSUE TITLE
Cannot redefine property: onerror

### ISSUE THREAD

**Issue by VladimirHumeniuk** [cypress-io/cypress#7395]
We are used Cypres v3.8 and had the next code, to redefine `onerror`:
```js
// patch Cypress top.onerror
Object.defineProperty(top, 'onerror', {
  value: window.onerror,
})
```

But after updating to Cypress v 4.5 we have the next error:
> Cannot redefine property: onerror

Is it possible to redefine Cypress top.onerror now somehow?

**Comment by jennifer-shehane** [comment]
Can you specify where you are calling this code from? Can you also explain a bit about why you want to redefine onerror, it might help in finding a better workaround. Thanks!

**Comment by VladimirHumeniuk** [comment]
@jennifer-shehane  we specified this code in `cypress/support/index.js`, our QAs need to for some Jenkins hooks or whatever.
