### ISSUE TITLE
Good to have more options on wait

### ISSUE THREAD

**Issue by saranyas72** [cypress-io/cypress#7397]
### Current behavior:

The current wait syntax : https://on.cypress.io/wait

### Desired behavior:

In selenium, we have something like these to wait until the element disappears.  It would be good if we have something simple (one-liner) and similar in cypress without returning yield.

```
wait.until
ExpectedConditions.invisibilityOf(element)
ExpectedConditions.invisibilityOfElementLocated(By),
!ExpectedConditions.presenceOfElementLocated(By)
```

**Comment by jennifer-shehane** [comment]
Cypress automatically waits for the element to meet the expectations your chained to its assertion. So there's no need to tell it to 'wait', it's automatic. 
I suggest reading the entirety of our [Introduction to Cypress]

(https://on.cypress.io/introduction-to-cypress) guide and our guide on built in [retry-ability](https://on.cypress.io/retry-ability)

To wait for an element to disappear, for example, you would write the code below, which will wait 4 seconds for the element to not be visible:

```js
cy.get('div').should('not.be.visible')
// or whatever your assertion is
cy.get('div').should('have.css', 'display', 'none')
```

You can increase the time Cypress waits by passing a larger timeout.

```js
cy.get('div', { timeout: 10000 }).should('not.be.visible')
```
