### ISSUE TITLE
Unable to connect to Cypress Test Runner - Dashboard (http://api.cypress.io/104.26.7.176:443) in intranet

### ISSUE THREAD

**Issue by kalyansatvik** [cypress-io/cypress#7406]
Hi,

I am unable to connect to API Server at http://api.cypress.io/(104.26.7.176:443) in intranet.
<img width="960" alt="error" src="https://user-images.githubusercontent.com/47410809/82283120-147aa880-99b3-11ea-8eba-3112deae66f1.png">

Same API/port is accessible over the internet. It seems my company is blocking this api/port.

shall i request my company network team to open this port for connection? 
if yes, will the port# 104.26.7.176:443 always same? 

is it something we can configure our [end?](url)
does cypress provide any other port for Cypress Test Runner - Dashboard?

**Comment by jennifer-shehane** [comment]
You may want to make sure that your VPN whitelists certain urls as explained here: https://on.cypress.io/dashboard-faq#I%E2%80%99m-working-at-a-restrictive-VPN-Which-subdomains-do-I-have-to-whitelist-on-my-VPN-for-the-Dashboard-to-work-properly

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
