### ISSUE TITLE
REMOTE_DEBUGGING_PORT can only be set from environment, and not config files

### ISSUE THREAD

**Issue by george43g** [cypress-io/cypress#7407]
### Current behavior:

There is a parameter that is passed to Google Chrome when it is launched in tests:
`--remote-debugging-port=xxx`

This allows for connecting a debugger to running tests. Good for a test-driven-development workflow with cypress.

Now, to set this parameter, one must set the following env var:
`CYPRESS_REMOTE_DEBUGGING_PORT=xxx`

As long as this is set in your environment, the correct port number will be set. Whether you simply use `export CYPRESS_...` in bash, or set it in a `.env` file which you load in using `dotenv` or otherwise, cypress only respects the following via node: `process.env.CYPRESS_REMOTE_DEBUGGING_PORT`.

It is not possible to set this via CLI arguments, which are used in some monorepo configurations, it is not possible to set this setting via the cypress.json file, which contains an `"env": {}` key which *should* be able to set this setting.

Cypress only seems to respect it when found in `process.env` from bash environment variables.

To clarify - if you set env variables via cypress.json, or via the CLI - they still seem to show up in the configuration section of the cypress GUI, however, the setting is not respected. The actual Chrome parameter `--remote-debugging-port=xxx` ends up being set to a random number.

### Desired behaviour:

In any environment object passed to cypress, whether it is from the actual shell env, or from CLI args or from cypress.json or cypress.env.json, (in which case it's just `REMOTE_DEBUGGING_PORT` rather than `CYPRESS_REMOTE_DEBUGGING_PORT`) , the correct args `--remote-debugging-port=xxx` should be set on the Chrome browser that is launched, to allow IDE's to reliably connect to the chrome debugging API.

### Test code to reproduce

Set VSCode launch config to connect to a certain port X.
Set `REMOTE_DEBUGGING_PORT` key to the same port in either cypress.json under the `env` key, or pass it in via CLI.

Launch cypress and chrome browser.
Try to connect the debugger from VSCode.
Will fail.
---
Set a bash env var like follows:
`export CYPRESS_REMOTE_DEBUGGING_PORT=xxx` to your configured port.
Relaunch cypress chrome browser.
Connect VSCode IDE debugger
Will succeed.

### Versions
Chrome 80, Cypress latest, MacOS latest. VSCode latest.

**Comment by jennifer-shehane** [comment]
`env` within the `cypress.json` has nothing to do with OS level environment variables. They are setting cypress specific environment settings to later be accessed via your tests, so wouldn't directly affect the way Cypress runs or any settings within Cypress itself.

We use the remote-debugging-port ourselves in order to automate Cypress and this happens to be the process.env variable we look for in our internal code. 

I think you'll run into very unexpected behavior by changing the RDP port https://github.com/cypress-io/cypress/issues/6884 

Can you explain what you're trying to achieve by editing the RDP port?

**Comment by george43g** [comment]
Thanks for your response @jennifer-shehane , the reason I'm setting the RDP is so I can connect the VScode debugger to the Chrome instance launched by cypress.

Whilst coding, I often follow a test-driven workflow, with cypress GUI open while I develop both tests and new features.
Ultimately, I use the debugger exactly in the same way one would use a debugger when developing a PWA that runs in Chrome or any other browser.

The only reason I need to set this for Cypress is that I want to connect to the debugger running in the Chrome window that is launched by cypress, hence I need to set this variable.

Are you suggesting that this is not the correct workflow and that I should connect to a debugger in my own Chrome instance whilst leaving the Cypress Chrome alone?

If this is an acceptable workflow, I will post use cases for being able to configure this and why I confused it with the `env` object - but for the sake of brevity, decided to omit this until we clarify if debugging during a testing workflow is something that cypress wants to support in the first place.

**Comment by jason-ha** [comment]
I was just experiencing the same issue attempting to debug via VS Code. The Cypress setting view shows the env when using `--env CYPRESS_REMOTE_DEBUGGING_PORT=xxx`, but debugger cannot attach as expected.

Am now using [`env-cmd`](https://www.npmjs.com/package/env-cmd) to specify CYPRESS_REMOTE_DEBUGGING_PORT.

**Comment by andyjakubowski** [comment]
Thanks for pointing this out @george43g! I was trying to set the `--remote-debugging-flag` in `cypress.config.ts` with the [Browser Launch API](https://docs.cypress.io/api/plugins/browser-launch-api), but that didn’t seem to work.

Setting the `CYPRESS_REMOTE_DEBUGGING_PORT` environment variable in the environment in which you run `cypress` does work.
