### ISSUE TITLE
fixture with `.json` file extension ignores specified encoding and applies JSON.parse

### ISSUE THREAD

**Issue by Sjeiti** [cypress-io/cypress#7412]
### Current behavior:

```js
cy.fixture('upload.json', 'hex').then(s=>assert.typeOf(s, 'string')) // fails
cy.fixture('upload.foojson', 'hex').then(s=>assert.typeOf(s, 'string')) // passes
```

### Desired behavior:

JSON.parse should not be applied when encoding is set.

### Versions

Cypress 3.8.3, Windows 10, Electron 78

**Comment by jennifer-shehane** [comment]
I can recreate this. 

```js
it('not hex value', () => {
  // when file ext is .json this fails
  cy.fixture('movies.json', 'hex').then(s => assert.typeOf(s, 'string')) // fails
})

it('hex value', () => {
  // other extensions pass
  cy.fixture('movies.foojson', 'hex').then(s => assert.typeOf(s, 'string')) // passes
})
```

<img width="465" alt="Screen Shot 2020-05-19 at 6 27 13 PM" src="https://user-images.githubusercontent.com/1271364/82323645-63016480-99fe-11ea-948f-a6de4e17231f.png">

When the file has an extension of `.json`, we just do a JSON.parse and don't consider the encoding at all as you can see in this line https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/fixture.coffee#L106:L106

Somewhat related #5395

**Comment by sainthkh** [comment]
I have a question. When should we encode JSON files to hex format?

According to [json.org](https://www.json.org/json-en.html), 

> JSON (JavaScript Object Notation) is a lightweight data-interchange format. It is easy for humans to read and write. It is easy for machines to parse and generate. 

Hex format is not easy for humans to read and write. And in most cases, JSON is written in plain text.

**Comment by sainthkh** [comment]
The code has been decaffeinated and the link has been changed to:

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/fixture.js#L119

**Comment by jennifer-shehane** [comment]
Closing since there's been no response. If someone can elaborate on the use case of encoding in hex format, we can consider reopening.
