### ISSUE TITLE
Feature request: Test "Rehydration", a strategy to execute tests faster

### ISSUE THREAD

**Issue by amitguptagwl** [cypress-io/cypress#7414]
I'm not sure if we're already doing this. But to explain the feature I was looking for; there can be multiple scenarios where starting steps are same but some steps in the end changes. Can there be a possibility to save the page state for such scenarios without running all the common steps again?

No I'm not talking about commands.

**Comment by jennifer-shehane** [comment]
No this feature currently doesn't exist.

This is a feature we've been discussing lately although no one has previously requested it. The idea is to have some sort of ability to save the current state of your application under a test, then later get that reference to 'hydrate' your test to that state of the application. 

We're working on a product proposal for this now.

**Comment by jennifer-shehane** [comment]
We’ve since released cy.session, which is a form of saving a session to use at later points to save things like login steps from being done over and over. We don’t have any current plans to extend hydration logic.
