### ISSUE TITLE
[Feature Request] Support expected failure for test cases

### ISSUE THREAD

**Issue by draganrakas** [cypress-io/cypress#7420]
### Current behavior:

Currently, test results are reported with a few states, PASSED, FAILED, PENDING.

### Desired behavior:

Add two additional reported statuses: XFAILED, XPASSED, if a test case has been "marked" or "grouped" into an "xfail" category (names TBD).

**Rationale**:
* Typically larger, more complex test suites almost always have tests failing due to bugs. The goal of this feature request is to support the ability to differentiate tests that are failing due to known issues (e.g. a bug that is scheduled to be fixed in 3 months) versus brand new failures that have not been triaged.

* This would prevent the extra overhead of re-triaging the same failures, and allowing people to just focus on "new failures."

* Similarly, if an xfailed test case is now passing, it can be reported as XPASSED. In this scenario, we know a bug has been fixed, and the test case could be removed from the "xfail" category/grouping.

**Comment by jennifer-shehane** [comment]
Adding this feature is not something we see as within our scope of feature work, but rather inline with the internal workflow of the company and how they choose to manage their tests, so we will be closing this issue. 

In our case, we add comments in our tests to designate things like this, you may want to change the title of the test to include `KNOWN BUG` or something that is searchable to see which failures are attributed to a known cause.

We do not want to change the test statuses or how a test 'fails' based on code workflow decisions.

We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by se7entyse7en** [comment]
I was looking for this as well, in the end I worked around it as @jennifer-shehane said by prefixing a `[KNOWN BUG]` in the name and by making the test conditional by checking `Cypress.env('CI')` so that when running locally they fail, but they won't make the CI job exit with an error.

**Comment by IA3898** [comment]
Since this post has been made has there been any functionality added that handles this desired behavior? @jennifer-shehane
