### ISSUE TITLE
cy.request() does not set session id cookie to be able to login

### ISSUE THREAD

**Issue by dominicroessner** [cypress-io/cypress#7424]
### Current behavior:

We login to our application by making a request to an endpoint using `cy.request()`. The response includes a sessionid cookie.

We then use `cy.visit('/')` to visit the app and expect a logged in session. However, it shows the login page. In 4.2.0 it successfully logged us in (and has been working since around 3.5.0 or earlier). In 4.3.0 it no longer works.

This issue seems similar to what was reported in #6757 but I'm able to reproduce this even when downgrading to older versions of Chromium, so doesn't appear browser related. I can also reproduce on any browser with Cypress 4.3.0.

### Desired behavior:

Session id cookie is set and navigating to the baseUrl has an authenticated session.

### Test code to reproduce

```javascript
Cypress.Commands.add('login', (isDeveloper = false) => {
  const username = isDeveloper ? 'developer@user.foo' : 'user@user.foo';
  const password = 'password';

  cy.request({
    method: 'POST',
    url: 'http://127.0.0.1:8000/account/auth',
    qs: { username: username, password: password }
  }).then(response => {
    expect(response.status).to.eq(200);
  });
});
```

![image](https://user-images.githubusercontent.com/45669990/82383536-ddbc8680-99e2-11ea-8025-92ceb7ba964f.png)

### Versions

Cypress 4.3.0
Reproducible in Chrome, Electron, Chromium, Firefox and Edge. Also downgraded Chromium to 78.0.3904.0 and was able to reproduce with Cypress 4.3.0, but worked fine with Cypress 4.2.0.

**Comment by jennifer-shehane** [comment]
I'm not exactly sure from the provided screenshots what the expected cookies are versus the cookies that are present since I'm not familiar with your application. 

Can you write a failing test case that shows the failure? If there are cookies missing, then write a test showing the cookies are not present? 

Or show a screenshot of the cookies present outside of Cypress versus inside of Cypress? Thanks.

**Comment by dominicroessner** [comment]
@jennifer-shehane thanks for the quick reply. Here is a test case that passes with Cypress 4.2.0 and fails with 4.3.0 with some inline comments to explain what happens at each step. Please let me know if I can provide any more info.

```javascript
it('login test', () => {
  const username = 'user@user.foo';
  const password = 'password';

  // if credentials are valid, the backend will include a `set-cookie`
  // header in the response that sets a `sessionid` and `csrftoken` cookie
  cy.request({
    method: 'POST',
    url: 'http://127.0.0.1:8000/account/auth',
    qs: { username: username, password: password }
  });

  cy.server();
  cy.route('http://127.0.0.1:8000/auth_token').as('token');

  // when visiting the app at http://localhost:4200 a request is made to
  // http://127.0.0.1:8000/auth_token and passes the sessionid cookie
  // in the request header and validates it against the backend.
  // in Cypress 4.2.0 I can see the cookie being passed, in 4.3.0 it is not
  // causing the user to not be logged in at this point
  cy.visit('/');

  // any subsequent steps here will now fail since we're not logged in
});

```

One other point to make, when I inspect the request headers to the `/auth_token` endpoint using `cy.get('@token').its('request.headers')`, I don't see the sessionid in the Cypress runner (in 4.2.0 or 4.3.0), but it is clearly passing it as I can see it in the Chrome network tab in 4.2.0, but not 4.3.0. The fact that the Cypress runner isn't showing it is probably not the cause, but wanted to mention it. The failing test I would write would assert that the request contains the sessionid cookie.

![image](https://user-images.githubusercontent.com/45669990/82481706-9689d080-9a8a-11ea-9736-37031459d832.png)

![image](https://user-images.githubusercontent.com/45669990/82481750-a43f5600-9a8a-11ea-9509-5d0041156f23.png)

**Comment by dominicroessner** [comment]
@jennifer-shehane any update on this? do you still need any more information to troubleshoot? it is preventing us from upgrading past version 4.2.0.

**Comment by nimmala89** [comment]
I have the same issue. Though the resp.status is equal to 200 , when I try to to grab the cookie from the response header. it gives null.
.then((rsp) => {
            
            const cookies = rsp.headers['set-cookie']
            cy.log(cookies)
                    cookies.forEach(cookie => {
                        const firstPart = cookie.split(';')[0]
                        const separator = firstPart.indexOf('=')
                        const name = firstPart.substring(0, separator)
                        const value = firstPart.substring(separator + 1)
                        console.log('cookie', name, value)
                        cy.setCookie(name, value)
                    })
        })
})


This works locally for me. I have the issue on the CI pipeline.(TeamCity)

**Comment by robotmonkey** [comment]
@jennifer-shehane thanks for making the updates to the issue. We're currently blocked from upgrading to all the beauty of 5.0, any updates here.

**Comment by dominicroessner** [comment]
For anyone with this issue, this seems to be related to browser changes, specifically around cookies that have SameSite=None but are not marked Secure, in which case Chrome rejects those. This is the standard starting with Chrome 85 and will be implemented in Firefox and Edge soon. See more here: https://www.chromestatus.com/feature/5633521622188032

For local development, since our backend API was running on 127.0.0.1:8000 and we are setting a sessionid cookie on that domain while loading the app on localhost:4200 in the browser, the sessionid cookie was rejected and we wouldn't have a session to login. Instead of requesting resources from our backend API on 127.0.0.1:8000, our solution was to simply request those resources on localhost:8000. We were able to upgrade to 4.3.0 as well as 5.0.0 after that.

**Comment by michaelhayman** [comment]
Also seeing this problem.  We're running both API and front end on `localhost`.

This started being a problem for us as soon as we upgrade to a Cypress `> 4.12`.

Signing in via UI works fine 100% of the time.

Signing in via `cy.request` succeeds in a `beforeEach`, and the cookie gets set (I check via an assertion).

But apparently it doesn't set the cookie "correctly" about 30% of the time, or something else goes wrong, and on the next request to the API we get booted out to the sign in screen, as if there's no cookie set at all.  This is random, but usually one test succeeds, then the next fails.

I checked and it's the same host & port for both requests.

Not sure what changed between these versions.

**Comment by wreality** [comment]
I'm running into the same problem and can't figure out what I'm doing wrong. Using cy.request to hit the login endpoint doesn't seem to be setting the session cookie. I can login with the ui (via a spec) and using cy.visit to go to another url still shows the session logged in, so the cookies just don't seem to be working when using cy.request. 

I'm using the same domain throughout so I don't think that's the issue, but I'm new to using cypress so I can only assume I'm doing something wrong here. 
'''

Cypress.Commands.add('login', ({ email }) => {
  cy.csrfToken();
  const baseUrl = Cypress.config().baseUrl;
  return cy.request('POST', ’${baseUrl}/graphql’, { query: `mutation { forceLogin(email: "${email}") {username, email, id, name}}` })
    .then(({ body }) => {
      console.log(body.data);
      return body.data.forceLogin;
    });
})
'''

**Comment by michaelhayman** [comment]
This issue went away for us after upgrading to Cypress 6.0+.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

I'd also recommend taking a look at our new `cy.session()` command, which is meant to make the process of logging in simpler. https://on.cypress.io/session

**Comment by stokrattt** [comment]
I have this problem with cypress 9.1.1 and chrome 99
