### ISSUE TITLE
Cypress.config() inside test does not override "blacklistHosts" value

### ISSUE THREAD

**Issue by CKuB** [cypress-io/cypress#7426]
### Current behavior:

Adding `Cypress.config('blacklistHosts', '127.0.0.1:63342')` within test does not override global `blacklistHosts` in `cypress.json`

Is it a bug or a feature?

### Desired behavior:

Adding `Cypress.config('blacklistHosts', '127.0.0.1:63342')` within test overrides global `blacklistHosts` in `cypress.json`

### Test code to reproduce

I have no opportunity to add my tests here((((

### Versions

Cypress 4.5.0, MacOS 10.14.6, Chrome 81

**Comment by jennifer-shehane** [comment]
`blacklistHosts` is not writeable at the time that `Cypress.config()` is called here. It needs to be set before the browser is opened. We should warn in these circumstances. Duplicate of #6407
