### ISSUE TITLE
Passing timeout to `cy.get('@alias')` does not apply timeout to aliased DOM elements.

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#7427]
### Current behavior:

```cy.get(alias, {timeout: ...})``` doesn't work when "timeout" > "defaultCommandTimeout".

### Desired behavior:

Timeout worked same as get selector.

### Test code to reproduce

cypress.json:
```
"defaultCommandTimeout": 10000
```

code:
```js
cy.get('.ant-table-tbody > :nth-child(1) > :nth-child(3) > :nth-child(1) > span').as('status')
cy.get('@status', { timeout: 60000 })
.then(()=>{...}) // wait and check status change
```

After about 10 seconds, cypress timeout with error "Timed out retrying...".
If not use alias, after about 15 seconds,  test case pass with no error.

### Versions
Cypress 4.5.0
MacOS 10.15.2
Chrome 81.0.4044.138

**Comment by jennifer-shehane** [comment]
Yes, I can recreate this, the `timeout` passed through to an alias it not applied back to the rerun commands. I'm not sure if this is intended behavior and the docs just need updating.

### Reproducible Example

```html
<html>
<body>
  <h1 id="h1">Hello</h1>
  <button id="button">Update DOM</button>
</body>
<script>
  document.getElementById('button').onclick = () => {
    document.getElementById('h1').remove()
  }
</script>
</html>
```

```js
it('alias timeout', () => {
  cy.visit('index.html');
  cy.get('h1').as('myH1')
  cy.get('button').click()
  cy.get('@myH1', { timeout: 60000 })
})
```

![](http://g.recordit.co/jlrOKQAZsc.gif)

### Workaround

Pass the timeout that you want applied to the aliased elements to the original element commands. 

```
it('alias timeout', () => {
  cy.visit('index.html');
  cy.get('h1', { timeout: 60000 }).as('myH1')
  cy.get('button').click()
  // this alias will now wait 60 seconds to find the h1
  cy.get('@myH1')
})
```

**Comment by Atif-Bashir-1998** [comment]
Any updates on this issue?
