### ISSUE TITLE
Plugin stdout not captured as part of stdout during run record

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#7434]
currently we capture run stdout for recording by intercepting `process.stdout.write`, however that will only capture the stdout from the parent process, missing the plugins

We should capture stdout from the plugins as well

We likely should spawn plugins with `{ stdio: 'pipe' }` instead of `inherit` and manually forward the stdout to the parent

**Comment by jennifer-shehane** [comment]
The reason this is important - if you `console.log` output through the `plugins/index.js`, they will show up in the terminal when you run `cypress run`, but they will not show up captured later in the Dashboard stdout.
