### ISSUE TITLE
Cypress open record switch missing

### ISSUE THREAD

**Issue by aangelinsf** [cypress-io/cypress#7436]
### Current behavior:

Though the documentation indicates that it's possible to start recording with the following:

```
export CYPRESS_RECORD_KEY=<record key>
cypress run --record
```

Please see:
https://on.cypress.io/projects#Setup

This is the response I get:
```
source git:(feature/AA-001) ✗ export CYPRESS_RECORD_KEY=<key snipped>
source git:(feature/AA-001) ✗ npx cypress open --record

  error: unknown option: --record

Usage: cypress open [options]

Opens Cypress in the interactive GUI.

Options:
  -b, --browser <browser-path>     path to a custom browser to be added to the list of available browsers in Cypress
  -c, --config <config>            sets configuration values. separate multiple values with a comma. overrides any value in cypress.json.
  -C, --config-file <config-file>  path to JSON file where configuration values are set. defaults to "cypress.json". pass "false" to disable.
  -d, --detached [bool]            runs Cypress application in detached mode
  -e, --env <env>                  sets environment variables. separate multiple values with a comma. overrides any value in cypress.json or cypress.env.json
  --global                         force Cypress into global mode as if its globally installed
  -p, --port <port>                runs Cypress on a specific port. overrides any value in cypress.json.
  -P, --project <project-path>     path to the project
  --dev                            runs cypress in development and bypasses binary check
  -h, --help                       output usage information
```

Carefully examining the switches shows that there is, in fact, no record switch available. How does one initiate recording?

### Desired behavior:

App should open with recording enabled.

### Versions

Cypress 4.6, macOS 10.15.1

**Comment by bahmutov** [comment]
Cypress run allows “—record”

Cypress open is interactive GUI mode that does not accept “—record” since it keeps rerunning tests as you work with them

**Comment by jennifer-shehane** [comment]
Yes, as @bahmutov mentioned, only `cypress run` works with `--record`. `cypress open` does not allow the record key.

`cypress open` is intended to be used as a developer tool, not a way to capture and record runs - this is what `cypress run` is for. Adding this feature is not something we see as within our scope of feature work, so we will be closing this issue.
