### ISSUE TITLE
Not able to login via valid credentials using cypress

### ISSUE THREAD

**Issue by siddy1639** [cypress-io/cypress#7438]
I am not able to login via correct credentials in cypress when running cypress test, even though the page navigates to the home page

After having read from previous blogs I have also set `chromeWebSecurity` to `false `in my `cypress.json` file but it does not solve the issue.

_Note_: I am able to login via same credentials on cypress chrome instance

**Current Behaviour:** 

I do not get logged in and navigate to base url after trying to log in

**Desired behavior:**

I should be able to login via valid credentials (mentioned in code snippet) and should stay on the login page with an error displayed when i use invalid credentials

**Test code to reproduce**

The snippet of my code is:

```js
class customerLogInPage
{
    navigate()
    {
        cy.visit(Cypress.env("url"))
        cy.get(".user-menu.alt").click()
        cy.get(".dropdown-menu ").find("[href='/login']").click()
        cy.url().should('include', '/login')
    }

    verifyUnsuccessfulLogin()
    {
        cy.get("#spree_user_email").clear().type("abcd@whitespectre.com")
        cy.get("#spree_user_password").type("abcd@1234")
        cy.get("[value='Login']").click()
        cy.title().should('eq', 'Login | Consultant Center')
        cy.get(".flash-alert").should(($el) =>
        {
            const text = $el.text()
            expect(text).to.include('Invalid email or password')
        })
    }
```

**Versions**

I am on mac OS (10.15 Beta) with cypress "version": 4.5.0
Chrome: 81.0.4044.138

**Comment by jennifer-shehane** [comment]
Hey @siddy1639, I'm not able to recreate the behavior as described. Running the tests provided passes for me. Can you explain what is happening when you run the tests? Do the tests fail?

I would also not advise exposing login credentials on a public github comment as anyone can access this information. You should likely update your testing login credentials.

<img width="1326" alt="Screen Shot 2020-05-21 at 6 14 02 PM copy" src="https://user-images.githubusercontent.com/1271364/82556055-02556180-9b8f-11ea-9302-9eeacb340a88.png">

**Comment by siddy1639** [comment]
Thank you for checking Jennifer, when my cypress tries to login with invalid credentials it shoukd show the error message as it does for you, however when I run it in my machine, it navigates to the Home url ever after failing to login.
I had a similar problem on a different site as well but then that was fixed itself in a couple of hours. For me when I login it navigates to www.qa.dna.whitescpectre.com without logging in. (or without showing error with invalid creds)

Here is a screenshot: https://ibb.co/WyG6PSF

**Comment by siddy1639** [comment]
I see that after the .click() function is called, somehow the base url is called again. 
I tried a workaround and used form submit to do the same function but that also resulted in illegal invocation: https://ibb.co/RvskqmT

I changed "cy.get("[value='Login']").click()" to =>
cy.get("#new_spree_user").submit()

**Comment by siddy1639** [comment]
Also @jennifer-shehane could you please remove the screenshot from your comment above, that would be really helpful.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by AtofStryker** [comment]
@siddy1639 this should now work with the new `cy.origin()` command as of `10.11.0`. Just enable the `experimentalSessionAndOrigin` flag to use the command. This will be generally available in Cypress 12 and should work with most authentication flows. Let us know what you think!
