### ISSUE TITLE
Redirect adds `__` within directory path when `experimentalSourceRewriting` is on

### ISSUE THREAD

**Issue by varunpradhan** [cypress-io/cypress#7439]
### Current behavior:

Current behavior:
When I login through the normal browser then I am able to log in.
But when running from cypress test runner the directory path is missing from URL.

The Cypress Test Runner redirects to: `http://:8084/__/branchHome.html`

![image](https://user-images.githubusercontent.com/26091432/82546735-396b4900-9b76-11ea-9358-62819d9d5097.png)

I have added below after there was a comment on my previous same bug still it didn't worked.

The previous bug raised: #5569

![image](https://user-images.githubusercontent.com/26091432/82548265-b0094600-9b78-11ea-837f-4ac97fba5bd0.png)

My cypress.json file:

![image](https://user-images.githubusercontent.com/26091432/82548592-2a39ca80-9b79-11ea-8aa1-635ae918ecf1.png)

### Desired behavior:

The Cypress Test Runner should redirect to : http://:8084//branchHome.html 

### Test code to reproduce

Below is the code:

```js
cy.visit("http://<ip>:8084/<directory>")
cy.get("#login").click()
cy.get("input[value='Organization']").click()
cy.get("#username").type('<User name provided>')
cy.get("#pwd").type('<password provided>')
cy.get("#login").click()
```

### Versions

Cypress Version : 4.6.0
Operating System: Windows 10
Browser : Chrome 81 / Electron 80

**Comment by jennifer-shehane** [comment]
@varunpradhan Thanks for opening an issue. 

Do you have any idea what in your application initiates the redirect to the `branchHome` page? Typically we've seen this issue when the application under test is changing the route in some manual way. Some previous examples were:

- Setting `location`, `location.href`, calling `location.replace`, `location.assign`
- Calling `window.top` or `window.parent`
- Calling into `window.frames`, `window.parent.frames` or other `frames`
- Having an `integrity` attribute on script resources.

**Comment by varunpradhan** [comment]
@jennifer-shehane yes it uses `location.href `

**Comment by flotwig** [comment]
I think this might be happening because the current version of `experimentalNetworkStubbing` only works on JS served from the current origin. JS served from other origins is not yet intercepted. 

Is the script that does the `location.href` change served from the same domain that you originally `cy.visit`ed?

**Comment by varunpradhan** [comment]
@flotwig yes it is from the same domain.

**Comment by flotwig** [comment]
Can you share the source code that is doing the `location.href` change please?

**Comment by varunpradhan** [comment]
@flotwig Below is the source code that is doing the `location.href` change:

```
function navigate(url) {
  try {
    window.location.href = url;
  } catch (e) {
    alert(e + "url===>" + url);
  }
}
```

We are using a relative URL.
Can anyone also suggest what approach in source code will work my cypress test? I will pass on the feedback to my developers.

**Comment by flotwig** [comment]
@varunpradhan the issue occurs when setting `href` to a relative path, so if you could use an absolute URL instead of relative, that would avoid the bug

**Comment by varunpradhan** [comment]
@flotwig I have forwarded the feedback to development team. Thank you for the suggestion. But I don't think they will change this anytime soon.
Till that time will be waiting for this bug to be resolved.

**Comment by gcoombe** [comment]
We're seeing the same. Are there any other workarounds? For us the seeing of location.href is inside a framework so it's not something we can update. Unfortunately this means that Cypress just won't work for a large part of our site.

**Comment by gcoombe** [comment]
Is there any timeline on when these redirecting to __ issues will be addressed? It's causing is significant pain and means we can't write tests for a number of high traffic areas of our app.
