### ISSUE TITLE
App preview of Cypress GUI displays incorrectly in React v16

### ISSUE THREAD

**Issue by khiettran** [cypress-io/cypress#744]
- Operating System: MacOS Sierra 10.12.6
- Cypress Version: 1.0.2
- Browser Version: Electron 53/ Chrome 61

### Current behavior:
App preview does not correctly display

### Desired behavior:
App preview of Cypress GUI should be display nicely

### How to reproduce:
Run specs on Cypress GUI with React v16

### Additional Info (images, stack traces, etc)
<img width="1437" alt="r16" src="https://user-images.githubusercontent.com/3986091/31586170-b886fc4a-b1f7-11e7-8a42-136e08538c08.png">

I think this is a limitation of capturing screenshot not a bug of Cypress as we're using reflexbox to render pages. Any support would be appreciated. Thank in advance.

**Comment by brian-mann** [comment]
We'll need a reproducible example such as a repo we can clone, or an external site which demonstrates this problem. As is, there's nothing actionable for us to look into here. 

There are hundreds of React projects using Cypress every day, so this is likely more of an edge case with your specific setup.

**Comment by khiettran** [comment]
Fixed, this happens cause by our setup. Thank you!
