### ISSUE TITLE
Unable to trigger sending email notification after test execution 

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#7441]
### Current behavior:

method is not triggered after cypress test run

### Desired behavior:

SMTP service should be triggered after test run and send an email notification 

### Test code to reproduce
 in support/index.js

```js
import './commands'
import q from 'q';
import fs from 'fs';
import smtpTransport from 'nodemailer-smtp-transport';
import nodemailer from 'nodemailer';

const SendMail = function () {

    const name = process.env.E2E_ENV;
    const envName = name.charAt(0).toUpperCase() + name.slice(1);

    this.sendHTMLMail = function (htmlContent) {
        const transporter = nodemailer.createTransport(smtpTransport({
            service: 'Gmail',
            host: 'smtp.gmail.com',
            port: 465,
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PWD,
            },
        }));
        const mailOptions = {
            from: 'Amr',
            to: ['test@test.com'],
            subject: envName+' Cypress Automation Test Report',
            text: 'Amr Kamel',
            html: htmlContent,
            mailParserOptions: { streamAttachments: true },
            attachments: [{
                // filename: '1234.jpg',
                // path: './autoReport/1234.jpg'
            }]
        };
        transporter.sendMail(mailOptions, function (error, info) {
            if (error) {
                return console.log(error);
            }
            console.log('Mail sent: ' + info.response);
        });
    };
};


Cypress.on('command:end', (test) => {
    if (test.state === 'failed'|| test.state === 'passed') {
        return q.fcall(function () {
            const htmlFilePath = 'server/cypress/reports/tests/1590058325267_login-and-choose-company.html';
            const htmlFileContent = String(fs.readFileSync(htmlFilePath));
            (new SendMail()).sendHTMLMail(htmlFileContent);
        }).delay(4000);
    }
});
```

### Versions

4.0.2

**Comment by jennifer-shehane** [comment]
The code above would trigger the code after every single **command** has run. A command is something like `cy.get()`, `.click()`, not after the entire Cypress run has completed. This event yields a command, not a test, so will not have a state of failed or passed as a test does. 

If you want to run some code after each test execution, I would recommend calling a [`cy.task()`](https://on.cypress.io/task) from within an `afterEach` hook that will call into the code you want to execute. All code within the event handlers or tests will have to be run within the context of the browser, so running code that needs to run in Node needs to be done in a `cy.task()`.

If you want to run some code after the Cypress run has finished, I recommend using our [Module API](https://on.cypress.io/module-api) which will return the full results of a run, including an array of tests that would include failed tests. 

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by mitujain01** [comment]
@amrsa1 - Were you able to resolve the above issue, if yes could you please help me for the same.
