### ISSUE TITLE
Update to cypress 4.6.0 is not consistently showing address bar/viewport is resizing

### ISSUE THREAD

**Issue by danreale** [cypress-io/cypress#7443]
### Current behavior:

When running a test with cypress 4.6.0, I am noticing that that address bar is showing when the test starts and then disappearing shortly after.
I am also noticing the view port is resizing and not showing the whole application while the tests run through. I was on version 4.4.1 prior to uploading (didnt see these issues), so I am not sure if this issue was present on 4.5.0.

### Desired behavior:
I would expect the address bar would always show during a test and that the page doesnt resize/ stays the same size during the test run.

![May-21-2020 09-53-17_6](https://user-images.githubusercontent.com/37839370/82565766-efb83980-9b48-11ea-8a0c-d45083551a0f.gif)

### Versions

4.6.0
mac (high sierra 10.13.6)
chrome and edge browsers (did not try others)

**Comment by Jacek-fstack** [comment]
+1 it's gone for me as well

**Comment by jennifer-shehane** [comment]
I bet this is due to https://github.com/cypress-io/cypress/issues/6898

**Comment by danreale** [comment]
@jennifer-shehane would this be slated for the next release?

**Comment by ragu2807** [comment]
Yeah, I can see the same issue with `v4.6.0` whereas `4.5.0` looks good.

**Comment by jennifer-shehane** [comment]
I was able to recreate this with the following code. I also have to run this code in combination with resizing the main browser window to touch either the width/height of the AUT iframe. So if my browser window is really maxed out - you won't see it. 

`index.html`

```html
<html>
<body>
<p style="height: 2000;">Aenean lacinia bibendum nulla sed consectetur.</p>
<footer>Aenean lacinia bibendum nulla sed consectetur.</footer>
</body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('footer').click()
})
```

![](http://g.recordit.co/za86crNuUV.gif)

**Comment by jennifer-shehane** [comment]
Reverting #7203 fixes the issue. Will go ahead and revert and reopen the other issue this was fixing since this affects more people.
