### ISSUE TITLE
Proposal: Support video recording in browsers other than electron

### ISSUE THREAD

**Issue by Sumolari** [cypress-io/cypress#745]
From [version 0.20.0 changelog](https://docs.cypress.io/guides/references/changelog.html#0-20-0)...

> There is a new --browser option that lets you change the browser that runs from the command line. This works the same way as changing the browser in the GUI, with the exception that **any browser other than the default electron browser will not record a video**. This is solvable but requires more work.

Is this going to be addressed in a future version?

**Comment by brian-mann** [comment]
Yes, we already ship `ffmpeg` and could use that to record the headed browsers. The code just needs to be updated to handle these different scenarios.

There's some complexity around situations where the user has 2 monitors, or they inadvertently record the wrong thing and upload it to the Dashboard. The video would likely be taken at maximum screen size resolution too, making these bigger than the usual videos taken. It's also possible to figure out the dimensions of the browser and to possibly just record that. 

Launching in full screen would likely also need to be the default, and/or we'd need to expose a CLI flag for launching at a specific resolution.

**Comment by gpenafib** [comment]
Hi Brian, could you please provide roughly a date when the recording video feature will be already implemented for Chrome browser?

**Comment by RandallKent** [comment]
Closing in favor of https://github.com/cypress-io/cypress/issues/1767
