### ISSUE TITLE
cypress.run() does not release activeHandles since 3.5.0, wrapping script doesn't exit.

### ISSUE THREAD

**Issue by dubbha** [cypress-io/cypress#7454]
### Current behavior:

`cypress.run()` does not release some activeHandles since 3.5.0. Wrapping script doesn't exit without an explicit `process.exit()`.

Same situation in 4.5.0, and probably all the versions starting 3.5.0. Worked seamlessly in 3.4.1.

### Desired behavior:

No activeHandles/activeRequests should stuck, the wrapping script should exit cleanly, without an explicit forceful `process.exit()` call.

### Test code to reproduce

[activeHandles@3.4.1](https://github.com/dubbha/cypress-test-tiny/tree/activeHandles%403.4.1)   [OK, last good version]
[activeHandles@3.5.0](https://github.com/dubbha/cypress-test-tiny/tree/activeHandles%403.5.0)   [NOK, first problematic version]
[activeHandles@4.5.0](https://github.com/dubbha/cypress-test-tiny/tree/activeHandles%404.5.0)   [NOK, still bad in 4.5.0]

```js
// package.json
"scripts": {
  "cy:report": "node ./cypress/scripts/report.js"
},

// console
$ yarn cy:report
```

The wrapping script:
```js
#!/usr/bin/env node

const cypress = require('cypress')

main()
// process.exit()  // this would "help" but should not be needed

async function main() {
    const result = await cypress.run()

    console.log(result)
    console.log(process._getActiveHandles())
    console.log(process._getActiveRequests())
}
```

### Versions
Windows 10
Cypress 3.5.0+ (e.g. 4.5.0)

**Comment by jennifer-shehane** [comment]
Can you explain a bit more about the exact behavior you are seeing that is different between version? When I run the provided code, the process does exit for me. I'm using macOS. 

Both the 3.4.1 and the 4.6.0 versions exit and also print activeHandlers and activeRequests in the process log after the run has finished. 

May be isolated to Windows if you're seeing something different here.

`4.6.0 log with DEBUG logs`

```
  cypress:server:cypress about to exit with code 0 +6s
  cypress:cli child event fired { event: 'exit', code: 0, signal: null } +7s
  cypress:cli child event fired { event: 'close', code: 0, signal: null } +1ms
[ WriteStream {
    connecting: false,
    _hadError: false,
    _handle:
     TTY {
       onread: [Function: onStreamRead],
       [Symbol(owner)]: [Circular] },
```

**Comment by dubbha** [comment]
Hi Jennifer,

Not much to add regarding the expected behavious - I expect the parent script to exit cleanly in all the versions.

Basically, I expect it to behave as it does in 3.4.1:
![Co3rQri76T](https://user-images.githubusercontent.com/60435724/82883116-b1f15180-9f4a-11ea-9cf7-db1b25865f10.gif)



While starting 3.5.0 it doesn't (screen taken at 4.5.0):

![9FqQg5u2MP](https://user-images.githubusercontent.com/60435724/82883538-3d6ae280-9f4b-11ea-976e-cfca850585de.gif)


OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363

My assumption was that the root cause is that some of the child processes do not release some activeHandlers, so the partent process is stuck, so I added the getActiveHandles and getActiveRequests outputs. But I can't debug it any further, because their outputs are not exactly clear to me. So I might be wrong, and the reason might be elsewhere.

**Comment by jennifer-shehane** [comment]
I think this is isolated to Windows because this is not the behavior I see. The process exits properly on MacOS on all of these versions.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
