### ISSUE TITLE
cy.clock() preventing the subsequent visit/reload to load completely when running in emulator

### ISSUE THREAD

**Issue by guruannapantula** [cypress-io/cypress#7455]
### Current behavior: 
In emulator, Page is not loading completely if we are setting the clock before visiting the page

In emulator:
Set the clock --> visit the page again --> page is not loading completely.
### Desired behavior:
Page should be completely loaded. (please note : There is no issue with the flow when executed on chrome desktop view)

### Test code to reproduce
code snippet which is causing issue

```js
//eg :  url = https://www.amazon.com/  (or) https://www.unibet.co.uk/

cy.clock(new Date().getTime())
cy.visit(url)
```

config used:
```json
{
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
    "viewportWidth":414,
    "viewportHeight":896
}
```

### Versions
"cypress": "^4.5.0"
running on chrome 81

**Comment by guruannapantula** [comment]
![cyclock](https://user-images.githubusercontent.com/48826492/82667181-9bd84e00-9c37-11ea-9d30-ff91ccd0c5c6.png)

**Comment by jennifer-shehane** [comment]
I can see the behavior you are describing when using `cy.clock()`. I'm not sure why Amazon's view does not load when we overwrite the timeout or Date objects.

That being said, we do not recommend using Cypress to test sites that are not under your control as explained in our [Best Practices](https://on.cypress.io/best-practices#Visiting-external-sites). Closing as we do not support testing 3rd party websites.

**Comment by annapantula** [comment]
In the code snippet, I have given another example about loading the site https://www.unibet.co.uk
which is under our control, the result is same in this case as well

**Comment by guruannapantula** [comment]
In the code snippet, I have given another example about loading the site https://www.unibet.co.uk
which is under our control, the result is same in this case as well. The page is not loaded completely

**Comment by jennifer-shehane** [comment]
I can also recreate this on https://www.unibet.co.uk. The issue does not occur if removing the `cy.clock()` definition or if removing the `userAgent` definition.

### No `cy.clock()` and `userAgent`

<img width="1292" alt="Screen Shot 2020-05-26 at 1 28 07 PM" src="https://user-images.githubusercontent.com/1271364/82869895-08638d80-9f55-11ea-9346-ce753d32f589.png">

### `cy.clock()` and `userAgent`

<img width="1306" alt="Screen Shot 2020-05-26 at 1 27 50 PM" src="https://user-images.githubusercontent.com/1271364/82869916-14e7e600-9f55-11ea-92a5-a77d1d003fbc.png">

**Comment by jennifer-shehane** [comment]
So basically, there is some call using `setTimeout` that your application requires when it's on this userAgent in order to load your page. Since calling [`cy.clock()`](https://on.cypress.io/clock) overwrites `setTimeout`, the time is not clicking forward in order to trigger what it needed in this call. 

You can see that the loading of the site breaks only if you overwrite `setTimeout`. 

```js
// Not working ☹️ 
it('test', () => {
  cy.clock(new Date().getTime(), ['setTimeout'])
  cy.visit('https://www.unibet.co.uk')
})
```

If you want to only overwrite the `Date` object, I recommend explicitly specifying to only overwrite that function like below:

```js
// Working!!
it('test', () => {
  cy.clock(new Date().getTime(), ['Date'])
  cy.visit('https://www.unibet.co.uk')
})
```

If you still want to overwrite the `setTimeout` timing, you'll need to tick time forward so that your call to `setTimeout` is not overwritten by Cypress. 

```js
// Working!!
it('test', () => {
  cy.clock(new Date().getTime())
  cy.visit('https://www.unibet.co.uk')
  cy.tick(5000)
})
```

**Comment by RKodandam** [comment]
I have same issue. Hope this issue still exist. please advise me. Thank you

**Comment by JesseCheng77** [comment]
I encountered the same issue in version 12.16.0, it seems that `cy.clock()` cannot be used without any concerns.🤔
