### ISSUE TITLE
VSCode not detected in Open File Preference | Cy 4.6.0 | Error Stack Trace

### ISSUE THREAD

**Issue by a-onkar** [cypress-io/cypress#7456]
### Current behavior:
File not opening in VSCode from View Stack Trace.

### Desired behavior:

After clicking on the link in the stack trace, VSCode Editor should open.
According to your documentation VSCOde is showing up in options, but I can't see such options present in my Test Runner.

### Test code to reproduce

I set the path for VSCode executable in settings.
![image](https://user-images.githubusercontent.com/25897622/82667206-46983e80-9c2f-11ea-8ffb-d044a0363de9.png)

Click on the link in the stack trace
![image](https://user-images.githubusercontent.com/25897622/82667246-5adc3b80-9c2f-11ea-8c2b-71eafa2e18a3.png)

Get error in VSCode
![image](https://user-images.githubusercontent.com/25897622/82667291-734c5600-9c2f-11ea-804d-c35e9e1f2103.png)

### Versions

Cy 4.6.0
Windows 10
VSCode

**Comment by tyagi487** [comment]
Hi How can i update my cypress(4.6.0) currently m using 4.5.0
am using this command "npx cypress install" to install new update
but am getting this, so how 
Cypress 4.5.0 is installed in C:\Users\akash\AppData\Local\Cypress\Cache\4.5.0

Skipping installation:

  Pass the --force option if you'd like to reinstall anyway.

**Comment by a-onkar** [comment]
> Hi How can i update my cypress(4.6.0) currently m using 4.5.0
> am using this command "npx cypress install" to install new update
> but am getting this, so how
> Cypress 4.5.0 is installed in C:\Users\akash\AppData\Local\Cypress\Cache\4.5.0
> 
> Skipping installation:
> 
> Pass the --force option if you'd like to reinstall anyway.

If you are asking me the question, apparently this won't be the right place.

To answer to your query regarding updating cypress, use the following command:

npm install --save-dev cypress@latest

**Comment by a-onkar** [comment]
Found solution

**Comment by s1n7ax** [comment]
For people who are wondering, the solution was to install vscode (editor) to the system. It looks like user AppData can not be accessed by the Cypress process.

**Comment by a-onkar** [comment]
> For people who are wondering, the solution was to install vscode (editor) to the system (to all users). It looks like user AppData can not be accessed by the Cypress process.

I actually missed writing .exe to the path of the editor.

**Comment by vitkusv** [comment]
For macos users, run built in VSCode command: "Install 'code' command in path", then reopening the runner lists out the Visual Studio Code as an option.

**Comment by tudorsss** [comment]
To be more specific, in Visual Studio Code, go to View -> Command Pallete and paste this in there `Install 'code' command in path`  then press `Enter`.

Now you just need to restart Visual Studio Code and that's it.

**Comment by NikhilNanjappa** [comment]
> To be more specific, in Visual Studio Code, go to View -> Command Pallete and paste this in there `Install 'code' command in path` then press `Enter`.
> 
> Now you just need to restart Visual Studio Code and that's it.

@tudorsss  I tried this but still get the below error message on my terminal when I click the path on Chrome (`cypress open`)

`The editor process exited with an error: spawn /Applications/Visual Studio Code.app/ EACCES`

**Comment by cragun47** [comment]
The UI for Cypress settings has changed.  After running the command as described by @tudorsss  and @vitkusv ,  and restarting VS Code, VS Code now shows up in the External Editor list (on Mac).
<img width="880" alt="image" src="https://user-images.githubusercontent.com/4914849/195414200-628fa2fa-3715-4fe0-8119-971005d5c1b0.png">

**Comment by Serhii-shk** [comment]
> To be more specific, in Visual Studio Code, go to View -> Command Pallete and paste this in there `Install 'code' command in path` then press `Enter`.
> 
> Now you just need to restart Visual Studio Code and that's it.

Same problem with webStorm. Tell me plz how to solve the problem
WebStorm installed via Toolbox
