### ISSUE TITLE
Cannot able to run cypress from npm

### ISSUE THREAD

**Issue by sumabala9** [cypress-io/cypress#7458]
i uninstalled and installed  nodejs and when trying to open cypress, i am facing this issue.Please provide solution
![Capture](https://user-images.githubusercontent.com/65771070/82670896-9d1b7200-9c5b-11ea-99a1-28de31a05dab.PNG)

**Comment by ragu2807** [comment]
@sumabala9 This looks related to `npm` not found on your machine and not related to cypress.

**Comment by jennifer-shehane** [comment]
If you're encountering an error running `npm init`, this is related to npm, not Cypress. Closing as this is not related to the Cypress project.
