### ISSUE TITLE
Support TypeScript support and plugin files

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress#7459]
### Current behavior:

TypeScript support files (i.e `support/commands.ts`) and plugin file (`plugins/index.ts`) cause tasks and/or custom commands to not be found/registered. For example, the custom task `db:seed` could not be registered within the [cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app) project:

<img width="2002" alt="Screen Shot 2020-05-20 at 3 12 52 PM" src="https://user-images.githubusercontent.com/334337/82671922-a251d000-9c0d-11ea-9b03-dda9939e330a.png">

Converting the plugins file back to JavaScript resolved the issue, but a similar issue also exists for a `commands.ts`, which resulted in custom commands not being added:

<img width="2002" alt="Screen Shot 2020-05-20 at 5 36 17 PM" src="https://user-images.githubusercontent.com/334337/82672179-ffe61c80-9c0d-11ea-9a5a-080abf8de22d.png">

Converting the support files back to JavaScript also resolved the issue.

It should be noted that this issue did not exist with Cypress `develop` branch before and after the v4.6 release.

### Desired behavior:

- TypeScript support and plugin files to be properly loaded and/or executed for test execution.
- Customs commands should be added and tasks should be registered when declared in TS files.

### Test code to reproduce

Reproduction (with [associated commit](https://github.com/cypress-io/cypress-realworld-app/commit/40c612023f411c7fccf4d717341167ead1c3173c)) can be seen within this cypress-realworld-app test run: https://dashboard.cypress.io/projects/7s5okt/runs/1272/specs

### Versions

Cypress v4.6

**Comment by bahmutov** [comment]
Confirmed in https://github.com/bahmutov/test-ts-plugins

Workaround: point at plugins and support TS files explicitly from `cypress.json` file

```json
{
  "pluginsFile": "cypress/plugins/index.ts",
  "supportFile": "cypress/support/index.ts"
}
```

**Comment by amirrustam** [comment]
@bahmutov I can confirm your workaround worked.
