### ISSUE TITLE
Fixture not immediately available in `beforeEach`

### ISSUE THREAD

**Issue by eric-burel** [cypress-io/cypress#7460]
### Current behavior:

When defining a fixture in `beforeEach`, it won't be immediately available in the `this` context.

The alternative is to add a second `describe` nested block, in order to define a new `beforeEach` where `this` is correctly populated.
Other alternative is to directly import the fixture using an usual ES6 import, but that's ugly.
Eventually, putting the `cy.fixture` call in `before` instead of `beforeEach` makes the trick. Basically, as long as the fixture loading is separated from the `beforeEach`, it seems ok.

Maybe I should use `before`?

### Desired behavior:

Either:
- make the fixture available in `beforeEach` (not sure if that's technically possible?)
- or document a valid alternate pattern
- or document this use case to make it clear it's not possible

### Test code to reproduce
An example:
```js
  beforeEach(function() {
    cy.fixture("graphql/dashboardResponse").as("dashboard");
    console.log("this", this.dashboard); // => undefined
    cy.mockGraphQL([dashboard]); // => I want to mock queries systematically using my fixture, but it won't work
    cy.visit("/dashboard"); // will trigger the query and fail
  });
```
I am in the context of a graphql query, so I am not sure how the doc meant for usual REST requests can apply to me.

### Versions

4.5.0
Chrome
Ubuntu

**Comment by jennifer-shehane** [comment]
This is because the `this.dashboard` is evaluated immediately, being synchronous code, before the asynchronous `cy.fixture("graphql/dashboardResponse").as("dashboard")` runs. 

```js
  beforeEach(function() {
    cy.fixture("graphql/dashboardResponse").as("dashboard").then(() => {
      // this will be defined since it runs *after* the async methods ran above.
      console.log("this", this.dashboard); 
    }
  }
```

I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).
