### ISSUE TITLE
Cypress hangs during `cypress open` and `cypress run` after opening browser (4.6.0)

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#7464]
### Current behavior: 

Running tests hangs. 

With `cypress run`, it times out having never begun the first test.

![Screen Shot 2020-05-21 at 9 44 20 PM](https://user-images.githubusercontent.com/1271364/82860177-cfb8b980-9f3e-11ea-9858-516dd563e06d.png)

With `cypress open`, the Test Runner browser opens, but the test doesn't start running for 30+ minutes. It appears blank.

<img width="742" alt="Screen Shot 2020-05-21 at 10 02 11 PM" src="https://user-images.githubusercontent.com/1271364/82860137-b9aaf900-9f3e-11ea-9b2e-0718a4d6a583.png">

The culprit seems to be [this line](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/source_map_utils.js#L26). Surrounding it with `console.time/timeEnd` results in it taking over 30 minutes to run.

### Test code to reproduce

This can be seen in the Cypress Dashboard internal tests. Still trying to narrow it down to an easily reproducible (and publicly-postable) case.

### Versions

Cypress 4.6.0

### Current Workaround

Downgrade to Cypress 4.5.0.

**Comment by jennifer-shehane** [comment]
I have what I believe to be the same issue with a smaller repro from https://github.com/cypress-io/cypress/issues/7453

This takes a full 10+ seconds to load the first test during `cypress run` or `cypress open` in Cypress regardless of version (not 4.6.0 related). I'm not using any preprocessor with that run. The increased time occurs when importing the `aws-amplify` modules. 

In 4.6.0 - when including the `@cypress/webpack-preprocessor` v5.4.1 (will all required peer deps) it causes the Test Runner to never load and runs up my CPU over 100% with the Cypress process. 

Again, the Test Runner runs completely fine when I remove the `aws-amplify` import statement from the support file.

`support/index.js`

```js
import { Auth } from 'aws-amplify'
```

`spec.js`

```js
it('Loads the homepage', function () {
  cy.visit('index.html')
});
```

`index.html`

```html
<html>
<body>
</body>
</html>
```

`package.json`

```json
{
  "name": "my-application",
  "version": "1.2.3",
  "scripts": {},
  "dependencies": {},
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "@cypress/webpack-preprocessor": "^5.4.1",
    "aws-amplify": "^3.0.12",
    "babel-loader": "^8.1.0",
    "cypress": "4.6.0",
    "webpack": "^4.43.0"
  }
}

```

Seems to stall at this DEBUG log:

```
  cypress:server:run browser launched +1s
  cypress:browserify finished bundling: /Users/jennifer/Library/Application Support/Cypress/cy/production/projects/cypress-transform-test-74d5161f4a1005f86b0d85a657ddcf07/bundles/cypress/integration/spec.js +510ms
  cypress:server:controllers:spec sending spec { filePath: '/Users/jennifer/Library/Application Support/Cypress/cy/production/projects/cypress-transform-test-74d5161f4a1005f86b0d85a657ddcf07/bundles/cypress/integration/spec.js' } +558ms
```

**Comment by fsteinbauer** [comment]
@jennifer-shehane, thanks for investigating. 

We are facing a similar startup issue when upgrading to cypress 4.6.0. However, we don't use the `aws-amplify` package in our project. 

You added the label `existing workaround`. Is this workaround currently to downgrade back to cypress 4.5.0?

**Comment by flotwig** [comment]
@chrisbreiding is it catastrophic backtracking from the regex? I don't think you need `regexCommentStyle1` according to the spec:

![image](https://user-images.githubusercontent.com/1151760/82906198-e0633280-9f32-11ea-9cd8-635b5dca45a5.png)

https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit
