### ISSUE TITLE
CypressError: The XHR server is unavailable or missing.

### ISSUE THREAD

**Issue by lugosium** [cypress-io/cypress#7465]
### Current behavior:

Updated to 4.6.0, get a lot of errors, all already created by others, except this one i think:

  2) Website links
       "before each" hook for "Should open demo page as an anonymous":
     CypressError: The XHR server is unavailable or missing. This should never happen and likely is a bug. Open an issue if you see this message.

Because this error occurred during a `before each` hook we are skipping all of the remaining tests.
      at unavailableErr (https://localhost:8080/__cypress/runner/cypress_runner.js:147830:20)
      at getXhrServer (https://localhost:8080/__cypress/runner/cypress_runner.js:147843:29)
      at Context.server (https://localhost:8080/__cypress/runner/cypress_runner.js:148106:14)
  From Your Spec Code:
      at Context.eval (https://localhost:8080/__cypress/tests?p=tests/cypress/support/index.js:105:6)

### Desired behavior:

-

### Test code to reproduce

Test:

```
it('Should open demo page as an anonymous', function() {
    cy.get('main#main .jumbotron .demo-link').click();
    cy.url().should('contains', '/demo/login');
    cy.get('#login-container').should('be.visible');
});
```

### Versions

Cypress: 4.6.0 (Chrome, headless)

**Comment by lugosium** [comment]
It's working today, don't know why, closing here. 

Thank you Atlanta, keep up the good work! 💪

**Comment by dxc-jbeck** [comment]
I got this error today when running a suite of tests all at once.  I can run the tests in their own integrations/my_test.spec.js file one by one but when I run them with "Run all specs".
The entire suite of tests uses 370kb of mock JSON data in the /fixtures folder. I think this much mock data is causing the Cypress test runner to overload and throw this error.

**Comment by dxc-jbeck** [comment]
This fixes it: `numTestsKeptInMemory`  set to 3.
https://docs.cypress.io/guides/references/configuration.html#Global
