### ISSUE TITLE
some request hangs in 4.6.0

### ISSUE THREAD

**Issue by pangwa** [cypress-io/cypress#7468]
We found cypress timeouts while waiting an request "ray/api/b/school/1/queryClass?levelId=963071&name=class-1590282374378班&rxnd=2020" (this api returns null), the server responses in a very short time(0.02s).

It works well in 4.3.0.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
