### ISSUE TITLE
Learn more link for File Opener Preference returns 404

### ISSUE THREAD

**Issue by mncharlton** [cypress-io/cypress#7475]
## Current behavior:

Click 'Learn More' for the File Opener Preference in the test runner settings
Get 404 page

### Desired behavior:

The URL it directs to (https://on.cypress.io/file-opener-preference) should redirect to https://docs.cypress.io/guides/tooling/IDE-integration.html#File-Opener-Preference

Looking at the others, that appears to be how it's supposed to work, rather than linking straight to the longer URL.

### Test code to reproduce

n/a

### Versions

Cypress 4.6

**Comment by jennifer-shehane** [comment]
Thanks for opening an issue. This is 404'ing, I've got a fix going in for this and will update when it's released.

**Comment by jennifer-shehane** [comment]
This is fixed now! Closing as resolved.
