### ISSUE TITLE
Cookies not sent to the browser on CI

### ISSUE THREAD

**Issue by rovansteen** [cypress-io/cypress#748]
- Operating System:
Running on Travis with a PHP 7.1 box
- Cypress Version:
`1.0.2`
- Browser Version:
Default CI

### Is this a Feature or Bug?
Bug

### Current behavior:
I'm running a React application and a Laravel application. The React application is running on localhost:3000 and the Laravel one is running on localhost:8000. I'm using oAuth and whenever I visit the application it tries to refresh my token by using a refresh token that Laravel stores in the session data. 

Now the issue is that this procedure fails within a test where I login and then visit another page, I get redirected back to the login screen because my API returns a 401 when it tries to refresh token. **When I log the requests on my API I see that there are no cookies on the request**.

This test works fine when running local, with the same configuration and the same host and ports.

Unfortunately, I have no way to get a more clear picture of what's going on inside Cypress right now on CI.

### Desired behavior:
Send the cookies along with the request.

### How to reproduce:
I'll try to set up a minimal repo later to reproduce this issue.

#### Test code:

```js
it('keeps you logged in', () => {
  cy.visit('/login');
  cy.get('input[name=username]').type('j.doe@example.com');
  cy.get('input[name=password]').type('secret');
  cy.get('button').click();
  cy.location('pathname').should('equal', '/');
  cy.contains('j.doe@example.com');
  cy.visit('/');
  cy.location('pathname').should('equal', '/'); // Test fails here, gets redirect to /login
  cy.contains('j.doe@example.com');
});
```

Don't have really much to go from here, so I'm hoping you might be able to point me in a direction where the issue is.

**Comment by rovansteen** [comment]
Still struggling with this. When I add a simple assertion `  cy.getCookie('laravel_session').should('exist');` after the login it fails on the CI while it passes locally (both in Chrome and Electron).

**Comment by brian-mann** [comment]
There's no reason it should fail in CI but then pass locally in Electron.

Are you 100% sure this is the case? Running in CI by default uses Electron. So just make sure you switch to that browser when running locally.

Also it would be *incredibly* helpful to have a reproducible example for this. We have a gazillion tests around cookie handling and its unlikely we'll be able to simulate or think of the situation that is or isn't causing this.

To look into it we'll need more information.

**Comment by rovansteen** [comment]
You were right, the issue itself turned out to be caused by a misconfigured session domain that was caused by a env override I completely missed. 

The tests now pass most of the time but I seem to be suffering from the same issue as  #781 where it sometimes fails because I assume the user is logged out while it still has a cookie from the previous session. But I’ll keep an eye out on that issue and close this one, thanks!
