### ISSUE TITLE
Desired Behavior: manipulate elements in test runner snapshot steps

### ISSUE THREAD

**Issue by jprealini** [cypress-io/cypress#7487]
I was running some tests today, and would have been very helpful to be able to "manipulate" the selected elements in the test runner snapshots list in order to find out why a given element was not being selected, kind of like when you manipulate html code in the devtools Elements tab... 
That way, if you issue a cy.get('i').eq(2) for example, but the element you expect to select doesn't get selected, you could start playing with the get and the eq in the snapshot, changing their values, and seeing "live" in the test runner's browser what the outcome is... 

Descriptive image below

![image](https://user-images.githubusercontent.com/7246755/82944821-41f6c180-9f72-11ea-8375-9a7bc2f99fc4.png)

**Comment by jennifer-shehane** [comment]
You could edit the html, etc in your Dev Tools and then issue Cypress commands in your DevTools in real time using `cy.now()` as shown in this comment: https://github.com/cypress-io/cypress/issues/3636#issuecomment-470011341

The snapshots are just that - snapshots of the entire DOM at that time, so we won't be integrating anything specifically into Cypress to support editing of the snapshot.
