### ISSUE TITLE
Not able to change global variable values inside each() command in Cypress

### ISSUE THREAD

**Issue by gitanshumalhotra** [cypress-io/cypress#7493]
Not able to change global variable values inside each() command in Cypress. 

Expected behavior: 

Should yield the modified value as an output.

Current behavior:

Yields original value as output

```js
var x= "Adams"

cy.get('.id1').find('.class3').find('.id2').each(($el, index, $list) => {
  if (true) {
    x = "Steve"
  }
})
cy.log(x) //Yields Adam as the output, but should yield Steve
cy.pause();
```

**Comment by jennifer-shehane** [comment]
The value of `x` within `cy.log()` is being evaluated before before you have set `x = "Steve".

I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).
