### ISSUE TITLE
Waiting for macOS to verify executable times out

### ISSUE THREAD

**Issue by cbrunnkvist** [cypress-io/cypress#7497]
### Current behavior:

<img width="844" alt="cypress now waiting for application verification" src="https://user-images.githubusercontent.com/34006/82998737-47b3dc00-a032-11ea-83e2-699ca8a8a9c2.png">

### Desired behavior:

If it cannot wait for the verification to exit, I think the wait timeout at least needs to be increased a little bit _or_ add a hint to the error message comforting the (potentially first-time-)user that OKAY maybe it wasn't so bad - just try running the command again.

### Test code to reproduce

Upgrade to a previously uncached Cypress version / delete the matching version in `~/Library/Caches/Cypress/?.?.?`.

### Versions

- Cypress 4.7.0
- macOS 10.15.4

**Comment by RiZKiT** [comment]
This problem exists for a longer time, also appeared in other versions of cypress. MacOS takes longer to validate the app the first time, then the start script is willing to wait for cypress to start.

It appears once after every update of cypress. So not a big problem, but the more annoying the more often you publish new versions. :)

**Comment by jennifer-shehane** [comment]
Could you run `cypress verify` in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

```
DEBUG=cypress:* cypress verify
```

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by RiZKiT** [comment]
Sorry for the late response, the issue did not occurred for the last updates. Thanks!
