### ISSUE TITLE
Unable to load iFrame

### ISSUE THREAD

**Issue by AmiChandra89** [cypress-io/cypress#7508]
Actual:
While loading the portal, iframe is not loading up. Following are the errors in console:

```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src URL". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
[Report Only] Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src <URL> <URL> <URL> <URL> '' 'strict-dynamic' 'unsafe-inline'".
```

Expected:

I should be able to see the iFrame as it properly coming when I am launching the portal from browser

I did try this solution as well: https://gist.github.com/dergachev/e216b25d9a144914eae2 , but it did not work. Screenshot attached.

<img width="1659" alt="Screenshot 2020-05-28 at 10 53 31" src="https://user-images.githubusercontent.com/43046348/83120740-b7c56f00-a0d1-11ea-89c7-266a258235e1.png">

Cypress version: 4.7.0
Chrome version: 83
<img width="1758" alt="Screenshot 2020-05-28 at 10 30 03" src="https://user-images.githubusercontent.com/43046348/83118688-f7d72280-a0ce-11ea-975f-f2cd660598d2.png">

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
