### ISSUE TITLE
Cypress adds underscore while running tests and fails with error - Error: Cannot match any routes. URL Segment: '__'

### ISSUE THREAD

**Issue by anujpin** [cypress-io/cypress#7509]
See following in console logs -

```
An unhandled error occurred Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '__'
Error: Cannot match any routes. URL Segment: '__'
    at ApplyRedirects.noMatchError (router.js:4295)
    at CatchSubscriber.selector (router.js:4259)
    at CatchSubscriber.error (catchError.js:29)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at TapSubscriber._error (tap.js:56)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
```

Following is the `cypress.json` -

```
{
    "baseUrl": "http://localhost:4200",
    "fileServerFolder": ".",
    "fixturesFolder": "./src/fixtures",
    "integrationFolder": "./src/integration",
    "modifyObstructiveCode": false,
    "pluginsFile": "./src/plugins/index",
    "supportFile": "./src/support/index.ts",
    "video": false,
    "videosFolder": "../../dist/cypress/apps/e2e/videos",
    "screenshotsFolder": "../../dist/cypress/apps/e2e/screenshots",
    "chromeWebSecurity": false,
    "testFiles": "**/test.feature",
    "numTestsKeptInMemory": 0,
    "env": {
        "auth_username": "1111",
        "auth_password": "2222",
        "RETRIES": 2
    }
}
```
This is what I see when test runs in cypress window -

`http://localhost:4200/__/#/tests/integration\maintenance\service\test.feature`

**Comment by jennifer-shehane** [comment]
@anujpin We have a potential fix available for this starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments).Can you try setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

**Comment by Ryguy1979** [comment]
This is an issue we have also faced and will try this config. However, a valid work around we have been using is to simply run in Electron.

**Comment by anujpin** [comment]
> @anujpin We have a potential fix available for this starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments).Can you try setting this config option in your `cypress.json` or elsewhere:
> 
> ```json
> {


> @anujpin We have a potential fix available for this starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments).Can you try setting this config option in your `cypress.json` or elsewhere:
> 
> ```json
> {
> 	"experimentalSourceRewriting": true
> }
> ```

@jennifer-shehane , `"experimentalSourceRewriting": true` doesn't help. I tried.

**Comment by jennifer-shehane** [comment]
@anujpin Unfortunately we'll have to close this issue without a way to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example or else we will have to close.

**Comment by anujpin** [comment]
@jennifer-shehane , I followed `https://github.com/nrwl/nx/issues/1276` to setup the tests. We are following feature files (cucumber) pattern in nrwl mono repo. Just in case that gives any pointers.

What else can I provide so that you can reproduce it on your side. Can try setting up a new project and share the repo, may be. We are halfway using cypress and now this issue is completely blocking.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by Aayush9507** [comment]
I am facing the same issue, it works on Electron and even Edge but not on Firefox and Chrome.
I have tried using this but it didn't work for me as well.
```
{
	"experimentalSourceRewriting": true
}
```

**Comment by r20** [comment]
This suddenly happened to me today.  I eventually found that the problem exists when I have my corporate security/monitoring software running (Symantec WSS Agent).  If I disable it, the path and tests are fine.   If I turn it back on, the problem comes back.

**Comment by yogeshgadge** [comment]
This is happening to me todat angular 13 and cypress/schematics 1.6.0 , cypress 9.6.0.

Step1: Create a brand new angular project with routing - call this my-cypress-app

Step 2: ng add @cypress/schematic 

Step 3: ng serve

Step 4: ng run my-cypress-app:cypress-open - click on the spec file, F12 in the another chrome window and this exact error
