### ISSUE TITLE
Mocha done errors don't display stack trace or code frame

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#7514]
### Current behavior:

When Mocha throws an error because the `done` callback is called twice or doesn't get called before the timeout, the error does not show the stack trace or a code frame with links to the calling code.

![Screen Shot 2020-05-28 at 10 38 19 AM](https://user-images.githubusercontent.com/1157043/83156256-2f929a00-a0d0-11ea-88aa-b59086cb0a8f.png)

![Screen Shot 2020-05-28 at 10 39 11 AM](https://user-images.githubusercontent.com/1157043/83156276-328d8a80-a0d0-11ea-860a-57f2ddf0fdce.png)

### Desired behavior:

Such errors should display the stack trace and a code frame pointing to the call site.

### Test code to reproduce

```javascript
it('calls done twice', (done) => {
  done()
  done()
})
```

```javascript
it('done timeout', (done) => {
})
```

### Versions

Cypress 4.6.0+

**Comment by jennifer-shehane** [comment]
This shows a stack trace in 9.5.3. No code frame though. 

<img width="667" alt="Screen Shot 2022-04-08 at 12 41 50 PM" src="https://user-images.githubusercontent.com/1271364/162494095-979317eb-1c19-4b83-b827-bbb13aed04a6.png">
<img width="684" alt="Screen Shot 2022-04-08 at 12 42 17 PM" src="https://user-images.githubusercontent.com/1271364/162494098-eba6b639-191e-449e-b996-94c4fb0b9e7b.png">
