### ISSUE TITLE
Cannot read property '__error' of null

### ISSUE THREAD

**Issue by csalazar1** [cypress-io/cypress#7518]
As of version 4.6.0, Cypress has been throwing this exception during a very simple test that consists of
- Routing a request
- Logging in
- Visiting a page
- Make sure an element is displayed

This issue is reproducible with 4.7.0 version as well. It works perfectly fine in version 4.5.0. 
Here's how to reproduce

1. **Set baseUrl in cypress.json to: https://qa1-cypress.st.dev**
2. Run the following test using either Cypress version 4.6.0 or later
```js
it('Business Unit Test', () => {
    cy.server()
    cy.route({
      method: 'GET',
      url: '/Settings/GetBusinessUnits*',
      response: [{
        Id: 56345,
        Name: 'Test BU',
        OfficialName: 'Test BU',
        Active: true,
        Logo: null,
        PostDate: null,
        QbExportState: null
      }],
      status: 200
    })
    cy.request('POST', '/Auth/Login', { username: 'cydemoadmin', password: 'Test1@#$%' })
    cy.visit('/#/Settings/business-units')
    cy.get('.e2e-column-name').contains('Test BU').should('be.visible')
  })
```

Here's a screenshot of the exception stack trace 
<img width="1902" alt="exceptionStackTrace" src="https://user-images.githubusercontent.com/32462093/83175338-987a1200-a0d0-11ea-83fb-59f1f7c5a371.png">

**Comment by MorganNesbitt** [comment]
Same, tests that never had this now have it appearing all over the place. Cypress says it originates from our app but it doesnt seem like it is, or if it is its not appearing in a console anywhere.

**Comment by FLGMwt** [comment]
Struggled with this as well and the issue seems to with `200` responses with response bodies of the literal value `null`. Cypress errors handling them and the request in the runner appears to be hung. This *does* break my tests.

I'll put up a repro in the next hour but for now, the following should be a good workaround:

```js
it('my test', () => {
  cy.on('uncaught:exception', err => {
    return !err.message.includes(`Cannot read property '__error' of null`);
  });
  // my test code ...
});
```

**Comment by jdmairs** [comment]
I'm seeing it now too after upgrading to v4.7 from v4.5.  This test has never failed before.  Interesting how its mixed in with the Code Coverage section.  

<img width="429" alt="image" src="https://user-images.githubusercontent.com/5624808/83204565-23332f00-a11a-11ea-96d0-3b18d9cd71fd.png">

**Comment by jennifer-shehane** [comment]
Thanks for providing a reproducible example! I can recreate this and see this was introduced in Cypress 4.6.0. I suspect this is related to our error improvements https://github.com/cypress-io/cypress/pull/3930

### 4.5.0

<img width="468" alt="Screen Shot 2020-05-29 at 4 01 22 PM" src="https://user-images.githubusercontent.com/1271364/83244716-b37a7e00-a1c5-11ea-822b-e4b692a39eb8.png">


### 4.6.0

<img width="454" alt="Screen Shot 2020-05-29 at 4 02 52 PM" src="https://user-images.githubusercontent.com/1271364/83244816-e02e9580-a1c5-11ea-8e8a-21f5aadf7722.png">

### Stack trace

This is throwing from this line of code, where the `body` is `null`. 

https://github.com/cypress-io/cypress/blob/issue-7428/packages/driver/src/cypress/xml_http_request.js#L97:L97

In the example, there is a request to `https://qa1-cypress.st.dev/DataProvider/GetEmbeddedPhoneUserConfiguration` that has a `null` response.body.

```
TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read property '__error' of null

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    at XMLHttpRequest._getFixtureError (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:163144:22)
    at onLoadFn (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:161996:27)
    at XMLHttpRequest.<anonymous> (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:161980:25)
From previous event:
    at run (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:155845:19)
    at Object.cy.<computed> [as request] (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:156289:11)
    at Context.runnable.fn (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:156514:21)
    at callFn (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:95404:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:95391:7)
    at https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:160893:28
From previous event:
    at Object.onRunnableRun (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:160881:20)
    at $Cypress.action (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:152580:61)
    at Test.Runnable.run (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:159483:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:96063:10)
    at https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:96189:12
    at next (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:95972:14)
    at https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:95982:7
    at next (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:95884:14)
    at https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:95950:5
    at timeslice (https://qa1-cypress.st.dev/__cypress/runner/cypress_runner.js:89876:27)
```

**Comment by jennifer-shehane** [comment]
I also see these files were converted from coffeescript in the 4.6.0 release in https://github.com/cypress-io/cypress/pull/7227

**Comment by ahmedkotb** [comment]
@jennifer-shehane is this going to be released as a hotfix (in a day or two) ? or will it be released according to the normal release schedule (every two weeks if i remember correctly) ?

**Comment by jennifer-shehane** [comment]
This will be released in our normal release schedule next Monday.

**Comment by colemars** [comment]
Just encountered this - awesome to see it's already been traced and handled.

Thanks @jennifer-shehane and everyone
