### ISSUE TITLE
Incorrectly formatted log message for "have.all.keys" assertion

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#753]
All versions of Cypress when making this assertion

```js
it('expect - assert shape of an object', function(){
  const person = {
    name: 'Joe',
    age: 20
  }
  expect(person).to.have.all.keys('name', 'age')
})
```
Look at the reporter message - looks very weird

<img width="423" alt="have all keys" src="https://user-images.githubusercontent.com/2212006/31674166-1ff6e344-b32f-11e7-9fae-5f6f4401fa80.png">

I added example test to https://github.com/cypress-io/cypress-example-kitchensink/pull/17

**Comment by jennifer-shehane** [comment]
I thought this formatting may have improved in [v4.0 branch of Cypress](https://github.com/cypress-io/cypress/pull/4226) with Chai upgrade, but it hasn't. This is still an issue in 3.4.0
