### ISSUE TITLE
Allow using multiple built-in reporters

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7532]
Cypress v4.7.0

When running with default `spec` reporter I see good human output

```
$ npx cypress run
  Running:  spec.js                                                                         (1 of 1)


  page
    ✓ works (484ms)


  1 passing (3s)


  (Results)
```

But for checking the tests that ran I need `json` reporter

```
$ npx cypress run --reporter json
```

```
  Running:  spec.js                                                                         (1 of 1)
{
  "stats": {
    "suites": 1,
    "tests": 1,
    "passes": 1,
    "pending": 0,
    "failures": 0,
    "start": "2020-05-29T14:02:03.671Z",
    "end": "2020-05-29T14:02:05.415Z",
    "duration": 1744
  },
  "tests": [
    {
      "title": "works",
      "fullTitle": "page works",
      "duration": 434,
      "currentRetry": 0,
      "err": {}
    }
  ],
  "pending": [],
  "failures": [],
  "passes": [
    {
      "title": "works",
      "fullTitle": "page works",
      "duration": 434,
      "currentRetry": 0,
      "err": {}
    }
  ]
}
  (Results)
```

## Json report problem

Let's say we want to validate the tests that executed. We could try using json reporter ... but we cannot get JUST the JSON file

The user could redirect the STDOUT 

```
npx cypress run --reporter json > report.json
```

then there is NO output from the run and the report.json has a mixture of the human output and JSON parts.

### proposal

First, let's split the `json` output and output it to STDERR. Then the user at least could have nice and clean json file

```
npx cypress run --reporter json 2> report.json
```

Note: if there is an error, we write errors to STDERR, but in that case the report is invalid anyway, so I am ok with that.

## Ideally

But I really want both: human-readable spec reporter and json report for checking the tests that executed.

I think a good approach would be to allow specifying multiple reporters using `--reporter name1,name2` and saving additional reports into `cypress/reports` folder

## Why

When running component tests we use settings in cypress.json

```
experimentalComponentTesting: true,
componentFolder: "src"
```

If we change the config key name or how they work - the tests still happily pass (because there are integration specs), yet the component tests that we really wanted to execute never ran, and there is no easy way of verifying the list of files and tests that were executed.

One could install a multi reporter module, but that is unnecessary complexity in my opinion.

**Comment by bahmutov** [comment]
One more point about this: ability to show human spec output and save additional reports to be fed into other test reporting systems would be nice for people using Cypress as a tool in a larger CI system

**Comment by jennifer-shehane** [comment]
Since this feature hasn’t had a lot of interest over the years, we’ll close this issue.
