### ISSUE TITLE
cy.visit() passes but no content loads

### ISSUE THREAD

**Issue by abarajas10** [cypress-io/cypress#7538]
### Current behavior:

Im fairly new to cypress but have been slowly working on it, the issue I have is that when I try to visit my company's website in production (www.jwine.com) I get an issue, cypress "passes" the cy.visit test but no content is ever loaded. We have a dev site, similar to the site in production (acc.jwine.com) which it loads fine and able to do testing but we want to be able to do simple tests in our site.

When I check the logs, there is an issue with initialNavigation. At this point im not sure if its a configuration issue. Been looking without any luck. 

<img width="1400" alt="Screen Shot 2020-05-29 at 8 48 16 AM" src="https://user-images.githubusercontent.com/44122116/83279099-6d072e00-a189-11ea-8d4a-66cbea47f243.png">

<img width="1408" alt="Screen Shot 2020-05-29 at 8 48 59 AM" src="https://user-images.githubusercontent.com/44122116/83279143-8314ee80-a189-11ea-9ba4-3fda4406c8d8.png">

### Desired behavior:

The page to load correctly in order to be able to test the site.

### Test code to reproduce

<img width="424" alt="Screen Shot 2020-05-29 at 8 49 50 AM" src="https://user-images.githubusercontent.com/44122116/83279183-958f2800-a189-11ea-9fae-8ec7d358eef6.png">

<img width="341" alt="Screen Shot 2020-05-29 at 8 49 29 AM" src="https://user-images.githubusercontent.com/44122116/83279197-99bb4580-a189-11ea-8e88-6f4d3a6d138c.png">

### Versions

Cypress 4.7.0
macOS mojave 10.14.6

**Comment by jennifer-shehane** [comment]
I can recreate this with the following code:

```js
it('test', () => {
  cy.visit('https://www.jwine.com/')
})
```

I'm not exactly sure what the issue is with the console error, except that this call is undefined. It's a bit hard to tell what this is supposed to be since it's obfuscated. 

<img width="576" alt="Screen Shot 2020-06-01 at 5 48 19 PM" src="https://user-images.githubusercontent.com/1271364/83404189-30a92b80-a430-11ea-8207-482fdaaa0f1a.png">

**Comment by emilyrohrbough** [comment]
I am unable to create the issues using Cypress 9.1.1 with the following test case.
```
it('test', () => {
  cy.visit('https://www.jwine.com/')
})
```
