### ISSUE TITLE
Elements shown in dev tools do not reference correct DOM nodes when pinned to a snapshot

### ISSUE THREAD

**Issue by avanslaars** [cypress-io/cypress#754]
### Current behavior:

When a snapshot is pinned, choosing a Yielded DOM node in the dev tools and clicking "Reveal in Elements Panel" opens the elements panel, but does not select the expected DOM node. Unpinning the snapshot allows this to work.

### Desired behavior:

"Reveal in Elements Panel" should yield the expected DOM node when pinned to a snapshot.

### How to reproduce:

1. Pin a command in the command log.
2. Open dev tools.
3. Right click the yielded DOM node
4. Choose "Reveal in Elements Panel"
5. Observe that the expected node is not selected

**Comment by jennifer-shehane** [comment]
This is still happening in Cypress 3.4.0

**Comment by jennifer-shehane** [comment]
This is still an issue in 9.5.3
