### ISSUE TITLE
Add package.json to cypress directory for es module compatibility

### ISSUE THREAD

**Issue by or9** [cypress-io/cypress#7544]
### Current behavior:

Cypress fails to open when main package is of type `module` using NodeJS 14.

### Desired behavior:

`/cypress` directory should be created with a package.json file (doesn't actually need any content, but could have `"type": "commonjs"`). 

### Test code to reproduce
```bash
mkdir teststuff
cd teststuff
npm init
npm install cypress --save-dev
```
In package.json, add `"type": "module"`.
Run `npx cypress open`.
![image](https://user-images.githubusercontent.com/1733416/83315922-12092180-a1f1-11ea-9127-34d17de62e93.png)

There will be an error in the launcher.
Create the following package.json in the cypress directory (created by installation scripts?)  
```javascript
// teststuff/cypress/package.json
{
    "type": "commonjs"
}
// or 
{}
// file just needs to exist
```
Open cypress via `npx cypress open`.
Everything is OK.
![image](https://user-images.githubusercontent.com/1733416/83315725-f05b6a80-a1ef-11ea-8a21-a1a53230dc0e.png)

### Versions
* NodeJS 14  
* Windows 10  
* Chrome 81

**Comment by jennifer-shehane** [comment]
I can't recreate the issue as described. I created the repo exactly and added `type: module` to the `package.json` as well as ran this within Node 14.3.0. There are no errors in Cypress 4.7.0 with these steps. 

Please provide a full example - ideally a repo that we can run to reproduce the issue. Maybe there is something in your plugins/support file, tsconfig or something that I don't have?

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by trenc** [comment]
I observed the exact same issues as or9 reported with a clean cypress installation (with -D flag).

Debian 10
Node v14.15.3 (provided by NVM)
Cypress 7.2.0 (package and binary)

**Comment by dgkimpton** [comment]
@or9  
> Create the following package.json in the cypress directory (created by installation scripts?)
> 
> ```js
> // teststuff/cypress/package.json
> {
>     "type": "commonjs"
> }```

Thank you! I just installed cypress and experienced the error you mentioned, with this fix I'm at least able to start trying to write tests. Hopefully, it doesn't cause any issues down the road.
