### ISSUE TITLE
Running Cypress in parallel with debug cypress:* cannot complete because 413 responses from cypress servers

### ISSUE THREAD

**Issue by BadLiveware** [cypress-io/cypress#7548]
### Current behavior:

While trying to debug other issues we have had to run cypress in debug mode however this causes cypress to abort it's test run due to a 413 response from the cypress servers. 
This does not happen when not running in debug mode.

Start task:
```
set DEBUG=cypress:*
npx cypress run --tag debug --config baseUrl=<baseUrl>,video=false --config-file cypress.ci.json --headless --record --group 'Windows/Electron' --parallel --ci-build-id $(Release.DeploymentID) --specs "<specs..>"
```
Settings: 
```json
{
  "viewportWidth":1280,
  "viewportHeight":720,
  "env": {
    "RETRIES": 3
  },
  "numTestsKeptInMemory": 5,
  "video": true,
  "videoCompression": 0,
  "videoUploadOnPasses": false,
  "reporter":"junit",
  "reporterOptions": {
    "mochaFile": "results/TEST-output-[hash].xml",
    "toConsole": false
  },
  "ignoreTestFiles": [
    "*.ts",
    "*.js"
  ],
  "projectId": "xyz"
}
```
[Debug run logs](https://github.com/cypress-io/cypress/files/4710467/Cypress_run_logs.log)

### Desired behavior:
The tests to finish normally.

### Versions

Cypress: version 4.7
Platform: Azure DevOps pipelines
OS: Windows 10
Browser: Electron

**Comment by jennifer-shehane** [comment]
Hey @BadLiveware Thanks for sending over the DEBUG logs. These are helpful. 

I'm going to check with our engineering team on the API side, to see if they have any insight on this specific request and then try to walk back to see how this could be related to the DEBUG logs from the Test Runner.
