### ISSUE TITLE
Failing to reliably connect to Chrome on 4.7.0 when using -b chrome --headless

### ISSUE THREAD

**Issue by AshMcConnell** [cypress-io/cypress#7551]
When upgrading to 4.7.0 (from 4.6.0) we are getting error messages when connecting to chrome about 50-75% of the time, this was not a problem before 4.7.0 (we have used Cypress for a couple of years now).

It only happens when we use `-b chrome --headless`

![image](https://user-images.githubusercontent.com/497941/83400731-43553d80-a3fb-11ea-822b-e401a93cd5f1.png)

### Versions

4.7.0
Windows 10
Chrome 83

**Comment by shutchison-bai** [comment]
Experiencing this as well.  I am seeing this issue when running tests headless and headed in chrome.

Versions
4.7.0
Windows 10
Chrome 83

**Comment by techhysahil** [comment]
I am also getting same issue

**Comment by andrexello** [comment]
We're also seeing this problem. My colleagues and I use Windows 10 but we also see it on our automated test job running on Windows server 2012 R2. Both use Chrome v. 83.0. Initially when this started happening we were using Cypress version 4.7. Then we tried running lower versions - 4.6, 4.5. Both exhibit the issue.

**Comment by samar-77** [comment]
Same issue here. Running Cypress 4.7.0 on Windows 10.
Running against Chrome 83 with --headless

**Comment by rockthis13** [comment]
For me first test passed, but next failed with that issue
Explored in 4.7.0  and 4.6.0 (windows 10)
![image](https://user-images.githubusercontent.com/59865468/83662450-27ef5b80-a5d0-11ea-8daf-f35df5cf03b0.png)

**Comment by PetMou** [comment]
I think this is a copy of #7450 
It is rather blocking, as Google makes it impossible to downgrade to an earlier version of chrome. And yes, Electron is a kind of workaround, but it almost doubles the run duration.

**Comment by WayneHiller** [comment]
Getting this as well, I just updated to Windows 10 2004 not sure if related. Sometimes fails on the first test other times it is after 10 tests run.

**Comment by eabusharkh0** [comment]
Following this thread as it's affecting all my chrome headless tests with Cypress 4.7.0.

**Comment by PetMou** [comment]
Thank you @stevejefferies, adding the --disable-gpu flag to 'before:browser:launch' seems to do the trick for me!

**Comment by eabusharkh0** [comment]
@PetMou which file do you add the --disable-gpu flag to? index.js file inside the plugins folder? also can you share what that code looks like please?

**Comment by O5ten** [comment]
We're seeing this on RHEL on our jenkins (latest and greatest) when running cypress as a container. 

Very random problem.

**Comment by stevejefferies** [comment]
@eabusharkh0 something like the following in plugins/index.js:

```
module.exports = (on, config) => {
  on('before:browser:launch', (browser, args) => {
    if (browser.name === 'chrome' && browser.isHeadless) {
      args.push(
        '--disable-gpu'
      );
      return args;
    }
  });
}
```

**Comment by WayneHiller** [comment]
@stevejefferies That did the trick. Thanks for the work around.

**Comment by eabusharkh0** [comment]
@stevejefferies thank you so much, just a side note, I get a warning after adding your code snippet in the index.js upon execution:
Deprecation Warning: The `before:browser:launch` plugin event changed its signature in version `4.0.0`

The `before:browser:launch` plugin event switched from yielding the second argument as an `array` of browser arguments to an options `object` with an `args` property.

We've detected that your code is still using the previous, deprecated interface signature.

This code will not work in a future version of Cypress. Please see the upgrade guide: https://on.cypress.io/deprecated-before-browser-launch-args

if you click on the link, it says cypress no longer support the second argument being an array but instead it should look something like this (you can click on the link and read all the details as well):
Before The second argument is no longer an array.

on('before:browser:launch', (browser, args) => {
  // will print a deprecation warning telling you
  // to change your code to the new signature
  args.push('--another-arg')

  return args
})
After Access the args property off launchOptions

on('before:browser:launch', (browser, launchOptions) => {
  launchOptions.args.push('--another-arg')

  return launchOptions
})

**Comment by stevejefferies** [comment]
@eabusharkh0 good catch, updated above with 4.x and 3.x versions of the snippet

**Comment by eabusharkh0** [comment]
@stevejefferies I'm still getting the warning in my intellij IDE even after updating the code snippet, any idea on why Cypress is still showing the warning?
![image](https://user-images.githubusercontent.com/57271211/84080823-6e630280-a9a2-11ea-80c5-e698cc28f223.png)

**Comment by WayneHiller** [comment]
@eabusharkh0 Shouldn't it be launchOptions.args.push('--another-arg')

**Comment by samar-77** [comment]
Great! This fixes the issue for me as well. 
I thought that this option was a default in Cypress?
Guess I was wrong...

**Comment by shutchison-bai** [comment]
My tests fail when implementing this workaround.

**Comment by WayneHiller** [comment]
@shutchison-bai Strange, I have over 500 tests passed. Are you comparing screen captures maybe or something like that?

**Comment by shutchison-bai** [comment]
@WayneHiller, I rearrange some code in my plugins/index.js file. The workaround appears to be working now. Thanks!

**Comment by WayneHiller** [comment]
Has anyone noticed a performance hit when specifying --disable-gpu on Chrome? My tests seems to run at about the same speed.

**Comment by shutchison-bai** [comment]
@WayneHiller, My tests run about the same speed as well.

**Comment by PetMou** [comment]
@WayneHiller, here it is a bit slower, but not much (about 3 minutes extra for a run taking about 30 minutes). Nothing dramatic

**Comment by eabusharkh0** [comment]
@WayneHiller when I update the line to use "--another-arg", my tests won't run at all, screenshot is down below, any ideas?
![image](https://user-images.githubusercontent.com/57271211/84175234-49739b80-aa45-11ea-9524-6e76ddee80fa.png)

**Comment by WayneHiller** [comment]
@eabusharkh0 I believe that should be 'disable-gpu' not 'another-arg'. another-arg was just an example of adding an argument.

**Comment by eabusharkh0** [comment]
@WayneHiller thank you, I switched it back to disable-gpu, the tests run but I still get the warning for some reason, any idea why?
![image](https://user-images.githubusercontent.com/57271211/84178074-79bd3900-aa49-11ea-923d-57f7afcc7763.png)

**Comment by WayneHiller** [comment]
@eabusharkh0 Change it to launchOptions.args.push('--disable-gpu');

**Comment by eabusharkh0** [comment]
@WayneHiller thank you so much, that did the trick!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by fattynomnom** [comment]
Still experiencing this problem on version 7.0.1, MacOS Catalina with Chrome 89. Already restarted computer, run `npx cypress cache clear` and `npx cypress install` multiple times. Added the following code to `plugins/index.js` but still not connected:
```
on('before:browser:launch', (browser, launchOptions) => {
        launchOptions.args.push('--disable-gpu')

        return launchOptions
})
```
Can anyone help?

**Comment by cjcrandall** [comment]
For a while the suggested workaround seemed to make this go away for us, but I have occasionally been seeing it again. I'm on Cypress 5.5.0 and Chrome 86. 

Yes, I need to get around to upgrading all my tests to Cypress 7, which I keep putting off mainly due to the change in 6.0.0 that will cause a lot of my `not.visible`-type assertions to fail when I don't really care whether the element happens to exist in the DOM, but that's neither here nor there.

**Comment by Undistraction** [comment]
Seeing this a lot (on Gitlab CI) after upgrading to 7.1.0:
```
  Running:  forms/simple/contact-form.spec.js                                  (1 of 5)
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
Failed to connect to Chrome, retrying in 1 second (attempt 19/62)
Failed to connect to Chrome, retrying in 1 second (attempt 20/62)
Failed to connect to Chrome, retrying in 1 second (attempt 21/62)
Failed to connect to Chrome, retrying in 1 second (attempt 22/62)
Failed to connect to Chrome, retrying in 1 second (attempt 23/62)
Failed to connect to Chrome, retrying in 1 second (attempt 24/62)
Failed to connect to Chrome, retrying in 1 second (attempt 25/62)
Failed to connect to Chrome, retrying in 1 second (attempt 26/62)
Failed to connect to Chrome, retrying in 1 second (attempt 27/62)
Failed to connect to Chrome, retrying in 1 second (attempt 28/62)
Failed to connect to Chrome, retrying in 1 second (attempt 29/62)
Failed to connect to Chrome, retrying in 1 second (attempt 30/62)
Failed to connect to Chrome, retrying in 1 second (attempt 31/62)
Failed to connect to Chrome, retrying in 1 second (attempt 32/62)
Failed to connect to Chrome, retrying in 1 second (attempt 33/62)
Failed to connect to Chrome, retrying in 1 second (attempt 34/62)
Failed to connect to Chrome, retrying in 1 second (attempt 35/62)
Failed to connect to Chrome, retrying in 1 second (attempt 36/62)
Failed to connect to Chrome, retrying in 1 second (attempt 37/62)
Failed to connect to Chrome, retrying in 1 second (attempt 38/62)
Failed to connect to Chrome, retrying in 1 second (attempt 39/62)
Failed to connect to Chrome, retrying in 1 second (attempt 40/62)
Failed to connect to Chrome, retrying in 1 second (attempt 41/62)
Failed to connect to Chrome, retrying in 1 second (attempt 42/62)
Failed to connect to Chrome, retrying in 1 second (attempt 43/62)
Failed to connect to Chrome, retrying in 1 second (attempt 44/62)
Failed to connect to Chrome, retrying in 1 second (attempt 45/62)
Timed out waiting for the browser to connect. Retrying...
Timed out waiting for the browser to connect. Retrying again...
```

**Comment by Danjenator** [comment]
I'm getting this error locally as well. I'm running MacOS BigSur 11.5, Chrome Version 92.0.4515.107, Cypress 7.5.0. It only occurs when I'm not running headless. I can run headless just fine.
