### ISSUE TITLE
cy.wait on aliases array keeps waiting forever

### ISSUE THREAD

**Issue by ofirassif** [cypress-io/cypress#7559]
### Current behavior:

I wanted to use the `cy.wait` for aliases feature in order to wait for 4 xhr requests to return before I start testing elements rendering.

The 4 aliases are: `@getdataflows`, `@getEngines`, `@getInvestigations`, `@getleads` defined as such:
```js
cy.route('\*\*/data-flows/\*').as('getDataFlows');
cy.route('\*\*/hunting-engines\*').as('getEngines');
cy.route('\*\*/investigations\*').as('getInvesigations');
cy.route('\*\*/leads/\*').as('getLeads');
```

The wait command is 

```js
cy.wait(['@getdataflows', '@getEngines', '@getInvestigations', '@getleads'])
```

It seems cypress identifies all the relevant aliases but keeps waiting forever for them to return...

![image](https://user-images.githubusercontent.com/47642765/83447448-22bbd080-a459-11ea-94c4-7ac00aebe5e5.png)

### Desired behavior:

I expected that the `cy.wait` to wait for all aliases to return and then continue.

### Versions

Cypress 4.7.0, macOS Catalina 10.15

**Comment by jennifer-shehane** [comment]
@ofirassif Are you using GraphQL? May be related to this issue https://github.com/cypress-io/cypress/issues/5999

**Comment by ofirassif** [comment]
No..

**Comment by srotak5** [comment]
@ofirassif try this
`cy.wait(['@getdataflows', '@getEngines', '@getInvestigations', '@getleads'], {timeout: 60000}, {multiple: true}) 
            .should('have.property', 'status', 200);`

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
