### ISSUE TITLE
Cypress seems to ignore afterEach hooks registered programmatically

### ISSUE THREAD

**Issue by jan-molak** [cypress-io/cypress#7562]
### Current behaviour:

Cypress does not invoke `afterEach` hooks registered programmatically by a test reporter.

I'm experimenting with writing a [Serenity/JS](https://serenity-js.org) reporter for Cypress. The reporter has a need to perform an async call after each test is finished so that the async operations the reporter runs internally can be synchronised.

The way I'm going about it with other test runners (like [Protractor](https://serenity-js.org/modules/protractor), for example) is by programmatically registering an async `afterEach` hook that returns a `Promise`, which is resolved upon completion of the operations the reporter performs.

Regular Mocha has an API on the `Runner` object that allows reporters to register such hooks:

```javascript
runner.suite.afterEach('my hook', function () {
  // ...
});
```
However, Cypress seems to ignore hooks registered this way.

### Desired behaviour:

I'd love Cypress to behave the same way Mocha does in this regard, so invoke the `afterEach` hook and wait for the `Promise` it returns to resolve before executing the next test.

Alternatively, I'd be grateful if you could point me to an API that allows for `afterEach` hooks to be registered programmatically with Cypress, or any way for a reporter to inform Cypress of async operations it should await for between the tests.

The reporter I'm working on does not need to support the interactive run mode and will be limited to running on CI.

### Test code to reproduce

Create a custom reporter as follows:

```javascript
// reporters/sample-reporter.js
const { Runner } = require('mocha');

module.exports = class SampleReporter {

    constructor(runner, options) {

        console.log('Instantiated');

        runner.on(Runner.constants.EVENT_TEST_BEGIN, (test) => {
            console.log('EVENT_TEST_BEGIN');
        });
        
        runner.on(Runner.constants.EVENT_TEST_PASS, (test) => {
            console.log('EVENT_TEST_PASS');
        });

        runner.on(Runner.constants.EVENT_TEST_FAIL, (test, err) => {
            console.log('EVENT_TEST_FAIL');
        });

        runner.on(Runner.constants.EVENT_TEST_END, (test) => {
            console.log('EVENT_TEST_END');
        });
        
        runner.suite.afterEach('SampleReporter hook', function () {
            console.log('afterEach');

            return Promise.resolve();
        });
    }
}

```

Instruct Cypress to use the `SampleReporter`:

```json
// cypress.json

{
  "reporter": "reporters/sample-reporter.js"
}
```

Execute any test using `cypress run` (I used [this one](https://docs.cypress.io/guides/getting-started/writing-your-first-test.html#Adding-more-commands-and-assertions)) and note the following output:

```
  Running:  sample_spec.js                                                                  (1 of 1)
Instantiated
EVENT_TEST_BEGIN
EVENT_TEST_PASS
EVENT_TEST_END

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     sample_spec.js                                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

As you can see in the listing above, while `Instantiated`, `EVENT_TEST_BEGIN`, `EVENT_TEST_PASS` and `EVENT_TEST_END` are printed correctly, `afterEach` is never executed.

### Versions

Cypress 4.7.0
Mocha 7.2.0
Node 12.14.1
Chrome 83.0.4103.61 (Official Build) (64-bit)
Mac OS 10.15.4

**Comment by jennifer-shehane** [comment]
Have you looked at the `test:before:run` and `test:after:run` event listeners? https://on.cypress.io/catalog-of-events#Cypress-Events

**Comment by jan-molak** [comment]
Hi @jennifer-shehane and thanks for the quick response! It looks like `test:after:run` is exactly what I'm after, thank you very much.
