### ISSUE TITLE
cy.should with custom chai chainable not working as expected

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#7566]
### Current behavior:

I'm attempting to add a custom chai chainable method to use with cypress, now this may be that I have incorrectly implemented the chainable _(apologies if so)_ however this works when using chai elsewhere and also when using expect() over cy.should()

Given the `below` code I expect **both** assertions to have the same outcome however the first assertion using **cy.should()** results in the order being called as followed:
```chainingBehavior (fn) > chainingBehavior(fn) (never hitting the assertion)```
but the desired calling order **(using expect)** is
```chainingBehavior (fn) > assertion method (fn)```

```javascript
cy.get(".block", { timeout: 0 }).should("have.width", 250);

cy.get(".block", { timeout: 0 }).should(($e) => {
    expect($e).to.have.width(250);
});
```

### Desired behavior:

I expect both of the above calls to act the same and have the same outcome.

### Test code to reproduce

Clone: https://github.com/msmps/cy-issue-reproduction-01

```npm test || yarn test```

Chainable: https://github.com/msmps/cy-issue-reproduction-01/blob/master/cypress/support/commands.js

Assertions: https://github.com/msmps/cy-issue-reproduction-01/blob/master/cypress/integration/example.spec.js

### Versions

Cypress 4.7.0, macOS Catalina 10.15.5, Electron & Chrome

**Comment by jennifer-shehane** [comment]
### Reproducible Example:

`index.html`

```html
<html>
  <body>
    <div 
      class="block" 
      style="width: 250px; height: 250px; margin: 25px; background: salmon;">
    </div>
  </body>
</html>
```

`spec.js`

```js
chai.use(function (_chai, utils) {
  const { flag } = utils;

  _chai.Assertion.addChainableMethod(
    'width',
    function (exp) {
      console.log('assertion', this._obj);

      const actual = this._obj;
      return new _chai.Assertion(actual).to.equal(exp);
    },
    function () {
      console.log('chainable (1)', this._obj);

      const element = this._obj;
      const actual = element.outerWidth(); // from jQuery element
      flag(this, 'object', actual);

      console.log('chainable (2)', this._obj);
    }
  );
});

it('should pass when not using a chainable', () => {
  cy.visit('index.html');
  cy.get('.block', { timeout: 0 }).should('have.width', 250);
  // Output.
  // Chainable (1): jQuery element
  // Chinable (2): 250 (width)
  // Chainable (1): 250 (width) (should not hit?)
  // Retry?
  // Never reaches Assertion?
});

it('should pass when using a chainable', () => {
  cy.visit('index.html');
  cy.get('.block').should('have.width.equal', 250);

  // Output.
  // Chainable (1): jQuery element
  // Chinable (2): 250 (width)
  // Assertion handled by .equal
});

it('should pass when using expect', () => {
  cy.visit('index.html');
  cy.get('.block').should(($e) => {
    expect($e).to.have.width.equal(250);
    // Outout.
    // Chainable (1): jQuery element
    // Chainable (2): 250 (width)
    // Assertion handled by .equal

    expect($e).to.have.width(250);
    // Outout.
    // Chainable (1): jQuery element
    // Chainable (2): 250 (width)
    // Assertion: 250
    // Assertion handled by our custom method
  });
});
```

<img width="840" alt="Screen Shot 2020-06-03 at 1 06 00 PM" src="https://user-images.githubusercontent.com/1271364/83603767-02942a80-a59b-11ea-9f86-e886022d5d6e.png">
