### ISSUE TITLE
After Selection ,shows blank space and navigate to next component 

### ISSUE THREAD

**Issue by Gaurav98990** [cypress-io/cypress#7578]
### Current behavior:
Stuck on one of the components (dynamic dropdown ) using cypress,  problem statement --able to handle dynamic dropdown on one field and not on another field using the same approach. after selection ,shows  blank field. and navigate to another component in form.

the test case is failing because the component is a mandatory field in a form.

### Versions

Cypress version -4.5.0
Operating System -window 7
Browser -electron

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example including test code, HTML, CSS, and everything necessary to recreate the issue on our machines and we will consider reopening the issue.

**Comment by Gaurav98990** [comment]
> Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
> 
> Please comment in this issue with a reproducible example including test code, HTML, CSS, and everything necessary to recreate the issue on our machines and we will consider reopening the issue.

Please find the attached ,if you can get an idea what the problem is  and figure out the path

**Comment by Gaurav98990** [comment]
> Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
> 
> Please comment in this issue with a reproducible example including test code, HTML, CSS, and everything necessary to recreate the issue on our machines and we will consider reopening the issue.

Please find the attached,if you can get an idea what the problem is and figure out the path

Also, this dropdown is mix between the simple selector and autocomplete.(above are the attached screenshot and the approach I am trying to resolve this issue.

My question would be ,--How to handle these types of dropdown.
