### ISSUE TITLE
XHR requests do not handle multiple set-cookie headers for the same name in the correct order

### ISSUE THREAD

**Issue by LieutenantClone** [cypress-io/cypress#7579]
### Current behavior:

A `cy.request()` which returns a response with multiple 'set-cookie' headers for the same cookie name will use the first value when setting the cookie.

For example, if the returned set-cookie headers are:
```
Set-Cookie: PHPSESSID=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
Set-Cookie: PHPSESSID=1234567890; path=/; secure; HttpOnly
```
Cypress will use the first line and delete the PHPSESSID cookie.

### Desired behavior:

The last value should be used, to match the behaviour of the browser.  Chrome would use the second line in the example above, and set the PHPSESSID cookie to `1234567890`.

I understand that cypress does not make XHR requests in the browser, it makes an HTTP request from the node server, then pulls out the cookie values itself.  I imagine that this is the source of the incorrect cookie handling.

### Test code to reproduce

Make a cy.request() to any URL that will return two set-cookie headers as described above.

### Versions

Cypress: 4.7.0
Operating System: Ubuntu 16.04.6 LTS (Xenial Xerus)
Browsers: Electron 80, Chrome 83, Firefox 77

**Comment by jennifer-shehane** [comment]
This may be a duplicate of #5688

**Comment by craigblunden** [comment]
I've had the same issue for a while, was tearing my hair out until I saw this comment. Reventing back to 3.4.1 fixed the issue. 

Is there a fix in the works for v5?

**Comment by QuinnMcHale** [comment]
Is there a workaround to this issue?
