### ISSUE TITLE
Execute a subset of specs by subfolders in UI

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#759]
### Is this a Feature or Bug?
Feature

### Current behavior:
In the Cypress UI there is only the option to run either one file or all files altogether.

### Desired behavior:
Provide a run button on subfolder level that only executes tests in spec files below that level (recursively).

**Comment by brian-mann** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/681
