### ISSUE TITLE
Non-cross-origin uncaught error messages are left undefined

### ISSUE THREAD

**Issue by juliogarciag** [cypress-io/cypress#7590]
### Current behavior:

In [this PR](https://github.com/cypress-io/cypress/pull/3930/files#diff-6bc45df9d1822d1a0fc3b057744e9e66L37-L89), the way `createUncaughtException` creates an error changed, and the `message` variable was left `undefined` under these conditions: if `crossOriginScriptRe.test(msg)` fails and the `err` variable is not defined. The error that triggered the situation was a `ResizeObserver loop limit exceeded` error.

Because the error message ends up being `undefined`, checks like this no longer work:

```js
Cypress.on("uncaught:exception", (error) => {
  if (error.message && error.message.includes("ResizeObserver loop limit")) {
    return false;
  }
});
```

This is a screenshot of the debugging session in which I found this:

<img width="1436" alt="Image 2020-06-04 at 2 26 24 PM" src="https://user-images.githubusercontent.com/362584/83802064-bd8df800-a66f-11ea-81ad-2ca02b90a797.png">

### Desired behavior:

The final uncaught error message has the original information and can be used to catch expected errors.

### Test code to reproduce

Any thrown string should work:

`index.html`

```html
<html>
  <body>
    <button id="button">Click</button>
  </body>
  <script>
    document.getElementById("button").addEventListener(() => {
      throw "clicked";
    });
  </script>
</html>
```

`test.js`

```js
Cypress.on('uncaught:exception', (err, runnable) => {
  if (err.message === "clicked") {
    return false;
  }
})

it("should not fail because the error should be caught", () => {
  cy.visit("index.html");
  cy.get("#button").click();
});
```

### Versions

Cypress 4.7.0
MacOS 10.15.5
Electron 80

**Comment by jennifer-shehane** [comment]
The code line being referred to is here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/errors.js#L42:L42

This is a common workaround for people to ignore specific error messages coming from app/cross origin scripts and I believe should be continued to be supported in some way. I even advised people with this ResizeObserver error to ignore them in this way: https://github.com/quasarframework/quasar/issues/2233#issuecomment-492975745

**Comment by chrisbreiding** [comment]
@jennifer-shehane I think the error you're seeing is different due to an omission in the code reproduction. In the html, it should be:

```javascript
document.getElementById("button").addEventListener("click", () => {
```

When I fix that, I get the following error:

```
Cannot read property 'split' of undefined
```

@juliogarciag Is that the error you see when the `ResizeObserver loop limit` error is thrown? Just want to make sure we have the reproduction right.

**Comment by chrisbreiding** [comment]
In looking into this further, I think the test code should be revised to:

```javascript
Cypress.on('uncaught:exception', (err, runnable) => {
  if (err.message.includes("clicked")) {
    return false;
  }
})
```

The error will always be wrapped in the "originated from your application" part, so the message won't exactly equal the one thrown. It will include the message thrown though. This matches the code included in the issue description concerning the `ResizeObserver` error.

**Comment by juliogarciag** [comment]
> @jennifer-shehane I think the error you're seeing is different due to an omission in the code reproduction. In the html, it should be:
> 
> ```js
> document.getElementById("button").addEventListener("click", () => {
> ```
> 
> When I fix that, I get the following error:
> 
> ```
> Cannot read property 'split' of undefined
> ```
> 
> @juliogarciag Is that the error you see when the `ResizeObserver loop limit` error is thrown? Just want to make sure we have the reproduction right.

Oh, it seems I made a mistake on that reproduction. It needs the click to work, and it only happen when an error meets these two criteria. I don't remember right now if that was the exact error I got, just that `error.message` was `undefined`.
