### ISSUE TITLE
Collapse/expand specs in subfolders in UI

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#760]
### Is this a Feature or Bug?
Feature

### Current behavior:
If you structured your tests in various subfolders, the Cypress UI reflects this with indented subheaders, but there's no way to collapse these blocks. In a large project, this can become cumbersome to work with.

### Desired behavior:
Make it possible to collapse (and expand) these subfolders one-by-one and/or all at once.

**Comment by brian-mann** [comment]
Would love to see this as a community PR. This is just front end React work in the `packages/desktop-gui`.

**Comment by metcorne** [comment]
I would like to give this a go

**Comment by metcorne** [comment]
Something like this? https://github.com/cypress-io/cypress/pull/782

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by brian-mann** [comment]
Fixed in [`1.0.3`](https://docs.cypress.io/guides/references/changelog.html#1-0-3).

**Comment by verheyenkoen** [comment]
Wonderful, thanks a million @metcorne!
