### ISSUE TITLE
cy.url() doesn't return url string in headless mode

### ISSUE THREAD

**Issue by ssnsudhakar** [cypress-io/cypress#7602]
### Current behavior:

Can retrieve url string in `cypress open` mode, test runs fine.

Can't retrieve url string in `cypress run` mode, test fails due to variable dependency returns `undefined`.

Tried alias `cy.location('href')` and observed the same behavior.

### Desired behavior:

Expected to retrieve url string irrespective of run mode.

### Test code to reproduce

```js
let urlString;
cy.url().then((url) => {
  urlString = url
})

let urlString;
cy.location('href').then((url) => {
      urlString = url
 })
```

### Versions

Observed in 4.5.0, 4.7.0
Browser Chrome 83

**Comment by jennifer-shehane** [comment]
Please provide a full failing example of your test. The situation you've given has no `cy.visit()` and no evaluation of the `url` later, so I'm not sure where you are evaluating the `urlString` to be undefined. The context of these other commands are important.

**Comment by ssnsudhakar** [comment]
Below is the test code written which works fine in both open and run mode.
In our case test case 2, cy.visit() ends with undefined in run mode and works fine in open mode.

let urlString;
describe('Sample Test', function () {
    it('Url Verification 1', async () => {
        Cypress.config('baseUrl', "https://cypress.io")
        cy.visit("/features")
            .url().should('contain', 'features')

        urlString = await new Cypress.Promise((resolve, reject) => {
            cy.url().then(async (url) => {
                let urlSuffix = url.substring(url.indexOf("/fe")).slice(4)
                resolve(urlSuffix)
            })
        })
        cy.log("Url String : " + urlString)
    })

    describe('Url Verification 2', function () {
        it('Url Verification', function () {
            cy.visit("/fea" + urlString)
            cy.log("Url String : " + urlString)
        })
    })
})

**Comment by jennifer-shehane** [comment]
@ssnsudhakar You cannot ever run Cypress commands inside of a promise because of the way that Cypress commands are enqueued, so likely there is some variability with how this runs between open mode and run mode - sometimes the Promise has resolved, sometimes it hasn't. 

I'm not sure why this Promise is necessary, the url is static at this point, so you can just assign the value to the `urlString`.

```js
let urlString;
describe('Sample Test', function () {
  it('Url Verification 1', () => {
    cy.visit("https://cypress.io/features")
    cy.url().should('contain', 'features').then((url) => {
      let urlSuffix = url.substring(url.indexOf("/fe")).slice(4)
      urlString = urlSuffix
    })
    cy.log("Url String : " + urlString)
  })

  it('Url Verification 2', function () {
    cy.visit("https://cypress.io/fea" + urlString)
    cy.log("Url String : " + urlString)
  })
})
```
