### ISSUE TITLE
cy.should('have.value', someValue) always fails when applied to <progress> or <meter> elements

### ISSUE THREAD

**Issue by LisaManresa** [cypress-io/cypress#7603]
### Current behavior:

`cy.should('have.value', someValue)` always fails when testing `<progress>` or `<meter>` elements. This is regardless of whether the value passed to the assertion is a String or Number.

Assertion results in `expected '<progress#progressEl>' to have value '50', but the value was 50`
![Screen Shot 2020-06-05 at 8 58 54 AM](https://user-images.githubusercontent.com/1137390/83897792-e6af9680-a70a-11ea-9f82-f05515f05ece.png)

### Desired behavior:

When applied to a `<progress>` or `<meter>`  element, the `cy.should('have.value', someValue)` should behave the same way it does for `<input>` elements.

### Test code to reproduce
HTML
```html
<progress id="progressEl" max="100" value="50">50%</progress>
```

Test
```js
cy.get('#progressEl').should('have.value', 50);
```

Comparison between `have.value` asserted on `<input>` vs `<progress>`/`<meter>`, as well as a comparison with `have.attr` can be found here: https://github.com/LisaManresa/cypress-test-tiny

### Versions

Cypress 4.6.0

**Comment by jennifer-shehane** [comment]
@LisaManresa Thanks for providing a reproducible example! This looks to be a regression introduced in 4.6.0 very likely within https://github.com/cypress-io/cypress/issues/7314

A progress element's `value` actually accepts a floating point number, as opposed to `input` values which accept strings, which is what the main use case was considering with the change that was made in 4.6.0. So I think it wasn't taking `progress` and `meter` HTML elements into account. 

```html
<html>
<body>
<progress max="100" value="70">70%</progress>
<meter min="0" max="100" low="33" high="66" optimum="80" value="50">
  at 50/100
</meter>
</body>
</html>
```

```js
describe('progress', () => {
  it('test', () => {
    cy.visit('index.html')
    // ❗️fails in 4.6.0 - passes in 4.5.0
    cy.get('progress').should('have.value', 70) 
  })
  
  it('test', () => {
    cy.visit('index.html')
    // fails in 4.6.0 and 4.5.0
    cy.get('progress').should('have.value', '70') 
  })
  
  it('test', () => {
    cy.visit('index.html')
    // passes in 4.6.0 and 4.5.0
    cy.get('progress').invoke('val').should('eq', 70) 
  })
  
  it('test', () => {
    cy.visit('index.html')
    cy.get('progress').should(($el) => {
      // passes in 4.6.0 and 4.5.0
      expect($el.val()).to.eq(70)
    })
  })
})

describe('meter', () => {
  it('test', () => {
    cy.visit('index.html')
    // ❗️fails in 4.6.0 - passes in 4.5.0
    cy.get('meter').should('have.value', 50)
  })

  it('test', () => {
    cy.visit('index.html')
    // fails in 4.6.0 and 4.5.0
    cy.get('meter').should('have.value', '50')
  })

  it('test', () => {
    cy.visit('index.html')
    // passes in 4.6.0 and 4.5.0
    cy.get('meter').invoke('val').should('eq', 50)
  })

  it('test', () => {
    cy.visit('index.html')
    cy.get('meter').should(($el) => {
      // passes in 4.6.0 and 4.5.0
      expect($el.val()).to.eq(50)
    })
  })
})
```

<img width="889" alt="Screen Shot 2020-06-08 at 3 34 53 PM" src="https://user-images.githubusercontent.com/1271364/84012486-a1ef5e00-a99d-11ea-876c-dbab2a4aee67.png">


### Workaround

Downgrade to 4.5.0 or use one of the other passing methods above to test the value outside of the `.should()` chainers.
