### ISSUE TITLE
One of the custom commands returns error "is not a function"

### ISSUE THREAD

**Issue by kamilpioro** [cypress-io/cypress#7604]
So what to begin with.
- I created a new folder with for custom commands .js files.
- I named it paymentFormCommands.js.
- Added import in index.js file.

And for some reason one of the commands returns "TypeError {functionName} is not a function" while invoked.

THIS command:
```
Cypress.Commands.add('setDateAndProceed', () => {
  function getMonth(date) {
    const month = date.getMonth() + 2;
    return month < 10 ? `0${month}` : `${month}`;
  }
  const d = new Date();
  const n = d.getMonth(d) + 2;
  cy.wait(1000);
  cy.get('div[class*="PaymentPreferences-cssmodule-item-"]').eq(0).find('input[name="month"]').clear()
    .type(n, typeOptions);
  cy.get('div[class*="PaymentPreferences-cssmodule-item-"]').eq(0).find('input[name="day"]').clear()
    .type('01', typeOptions);
  cy.get('div[class*="PaymentPreferences-cssmodule-item-"]').eq(0).find('input[name="year"]').clear()
    .type('2020', typeOptions);
  cy.get('button[name="preferences[0].payment_form"]').click({ force: true });
  cy.get('div[class*="SelectField-cssmodule-menuVisible-"] button[class*="SelectItem-cssmodule-selectItem-"]').eq(0).click({ force: true });
  cy.get('div[class*="PaymentPreferences-cssmodule-item-"]').eq(1).find('input[name="month"]').invoke('attr', 'value')
    .then((classValue) => {
      expect(classValue).to.contain(getMonth(d));
    });
  cy.get('div[class*="PaymentPreferences-cssmodule-item-"]').eq(1).find('input[name="day"]').invoke('attr', 'value')
    .then((classValue) => {
      expect(classValue).to.contain('1');
    });
  cy.get('div[class*="PaymentPreferences-cssmodule-item-"]').eq(1).find('input[name="year"]').invoke('attr', 'value')
    .then((classValue) => {
      expect(classValue).to.contain('2020');
    });
  cy.get('form button[data-title="Next Step"]').eq(0).click({ force: true });
});
```

What is worth mentioning, all others commands work fine.

My first workaround was to paste this custom command to commands.js - it worked every time.
My final workaround was to change file name to payment_forms_commands.js, update index.js and it worked.

I also have other file with custom commands named signCommands.js and there is no problem with that.

![image](https://user-images.githubusercontent.com/64773325/83888363-04502080-a74a-11ea-9a22-8a9e81eb82d4.png)

Can someone explain me, why file naming was the issue here?

Cypress version 4.5.0.

**Comment by kamilpioro** [comment]
Restart helped  ¯\\\_(ツ)\_/¯

**Comment by Diazhao** [comment]
restart may helped. but if you need to do something when error coming, this case will make wrong result, maybe
