### ISSUE TITLE
Feature Request:  Allow us to configure additional attributes to the default "SELECTOR_PRIORITIES" through 'cypress.json' config

### ISSUE THREAD

**Issue by mthoreso** [cypress-io/cypress#7606]
### Current behavior:

Cypress prefers `data-cy` and `data-test` as element attributes which is great.

### Desired behavior:

Allow us to add to this list of element attributes because, let's face it, we might not be able to get large engineering departments to follow Cypress's recommendations.  I work at a company who enforces the `data-qa` attribute (so close).  

Create a new configuration attribute, something like `additionalSelectors`:
```
cypress.json
{
  additionalSelectors: ["data-qa", "data-bar"]
}
```

If any are present they will get added to the `SELECTOR_PRIORITIES` in `packages/driver/src/cypress/selector_playground.js`

Then please add this to the configuration documentation at https://docs.cypress.io/guides/references/configuration.html#Options

**Comment by jennifer-shehane** [comment]
This is already configurable via the `Cypress.SelectorPlayground` api: https://on.cypress.io/selector-playground-api#Selector-Priority

```
Cypress.SelectorPlayground.defaults({
  selectorPriority: ['data-qa', 'data-bar', 'data-cy', 'data-test']
})
```

**Comment by mthoreso** [comment]
Thank you for the information @jennifer-shehane !  Does this have to be done in every `spec` file?  It doesn't seem like you can do it in the `plugins/index.js` file.

**Comment by jennifer-shehane** [comment]
@mthoreso You should be able to put it in the support file, which is basically what is run before the spec files - `cypress/support/index.js` by default.

**Comment by mthoreso** [comment]
Awesome, thanks Jennifer!
