### ISSUE TITLE
Failed to connect to chrome Cypress 4.7.0

### ISSUE THREAD

**Issue by eabusharkh0** [cypress-io/cypress#7607]
After upgrading to cypress 4.7.0, I started getting "Failed to connect to Chrome, retrying in 1 second..."

![image](https://user-images.githubusercontent.com/57271211/83918865-2abc8e80-a73f-11ea-9cec-4500f31783a4.png)

### Desired behavior:

To be able to run cypress tests in chrome headless mode without failing.

### Test code to reproduce

No test code here, just the CI run command in the screenshot.  When I revert back to Cypress 4.6.0, the same command runs fine and tests execute with no issues.

### Versions

4.7.0, Windows 10, Chrome 83.

**Comment by clarmso** [comment]
Maybe duplicate of #7551 and/or #7450

**Comment by jennifer-shehane** [comment]
Closing as duplicate of #7551

**Comment by Rajaptron** [comment]
getting the Failed to connect to Chrome, retrying in 1 second (attempt 62/62) with cypress 8.6.0 & 8.7.0 both latest versions. can anyone help in this
