### ISSUE TITLE
Expose cypress open dashboard as web app

### ISSUE THREAD

**Issue by dan-cooke** [cypress-io/cypress#7610]
This is a question, apologies - but I have asked 5 times on https://on.cypress.io/chat  with no replies.

Is it possible to expose the electron app that appears when you run `.bin/cypress open` as a webapp ? 

We would like to be able to have our QA run Cypress tests from a single place, instead of from their local environments.

I'm aware that this encroaches on the Cypress dashboard territory, but unfortunately we are not able to get funding for this at the time being.

**Comment by jennifer-shehane** [comment]
Sorry for the lack of replies in the chat. We're hoping to improve community options for questions soon.

The only other way currently available to run Cypress without having it completely installed through `npm` would be to download the app directly and choose a local project to run in there. https://on.cypress.io/installing-cypress#Direct-download This could maybe be used to uncomplicate some of your process.

But no, Cypress is not be available as a web application where tests could be run. It has to be installed on a machine. The Cypress Dashboard doesn't offer this either, it offers a place to *view* the results of recorded runs that were executed elsewhere via `cypress run`.

**Comment by dan-cooke** [comment]
No problem, I understand you guys are swamped with questions in there.

Thanks for the suggestion. The installation via npm is not a major pain
point for us currently, but we may consider a direct download in future.

That's unfortunate, It would definitely be a cool feature. Provided it's
possible to implement in a secure manner.

Just for one final question then,

Do you know of any way of getting the entire test "schema".

Ie. The same object that a reporter would generate after a test run.

We would like to display a list of pending , passed tests etc. Based on
what our travis pipeline is currently running, but we would need a list of
_all_ tests _before_ the run is complete.

I would imagine there is some kind of mocha parser or something?

Thanks for your time, Cypress is an awesome application

**Comment by jennifer-shehane** [comment]
Anything that we have would display the results of tests after they are run. We don't know what tests are expected before they complete/run.

Maybe you could hook into Cypress events if you want to do something really fancy before/after each test. https://on.cypress.io/catalog-of-events#Cypress-Events

But there's the [Module API](https://on.cypress.io/module-api), and our Dashboard has GitHub and Slack integration which would show results after the run. 

Outside of that you could utilize some custom reporters https://pm.cypress.io/reporters
