### ISSUE TITLE
Error: Cannot find module '@azure/logger' from '\node_modules\@azure\identity\dist'

### ISSUE THREAD

**Issue by rmnunes** [cypress-io/cypress#7612]
### Current behavior:

```
Error: Cannot find module '@azure/logger' from ..\node_modules\@azure\identity\dist'
```

### Desired behavior:

Under `plugins/index.js` this statement should work

```js
const { DefaultAzureCredential } = require("@azure/identity")
const { SecretClient } = require("@azure/keyvault-secrets")
```

### Test code to reproduce

- create a sample cypress test add those 2 libraries
- `npm install @azure/keyvault-secrets`
- `npm install @azure/identity`

https://www.npmjs.com/package/@azure/keyvault-secrets

### Versions
4.7.0

**Comment by jennifer-shehane** [comment]
I'm not able to recreate this from the information provided. Please provide a full repo that reproduces the results. Likely there's something else in the project involved - like, do you have TypeScript set up on the project? 

Also, where and when are you seeing this error display?

My code is below - `cypress open` opens successfully.

```json
{
  "name": "my-application",
  "version": "1.2.3",
  "devDependencies": {
    "cypress": "4.7.0"
  },
  "dependencies": {
    "@azure/identity": "^1.0.3",
    "@azure/keyvault-secrets": "^4.0.4"
  }
}
```

`cypress/plugins/index.js`

```js
const { DefaultAzureCredential } = require("@azure/identity")
const { SecretClient } = require("@azure/keyvault-secrets")

module.exports = (on) => {
};
```

**Comment by rmnunes** [comment]
Thanks for your help! What I'm trying to do is protect secrets, and not expose them on cypress.json as env. Is there any thing out the box to do like so?

**Comment by jennifer-shehane** [comment]
@rmnunes There are multiple ways to pass env vars through Cypress, not just statically in the `cypress.json`, so you could likely utilize one of those ways to make the keys secret, depending on your workflow. https://on.cypress.io/environment-variables#Setting

You could have a `cypress.env.json` file that is not committed to git for example, that your team generates somehow on your end. 

Is the issue with the imports resolved for you?

**Comment by rmnunes** [comment]
It did! This is what I'm trying to do:
```const fs = require("fs-extra")
const path = require("path")
const { SecretClient } = require("@azure/keyvault-secrets")
const { DefaultAzureCredential } = require("@azure/identity")

function getConfigurationByFile(file) {
  const pathToConfigFile = path.resolve("cypress", "config", `cypress.${file}.json`)

  return fs.readJsonSync(pathToConfigFile)
}

async function KeyVault(url, secretName) {
  const credential = new DefaultAzureCredential()
  const client = new SecretClient(url, credential)
  return await client.getSecret(secretName)
}

module.exports = (on, config) => {
  // accept a configFile value or use local by default
  const file = config.env.configFile || "local"
  var jsonFile = getConfigurationByFile(file)

  if(!process.env.CI){
    KeyVault("uri", "client_secret").then((secret) => {
      jsonFile.env.client_secret = secret.value
    })
    KeyVault("URI", "password").then((secret) => {
      jsonFile.env.password = secret.value
    })
  }

  console.log(jsonFile)

  return jsonFile
}

**Comment by prma85** [comment]
> It did! This is what I'm trying to do:
> 
> ```
> const path = require("path")
> const { SecretClient } = require("@azure/keyvault-secrets")
> const { DefaultAzureCredential } = require("@azure/identity")
> 
> function getConfigurationByFile(file) {
>   const pathToConfigFile = path.resolve("cypress", "config", `cypress.${file}.json`)
> 
>   return fs.readJsonSync(pathToConfigFile)
> }
> 
> async function KeyVault(url, secretName) {
>   const credential = new DefaultAzureCredential()
>   const client = new SecretClient(url, credential)
>   return await client.getSecret(secretName)
> }
> 
> module.exports = (on, config) => {
>   // accept a configFile value or use local by default
>   const file = config.env.configFile || "local"
>   var jsonFile = getConfigurationByFile(file)
> 
>   if(!process.env.CI){
>     KeyVault("uri", "client_secret").then((secret) => {
>       jsonFile.env.client_secret = secret.value
>     })
>     KeyVault("URI", "password").then((secret) => {
>       jsonFile.env.password = secret.value
>     })
>   }
> 
>   console.log(jsonFile)
> 
>   return jsonFile
> }
> ```

Did you have your problem solved? I am having the same issue when using typescript 🤔 

But instead of plugin, I am using it as a command to get the token and do a login before each test.

It returns the error '@azure/logger'

**Comment by rmnunes** [comment]
@prma85 This is how I did, and it worked the way I want.
under plugins -> index.js
```
const fs = require("fs-extra")
const path = require("path")
const { SecretClient } = require("@azure/keyvault-secrets")
const { DefaultAzureCredential } = require("@azure/identity")

function getConfigurationByFile(file) {
  const pathToConfigFile = path.resolve("cypress", "config", `cypress.${file}.json`)

  return fs.readJson(pathToConfigFile)
}

async function KeyVault(url, secretName) {
  const credential = new DefaultAzureCredential()
  const client = new SecretClient(url, credential)
  return await client.getSecret(secretName)
}

module.exports = (on, config) => {
  on("task", {
    getSecret({ url, secretName }) {
      return KeyVault(url, secretName)
    },
  })

  on("before:browser:launch", (browser = {}, launchOptions) => {
    if (browser.family === "chromium" && browser.name !== "electron") {
      launchOptions.args.push("--disable-dev-shm-usage")
    }

    return launchOptions
  })

  // accept a configFile value or use local by default
  const file = config.env.configFile || "local"
  return getConfigurationByFile(file)
}
```

later I created a command, under support, and called the task. You can't use the keyVault function directly on your spec files. You need to use task for that.

```
Cypress.Commands.add("keyVault", (url) => {
  const keyVaultUri = Cypress.env("keyvault_uri")
  cy.task("getSecret", { url: keyVaultUri, secretName: "AADClientSecret" }).then((secret) => {
     // call your login passing secret.value
    .....
  })  
})
```
I hope that helps. xD
