### ISSUE TITLE
Cypress 4.7.0 | Cypress failed to start

### ISSUE THREAD

**Issue by sivakrishna-wq** [cypress-io/cypress#7616]
I have installed cypress 4.7.0 . and ran `./node_modules\.bin\cypress open`. I get the below error

```
It looks like this is your first time using Cypress: 4.7.0

  ×  Verifying Cypress can run C:\Users\Username\AppData\Local\Cypress\Cache\4.7.0\Cypress
    → Cypress Version: 4.7.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

spawn EPERM

----------

Platform: win32 (10.0.18362)
Cypress Version: 4.7.0
```

**Comment by jennifer-shehane** [comment]
@sivakrishna-wq Opening Cypress will require write permissions, can you verify the correct permissions are set? https://github.com/cypress-io/cypress/issues/7310

**Comment by LoganFievez** [comment]
I had the same error
I came back to 4.6.0 and everything works fine with 4.6.0

**Comment by sivakrishna-wq** [comment]
I did not have write access to C:\Users\Username\AppData\Local\Cypress\Cache\4.7.0\Cypress
1       Create a folder ex – C:\Cypress
2.       Create system environment variable – CYPRESS_CACHE_FOLDER – C:\Cypress
3.       Run the command Set CYPRESS_CACHE_FOLDER= C:\Cypress
4.       Run npm install cypress --save-dev
5.       Run npx cypress open or ./node_modules/.bin/cypress open

Issue is resolved.

**Comment by dinaRodeny** [comment]
try  npx cypress install --force

**Comment by shellbot97** [comment]
Followed all the steps given by @sivakrishna-wq 
It's still giving me the following error with version 6.8.0

```
----------

Command failed with EPERM: C:\Cypress\6.8.0\Cypress\Cypress.exe --smoke-test --ping=8
spawn EPERM

----------
```

**Comment by Joost-SF** [comment]
I had the same issue and went back to 7.3.0. 

This was working fine on that version, but when I installed 7.4.0 it instantly crashed a perfectly working project.

Also, there is no list of dependencies to be found in the link it points me to.
