### ISSUE TITLE
win.localStorage was cleared between cases.

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#7617]
``` typescript
describe("Test AlertList", () => {
  before("Login", () => {
    cy.login() // after login , save some info like token into win.localStorage
  });

  beforeEach("beforeEach", () => {
    cy.window().then((win) => {
        console.log("afterEach localStorage==>", win.localStorage);
    });
    cy.server();
  });

  afterEach("after", () => {
    cy.window().then((win) => {
        console.log("afterEach localStorage==>", win.localStorage);
    });
  });

  it("test1", () => {
  	...
  });

  it("test2", () => {
  	...
  });
});
```

after case "test1",  win.localStorage still save some values, but before next case, win.localStorage was cleared: 

<img width="491" alt="截屏2020-06-08 下午3 08 12" src="https://user-images.githubusercontent.com/22906174/84001838-06102300-a99a-11ea-9737-4c7b2d4f0589.png">

<img width="658" alt="截屏2020-06-08 下午2 50 06" src="https://user-images.githubusercontent.com/22906174/84000662-a6187d00-a997-11ea-89ef-0c332d33c1a6.png">

Is this function changed or a bug?
Usually, only login when "before", and all cases will share token info, instead of login before every cases.

Cypress: 4.7.0
Chrome: 83.0.4103.61
MacOS: 10.15.4

**Comment by jennifer-shehane** [comment]
Cypress automatically clears localStorage before each test runs. https://on.cypress.io/clearlocalstorage#Syntax

>Is this function changed or a bug?
>Usually, only login when "before", and all cases will share token info, instead of login before every cases.

Can you be more specific about what 'usually' means here? Did you recently upgrade Cypress or make changes to your application and this behavior changed?

**Comment by JFRabbit** [comment]
@jennifer-shehane 

If "Cypress automatically clears localStorage before each test runs.", I just need add "cy.longin()" into "beforeEach()" instead of "before()".

But this will spending some time with "cy.longin()"  between each test, cause clear localStorage will clear user token.

Can this function add to "cypress.json" ? User can open or close "clears localStorage" with config.

**Comment by jennifer-shehane** [comment]
@JFRabbit We're working on reworking how the clearing of state works here: https://github.com/cypress-io/cypress/issues/686 

For now, this is how it works, so it would spend more time logging in in between or you can follow some of the workaround in https://github.com/cypress-io/cypress/issues/461 to save the localStorage across tests.

**Comment by lucasdonato** [comment]
Good night, any release forecast?
I need the cypress not to clean the localStorage between tests.
Thanks
