### ISSUE TITLE
cy.click() on anchor throws cross domain error when destination page has server error

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#762]
### Current behavior:
When I `cy.click()` a (non-cross-domain) anchor of which the destination page throws an HTTP 500 server error, Cypress logs a cross-origin-violation (thus failing the test).

If I run with `chromeWebSecurity: false` the test passes. I'd expected this to fail as well because `cy.visit()` asserts it that way, but since it's [not in the docs](https://docs.cypress.io/api/commands/click.html#Assertions) I guess that part is not a bug.

### Desired behavior:
Cypress should not log a cross-origin-violation error.

#### Test code:
With `chromeWebSecurity: true`:

```js
cy.get({some anchor that links to a page that errors}).click();
```

### Additional Info (images, stack traces, etc)

![image](https://user-images.githubusercontent.com/599538/31722266-f2484f6c-b41b-11e7-855a-e5f9a2587937.png)

FYI: `cy.prop('abc')` is just shorthand for `cy.invoke('prop', 'abc')`.

- Operating System: Mac OS X Sierra
- Cypress Version: 1.0.2
- Browser Version: All

**Comment by rockthis13** [comment]
This one helped me to make turn around, because my tests are working but cypress retun
"anchors is not iterable" error
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
  })

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
