### ISSUE TITLE
Update contributing with instructions on how to run tests in the driver package

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#763]
*General note:* The best source of truth in figuring out how to run tests for each package is our `circle.yml` file found in the main `cypress` directory. The tasks defined in our `cypress.yml` are all run before anything is deployed.

**To run end-to-end tests for the `driver` package from the Cypress Test Runner:**
- In the `cypress` directory, run `npm install` & `npm start`.
- When the Cypress Test Runner opens, manually add the directory `cypress/packages/driver/test`.
- In the `cypress/packages/driver` directory, run `npm start`.
- Click into the `test` directory from the Cypress Test Runner.
- Select any test file you want to run.

**To run end-to-end tests in the `driver` package from the terminal:**
- In the `cypress` directory: run `npm install`.
- In the `cypress/packages/driver` directory, run `npm start` & `npm run test-integration`.
- The Cypress Test Runner should spawn and run through each test file individually.

**Comment by chrisbreiding** [comment]
It should be noted that for developing the driver, you need to watch the files using one of the following methods:

* `npm run watch` from root directory: This will run the watch task for all packages that have one
* `npm run watch` from `packages/runner`: This will run the watch task for the runner, which bundles the driver
