### ISSUE TITLE
Test configuration object ignored for viewportHeight and viewportWidth

### ISSUE THREAD

**Issue by maximilianschmid** [cypress-io/cypress#7631]
### Current behavior:
Testrunner browser window does not respect viewportWidth and viewportHeight configuration passed in via a configuration object to the test or suite function as the second argument.

Your test checks if config object get's the value, which it does.
https://github.com/cypress-io/cypress/commit/4cfcae28f097e013ffe7dc7419905eccf1022709#diff-8a1bc60bd20378ff06f1cd550ab21defR59

But the testrunner browser window does not get resized.

![Screenshot 2020-06-09 at 09 37 24 (2)](https://user-images.githubusercontent.com/574203/84119676-ff82b980-aa34-11ea-93bd-a86383975954.png)

### Desired behavior:
Testrunner browser window should respect viewportWidth and viewportHeight passed in via a configuration object to the test or suite function as the second argument.

### Test code to reproduce
```js
describe('demo.planfred.com …', {
  viewportHeight: 800,
  viewportWidth: 400,
  baseUrl: 'https://demo.planfred.com/'
}, () => {
  it('test', () => {
    cy
      .visit('https://demo.planfred.com/')
  })
})

```

### Versions
4.8.0

Should work in 4.8.0 according to feature issue https://github.com/cypress-io/cypress/issues/7167

┆Issue is synchronized with this [Jira Story](https://cypress-io.atlassian.net/browse/TR-121) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Yes, I can confirm setting `viewportHeight` and `viewportWidth` is not actually changing the viewport size of the suite/test that it's passed to in 4.8.0. 

The [original PR](https://github.com/cypress-io/cypress/pull/5346) is only checking that the `Cypress.config().viewportHeight`, etc values are correct, but there have been [other instances](https://github.com/cypress-io/cypress/issues/6407) where this value can be correct and actually have no effect on the behavior of the test. 

The `baseUrl` is taking effect and working in the example below however. 

```js
describe('test', {
  viewportHeight: 200,
  viewportWidth: 400,
  baseUrl: 'https://example.cypress.io'
}, () => {
  it('test', () => {
    cy.visit('/').then(() => {
      expect(Cypress.config().viewportHeight).eq(200) // passes
      expect(Cypress.config().viewportWidth).eq(400)  // passes
    })
  })
})
```

<img width="1399" alt="Screen Shot 2020-06-09 at 2 32 35 PM copy" src="https://user-images.githubusercontent.com/1271364/84122511-8b5d0b80-aa5e-11ea-96f6-cbc1bcb9057c.png">
