### ISSUE TITLE
Applitools plugin blocker using it with cucumber plugin.

### ISSUE THREAD

**Issue by joydeep100** [cypress-io/cypress#7632]
### Current behavior:
Applitools plugin blocker when using it with cucumber plugin.

![image](https://user-images.githubusercontent.com/45758076/84120715-d6bdec80-aa53-11ea-9cac-4ed3e17f2311.png)

### Desired behavior:
We should be able to run our spec / feature files containing the test cases.

### Test code to reproduce

Pre-Conditions - create an Applitools account and update the `apiKey` in `applitools.config.js` file

1. Clone the sample repo provided by applitools ```git clone https://github.com/applitools/tutorial-cypress.git```
2. Add ```"cypress-cucumber-preprocessor": "^2.0.1"``` in your package.json file under dependecies
3. Add this code in your `support/plugins/index.js` as mentioned by cucumber docs.
```js
const cucumber = require('cypress-cucumber-preprocessor').default
module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
}
```
4. Try to run the test file `ultraFastGrid.spec.js`, you will get the error

### Versions
Replicated with Cypress v4.7.0 and v4.8.0

**Comment by jennifer-shehane** [comment]
@joydeep100 This does not appear to be related to the Cypress product directly. Please reach out to the corresponding plugin where the error is being thrown. It looks like this error is being thrown from within the applitools plugin.

**Comment by joydeep100** [comment]
[tutorial-cypress.zip](https://github.com/cypress-io/cypress/files/4750829/tutorial-cypress.zip)
Actual project files.

**Comment by joydeep100** [comment]
@jennifer-shehane Yes, i have raised a ticket with applitools. Thanks.

**Comment by joydeep100** [comment]
Not a bug issue was i was exporting modules twice.

```
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
}

require('@applitools/eyes-cypress')(module);
const cucumber = require('cypress-cucumber-preprocessor').default 
module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
}
```

I changed it to below and it worked.

```
const cucumber = require('cypress-cucumber-preprocessor').default
module.exports = (on, config) => {
 on('file:preprocessor', cucumber())
}

require('@applitools/eyes-cypress')(module);

````
