### ISSUE TITLE
Show better error message when permissions are not properly set for Cache folder in Cypress

### ISSUE THREAD

**Issue by amitk7407** [cypress-io/cypress#7640]
Running cypress on windows in throwing this error everytime.

```
C:\Users\amikumar70>cypress open
It looks like this is your first time using Cypress: 4.8.0

  ×  Verifying Cypress can run C:\Users\amikumar70\AppData\Local\Cypress\Cache\4.8.0\Cypress
    → Cypress Version: 4.8.0
Cypress failed to start.`

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

spawn EPERM

----------

Platform: win32 (10.0.18362)
Cypress Version: 4.8.0
```

Detailed log can be viewed in the attached screenshot :
![cypress error](https://user-images.githubusercontent.com/20415001/84177226-32ae6280-aaa0-11ea-9330-16765b409389.PNG)

**Comment by jennifer-shehane** [comment]
EPERM is a permissions error. Opening Cypress will require write permissions, you'll need to verify the correct permissions are set.

A similar situation where fixing permissions to `C:\Users\Username\AppData\Local\Cypress\Cache\4.8.0\Cypress` fixed the issue. https://github.com/cypress-io/cypress/issues/7616#issuecomment-641114490

**Comment by jennifer-shehane** [comment]
Reopening to maybe show a better error message when this happens.

**Comment by amitk7407** [comment]
I have the write permission to `C:\Users\Username\AppData\Local\Cypress\Cache\4.8.0\Cypress` and I also tried setting `CYPRESS_CACHE_FOLDER` to `C:\Cypress`  but everytime I install, it writes in `C:\Users\Username\AppData\Local\Cypress\Cache\4.8.0\Cypress`. I'm still getting the same error

**Comment by seongwon-kang** [comment]
A errror message already present: https://github.com/cypress-io/cypress/blob/c12347dc9c4f9dc0662ad9350536c6c6b99225c4/cli/lib/errors.js#L177

**Comment by seongwon-kang** [comment]
Let me work on this.

**Comment by bahmutov** [comment]
I have looked at the code and I do not understand where it throws the error. Is it inside the CLI (NPM) module or from the Cypress? From the stack trace it seems that this is throwing from Cypress when running a child process, thus not the CLI problem (that was worked on in the pull request).

Could you:

- provide debug logs by running `DEBUG=cypress:cli npx cypress verify`
- try the latest version of Cypress 6.4.0
