### ISSUE TITLE
Using Bamboo and create a Build

### ISSUE THREAD

**Issue by Elif5757** [cypress-io/cypress#7648]
### Current behavior:

I need also help.
I have deposited in my script :
```
"cy:run": "cypress run", 
"cy:test": "start-server-and-test start http://localhost:4300 cy:run"
```

After that I've added a task in bamboo to run my cypress tests - using the command "run cy:test"

That's working but is there a possibility to say bamboo if a test failed then the build break up and suchlike that ?

What options do I have to act with failed test or generally in bamboo ?

**Comment by jennifer-shehane** [comment]
When running `cypress run`, Cypress will run the entire test suite until is it finished, then issue an exit code that Bamboo will see to exit the process. 

There is no way to exit early on a single Cypress test failure. There's a request for this feature here: https://github.com/cypress-io/cypress/issues/518

I would refer to Bamboo's docs for anything else about how Bamboo acts: https://confluence.atlassian.com/bamboo

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by humayunrana786** [comment]
What is the test runner in Bamboo for Cypress. How can I run this in bamboo.
I use this command to run ....   npx cypress run --spec "cypress/integration/posui.spec.js"
