### ISSUE TITLE
Test if element does not exist at first render

### ISSUE THREAD

**Issue by eric-burel** [cypress-io/cypress#7651]
## Current behavior: 

I want to test correct SSR behaviour, meaning that the app should not be in "loading" state:

```js
cy.contains("loading").should("not.exists")
```

2 possibilities:

- "loading" exists. Then, the should is retried for a few seconds. The test fails as expected, but is very time consuming. It can be bypassed by a `timeout` on the contains, but that's clearly not intuitive.
- "loading" does not exist. The test still fails because "contains" fails. NOTE: this seems to be an erratic behaviour. I encountered this issue in 4.7 and it somehow disappeared when I tried to repro : ... :alien:

Note:

- the relevant [StackOverflow question](https://stackoverflow.com/questions/48915773/cypress-test-if-element-does-not-exist) accepted answer is not clear, it targets removed elements.
- the relevant official doc, is also targeted at removed element.
In some situation we might want a clear doc

Here, I specifically mean an element that never existed in the first place.

### Desired behavior:

We should have an easy way to test non-existent element.

### Test code to reproduce
```js
  it("fails but very slowly  because of retries", () => {
    cy.visit("https://example.cypress.io");
    cy.contains("Kitchen Sink").should("not.exist");
  });
  it("fails faster (but not intuitive...)", () => {
    cy.visit("https://example.cypress.io");
    cy.contains("Kitchen Sink", { timeout: 10 }).should("not.exist");
  });
  /*
  I had this issue at some point, but can't repro anymore. Seems to happen eratically
 */
  it("fails on 'contains', while it should pass", () => {
    cy.visit("https://example.cypress.io");
    cy.contains("I do not exist").should("not.exist");
  });
```

### Versions

4.7
Ubuntu

**Comment by jennifer-shehane** [comment]
>"loading" exists. Then, the should is retried for a few seconds. The test fails as expected, but is very time consuming. It can be bypassed by a timeout on the contains, but that's clearly not intuitive.

The timeout option is the correct way to decrease the wait time for an elements existence/non-existence if you are sure at that point there is no need to waiting for the element to 'not exist'. 

The equivalent of a 'never exist' would be setting `timeout: 0` to turn off Cypress' retry mechanism. I think it's unlikely we would add support for a 'never.exists' chainer.

>"loading" does not exist. The test still fails because "contains" fails. NOTE: this seems to be an erratic behaviour. I encountered this issue in 4.7 and it somehow disappeared when I tried to repro : ... 👽

We'll need a reproducible example of this in order to look into it. 

---

You may be running into a situation described in https://github.com/cypress-io/cypress/issues/205 where there can be some false positives. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by eric-burel** [comment]
Thank for your explanations! I've added a PR in the doc to clarify the patterns to test existence. I was not sure that `timeout:0` would be safe.

**Comment by lukemovement** [comment]
Cypress 5.6.0
NPM 6.14.8
Node - 14.15.0

I'm getting the same issue, I am checking for a notification (buefy snackbar). The notification disappears before should('not.exist') times out. It is also not available when setting the timeout to 0. Maybe because of the MVVM architecture of Vue, the lagging on my PC or a delay in the snackbar showing due to a 'fade' implementation.
   
  ```
    it("Enter details", async () => {
      cy.visit("#/login");
      cy.get("input#username").type("demo_user");
      cy.get("input#password").type("P@55w0rd");
      cy.get("button.login").click();
    });

    it("Has no error notification", () => {
      cy.get(".snackbar.is-danger").should("not.exist");
    });
```

In another bit of my code, I use the code below to detect an expected notification error. The below results in success as soon as the notification exists.
```
    it("Has error notification", () => {
      cy.get(".snackbar.is-danger").should("exist");
    });
```

Both of these conditions are successful even though an error notification is available both times. (I'm current;y not working with a backend so error notifications are shown in both instances).

Do I need to make the notification last longer than the cypress's timeout or has anyone found a work around yet?

**Comment by lukemovement** [comment]
Workaround for this bug if anyone is still looking.

```
    it("Has no error notification", () => {
      cy.get(".snackbar.is-danger").should((notificaiton) => {
        expect(notificaiton, "Error notification has been found").eq(null);
        return true;
      });
    });
```

**Comment by lukemovement** [comment]
```    
    it("Has no error notification", () => {
      cy.get("button.login").click();
      cy.get(".snackbar.is-danger", {
        timeout: 0,
      }).should("not.exist");
    });
```
Will error as expected

```
    it("Enter details", () => {
      cy.get("input#username").type("demo_user");
      cy.get("input#password").type("P@55w0rd");
      cy.get("button.login").click();
    });
    
    it("Has no error notification", () => {
      cy.get(".snackbar.is-danger", {
        timeout: 0,
      }).should("not.exist");
    });
```
Will pass which is not expected. 
Where is the source code so I can debug and PR?

**Comment by abidshah-TP** [comment]
cy.contains("loading").should("not.exists") i dont want to retry any suggestions

**Comment by zwingliernst** [comment]
We ended up doing something like:
```
const checkForNeverBePresent = function (locator, maxTimeout = 2000){
  // select a parent element, that is for sure present.
  cy.get('body', {log: false}).then(($body) => {

    // then check with jQuery, that the undesired child element doesn't exists in DOM
    if($body.find().length > 0) {
      console.error("BAD")
    }
    
    // recursive Call for timeout-check
    maxTimeout -= 100
    checkForNeverBePresent (locator, maxTimeout)
  });
}

const element = '.snackbar.is-danger'
checkForNeverBePresent(element, 5000)
```

It's an annoying workaround, but it does the job.

**Comment by trainoasis** [comment]
> cy.contains("loading").should("not.exists") i dont want to retry any suggestions

maybe 

`cy.contains("loading", {timeout: 0}).should("not.exists") ` ?

**Comment by zwingliernst** [comment]
> > // then check with jQuery, that the undesired child element doesn't exists in DOM
> > if($body.find().length > 0) {
> > console.error("BAD")
> > } else {
> 
> this looks wrong, you probably meant
> 
> ```
> if($body.find(locator).length > 0) { 
> ```
> 
> ?
> 
> Otherwise I'm joining the +1 here, wanna check for element not existing, at all and only find flaky/weird solutions.

Thank you for the hint. Yes, indeed. I fixed it in my post.

**Comment by papb** [comment]
> We ended up doing something like:
> 
> ```
> const checkForNeverBePresent = function (locator, maxTimeout = 2000){
>   // select a parent element, that is for sure present.
>   cy.get('body', {log: false}).then(($body) => {
> 
>     // then check with jQuery, that the undesired child element doesn't exists in DOM
>     if($body.find('locator-string').length > 0) {
>       console.error("BAD")
>     } else {
>     
>       // recursive Call for timeout-check
>       maxTimeout -= 100
>       checkForNeverBePresent (locator, maxTimeout)
>     }
>   });
> }
> 
> const element = '.snackbar.is-danger'
> checkForNeverBePresent(element, 5000)
> ```
> 
> It's an annoying workaround, but it does the job.

Are you sure your timeout is working here? I don't see any waits, it seems you're recursing immediately so all your 50 calls (`5000/100`) happen synchronously.
