### ISSUE TITLE
Can not set reporterOptions from inside plugins

### ISSUE THREAD

**Issue by nitzanashi** [cypress-io/cypress#7652]
### Current behavior:
setting `reporterOptions` inside `plugins/index.js` does nothing.
also, `reporterOptions` is not part of `ConfigOptions` interface :/

### Desired behavior:
setting `reporterOptions` inside `plugins/index.js` returns the settings as described.

### Test code to reproduce
```js
// plugins/index.js

module.exports = (on, config) => {
    return {
        ...config,
        reporterOptions: {
            test: true,
        },
    };
}
```

### Versions
tested on 4.5.0

**Comment by jennifer-shehane** [comment]
This may be a case where the `reporterOptions` on non-mutable at this point like in https://github.com/cypress-io/cypress/issues/6407, but I'm unaware of this situation. 

I can see that the config is changed within the plugins, but not shown in the resolved Configuration - but `console.log(Cypress.config('reporterOptions'))` resolves with the correct value. 

Are the new values passed to reporterOptions not taking effect at all?

**Comment by albertmir** [comment]
Just to bring more information.
I saw that setting `reporterOptions` value as a string resolves correctly in configuration. It is just when setting an object inside of it.

```js
// plugins/index.js

module.exports = (on, config) => {
    return {
        ...config,
        reporterOptions: "This is just a test",
    };
}
```

Settings tab:
![image](https://user-images.githubusercontent.com/61497067/90006883-0bd7fc80-dc9a-11ea-9e0a-c3309679e32f.png)

Can it be a little related to this previous issue https://github.com/cypress-io/cypress/issues/7959?

**Comment by quad5** [comment]
This is still happening in 5.5.0. 

`console.log(Cypress.config('reporterOptions'))` returns `null`

**Comment by quad5** [comment]
This seems to be working fine in 5.5.0.

**Comment by sainthkh** [comment]
@quad5 When `reporterOptions` is a string, it shows the value correctly, but when it's an object, it simply shows a null.

**Comment by ilbmiller** [comment]
It is still an issue in cypress 7.2.0.  Frustrating as we have own config file 'extends' enhancement that relies on plugins processing of config files, and thus can't 'inherit' a reporterOptions object from an ancestor configFile.
