### ISSUE TITLE
Wrong config types in type declaration files

### ISSUE THREAD

**Issue by jereaameli** [cypress-io/cypress#7654]
### Current behavior:

When running Cypress through a script made in TypeScript, there are conflicts with the current Type Definitions with the actual configs supported.

There are some configs that accept both strings (path to a file / folder) or `false` to disable that options. The properties I have found that meet this criteria are `fixturesFolder`, `supportFile` and `pluginsFile`, but there could be more.

The type declarations for this config properties accept only `string`s as values, as seen [here](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L2367).

Screenshot of error thrown in VSCode:
![image](https://user-images.githubusercontent.com/46169131/84272612-09bfb900-ab04-11ea-872f-e96f71e25ad3.png)

### Desired behavior:

`false` should be a valid value for this mentioned configs.

Example of correct type declaration:

```ts
pluginsFile: string | false
```

### Test code to reproduce

```ts
// cypressScript.ts
import { run } from 'cypress';

const runConfig = {
  config: {
    pluginsFile: false,
  }
}

run(runConfig);
```

```bash
npx tsc cypressScript.ts
```

### Versions

Cypress 4.8.0
OS: macOS Catalina 10.15.3

**Comment by jennifer-shehane** [comment]
Opened a PR to fix this here: https://github.com/cypress-io/cypress/pull/7674
