### ISSUE TITLE
Implement backend events for stubbing/spying WebSockets

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#7655]
Build out backend events to support stubbing/spying WebSockets for #199

- [ ] Add support to `add:route` for matching on WebSockets
- [ ] Match incoming websocket connections against registered net-stubbing routes
- [ ] Add events to communicate WebSocket info between driver and server and to support interception of frames/connects/disconnects. Draft spec:

eventName | from | to | payload | description
--- | --- | --- | --- | ---
`ws:connect` | server | driver | `CyIncomingRequest, CyWebSocket` | fired when a new WS connection is received
`ws:connect:continue` | driver | server | `CyIncomingRequest` | fired when driver wishes to pass the connection on to destination
`ws:disconnect` | server | driver | `CyWebSocket` | fired when a WS disconnects
`ws:frame:outgoing` | server | driver | `CyWebSocket, CyWebSocketMessage` | fired when browser sends a ws frame
`ws:frame:outgoing:continue` | driver | server | `CyWebSocketMessage` | continue passing frame to upstream
`ws:frame:incoming` | server | driver | `CyWebSocket, CyWebSocketMessage` | fired when upstream server sends a ws frame
`ws:frame:incoming:continue` | driver | server | `CyWebSocketMessage` | continue passing frame to browser

Depends on #687

**Comment by unlikelyzero** [comment]
This would be a game-changer for test automation. I can't wait for this to land! Let me know if you'd like me to test a preview PR!

**Comment by deepanshuverma** [comment]
any update on this one guys, when can we expect this ?

**Comment by Andarist** [comment]
this feature would be awesome, bump for a stale bot

**Comment by suppadeliux** [comment]
Would be awesome to support this!

**Comment by jove4015** [comment]
Would be so great to have this!  We are waiting on data from a websocket to refresh and right now we have to go through hurdles to update hidden dom elements on the page so that we can notify cypress that the data is done loading.... it's beyond kludgy.  Having a "cy.intercept" that works with websocket messages would be so helpful.

**Comment by jennifer-shehane** [comment]
Going to close this and fold this into this request: https://github.com/cypress-io/cypress/issues/2492
