### ISSUE TITLE
Show req/res diffs in consoleProps when using cy.intercept

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#7662]
### Current behavior:
There is not an easy way to tell what types of transformations were applied to a request or response in `cy.route2` after the fact.

### Desired behavior:
Improve logging to show the original request/response objects, as well as their diffs to the request/response objects that were actually used.

This may rely on the under-the-hood work to keep track of taintedness in #7657 

Depends on #687

**Comment by jennifer-shehane** [comment]
Closing since this is not currently prioritized.
