### ISSUE TITLE
Update types to allow 'any.key' chai chainer

### ISSUE THREAD

**Issue by thisissami** [cypress-io/cypress#7665]
### Current behavior:

```typescript
expect({ v1: 1, v2: 2}).to.have.key('v1'); // this does not pass
```

### Desired behavior:

The above will pass (exactly as per your defined API). 

### Test code to reproduce

https://github.com/thisissami/cypress-test-tiny/tree/expectBug

^please note you need to be in the `expectBug` branch, as there is a different bug I filed in the `master` branch in Feb that has yet to be addressed.

### Versions

Linux (essentially Ubuntu 18.04) running Cypress 4.0.2 for the test project. Also fails with Cypress 4.3.0 in our production environment.

**Comment by jennifer-shehane** [comment]
This comes directly from Chai with no changes in Cypress, so please refer to their documentation on using the `key` or any other assertions. https://www.chaijs.com/api/bdd/#method_keys

By default, `key` asserts that **all** keys are present, to check for only one keys presence, you can chain the `any` assertion chainer. 

```js
it('test', () => {
  expect({ v1: 1, v2: 2 }).to.have.any.key('v1')
})
```

That being said, the example in the docs is inaccurate, so I'll update that. https://on.cypress.io/assertions#BDD-Assertions

**Comment by thisissami** [comment]
Ah understood. Yes, I was going based off your docs. Thanks for the info @jennifer-shehane! :)

**Comment by thisissami** [comment]
Hi @jennifer-shehane - the example you gave above causes typescript to complain. the `.any` only accepts `.keys` or `.members` after it. Would it be possible for your team to make an adjustment so that `.key` is accepted to? I think it reads much better semantically.
