### ISSUE TITLE
Page Load takes a long time time to finish when "experimentalSourceRewriting" is set to true.

### ISSUE THREAD

**Issue by axleross09** [cypress-io/cypress#7669]
### Current behavior:

Whenever I set "experimentalSourceRewriting" to true in my Env Config, Page Load keeps on loading after signing in to the page even though in the Browser window, The page has loaded completely. 

![image](https://user-images.githubusercontent.com/65379921/84338768-89668a00-abcf-11ea-918b-a1e394a1604e.png)

This will eventually time out and will stop the testing and will not proceed the next steps of the testing.

### Desired behavior:

Page Load will complete and proceed to the other steps.

### Test code to reproduce
```js
it('Add Valid Company Details with Required Fields only', () => {
  var Companyname = chance.company()
  cy.log(Companyname)

  Cypress.on('window:before:load', (win) => {
    Object.defineProperty(win, 'self', {
      get: () => {
        return window.top
      }
    })
  })

  cy.login()
  cy.wait(5000)
  cy.visit('/admin/insites/#/crm/add-company', { timeout: 60000 })
  cy.reload()
  cy.log(Companyname)
  cy.get('.large-4:nth-child(2) > .hydrated > .ins-input-wrap > .ins-sw-in > .input-wrap > .ins-form-field').type(Companyname)
  cy.get('.ins-button-options-wrap > .button-wrap > .ins-button > div > .btn__label').click()
})
```

Please note that I am using Chance.js to generate Strings and created a Custom Command for the whole login process.

### Versions

Cypress 4.8, Mac OS Catalina, Chrome Version 83.0.4103.61

**Comment by learnuser** [comment]
Good evening - Just wanted to check if this defect is on your road map anytime in near future?
Thanks for all your work and making cypress awesome!

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/7565
