### ISSUE TITLE
Cypress Request failing

### ISSUE THREAD

**Issue by AbreezaSaleem** [cypress-io/cypress#7675]
I am trying to make a request on Cypress but it gives me

```
We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:80
```

```
Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
```

Here is my configuration:

```js
appDomain = "some.domain";
 cy.server(
     "Set-Cookie": sessionCookie.value
 });
 cy.request({
    method: "GET",
    url: (`${appDomain}/sites/${siteId}/users.json`),
    headers: {
        "Content-Type": "application/json",   
        "Set-Cookie": sessionCookie.value
    }
 }).as("getUsers");
cy.get('@getUsers').should((response) => {
    console.log('response', response)
})
```

**Comment by jennifer-shehane** [comment]
Can you access the domain normally, via curl within your environment? What is the result of running `curl yourdomain.com`? Can you access the domain via a normal [Node http.request](https://nodejs.dev/making-http-requests-with-nodejs) within the environment? Knowing the results of these will help narrow down if this is a network issue inside or outside of Cypress.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
