### ISSUE TITLE
Cypress hangs when calling .click() on a web component

### ISSUE THREAD

**Issue by elylucas** [cypress-io/cypress#7679]
### Current behavior:

This appears to be a regression in 4.8. In 4.7 this functions as expected.

When targeting an Ionic web component like so:

```js
cy.contains('ion-button', 'My Button').click()
```

The call to the click freezes the Cypress test runner. This appears to happen in Chrome 83, but seems to run fine in Firefox 75.

### Desired behavior:

The click event should be fired on the targeted web component.

### Test code to reproduce

Repo here: https://github.com/elylucas/ionic-react-cypress-4.8-hang

1) `npm i`
2) `npm run start` (to start the Ionic React app)
2) `npx cypress open`
3) Run `mytest.spec.js` against chrome
4) The first test freezes the runner
5) Skip the first test and see that the second test targeting a plain button runs fine
6) Downgrade to Cypress@4.7.0 and see that both tests run fine

Downgrading to 4.7 seems to run fine, even when targeting Chrome 83.

### Versions

MacOS Catalina
Cypress 4.8
Chrome 85
Firefox 75

**Comment by jennifer-shehane** [comment]
@elylucas Thanks for providing a reproducible example!

Ionic uses Shadow DOM, and we did make some changes in 4.8.0 concerning Shadow DOM, albeit - all effects should have been isolated to setting the `experimentalShadowDomSupport` flag to `true`. 

But, my suspicions seem to be true in that some of the changes leaked out and is effecting your app even though you have not turned on the experimental feature. 

**Test passes on commit before Shadow DOM**: https://github.com/cypress-io/cypress/commit/7597bf9463d0655fd613c2a891719259084fb121

<img width="725" alt="Screen Shot 2020-06-12 at 10 29 17 AM" src="https://user-images.githubusercontent.com/1271364/84464380-563cfd00-ac9a-11ea-9105-552e5f6be1a1.png">

**Test fails on Shadow DOM commit**: https://github.com/cypress-io/cypress/commit/a7ff8fddc2e30db8060b3f2c6bbac5793bee3977

<img width="914" alt="Screen Shot 2020-06-12 at 10 48 24 AM" src="https://user-images.githubusercontent.com/1271364/84464389-5ccb7480-ac9a-11ea-9c21-75e3c3539666.png">

**Comment by JessicaSachs** [comment]
@chrisbreiding Can you take a look into this?
