### ISSUE TITLE
Jazz up the Readme

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#768]
The `README.md` for this repo is kind of sad. 😢  I would like to see the readme more focused on explaining what cypress is, why you would use cypress, **simple install instructions**, etc - for our users and have contributing the secondary focus. 

**Ideas to jazz up**
- Add header from old readme branch. 
- Embed 'Why Cypress' video directly into readme.
- Have simple 'npm install' instructions. 
- Add some cool badges. (gitter, npm package)
- Don't make it too long - refer to the docs when necessary.

**Comment by brian-mann** [comment]
https://gist.github.com/brian-mann/3a59f950e51b35b126d65a206b513da2

**Comment by bahmutov** [comment]
do not duplicate content between static site and readme.

**Comment by brian-mann** [comment]
@bahmutov yeah we discussed this internally already - we're going to steal the header and the formatting but reference docs as opposed to duplicate.
