### ISSUE TITLE
Assertions should('exist') and should('not.exist') both true on some elements

### ISSUE THREAD

**Issue by stuarth-inova** [cypress-io/cypress#7680]
### Current behavior:

For elements in an ```<aside>``` sidebar, both assertions return ```true```. This prevents me from testing if the sidebar is open and visible, or closed and hidden - or gone.

The sidebar is open; the element in question is present and visible. But for this case both ```should('exist')``` and ```should('not.exist')``` pass!

The ```should('not.exist')``` assertion passes with unexpected text, visible in my screenshot:
```expected null to not exist```

But in the preceding test it found the element ```aside.sidebar```, why would ```get``` resolve the exact same element as ```null``` this time around?

Note I tried this on static elements not in ```aside.sidebar``` - they work just fine. One or the other test always fails, which is what I need.

### Desired behavior:

Assertions ```should('exist')``` and ```should('not.exist')``` should be mutually exclusive; when one is true for a given element, the other should be false. Should work on any and all elements.

### Test code to reproduce
Simple test showing the issue:
```js
describe('Shows inconsistencies with "exist" and "not.exist"', function () {
  it('should fail one of these two tests', function () {
    cy.visit('').get('aside.sidebar').should('exist');
    cy.visit('').get('aside.sidebar').should('not.exist');
  });
});
```
Screenshot of Test Runner showing those tests both passing:
<img width="904" alt="Screen Shot 2020-06-11 at 2 02 54 PM" src="https://user-images.githubusercontent.com/2287831/84423406-66969e80-abec-11ea-8b82-1c34fafa2b6f.png">

### Versions
App is a VUE SPA app, VUE v2.6.6
Cypress 4.8.0, Electron version shipped w/ Cypress 4.8.0 and Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
As a side note, you should never need to chain `.should('exist')` to `.get()` because this is a default assertion of `.get()`. 

My suspicion is that this is happening:

1. The first `.get()` does not initially find the element, so it retries for 4 seconds until the element exists on the page - passes.
2. The second `.get()` looks ahead and sees you want to verify the element does not exist. The element doesn't exist yet so it instantly passes. (It wouldn't retry for 4 seconds)

You could try lowering the `timeout` option to get a more 'instant' response on the existence of the element or not. `cy.get('aside', { timeout: 0 })` - this would not retry at all for example and instantly give the current state of the element.

We'll need a reproducible example in order to investigate more fully if there's something Cypress can do in this situation.

Can you provide a repo or application code + test code to reproduce the issue? Otherwise we'll have to close the issue as there's no path forward to investigate.

**Comment by stuarth-inova** [comment]
Why does it work the way I'd suspect with an element that is not on the sidebar, in the nav bar, for example then? For those elements ```should('not.exist')``` fails. It definitely has something to do with the elements on the <aside.sidebar>. Now, it may be a timing issue, butI don't think it is as simple as you've suggested.

This all came about when I was trying to determine if the sidebar was open or closed. When it closes, for all appearances it is removed from the DOM - at least as far as Dev Tools in Chrome shows. But Cypress was still finding the elements on the sidebar- I was asserting ```should('not.exist')```. The only reason I asserted ```should('exist')``` was to create a simple example showing my problem.

I can't really share our app code, and I don't have time to create a new app to reproduce the issue. Maybe over the weekend. I went to Gitter w/ my issue, and Gleb told me to write it up. So I didn't get help with "how" over there, and now I am not getting help with "why" here, it is a bit disappointing.

**Comment by bahmutov** [comment]
@stuarth-inova from the description we cannot determine what is going on in your application. I would suggest forking https://github.com/cypress-io/cypress-test-tiny and creating an index.html with `<aside>` and a test that shows the problem. I completely understand your frustration, but we have nothing to go on to help you.

In fact, your test is completely valid to pass

```js
describe('Shows inconsistencies with "exist" and "not.exist"', function () {
  it('should fail one of these two tests', function () {
    cy.visit('').get('aside.sidebar').should('exist');
    cy.visit('').get('aside.sidebar').should('not.exist');
  });
});
```

On the first visit the app renders the sidebar after 1000ms. Great, the first assertion retries and passes.

On the second visit the app does not have the sidebar initially, so the assertion "not.exist" passes very quickly.

**Comment by stuarth-inova** [comment]
I see, the fact that elements in the header don't behave this way makes sense too? Anyway, I worked around this issue by making a dynamic ```data-cy``` attribute with the state of the sidebar inside of it, so I am going to close this issue and just use that approach. I hope that's not an anti-pattern of some sort.
