### ISSUE TITLE
Unable to load iframe.contents()

### ISSUE THREAD

**Issue by danteoh** [cypress-io/cypress#7681]
Test Git Repo: 

https://github.com/danteoh/cypress-iframe-test

### Current behavior:

I've gone through #136 several times trying to get some level of iFrame functionality working.  I don't think this should be marked as a dupe of #136 as there's actual functionality reference there that is not working in a base case.

For the life of me, I can't get past the .contents() part of every listed example and workaround.  I tried this on a work computer, then suspicious I had some weird corp policy plugin influencing things, I also tried it on my personal machine and got the same result.

I spun up a basic test to just pull up an iframe within a page and assert that the contents are there.  I'm getting that it's undefined every time.  Chrome Web Security is set to false.

### Desired behavior:

I should be able to see at least the contents()

### Test code to reproduce

git clone git@github.com:danteoh/cypress-iframe-test.git
npm install
npm run start

Notice that you get a simple existence error

### Versions

Mac OS 10.15.5
Cypress 4.8.0

**Comment by jennifer-shehane** [comment]
There error is indicating that it cannot read property `exist` of undefined.

<img width="474" alt="Screen Shot 2020-06-12 at 11 12 00 AM" src="https://user-images.githubusercontent.com/1271364/84465658-98b40900-ac9d-11ea-8e34-62d743b74343.png">

You've written the `.to.exist` chainer inside of the iframe DOM selector - it should be chained off of the `expect` assertion. 

```js
context('iframes', () => {
  it('Tests that you can touch the data in the iframe', () => {
    cy.visit('http://www.teoh.ca/iframe.html');
    cy.get('iframe')
      // .should(iframe => expect(iframe.contents().find('body').to.exist)) fail
      .should(iframe => expect(iframe.contents().find('body')).to.exist) // pass
  });
})
```

**Comment by danteoh** [comment]
@jennifer-shehane sorry, I guess my test here to confirm my suspicions was slightly inaccurate.  I've updated the test page to point to an iFrame on a different domain, which now renders the contents empty.

Thanks for helping out.  This is a cross-domain issue, it seems (we're trying to automate our flows with Plaid).

**Comment by danteoh** [comment]
(This is only happening in Chrome.  We can get past this by using Electron, although we're running into other issues there unrelated to the iFrame)

**Comment by jennifer-shehane** [comment]
We can take a look with a provided example. I don't see the provided repo example having been updated on the `master` branch.

**Comment by danteoh** [comment]
I updated the actual test web page which the test references (since I have
a couple domains to play with)

Dan

**Comment by danteoh** [comment]
@jennifer-shehane are we able to re-open this, or should I close it out and create a new issue that's specific to cross-origin issues in Chrome I'm experiencing?

**Comment by jennifer-shehane** [comment]
@danteoh You mentioned updating the tests, but the provided repo hasn't been edited in 5 days https://github.com/danteoh/cypress-iframe-test. Please provide the exact code to reproduce the issue you're still having.

**Comment by danteoh** [comment]
@jennifer-shehane The tests themselves didn't need to be updated, they can be re-run.  The html page which contains an iframe I'm testing has been modified to reference a source on a different domain (they're teoh.ca and t0media.com) to demonstrate the issue.  https://github.com/danteoh/cypress-iframe-test/blob/master/cypress/integration/iframe_spec.js#L3

**Comment by jennifer-shehane** [comment]
As noted in this comment - https://github.com/cypress-io/cypress/issues/7681#issuecomment-643061282 Your chainer `to.exist` is not chained properly. The test below passes. Please provide the exact test I should run with the fixed `to.exist` chainer that is failing for you. Thanks.

```js
context('iframes', () => {
  it('Tests that you can touch the data in the iframe', () => {
    cy.visit('http://www.teoh.ca/iframe.html');
    cy.get('iframe')
      // do not use the chainer inside the expect
      // .should(iframe => expect(iframe.contents().find('body').to.exist)) <-- will always fail
      .should(iframe => expect(iframe.contents().find('body')).to.exist)
  });
})
```

**Comment by danteoh** [comment]
@jennifer-shehane I've updated this test (pull master please) and it still fails on my machine when using cypress open and using chrome.  As mentioned, it still passes with Electron but not with Chrome...

**Comment by jennifer-shehane** [comment]
I pulled down latest master. The tests pass for me in Chrome Version 83.0.4103.116 using Cypress 4.10.0 during `cypress open` and `cypress run` on MacOS Catalina. 

Can you provide a screenshot or video of what you're seeing on failure?

`spec.js`

```js
context('iframes', () => {
  it('Tests that you can touch the data in the iframe', () => {
    cy.visit('http://www.teoh.ca/iframe.html');
    cy.get('iframe')
      .should(iframe => expect(iframe.contents().find('body')).to.exist)
  });
})
```

`cypress.json`

```json
{
  "chromeWebSecurity": false
}
```

#### Chrome

`cypress open`

<img width="730" alt="Screen Shot 2020-07-09 at 3 54 34 PM" src="https://user-images.githubusercontent.com/1271364/87022607-b91fa680-c1fc-11ea-828f-bfa000156ec4.png">

`cypress run`

<img width="823" alt="Screen Shot 2020-07-09 at 3 57 02 PM" src="https://user-images.githubusercontent.com/1271364/87022686-de141980-c1fc-11ea-8614-d0d2d671f6ce.png">

**Comment by anamake** [comment]
> @jennifer-shehane sorry, I guess my test here to confirm my suspicions was slightly inaccurate. I've updated the test page to point to an iFrame on a different domain, which now renders the contents empty.
> 
> Thanks for helping out. This is a cross-domain issue, it seems (we're trying to automate our flows with Plaid).

@danteoh Where did you end up hosting the Plaid iframe content / JS to get your tests to work? I'm in a similar boat where I'm trying to automate a flow using Plaid.

**Comment by anilpujaraofficial** [comment]
![Screenshot from 2023-06-15 19-03-32](https://github.com/cypress-io/cypress/assets/65593381/fbe1025d-8240-40f9-805d-a02179f75577)

how can implement this text field

**Comment by anilpujaraofficial** [comment]
![Screenshot from 2023-07-14 13-53-45](https://github.com/cypress-io/cypress/assets/65593381/bc3d4583-2d8c-424b-9dfa-0fa11149a41d)

how can implement this text bold,italic,tex underline and test align

**Comment by nagash77** [comment]
@anilpujaraofficial issues int he github repo are reserved for bugs and feature requests.  For help using Cypress check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
