### ISSUE TITLE
Devtools doesn't open in Electron when cypress is launched from console with admin rights

### ISSUE THREAD

**Issue by yugandhar02** [cypress-io/cypress#7688]
### Current behavior:

When I try to run cypress from a console with admin rights and open devtools. It doesn't work.
Nothing happens on click to open devtools

### Desired behavior:

Devtools should work correctly with or without admin rights

### Test code to reproduce

1. Open console with admin rights.
2. Launch cypress with electron selected
3. Try to open devtools

### Versions
Cypress 4.4.1
Electron 80
windows 10 enterprise 1709

**Comment by jennifer-shehane** [comment]
I'm not able to recreate the issue as you're describing in MacOS. 

>When I try to run cypress from a console with admin rights and open devtools. It doesn't work.
Nothing happens on click to open devtools

- How/what are you running with admin rights exactly?
- Can you explain more about what you mean here? Perhaps provide a video/gif of this experience? 
- How are you opening the devtools? There are several ways to open.

**Comment by yugandhar02** [comment]
I am using windows 10 and git bash console
I have recorded a video. Should I send it privately to support@cypress.com ?

**Comment by yugandhar02** [comment]
It could be related to electron bug ?
[https://github.com/electron/electron/issues/20069](url)
