### ISSUE TITLE
Exit Cypress when CPU processes are maxed.

### ISSUE THREAD

**Issue by baronvonbirra** [cypress-io/cypress#7689]
### Current behavior:
After some changes in our app we found out we had a re-render loop that was causing a big malfunction. This was not caught by our tests because our CI pipelines were giving us false positives, and after further investigation we found out that was caused due to Cypress getting stuck because of this re-render loop mentioned. 
You can see a screenshot here:
<img width="1090" alt="2020-06-12_1329" src="https://user-images.githubusercontent.com/18036304/84498861-b55a3c00-acb1-11ea-8091-cc0aeff3c037.png">

As you can see, the 1st scenario was correctly failing because the loading icon is still present in the app, but the big problem comes because the 2nd scenario never starts, and Cypress gets stuck at that point - stuck to the point that you are not able to close the Cypress screen, and just shut it down through the Terminal.

### Desired behavior:
Cypress not getting stuck, or showing a crash message at least, so our CI/CD can catch it and avoid false positives.

### Versions
Checked on Cypress 3.4.1 & 4.8.0.

**Comment by jennifer-shehane** [comment]
Anything that causes the Chrome renderer process to lock up within your application - would do the same when running within Cypress. If you have a loop in your application that will cause the Chrome process to lock up - Cypress can't continue running the tests. 

This is why tracking down 'Cypress locked up' issues is really difficult because any memory leaks or performance issues from the application itself when performing actions from you tests have actually nothing to do with Cypress. 

I'm not totally sure what we could do in this situation. Is the Chrome browser actually ever crashing? Because we should show a message in this situation. If the CPU is just maxing out...we'd have to think about what we could do in this situation.

**Comment by baronvonbirra** [comment]
Hi! Yes, I'm afraid this is the case of one of those memory leaks that makes your CPU max out... Chrome doesn't crash, but Cypress does. I'm not sure if what I'm asking is possible, but would be nice to have some kind of error alert when Cypress crash. 
Thanks!

**Comment by jennifer-shehane** [comment]
Just had a thought on this. There is a way to log CPU usage / memory when running Cypress as detailed here: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage

**Comment by baronvonbirra** [comment]
I took a look to the doc there, and this is what I got:
```
cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler 
┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │    'Electron'     │      1       │    '31673'     │   136.1    │     86.15      │  754.95  │    633.19    │   976.71    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │    '31161'     │   113.3    │     78.03      │  265.73  │    273.34    │   344.85    │
  cypress:server:util:process_profiler │    2    │ 'electron-shared' │      2       │ '31164, 31167' │    60.8    │     46.83      │  200.63  │    175.59    │   200.63    │
  cypress:server:util:process_profiler │    3    │     'plugin'      │      1       │    '31193'     │     0      │      7.53      │  164.86  │    165.75    │    235.8    │
  cypress:server:util:process_profiler │    4    │     'ffmpeg'      │      1       │    '31672'     │    14.6    │     32.55      │  91.99   │    85.87     │   278.09    │
  cypress:server:util:process_profiler │    5    │      'other'      │      2       │ '31748, 31749' │     0      │      9.54      │   4.61   │     9.8      │   102.28    │
  cypress:server:util:process_profiler │    6    │      'TOTAL'      │      8       │      '-'       │   324.8    │     252.78     │ 1482.77  │   1292.21    │   1667.03   │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
```

This one was taken just when the test reach the problematic re-render loop. Is it possible to configure Cypress to exit with a failure before it reaches this Cpu usage percentages? 
Thanks!

**Comment by jennifer-shehane** [comment]
@baronvonbirra There is not a built in way to do this, so I'm not sure if this is possible.
