### ISSUE TITLE
Ignore error

### ISSUE THREAD

**Issue by tasuli** [cypress-io/cypress#7690]
I got "Error: Interrupting page load to complete the redirect." error message when I try to execute login test case on my application.

This is normal behavior of the application, so I don't want to threat it as an error.

```js
Cypress.on('uncaught:exception', (error, runnable) => {
  return false
})
```

I guess this isn't an uncaught exception.
Are there any way to ignore a specific error?

**Comment by jennifer-shehane** [comment]
This handler is hit when there is an uncaught exception from within your application. So this wouldn't be hit with cross origin errors from other applications or errors thrown from Cypress. 

We'd need a reproducible example to even tell what and where the error is being thrown that you're mentioning, so I can't really give any guidance on how to ignore the error without that.
