### ISSUE TITLE
Run multiple same test at same times

### ISSUE THREAD

**Issue by ardiwirawan11** [cypress-io/cypress#7694]
### Current behavior:
I need to run some test multiple times in same time, is it possible?
Now i only can run 1 test at time, and if i want to run same test in same time i use paralelize to run it but need to make many same test files.

### Desired behavior:
Make 1 test then run multiple times at once

**Comment by jennifer-shehane** [comment]
No, this isn't currently possible except to parallelize like you've already mentioned. 

Could you explain the use case for this? We'd like to understand the reasons why someone might need the feature so we can evaluate how valuable it'd be to implement. Thanks!

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
