### ISSUE TITLE
CypressError: `cy.request()` failed trying to load

### ISSUE THREAD

**Issue by WinstonN** [cypress-io/cypress#7696]
I'm testing an API json response
My code looks like 
```
describe('retrieve information for product', () => {
    // asserts
    it('with sku', () => {
      cy.request('GET', `${url}/product/list?skus=WJ12`)
        .then((response) => {
          // response.body is automatically serialised into JSON
          console.log(response)
      })
    })
  })
```
The API url is `http://localhost:8080/api/product/list?skus=WJ12`

Within the GUI of Cypress it works, as can be seen below
![image](https://user-images.githubusercontent.com/1143789/84582165-a5bb2e80-ae3c-11ea-9048-eb6a243087e9.png)

When running the same code in the CLI it fails with
```
  test the product api
    ✓ loads the product api (48ms)
    retrieve information for product
      1) with sku


  1 passing (940ms)
  1 failing

  1) test the product api
       retrieve information for product
         with sku:
     CypressError: `cy.request()` failed trying to load:

http://localhost:8080/api/product/list?skus=WJ12

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:8080
```

I have tested this in 
Cypress 4.7.0
Cypress 4.8.0

Can you see if I am doing anything wrong here?

**Comment by WinstonN** [comment]
I found the issue. I'm running cypress cli in a docker, and this docker instance, does not recognise the location of the API
Running it locally works, as expected

```
  test the product api
    ✓ loads the product api
    retrieve information for product
      ✓ with sku (1663ms)


  2 passing (2s)
```
Closing this issue

**Comment by EliasSalom** [comment]
> I found the issue. I'm running cypress cli in a docker, and this docker instance, does not recognise the location of the API Running it locally works, as expected
> 
> ```
>   test the product api
>     ✓ loads the product api
>     retrieve information for product
>       ✓ with sku (1663ms)
> 
> 
>   2 passing (2s)
> ```
> 
> Closing this issue

how do you fix this issue? because I have the same one when I try to test on the GitHub action 

![image](https://github.com/cypress-io/cypress/assets/39850311/af4b1bee-a544-4390-9b95-9287b82639dd)

**Comment by Duccem** [comment]
> > I found the issue. I'm running cypress cli in a docker, and this docker instance, does not recognise the location of the API Running it locally works, as expected
> > ```
> >   test the product api
> >     ✓ loads the product api
> >     retrieve information for product
> >       ✓ with sku (1663ms)
> > 
> > 
> >   2 passing (2s)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Closing this issue
> 
> how do you fix this issue? because I have the same one when I try to test on the GitHub action
> 
> ![image](https://private-user-images.githubusercontent.com/39850311/259726589-af4b1bee-a544-4390-9b95-9287b82639dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNjcyMzAsIm5iZiI6MTcxNDE2NjkzMCwicGF0aCI6Ii8zOTg1MDMxMS8yNTk3MjY1ODktYWY0YjFiZWUtYTU0NC00MzkwLTliOTUtOTI4N2I4MjYzOWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDIxMjg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NDdlZGRiNzIzYWU3ZjQyZGQwZTJhMGQ3MTA0M2E2OTU0YWI2ODJjZGQxOThkY2YyYmZiZmEyNmYwYTk5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oRzdlcaR-UgWXTtM5zs1AF8pxHa6O-6eMGr5k3414mw)

You found a solution? i have the same issue

**Comment by peterMaxab** [comment]
is there any solution for this bug, i am facing the same error while using cypress-keyclock
