### ISSUE TITLE
react input type email clears, not firing event

### ISSUE THREAD

**Issue by spearmootz** [cypress-io/cypress#770]
- Operating System:
- Cypress Version:
- Browser Version:

### Is this a Feature or Bug?
Bug

### Current behavior:
Cypress not emitting event on valid or invalid email on input type email, so when you go handle user action, you dont have the values in state

### Desired behavior:
events are triggered for input type email

#### Test code:

```js

```

**Comment by jennifer-shehane** [comment]
What event are you specifically listening to? Are you talking about the [`invalid` event](https://developer.mozilla.org/en-US/docs/Web/Events/invalid)? 

Could you possibly paste some sample test code/html of what you are doing/testing?

**Comment by spearmootz** [comment]
At this time I can't. I'll try tomorrow. I'm talking about the onChange
event.

**Comment by jennifer-shehane** [comment]
What version of Cypress are you using? We just did some fixes for `onChange` events in version `1.0.2`. https://github.com/cypress-io/cypress/issues/647

**Comment by spearmootz** [comment]
1.0.2
Mac OS, latest

**Comment by brian-mann** [comment]
@chrisbreiding can you investigate this. There are already react v16 e2e tests in the driver code

**Comment by Fjoggs** [comment]
I'm not sure if it's related, but I have issues with React 16 + cy.type only with Electron. Chrome works as expected. I made a comment on the closed issue:
https://github.com/cypress-io/cypress/issues/647

Maybe spearmootz is using Electron too?

**Comment by spearmootz** [comment]
no im using web. im actually going to close this issue because i made a small sample test using codepen and cypress and the tests passed. so there might be something going on behind the hood of my code that im not identifying as an issue.

**Comment by Fjoggs** [comment]
What do you mean by web? Chrome? You can specify if you want to use Chrome or Electron when you run your tests.

**Comment by chodorowicz** [comment]
Same problem here still. Working good in Chrome, but not in `headless` Electron.

**Comment by brian-mann** [comment]
Fixed in [`1.0.3`](https://docs.cypress.io/guides/references/changelog.html#1-0-3).

**Comment by chodorowicz** [comment]
Thanks 🙇
