### ISSUE TITLE
cypress-file-upload not working

### ISSUE THREAD

**Issue by jyteshpunjwani10p** [cypress-io/cypress#7708]
cypress-file-upload plugin was working fine but has stopped working since last week.

Here is the upload command i am using 

`        cy.fixture(fileName, 'binary')
            .then(Cypress.Blob.binaryStringToBlob)
            .then(fileContent => {
                cy.get('.file-upload').upload(
                    { fileContent, fileName, mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', encoding: 'utf8' },
                    { subjectType: 'drag-n-drop', force: true },
                );
            });
    })`

The error i am getting is 

> CypressError: cy.then() timed out after waiting '50000ms'.

Your callback function returned a promise which never resolved.

The callback function was:

function(u){try{var y=(void 0===(F=a)&&(F={}),void 0===(A=j)&&(A={}),Object.assign({},A,F)),g=y.subjectType,h=y.subjectNature,E=y.force,O=y.allowEmpty,P=y.events;return function(e){var t=e.subjectType,o=e.subjectNature,i=e.force,s=e.allowEmpty,a=e.events;if(-1===Object.values(n).indexOf(t))throw new T(f);if(-1===Object.values(r).indexOf(o))throw new T(l);if("boolean"!=typeof i)throw new T(p);if("boolean"!=typeof s)throw new T(d);if(!Array.isArray(a)||!a.every(function(e){return"string"==typeof e}))throw new T(b)}({subjectType:g,subjectNature:h,force:E,allowEmpty:O,events:P}),function(e){var t=e.subject;if(!t||!t[0]||!w[e.subjectType][e.subjectNature](t[0]))throw new T(c)}({subject:e,subjectNature:h,subjectType:g}),function(e,t){(Array.isArray(e)?e:[e]).forEach(function(e){var n=e.fileContent;if(!(t?!n:n)||!e.fileName||!e.mimeType)throw new T(v)})}(t,O),Promise.resolve(function(e){var t=e.validator,n=e.constructor;return Cypress.Promise.all(e.files.map(function(e){var r=e.fileContent,s=e.fileName,a=e.mimeType,u=e.encoding;void 0===u&&(u=function(e){var t={};return t[o.JSON]=i.UTF8,t[o.JS]=i.UTF8,t[o.COFFEE]=i.UTF8,t[o.HTML]=i.UTF8,t[o.TXT]=i.UTF8,t[o.CSV]=i.UTF8,t[o.PNG]=i.BASE64,t[o.JPG]=i.BASE64,t[o.JPEG]=i.BASE64,t[o.GIF]=i.BASE64,t[o.TIF]=i.BASE64,t[o.TIFF]=i.BASE64,t[o.ZIP]=i.BASE64,t[o.PDF]=i.UTF8,t[o.VCF]=i.UTF8,t[e.slice(e.lastIndexOf(".")+1)]}(s));try{return t({fileContent:r,fileName:s,mimeType:a,encoding:u}),Promise.resolve(function(e){var t=e.fileContent,n=e.mimeType,r=e.encoding,o={};return o[i.ASCII]=function(){return Promise.resolve(t)},o[i.UTF8]=function(){return Promise.resolve(t)},o[i.UTF_8]=function(){return Promise.resolve(t)},o[i.BASE64]=function(){return Cypress.Blob.base64StringToBlob(t,n)},o.default=function(){return Cypress.Blob.base64StringToBlob(t,n)},(o[r]||o.default)()}({fileContent:r,mimeType:a,encoding:u})).then(function(e){return n([e],s,{type:a})})}catch(e){return Promise.reject(e)}}))}({files:Array.isArray(t)?t:[t],validator:function(e){return function(e){if(!e||-1===Object.values(i).indexOf(e))throw new T(m)}(e.encoding)},constructor:function(){for(var e=[],t=arguments.length;t--;)e[t]=arguments[t];return new(Function.prototype.bind.apply(u.File,[null].concat(e)))}})).then(function(t){var n;Cypress.log({name:"upload",displayName:"UPLOAD",message:t.map(function(e){return e.name}).join(", "),consoleProps:function(){return{subjectType:g,subjectNature:h,files:t,force:E,allowEmpty:O,events:P}}}),(0,s[(n={subjectType:g,subjectNature:h}).subjectType][n.subjectNature])({window:u,subject:e,force:E,events:P},{files:t})})}catch(e){return Promise.reject(e)}var F,A}

Cypress version
^4.1.0
cypress-file-upload version
^3.5.3

**Comment by jyteshpunjwani10p** [comment]
I updated the cypress-file-upload version to 4.0.7 and renamed upload function to attachFile. The issue with promise seems to be passed but upload is still not working. It never drags and drops the file. and fails at getting an element which is on a modal, which comes after you upload a file.

**Comment by panzarino** [comment]
Thanks for reporting this issue. However, `cypress-file-upload` is not maintained by the Cypress.io team. Seeing as you have already reported the issue on the correct repo for that plugin, I'm going to go ahead and close this issue.

**Comment by iamdaniyalz** [comment]
Just in case anyone is still facing the similar issue:
Change **upload** to **attachFile** in
`cy.get('.file-upload').upload(`

It should now be:
`cy.get('.file-upload').attachFile(`

**Comment by jyteshpunjwani10p** [comment]
@iamdaniyalz The issue was resolved. Thanks anyway

**Comment by panache-chinmay** [comment]
@jyteshpunjwani10p  I am facing similar issue upload not working , what solution you came up with , my application is in angular , upload functionality is similar to Facebbok..

**Comment by juanan22** [comment]
@panache-chinmay try with trigger: cy.get('input[type="file"]').attachFile(fileName).trigger('input');
