### ISSUE TITLE
Not able to open twitter

### ISSUE THREAD

**Issue by amitguptagwl** [cypress-io/cypress#7719]
### Current behavior:

When I open `https://twitter.com/` with cypress, it gives 503. But it opens with any browser.

![image](https://user-images.githubusercontent.com/7692328/84759176-020c8280-afe4-11ea-8f7e-513957718df0.png)

Though the issue doesn't seem related but continuously happening.

### Test code to reproduce
```js
cy.visit("https://twitter.com/");
```
### Versions
"cypress": "3.4.1"
OS : Ubuntu 18.04

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. This issue does not occur for me in 4.8.0.

**Comment by amitguptagwl** [comment]
Thanks for your quick response. I have tried with 4.8.0 as well;

![twitter](https://user-images.githubusercontent.com/7692328/84878745-df43a200-b0a7-11ea-8c1b-db99648f833e.gif)


```js
const posts = [];
function openpage(url){
    cy.visit("https://twitter.com/", {
        failOnStatusCode : false,
        onLoad: () => {
          // contentWindow is the remote page's window object
        }
      });
}
Given(/^I open twitter url$/, () => {
    openpage("https://twitter.com/");
});
Then(/^I fetch posts link$/, () => {
    cy.get('[aria-labelledby="accessible-list-0"]').find("a[href]").each( a => {
        posts.push(Cypress(a).contains("O2/status").attr("href"));
    })
});

```

**Comment by amitguptagwl** [comment]
@jennifer-shehane As I mentioned in above comment, not able to open twitter with cypress 4.8.0. Have yo get the chance to check it?

**Comment by jennifer-shehane** [comment]
Are you able to open Twitter outside of Cypress? Your VPN/firewall is not blocking the site?

I'm not seeing this behavior with

```js
it('visit the page', () => {
  cy.visit("https://twitter.com/")
})
```

![](http://g.recordit.co/ci1qzMCFTm.gif)

**Comment by amitguptagwl** [comment]
Yes I'm able to open in firefox or chrome directly.
