### ISSUE TITLE
Click on table cell inside a contenteditable element does not behave as expected

### ISSUE THREAD

**Issue by erwinheitzman** [cypress-io/cypress#7721]
### Current behavior:

When clicking a table cell, the table cell is not focused / not the active element so that when I type, the text is not put into the table cell but outside of it.

### Desired behavior:

When clicking a table cell I expect the table cell to be focused and set as the active element so that when I type text, the table cell will be filled with text.

Create this html file:
```html
<!DOCTYPE html>
<html>
<body>
  <div contenteditable="true" style="border: 1px solid black; width: 300px;">
      <table style="border: 1px solid black; width: 300px;">
          <tr style="border: 1px solid black">
            <td style="border: 1px solid black"></td>
            <td style="border: 1px solid black"></td>
            <td style="border: 1px solid black"></td>
          </tr>
          <tr style="border: 1px solid black">
            <td style="border: 1px solid black"></td>
            <td style="border: 1px solid black"></td>
            <td style="border: 1px solid black"></td>
          </tr>
          <tr style="border: 1px solid black">
            <td style="border: 1px solid black"></td>
            <td style="border: 1px solid black"></td>
            <td style="border: 1px solid black"></td>
          </tr>
      </table>
  </div>
</body>
</html>
```

Create testcase:
```js
it('should type inside of the table cell', () => {
      cy.visit('./cypress/integration/example.html');
      cy.get('table tbody tr td').eq(2).click().type('dummy text');
});
```

Run the testcase to reproduce the issue.

### Versions

os: OSX 10.15.4
browser: Chrome 83.0.4103.106
cypress: 4.8.0

**Comment by jennifer-shehane** [comment]
@erwinheitzman Thanks for the reproducible example!

`index.html`

```html
<!DOCTYPE html>
<html>
<body>
  <div contenteditable="true" style="border: 1px solid black; width: 300px;">
    <table style="border: 1px solid black; width: 300px;">
      <tr style="border: 1px solid black">
        <td style="border: 1px solid black"></td>
        <td style="border: 1px solid black"></td>
        <td style="border: 1px solid black"></td>
      </tr>
    </table>
  </div>
</body>
</html>
```

`spec.js`

```js
it('should type inside of the table cell', () => {
  cy.visit('index.html')
  cy.get('td').last()
  .type('dummy text')
})
```

**Current behavior**

<img width="762" alt="Screen Shot 2020-06-17 at 3 58 32 PM" src="https://user-images.githubusercontent.com/1271364/84881134-72360980-b0b3-11ea-9f99-c1d5a415a96a.png">

**What should happen**

<img width="752" alt="Screen Shot 2020-06-17 at 4 01 39 PM" src="https://user-images.githubusercontent.com/1271364/84881452-dfe23580-b0b3-11ea-9789-98d94660434f.png">

**Comment by Bkucera** [comment]
Hi @erwinheitzman, looking into this. 

Since `cy.type(...)` will respect the cursor position if the element is already focused, as a workaround you can focus and move the selection before typing e.g.:

```js
 cy.get('[contenteditable] td:first')
    .then(($el) => {
      const sel = $el[0].ownerDocument.getSelection()

	 // get div[contenteditable] from the td element
      Cypress.dom.getHostContenteditable($el[0]).focus()

	 // select the td element
      sel.selectAllChildren($el[0])
    })
    .type('foobar')
```
Hope this helps
