### ISSUE TITLE
Use cy.wait to deterministically wait on response with specific HTTP status code

### ISSUE THREAD

**Issue by alexagranov7** [cypress-io/cypress#7729]
I'm implementing 'long polling' in my application which means I send an HTTP request, get a `HTTP 202` with token. Then I keep calling the same endpoint with token until I eventually get an `HTTP 200`.

The problem I'm seeing with cypress is I have to anticipate exactly how many HTTP responses I'll get and put in that many `cy.wait` calls. Is there a more elegant way of calling `cy.wait` so that it skips the `HTTP 202` responses and just handles the `HTTP 200` so I can do my assertions?

F.e.,
api request sent -->
<--- HTTP 202 with token
api request sent(with token)-->
<--- HTTP 202
...
api request sent(with token) -->
<--- HTTP 200

I'd like to just have 1 `cy.wait` call for that HTTP 200 response.

**Comment by jennifer-shehane** [comment]
No, there's not a way to specifically only wait for routes that return with a certain HTTP method at this time through Cypress. Maybe this will be available from the work in https://github.com/cypress-io/cypress/pull/4176 ?

**Comment by josephzidell** [comment]
@jennifer-shehane One possible way to solve this and many other use-cases can be for `wait` to accept a callback containing a condition and will retry until the callback/condition returns true.

Example:
```
cy.wait((res): bool => {
  return res.status === 200;
});
```

Syntaxes:
```
cy.wait(conditionCallback)
cy.wait(time, conditionCallback)
```

**Comment by jennifer-shehane** [comment]
I think this is likely possible now with cy.intercept.

**Comment by annatindall** [comment]
@jennifer-shehane, do you have an idea of how this could be done with cy.intercept?

I have a similar problem and tried dynamically setting req.alias inside req.continue, but don't think it's working because the request has already been matched at that point.
