### ISSUE TITLE
Can't visit IIS site with ASP core

### ISSUE THREAD

**Issue by olee** [cypress-io/cypress#773]
- Operating System: Windows
- Cypress package version: 1.0.2
- Cypress binary version: 1.0.2
- Browser: Chrome

If I try to visit a page which is hosted through IIS (Express or on azure as app service) written by using ASP core, I get the following error when trying to access a page:

````
CypressError: cy.visit() failed trying to load:

https://XYZW.azurewebsites.net/about?testing=1

The content-type of the response we received from your web server was:

  > null

This was considered a failure because responses must have content-type: 'text/html'

However, you can likely use cy.request() instead of cy.visit().

cy.request() will automatically get and set cookies and enable you to parse responses.
````

Accessing the url directly without any path appended (eg. `https://XYZW.azurewebsites.net/?testing=1` instead of `https://XYZW.azurewebsites.net/about?testing=1`) works without any problems.

This is nearly the same as #309

**Comment by brian-mann** [comment]
It's possibly Cypress **is** telling you the exact error message. That your server is sending null content-type headers and it requires it to be text/html...

Curl your server and see what it sends. Post a screenshot here if you cannot provide the external URL.

**Comment by olee** [comment]
![unbenannt](https://user-images.githubusercontent.com/6547794/31929048-a3d0f7c0-b89a-11e7-808c-c8f3f3361f30.PNG)

**Comment by olee** [comment]
Anything new for this issue?

**Comment by jennifer-shehane** [comment]
Cypress often takes the route of being more opinionated than other testing tools. Part of what we're trying to do is catch errors in your application that you may not find otherwise. We do not take a strategy of guessing the MIME type as some browsers do. There are many reasons for this that you can read here: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types

That being said, we'd like to confirm that this is not an error on our part, but to do that **you will need to confirm that the `Content-Type` is set from your server and is not in fact, `null`.**

**Comment by olee** [comment]
It seems the content type is actually `null`.
Even then, there should be some kind of setting, to allow that kind of behaviour.

**Comment by jennifer-shehane** [comment]
We're not going to update the behavior to accommodate for `null` MIME types. This would mean we would have to *guess* the MIME type which we're not going to do for a couple of reasons:
1. Guessing the `content-type` no longer gives the server the control to decide what content-type the server wants.
2. Guessing the `content-type` opens Cypress itself up to potential security vulnerabilities. 

We suggest you do not send a `null` MIME type from your server as, according to the HTTP specification, browsers have *no way of knowing* how you intend for them to display and process your content.

**Comment by jennifer-shehane** [comment]
We've changed our implementation some regarding this issue. If the `content-type` is `null` or `undefined`, we now look at the content that was visited and evaluate whether it looks like HTML, if it is - we do not error and continue as if it is `content-type: text/html`.

If it does not look like HTML, then it will still error as shown above in this issue.

The code for this is done in https://github.com/cypress-io/cypress/pull/4321, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
