### ISSUE TITLE
An assertion log will be inserted as a child when outside of a parent command

### ISSUE THREAD

**Issue by panzarino** [cypress-io/cypress#7731]
### Current behavior:

When a `before` or `beforeEach` hooks that end with a `.then` chained to a `cy.visit`, an assertion in the following test, if not wrapped inside a command, will display as a child.

### Desired behavior:

Said assertion should be displayed as a parent, as it does not have a parent.

### Test code to reproduce

```js
before(() => {
  cy.visit(...).then(...)
})

it('expects', () => {
  expect(true).to.be.true
})
```

Notice green dash on left side of assert, indicating that the log is a child:

![Screen Shot 2020-06-17 at 12 51 53 AM](https://user-images.githubusercontent.com/7033952/84856479-d06fd780-b034-11ea-8dd3-6e9b98ea7eb8.png)

**Comment by jennifer-shehane** [comment]
So, you actually have to define the param in the `.then()` for this issue to present itself, which is...really weird. 

**Will not show behavior**

```js
before(() => {
  cy.visit('/index.html').then(() => {}) // no win param
})

context('closing commands', () => {
  it('properly closes commands', function () {
    expect(true).to.be.true
  })
})
```

<img width="450" alt="Screen Shot 2020-06-17 at 3 04 12 PM" src="https://user-images.githubusercontent.com/1271364/84875325-d523a280-b0ab-11ea-93f7-3b828928353e.png">

**Will show behavior (added `win` param)**

```js
before(() => {
  cy.visit('/index.html').then((win) => {}) // win param
})

context('closing commands', () => {
  it('properly closes commands', function () {
    expect(true).to.be.true
  })
})
```

<img width="453" alt="Screen Shot 2020-06-17 at 3 05 27 PM" src="https://user-images.githubusercontent.com/1271364/84875455-01d7ba00-b0ac-11ea-93c0-31c53437b0c3.png">
