### ISSUE TITLE
Cypress script halts with error window.parent.jQuery is not a function

### ISSUE THREAD

**Issue by sarangkh** [cypress-io/cypress#7733]
![image](https://user-images.githubusercontent.com/42429144/84845516-27ef6100-b090-11ea-8d2e-0a1c781b90c5.png)

**Comment by sarangkh** [comment]
![image](https://user-images.githubusercontent.com/42429144/84845872-f034e900-b090-11ea-8bf1-d3d365ba1e3d.png)

**Comment by sarangkh** [comment]
This is not helping here:-

Cypress.on('uncaught:exception', (err, runnable) => {
  return false;
});

**Comment by jennifer-shehane** [comment]
This error is being thrown from your application code (or a 3rd party library you've required). I suggest debugging through the stack trace to see why/where this is thrown.

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
