### ISSUE TITLE
Not able to upload/submit a file to input file element from local machine

### ISSUE THREAD

**Issue by sushilcmd** [cypress-io/cypress#7739]
### Description
Our app takes a file from a user and gives a response based on the input which is provided by the user. Lots of things happen in the system after uploading the file generate some design based on that image.
Now the problem is when I clicked on choose image button with cypress command, not able select any file from the filesystem.
Please help me out.
@jennifer-shehane @brian-mann @Bkucera @chrisbreiding 

Commands which I'm using are given below
```js
  cy.fixture("image.jpg")
    .as('img')
      .get("input[type=file]")
      .then(function (el) {
        return Cypress.Blob.base64StringToBlob(this.img, "image/jpg").then(
          (blob) => {      
            blob.dispatchEvent(new Event("change", { bubbles: true }));
          }
        );
      }); 
```

**Comment by jennifer-shehane** [comment]
File upload is not natively supported in Cypress. I would see #170 for any recommended workarounds. 

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
