### ISSUE TITLE
Page load times out for Chrome and Electron but works from Firefox beta when submitting a simple login form

### ISSUE THREAD

**Issue by shahsar2013** [cypress-io/cypress#7740]
### Current behavior:
Page load times out for Chrome and Electron but works from Firefox beta when submitting a simple login form

Not sure exactly what the root cause is, however, the login form itself is very simple, created with h1, form, and input tags with help of Bootstap and jQuery. I have looked through the GitHub open issues but didn't find anything for this exact issue. Let me know if more info is needed.

Chrome 83:
<img width="1679" alt="Chrome" src="https://user-images.githubusercontent.com/63612004/84900093-a1c72080-b077-11ea-893f-6e9e38da391a.png">

Electron 80:
<img width="1679" alt="Electron" src="https://user-images.githubusercontent.com/63612004/84900117-a986c500-b077-11ea-8d2f-4cecac04bc1f.png">

Firefox 77 beta:
<img width="1679" alt="Firefox" src="https://user-images.githubusercontent.com/63612004/84900127-ad1a4c00-b077-11ea-9f8d-930b70754709.png">

### Desired behavior:
Page should load properly for Chrome and Electron, just like it loads for Firefox beta

### Test code to reproduce
loginURL is: https://qechallenge2-mcg.azurewebsites.net/login
Username: shahsar2013@gmail.com
Password: shahsar2013 (not sure if there is a better way to provide this)
```js
describe('Positive Log In Scenario', () => {
    before(() => {
        cy.visit(data.base.loginURL);
    })

    it.only('I am logged in', () => {
        cy.get('input[type="email"]').type(data.validCred.userName);
        cy.get('input[type="password"]').type(data.validCred.passWord);
        cy.get('form').submit();
    })
})
```

### Versions

Cypress: 4.8.0
MacOS: Catalina 10.15.4
Browsers: Chrome 83, Electron 80, Firefox 77 beta

**Comment by johannesschobel** [comment]
Dear Cypress-Team, dear @shahsar2013 ,
i noticed the same behaviour in my tests today, as i upgraded from `v4.7.0` to `v4.8.0` today. I spent the entire day trying to figure out, what has changed / happened to my tests or my application. At first, i had the upgrade from `@angular` in mind, but it is actually a problem with cypress!

I traced the issue down to **every use of `.get()` or `.find()`** - it has nothing to do with the form or something like that.

Can you guys help me out?!
All the best

**Comment by johannesschobel** [comment]
Btw. to mention additional infos. This error occurs in an `Ionic` application that i am testing. It works as expected, when i **downgrade** to `v4.7.0` though!

**Comment by shahsar2013** [comment]
Page load still timing out for `Cypress v4.7.0` for me. I have uninstalled cypress and reinstalled `Cypress v4.7.0` and rerun the test.

**Comment by johannesschobel** [comment]
The thing that is really weird is that it works in Firefox but fails in chrome. It is as if the browser addresses elements differently

**Comment by kamranayub** [comment]
I may be having a similar issue, an Ionic app. It was working fine with 4.7.0 just now and I upgraded, thinking it would fix another separate issue. Now Chrome will freeze, with the tab using >100 CPU and not responding until I End Task. Definitely a regression I think.

**Comment by jennifer-shehane** [comment]
@johannesschobel @kamranayub Your issues sound related to https://github.com/cypress-io/cypress/issues/7679 - which was a regression introduced in 4.8.0 that will be fixed in our next release. I can't be sure without a reproducible example, but it sounds very similar. These issues seem unrelated to the original issue. 

@shahsar2013 As to the original issue, If you open your Devtools when the test is running, you'll see an error being displayed:

>Mixed Content: The page at 'https://qechallenge2-mcg.azurewebsites.net/__/#/tests/integration/spec.js' was loaded over HTTPS, but requested an insecure form action 'http://qechallenge2-mcg.azurewebsites.net/calculator'. This request has been blocked; the content must be served over HTTPS.

Outside of Cypress this goes to the `http` URL then issues a 301 redirect to the `https` URL.

This is a chrome web security warning and can be bypassed within Cypress by passing `chromeWebSecurity: false` to your `cypress.json` configuration. Your test will pass with this setting.

Although you should probably update the form to route to an `https` url as this is a security vulnerability.

**Comment by johannesschobel** [comment]
Dear @jennifer-shehane , thanks a lot for your response - and the link to the other issue. Do you have an estimated timeframe when you will release a new version? I would be very happy to test a new release ;)

**Comment by jennifer-shehane** [comment]
@johannesschobel We release every 2 weeks on Monday. Barring any unforeseen challenges encountered during release, it should be released Monday, Jun 22 sometime during EST working hours.

**Comment by johannesschobel** [comment]
Thank you very much for the info! I will give feedback about this issue when i update to the latest version!

**Comment by kamranayub** [comment]
@jennifer-shehane Ah good catch, I could not find an existing issue! I'll wait for the update!

**Comment by johannesschobel** [comment]
Dear @jennifer-shehane ,

i just wanted to give feedback, that this issue is in fact solved for me!
All the best

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
