### ISSUE TITLE
Type-Command needs force-option on Inputs in ShadowDOM

### ISSUE THREAD

**Issue by suffle** [cypress-io/cypress#7741]
### Current behavior:

Calling  type on an inout in the ShadowDOM throws an error and seems to be called on the wrong element:
```
cy.type() failed because it requires a valid typeable element.

The element typed into was:

  > <webcomponent-lightdom></webcomponent-lightdom>

```

### Desired behavior:

type-command should work on inputs in ShadowDOM just as it does on inputs in LightDOM

### Test code to reproduce
DOM:

```html
<webcomponent-lightdom>
  #shadow-root
    <webcomponent-with-input>
      #shadow-root
        <input type="text" />
    <webcomponent-with-input>
</webcomponent-lightdom>
```

Test:
```javascript
// Finds element but fails on type
cy.get('webcomponent-lightdom').get('input', { includeShadowDom: true }).type('test');

// Works, if you don't have to wait for actionability
cy.get('webcomponent-lightdom').get('input', { includeShadowDom: true }).type('test', {force: true});
```

**Comment by jennifer-shehane** [comment]
Sorry for the simple question, but just want to double check. Do you have the `experimentalShadowDomSupport` set to `true` in Cypress 4.8+ when this issue occurs?

**Comment by suffle** [comment]
`experimentalShadowDomSupport` is set to `true` and the get-Command does find the correct element. The problem seems to be part of the `wait for actionable state`. If I turn that of (by using the option `force: true`), the text gets filled in as expected

**Comment by chrisbreiding** [comment]
### Reproducible example

`cypress.json`

```json
{
  "experimentalShadowDomSupport": true
}
```

`index.html`

```html
<div id="host"></div>

<script>
  document
  .getElementById('host')
  .attachShadow({ mode: 'open' })
  .innerHTML = '<input />'
</script>
```

`spec.js`

```js
it('types into shadow dom', () => {
  cy.visit('/index.html')
  cy.get('input', { includeShadowDom: true }).type('foo')
})
```

**Comment by Dixit199213bafna** [comment]
I am also facing similar issue. When it tries to type in input element that is in shadowDom it gives me a error saying it is trying to type in root .

cy.type() failed because it requires a valid typeable element.

The element typed into was:
<app></app>

**Comment by shaunswales** [comment]
I'm having a similar issue where I seem to be able to .click() but .type() just constantly throws an error...

``` 
cy.type() failed because it requires a valid typeable element.
```

Despite it interacting with an input:
```javascript
  const authLocators = {
  "shadowDOM": {
    "authApp": "wk-ui-auth-app",
    "authLoginPage": "wk-ui-auth-login-page",
    "authLoginForm": "wk-ui-auth-login-form"
  },
  "emailAddressInput": "input#email",
  "passwordInput": "input#password",
  "loginButton": "form button.btn--primary.gt--s"
};

cy.visit('/login');
cy.get(authLocators.emailAddressInput, { includeShadowDom: true }).type("123");
cy.get(authLocators.loginButton, { includeShadowDom: true }).click();
```

**Comment by Dixit199213bafna** [comment]
> I'm having a similar issue where I seem to be able to .click() but .type() just constantly throws an error...
> 
> ```
> cy.type() failed because it requires a valid typeable element.
> ```
> 
> Despite it interacting with an input:
> 
> ```js
>   const authLocators = {
>   "shadowDOM": {
>     "authApp": "wk-ui-auth-app",
>     "authLoginPage": "wk-ui-auth-login-page",
>     "authLoginForm": "wk-ui-auth-login-form"
>   },
>   "emailAddressInput": "input#email",
>   "passwordInput": "input#password",
>   "loginButton": "form button.btn--primary.gt--s"
> };
> 
> cy.visit('/login');
> cy.get(authLocators.emailAddressInput, { includeShadowDom: true }).type("123");
> cy.get(authLocators.loginButton, { includeShadowDom: true }).click();
> ```
> 
> This is targeting the page below, if you follow the link and click the 'Login' button you will see the page that is being tested:
> 
> https://bit.ly/3hMHFU5
> 
> <img alt="Screenshot 2020-06-21 at 13 14 35" width="477" src="https://user-images.githubusercontent.com/17008391/85224345-a403e480-b3c1-11ea-86db-e90db830854e.png">

@shaunswales as @suffle mentioned if we add option as { force: true } it would work
```cy.get(authLocators.emailAddressInput, { includeShadowDom: true }).type("123", { force: true });```

**Comment by jennifer-shehane** [comment]
### Workaround

Passing the option `{ force: true}` to `.type()` will allow typing in the input and ignore the error currently being thrown. We suggest using this workaround in the meantime until this is addressed.

```js
cy.get('input', { includeShadowDom: true })
  .type('foo', {force:true})
```
