### ISSUE TITLE
Cypress uploads passing tests video even if videoUploadOnPasses is false

### ISSUE THREAD

**Issue by pawelgalazka** [cypress-io/cypress#775]
- Operating System: Linux Debian - 8.8
- Cypress Version: 0.20.0
- Browser Version: Electron 53.0.2785.143

### Is this a Feature or Bug?

BUG

### Current behavior:

When setting up Cypress Dashboard with runs, and giving option `"videoUploadOnPasses": false` in `cypress.json` config, video recordings are sent to dashboard anyway, whether test passes or not.

### Desired behavior:

When setting up Cypress Dashboard with runs, and giving option `"videoUploadOnPasses": false` in `cypress.json` config, video recordings should not be sent to dashboard when tests passes.

### How to reproduce:

- Setup video recordings with Cypress Dashboard
- set config `"videoUploadOnPasses": false` in `cypress.json` config
- make tests pass
- check run in Cypress Dashboard

**Comment by jennifer-shehane** [comment]
The `videoUploadOnPasses` configuration key was added in version [`1.0.2`](https://docs.cypress.io/guides/references/changelog.html#1-0-2).

Sorry for the confusion, we need to be a bit more clear about versioning our documentation.

**Comment by brian-mann** [comment]
This feature was introduced in 1.0.2 https://docs.cypress.io/guides/references/changelog.html#1-0-2

I guess we should probably start labeling things in the docs with the version they were released on.

**Comment by pawelgalazka** [comment]
Ahh ok, sorry about that 👍

**Comment by pawelgalazka** [comment]
@jennifer-shehane so I did Cypress update to `1.0.2` and I run it with option `"videoUploadOnPasses": false` all tests passes and in dashboard it still indicates that I have video but it can't load it:

<img width="900" alt="screen shot 2017-10-20 at 9 46 07 am" src="https://user-images.githubusercontent.com/829242/31797729-97c45e6c-b57b-11e7-9e06-c5f271f41290.png">

is that intended ?

**Comment by pawelgalazka** [comment]
Should we reopen this then ?

**Comment by brian-mann** [comment]
Separate issue. It's not uploading the video, its just incorrectly telling the Dashboard that a video was present when it wasn't.

**Comment by BilalRahaoui** [comment]
same problem,still taking videos whatever test pass or not **(05/28/2019)**

**Comment by jennifer-shehane** [comment]
@BilalRahaoui Please [open a new issue](https://github.com/cypress-io/cypress/issues/new?template=bug_report.md) describing exactly what configuration you have set and where. This is a very old issue that was resolved, so what is causing your issue is likely something new and unrelated. Thanks!

I will be locking this original issue to discussion since it was last referenced in 2017.
