### ISSUE TITLE
After type.(`{enter}`) the page reloads and Cypress is not asserting GA events that are fired before this happens

### ISSUE THREAD

**Issue by melibe23** [cypress-io/cypress#7759]
I have the following outside any test:
```js
Cypress.on("window:before:load", win => {
  win.ga = cy.stub().as("ga");
});

```
**The scenario to test is:** User clicks on X element and GA events are fired, then the page reloads (I don´t care about this las behaviour, I only want to test the events fired on click).

 ```js
 it("Search bar - Enter", function() {
  cy.get('id=search')
    //.trigger("keypress", { keyCode: 13 }) I also tried this
  .type(`information{enter}`) 
  // After hiting enter the page reloads so Cypress is trying to assert in the new page and the events are not longer there, so its fails
      cy.get("@ga").should(`be.calledWith`, "send", {
        hitType: "event",
        eventCategory: "search-bar",
        eventAction: "search_enter-search-bar",
        eventLabel: "search-bar"
      });
    });
  });
});
```
This is the GA event that I want to catch (Stub-1)
![image](https://user-images.githubusercontent.com/32499737/85112909-b130a000-b216-11ea-8438-9d3adebbdd2c.png)
It is present, but the assertion is done on the new page  :(

### Desired behavior:
Make assertions on GA events before a new page is loaded.

### Versions
macOS Catalina
Cypress Version 4.7.0

**Comment by jennifer-shehane** [comment]
I think there could be a way to make synchronous assertions on the state of this in the `window:before:load` event, so you couldn't use Cypress commands directly there and you'd need some reference to ga available from there. https://on.cypress.io/catalog-of-events#App-Events

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
