### ISSUE TITLE
Quick way to build tests?

### ISSUE THREAD

**Issue by chachra** [cypress-io/cypress#776]
Is there a way to build tests quickly, or do they have to be written manually?

- Operating System:
- Cypress Version:
- Browser Version:

### Is this a Feature or Bug?
Feature question.

### Current behavior:
Didn't find....

### Desired behavior:
Something similar to http://seleniumbuilder.github.io/se-builder/ and http://www.seleniumhq.org/projects/ide/

#### Test code:

```js

```

**Comment by jennifer-shehane** [comment]
No, although there is a proposal open for this feature if you'd like to add any comments there: https://github.com/cypress-io/cypress/issues/73
