### ISSUE TITLE
Cant run e2e tests | Cant connect to Chrome DevTools

### ISSUE THREAD

**Issue by ritox842** [cypress-io/cypress#7766]
### Current behavior:

I'm getting the following error message: 
![image](https://user-images.githubusercontent.com/7280441/85204870-32c02500-b320-11ea-98a2-00044487f8b3.png)

I've looked in previous issues here and tried to run `netstat -vanp tcp | grep `52297` but it didn't help. Also, I've followed [this issue](https://github.com/cypress-io/cypress/issues/5912) and commenting localhost didn't help.
Tried to reinstall cypress and got the same issue.

It happened all of a sudden. Didn't update anything special.

### Desired behavior:

Should run e2e tests as before.

### Versions
chorme 83.
cypress 4.1.0
mac 10.14.6

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
