### ISSUE TITLE
Can generate large responses : http status 431 Request Header Fields Too Large

### ISSUE THREAD

**Issue by alexkts** [cypress-io/cypress#7768]
### Current behavior:

http status 431 Request Header Fields Too Large

### Desired behavior:

http status 200
### Test code to reproduce

```js
let resp = generateJSONResponce(5000);

cy.server();
cy.route({
  method: 'GET',
  url: '**/myappurl',
  status: 200,
  response: resp,
}).as('qwert');
cy.visit('myappurl');

export function generateJSONResponce(amount) {
  let all = new Array();
  for (let i = 1; i < amount + 1; i++) {
    let instance = {}
    instance.id = i;
    instance.name = i;
    instance.description = "test";
    instance.parameter1 = true;
    instance.parameter2 = true;
    instance.parameter3 = true;
    instance.parameter4 = true;
    instance.parameter5 = true;
    instance.parameter6 = true;
    instance.parameter7 = true;
    instance.parameter8 = false;
    instance.other = [];
    all.push(instance);
  }

  let head = '{';
  let body = JSON.stringify(all);
  let tail = "}";

  let resp = head + body + tail;
  return resp;
}
```

### Versions

cypress 4.8.1

macos | windows 
chrome 83

setting node variable to make limit bigger have no affect

**Comment by loveqseven** [comment]
Got the same status for one of the stubbing requests when move forward to release 6.8.0 from 6.6.0, now roll back to 6.6.0, it works for 6.6.0

**Comment by Astridax** [comment]
I had this when upgrading to 7.2 and upon closer inspection, it does seem that our cookies were pretty large as with other sets of headers. Ironically it only happened when we pointed to staging (not locally). Given that the headers did include the URL, the only thing I could conclude is that we were near the limit of header size.

People had this issue previously: https://github.com/cypress-io/cypress/issues/5431

It was suggested that you add the `NODE_OPTIONS=--max-http-header-size=1000000` to your Cypress npm scripts.

**Comment by KyleThenTR** [comment]
Same issue here after upgrading to 7.3.0 from 6.6.0

**Comment by wilsonpage** [comment]
I ran into this issue when testing my Next.js app. It appears the `NODE_OPTIONS=…` flag is no longer required with the Cypress Node server. I eventually found that the flag needed passing to `next` as the `431` was coming from the Next.js Node server _not_ the Cypress Node server.

```sh
NODE_OPTIONS=--max-http-header-size=1000000 next start
```

**Comment by flotwig** [comment]
`cy.route()` was removed in [Cypress 12.0.0](https://docs.cypress.io/guides/references/changelog#12-0-0), please try using [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept) instead. Closing this issue since the relevant API has been deprecated and removed.
