### ISSUE TITLE
4.8.0 ShadowDOM - Only seems to allow you to travel down through one level

### ISSUE THREAD

**Issue by shaunswales** [cypress-io/cypress#7769]
### Current behavior:
After the release of the 4.8.0 and turning on the experimental flag **experimentalShadowDomSupport** but only seems to let you go one level deep... We use polymer and it has components within each other so multiple levels of ShadowDOM and it doesn't seem possible with this implementation?

Example:
```html
<wrapper-component>
    <div data-testid="count">123</div>
    <iron-lazy-pages>
        <page>
            <div data-testid="page-name">Page Name</div>
        </page>
    </iron-lazy-pages>
</wrapper-component>
```
 
### Desired behavior:
Trying to access the **Page Name** using the new ShadowDOM in 4.8.0 seems I can only access `<wrapper-component>` but the information I am seeking is down multiple levels of ShadowDOM.

### Versions

4.8.0 - experimentalShadowDomSupport

**Comment by 43081j** [comment]
Do you have any example of the code you're using in your test? The selector etc. It definitely does traverse deeply as that was the point of the implementation. So this will either be a bug or usage issue

**Comment by jennifer-shehane** [comment]
@shaunswales Can you please provide the test code you wrote to traverse against the Shadow DOM you provided? Thanks!

**Comment by shaunswales** [comment]
Good Morning, Sorry about the delay in the reply, I have managed to get it working it was an implementation detail and turns out it's an issue with the .type() command against it, which is already open as another issue i've commented on :)
