### ISSUE TITLE
fs.readdirSync is not a function

### ISSUE THREAD

**Issue by nkguoym** [cypress-io/cypress#7770]
const fs = require("fs");
fs.readdirSync("./");

report error: 
TypeError
fs.readdirSync is not a function

**Comment by nkguoym** [comment]
understand wrong, use the plugin can support this need. so close the issue.

**Comment by jprealini** [comment]
@nkguoym hope you are still around.. how exactly did you fix this? I'm driving nuts with this error.. thanks
