### ISSUE TITLE
Cypress can't connect to corporate website by using corporate proxy

### ISSUE THREAD

**Issue by jieyunchen** [cypress-io/cypress#7772]
### Current behavior:

Can't visit the corporate intranet through `cy.vist("https://corporate-web-site")` with corporate proxy. 

Use command `HTTP_PROXY=http://vfproxy.corporate.com.au:8080 npx cypress open` to start the cypress, can visit public website like google but can't visit corporate intranet. 

Here is the error message when cypress tries to connect to corporate website. 
========================= ERROR Message Start ========================
```
CypressError
cy.visit() failed trying to load:

https://corporate-web-site

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: Error establishing proxy connection. Response from server was: HTTP/1.1 503 Service Unavailable
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
Content-Length: 5991

<html>
<meta name="author" content="Corporate name">
<head>
<title>Network Error - 503 tcp_error  - Corporate Internet Security</title>
<link type="image/x-icon" href=
  "http://www.corporate.com.au/cs/static/mm/img/favicon.ico" rel="shortcut icon" />
<style type="text/css">
@font-face {
    font-family: "CorporatePTYRgRegular";
    font-style: normal;
    font-weight: normal;
    src: url("http://www.corporate.com.au/cs/static/fonts/corporateptyrg_digital-webfont.eot?#iefix") format("embedded-opentype"), url("http://www.corporate.com.au/cs/static/fonts/corporateptyrg_digital-webfont.woff") format("woff"), url("http://www.corporate.com.au/cs/static/fonts/corporatetyrg_digital-webfont.ttf") format("truetype");
}
body {
	font-family: CorporatePTYRgRegular, "Trebuchet MS", sans-serif;
	color: #333333;
	background-color: #F4F4F4;
}
a {
    text-decoration: none;
}
a:link {
    color: #333333;
}
a:visited {
    color: #333333;
}
a:hover {
    color: #BF0000;
    text-decoration: underline;
}
a:active {
    color: #BF0000;
}
</style>
<script>
    var button_beg = '<button id="button" onclick="moreless()">', button_end = '</button>';
    var more_button = ' More Info ', less_button = ' Less Info ';
    function moreless() {
        var div = document.getElementById( "less_more" );
        var moreless = document.getElementById( "moreless" );

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
```
========================= ERROR Message End ======================== 

### Desired behavior:

Can connect to https://corporate-web-site successfully through code `cy.vist("https://corporate-web-site")`

### Test code to reproduce

Here is my test code - test.js, I didn't modify other configurations in the framework
```js 
/// <reference types="cypress" />

Cypress.on('uncaught:exception', (err, runnable) => {
    return false;
});

describe("Simple Test", ()  => {
    it("Login application", () => {
       cy.visit("https://corporate-web-site");
    })

})
```

### Versions

Operation system: macOS Catalina, version 10.15.3
Browser: chrome 81
Cypress package version: 4.8.0
Cypress binary version: 4.8.0

**Comment by fatmaBouchekoua** [comment]
Hello,
I have a similar problem, is there any solution please?

**Comment by ctan66** [comment]
I also had similar on this problem, suddenly the corporate website hit 503 service unavailable, however external website like google.com it can display succesfully.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by ctan66** [comment]
Apologized for the delay response. Yes, you can closed this issue as I managed to put these codes under “after()” at /support/index.js it works fine.

**Comment by adasGit** [comment]
Hi @ctan66 which code did you mean to put unde after() at /support/index.js
Could you share please and thank you!

Hi @jieyunchen were you able to fix the issue?

 @jennifer-shehane I am getting the same error when i run tests from Jenkins pipeline!
Same test runs fine when i run in local!
Cypress: 8.7.0

`https://arbetsformedlingen.se/loggain/arbetsgivare

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: Error establishing proxy connection. Response from server was: HTTP/1.1 503 Service Unavailable
Server: squid/3.5.20
Mime-Version: 1.0
Date: Tue, 02 Nov 2021 00:13:17 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 3500
X-Squid-Error: ERR_CONNECT_FAIL 111
Vary: Accept-Language
Content-Language: en`

**Comment by yashgondkar** [comment]
@adasGit Can you please explain little in detail how did you make it work? I am getting similar error for cy.visit
