### ISSUE TITLE
Proposal: get all the test results after all specs are finished and save them into a json/html file. 

### ISSUE THREAD

**Issue by estefafdez** [cypress-io/cypress#7774]
### Current behaviour:

I can get the results by spec and save it into a file and then use some tools to merge, but I can't have a simple JSON/HTML/txt file to display easily on the command line. 

I've tried with a custom report, mocha report... but every time and every event is only for specs, but not for all-suite of tests. 

### Desired behaviour:

I would love to have an easy way to get the complete run results and saved it into a simple .txt file. 

### Test code to reproduce

1. Configure any file to get the results (pass, failed, skipped...) . 
2. All the tests finished to execute (all specs available) and the results from ALL specs are saved in a file (JSON, HTML TXT...). 

### Versions

Any, not relevant.

**Comment by jennifer-shehane** [comment]
Currently you can merge reports across spec files as explained here: https://on.cypress.io/reporters#Merging-reports-across-spec-files

Generating a single report from the CLI here is pretty tricky to implement honestly with the way that tests can be run across multiple machines/environments. We did create a mechanism to communicate across these disparate `cypress run` calls to aggregate the run data in our Dashboard, which requires API requests to a central place to store it. 

Generating reports from our Dashboard has been something others have proposed, so I've added your request to the product board there: https://portal.productboard.com/cypress-io/1-cypress-dashboard

**Comment by estefafdez** [comment]
Thanks @jennifer-shehane . I will try with the merge reports across spec files (it wasn't exactly as I was expecting as I needed something even easier). 

What I was thinking is something like a line at the end that said:

> Your Test: 100 executed, 50 passes, 50 failed, 0 skipped 

and being able to save it into a json, txt or something like that. 

Again, thanks, I will keep an eye on this ticket. Thanks again for your effort to make Cypress great!

**Comment by estefafdez** [comment]
Hello everyone, 

Just to leave my 5 cents here, I finally solve the problem using mochawesome and mochawesome-merge and then with a bash script to display the results as I needed it. 

1. Integrate mochawesome 
2. Integrate mochawesome-merge
3. Add both as steps on the package.json file:

`"merge_reports": "mochawesome-merge --reportDir mochawesome-report > mochawesome-report/Final_Report.json",
"generate_mochawesome_report": "marge mochawesome-report/Final_Report.json"`

4. Run the tests as usual and then execute both of the commands that you defined to create the reports. The file we jeed is the Final_Report.json. 
5. Create the following bash script using jq (https://stedolan.github.io/jq/) to search on the JSON results:

`#!/bin/bash

cd PATH_TO_REPORTS/mochawesome-report

TEST=`cat Final_Report.json | jq ".stats.tests"`
PASSES=`cat Final_Report.json | jq ".stats.passes"`
FAILURES=`cat Final_Report.json | jq ".stats.failures"`
SKIP=`cat Final_Report.json | jq ".stats.skipped"`
PENDING=`cat Final_Report.json | jq ".stats.pending"`
TOTAL_SKIPPED=$((SKIP+PENDING))

echo "TEST_RESULTS: Tests: $TEST | ✔: $PASSES | ✖: $FAILURES | Skipped: $TOTAL_SKIPPED"`

After running an execution on CodeBuild(AWS) I got:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/6990209/87926677-55aa3a00-ca82-11ea-9c3c-b2a79e557ee8.png">

On Slack, I got the notification as I needed: 
<img width="778" alt="image" src="https://user-images.githubusercontent.com/6990209/87926751-707cae80-ca82-11ea-9402-86d3cb1c8dd0.png">

I hope it could help :)

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
