### ISSUE TITLE
Before and After Hooks Running Twice

### ISSUE THREAD

**Issue by adrianYembo** [cypress-io/cypress#7780]
### Current behavior:

I have some before and after calls for creating and deleting a user.  I noticed these calls are running twice for some reason, and the `afterEach` is also executing before the test spec runs, which seems incorrect.

So the order of the calls is `Login > Create Employee` in the before, and `Delete Employee` in the after.  I would expect the first two to run before the test once, but they are running twice, so `PUT, POST, PUT, POST`.  Then I'd expect the test to run, but instead the after runs `DELETE, DELETE`.

### Desired behavior:

`beforeEach` hooks should only execute once before a test starts, and `afterEach` hooks once after the test ends.

### Test code to reproduce

index.js:

```js
beforeEach(() => {
    cy.superAdminLogin(Cypress.env('environment'))

    function randomString(length) {
        var result = '';
        var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstufwxyz0123456789';
        var charactersLength = characters.length;
        for (var i = 0; i < length; i++) {
            result += characters.charAt(Math.floor(Math.random() * charactersLength));
        }
        return result;
    }

    const randomEmail = "qa+" + Math.floor((Math.random() * 100) + 1) + "@gmail.com";

    const password = randomString(8);

    cy.createEmployee(randomEmail, password)

})

afterEach(() => {
    cy.deleteEmployee(Cypress.env('environment'))
})
```

commands.js:

```js
//Login as Super Admin
Cypress.Commands.add('superAdminLogin', (env) => {
    cy.request({
        method: 'PUT',
        url: '/employee/login',
        body: {
            email: Cypress.env('email'),
            password: Cypress.env(env + 'SuperAdminPassword')
        },
        headers: {
            "X-Company-Secret": Cypress.env('devApiSecret')
        }

    })
        .then((resp) => {
            window.localStorage.setItem('accessToken', resp.body.device.accessToken)
            cy.log("SUPER ACCESS TOKEN", localStorage.getItem('accessToken'))
        })
})

// //Create a user with the employee role
Cypress.Commands.add('createEmployee', (email, password) => {
    cy.request({
        method: 'POST',
        url: '/employee',
        body: {
            givenName: Cypress.env('givenName'),
            familyName: "Employee",
            email: email,
            password: password,
            companyKeys: [
                Cypress.env('companyKey')
            ]
        },
        headers: {
            "X-Company-Secret": Cypress.env('apiSecret'),
            "X-Employee-Access-Token": localStorage.getItem('accessToken')
        }
    })
        .then((resp) => {
            window.localStorage.setItem('employeeKey', resp.body.employee.key)
            cy.log("EMPLOYEE KEY", localStorage.getItem('employeeKey'))
        })
})

//Delete Employee
Cypress.Commands.add('deleteEmployee', (env) => {
    cy.request({
        method: 'DELETE',
        url: Cypress.env('deleteUserUrl'),
        body: {
            key: localStorage.getItem('employeeKey'),
            password: Cypress.env(env + 'SuperAdminPassword')
        },
        headers: {
            "X-Company-Secret": Cypress.env('apiSecret'),
            "X-Employee-Access-Token": localStorage.getItem('accessToken')
        }

    })
})

//Mask credentials in console
Cypress.Commands.overwrite('type', (originalFn, element, text, options) => {
    if (options && options.sensitive) {
        options.log = false

        Cypress.log({
            $el: element,
            name: 'type',
            message: "*****"
        })
    }

    return originalFn(element, text, options)
})
```
cypress_dev.json(this has replaced cypress.json):

```json
{
    "defaultCommandTimeout": 8000,
    "requestTimeout": 8000,
    "baseUrl": "https://api.something.dev.company.com",
    "env": {
        "givenName": "Wizard",
        "email": "qa@gmail.com",
        "companyKey": "xxxxxx",
        "deleteUserUrl": "https://api-us.something.dev.company.com/employee"
    }
}
```

### Versions

package.json:
```json
{
  "name": "test-integration-frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cypress:open-dev": "cypress open --config-file cypress_dev.json --env environment=dev"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^4.8.0",
    "cypress-dotenv": "^1.2.1",
    "eslint": "^7.3.0",
    "eslint-plugin-cypress": "^2.11.1"
  },
  "dependencies": {
    "dotenv": "^8.2.0"
  }
}
```
OSX 10.15.4
Electron 80

**Comment by jennifer-shehane** [comment]
Hey @adrianYembo, in Cypress `beforeEach` and `afterEach` hooks will run before and after **each and every test**, so they are expected to run multiple times for each `it` block. 

If you want to run a piece of code **once only** before/after all of the tests within each spec file, you'd want place this code within `before` and `after` hooks. 

You can read more about how hooks are run here: https://on.cypress.io/writing-and-organizing-tests#Hooks

If you believe there is some bug still outside of my explanation, please provide the test code you are running and we will consider reopening the issue.

**Comment by Bkucera** [comment]
@jennifer-shehane I think the issue is they have a `baseUrl` pointing to their api: `https://api.something.dev.company.com`, and they are most likely visiting a different domain in the test body. This would cause a domain change and test restart after the beforeEach has run.

**Comment by adrianYembo** [comment]
> Hey @adrianYembo, in Cypress `beforeEach` and `afterEach` hooks will run before and after **each and every test**, so they are expected to run multiple times for each `it` block.
> 
> If you want to run a piece of code **once only** before/after all of the tests within each spec file, you'd want place this code within `before` and `after` hooks.
> 
> You can read more about how hooks are run here: https://on.cypress.io/writing-and-organizing-tests#Hooks
> 
> If you believe there is some bug still outside of my explanation, please provide the test code you are running and we will consider reopening the issue.

@jennifer-shehane  I did some cleanup in my test file, and now I cannot reproduce.  Guessing some of the errors where triggering this behavior.  I only have one `it` block in the file though, so the hooks should only execute once.
