### ISSUE TITLE
Implement response middleware pattern for net-stubbing

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#7788]
### Current behavior:
Request handlers can be chained:

```ts
req.reply(async (req) => {
	const foo = await something()
	req.headers['x-foo'] = foo
})

req.reply((req) => {
	// more req handling...
})
```

There is not yet a similar system for response handler chaining.

### Desired behavior:
1. Decide if response handler chaining can make sense, and what the rules would be for chaining.
1. Implement an API similar to the req.reply chaining API for res.send.

**Comment by bahmutov** [comment]
Released in v7.0.0
