### ISSUE TITLE
Bug: Cypress hangs when detecting element visibility with Shadow DOM enabled

### ISSUE THREAD

**Issue by kamranayub** [cypress-io/cypress#7794]
### Current behavior:

It is the same or similar as #7679 (fixed in #7692), except this is _with_ `experimentalShadowDomSupport: true` and using Ionic (which heavily uses Shadow DOM).

Essentially when Cypress attempts to detect visibility of an Ionic component where there's a modal backdrop visible, it seems to go into an endless loop of that same find element code path.

**Note:** Also, notice how it thinks the `ion-button` is invisible. I think this is a separate regression/issue because I've seen this in other tests for Ionic popovers/toasts where it thinks it's not visible when they really are.

### Desired behavior:

Interacting with Ionic components shouldn't cause Cypress to hang.

I think that `while` loop may be due for a "max loop" check because it seems like we really don't want Cypress to totally hang under any circumstances. For example, this bug is causing my CI to generate 7GB video files, unless I force-stop the build/workflow.

### Test code to reproduce

https://github.com/kamranayub/junk-bug-cypress-ionic-hang

1. `npm install`
2. `npm run cypress:open`
3. Run the spec
4. Notice how Cypress hangs when the popover is shown

It tests against this URL: https://ionic-react-demo.stackblitz.io/app/account and clicks the top right button, then tries to detect visibility.

### Versions

- Cypress 4.9.0
- Chrome 83
- Windows 10

### Workaround

I think I can safely disable the experiment and rewrite my tests that were using `.shadow()`. 4.7.0 works with the experiment disabled. 4.8.0 had the other regression with clicking specifically.

**Comment by jennifer-shehane** [comment]
@kamranayub Thanks for providing a reproducible example!

I can recreate this from the code provided below (or repo above).

- 4.9.0: `cy.get()` hangs when `experimentalShadowDomSupport` is `true`
- 4.9.0: `cy.get()` does **not** hang when `experimentalShadowDomSupport` is `false`
- 4.8.0: `cy.get()` hangs when `experimentalShadowDomSupport` is `false` or `true`
- 4.7.0: `cy.get()` never hangs

`cypress.json`

```json
{
  "experimentalShadowDomSupport": true
}
```

```js
it('works', () => {
  cy.visit('https://ionic-react-demo.stackblitz.io/app/account');
  // wait for StackBlitz to boot up server
  cy.get('ion-button', { timeout: 60 * 1000 }).click()
  cy.get('ion-popover').should('be.visible')
})
```

![](http://g.recordit.co/Bwm2ukhrb9.gif)

**Comment by KevinBassaDevelopment** [comment]
This seems to be related:
- I am also using cypress with ionic 5.2.0, until cypress 4.5.0 everything worked fine
- I upgraded to cypress 4.9.0 to make use of experimentalShadowDomSupport: true

Result:  
- **cy.wait(500) is hanging** (its not even possible to close the browser once this happens).
- It consistently hangs at the same places

Example:
```
 cy.url().should('contain', TestRoute.stepCreation);
 cy.wait(500); // workaround: wait until routing transition animation is one, as this is not handled by cypress, and ionic ignores clicks that happen while transitioning
```

**Comment by chrisbreiding** [comment]
Here's as concise a reproduction as I could create:

test.html

```html
<html>
<head>
  <style>
    .full {
      bottom: 0;
      left: 0;
      right: 0;
      top: 0;
    }
    .container-1 {
      position: fixed;
    }
    .container-2,
    .host {
      position: absolute;
    }
  </style>
</head>
<body>
  <div class="container-1 full">
    <div class="container-2 full">
      <div class="host full"></div>
    </div>
  </div>

  <script>
    document.querySelector('.host').attachShadow({ mode: 'open' })
  </script>
</body>
</html>
```

spec.js

```javascript
it('hangs on visibility check', () => {
  cy.visit('/test.html')
  cy.get('.container-2').should('be.visible')
})
```

What's required is having an element that's a shadow host ('.host') that takes up all the area of its parent ('.container-2`) and then have any ancestor (`.container-1`) be `position: fixed`. 

It triggers [this part of the visibility algorithm](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/visibility.js#L79) and then gets [hung up here](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/elements.ts#L1234) in an infinite `while` loop because `node.shadowRoot.elementFromPoint(x, y)` returns the same node, which naturally still has a `shadowRoot`.
