### ISSUE TITLE
When switching workplace i am getting all my error where all my xhr get request are getting canclled.

### ISSUE THREAD

**Issue by SidharthLala1** [cypress-io/cypress#7801]
All the xhr request after switching the work place are geeting cancelled due to which no data us getting populated on the screen.

![image](https://user-images.githubusercontent.com/33153967/85615616-2d454080-b67a-11ea-8de5-409d8faaa97e.png)

### If have provided the code and if i do the same actions using cypress it failed.

I have both the files and zipped which has code to reproduce the issue,

### Versions

Windos 10
[integration.zip](https://github.com/cypress-io/cypress/files/4827379/integration.zip)

**Comment by SidharthLala1** [comment]
@jennifer-shehane  Could you please guide why this is happening. i have motivated made them believe cypress is better than selenium but i am still not able to run it as XHR code is getting cancelled.

**Comment by SidharthLala1** [comment]
@jennifer-shehane  Here is google drive link half of the link shows automation and second part of  the videos shows the manual  floe which i am trying to automate. A quick reply would be really  appreciated.

**Comment by jennifer-shehane** [comment]
Hey @SidharthLala1, these tests pass when placed all within a single test. This makes me think that there is something being cleared in between the tests that you need to make sure is preserved for the page to load correctly (it seems to be trying redirect to the `signin` url at some point, you can see in the logs). 

Cypress automatically clears all cookies and localStorage in between every test. 

If you want to preserve a cookie across tests, you can follow the instructions here: https://on.cypress.io/cookies#whitelist-accepts

And an option to preserve localStorage across tests is described here: https://github.com/cypress-io/cypress/issues/461#issuecomment-392070888

```js
  // loads the page
  it('It should load a correct URL', () => {
    cy.visit('https://one.clappia.com/', { timeout: 10000 })
    cy.url().should('include', 'one.clappia.com')
    cy.get('#wrapper > div > div').should('be.visible')
    cy.get('h3').contains('Sign In')
    cy.get('#loginform > div:nth-child(8) > div > div > button').should('be.visible')
    cy.get('#loginform > div:nth-child(3) > div > input').should('have.attr', 'placeholder', 'Email').type('sidharth@clappia.com')
    cy.get('#loginform > div:nth-child(4) > div > input').should('have.attr', 'placeholder', 'Password').type('clappia@786')
    cy.get('#loginform > div.form-group.text-center > div > button').click()
    cy.get('.logo-switcher-icon').click()
    cy.get('.p-r-0 > .logo-container').click()
  })
```
