### ISSUE TITLE
Cypress update to 4.9.0 error: JSDoc types can only be used inside documentation comments.

### ISSUE THREAD

**Issue by ravalibusetty1991** [cypress-io/cypress#7805]
Hi,

I recently updated from 3.1.5 to 4.9.0 and I'm seeing this error on running existing tests in cypress: 

```
 Oops...we found an error preparing this test file:
cypress/integration/ScheduleView/ScheduleFilter_spec.ts
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

A missing file or dependency
A syntax error in the file or one of its dependencies
Fix the error in your code and re-run your tests.

[at-loader] ./node_modules/cypress/types/chai/index.d.ts:124:9 
    TS8020: JSDoc types can only be used inside documentation comments.

[at-loader] ./node_modules/cypress/types/chai/index.d.ts:125:9 
    TS8020: JSDoc types can only be used inside documentation comments.

[at-loader] ./node_modules/cypress/types/chai/index.d.ts:129:16 
    TS2370: A rest parameter must be of an array type.
```

Can someone please help with this?

<img width="1233" alt="Screen Shot 2020-06-24 at 6 39 53 PM" src="https://user-images.githubusercontent.com/9024166/85643837-2999c580-b64a-11ea-9087-8363bc7857d6.png">

**Comment by jennifer-shehane** [comment]
@ravalibusetty1991 We have native TypeScript support since 4.4.0, so if you had any preprocessors handling that, you should be able to remove those. 

Outside of that, I would suggest narrowing down which version this broke in or providing the failing test code so we can help track down the issue exactly because we haven't seen this error before.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
