### ISSUE TITLE
Sometimes My test failed, sometimes it passed

### ISSUE THREAD

**Issue by elycisjasa123** [cypress-io/cypress#7809]
### Current behavior:
- Here is the link during a failed test
https://gitlab.com/stacktrek/stacked/uploads/d9272d812de85a4a22928895a9750512/bandicam_2020-06-25_11-33-50-477.mp4

- Here is the link during my test was passed
https://gitlab.com/stacktrek/stacked/uploads/b5d3cc4b5475dd0772f2e380d22ee7be/bandicam_2020-06-25_11-55-02-190.mp4
### Desired behavior:

- The result must be accurate

### Test code to reproduce

- Here is the link during a failed test
https://gitlab.com/stacktrek/stacked/uploads/d9272d812de85a4a22928895a9750512/bandicam_2020-06-25_11-33-50-477.mp4

- Here is the link during my test was passed
https://gitlab.com/stacktrek/stacked/uploads/b5d3cc4b5475dd0772f2e380d22ee7be/bandicam_2020-06-25_11-55-02-190.mp4

### Versions
Cypress Version -> 4.9.0
Cypress Browser -> Chrome
Cypress command used -> `cypress open`

**Comment by sanakhan205** [comment]
I face the same issue as well

**Comment by jennifer-shehane** [comment]
Just at a quick glace, it looks like you're not waiting long enough for the page to load on reload. There is variation on when things will complete loading, so 4 secs of waiting for the element may not be enough. You can increase the timeout option of the `.get()` command. 

Most often in cases of flaky tests, we see that there is not enough assertions surrounding the actions or XHR requests/responses necessary before moving on to the next assertion. So if there is any variation in the speed of the XHR requests response in interactive mode versus run mode, then there will start to be failures in one over the other - or flaky tests. 

One of our engineers, Gleb, wrote a great blog post about this you can read here: https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/

My best debugging tip is to get a screenshot/video of the Command Log while running in CI on the flaky failed test and compare this to a screenshot/video of the Command Log while passing - anywhere you see that it does not match exactly, look into that - may be a request returned slower or the order of how your app responded slightly changed.

**Comment by gigamesh** [comment]
@jennifer-shehane I'm also grappling with `click` being flaky. Something I don't understand: If you recommend that pipe method explained in the blog post, why isn't it built into cypress? It seems strange that an external library and a custom `click` is needed just to get cypress's `click` to work as expected.
