### ISSUE TITLE
Cypress is causing the test to pass giving false alarm 

### ISSUE THREAD

**Issue by sanakhan205** [cypress-io/cypress#7810]
### Desired behavior:

There was a bug which i could manually reproduce. Clicking the toggle button does not display bar chart on chrome. Ran the test using cypress, it shows the bar chart appearing and passing the test. The collapsed element exists in the DOM, but there was a bug with  bootstrap `v-b-toggle` and is not triggering the collapsed element to appear. Hence i cannot see manually when I do try to test, but how cypress is showing it?

### Test code to reproduce
```js
it('Verify Sales Ratio Card Title And Section visible', function () {
  calcMampDrilldownPage.getSalesRatioText().should('have.text', 'Sales Ratio')
  calcMampDrilldownPage.getSalesRatioTogglebtn().should('have.attr', 'aria-expanded', 'false')
  calcMampDrilldownPage.getSalesRatioTogglebtn().click()
  cy.wait(10000)
  calcMampDrilldownPage.getSalesRatioTogglebtn().should('have.attr', 'aria-expanded', 'true')
  calcMampDrilldownPage.getSalesRationBarchart().should('be.visible')
  calcMampDrilldownPage.getSalesRatioSection().should('be.visible')
})

//The pageobject methods
getSalesRatioTogglebtn(){
  return cy.get('[data-test=dd-sales-ratio-collapse-toggle]')
}


getSalesRationBarchart(){
  return cy.get('.chartjs-size-monitor')
}

getSalesRatioSection(){
  return cy.get('[data-test=drilldown-section-sales-ratio] > .card-body > .row')
}
```
### 

> 
<img width="1439" alt="BarChartDisplayedinCypress" src="https://user-images.githubusercontent.com/65189522/85665462-48ab4e00-b670-11ea-9e70-728d5810ba13.png">
<img width="1438" alt="RealSite" src="https://user-images.githubusercontent.com/65189522/85665515-552fa680-b670-11ea-812d-ff9f0295970e.png">
<img width="1293" alt="Code" src="https://user-images.githubusercontent.com/65189522/85665544-5e207800-b670-11ea-9b09-d594de59d3a1.png">
<img width="1341" alt="CodeTestRunner" src="https://user-images.githubusercontent.com/65189522/85665613-6bd5fd80-b670-11ea-9e26-466343b06b7a.png">

### Versions
Cypress Version : 4.9.0
Operating System : Mac OS High Sierra
Browser : Chrome 83

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
