### ISSUE TITLE
cypress-plugin-retries causing problems with hanging assertions

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#7811]
### Current behavior:

Tests running from console are hanging on failed assertions while using **cypress-plugin-retries**
As you can see on printscreen this test lasting 645.30s, but it's hanging to eternity

Plugin taken from here:
https://github.com/Bkucera/cypress-plugin-retries

![image](https://user-images.githubusercontent.com/34089686/85678812-1ed24580-b6c9-11ea-8ecd-07cb98bb4fea.png)

### Desired behavior:

Test should retry after crash

### Versions
Cypress: 4.9.0
cypress-plugin-retries: 1.5.2
Chrome: 83.0.4103.116

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to the Cypress product, not third party plugins. If you want to open an issue for the plugin, you can open it [here](https://github.com/Bkucera/cypress-plugin-retries). This issue will be closed in this repository.
