### ISSUE TITLE
Bug: experimentalFetchPolyfill modify network requests query string 

### ISSUE THREAD

**Issue by martin-pikalek** [cypress-io/cypress#7813]
### Current behavior: 

When `experimentalFetchPolyfill` is turned on, network requests with query string sent by tested application have modified query string by FetchPolyfill.

For example: request sent by application with url 
```
https://domain.com/api/filter?param1=false&param2=value1&param2=value2
```
is modified to 
```
https://domain.com/api/filter?param1=false&param2=value1,value2
```

Modified request of course return different response by backend server or cannot be processed.

### Desired behavior: 

`experimentalFetchPolyfill` feature should not modify query string of any requests.

### Test code to reproduce: 

Sorry, I'm not application developer (Frontend or Backend) to prepare small test application to give you reproducible example. If you are able to reproduce this with my description of problem, I would be glad.

### Versions : Cypress 4.9.0 , MacOS Catalina 10.15.5
Tested in Chrome 83 and Electron 80

**Comment by TomaszG** [comment]
I can confirm, this happens to me as well. As a result, data to the tested app is not loaded correctly.

**Comment by bahmutov** [comment]
@martin-pikalek there is no definite standard on how the duplicate query parameters should be sent, but I checked the source code for the polyfill we use and did not see anything that would change the URL parameter.

Just to confirm, I have created https://github.com/cypress-io/cypress-test-tiny/tree/query-string
where the app requests the following

```js
const url = 'https://jsonplaceholder.cypress.io/comments?param1=false&param2=value1&param2=value2'
window.fetch(url)
```

## No polyfill

experimental fetch polyfill is false

<img width="1440" alt="Screen Shot 2020-06-26 at 5 17 43 PM" src="https://user-images.githubusercontent.com/2212006/85902123-46acd080-b7d1-11ea-88af-70de94646f46.png">

## Polyfill

experimental fetch polyfill is true, so you see the XHR in the command log

<img width="1440" alt="Screen Shot 2020-06-26 at 5 18 18 PM" src="https://user-images.githubusercontent.com/2212006/85902151-562c1980-b7d1-11ea-8e4b-2277dc57807c.png">

Seems the same query in both cases. We would need a reproducible example thus to work on this issue

**Comment by JessicaSachs** [comment]
We need additional info about the failing request. I believe that this is an issue. We should not be modifying user requests in any way (regardless of Web Standards). Can someone please take a look at @bahmutov’s example repository and see if there is a difference between your own internal application?

**Comment by Ethnity** [comment]
I will try to look tomorow. But it is strange. I compared request url on same environment of application normaly in browser and then in cypress with experimental polyfill and query in url is changed in cypress and test fails. Sorry but I cannot show you our application data.

**Comment by Ethnity** [comment]
I found it because after turning off this experimental polyfill test did not fail.

**Comment by bahmutov** [comment]
Please provide a reproducible example, since I could not reproduce it and did not see how it would be modifying the URL parameter.

**Comment by JessicaSachs** [comment]
@Ethnity @TomaszG or @martin-pikalek when you make the fetch request, what shows up in your command log?

![Screen Shot 2020-06-29 at 12 06 04 PM](https://user-images.githubusercontent.com/2801156/86029334-0af84d80-ba01-11ea-910c-021211bad3c1.png)

**Comment by martin-pikalek** [comment]
@JessicaSachs first image is from cypress with experimentalPolyfill and second image is from browser. PUT request with query param is send after clicking the button.

<img width="926" alt="Screenshot 2020-06-30" src="https://user-images.githubusercontent.com/57229273/86091229-cd9cca00-baab-11ea-8605-9e41f1654c3b.png">
<img width="664" alt="Screenshot 2020-06-30-2" src="https://user-images.githubusercontent.com/57229273/86091241-d2617e00-baab-11ea-8544-87028b8f26cd.png">

**Comment by TomaszG** [comment]
Now I'm not sure if the bug which I have observed is the same, let me know if I should move it to a separate ticket.

My API request is:
`http://localhost:3001/api/sth1/sth2?sth3=4dcedc8e-ba9a-11ea-b78f-0242ac1a0002&sth4="sth_5"&sth6=false`

The logged response with `experimentalFetchPolyfill` turned on is a text response:
```
response: "["Peer ID 4dd129a8-ba9a-11ea-b78f-0242ac1a0002","Peer ID 4dd3b9b6-ba9a-11ea-b78f-0242ac1a0002"]"
responseText: "["Peer ID 4dd129a8-ba9a-11ea-b78f-0242ac1a0002","Peer ID 4dd3b9b6-ba9a-11ea-b78f-0242ac1a0002"]"
responseType: ""
```

However, with `experimentalFetchPolyfill` turned off (and whatwg-fetch turned on instead - [link](https://github.com/cypress-io/cypress/issues/95#issuecomment-526839501)) I get:
```
response: Blob {size: 95, type: "application/json"}
responseText: [Exception: DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').]
responseType: "blob"
```

which, when logged using the following code:
```js
.wait('@alias').then(xhr => {
            Cypress.Blob.blobToBinaryString(xhr.responseBody)
              .then(JSON.parse)
              .then(responseBody => {
                cy.log(responseBody);
              });
          })
```
gets me the same result:
```
 "["Peer ID 4dd129a8-ba9a-11ea-b78f-0242ac1a0002","Peer ID 4dd3b9b6-ba9a-11ea-b78f-0242ac1a0002"]"
```

However, in the first case, the application cannot parse the response correctly and therefore, the data is not loaded to it.

**Comment by martin-pikalek** [comment]
@TomaszG I think it is maybe different issue. I have issue with duplicity query parameters that are stacked together which causing wrong response from backend server.

**Comment by martin-pikalek** [comment]
> @JessicaSachs first image is from cypress with experimentalPolyfill and second image is from browser. PUT request with query param is send after clicking the button.
> 
> <img alt="Screenshot 2020-06-30" width="926" src="https://user-images.githubusercontent.com/57229273/86091229-cd9cca00-baab-11ea-8605-9e41f1654c3b.png">
> 
> <img alt="Screenshot 2020-06-30-2" width="664" src="https://user-images.githubusercontent.com/57229273/86091241-d2617e00-baab-11ea-8544-87028b8f26cd.png">

@JessicaSachs I tried it with chrome runner and electron runner  - both showing exactly same problem with merged duplicity query parameters (after that, backend server do not return right response, button click action is not performed correctly and test fails). When I turned 'experimentalFetchPolyfill' off for whole test or only for that test suite, correct action in UI is made (test succeed, but of-course i do not see mocked request in Cypress UI)

**Comment by bahmutov** [comment]
Can you work around this using [cy.route2](https://on.cypress.io/route2)? Since this experimental fetch polyfill is a temporary measure, we don't plan to investigate it or enhance it.

**Comment by martin-pikalek** [comment]
> Can you work around this using [cy.route2](https://on.cypress.io/route2)? Since this experimental fetch polyfill is a temporary measure, we don't plan to investigate it or enhance it.

@bahmutov I did not tried it on that project yet but I will. I am using route2 on another project and seems working perfectly, did not find any issues yet :) . I will write result soon if the problem was solved by using route2 instead of route.

**Comment by alxndr** [comment]
I have found that with the experimentalFetchPolyfill option turned on, a request using `fetch` with a `Headers` object will lose the custom header value.

I am testing an app which adds an auth header to the requests which the front-end makes to the back-end. However when I look at one of these requests in the Network dev tool, it does not include the auth header any more, and the back-end returns an error. With `"experimentalFetchPolyfill": false, "experimentalNetworkStubbing": true` the header is present and the back-end returns a successful response.

**Comment by jennifer-shehane** [comment]
`experimentalFetchPolyfill` has been deprecated in Cypress 6.0.0. We will not be addressing any new work on this feature. We encourage you to use [`cy.intercept()](https://on.cypress.io/intercept)` to intercept requests using the Fetch API instead.
