### ISSUE TITLE
Cannot read property '_setRequestBody' of undefined

### ISSUE THREAD

**Issue by fltonii** [cypress-io/cypress#7817]
### Current behavior:

Whenever visiting a page in which the XHR id is protected via `Object.defineProperties`, cypress throws the following error:

```
Cannot read property '_setRequestBody' of undefined 
```

The issue here is that the following code in [`packages/driver/src/cypress/server.js`](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/server.js#L338) is trying to override the XHR id with a unique id

```js
add (xhr, attrs = {}) {
    const id = _.uniqueId('xhr')

    _.extend(xhr, attrs)
    xhr.id = id
    xhrs[id] = xhr
    proxies[id] = $XHR.create(xhr)

    return proxies[id]
}
```

But since the `id` property is immutable in my environment and is referencing the value of another property, like so

```js
Object.defineProperties(XMLHttpRequest.prototype, {
    "id": {
        get: function() {
            return XMLHttpRequest.prototype._id
        }
    }
})
```

The result is that the code is not being able to locate the proxy for the request, returning `undefined` instead, thus, causing the error

```js
proxy._setRequestBody(requestBody)
```

### Desired behavior:

I would expect to be able to parameterise the property I want to be considered as an ID, in a way that I would be able to tell cypress to override the property `_id` instead of `id`.

### Test code to reproduce

Reproduction is available here https://github.com/fltonii/cypress-test-tiny

**Comment by Psidium** [comment]
we tried to create an example with our environment, but since we use closed-source tools, we can't share it 😭

**Comment by jennifer-shehane** [comment]
This code has been there for quite a while, so I don't think this was a recently introduced thing. 

I can recreate this with the following code:

```js
it("Sample error when XHR id is not available", () => {
  cy.server()
  cy.route("GET", "/api/myService").as("myService");
  cy.visit("https://cy-test-page.uc.r.appspot.com");
  cy.wait("@myService");
  cy.get("#response").should("equal", `{"working":true}`);
});
```

**Comment by timostark** [comment]
Hi All,
I am experiencing the same issue. The UI library by SAP (Fiori Launchpad based on SAPUI5) is overwriting the XHR Id, which unfortunatly makes it impossible to use cypress for end-to-end launchpad tests (it uses a getter, overwriting the _id attribute).
Is there any option to switch to a different attribute name?

![grafik](https://user-images.githubusercontent.com/19237828/95593930-9181e980-0a4a-11eb-8b7a-f2f7b5bffd63.png)

Regards,
Timo

**Comment by timostark** [comment]
Tagging @jennifer-shehane : any Update on the investigation?

**Comment by manpreetoberoi** [comment]
I am having same issue. @jennifer-shehane is there any work around for this ?

**Comment by gphangurehnn** [comment]
@timostark  @manpreetoberoi @jennifer-shehane is there any workaround for SAP Fiori Launchpad? Thanks

**Comment by luker2** [comment]
@timostark Also using SAP Fiori here & getting the same error. 

We did a hacky work-around using [local overrides](https://developers.google.com/web/updates/2018/01/devtools#overrides) in chrome to modify cypress source code (`cypress_runner.js`).

Obviously this only works when running a test on your local machine with DevTools open. We're also looking for a permanent solution to run on ci/cd - and the band-aid snippet below probably isn't the correct thing to PR to cypress, nor do I know if it fits everyone's use case.

```
getProxyFor(xhr) {
  try {
    const proxy = proxies[xhr.id];                  // use cypress original approach
    if (!proxy) throw new Error();
    return proxy;
  } catch (e) {
    return proxies[Object.keys(proxies)[0]];        // fall-back to looking for xhr uniqueId on 'proxies' object
  }
},
```

![image](https://user-images.githubusercontent.com/8629597/108406898-a0db2580-71e8-11eb-8339-fbc9f3381de9.png)

**Comment by bahmutov** [comment]
See the workaround in https://github.com/cypress-io/cypress-test-tiny/tree/xmloverride

```js
/// <reference types="cypress" />
Cypress.on('test:before:run', () => {
  const server = cy.state('server')
  server.getProxyFor = (xhr) => {
    xhr._setRequestBody = () => { }
    xhr._getXhr = () => {}
    return xhr
  }
})

it("Sample error when XHR id is not available - not working", () => {
  cy.server()
  cy.route("GET", "/api/myService").as("myService");
  cy.visit("https://cy-test-page.uc.r.appspot.com");
  // does not work, since we break book-keeping
  // cy.wait("@myService");
  cy.get("#response").should("contain", `{"working":true}`);
});

it("Sample error when XHR id is not available", () => {
  cy.intercept("GET", "/api/myService").as("myService");
  cy.visit("https://cy-test-page.uc.r.appspot.com");
  cy.wait("@myService");
  cy.get("#response").should("contain", `{"working":true}`);
});
```

The `cy.wait` on `cy.route` no longer works, since the XHR book-keeping is broken, but `cy.intercept` works beautifully and is the preferred method.

<img width="930" alt="Screen Shot 2021-02-18 at 3 04 26 PM" src="https://user-images.githubusercontent.com/2212006/108414906-c96c1b00-71fa-11eb-90d2-5bc55f5f6749.png">

In the future, as we remove the deprecated `cy.server()` and `cy.route()`, this problem will resolve itself.

**Comment by bahmutov** [comment]
I will close this issue, I believe the workaround should be sufficient and we urge everyone to transition to `cy.intercept` command.

**Comment by luker2** [comment]
@bahmutov that looks promising. Can I still access the `proxies` variable which lives outside the scope of `getProxyFor()`?

**Comment by bahmutov** [comment]
Unfortunately no, since it is a closure variable. If we could we could have cy.wait working with cy.route probably

**Comment by luker2** [comment]
@bahmutov Ok. If I'm looking at your example right, I would make my override of `getProxyFor()` in the support file. But since I can't access `proxies` I can't do the same override as I described above. 

Any advice how/if I can achieve the same thing without `proxies` ?

**Comment by bahmutov** [comment]
Use cy.intercept

**Comment by luker2** [comment]
Thanks. I tinkered with `cy.intercept()` but being new to cypress I couldn't get a solution working. Below is what ended up working in our support file. Seems a simple attribute name change suggested by @timostark would solve this but we can get by with this too:

```
Cypress.on('test:before:run', () => {
    const server = (cy as any).state('server');

    const myProxies = {};

    const origAdd = server.add;
    server.add = (xhr, attrs = {}) => {
        const myXhrId = Cypress._.uniqueId('xhr');
        xhr.myXhrId = myXhrId;
        const proxy = origAdd(xhr, attrs);
        myProxies[myXhrId] = proxy;
        return proxy;
    }

    const origGetProxyFor = server.getProxyFor;
    server.getProxyFor = (xhr) => {
        let proxy = tc(() => origGetProxyFor(xhr));
        if (!proxy) proxy = myProxies[xhr.myXhrId];
        return proxy;
    }
})
```

**Comment by Just2Mins** [comment]
I am also facing the same issue. Can anyone help me with some solution?
I tried @luker2 and @bahmutov solutions but not working in my case.
If anyone has any workout then kindly post that over here.

**Comment by nazarkulyk** [comment]
Hi all,

i was launching to same problem few days ago with SAP CF Launchpad service.
Currently it was not possible to cross tests fiori ui5 applications inside launchpad service because SAP want to cap XHR object.
So my best solution for this was to add this code to **/support/e2e.ts**

```typescript
Cypress.on('test:before:run', () => {
  const server = (cy as any).state('server');
  const { defineProperty } = Object;

  const serverAdd = server.add.bind(server);
  server.add = (xhr: XMLHttpRequest, attrs = {}) => {
    defineProperty(xhr, 'id', {
      writable: true,
      configurable: true
    });

    defineProperty(xhr, '_setRequestBody', {});

    defineProperty(xhr, '_getXhr', {});

    return serverAdd(xhr, attrs);
  };
});
```

Maybe there is a better way to change XHR object with intercept command from Cypress, but i didnt found how that suppouse to work. So maybe that saves you some time finding workarround.
