### ISSUE TITLE
cy.route swallows the error about missing fixture

### ISSUE THREAD

**Issue by przemuh** [cypress-io/cypress#7818]
### Current behavior:
When I use shortcut to load a fixture that doesn't exists

```js
cy.route("/path", "fixture:myFileWithDifferentName")
```

I get an error:

    CypressError: The following error originated from your application code, not from Cypress.
    
    When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
    
    This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    
    https://on.cypress.io/uncaught-exception-from-applicationAnd in cy logger there is info that request has been stubbed but responded with `400` HTTP code:![stub](https://user-images.githubusercontent.com/3865478/85800408-33522480-b741-11ea-9d67-3c31046eeba9.png)Maybe related: https://github.com/cypress-io/cypress/issues/78 ?### Desired behavior:Error message should be the same as for `cy.fixture` command:```jscy.fixture("notExistingFixture");``````

Error: A fixture file could not be found at any of the following paths:

> cypress/fixtures/examplEFixture
> cypress/fixtures/examplEFixture{{extension}}

Cypress looked for these file extensions at the provided path:
.json, .js, .coffee, .html, .txt, .csv, .png, .jpg, .jpeg, .gif, .tif, .tiff, .zip

Provide a path to an existing fixture file.
```

Screen:

![fixture](https://user-images.githubusercontent.com/3865478/85800502-609ed280-b741-11ea-932d-cf82d6772574.png)

### Test code to reproduce
You can read the full story on my blog:
https://przemuh.dev/en/blog/watch-out-for-fixtures-in-cypress

App to reproduce the issue (with caseSensitive name) on Linux:
https://github.com/przemuh/cypress-fixture-case

### Versions
4.9.0



┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-114) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Thanks for the thorough write up! I read the blog and agree that this error should be better.

**Comment by jennifer-shehane** [comment]
Full repro:

```js
it('fails with application error', () => {
  cy.visit('https://example.cypress.io/commands/aliasing')
  cy.server()
  cy.route('GET', 'comments/*', 'fx:notExistingFixture').as('getComment')
  cy.get('.network-btn').click()
  cy.wait('@getComment').its('status').should('eq', 200)
})

it('fails correctly - fixutre not found', () => {
  cy.fixture("notExistingFixture")
})
```

<img width="566" alt="Screen Shot 2020-07-17 at 1 16 51 PM" src="https://user-images.githubusercontent.com/1271364/87756996-de7d6780-c82f-11ea-9c97-13a468f1f79d.png">
