### ISSUE TITLE
Using CYPRESS_DOWNLOAD_MIRROR with NO_PROXY and HTTP_PROXY set

### ISSUE THREAD

**Issue by emiltorp** [cypress-io/cypress#7822]
I am trying to use CYPRESS_DOWNLOAD_MIRROR since the build servers are without internet access, we have created local copies of some cypress versions and serve it via a Mirror. 

.npmrc has the CYPRESS_DOWNLOAD_MIRROR and http_proxy and  no_proxy variable as follows
```
registry=internal.registry
CYPRESS_DOWNLOAD_MIRROR=http://localhost/CypressMirror
http_proxy=http://proxy.companyname.local:8080
no_proxy=localhost,*.companyname.local
```
### Current behavior:
```
Installing Cypress (version: 4.9.0)

  ×  Downloading Cypress    
    → Cypress Version: 4.9.0
     Unzipping Cypress      
     Finishing Installation 
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: http://localhost/cypressmirror/desktop/4.9.0?platform=win32&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 407
Response message: authenticationrequired

----------
Platform: win32 (10.0.17763)
Cypress Version: 4.9.0
```

The NO_PROXY variable is working flawlessly when using cypress for testing, but seem to be ignored during the postinstall script of cypress. 

The workaround is to remove the HTTP_PROXY from the npm config during the Cypress installation, and then put it back afterwards when Cypress gets the cached version instead.

### Desired behavior:
The mirror is visited without going via the proxy since it is in the no_proxy configuration, and the download starts

### Test code to reproduce
Have http_proxy configured that requires authentication and no_proxy configured, with a mirror available for example on localhost. Try to install a non-cached version of Cypress.

Honestly, don't know how to set that up, but I see here that the no_proxy variable is never fetched:
https://github.com/cypress-io/cypress/blob/d810950379ca4744748f8ec1735376af06db2441/cli/lib/tasks/download.js

So was hoping it was something obvious missing there...

### Versions
Tested with Cypress 4.9.0 on Windows 10, node 12.18.1, npm 6.14.4

**Comment by flotwig** [comment]
#17702 added support for NO_PROXY here, please try the latest version of Cypress (at minimum, 8.5.0)
