### ISSUE TITLE
Mute libnotify-WARNING on headless

### ISSUE THREAD

**Issue by penx** [cypress-io/cypress#7828]
### Current behavior:

When you run a web app that issues notifications on a headless server, Cypress issues the following warnings to stderr:

`libnotify-WARNING **: Failed to connect to proxy`

### Desired behavior:

This can be worked around by running Cypress as follows:

```sh
cypress run 2> >(grep -v "libnotify-WARNING \*\*: Failed to connect to proxy")
```

However, ideally Cypress should mute this warning by default as it creates a lot of noise on CI servers.

### Test code to reproduce

1. create a web app that uses the notifications api https://developer.mozilla.org/en-US/docs/Web/API/notification
2. create a test that triggers the notification
3. run the test within the cypress:base docker container in a headless environment 

### Versions

Cypress 4.8.0, Cypress Docker base image @ 12

**Comment by penx** [comment]
Related https://github.com/electron/electron/issues/14362

**Comment by jennifer-shehane** [comment]
I'm not seeing this when running locally outside of docker. I think this may be more related to the docker image itself.

**Comment by penx** [comment]
I don't think you'll be able to recreate this locally unless you are running in a headless OS

**Comment by yonatanaftali** [comment]
I'm still having this issue with version 9.0.1. Is there any update?
