### ISSUE TITLE
experimental fetch polyfill locks a site visit

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7830]
Cypress v4.9.0 with experimental fetch polyfill "true"

```js
it('hangs forever', () => {
  cy.visit('https://one.clappia.com/', { timeout: 10000 })
  cy.get('#loginform > div:nth-child(8) > div > div > button').should('be.visible')
})
```

Note: the site has a redirect and bunch of canceled ajax calls normally, maybe there is something that locks up XMLHttpRequest polyfill?

<img width="1440" alt="Screen Shot 2020-06-26 at 8 46 40 AM" src="https://user-images.githubusercontent.com/2212006/85863818-b00cef00-b791-11ea-995d-9b94c991b2b4.png">

**Comment by SidharthLala1** [comment]
@jennifer-shehane What is the issue over here, could you please explain @bahmutov  can you give an insight on the above issue. Since its related to our product.

**Comment by bahmutov** [comment]
@SidharthLala1 nothing alarming for you, it is just weird that our polyfill flag that in Cypress replaces `fetch` with `XMLHttpRequest` object locks up Cypress. This is just for us to investigate further inside Cypress.

**Comment by bahmutov** [comment]
Running against `develop` seeing the test hanging and continuing

<img width="1279" alt="Screen Shot 2020-06-29 at 11 40 51 AM" src="https://user-images.githubusercontent.com/2212006/86026454-72140300-b9fd-11ea-8cc6-ffe31c95c1c2.png">

Note: there are some errors in the DevTools Console

<img width="1276" alt="Screen Shot 2020-06-29 at 11 42 49 AM" src="https://user-images.githubusercontent.com/2212006/86026652-b56e7180-b9fd-11ea-962a-b0fed2a7abb7.png">

Interesting, reloading the test and sometimes it passes. In those cases, I don't see any errors

<img width="1281" alt="Screen Shot 2020-06-29 at 11 47 26 AM" src="https://user-images.githubusercontent.com/2212006/86027128-4f361e80-b9fe-11ea-9e1c-639873b85981.png">

It seems to be the locking up is NOT due to the `fetch` override, but due to thrown errors somehow breaking Cypress

**Comment by bahmutov** [comment]
Interesting without `fetch` polyfill sometimes I see this message

<img width="1276" alt="Screen Shot 2020-06-29 at 11 53 49 AM" src="https://user-images.githubusercontent.com/2212006/86027940-442fbe00-b9ff-11ea-9ec1-6c4aa1305b3d.png">

**Comment by bahmutov** [comment]
The same error is shown in regular Chrome loading the site sometimes

<img width="1440" alt="Screen Shot 2020-06-29 at 11 58 30 AM" src="https://user-images.githubusercontent.com/2212006/86028498-f10a3b00-b9ff-11ea-8db3-37a9c8f6ed9b.png">

And now the site does not load from Cypress

<img width="1279" alt="Screen Shot 2020-06-29 at 11 57 19 AM" src="https://user-images.githubusercontent.com/2212006/86028539-fe272a00-b9ff-11ea-82a9-d817d8a2188f.png">

**Comment by bahmutov** [comment]
Hmm, it seems to "lose" the next command if there are new XHR commands added to the queue. For example this test

```js
it('hangs forever', () => {
  cy.pause()
  cy.visit('https://one.clappia.com/', { timeout: 10000 })

  // finish for the redirect
  cy.wait(10000)
  cy.url().should('include', 'signin')
  cy.contains('button', 'Sign in with Google')
})
```

Going through every command using "next" button, after the page reload it gets a few new XHR objects. Then trying to click "Next" (which shows "cy.wait" command is next) and nothing happens

<img width="1280" alt="Screen Shot 2020-06-29 at 12 35 02 PM" src="https://user-images.githubusercontent.com/2212006/86032439-5c0a4080-ba05-11ea-9527-201c9417f736.png">

**Comment by bahmutov** [comment]
Tried combinations of canceled and new `fetch` calls in a clean project, no luck, the test always completes

<img width="781" alt="Screen Shot 2020-06-29 at 1 06 16 PM" src="https://user-images.githubusercontent.com/2212006/86035010-9aa1fa00-ba09-11ea-8e78-643cc54046b4.png">

**Comment by bahmutov** [comment]
I could not recreate the failure locally, and assume this is from one of the plugins the page is loading. The test can be tried in https://github.com/cypress-io/cypress-test-tiny/tree/test-fetch-lockup

<img width="1438" alt="Screen Shot 2020-06-29 at 1 15 12 PM" src="https://user-images.githubusercontent.com/2212006/86035828-eef9a980-ba0a-11ea-9641-d4d6e57fbb4d.png">

I think the best course of action (which is difficult) is to comment out the code on the page and the widgets one by one to see which one is causing the Test Runner lockup.

**Comment by bahmutov** [comment]
If anyone can demo a standalone reproduction with code, I would be super interested in taking a look again.

**Comment by jennifer-shehane** [comment]
@SidharthLala1 This shouldn't relate to your tests. I happened to be testing your application in the issue and accidentally had the `experimentalFetchPolyfill` configuration on when visiting the app and noticed the behavior was different with the experimental flag on. So, it was a bug that I forwarded to gleb that he then opened to investigate why your app would behave differently with this flag on. 

It shouldn't affect your testing since you do not use this experimental flag.

**Comment by jamie-pate** [comment]
In my application ,this happens when there are 2 visit calls, inside `beforeEach` i log in to the app, and then in the test itself, `visit('/')` never completes because the promise never resolves.

Unfortunately, inside the `unfetch.mjs` that's bundled inside `cypress_runner.js` i'm unable to set logpoints :( is there a good way to modify cypress to be able to alter this dependency?

**Comment by bahmutov** [comment]
Can you work around this using [cy.route2](https://on.cypress.io/route2)? Since this experimental fetch polyfill is a temporary measure, we don't plan to investigate it or enhance it.

**Comment by jennifer-shehane** [comment]
`experimentalFetchPolyfill` has been deprecated in Cypress 6.0.0. We will not be addressing any new work on this feature. We encourage you to use [`cy.intercept()](https://on.cypress.io/intercept)` to intercept requests using the Fetch API instead.
