### ISSUE TITLE
cy.screenshot does not restore the original app iframe

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7832]
Cypress v4.9.0

This is more an exploration and a question, not a bug

In https://github.com/bahmutov/cypress-movie/issues/9 I am trying to take a viewport of an application that has already been set to take over the entire window

```js
cy.screenshot('finish', { capture: 'viewport' })
```

The window size is 1920x1080 and the application under test has been set to cover the entire thing (hiding the command log and the navigation bar)

```js
 Cypress.Commands.add("clearViewport", () => { 
   const runnerContainer = window.parent.document.getElementsByClassName( 
     "iframes-container" 
   )[0]; 
   runnerContainer.setAttribute( 
     "style", 
     "left: 0; top: 0; width: 100%; height: 100%;" 
   ); 
  
   const sizeContainer = window.parent.document.getElementsByClassName( 
     "size-container" 
   )[0]; 
   sizeContainer.setAttribute("style", ""); 
  
   const sidebar = window.parent.document.getElementsByClassName( 
     "reporter-wrap" 
   )[0]; 
   sidebar.setAttribute("style", "opacity: 0"); 
  
   const header = window.parent.document.querySelector( 
     ".runner.container header" 
   ); 
   header.setAttribute("style", "opacity: 0"); 
 }); 
```

So the app is there in the page, no scroll is necessary, the screenshot is take and looks right. But after the screenshot the iframe is shifted again, which is visible in the video

<img width="1440" alt="Screen Shot 2020-06-26 at 11 05 45 AM" src="https://user-images.githubusercontent.com/2212006/85884492-c8403680-b7b0-11ea-82cc-afb04cd17af5.png">

I did try to add a timer after the screenshot to restore the position above, which it does, but there is still a noticeable jump.

![screenshot-spec](https://user-images.githubusercontent.com/2212006/85884620-e5750500-b7b0-11ea-9bea-9b53cb0ea754.gif)

It would be ideal to NOT move the window at all, if capturing the window that is already matching the output dimensions.

**Comment by bahmutov** [comment]
For now as a workaround I used Chrome Debugger Protocol to take the screenshots https://github.com/bahmutov/cypress-movie/pull/12

**Comment by jennifer-shehane** [comment]
Is this a request to change the behavior in the Cypress product? Otherwise, we don't keep questions open in the repo since it adds a lot of noise.

**Comment by bahmutov** [comment]
This is a request for `cy.screenshot` to NOT move and resize the application under test iframe. Because right now Cypress does not restore the AUT after the screenshot, which causes problems and I would classify as unexpected behavior

**Comment by chrisbreiding** [comment]
If you're manually removing the test runner UI and don't want Cypress to do it for you, use `{ capture: 'runner' }`.

**Comment by jennifer-shehane** [comment]
@bahmutov Were you able to pass `capture: 'runner'` to resolve this issue?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
