### ISSUE TITLE
cy.tick() works in Firefox but not Chrome or Electron for setInterval

### ISSUE THREAD

**Issue by joejknowles** [cypress-io/cypress#7834]
### Current behavior:
Tick doesn't trigger setTimeout or setInterval in chrome or electron, but works fine in firefox

In Chrome:
![image](https://user-images.githubusercontent.com/10728145/85919949-8de5a080-b867-11ea-881b-30f40a2e781b.png)

In Firefox:
![image](https://user-images.githubusercontent.com/10728145/85919941-70b0d200-b867-11ea-9e83-b13efd50037c.png)

### Desired behavior:
Tick should trigger setInterval in all browsers

### Test code to reproduce
Simple, full test case: https://github.com/joejknowles/timethings/tree/07780e302de7d81df33f7aff37a023f35fffc4f7

Files with test code: https://github.com/joejknowles/timethings/commit/07780e302de7d81df33f7aff37a023f35fffc4f7
File with app code: https://github.com/joejknowles/timethings/blob/07780e302de7d81df33f7aff37a023f35fffc4f7/src/App.js#L41

The app code is fully functional, you can see it here: https://timethings.xyz/
And the tests pass if they use "cy.wait(4000)" instead of tick, but obviously that makes really slow tests. I've tried longer tick times, multiple tick calls etc. and can't get it to work in chrome. Verified that setInterval is called in my app, but setInterval never calls the callback function in chrome whenever cy.clock() is set.

### Versions

Cypress: 4.9.0
Windows 10
Chrome 83, Firefox 72, Electron 80

**Comment by jennifer-shehane** [comment]
I can recreate this issue from the code in this repo https://github.com/joejknowles/timethings/tree/07780e302de7d81df33f7aff37a023f35fffc4f7

Very strange.

### Firefox

<img width="1049" alt="Screen Shot 2020-06-29 at 3 22 52 PM" src="https://user-images.githubusercontent.com/1271364/85993547-84ea0000-ba1c-11ea-8b35-c97b303b14e7.png">


### Chrome

<img width="1082" alt="Screen Shot 2020-06-29 at 3 23 17 PM" src="https://user-images.githubusercontent.com/1271364/85993611-9501df80-ba1c-11ea-9b07-e857fb3b0206.png">

**Comment by joejknowles** [comment]
@jennifer-shehane Thanks for validating this.

Do you have any ideas/suggestions on where to start with investigating this? I might be able to some time on it, but really have no idea where to begin.

**Comment by Malgalad** [comment]
Looks like the problem is still present in Cypress@7.
