### ISSUE TITLE
Test doesnt fail asserting on onResponse of XHR

### ISSUE THREAD

**Issue by eduardosousaufjf** [cypress-io/cypress#7851]
### Current behavior:

Using "expect" on a XHR onResponse callback does not fail a test.

### Desired behavior:

Using "expect" on a XHR onResponse callback fail a test.

### Test code to reproduce

```js
cy.server();
cy.route({
  method: 'POST',
  url: '**/myurl/',
  onResponse: (xhr) => {
    expect(xhr.status).eq(200);
  }
}).as('myUrlAlias');
```
### Versions

Cypress 4.9.0
Chrome 83
Ubuntu 16.04

**Comment by jennifer-shehane** [comment]
You can't use `expect` assertions inside of callback functions of Cypress commands. You would do this like the following. 

```js
cy.server();
cy.route({
  method: 'POST',
  url: '**/myurl/'
}).as('myUrlAlias');

// do the action that makes the request happen

cy.wait('@myUrlAlias').its('status').should('eq', 200)
```

**Comment by WillPK** [comment]
this only works for one request respone?
How'd you wait for all?
cy.waitAll('@myBaseUrl').its('status').should('eq', 200)

**Comment by jennifer-shehane** [comment]
@WillPK I'm not sure what 'all' means here in your application There is not concept of waiting for 'all' requests, because we don't know how many requests you expect.
