### ISSUE TITLE
Check number of arguments to Cypress.Commands.add

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7858]
Cypress v4.9.0

If one forgets to pass a function to `Cypress.Commands.add` the error is cryptic

```js
// should be
Cypress.Commands.add('toast', fn)
// if we forget `fn` then
Cypress.Commands.add('toast')
```

We get a weird error

<img width="930" alt="Screen Shot 2020-06-30 at 7 58 56 AM" src="https://user-images.githubusercontent.com/2212006/86123632-d9868d00-baa7-11ea-9c49-2b06ff06bd76.png">

Only by looking through the stack we can find what is going on

<img width="1041" alt="Screen Shot 2020-06-30 at 7 59 37 AM" src="https://user-images.githubusercontent.com/2212006/86123666-e60ae580-baa7-11ea-8028-addb0d49cd19.png">

Input parameters should be validated better: `Cypress.Commands.add` can have 2 or 3 parameters, but never 1.

**Comment by jennifer-shehane** [comment]
This is still an issue in 9.5.3
