### ISSUE TITLE
cypress.runner.js not loaded with https

### ISSUE THREAD

**Issue by jhartma** [cypress-io/cypress#786]
- Operating System: Arch Linux
- Cypress Version: 1.0.2
- Browser Version: Electron browser

I noticed that when I visit a https page with a self-signed certificate, the page doesn't load. ```cypress.runner.cs``` is loaded, but ```cypress.runner.js``` returns 404. 

Without https, everything runs fine. My guess is that this is a proxy issue?

**Comment by brian-mann** [comment]
Sounds like it, but Cypress runs just fine on https. We have many projects using it without any problems.

So, we'd need a reproducible example. Maybe some combination of your webserver or OS environment is causing a problem (?)

Can you provide your test code or a link to your webserver?

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?
