### ISSUE TITLE
Multiple tabs - Trade-offs

### ISSUE THREAD

**Issue by FezVrasta** [cypress-io/cypress#7863]
Right now the Trade-offs section mentions multiple tabs support will never be added.

> Most of the time this use case is needed when users click an <a> that opens a new tab. Users then want to switch to that tab to verify that the content loaded. But, you shouldn’t need to do this. In fact we have recipes of showing you how to test this without multiple tabs.

https://docs.cypress.io/guides/references/trade-offs.html#Multiple-tabs

My use case would be to test an app that is supposed to be used on multiple monitors, with one browser window/tab for each screen... (the different tabs would sync with each other). Is there any reason why this use case shouldn't be supported by Cypress?

What are my options?

**Comment by jennifer-shehane** [comment]
Please see https://github.com/cypress-io/cypress/issues/6251 to express your want and use case for this feature. 

Current workarounds are explained in the trade-offs doc.

**Comment by FezVrasta** [comment]
Thanks, current workarounds don't support my use case.
