### ISSUE TITLE
Execution order of `after` hooks when globally defined is not direct opposite of `before` hooks execution order

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7868]
### Current behavior: 

In `before` hooks, the hooks defined in `support/index.js` execute first, before any hooks defined in the spec file, but in the `after` hooks, the hooks defined in `support/index.js` do not execute last - the `after` hooks defined in the spec file run last. 

I verified this is not a UI only issue - this is how they execute. 

### Desired behavior:

This behavior is not what I was expecting. I would expect the `after` hooks to execute in the exact opposite as `before` hooks had - in the same manner. Maybe I'm missing something. 

This seems to be how they've always run, tested back to 3.4.1. 

### Test code to reproduce

`support/index.js`

```js
before(() => {
  cy.log('support/index.js before')
  console.log('support/index.js before')
})

beforeEach(() => {
  cy.log('support/index.js beforeEach')
  console.log('support/index.js beforeEach')
})

afterEach(() => {
  cy.log('support/index.js afterEach')
  console.log('support/index.js afterEach')
})

after(() => {
  cy.log('support/index.js after')
  console.log('support/index.js after')
})
```

`spec.js`

```js
before(() => {
  cy.log('main before')
  console.log('main before')
})

beforeEach(() => {
  cy.log('main beforeEach')
  console.log('main beforeEach')
})

describe('my tests', () => {
  before(() => {
    cy.log('suite before')
    console.log('suite before')
  })
  
  beforeEach(() => {
    cy.log('suite beforeEach')
    console.log('suite beforeEach')
  })
  
  it('visit', () => {
    cy.log('test body')
    console.log('test body')
  })

  afterEach(() => {
    cy.log('suite afterEach')
    console.log('suite afterEach')
  })

  after(() => {
    cy.log('suite after')
    console.log('suite after')
  })
})

afterEach(() => {
  cy.log('main afterEach')
  console.log('main afterEach')
})

after(() => {
  cy.log('main after')
  console.log('main after')
})
```

<img width="524" alt="Screen Shot 2021-02-05 at 3 19 17 PM" src="https://user-images.githubusercontent.com/1271364/107011075-8c993080-67c5-11eb-83f8-00ef592eab8e.png">

**Comment by jennifer-shehane** [comment]
This is still an issue in Cypress 6.4.0

**Comment by felipsimoes** [comment]
@jennifer-shehane this seems to be resolved in more recent versions.

**Comment by cameroncooks-branch** [comment]
Still seeing this in cypress 9.6.0

**Comment by cameroncooks-branch** [comment]
![Screen Shot 2022-06-10 at 12 30 26 PM](https://user-images.githubusercontent.com/87397241/173136932-834aa562-2f8e-42bb-9489-6bfe3f9b4f75.png)

**Comment by rachelruderman** [comment]
I've added a reproducible example in Cypress 10 [here](https://github.com/rachelruderman/cypress-example-kitchensink/blob/rachel/cypress/e2e/github-issues/7868-after-hooks.cy.js)

**Comment by cameroncooks-branch** [comment]
Any update on this?

**Comment by adoshi-branch** [comment]
This is still an issue for us.
