### ISSUE TITLE
Cypress not running after installing on windows 32bit

### ISSUE THREAD

**Issue by fr-ser** [cypress-io/cypress#787]
### Bug:

After the installation through npm I tried to open cypress. It fails with the following error message:

### Stack trace:
```
C:\Users\froeh\Development\werkstatt-app>node node_modules//cypress/bin/cypress open
It looks like this is your first time using Cypress: 1.0.2

 ×  Verifying Cypress can run C:\Users\froeh\Development\werkstatt-app\node_modules\cypress\dist\Cypress
   → spawn UNKNOWN
An unexpected error occurred while verifying the Cypress executable.

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.
----------

Error: spawn UNKNOWN
at _errnoException (util.js:1019:11)
at ChildProcess.spawn (internal/child_process.js:325:11)
at Object.exports.spawn (child_process.js:494:9)
at C:\Users\froeh\Development\werkstatt-app\node_modules\cypress\lib\tasks\verify.js:82:22
at Promise._execute (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\debuggability.js:300:9)
at Promise._resolveFromExecutor (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\promise.js:483:18)
at new Promise (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\promise.js:79:10)
at spawn (C:\Users\froeh\Development\werkstatt-app\node_modules\cypress\lib\tasks\verify.js:77:12)
at runSmokeTest (C:\Users\froeh\Development\werkstatt-app\node_modules\cypress\lib\tasks\verify.js:124:12)
at C:\Users\froeh\Development\werkstatt-app\node_modules\cypress\lib\tasks\verify.js:150:29
at tryCatcher (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._settlePromise0 (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\promise.js:614:10)

at Promise._settlePromises (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\promise.js:693:18)

at Promise._fulfill (C:\Users\froeh\Development\werkstatt-app\node_modules\bluebird\js\release\promise.js:638:18)
----------

Platform: win32 (10.0.10586)
Cypress Version: 1.0.2
```

- Operating System: Windows 10 - 32 Bit
- Cypress Version: 1.0.2
- Browser Version: N/A

**Comment by bahmutov** [comment]
Hmm, we must print the exact command we are using when verifying successful install. Maybe binary was not installed or unzipped correctly due to proxy restrictions.

**Comment by MarcLoupias** [comment]
When a proxy deny your download request it is very clear : 

```
...
> node index.js --exec install

Installing Cypress (version: 1.0.2)

 ×  Downloading Cypress    
   → Cypress Version: 1.0.2
    Unzipping Cypress      
    Finishing Installation 
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/1.0.2?platform=win32&arch=x64
Error: getaddrinfo ENOTFOUND download.cypress.io download.cypress.io:443
----------

Platform: win32 (6.1.7601)
Cypress Version: 1.0.2
```

**Comment by fr-ser** [comment]
I also just did a reinstall of Cypress and do not get any error message during the installation (I still get the abovementioned error however)

```C:\Users\froeh\Development\werkstatt-app>npm install cypress --save-dev

> cypress@1.0.2 postinstall C:\Users\froeh\Development\werkstatt-app\node_modules\cypress
> node index.js --exec install

Installing Cypress (version: 1.0.2)

 V  Downloaded Cypress
 V  Unzipped Cypress
 V  Finished Installation C:\Users\froeh\Development\werkstatt-app\node_modules\cypress\dist\Cypress

You can now open Cypress by running: node_modules\.bin\cypress open

https://on.cypress.io/installing-cypress
+ cypress@1.0.2
added 67 packages in 450.01s`

**Comment by webia1** [comment]
same here 

```
Installing Cypress (version: 1.4.2)

 ×  Downloading Cypress
   → Cypress Version: 1.4.2
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/1.4.2?platform=win32&arch=x64
Error: getaddrinfo ENOTFOUND download.cypress.io download.cypress.io:443
----------

Platform: win32 (10.0.15063)
Cypress Version: 1.4.2
```

We are behind a corporate proxy, that could be the reason.

**Comment by ManasaThaduri** [comment]
Similar issue 


> cypress@1.4.2 postinstall C:\Users\Thaduri\Development\fxc-client\node_modules\cypress
> node index.js --exec install

Installing Cypress (version: 1.4.2)

 ×  Downloading Cypress
   → Cypress Version: 1.4.2
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/1.4.2?platform=win32&arch=x64
Error: connect ECONNREFUSED 104.25.215.23:443
----------

Platform: win32 (6.1.7601)
Cypress Version: 1.4.2
npm verb lifecycle cypress@1.4.2~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle cypress@1.4.2~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\
haduri\Development\fxc-client\node_modules\cypress\node_modules\.bin;C:\Users\Thaduri\Development\fxc-client\node_modul
s\.bin;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath
C:\Program Files\Java\jdk1.8.0_60\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
sPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\apache-maven-3.3.3\bi
;C:\Users\khaliq\AppData\Roaming\npm;C:\Program Files (x86)\Git\cmd;C:\Users\Thaduri\AppData\Local\Programs\Git\cmd;C:\
rogram Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\WINDOWS\System32\WindowsPo
erShell\v1.0\;C:\Program Files\Microsoft Application Virtualization\Client ;C:\Ruby23\bin;C:\Users\Thaduri\AppData\Roam
ng\npm;C:\Users\Thaduri\AppData\Local\Programs\Fiddler



Can somebody help me fixing the proxy/connectivity issue.

**Comment by fr-ser** [comment]
I do believe that the issue I have in the original post is different than the ones you mention here.
I get no error message downloading, but only on the first run.

**Comment by NAPOLEON039** [comment]
I get this same error when I try to run cypress :(

**Comment by kutlaykural** [comment]
Hi all,
My system is windows 7 x86 
I downloaded cypress last update from;
https://download.cypress.io/desktop?platform=win32&arch=x86
but it says "this program is incompetible with your Windows. Please check program requirements whether x86 or x64"
what can I do?

**Comment by davegahn** [comment]
Same errors. Has anybody solved this?..

**Comment by itaditya** [comment]
I'm having the same issue as mentioned in title 


```
$ $(npm bin)/cypress open

It looks like this is your first time using Cypress: 3.0.1

 x  Verifying Cypress can run C:\Users\dev_adi\AppData\Local\Cypress\Cache\3.0.1\Cypress
   → spawn UNKNOWN
An unexpected error occurred while verifying the Cypress executable.

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.
----------

Error: spawn UNKNOWN
at _errnoException (util.js:999:13)
at ChildProcess.spawn (internal/child_process.js:340:11)
at Object.exports.spawn (child_process.js:499:9)
at F:\git\Testing\cypress-handson\node_modules\cypress\lib\tasks\verify.js:67:22
at Promise._execute (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\debuggability.js:300:9)
at Promise._resolveFromExecutor (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\promise.js:483:18)
at new Promise (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\promise.js:79:10)
at spawn (F:\git\Testing\cypress-handson\node_modules\cypress\lib\tasks\verify.js:62:12)
at runSmokeTest (F:\git\Testing\cypress-handson\node_modules\cypress\lib\tasks\verify.js:109:12)
at F:\git\Testing\cypress-handson\node_modules\cypress\lib\tasks\verify.js:132:29
at tryCatcher (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._settlePromise0 (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\promise.js:614:10)
at Promise._settlePromises (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\promise.js:693:18)
at Promise._fulfill (F:\git\Testing\cypress-handson\node_modules\bluebird\js\release\promise.js:638:18)
----------

Platform: win32 (6.1.7601)
Cypress Version: 3.0.1
```

**Comment by brian-mann** [comment]
@itaditya we've never seen this before. Perhaps it is a permissions issue. It looks like you're trying to run Cypress across a network drive - since I see it's installed to C:/ but your node modules is in F:/

Can you run Cypress in debug mode so we get all of the logs output?

```
set DEBUG=cypress:cli npm install
```

**Comment by Davidcreador** [comment]
```
> node index.js --exec install

  cypress:cli installing Cypress from NPM +0ms
  cypress:cli installing with options {} +0ms
  cypress:cli version in package.json is 3.0.1 +17ms
  cypress:cli no binary installed under cli version +285ms
  cypress:cli checking local file C:\Users\DPastor\Desktop\Dev\party-landing-web\3.0.1 cwd C:\Users\DPastor\Desktop\Dev\party-landing-web\node_modules\cypress +153ms
  cypress:cli preparing to download and unzip version  3.0.1 to path C:\Users\DPastor\AppData\Local\Cypress\Cache\3.0.1 +57ms
Installing Cypress (version: 3.0.1)

  cypress:cli needed Cypress version: 3.0.1 +0ms
  cypress:cli downloading cypress.zip to "C:\Users\DPastor\AppData\Local\Temp\cypress.zip" +69ms
 \  Downloading Cypress
    Unzipping Cypress
 |  Downloading Cypress
    Unzipping Cypress
 ×  Downloading Cypress
   → Cypress Version: 3.0.1
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/3.0.1?platform=win32&arch=x64
Error: unable to get local issuer certificate
----------

Platform: win32 (10.0.15063)
Cypress Version: 3.0.1
```

I am getting the same error, I just set it to DEBUG and that is what I am getting. Please review it and let me know what is happening and what could be the possible solution for it? I am on windows btw.

**Comment by AlxndrMlk** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle warsawjs-workshop-23-shopping-cart@0.1.0~pretest: warsawjs-workshop-23-shopping-cart@0.1.0
6 info lifecycle warsawjs-workshop-23-shopping-cart@0.1.0~test: warsawjs-workshop-23-shopping-cart@0.1.0
7 verbose lifecycle warsawjs-workshop-23-shopping-cart@0.1.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle warsawjs-workshop-23-shopping-cart@0.1.0~test: PATH: C:\Users\Ol\AppData\Roaming\nvm\v10.9.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Ol\Documents\PROGRAMMING\WAW_JS_2\warsawjs-workshop-23-shopping-cart\node_modules\.bin;C:\Users\Ol\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\bin;C:\Users\Ol\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\TXE Components\TCS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Hewlett-Packard\SimplePass;C:\Program Files\Intel\TXE Components\DAL;C:\Program Files\Intel\TXE Components\IPT;C:\Program Files\MATLAB\MATLAB Compiler Runtime\v710\runtime\win32;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\Library\bin;C:\MinGW\bin;C:\Program Files\Git\cmd;C:\Program Files\Skype\Phone;C:\Program Files\wkhtmltopdf\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\Ol\AppData\Local\Microsoft\WindowsApps;C:\Users\Ol\AppData\Local\atom\bin;C:\Users\Ol\AppData\Local\Microsoft\WindowsApps;C:\Users\Ol\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle warsawjs-workshop-23-shopping-cart@0.1.0~test: CWD: C:\Users\Ol\Documents\PROGRAMMING\WAW_JS_2\warsawjs-workshop-23-shopping-cart
10 silly lifecycle warsawjs-workshop-23-shopping-cart@0.1.0~test: Args: [ '/d /s /c', 'cypress open' ]
11 silly lifecycle warsawjs-workshop-23-shopping-cart@0.1.0~test: Returned: code: 1  signal: null
12 info lifecycle warsawjs-workshop-23-shopping-cart@0.1.0~test: Failed to exec test script
13 verbose stack Error: warsawjs-workshop-23-shopping-cart@0.1.0 test: `cypress open`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Ol\AppData\Roaming\nvm\v10.9.0\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Ol\AppData\Roaming\nvm\v10.9.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid warsawjs-workshop-23-shopping-cart@0.1.0
15 verbose cwd C:\Users\Ol\Documents\PROGRAMMING\WAW_JS_2\warsawjs-workshop-23-shopping-cart
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error warsawjs-workshop-23-shopping-cart@0.1.0 test: `cypress open`
22 error Exit status 1
23 error Failed at the warsawjs-workshop-23-shopping-cart@0.1.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

On Win 10 32bit I get the above log. `cypress` itself opens and returns options screen, but returns the above output when `cypress open` executed.

Will be grateful for feedback. Thanks!

**Comment by jennifer-shehane** [comment]
Where are you running the `cypress open`/`cypress run` command from? Is it in a plain terminal (cmd) window or from a terminal within your IDE program? I've read that running from the IDE terminal may cause this issue.

**Comment by Saibamen** [comment]
1. Does installing latest npm and node helps you?
2. Your npm and node is in global variables? (type `npm --version` and `node --version` to test it)
3. Please try install Cypress with admin - right click on cmd.exe and click "Run as Administrator"
4. Can you download Cypress directly from your browser: http://download.cypress.io/desktop or https://download.cypress.io/desktop/3.0.3?platform=win32&arch=x64

**Comment by Saibamen** [comment]
@AlxndrMlk Please try open it by adding
```
"scripts": {
    "cypress": "cypress"
  },
```
into your `package.json` file and run it by executing `npm run cypress open`

**Comment by PiyushTalwalkar** [comment]
Can I get some help on above issue

**Comment by fr-ser** [comment]
Just a quick heads up. I don't even use Windows anymore and cannot give any input here. Maybe the other posters have the same issue and can help....

**Comment by timelights** [comment]
https://github.com/cypress-io/cypress/issues/1554#issuecomment-471166439

**Comment by brian-mann** [comment]
@flotwig or @jennifer-shehane 	 	is this fixing the issue here? It says it's addressing the comments... should we lock this issue then?

**Comment by jennifer-shehane** [comment]
@brian-mann Many of the earlier comments were experiencing a proxy issue that will be resolved by this PR https://github.com/cypress-io/cypress/pull/3531 and the release of 3.3.0 - specifically these comments:

- https://github.com/cypress-io/cypress/issues/787#issuecomment-339024837
- https://github.com/cypress-io/cypress/issues/787#issuecomment-363499210

Although the original issue is the error below specifically, and this should be left open for this. 
```
 x  Verifying Cypress can run C:\Users\dev_adi\AppData\Local\Cypress\Cache\3.0.1\Cypress
   → spawn UNKNOWN
```

Although, I think this PR may give more insight into why the `spawn UNKNOWN` error is occuring since it specifically adds more login to `cypress verify` https://github.com/cypress-io/cypress/pull/3807

**Comment by flotwig** [comment]
We have fixed this by also building for Windows 32-bit.

The code for this is done in [cypress-io/cypress#3877](https://github.com/cypress-io/cypress/pull/3877), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by Mugane** [comment]
Except I don't have a proxy, so nothing at all is clear!

> When a proxy deny your download request it is very clear :
> 
> ```
> ...
> > node index.js --exec install
> 
> Installing Cypress (version: 1.0.2)
> 
>  ×  Downloading Cypress    
>    → Cypress Version: 1.0.2
>     Unzipping Cypress      
>     Finishing Installation 
> The Cypress App could not be downloaded.
> 
> Please check network connectivity and try again:
> ----------
> 
> URL: https://download.cypress.io/desktop/1.0.2?platform=win32&arch=x64
> Error: getaddrinfo ENOTFOUND download.cypress.io download.cypress.io:443
> ----------
> 
> Platform: win32 (6.1.7601)
> Cypress Version: 1.0.2
> ```
