### ISSUE TITLE
Missing reporterOptions from the ResolvedConfigOptions in cypress

### ISSUE THREAD

**Issue by admmasters** [cypress-io/cypress#7877]
### Current behavior:
reporterOptions is missing from [cypress.d.ts](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)

### Desired behavior:
reporterOptions should be added

### Test code to reproduce
N/A these are typescript types

### Versions
4.9.0

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-252) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
We're open to pull requests to add this!

**Comment by admmasters** [comment]
Sure I’ll create a PR for this later 👍🏽

**Comment by admmasters** [comment]
Added https://github.com/cypress-io/cypress/pull/8217
