### ISSUE TITLE
BeforeEach global (index.js) in combination with BeforeEach in file

### ISSUE THREAD

**Issue by Fanch-** [cypress-io/cypress#7880]
### Current behavior:

BeforeEach global (index.js) with a BeforeEach in file; makes an 'extra call' with cy.visit().

```
  FILE 1

GLOBAL before each index.js -> file 1 test 1
before each of file 1

GLOBAL before each index.js -> file 1 test 1
before each of file 1
    ✓ file 1 test 1 (335ms)
```

### Desired behavior:
Ability to control the flow, and even if having independent tests is the correct way to write them, I would like to not surcharge each test file with the same call. Thank you for the time to read this.

```
 FILE 1

GLOBAL before each index.js -> file 1 test 1
before each of file 1
    ✓ file 1 test 1 (335ms)

```
### Test code to reproduce

_plugins/index.js_

```js
module.exports = (on, config) => {
    on('task', {
        log(message) {
            console.log(message)

            return null
        }
    })
}
```

_support/index.js_

```js
beforeEach(function(){
    cy.task('log',`\nGLOBAL before each index.js -> ${this.currentTest.title}`)
})

afterEach(function(){
    cy.task('log',`GLOBAL after each index.js -> ${this.currentTest.title}`)
});
```

_file1.spec.js_

```js
describe('FILE 1', () => {
  beforeEach(() => {
    cy.task('log','before each of file 1')
    cy.visit('https://example.cypress.io/commands/location')
  })

  afterEach(() => {
    cy.task('log','after each of file 1 ******')
  })

  it('file 1 test 1', () => {
    // https://on.cypress.io/hash
    cy.hash().should('be.empty')
  })

  it('file 1 test 2', () => {
    // https://on.cypress.io/location
    cy.location().should((location) => {
      expect(location.hash).to.be.empty
    })
  })

  it('file 1 test 3', () => {
    // https://on.cypress.io/url
    cy.url().should('eq', 'https://example.cypress.io/commands/location')
  })
})
```
_file2.spec.js_

```js
describe('FILE 2', () => {
  beforeEach(() => {
    cy.task('log','before each of file 2')
    //no cy.visit here
  })

  afterEach(() => {
    cy.task('log','after each of file 2')
  })

  it('file 2 test 1', () => {
    // https://on.cypress.io/window
    cy.window().should('have.property', 'top')
  })

  it('file 2 test 2', () => {
    // https://on.cypress.io/document
    cy.document().should('have.property', 'charset').and('eq', 'UTF-8')
  })

  it('file 2 test 3', () => {
    // https://on.cypress.io/title
    cy.title().should('include', 'Kitchen Sink')
  })
})
```

**cypress run command** 

![file1](https://user-images.githubusercontent.com/7208988/86466668-55950500-bd34-11ea-8984-1468df20166b.png)
![file2](https://user-images.githubusercontent.com/7208988/86466676-588ff580-bd34-11ea-8fb6-ddd0e0e207f1.png)

So it looks like the cy.visit() somehow makes each beforeEach call twice for the first test.

Watching UI it seems fine :

![ui_file1](https://user-images.githubusercontent.com/7208988/86467472-b96bfd80-bd35-11ea-843c-b196deed12a9.png)

But watching the console we can still see that extra log anyway :

![console](https://user-images.githubusercontent.com/7208988/86467803-6181c680-bd36-11ea-8994-ad0db8a0e026.png)

Maybe I am doing it wrong?

### Versions

cypress: 4.8.0,
electron,
linux

**Comment by jennifer-shehane** [comment]
This can happen when you do not have a `baseUrl` set. So Cypress navigates to `localhost:<randomport>` and executes the hooks and tests until it runs into a `cy.visit()`, at this point, Cypress then needs to navigate to the url under test in the main window - this causes the hooks and previous commands to rerun under the new domain. 

You can avoid this by setting a `baseUrl`.
