### ISSUE TITLE
Cypress Examples itself not opening

### ISSUE THREAD

**Issue by PoornimaEkamban** [cypress-io/cypress#7883]
Cypress Examples script itself not working 

While running the test the URL in my chrome is like this
http://localhost:55128/__/#/tests/integration\examples\actions.spec.js
 
Steps:
1.created one folder
2. run npm init -y 
3.npm install --save-dev cypress
4.npx cypress open

But I saw some demo their the URL is in the following format

http://localhost:55128/__/#/tests/integration/examples/actions.spec.js

### Versions
Cypress 4.9.0
operating system windows 10 
browser chrome browser 83

**Comment by jennifer-shehane** [comment]
This url should not affect the behavior - it's just the difference of slashes from Windows and other OSes. 

- Can you describe what you mean by 'not working'?
- Can you provide a video or error of the failing run?

Thanks!

**Comment by PoornimaEkamban** [comment]
Here I attached the screenshots of the issues.
my browser
![image](https://user-images.githubusercontent.com/67619156/86649978-5c728f00-c036-11ea-8bc6-0fcc893dc6eb.png)
 
Cypress window
![image](https://user-images.githubusercontent.com/67619156/86650180-9479d200-c036-11ea-9417-7e09d3689440.png)

My Visual code editor and terminal
![image](https://user-images.githubusercontent.com/67619156/86650577-eae71080-c036-11ea-8a41-e1915c437506.png)

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

Do you have anything in your cypress.json, support/plugins files?

**Comment by cjydayang** [comment]
@jennifer-shehane I have a similar problem，my operating system is windows 10，run test script not work in chrome，return result “ERR_TIMED_OUT”.but it works fine in electron.Then i run cypress with chrome on MacOS（run the same test script），all works fine.So can you give me some suggestions that how do I check the environment on windows

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
