### ISSUE TITLE
Screenshot height changes between runs.

### ISSUE THREAD

**Issue by steveharrison** [cypress-io/cypress#7887]
### Current behavior:
When I run `npx cypress run --browser chrome` in my example project, [example.zip](https://github.com/cypress-io/cypress/files/4877282/example.zip), it generates different sized screenshots on multiple runs, with no files changed in between runs. I am running the command in a Terminal window on my external monitor for all runs, so the display resolution should be consistent.

Last week, it produced a screenshot that was 1000x660px (the "Generated 1" image in the example project).
I cleared the baseline image, ran it again, and got a 1000x487px screenshot (the "Generated 2" image in the example project). I ran the tests again, and it failed, because it was now comparing it with a 1000x537px screenshot.
I cleared the baseline image again, ran the command again, and got a 1000x537px screenshot. I ran the tests again, and they succeeded. It seems like most of the time, the command produces a 1000x537px screenshot, but sometimes, it produces something different.

Firstly, I'm confused as to why the height changes. Secondly, I'm confused as to where the 537px value is coming from, since I'm setting the browser size to 1000x600 in the `before:browser:launch` hook in `cypress/plugins/index.js`.

If you think this is instead an issue with the `cypress-image-snapshot` plugin, I am happy to raise it there instead.

### Desired behavior:
I would like the screenshots to be to be able to run `npx cypress run --browser chrome` multiple times under the same conditions and have resulting screenshots the same size.

### Test code to reproduce
I've attached a ZIP file. You just need to unzip it, use Node 13.9.0, run `npm i`, run `npm start`, and then run `npx cypress --run browser chrome`.

### Versions
Node 13.9.0
Cypress 4.9.0
macOS 10.15.3

**Comment by jennifer-shehane** [comment]
The original screenshots in the Cypress `screenshots` folder seem to be the same consistent size. 

The screenshots are also always consistent when using `cy.screenshot({capture: 'viewport'});`, so I would say this is a `cypress-image-snapshot` issue.
