### ISSUE TITLE
jUnit test results are owned by root when running as another user

### ISSUE THREAD

**Issue by drumbeg** [cypress-io/cypress#7888]
### Current behavior:

I am running Cypress within a Docker container based on Oracle Linux 7. I am kicking off tests using `cypress run` as a `sysadmin` user. All test artifacts generated are owned by this user except for my jUnit test output, which is owned by `root`. This means my CI framework cannot access test results.

### Desired behavior:

jUnit test output should be owned by the user I am logged in as when I run Cypress.

#### docker-compose.yml showing `sysadmin` test user

```yml
my-service:
    user: sysadmin
    image: cypress:4.9.0
    command: npm test
    ipc: host
```

#### package.json showing scripts

```json
"scripts": {
    "start": "cypress open",
    "test": "cypress run",
```

#### cypress.json

```jsson
"reporter": "junit",
"reporterOptions": {
    "mochaFile": "results/test-results.xml"
}
```

#### Output

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1645007/86596282-dd2b7f80-bf91-11ea-8a22-54f687b92154.png">

### Versions

4.9.0

**Comment by BlueWinds** [comment]
Going to close this after two years of inactivity + 7 major versions of Cypress. Please feel free to open another issue if this is still a problem and we'll try and do better about looking into things!
