### ISSUE TITLE
Provide ability to test @media print mode

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#790]
### Is this a Feature or Bug?
Feature

### Current behavior:
Now it's not possible to test CSS rules that only work in `@media print` mode.

### Desired behavior:
Provide a way to have a page rendered in `@media print` mode, eg:

```js
cy.viewport('print');
```
Apparently there is a [chromium flag](https://peter.sh/experiments/chromium-command-line-switches/#enable-print-browser) for this.

**Comment by verheyenkoen** [comment]
See also #691

**Comment by jennifer-shehane** [comment]
I wasn't able to get this flag to work actually. It appears that the print-mode is being applied to Cypress itself - and not applying to the iframe of the application under test. 

index.html

```html
<!DOCTYPE html>
<html>
<head>
  <style>
    @media print {
      div {
        background-color: red;
        color: white;
      }
    }
  </style>
</head>
<body>
  <div>Sed posuere consectetur est at lobortis. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
  Vestibulum id ligula porta felis euismod semper. Maecenas faucibus mollis interdum. Maecenas sed diam eget risus varius
  blandit sit amet non magna. Nullam quis risus eget urna mollis ornare vel eu leo.
  
  Cras mattis consectetur purus sit amet fermentum. Cras mattis consectetur purus sit amet fermentum. Morbi leo risus,
  porta ac consectetur ac, vestibulum at eros. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
  
  Curabitur blandit tempus porttitor. Cras mattis consectetur purus sit amet fermentum. Vivamus sagittis lacus vel augue
  laoreet rutrum faucibus dolor auctor. Sed posuere consectetur est at lobortis. Vivamus sagittis lacus vel augue laoreet
  rutrum faucibus dolor auctor. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.
</div>
  <script>
  </script>
</body>
</html>
```

test code

```js
it('example', () => {
  cy.visit('index.html')
})
```

plugins/index.js

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--enable-print-browser')
    }

    return args
  })
}
```

My test result should look like:

<img width="1792" alt="Screen Shot 2019-07-16 at 3 30 30 PM" src="https://user-images.githubusercontent.com/1271364/61280992-de8ef580-a7de-11e9-9a7b-f0685a81bd07.png">

Instead it looks like:

<img width="1792" alt="Screen Shot 2019-07-16 at 3 25 03 PM" src="https://user-images.githubusercontent.com/1271364/61280521-0598f780-a7de-11e9-95a5-01d8732c4e92.png">

**Comment by verheyenkoen** [comment]
Oh, well I didn't think about the `iframe` obviously. Can't think of another way to get that working.

Btw, in that last screenshot, why is the viewport that small? Did you scale that down manually?

**Comment by jennifer-shehane** [comment]
No, the area in the rightside pops up like that - with these blank spaces in this DOM area to the right. I didn't look into why.

**Comment by simonireilly** [comment]
There is a provided example from cypress of achieving this using the chrome remote debugger here:

https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__chrome-remote-debugging

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
