### ISSUE TITLE
No Version of cypress is install error, everytime when open my machine getting this error

### ISSUE THREAD

**Issue by Ayushrjt** [cypress-io/cypress#7901]
cypress cache exists before reboot, but is gone after, after rebooting maching everything is there except cypress, asking to install again

### Current behavior
![Screenshot (1)](https://user-images.githubusercontent.com/67945680/86734043-4e7d3800-c04f-11ea-99ad-99434bc81c53.png)

I've installed Cypress successfully, but when I try to run it with `npx cypress open` I get:-->

```
No version of Cypress is installed in: C:\Users\AXS06ZD\AppData\Local\Cypress\Cache\3.8.3\Cypress

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: C:\Users\AXS06ZD\AppData\Local\Cypress\Cache\3.8.3\Cypress\Cypress.exe

----------

Platform: win32 (10.0.17763)
Cypress Version: 3.8.3
```

## Desired behavior:

`npx cypress open` should open Cypress

Steps to reproduce:

- `npm install`
- `npx cypress open`

### Versions

cypress-3.8.3
node- v12.14.0
windows10

**Comment by jennifer-shehane** [comment]
What does `cypress cache list` print? If we don't find the cache there, then we don't consider Cypress as installed, so it will need to be reinstalled. 

Is there something changing when you reboot? Like the user?

**Comment by Ayushrjt** [comment]
user is not changing after reboot but i don't find cache folder in users C:\Users\AXS06ZD\AppData\Local\Cypress\Cache\3.8.3\Cypress  -not present on the path
After reboot i think machine clears the cache folder from that location. is there any way that we can change the path of cache folder ?
![Screenshot (2)](https://user-images.githubusercontent.com/67945680/86759479-2fd46c80-c062-11ea-819d-c457c762e25d.png)

**Comment by jennifer-shehane** [comment]
@Ayushrjt Yes, you can override the default cache folder using `CYPRESS_CACHE_FOLDER` by following the instructions here: https://on.cypress.io/installing-cypress#Binary-cache

**Comment by Ayushrjt** [comment]
Not able to get problem how to change.
u can see in screenshot final installation is in C:\Users\AXS06ZD\AppData\Local\Cypress\Cache\3.8.3\Cypress  now it works but after rebooting cypress is uninstalled and no cache is present at that path. So how and where i should select my path so that after rebooting no need to install cypress again.
![Screenshot (2)](https://user-images.githubusercontent.com/67945680/86887449-2c9ab880-c116-11ea-900f-df0ddd6c4039.png)

**Comment by jennifer-shehane** [comment]
It seems as if something on your system is clearing this data on reboot. Maybe something like Window Defender, that is deleting AppData? That or you're on a temporary profile where the profile data is deleted on each reboot. 

This does not appear to be an issue with Cypress, our program itself, so I will be closing this issue. We do not clear the cache path (without manually running `cypress cache clear`) and would have no way to do this on reboot.

**Comment by jennifer-shehane** [comment]
Someone else mentioned that their anti-virus software was deleting the Cypress `.exe` file - thought this may be a similar situation. https://github.com/cypress-io/cypress/issues/8228#issuecomment-671166126

**Comment by ivelin** [comment]
This happens in gitpod as well. Apparently gitpod does not keep around `/home/gitpod/.cache/Cypress/8.7.0/Cypress` on workspace restart.

**Comment by pleymor** [comment]
Solved it with with --force:

```
npm uninstall -D cypress -g
npm install cypress --save-dev
npx cypress install --force
```

**Comment by qaautomationengr** [comment]
Delete node_modules folder then run npm i. Works for me.

**Comment by raribencchi** [comment]
Im still getting this error even after installing cypress successfully. 
I ran below commands in sequence, but its not making any difference. 
npm uninstall -D cypress -g
npm install cypress --save-dev
npx cypress install --force

Then ran,' npm audit fix --force'   but not helpful. 

Ran 
npm audit -  to check the report.

# npm audit report
tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
fix available via `npm audit fix --force`
Will install tough-cookie@4.1.3, which is a breaking change
node_modules/tough-cookie
  @cypress/request  *
  Depends on vulnerable versions of tough-cookie
  node_modules/@cypress/request
    cypress  >=4.3.0
    Depends on vulnerable versions of @cypress/request
    node_modules/cypress

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Not sure how to stop this tough-cookie getting installed!

**Comment by MikeMcC399** [comment]
@raribencchi

```bash
npm audit fix --force
```

is not a good idea, as it will install a very old and legacy version of Cypress (`cypress@4.2.0`). It will also introduce many other security vulnerabilities. I would normally stay clear of using the `--force` option for `npm audit fix`.

To recover from that, delete the directory `node_modules`, then run:

```bash
npm install cypress@latest --save-dev --foreground-scripts
npx cypress verify
```

If that does not work then try:

```bash
npx cypress cache clear
npx cypress install
npx cypress verify
```

If that also does not work, then you could open a new issue or take your problem to the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

---

> Not sure how to stop this tough-cookie getting installed!

You can't get rid of the `tough-cookie` vulnerability. Cypress will need to look after that. If this vulnerability concerns you unduly, you could open a separate issue on that topic.

```text
npm ls tough-cookie
└─┬ cypress@12.17.0
  └─┬ @cypress/request@2.88.11
    └── tough-cookie@2.5.0
```

- Edit: No need for your action, as it has been logged separately in issue https://github.com/cypress-io/cypress/issues/27261
