### ISSUE TITLE
Not able to use cy.route() if application enable cache 

### ISSUE THREAD

**Issue by nikhilesh009** [cypress-io/cypress#7903]
not able to use cy.route while application using cache.
before i was able to wait for response by using this.

```js
cy.server()
cy.route('**/users').as('getUsers')
cy.visit('/users')
cy.wait('@getUsers')
```

but now it's not able to wait for a response 
![Screenshot 2020-07-07 at 11 43 23](https://user-images.githubusercontent.com/40767850/86763933-fbec4d80-c047-11ea-96fd-08ec97e37f55.png)
![Screenshot 2020-07-07 at 11 45 42](https://user-images.githubusercontent.com/40767850/86763940-fd1d7a80-c047-11ea-871c-a0ce99adcd43.png)
![Screenshot 2020-07-07 at 11 46 11](https://user-images.githubusercontent.com/40767850/86763944-fdb61100-c047-11ea-80f1-39fc45b7d0ed.png)

Cypress version 4.9
Electron, chrome

**Comment by jennifer-shehane** [comment]
- Can you be more specific about what you mean by 'enabling cache'?
- You're saying the XHR goes through but `cy.wait()` times out?

Ideally a reproducible example will be best, so that we can narrow down the issue ourselves. Can you provide one? Thanks!

**Comment by nikhilesh009** [comment]
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/40767850/87007697-f49d7f00-c1c2-11ea-885c-ee1ecf4bf93b.png)
Yes XHR goes through but its throwing timeout
in our application, before we didn't use the cache, so it was working fine, but we introduce this https://angular.io/guide/service-worker-config
and then test started throwing error

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? I wonder if disabling service workers would have some effect https://github.com/cypress-io/cypress/issues/702

**Comment by nikhilesh009** [comment]
i tried to find the reproducible app, but i couldn't able to find, :(
i was playing around, I figure it out if I unregister manually then i can see XHR route and it works as it supposes to be 
![Screenshot 2020-07-15 at 16 50 23](https://user-images.githubusercontent.com/40767850/87560186-7a399700-c6bb-11ea-9a04-b5af0b6c6dc6.png)
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/40767850/87561446-ff717b80-c6bc-11ea-8dd5-27ec04cb38f7.png)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. It'd be nice to have an example of why this is not working when Service Workers are enabled.

**Comment by nikhilesh009** [comment]
https://github.com/cypress-io/cypress/issues/702 that was the issue.
