### ISSUE TITLE
execute script outside the test

### ISSUE THREAD

**Issue by isklep** [cypress-io/cypress#7904]
How can I execute script outside the test??

For example I have Cypress.on in index.js

```js
Cypress.on('test:after:run', (test, runnable) => {
    if (test.state === 'failed') {
        const screenshotFileName = `${runnable.parent.title} -- ${test.title} (failed) (2).png`
        addContext({ test }, `screenshots/${Cypress.spec.name}/${screenshotFileName}`)
    }
})
```

and I have to run script after tests failed.

For example:
```js
Cypress.on('test:after:run', (test, runnable) => {
    if (test.state === 'failed') {
        runnable.exec('touch example.txt')
    }
})
```

but         

```js
runnable.exec('touch` example.txt')
```

throw exeption 

```
runnable.exec is not a function
``` 

but `runnable.skip()` works fine

**Comment by jennifer-shehane** [comment]
exec is not a function on `runnable` - `runnable` comes from Cypress internals directly, so you can only call available methods that exist on it. 

You won't be able to call any Cypress commands in a Cypress event listener, the things called within here will be called within the context of the browser. Likely you want this feature https://github.com/cypress-io/cypress/issues/6316

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
