### ISSUE TITLE
Mocha's growl dependency at v1.9.2 critical risk security vulnerability

### ISSUE THREAD

**Issue by nthurnau** [cypress-io/cypress#7908]
### Current behavior:
Hi folks, my organization uses [dependabot](https://dependabot.com/)to automatically create PRs for our dependencies. Cypress has `mocha@^2.2.5` as a dependency,  has `growl version 1.9.2` as a dependency. Dependabot alerted our repo as growl v1.9.2 has a [security vulnerability rating of critical](https://www.npmjs.com/advisories/146) and suggested upgrading to `growl at version 1.10.0` :
<img width="980" alt="Screen Shot 2020-07-07 at 10 34 09 AM" src="https://user-images.githubusercontent.com/16470390/86820448-effb8e00-c03d-11ea-9a1f-eed0bdc4c712.png">

Our yarn.lock file:
![Screen Shot 2020-07-07 at 10 43 08 AM](https://user-images.githubusercontent.com/16470390/86821006-b1b29e80-c03e-11ea-8880-1b4a6ce3de01.png)

Audit results:
```
yarn audit v1.22.4
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.10.2                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cypress-testrail-accumulative-reporter                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cypress-testrail-accumulative-reporter > mocha > growl       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/146                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.10.2                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cypress-testrail-reporter                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cypress-testrail-reporter > mocha > growl                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/146                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
```
Since this is a dependency of a dependency, we don't have the ability to upgrade ourselves. 

### Desired behavior:
Please upgrade mocha or mocha dependencies.

### Test code to reproduce
Install new version, check `growl` for version 1.10.0.

### Versions
Currently using Cypress v.^4.9.0

Thank you!

**Comment by jennifer-shehane** [comment]
This is a dependency of `cypress-testrail-reporter` and `cypress-testrail-accumulative-reporter` as listed in the audit results. So you also this installed on your project. 

You can see where a dependency comes from by printing `yarn why`, so `yarn why growl`. 

Please open this issue in their respective repo https://github.com/Vivify-Ideas/cypress-testrail-reporter
