### ISSUE TITLE
Cypress - Error opening runner page.

### ISSUE THREAD

**Issue by MiguelMorgado2** [cypress-io/cypress#7909]
Hi, i always opened the cypress runner without problems..

today i tried to open it as usual and gives back this error:

An unexpected error occurred

Error reading from: C:\Users\mmorga03\INEXTEND\cypress.json

SyntaxError: C:\Users\mmorga03\INEXTEND\cypress.json: Unexpected end of JSON input

![image](https://user-images.githubusercontent.com/67731557/86827985-93729000-c08a-11ea-96a5-f93355f014ae.png)

Can someone help please? thank you

**Comment by bahmutov** [comment]
@MiguelMorgado2 is your `cypress.json` file just an empty file? It should be a json file with at least `{}` inside

**Comment by MiguelMorgado2** [comment]
@bahmutov Ah yes.. my  cypress.json file was empty. im still a noob :) :) Thanks a lot sir.

I let it empty by accident. i was trying to create a command that allowed me to fill a random string. I do not have any idea how to do it and i really need it.

I cant find how to do it on the tutorials.. do you know how?

Thanks again.

**Comment by jennifer-shehane** [comment]
Check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
