### ISSUE TITLE
Replacing input not working correctly

### ISSUE THREAD

**Issue by Opalevanescence** [cypress-io/cypress#7911]
### Current behavior:

The code:
```js
cy.findByLabelText("Name")
  .clear()
  .wait(1)
  .type("q for sub-collection");
cy.findByText("q for sub-collection");
```

The result is almost always a value of "for sub-collection"

The test passes when I run it in the test window/with the test window open, but fails when I run it with the window closed.

### Desired behavior:

The value to be "q for sub-collection"

### Image:

<img width="1265" alt="Screen Shot 2020-07-07 at 4 02 56 PM" src="https://user-images.githubusercontent.com/58329466/86855769-e428bf80-c06f-11ea-95f2-fda1069fca74.png">

### Versions

operating on a mac in chrome with Cypress v 3.8.2

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the HTML/application code to run the provided tests against and we will consider reopening the issue.

**Comment by Opalevanescence** [comment]
I don't have an isolated instance to share (yet), but if you close the master branch of `https://github.com/metabase/metabase` and run `yarn run test-cypress-no-build --testFiles frontend/test/metabase-smoketest/admin_setup.cy.spec.js` the issue will pop up in the third to last `it` statement (`should view collections I have access to, but not ones that I don't (even with URL) as user`)

**Comment by jennifer-shehane** [comment]
Requires installing [Oracle JDK](https://www.oracle.com/java/technologies/javase-downloads.html)

Requires installing [Leininjen](https://leiningen.org/)

```
brew install leiningen
```

```
git clone https://github.com/metabase/metabase
cd metabase
yarn
yarn run test-cypress-no-build --testFiles frontend/test/metabase-smoketest
```

@Opalevanescence After this, the script fails waiting for backend. Can you please advise?

<img width="1536" alt="Screen Shot 2020-07-09 at 1 16 06 PM" src="https://user-images.githubusercontent.com/1271364/87006288-705cf300-c1e6-11ea-9d8c-b5b16104911c.png">

**Comment by Glinkis** [comment]
I also have an issue with `.type("...")` not actually typing the entire value into the field.

![image](https://user-images.githubusercontent.com/8037927/87137055-980e9280-c29c-11ea-8125-4458e58be58e.png)

**Comment by Opalevanescence** [comment]
@jennifer-shehane Do you have java installed on your computer? The following instructions should get it up and running.
<img width="844" alt="Screen Shot 2020-07-10 at 8 53 21 AM" src="https://user-images.githubusercontent.com/58329466/87173563-d13e0700-c28a-11ea-9d8e-57a430b3b818.png">

**Comment by jennifer-shehane** [comment]
I have java installed and followed the instructions. I don't understand where to go from here - how this relates to running your dev environment to get the tests running.

**Comment by Opalevanescence** [comment]
Java is for the backend to build the uberjar.
Are you still hitting the same issue?

**Comment by jennifer-shehane** [comment]
Yes
