### ISSUE TITLE
Feature Request: adding a scrollRelativeTo() action or an option to ScrollTo() for relative scrolling.

### ISSUE THREAD

**Issue by JohnMCrooks** [cypress-io/cypress#7914]
### Current behavior:
Currently, When a user uses `cy.scrollTo( x, y )` the coordinates are taken as an absolute position on the page in which to go to regardless of your current position.

ex: `cy.scrollTo(0px, 200px)` will take the user to the absolute position (x: 0, y: 200) no matter where they currently are on the web page. This is great when you know exactly where you need to scroll to. If you don't, it adds overhead of having to calculate element positions and determine necessary coordinates for precise scrolling. 

### Desired behavior:

Create another method like `scrollRelativeTo()` or maybe add an option to pass into `scrollTo( x, y, {relative: 'true' })` to allow relative scrolling behavior. 

Example: If I call `cy.get('.some-selector')` I am taken to the absolute coordinates  (x: 0, y: 1000) for an element.  From this position I want to scroll down another 150 pixels to a position that doesn't correlate directly to any particular element. I could then call `cy.scrollRelativeTo( 0px, 150px )` ~OR~ `cy.scrollTo( 0px, 150px, { relative-scroll: 'true' })` then said call would deliver me to the absolute coordinates (x: 0, y: 1150).

**Comment by jennifer-shehane** [comment]
@JohnMCrooks You can do this with the `offset` option of `scrollIntoView`. 

```js
it('scrolls', () => {
  cy.visit('https://example.cypress.io/commands/actions')

  // scroll 150 pixels down from the #scrollTo element
  cy.get('#scrollTo').scrollIntoView({ offset: { top: 150, left: 0 }})
})
```
