### ISSUE TITLE
Syntax error, unrecognized expression: Date/Time

### ISSUE THREAD

**Issue by testerncoder** [cypress-io/cypress#7916]
# Current behavior:
Getting error : Syntax error, unrecognized expression: Date/Time

### Desired behavior:
It should consider 'Date/Time' as text/string.

### Test code to reproduce
Code:
```js
    cy.get('td>a')
      .contains('nrtuser')
      .then(elem => {
        const alltrs = elem.parentsUntil('tbody').siblings()
        alltrs.nextUntil('Date/Time')
```

HTML:
![image](https://user-images.githubusercontent.com/30372207/86876312-0ec35880-c102-11ea-8645-d69598fe0461.png)

![image](https://user-images.githubusercontent.com/30372207/86876502-83969280-c102-11ea-9098-b6e79d5d4a02.png)

### Versions
"cypress": "^4.6.0",
Browser: chrome
OS: windows 10

**Comment by jennifer-shehane** [comment]
You're calling into jQuery's `nextUntil` method. This method accepts a valid selector or jQuery element, not a string of the content you are looking for. This is why jQuery does not recognize the `Date/Time` as a selector or element. https://api.jquery.com/nextuntil/
