### ISSUE TITLE
how can I wait for some db status?

### ISSUE THREAD

**Issue by ycwdaaaa** [cypress-io/cypress#7919]
I have some batch job need to wait to complete in my testing. so I need to use the for or while to select db every 10s. like below:

```js
cy.get('.el-table__row > .el-table_6_column_40 > .cell')
  .then(($id) => {
    jobId = $id.text();
    console.log(`job id is : ${jobId}`);
    let startTime = new Date().getTime();
    let currentStatus = "0";

    for (let i = 0; i < 1000; i++) {
      cy.wait(10000);
      if (new Date().getTime() - startTime > timeout) {
        break;
      }
      cy.task('queryDb', `select status from push_user_set_job where id = ${jobId}`)
        .then((results) => {
          currentStatus = results[0].status;
          console.log(`等待任务执行, 当前任务状态为：${currentStatus}， 期望状态为${expectStatus.valueOf()}`);
        });
      console.log(currentStatus + "    " + expectStatus.valueOf());
      if (currentStatus === JobStatus.FAILED.valueOf() || currentStatus === expectStatus.valueOf()) {
        break;
      }
    }

    cy.wrap(currentStatus).should('be.eq', expectStatus.valueOf())
  });
```

it does not work. its every strange .
![image](https://user-images.githubusercontent.com/18463029/86916905-dbf77f80-c156-11ea-8e88-12a0ea0fdc35.png)

it print the result 1000 times first.  so what happend?

**Comment by jennifer-shehane** [comment]
In the example given, you're mixing async (Cypress comands) and synchonous code (the console.log outside of the `cy.task()`. The synchonous console.log will log the results immediately - not waiting for the cy.task for any Cypress commands to run, so it will log 0 1 before those run. 

I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).
