### ISSUE TITLE
Getting an aborted status out of a valid url

### ISSUE THREAD

**Issue by VickoLand** [cypress-io/cypress#7924]
### Current behavior:
Trying to run a test that removes the target attribute of a node so that the page that was originally supposed to load in a new tab, will load in the current browser tag 

I'm getting an "aborted" status in the GET request

![Screen Shot 2020-07-07 at 17 54 26](https://user-images.githubusercontent.com/61845924/86966329-5d431800-c13f-11ea-9ac1-c53b362aa30f.png)

### Desired behavior:

I should ideally be getting a 200 response with the GET request

![Screen Shot 2020-07-07 at 17 54 57](https://user-images.githubusercontent.com/61845924/86966348-66cc8000-c13f-11ea-912e-67d1df241426.png)

### Test code to reproduce
```js
describe('My Third Test Suite', function(){
    it('Alerts Test Case', function(){
        cy.visit('https://rahulshettyacademy.com/AutomationPractice/');
        //alert handling
        cy.get('#alertbtn').click();
        cy.get('#confirmbtn').click();
        cy.on('window:alert', (str) => {
            expect(str).to.equal('Hello , share this practice page and share your knowledge');
        })
        cy.on('window:confirm', (str) => {
            expect(str).to.equal('Hello , Are you sure you want to confirm?');
            return false;
        })

        //use jquery to handle browser child tabs
        cy.get('#opentab').invoke('removeAttr', 'target').click();
    })
})
```

### Versions

cypress version: latest npm install
OS: MacOS Mojave
Browser: Chrome 83

**Comment by jennifer-shehane** [comment]
Cypress reflects the state of the XHR requests as they occur in your application. When the browser navigates to the `https://www.rahulshettyacademy.com/` url (as it does in your test), there are aborted XHR requests. You can see this normally in the Chrome browser by just visiting `https://www.rahulshettyacademy.com/`. 

**Cypress shows XHR requests as aborted as they are**

<img width="1180" alt="Screen Shot 2020-07-09 at 9 53 44 AM" src="https://user-images.githubusercontent.com/1271364/86993658-907eb900-c1ca-11ea-84ad-3abba9bb2461.png">

**These XHR requests are aborted normally outside of Cypress**

![Screen Shot 2020-07-09 at 9 55 36 AM](https://user-images.githubusercontent.com/1271364/86993676-9bd1e480-c1ca-11ea-8315-3236064cfcb5.png)
