### ISSUE TITLE
Visit command does not call the onBeforeLoad function

### ISSUE THREAD

**Issue by delomer** [cypress-io/cypress#7933]
### Current behavior:
onBeforeLoad does not working!

this example:
```javascript
it('onload', function() {
  cy.on('window:before:load', e => {
    console.log('window:before:load');
  });

  cy.on('window:load', e => {
    console.log('window:load');
  });

  cy.visit('/', {
    onBeforeLoad(win) {
      console.log('onBeforeLoad');
    },
    onLoad(win) {
      console.log('onLoad');
    }
  });
});
```
Produces this logs:
> window:load
> onLoad

### Desired behavior:
the onLoadBefore callbacks are not called, this logs are missing:
> window:before:load
> onBeforeLoad

### Test code to reproduce
see example above

### Versions
Cypress version: 4.5.0
Browser: Chrome 83
OS: Windows 10 Enterprise, Version 1709

**Comment by jennifer-shehane** [comment]
I'm not seeing this behavior in 4.10.0 (or 4.5.0). 

Perhaps this is relevant to the application you are testing? Can you provide a fully reproducible example?

<img width="671" alt="Screen Shot 2020-07-10 at 12 47 11 PM" src="https://user-images.githubusercontent.com/1271364/87122777-8e405b80-c2ab-11ea-9f25-4f11059ef54a.png">

**Comment by delomer** [comment]
You are right, my app uses a service-worker and i think if the app is loaded from cache no onLoadBefore event is firing!
When i cancel all already runnig registrations before the test is running the onLoadBefore event is firing.

My updated spec now looks like this and every thing works like expected:
```javascript
describe('test', () => {
  beforeEach(() => {
   // remove already running service-worker registrations
    if (window.navigator && navigator.serviceWorker) {
      navigator.serviceWorker.getRegistrations().then(registrations => {
        registrations.forEach(registration => {
          registration.unregister();
        });
      });
    }
  });

  it('onload', function() {
    cy.on('window:before:load', e => {
      console.log('window:before:load');
    });

    cy.on('window:load', e => {
      console.log('window:load');
    });

    cy.visit('/', {
      onBeforeLoad(win) {
        console.log('onBeforeLoad');
        // prevent new service-worker registrations
        // https://glebbahmutov.com/blog/cypress-tips-and-tricks/#disable-serviceworker
        delete win.navigator.__proto__.serviceWorker;
      },
      onLoad(win) {
        console.log('onLoad');
      }
    });
  });
});
```

**Comment by jennifer-shehane** [comment]
See #702
