### ISSUE TITLE
Backend Adapters

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress#794]
While Cypress does provide documentation on [testing your app](https://on.cypress.io/testing-your-app), there are times when you need to interact with the backend at a deeper level. 

| Language | Repo | Status |
|---|---|---|
| Ruby | [cypress-adapter-ruby](https://github.com/cypress-io/cypress-adapter-ruby) | | 
| Node | [cypress-adapter-node](https://github.com/cypress-io/cypress-adapter-node) | | 
| Python | [cypress-adapter-python](https://github.com/cypress-io/cypress-adapter-python) 
| PHP | [cypress-adapter-php](https://github.com/cypress-io/cypress-adapter-php)
| .NET | [cypress-adapter-dotnet](https://github.com/cypress-io/cypress-adapter-dotnet)

**Comment by airhorns** [comment]
Are these still a planned feature for cypress or are you folks advocating people make custom endpoints to build integrations?

**Comment by Kondasamy** [comment]
Do we have any plans to implement these adapters?

**Comment by jennifer-shehane** [comment]
@Kondasamy No work has been done on this feature. It is still a proposal.

**Comment by idxn** [comment]
I vote for this and would like to see it in the roadmap

**Comment by cmsax** [comment]
There's no need to build adapter, because `Cypress` is a test runner for `Javascript` based projects with `Chrome` or `Electron` as backend browser environment. `Cypress` itself just makes it easy to launch a browser and encapsulate browsers' API for you to automatically test projects. `Chrome` | `Edge` | `Firefox` driver is enough.

**Comment by WTK** [comment]
What does that mean in practice though? If I'd like to write cypress.io tests in python would that be an option?

I imagine that one way it could be handled is via python code with similar api to cypress, code that is simply used to generate valid Javascript in the background and run it using usual cypress tools.

**Comment by Ambro17** [comment]
Is there any news on python adapter? I would like to help as cypress seems to be a great tool and python syntax may really help to increase tests readibility/maintenance

**Comment by cypress-zh** [comment]
Do u guys have any solution on how to convert cypress js APIs to python version? I'm so interested in this contribution.

**Comment by WTK** [comment]
I was personally thinking using something like https://github.com/QQuick/Transcript to have an intermediate step of converting python to js and then running it as usual.

Either that or creating a python adapter that would generate compatible spec js files on the fly. Cypress api is rather small, it would be semi easy to create a python code that translates to individual cypress calls.

**Comment by Vinerhugo** [comment]
Ainda estou no aguardo do cypress-adaptor-python seria de extrema ajuda, não estou conseguindo tirar o coverage dos meus testes cypress no meu backend python

**Comment by Ambro17** [comment]
For anyone looking for a testing framework with first-class support for python you can look at [playwright-python](https://github.com/microsoft/playwright-python)
It is maintained by microsoft so support should be guaranteed

**Comment by Vinerhugo** [comment]
My friend i need integration my code cypress and my back-end Python, you can help-me ?


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Ambro <notifications@github.com>
Enviado: terça-feira, 25 de agosto de 2020 15:17
Para: cypress-io/cypress <cypress@noreply.github.com>
Cc: Vinerhugo <vinerhugo@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [cypress-io/cypress] Backend Adapters (#794)


For anyone looking for a testing framework with first-class support for python you can look at playwright-python<https://github.com/microsoft/playwright-python>
It is maintained by microsoft so support should be guaranteed

**Comment by jennifer-shehane** [comment]
Closing as this is no longer under consideration to extend our products in this manner to support backend adapters.

**Comment by Ambro17** [comment]
Thank you @jennifer-shehane for resolution. Is there any link where we can read about the reasons behind the decision?
