### ISSUE TITLE
Add "overwrite" Option to cy.screenshot()

### ISSUE THREAD

**Issue by einfallstoll** [cypress-io/cypress#7955]
`cy.screenshot()` should add an option `overwrite` to overwrite existing screenshots.

**Comment by jennifer-shehane** [comment]
You could write this logic yourself as a workaround using the `after:screenshot` event documented here: https://on.cypress.io/after-screenshot-api

**Comment by EmaSuriano** [comment]
Hello, came up with a simple snippet that might help more people looking at the same problem.

``` javascript
const { renameSync } = require('fs');

module.exports = (on, config) => {
  on('after:screenshot', ({ path }) => {
    renameSync(path, path.replace(/ \(\d*\)/i, ''));
  });

  return config;
};
```

It uses a regex that will remove any `(number)` from the name of the images, making them work as singleton 👍

**Comment by kinoli** [comment]
This issue is also happening when my app downloads a file. The files never get removed from the downloads folder. Currently my cypress downloads folder has 60 files in it. Would love to see this fixed.
