### ISSUE TITLE
Timeout option not respected for .should('not.exist')

### ISSUE THREAD

**Issue by Nate-Wessel** [cypress-io/cypress#7957]
### Current behavior:
I am trying to wait patiently for an element to appear in and then disappear from the DOM. I pass a large custom timeout option to `should`, e.g. `... .should('not.exist',{timeout:120000})`. 
After a few seconds it fails and declares that the element has continuously existed, even though I told it to wait two minutes before giving up. 

### Desired behavior:

The timeout parameter should be respected. 

### Versions
Cypress 4.7.0
Ubuntu 20.04
Electron 80

**Comment by ChiuWeiBin** [comment]
Hi Nate-Wessel, 

Kindly refer to [here](https://docs.cypress.io/api/commands/should.html#Timeouts).

**Comment by jennifer-shehane** [comment]
Yes, as mentioned in the comment above, `.should()` does not accept a `timeout` option (or any options for that matter). The `timeout` should be passed to the Cypress command chained beefore the `.should()` command. 

```js
cy.get('div', { timeout: 1200000 }).should('not.exist')
```
