### ISSUE TITLE
./node_modules/.bin/cypress run error

### ISSUE THREAD

**Issue by leenItg** [cypress-io/cypress#7958]

**Comment by leenItg** [comment]
./node_modules/.bin/cypress : File C:\Users\pc corner\OneDrive\Desktop\myCypress\node_modules\.bin\cypress.ps1 cannot be loaded because 
running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ./node_modules/.bin/cypress run

**Comment by leenItg** [comment]
i have this error

**Comment by jennifer-shehane** [comment]
This is not an issue related to Cypress as a product. I suggest reading about the execution policies linked in the error at https:/go.microsoft.com/fwlink/?LinkID=135170 or googling to see how to execute scripts on your OS.
