### ISSUE TITLE
[Plugin] Cannot set property of undefined

### ISSUE THREAD

**Issue by jmsansan** [cypress-io/cypress#7959]
### Current behavior:
On cypress startup, it throws "Cannot set property [key] of undefined" error when modifying config from plugin.
This happens when setting a new object property to config on plugins. 

### Desired behavior:
Cypress startup properly and loads config on plugins.

### Test code to reproduce
add code to **/plugins/index.js** file and start cypress

```js
module.exports = (on, config) => {
  config.test = { foo: 'bar' }; // Fails
  config.test2 = "foobar"; // Pass
  config.test3 = { foo: {bar: "baz"} }; // Fails
  config.test4 = ["foo", "bar", "baz"]; // Pass
  return config;
};
```

### Versions
Cypress: 4.10.0 
OS: Manjaro/Arc linux

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-115) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
In terms of what 'fail' means here, the pluginsFile throws an error upon opening. 

```js
module.exports = (on, config) => {
  config.test = { foo: 'bar' }; // Fails
  return config;
};
```

<img width="407" alt="Screen Shot 2020-07-14 at 1 11 25 PM" src="https://user-images.githubusercontent.com/1271364/87393023-89ddb080-c5d3-11ea-9159-2f5cf526518b.png">


```js
module.exports = (on, config) => {
  config.test.foo = 'bar'; // Fails
  return config;
};
```

<img width="917" alt="Screen Shot 2020-07-14 at 1 11 43 PM" src="https://user-images.githubusercontent.com/1271364/87393069-9cf08080-c5d3-11ea-82f8-25ccda3c86a1.png">

```js
module.exports = (on, config) => {
  config.test3 = { foo: { bar: "baz" } }; // Fails
  return config;
};
```

<img width="356" alt="Screen Shot 2020-07-14 at 1 12 13 PM" src="https://user-images.githubusercontent.com/1271364/87393101-ac6fc980-c5d3-11ea-8298-cc41363a356a.png">
