### ISSUE TITLE
Xvfb issue on centOS 7.8 cannot start Cypress 

### ISSUE THREAD

**Issue by erangeles** [cypress-io/cypress#7961]
### Current behavior: 
When I first install and run cypress I get an error. I am running concurrently and my command looks like this `concurrently "npm run start" "cypress run --browser chrome --headless"`

![Screen Shot 2020-07-13 at 10 26 08 AM](https://user-images.githubusercontent.com/13124163/87322654-4744a700-c4f3-11ea-9301-fd9bd1fe5efa.png)
### Desired behavior:
I should be able to run cypress successfully.

### Test code to reproduce

N/A
### Versions

Platform: linux (CentOS - 7.8.2003) (minimal image) 
Cypress Version: 4.10.0

**Comment by jennifer-shehane** [comment]
Make sure you have our dependencies installed correctly. https://on.cypress.io/installing-cypress.html#Linux

I don't see how this is an issue specifically with Cypress but seems to be an issue with the xvfb, dependencies, or permissions on your system.
