### ISSUE TITLE
"The snapshot is missing. Displaying current state of the DOM." error showing up on every test.

### ISSUE THREAD

**Issue by Mat-Longinow** [cypress-io/cypress#7964]
### Current behavior:
Every time I run a test I can't look back at the snapshots. I just get the error:

![Screen Shot 2020-07-10 at 3 09 37 PM](https://user-images.githubusercontent.com/6404079/87336842-5a597600-c4f7-11ea-98c1-188fd1f674be.png)

Screen Recording --> https://www.loom.com/share/e697085e66c946beaac4098f0d4c634f

I have tried restarting Cypress, restarting my computer. Nothing.

The only thing I did recently was to set `"numTestsKeptInMemory": 0` in my `cypress.json` due to high RAM usage on my machine. But even with this, I tried changing the amount to 1, in case I was screwing this up myself, but still no change.

### Desired behavior:

Snapshots are incredibly helpful for me as I debug things and write successful tests, so not having the snapshots at all is a pretty big hindrance, I would very much like them back 😬

### Test code to reproduce

Not sure what code to share for this one...

### Versions

MacOS Catalina 10.15.4
Cypress 4.3.0

**Comment by jennifer-shehane** [comment]
`numTestsKeptInMemory` settings as described in the docs. https://on.cypress.io/configuration#Global

>The number of tests for which snapshots and command data are kept in memory. Reduce this number if you are experiencing high memory consumption in your browser during a test run.

If this is set to `0`, then snapshots will never be available as we are not saving the memory data for snapshots. 

If this is set to `1`, you would only have snapshots available for the 1 test, aka the last test ran. All other snapshots would be unavailable.

**Comment by Mat-Longinow** [comment]
Ah, thank you for clarifying @jennifer-shehane.

**Comment by andrasferenczi** [comment]
@jennifer-shehane it seems that the correct description for this number would be:

> Max number of consecutive tests to keep in memory that were tested against the same domain.

Even though this number is 50 (default), it does not show the snapshots from `localhost:8025`, if the test after it was done on `localhost:3000`

**Comment by jennifer-shehane** [comment]
@andrasferenczi Yah, that is accurate since we don't have multidomain support in a single test - that will be a part of the work for that feature, to maintain snapshots across multi-domains and iframes. https://github.com/cypress-io/cypress/issues/944
