### ISSUE TITLE
Hitting TypeError: Cannot read property 'browser' of undefined and other errors

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7968]
Cypress v4.10.0 and `develop` branch

* cloned https://github.com/bahmutov/cypress-react-unit-test (I have seen these bugs happen in other projects too)
* installed dependencies there (`yarn`)
* build the files (`yarn build`)
* opened project from `cypress` monorepo

```
$ yarn dev --project ~/git/cypress-react-unit-test
```

* opened a spec, for example `cypress/component/advanced/mocking-axios/1-users.spec.js`

The spec runs fine (I suggest keeping DevTools open)

![](https://user-images.githubusercontent.com/2212006/87346362-90125500-c51f-11ea-95b3-2e3078942128.png)

* now hit the "Run All Tests" button multiple times quickly

![](https://user-images.githubusercontent.com/2212006/87346432-af10e700-c51f-11ea-83e8-8941cb6d7871.png)

And get pretty quickly to errors in the DevTools, sometimes the tests are hanging, sometimes they fail

## first error: normalizeAll
![](https://user-images.githubusercontent.com/2212006/87346523-cea80f80-c51f-11ea-85f3-aeb944573ad0.png)

Code

![](https://user-images.githubusercontent.com/2212006/87346631-e7b0c080-c51f-11ea-9ed8-2c395f8d3114.png)

## second error: stop
![](https://user-images.githubusercontent.com/2212006/87346695-feefae00-c51f-11ea-8be0-cfa632a3a562.png)

## third error: Cannot read property 'browser' of undefined
![](https://user-images.githubusercontent.com/2212006/87346821-2e061f80-c520-11ea-9f0e-efaf440a8029.png)

Code

![](https://user-images.githubusercontent.com/2212006/87346838-352d2d80-c520-11ea-9a1f-be7ffd92cf5b.png)

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-109) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Yah, I was able to reproduce the `normalizeAll` error, but didn't see the ones after. Added the `build` step since that was missing from descriptions.

**Comment by bahmutov** [comment]
Here is a screen recording where I am just hitting the button at different speeds and getting all 3 errors one after another.

https://www.dropbox.com/s/5o0c1ecl9uzk0fj/three-amigos.mp4?dl=0

**Comment by bahmutov** [comment]
Bonus: I could even get browser error that claimed _it was from the application code_

<img width="1279" alt="Screen Shot 2020-07-14 at 8 33 12 PM" src="https://user-images.githubusercontent.com/2212006/87489553-51f55e00-c611-11ea-9b8d-67b3d8a75e9e.png">

or

<img width="1278" alt="Screen Shot 2020-07-14 at 8 34 12 PM" src="https://user-images.githubusercontent.com/2212006/87489594-6a657880-c611-11ea-92e0-9c3fc2f73a17.png">

**Comment by jennifer-shehane** [comment]
oh yah, there are some misattributions of where errors comes from that I've seen. 😕
