### ISSUE TITLE
Pop up does not show up

### ISSUE THREAD

**Issue by OlenaVakulenko** [cypress-io/cypress#7979]
### Current behavior:

I am practicing automation with Cypress on http://automationpractice.com

On the page http://automationpractice.com/index.php?id_product=1&controller=product when Cypress clicks on element with selector '#bigpic' nothing happens.
![image](https://user-images.githubusercontent.com/14077302/87430208-8f47f480-c5ed-11ea-964c-672ff54d3152.png)

When I click the element manually, the pop up is shown.

![image](https://user-images.githubusercontent.com/14077302/87430334-bbfc0c00-c5ed-11ea-96e8-7cc7e0dfff5d.png)

### Desired behavior:

After click on '#bigpic' the pop-up is displayed

### Test code to reproduce

```js
context('Full size', () => {
        beforeEach(() => {
            cy.visit('http://automationpractice.com/index.php?id_product=1&controller=product')
        })

        it('Show full size', () => {
            cy.get('#bigpic').click()
        })
    })
```

### Versions

cypress 4.8.0,
Chrome 83, Firefox 77
Windows 8.1

**Comment by OlenaVakulenko** [comment]
I've tried to:
- click on other elements within `#image-block`
- click with option {force:true}
- `cy.wait(5000)` in case the pop up is slow
- `cy.get(pop-up).invoke('show')` to show the pop-up
- disabling listening to `uncaught:exception`
but nothing worked for me

**Comment by panzarino** [comment]
Seems to be working for me with Cypress 4.8.0. Can you provide any additional information?

![ezgif-6-df08cc9bb2c7](https://user-images.githubusercontent.com/7033952/87441711-67db3280-c5c1-11ea-96ca-6531cdeca0dd.gif)

**Comment by OlenaVakulenko** [comment]
This is strange. By the way I've upgraded to cypress 4.10.0, but it didn't help either.
I've noticed, that the problem is not only in the pop-up. Some other thing also don't work (like clicking on the color picker does not add '/color-orange' to the URL).

I think, the problem might not be in cypress as I see the errors in console while running the tests:
```
Uncaught TypeError: The following error originated from your application code, not from Cypress.

  > Illegal invocation

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    at HTMLDocument.<anonymous> (product.js (original):167)
    at j (jquery-1.11.0.min.js (original):2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js (original):2)
    at Function.ready (jquery-1.11.0.min.js (original):2)
    at HTMLDocument.K (jquery-1.11.0.min.js (original):2)
(anonymous) @ product.js (original):167
j @ jquery-1.11.0.min.js (original):2
fireWith @ jquery-1.11.0.min.js (original):2
ready @ jquery-1.11.0.min.js (original):2
K @ jquery-1.11.0.min.js (original):2
```
![image](https://user-images.githubusercontent.com/14077302/87529610-eacebc80-c697-11ea-9554-2896464bf98b.png)

But the strange thing is that there are no errors when the same browser (Chrome, Firefox) is run directly from the OS (not the cypress test runner) and in this case everything is functioning correctly (all clicks perform necessary actions).

**Comment by panzarino** [comment]
Perhaps you can try running the same tests on a clean install of Cypress. It's also possible that something else in your test suite or configuration could be causing the issue, so try to see if you can narrow down what might be causing it and provide more information on how we can reproduce the issue.

**Comment by OlenaVakulenko** [comment]
Ok, you were right. The issue is not reproduced on the new project.
To reproduce the issue you have to add the following code to `cypress.json`
`"experimentalSourceRewriting": true`

Note, that this option was added by me in the initial project because I faced the issue https://github.com/cypress-io/cypress/issues/7402 and this solution worked for me.

**Comment by jennifer-shehane** [comment]
I'm able to reproduce this with `"experimentalSourceRewriting": true` 

`spec.js`

```js
it('Show full size', () => {
  cy.visit('http://automationpractice.com/index.php?id_product=1&controller=product')
  cy.get('#bigpic').click()
})
```

`cypress.json`

```json
{
  "experimentalSourceRewriting": true
}
```

There's a point in your application where you are assigning something to `window.location`. 

<img width="509" alt="Screen Shot 2020-07-21 at 2 24 54 PM" src="https://user-images.githubusercontent.com/1271364/88027946-fde10100-cb5d-11ea-879a-b18515f8cd5f.png">

This is triggering the `resolveWindowReference` method from within Cypress. This call seems to be throwing an Illegal invocation error. 

<img width="724" alt="Screen Shot 2020-07-21 at 2 25 56 PM" src="https://user-images.githubusercontent.com/1271364/88028059-2668fb00-cb5e-11ea-9342-b5fc2c974bbf.png">
