### ISSUE TITLE
Cannot override Cypress environment variables

### ISSUE THREAD

**Issue by bugzpodder** [cypress-io/cypress#798]
- Operating System: macOS
- Cypress Version: 1.0.2
- Browser Version: Chrome

### Is this a Feature or Bug?
Bug

### Current behavior:
Cypress cannot load environments from two of the four methods described in the doc:
https://docs.cypress.io/guides/guides/environment-variables.html
Option 1 and Option 3 works fine.  Option 2 and Option 4 doesn't work (only tested on baseUrl).
cypress.json 
{}
cypress.env.json (no effect)
{
  "baseUrl": "http://localhost:3000"
}

CYPRESS_baseUrl=http://localhost:3000 ./node_modules/.bin/cypress run (works as expected)

cypress run --env baseUrl=http://localhost:3000 (did not work)

### Desired behavior:
All four methods work.

### How to reproduce:
specify --env or use cypress.env.json

**Comment by brian-mann** [comment]
Thank you for opening a comprehensive issue.

We'll take a look but there are a ton of tests around this in various places that express all 4 ways of setting environment variables.

For instance here is one:

https://github.com/cypress-io/cypress/blob/develop/packages/server/test/integration/cypress_spec.coffee#L673

**Comment by bugzpodder** [comment]
It turns out that baseUrl is a config variable, not an environment variable.
https://docs.cypress.io/guides/references/configuration.html
one needed to specify --config in CLI rather than --env.
