### ISSUE TITLE
Flaky internal test: offsetTop error

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#7985]
### Current behavior:

`Cannot read property 'offsetTop' of null` error happens on Chrome and Electron.

[Link 1](https://app.circleci.com/pipelines/github/cypress-io/cypress/12329/workflows/41ae1df2-54c9-466d-a6aa-6fed94430e26/jobs/394189/steps)

[Link 2](https://app.circleci.com/pipelines/github/cypress-io/cypress/12326/workflows/f7762876-613b-4dbb-badd-5b6803126a42/jobs/394009/steps)

[Link 3](https://app.circleci.com/pipelines/github/cypress-io/cypress/12314/workflows/5dd5c1d6-a1b4-4d53-b7b2-6c897baa808f/jobs/393439/steps)

**Failed Test File:** https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/3_runnable_execution_spec.ts

### Desired behavior:

Test should not be flaky.

### Test code to reproduce

N/A

### Versions

Cypress 4.10.0+

**Comment by jennifer-shehane** [comment]
Oh, I fixed this! Pulling from Ben's fix in another PR. https://github.com/cypress-io/cypress/pull/7987
