### ISSUE TITLE
cy.screenshot does not waiting for animation

### ISSUE THREAD

**Issue by eduardocalixtoviasoft** [cypress-io/cypress#7991]
### Current behavior:
During `cy.screenshot`, image generated has difference due to animation

### Desired behavior:
`cy.screenshot` waits for animations to be resolved to make a screenshot.

### Test code to reproduce
Created a [Repo](https://github.com/eduardocalixtoviasoft/cypress-animation-testing) for this bug too, in this case using Angular Material 9.1 version and sidenav animation for the test. It first click a button that opens the sidenav then makes a screenshot.

### Versions
Cypress: 4.10.0
Angular Version: 9.1.9
Browser: Chrome v83.0

**Comment by jennifer-shehane** [comment]
In this case, there are zero expectations written in that would assure the screenshot is taken *after* the animation takes place. The screenshot runs directly after the last assertion ran. So if the animation is mid-animation - it will be taken mid-animation. `cy.screenshot()` is not aware of all of the animations on your page nor would it know how you want the state of the DOM to be when you take a screenshot.

You need to ensure that the animation is complete and the state of the DOM is how you want it **before** calling the `cy.screenshot()` to make sure your tests are not written in a way that introduces flake. Something like below ensures the test is not flaky.

```js
context('Animations', () => {
  it('open-sidenav-using-matchImageSnapshot', () => {
    cy.visit('http://localhost:4200/');
    cy.get('.mat-drawer-opened').should('not.exist')
    cy.get('#open-sidenav').click();
    cy.get('.mat-drawer-opened')
    // matchImageSnapshot: gets a diff from initial image and test image
    cy.matchImageSnapshot('test-open-sidenav');
  });
  
  it('open-sidenav-using-screenshot', () => {
    cy.visit('http://localhost:4200/');
    cy.get('.mat-drawer-opened').should('not.exist')
    cy.get('#open-sidenav').click();
    cy.get('.mat-drawer-opened')
    // This screenshot should wait all animations to end, right?
    cy.screenshot('test-open-sidenav-screenshot');
  });
})
```

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
