### ISSUE TITLE
ISO-8859 characters handled different when chromeWebSecurity is disabled

### ISSUE THREAD

**Issue by fabianMendez** [cypress-io/cypress#7996]
### Current behavior:

If the response content has ISO-8859 encoding (windows 1252) the page renders correctly if `chromeWebSecurity` is enabled (by default)

![image](https://user-images.githubusercontent.com/32204060/87613144-12427b00-c6d2-11ea-8567-2bff427be814.png)

But if `chromeWebSecurity` is false then the characters are shown different:
![image](https://user-images.githubusercontent.com/32204060/87613211-461da080-c6d2-11ea-93cf-65efa1c9d811.png)

### Desired behavior:

ISO-8859 encoded characters are handled the same independent of the `chromeWebSecurity` config

### Test code to reproduce

```bash
## In a temp dir

## <h1>ñ</h1>
echo -n "PGgxPvE8L2gxPg==" | base64 -d > test.html
python3 -m http.server &

echo {} > cypress.json
mkdir -p cypress/integration

cat << EOF > cypress/integration/spec.js
it('Show ISO-8859 characters correctly', () => {
	cy.visit('http://localhost:8000/test.html')
	cy.contains('ñ', { timeout: 0 })
})
EOF

## Passes
npx cypress run -s $(pwd)/cypress/integration/spec.js -q

## Fails
npx cypress run -s $(pwd)/cypress/integration/spec.js -q -c chromeWebSecurity=false

fg # ^c
```

### Versions

Cypress: 4.10.0
OS: OS: Ubuntu 20.04
Browsers: chrome and electron

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce this using `cypress run` with `chromeWebSecurity` set to `false` on MacOS with the example with iso88591 encoding or windows1252 encoding. 

We previously had an issue with this here: https://github.com/cypress-io/cypress/pull/4698 that may shed some light on this.

@fabianMendez Any ideas why this would break for you and not me?

<img width="480" alt="Screen Shot 2020-07-16 at 3 20 44 PM" src="https://user-images.githubusercontent.com/1271364/87650835-483a3a80-c778-11ea-9910-2e8608c0aebd.png">

<img width="808" alt="Screen Shot 2020-07-16 at 3 23 25 PM" src="https://user-images.githubusercontent.com/1271364/87650853-4ff9df00-c778-11ea-8e8f-6d97413e5420.png">

**Comment by fabianMendez** [comment]
Thanks for your quick response @jennifer-shehane

I am going to test it on a docker container just to confirm is not my current environment.

**Comment by fabianMendez** [comment]
Running the same set of commands inside `cypress/base:12.14.1` yields the same results:

```
 $ docker run --rm -it cypress/base:12.14.1 bash                                                                                                                         1 ↵
root@5e09ba505e99:/# echo -n "PGgxPvE8L2gxPg==" | base64 -d > test.html
root@5e09ba505e99:/# python3 -m http.server &
[1] 9
root@5e09ba505e99:/# Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
echo {} > cypress.json
root@5e09ba505e99:/# mkdir -p cypress/integration
root@5e09ba505e99:/# cat << EOF > cypress/integration/spec.js
> it('Show ISO-8859 characters correctly', () => {
> cy.visit('http://localhost:8000/test.html')
> cy.contains('ñ', { timeout: 0 })
> })
> EOF
root@5e09ba505e99:/# npx cypress run -s $(pwd)/cypress/integration/spec.js -q
  ✔  Verified Cypress! /root/.cache/Cypress/4.10.0/Cypress


127.0.0.1 - - [16/Jul/2020 12:40:57] "GET /test.html HTTP/1.1" 200 -
127.0.0.1 - - [16/Jul/2020 12:40:58] "GET /test.html HTTP/1.1" 200 -
  ✓ Show ISO-8859 characters correctly (150ms)

  1 passing (1s)

root@5e09ba505e99:/# npx cypress run -s $(pwd)/cypress/integration/spec.js -q -c chromeWebSecurity=false


127.0.0.1 - - [16/Jul/2020 12:41:21] "GET /test.html HTTP/1.1" 200 -
127.0.0.1 - - [16/Jul/2020 12:41:22] "GET /test.html HTTP/1.1" 200 -
  1) Show ISO-8859 characters correctly

  0 passing (1s)
  1 failing

  1) Show ISO-8859 characters correctly:
     AssertionError: Timed out retrying: Expected to find content: 'ñ' but never did.
      at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/integration/spec.js:6:6)



root@5e09ba505e99:/# exit
```

**Comment by fabianMendez** [comment]
Also this github action run showcases the problem: https://github.com/fabianMendez/cypress-test-tiny/runs/877697680

**Comment by jennifer-shehane** [comment]
I am able to see this not render properly now. I'm not sure what I'm doing different than before. But I still do not see a correlation to the `chromeWebSecurity` config - it never renders regardless of this setting. I find this to be the strange part of the bug report.

<img width="569" alt="Screen Shot 2020-07-23 at 4 13 40 PM" src="https://user-images.githubusercontent.com/1271364/88273028-982c7a80-ccff-11ea-8ff6-e7c63db8a8b9.png">

**Comment by fabianMendez** [comment]
I have cloned this repository and debugged it and I can confirm that it definitely has to do with the flag that is passed to chrome (`--disable-web-security`) or the configuration passed to electron (`options.webPreferences.webSecurity`)

Basically if I remove this line, chrome works even if chromeWebSecurity is false or true:
https://github.com/cypress-io/cypress/blob/3ab9643f5fc695484afa5278c85f20752379f428/packages/server/lib/browsers/chrome.ts#L360

And if I set `options.webPreferences.webSecurity`, to `true` before this line and to `false` after this line, the result is the same no matter what value is passed to chromeWebSecurity:
https://github.com/cypress-io/cypress/blob/3ab9643f5fc695484afa5278c85f20752379f428/packages/server/lib/gui/windows.js#L148

I can not think of a reason why the results are different for you, probably is specific to Linux, although I can not see why.

I will test this on Windows just to confirm if this is specific to Linux

**Comment by fabianMendez** [comment]
Tested on Windows with same results:

![imagen](https://user-images.githubusercontent.com/32204060/88445775-adca9e80-cdea-11ea-89e9-b83f243acbfe.png)


![imagen](https://user-images.githubusercontent.com/32204060/88445771-9db2bf00-cdea-11ea-962f-17b3134d0bea.png)
