### ISSUE TITLE
headless screenshots can't show error line with relevant file

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#7998]
run by cypress test runner:

<img width="537" alt="截屏2020-07-16 上午10 35 11" src="https://user-images.githubusercontent.com/22906174/87620233-9afffc00-c750-11ea-83da-b44dfaaefa49.png">

I can see assert error with relevant file.

run by headless:

<img width="395" alt="截屏2020-07-16 上午10 35 21" src="https://user-images.githubusercontent.com/22906174/87620247-a3583700-c750-11ea-89b2-f44bc7edd5f7.png">

screenshots only get assert error without relevant error file.

### Versions

Cypress 4.10.0

**Comment by jennifer-shehane** [comment]
Yeah, this is surprisingly true and very easy to reproduce. 

```js
it('test', () => {
  expect(true).to.be.false
})
```

`cypress open`

<img width="448" alt="Screen Shot 2020-07-16 at 3 36 58 PM" src="https://user-images.githubusercontent.com/1271364/87652512-54bf9280-c77a-11ea-8702-5a044f74dbfa.png">

`cypress run`

![test (failed)](https://user-images.githubusercontent.com/1271364/87652635-7d478c80-c77a-11ea-8463-95198707ddb8.png)
