### ISSUE TITLE
Incorrect error msg for traversing DOM elements w/ no selector and options

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#8]
When traversing a DOM element and passing in options but no selector, the error msg is not formatted correctly.

##### Examples of commands that will give incorrect error message:
```
cy.get("#header").next(visible: false)
```
```
cy.get("#header").children(visible: false)
```

##### Error Message
![screen shot 2015-03-30 at 2 13 00 pm](https://cloud.githubusercontent.com/assets/1271364/6903271/21f5128c-d6e7-11e4-9676-f48f0596561d.png)

**Comment by brian-mann** [comment]
Fixed in `0.4.5`. [Changelog](https://github.com/cypress-io/cypress/wiki/Changelog#045-04102015)
