### ISSUE TITLE
Err thrown when multiple cy.server() in one file's before

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#80]
When I have a file that has multiple `cy.server()` in seperate parent-level describe's `before`, this error is thrown on second `cy.server`:

```
CypressError: The XHR server is unavailable or missing. This should never happen and likely is a bug. Open an issue if you see this message.
```

**Screenshot of Command Log**
<img width="536" alt="screen shot 2015-11-02 at 12 31 34 pm" src="https://cloud.githubusercontent.com/assets/1271364/10889066/b69d2cb4-815d-11e5-95b3-bafa960ac5ce.png">

**Example Code**

``` coffeescript
describe "Model 1 [279]", ->
  before ->
    cy
      .visit("views/index.html")
      .server()

  it "foo bars [27a]", ->
    expect(true).to.be.true

describe "Model 2 [27b]", ->
  before ->
    cy
      .visit("views/index.html")
      .server()

  it "foo bars [27c]", ->
    expect(true).to.be.true
```

**Comment by brian-mann** [comment]
Fixed in [`0.12.6`](https://github.com/cypress-io/cypress/wiki/Changelog#0126-11292015).

**Comment by jennifer-shehane** [comment]
The above behavior is now happening again in `0.19.2`. I have not tracked down which version caused the regression.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by danigulyas** [comment]
I think the issue affects the emotional core of Mocha, as it's likes to be tucked in:

```
this works>
-describe
	-describe
		-before(() => cy.server())
		-it - works fine!
		-describe
			-it - works fine!
-describe
	-describe
		-before(() => cy.server())
		-it - works fine
		-describe
			-it - works fine!
```

```
this works too>
describe
	-describe
		-describe
			-before(() => cy.server())
			-it - works fine!
			-describe
				-it - works fine!
	-describe
		-describe
			-before(() => cy.server())
			-it - works fine
			-describe
				-it - works fine!
```

But when things get cold:

```
this doesn't work>
-describe
	-before(() => cy.server())
	-it - works fine!
	-describe
		-it - works fine!
-describe
	-before(() => cy.server())
	-it - :((((
	-describe
		-it - :((((
```
![image](https://user-images.githubusercontent.com/10425681/29936047-1cb5e716-8e81-11e7-9352-81e512583ee8.png)
