### ISSUE TITLE
Cypress and Yarn 2 PNP support

### ISSUE THREAD

**Issue by kirill-konshin** [cypress-io/cypress#8008]
### Current behavior:

In Yarn 2 monorepo I have a package `a` and tests in package `b`.

When I do

```js
// b/cypress/plugins/index
module.exports = require('a/src/cypress/plugins');
```

It works as expected.

But

```js
// a/cypress/commands/index
require('a/src/cypress/commands');
```

Fails with error:

```
Oops...we found an error preparing this test file:

  /Users/xxx/b/cypress/support/index.js

The error was:

Error: Cannot find module 'a/src/cypress/support' from '/Users/xxx/b/cypress/support'
```

Looks like Yarn's Plug'n'play file `.pnp.js` is not present in second (commands) context.

### Desired behavior:

Require of monorepo packages should work.

**Comment by kirill-konshin** [comment]
@bahmutov @jennifer-shehane please take a look at this issue, this is a huge blocker since there's no known workaround... Yarn 2.1.1 has been recently released, which means it's time to support it. Is there anything I can help?

@arcanis I was trying to find a way to import `.pnp.js` to enable proper resolution mechanics, but it did not help. Also I've tried https://yarnpkg.com/advanced/pnpify but seems that Cypress is launching some other context (for the browser?) which is not connected to main one, which is aware of PNP.

**Comment by bahmutov** [comment]
@kirill-konshin you can open a PR with at least some work showing what is going on in CLI when Yarn v2 is used to install Cypress

**Comment by kirill-konshin** [comment]
@bahmutov here you go https://github.com/kirill-konshin/cypress-test-tiny-yarn-pnp/pull/1/files (branch [bug](https://github.com/kirill-konshin/cypress-test-tiny-yarn-pnp/tree/bug)), monorepo is actually not needed, since none of PNP resolutions work.

Just run

```bash
$ yarn install
$ yarn test
```

And get an error: 

```
Error: Cannot find module 'cypress-plugin-snapshots/commands' from '/Users/xxx/cypress-test-tiny-yarn-pnp/cypress/support'
```

**Comment by kirill-konshin** [comment]
@bahmutov Any updates? We're completely blocked for almost a month, are there any workarounds or hacks?

**Comment by bahmutov** [comment]
We did not work on this issue, since it has low priority overall. If you know how to make Cypress NPM module play nicely with Yarn 2, you can open a PR into Cypress with the fix. 

PS: The error above seems to indicate a problem not with the Cypress itself, but with another plugin, no?

**Comment by kirill-konshin** [comment]
@bahmutov I wish I could make a PR, but I am not familiar with Cypress codebase at all.

I know that Yarn 2 is shipped with a set of tools https://next.yarnpkg.com/advanced/pnpapi and https://next.yarnpkg.com/advanced/pnpify that can be used to resolve packages. Superficially it looks like Cypress is creating a new context, which does is not aware of PNP resolution (unlike the main process).

The error above is a Cypress problem because it would happen with ANY plugin, since it is related to resolution algorithm in general.

Given that this issue has ben linked from another issue, there is some traction, and Yarn 2 is already public, so please consider raising the priority.

**Comment by kirill-konshin** [comment]
@bahmutov any updates?

**Comment by bahmutov** [comment]
No updates, we always post PRs or anything done under issues

**Comment by kirill-konshin** [comment]
@bahmutov is there anything else that I can do to speed it up? Do you have any ETA?

**Comment by bahmutov** [comment]
I would do a pull request with the solution if yarn 2 is a high priority for your needs

**Comment by kirill-konshin** [comment]
Like I said before, I’m not familiar with Cypress architecture and this bug seems to be buried quite deep, in the code where cypress resolves dependencies. Pnp has to be injected there, or their resolution has to be used. If you can point out the direction or provide a fix - it would be much better.

**Comment by bahmutov** [comment]
But isn’t it just the part of Cypress CLI which is quite limited?

**Comment by kirill-konshin** [comment]
It is definitely not part of CLI, it is the part that involves browser, because it all works in CLI. Please take a closer look at bug description: it works for `plugins` and does not work for `commands`.

**Comment by marcneander** [comment]
Adding the pnp-webpack-plugin is needed until cypress is using webpack 5.

```js
const webpackPreprocessor = require('@cypress/webpack-preprocessor');
const PnpWebpackPlugin = require('pnp-webpack-plugin');

module.exports = (on) => {
    const options = {
        webpackOptions: {
            resolve: {
                plugins: [
                    PnpWebpackPlugin
                ]
            },
            resolveLoader: {
                plugins: [
                    PnpWebpackPlugin.moduleLoader(module)
                ]
            }
        },
        watchOptions: {}
    };

    on('file:preprocessor', webpackPreprocessor(options));
};
```

**Comment by kirill-konshin** [comment]
@marcneander it did work, thanks a lot! Totally makes sense why.

**Comment by masihjahangiri** [comment]
Cypress should support built-in yarn 2 (PNP algorithm) and it's really important.
We use yarn 2 for the zero-install feature to improve our CI build time, and If we use nodeLinker, we miss that feature.

**Comment by kleingtm** [comment]
I had luck in a TypeScript + Cypress project doing the following in the Cypress plugins/index.js file:
```
const deepmerge = require("deepmerge");
const path = require("path");

module.exports = (on, config) => {

        // deep-merge config with the actual reporter 
        config =  deepmerge(config, {
            reporter: require(
                require(path.join(config.projectRoot, ".pnp.js")).resolveToUnqualified("cypress-multi-reporters", __filename)
            ),
            reporterOptions: {
                ... // put reporter options here
            }
        })
        ... // other plugin config
      
```
The key being yarn pnp API's `resolveToUnqualified` function which will spit out the pnp-ed module location.

**Comment by johnwiseheart** [comment]
As per #15241, this is also broken for resolving typescript cypress config:

`plugins/index.ts`:
```typescript
/// <reference types="cypress" />

const config: Cypress.PluginConfig = (on, config) => {
  // plugin config
};

export default config;
```

Fails with various errors due to it being run without transpilation.

**Comment by ysozer** [comment]
Has anyone succeeded with using PnpWebpackPlugin? I am also blocked with yarn 2 implementation

**Comment by missing1984** [comment]
Webpack 5 has built in pnp support. does Cypress have plan to switch default webpack preprocessor  to webpack 5?

**Comment by AaronBuxbaum** [comment]
Is there any movement on this PR? It's pretty annoying that this is the only package that forces us to use `nodeLinker: node-modules`

**Comment by jennifer-shehane** [comment]
@AaronBuxbaum You can track the currently opened PR here: https://github.com/cypress-io/cypress/pull/15623 Although this PR will not address all of the issues preventing Cypress from fully working with Yarn 2.

**Comment by jpulec** [comment]
If anyone else comes across this, managed to get this to work by just making sure that the PnP plugin gets added to the webpack config that Cypress uses. This works with cypress@7.3.0 using PnP with yarn workspaces. The following just needs to get added to you `cypress/plugins/index.js`.

```javascript
module.exports = (on) => {
    // You need to use your PnP file to resolve files. The following is just the path that traverses up to where my PnP file is in our repo root.
    const pnp = require('../../../../.pnp.js');
    // I couldn't find this documented, but this appears to monkey-patch require and do all the other necessary things to get PnP working
    pnp.setup();

    // This is where we'll be resolving packages from. In this case, it is a workspace package we have named, but using a relative path here should work as well to resolve from a specific folder.
    const targetModule = '@mypackages/package';

    // We need to patch the webpack config that cypress uses (which is v4 which needs a plugin for PnP support)
    const webpackPreprocessor = require(pnp.resolveToUnqualified('@cypress/webpack-preprocessor', targetModule));
    const PnpWebpackPlugin = require(pnp.resolveToUnqualified('pnp-webpack-plugin', targetModule));

    const options = {
        webpackOptions: {
            resolve: {
                plugins: [
                    PnpWebpackPlugin
                ]
            },
            resolveLoader: {
                plugins: [
                    PnpWebpackPlugin.moduleLoader(module)
                ]
            }
        },
        watchOptions: {}
    };

    on('file:preprocessor', webpackPreprocessor(options));
};
```

**Comment by ottoo** [comment]
> If anyone else comes across this, managed to get this to work by just making sure that the PnP plugin gets added to the webpack config that Cypress uses. This works with cypress@7.3.0 using PnP with yarn workspaces. The following just needs to get added to you `cypress/plugins/index.js`.
> 
> ```js
> module.exports = (on) => {
>     // You need to use your PnP file to resolve files. The following is just the path that traverses up to where my PnP file is in our repo root.
>     const pnp = require('../../../../.pnp.js');
>     // I couldn't find this documented, but this appears to monkey-patch require and do all the other necessary things to get PnP working
>     pnp.setup();
> 
>     // This is where we'll be resolving packages from. In this case, it is a workspace package we have named, but using a relative path here should work as well to resolve from a specific folder.
>     const targetModule = '@mypackages/package';
> 
>     // We need to patch the webpack config that cypress uses (which is v4 which needs a plugin for PnP support)
>     const webpackPreprocessor = require(pnp.resolveToUnqualified('@cypress/webpack-preprocessor', targetModule));
>     const PnpWebpackPlugin = require(pnp.resolveToUnqualified('pnp-webpack-plugin', targetModule));
> 
>     const options = {
>         webpackOptions: {
>             resolve: {
>                 plugins: [
>                     PnpWebpackPlugin
>                 ]
>             },
>             resolveLoader: {
>                 plugins: [
>                     PnpWebpackPlugin.moduleLoader(module)
>                 ]
>             }
>         },
>         watchOptions: {}
>     };
> 
>     on('file:preprocessor', webpackPreprocessor(options));
> };
> ```
> 
> You also may need to add `webpack@^4` as a dependency if you're using `strict` PnP mode, since it's peerDependency of `@cypress/webpack-preprocessor`.

Thanks! I've been looking for a solution for this for a while, I got it working with this example.

**Comment by christofer-castillo** [comment]
> ```js
> resolveToUnqualified
> ```

I'm currently trying to implement your solution. Thank you for doing all this work. But I have a question if you have the time. Do you know what the targetModule resolves to? I have tried reading Yarn PNP docs, but it just does not make sense to me.

**Comment by kleingtm** [comment]
Hello!

I'm not sure exactly what you mean by the "targetModule". With pnp, you'll
notice that modules are stored in a different location than
"node_modules/[thing]". So when using pnp, require("thing") gets translated
to require("/some/long/cached/path/of/the/thing/module").

The function resolveUnqualified essentially does that transformation for
you. It returns the long "/some/long/cached/path/of/the/thing/module".

Webpack 5 handles this for you so you don't need to worry about it.
However, something about the Cypress / Webpack 5 integration isn't complete
/ doesn't do this. So in my example, I manually go and get the location of
where pnp stored cypress-multi-reporters so that it can be used.

Hope that helps,

Tom

**Comment by missing1984** [comment]
cc @merceyz this is the cypress issue i was talking about. Cypress is using a forked process (from its electron app) to do compilation using webpack.

I think in order to make cypress compatible with yarn pnp natively . We need to either:

1. Fix https://github.com/arcanis/pnp-webpack-plugin/issues/32 and make it part of the default webpack config.
2. Fix the webpack 5 enhanced-resolve so it can load the correct pnpapi bases on source file(Do we have an issue opened?). and wait for Cypress switch to use webpack 5.
