### ISSUE TITLE
Hover not working using trigger or invoke on Shadow Dom component

### ISSUE THREAD

**Issue by rameshrc** [cypress-io/cypress#8016]
I have an application that is made of web components with lit-html. I could not make hover to work with the help of invoke or trigger along with experimental shadow dom as true. Any suggestions?

You could use sample application. Ignore the cypress test as it uses plugin
https://github.com/rameshrc/testinglithtml

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
