### ISSUE TITLE
Mocking a route with an empty response body doesn't show the XHR call as being stubbed

### ISSUE THREAD

**Issue by andreiduca** [cypress-io/cypress#8018]
### Current behavior:
Mocking a route with an empty response body

```js
cy.route('/sockjs-node/**', '').as('nodeSock');
```

incorrectly shows the XHR call not being stubbed:

![](https://user-images.githubusercontent.com/2589135/87823479-4f208600-c828-11ea-887e-f8b1fe5786dd.png)

Mocking the response body with a non-falsy value does produce the correct outcome:

```js
cy.route('/sockjs-node/**', '1').as('nodeSock');
```

![](https://user-images.githubusercontent.com/2589135/87823575-7f682480-c828-11ea-9d37-fe1ff325f008.png)

**Note: the request IS marked as stubbed in the Console in both cases:

![](https://user-images.githubusercontent.com/2589135/87824070-72980080-c829-11ea-9c63-ec43d27c278c.png)

### Desired behavior:
Both examples should show the call as `(xhr stub)` in the test runner.

### Test code to reproduce
1. Mock any route with an empty response body.
1. Observe the mocked XHR call note being shown as stubbed.

### Versions
Cypress@4.10, node 12.16.3, macOS 10.15.5

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-138) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Yeah, I feel like this is solely a visual bug in the Test Runner's Command Log. This test passes, but it doesn't show up as `xhr stub` in the Command Log.

So, I don't this is actually affecting any behavior.

```js
it('fails to show as stub in command log', () => {
  cy.visit('https://example.cypress.io/commands/aliasing')
  cy.server()
  cy.route('GET', 'comments/*', '').as('getComment')

  cy.get('.network-btn').click()
  cy.wait('@getComment').then((xhr) => {
    expect(xhr.response.body).to.eq('')
  })
})
```

<img width="580" alt="Screen Shot 2020-07-20 at 3 54 19 PM" src="https://user-images.githubusercontent.com/1271364/87921946-4d152c00-caa1-11ea-871e-b32364718268.png">

Looks like a check here that is returning false when the response is `''`. https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/xhr.js#L44:L44

**Comment by jennifer-shehane** [comment]
Opened PR here: https://github.com/cypress-io/cypress/pull/8033
