### ISSUE TITLE
Parse domains/subdomains/tld using public suffix

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#802]
Currently Cypress does a naive attempt at determining the domain, subdomain, and TLD of the current application under test.

It does not consider the public suffix, which results in it setting incorrect `document.domain` as well as yelling about changing domains when it's really not.

We should package in this [npm module](https://www.npmjs.com/package/psl) and then either make calls for parsing async (and do it in node) or transfer the data to Cypress during its bootstrap phase so it can parse it in the driver correctly.

Related to https://github.com/cypress-io/cypress/issues/380 and https://github.com/cypress-io/cypress/issues/600

**Comment by TomPridham** [comment]
do you guys have an ETA on this or a suggestion of where to start with this?

**Comment by function-de** [comment]
Same here. I can't get it running locally because my test domain contains "local" (and sorry, no, that's not easy to be changed in our setup).

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).
