### ISSUE TITLE
i have this error The following error originated from your application code, not from Cypress.

### ISSUE THREAD

**Issue by leenItg** [cypress-io/cypress#8023]
i write this simple code to visit site and type book  then click search
typescript file
this code

```js
type Url = string
it('loads examples', () => {
  const url: Url = 'https://www.ebay.com/'
  cy.visit(url)
  cy.get('input[type="text"]').type('book')
  cy.get('#gh-btn').click();
})
```
then I face this error 
![image](https://user-images.githubusercontent.com/66993565/87875593-065cfe80-c9db-11ea-9d6f-b9fcebe52b22.png)
 on click
how can I solve it?

**Comment by jennifer-shehane** [comment]
There is an error being thrown from a cross origin script on eBay's site when that button is clicked. Cypress fails the test when any uncaught errors are thrown from the application. You can ignore these uncaught errors throw from the application by following these directions: https://on.cypress.io/catalog-of-events#Uncaught-Exceptions
