### ISSUE TITLE
Cypress GUI does not clearly indicate scrollable area

### ISSUE THREAD

**Issue by shcallaway** [cypress-io/cypress#803]
- Operating System: macOS Yosemite
- Cypress Version: 0.20.1
- Browser Version: Chrome 61

### Is this a Feature or Bug?

Feature, I suppose.

### Current behavior:

The whitespace below `my-lists.spec.js` made me think that was my last spec file. In reality, I have more that can be seen by scrolling. The scrollbar is an obvious indicator, but the whitespace still threw me off.

![image](https://user-images.githubusercontent.com/7094076/31970867-700b79fe-b8ce-11e7-8f06-1f7f554ad74b.png)

### Desired behavior:

There should be no whitespace below the last visible spec file.

**Comment by jennifer-shehane** [comment]
This issue only occurs when the update banner is present.

**Comment by brian-mann** [comment]
Fixed in [`1.0.3`](https://docs.cypress.io/guides/references/changelog.html#1-0-3).
