### ISSUE TITLE
I'm an Owner and my Project Disappeared...

### ISSUE THREAD

**Issue by paper-id** [cypress-io/cypress#8030]
Hi, I'm an owner of a project and it disappeared from my dashboard. However in other users, I'm still listed as the Owner...And why is it so hard for non-programmer/developer to submit ticket??

Please personally PM me for the personal details.

**Comment by jennifer-shehane** [comment]
Hey @paper-id, sorry for the inconvenience. Could you send us an email at support@cypress.io? Including the projectId from your `cypress.json` will help us in tracking down the issue. Thanks.

**Comment by jennifer-shehane** [comment]
Closing to be handled through email support thread.
