### ISSUE TITLE
Cypress getting lose the Local session values at run time.

### ISSUE THREAD

**Issue by igopisrinivasan** [cypress-io/cypress#8037]
Cypress getting lose the Local session values at run time.
--
 
### Current behavior:
 
Our Problem isthat, whenever we try to run a test UI request two XHR from a click in UI. One XHR keep on fail for Authorization.

In our Scenario, we try to access the token from authO and saved in the Session storage. So when we click a button in the UI. UI sending two XHR request and waiting for two response. Once first XHR response got, second XHR request getting failed in the Execution.
 
when we Run the same in Debugging mode, we observed Session Storage getting dropped.
 
When i retry the test a couple of times manually  it works normal.
 
It seems to be an error connected to a Cypress browser. After it loads successfully, even opening new Mocha 'It' test and running tests in them.
 
Even worse is trying to test production web. It seems Cypress can not get authorized?

I constantly get 401 Unauthorized.
 
We're running under Single Sign On Bearer Token Authorization.
 
### Desired behavior:
 
Session storage should not get drop at any number of request flow between client and server in any supporting browser
 
### Test code to reproduce
 
```js
describe('Sample Tests', () => {
  before(() => {
    cy.clearLocalStorageCache()
    cy.login()   // Via Single Sign On
  })
  beforeEach(() => {
    cy.restoreLocalStorageCache()
  })
  afterEach(() => {
    cy.saveLocalStorageCache()
  })
  after(() => {
    cy.clearLocalStorageCache()
  })

  after(function () {
    cy.logout()  // Custom Command Logout
  })

  it('Verify Adding value to the Home Page', () => {
    cy.visit('/home')
    cy.wait(3000)
    cy.get('#clientsDropdown > div').click()
    cy.wait(3000)
    cy.get(' div.ui-dropdown-items-wrapper > ul > p-dropdownitem:nth-child(4) > li').click()
    for (let i = 0; i < temp.length; i++) {
      let { XX, XXX } = temp[i]
      cy.get('table > tbody.ui-table-tbody>tr:nth-child(' + i + ')>td:nth-child(2)').contains('td', XXX).should('be.visible')
      cy.get('table > tbody.ui-table-tbody>tr:nth-child(' + i + ')>td:nth-child(3)').contains('td', XXX).should('be.visible')
    }
  })
})
```
![image](https://user-images.githubusercontent.com/59263924/87929405-01b04d00-caa4-11ea-8403-4354f217ea2b.png)
 
Cypress.JSON
```
failOnStatusCode: false,
chromeWebSecurity: false,
```
 
### Versions
 
Cypress: 4.10.0
Windows 10 (Version 2004)
Chrome 83

**Comment by jennifer-shehane** [comment]
Cypress automatically clears `localStorage`, `sessionStorage`, and `cookies` in between each test (every `it` function). You will need to restore these in between tests if they are relevant to your application maintaining authorization for each test that is executed. 

I see you have some custom command to restore `localStorageCache`, but did not provide the code there. If you need to maintain [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) specifically, you'll need another command to do that.

**Comment by igopisrinivasan** [comment]
after adding below code in all the test cases. we are able to make connection live between the test cases. Thanks @jennifer-shehane 

before(() => {
        cy.clearLocalStorageCache()
        cy.login()
    })
    beforeEach(() => {
        cy.restoreLocalStorageCache()
    })
    afterEach(() => {
        cy.saveLocalStorageCache()
    })
    after(() => {
        cy.clearLocalStorageCache()
    })
