### ISSUE TITLE
HTTPS traffic is not getting redirected via http proxy

### ISSUE THREAD

**Issue by thecodejack** [cypress-io/cypress#8041]
Based on the info mentioned in this page regarding [Proxy config](https://docs.cypress.io/guides/references/proxy-configuration.html#Set-a-proxy-on-Linux-or-macOS), I have set HTTP_PROXY system variable. 

### Current behavior:

All HTTP traffic is getting redirected via proxy. Based in [link info](https://docs.cypress.io/guides/references/proxy-configuration.html#Proxy-environment-variables), HTTPS traffic also expected to be redirected via same proxy server. But observed that requested were sent directly rather via proxy server

Note that my proxy server is a http based node server. https support has been tested and worked fine of the proxy server.

### Desired behavior:

HTTPS traffic also needs to be redirected via same server.

### Versions

Cypress 4.10.0
OS Linux
Browser: Electron, Chrome

**Comment by jennifer-shehane** [comment]
@thecodejack Can you check the proxy settings in the UI to ensure the correct proxy settings are being read in properly? What does the settings panel say? https://on.cypress.io/proxy-configuration#View-proxy-settings-in-Cypress

Also print `echo $HTTP_PROXY` and `echo $HTTPS_PROXY` to ensure there is not a conflicting `HTTPS_PROXY` set?

>But observed that requested were sent directly rather via proxy server

What is happening during your tests when this occurs exactly? Are there any errors?

**Comment by thecodejack** [comment]
Tried debugging a bit more into this and found out that HTTPS socket is getting closed before it gets data. Can we rather do a retry when that happens?
