### ISSUE TITLE
AST rewriting not adding closing script tag when string is too long

### ISSUE THREAD

**Issue by panzarino** [cypress-io/cypress#8043]
### Current behavior:
The following test case, with `experimentalSourceRewriting` turned on, will not properly render the page. (It doesn't properly render the page without it either, see #1068)

```javascript
  it('can open office online', () => {
    cy.visit('https://www.office.com/launch/excel?ms.officeurl=webapps&auth=2');

    cy.contains('Sign in').should('be', 'visible');
  });
```

It looks like when the source is being rewritten, something is causing the closing `</script>` tag to be omitted. When this tag is omitted, the rest of the page goes missing as well.

Here's what the rewritten response looks like:

![Screen Shot 2020-07-20 at 6 32 38 PM](https://user-images.githubusercontent.com/7033952/87995503-aee38f00-cabd-11ea-91b2-071054e99d27.png)

Here's the actual response:

![Screen Shot 2020-07-20 at 6 32 58 PM](https://user-images.githubusercontent.com/7033952/87995509-b145e900-cabd-11ea-8c96-25e801d6d120.png)

From some initial investigations it appears that this is a bug caused by the length of the script.

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-156) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
I've seen an issue with the AUT not loading with this option in a few cases. Hopefully this addresses some of those. 🤞

**Comment by panzarino** [comment]
@jennifer-shehane Looks like we're not actually checking that the stream has finished being rewritten before returning the result, meaning long strings will complete after it returns: https://github.com/cypress-io/cypress/blob/develop/packages/rewriter/lib/html.ts#L17. Hopefully fixing with a PR later today.
