### ISSUE TITLE
cy.clear({ force: true }) only deletes first character of hidden input in 4.3.0 reappears after being closed in #5835

### ISSUE THREAD

**Issue by nagendraspeakap** [cypress-io/cypress#8044]
This issue was raised in #5835 and closed and released in 3.8.0 but I can still see it in 4.3.0.

### Current behavior:

`.clear({ force: true })` only deletes the first character of a hidden input's initial value.

### Desired behavior:

`.clear({ force: true })` should delete all characters of a hidden input's initial value.

Given:

```html
<input type="text" value="testDescription" type="hidden">
```
This assertion fails:

```js
cy.get('input').clear({ force: true }).type("testUpdatedDescription").should('have.value', 'testUpdatedDescription')
```
With error:

```
CypressError: Timed out retrying: expected '<input>' to have value '', but the value was 'testUpdatedDescriptionestDescription'
```

Versions
These versions have been confirmed to be affected:
v4.3.0

![image](https://user-images.githubusercontent.com/61794874/88015065-b0926e80-cb20-11ea-854c-13fead43e84a.png)

**Comment by jennifer-shehane** [comment]
I'm not able to replicate this in 4.3.0 or 4.10.0 of Cypress. 

It looks like you're using some kind of rich text editor in the application you're testing, the events or JS around that may be affecting when this issue occurs. Could you provide an example that we can run completely that replicates the error? Thanks!

```html
<html>
  <body>
    <input type="text" value="testDescription" type="hidden">
  </body>
</html>
```

`spec.js`

```js
it('clear hidden input', () => {
  cy.visit('index.html')
  cy.get('input')
  .should('have.value', 'testDescription')
  .clear({ force: true })
  .should('have.value', '')
  .type('testUpdatedDescription')
  .should('have.value', 'testUpdatedDescription')
})
```

<img width="740" alt="Screen Shot 2020-07-21 at 11 52 58 AM" src="https://user-images.githubusercontent.com/1271364/88016123-be5bea00-cb48-11ea-909d-3f025a4e2f81.png">

**Comment by nagendraspeakap** [comment]
Thanks for you reply Jennifer. Yes, indeed there is an event fired in rich text editor in my application. I will create a workaround in my script for this and closing this issue now.

**Comment by stevenvachon** [comment]
I'm having this issue with Monaco editor.
