### ISSUE TITLE
Cannot do any spaces in IDs when using ID with space 

### ISSUE THREAD

**Issue by Ahm3d-A** [cypress-io/cypress#8052]

**Comment by Ahm3d-A** [comment]
when using space in ID 
cypress throws error

**Comment by Ahm3d-A** [comment]
I am trying to use this code
Cypress.Commands.add('dataCy', (value: string) => cy.get(`[data-cy=${value}]`))
it is a custom command in typescript 
however as I said now when using spaces in this value I get errors

**Comment by jennifer-shehane** [comment]
@Ahm3d-A You'll need to put the value of the data-cy within quotes, since it contains spaces. 

`spec.js`

```js
// add quotation marks around ${value}
Cypress.Commands.add('dataCy', (value) => cy.get(`[data-cy="${value}"]`))

it('spaces in data-cy', () => {
  cy.visit('index.html')
  cy.dataCy('my id')
})
```

`index.html`

```html
<html>
<body>
<div data-cy="my id">Test</div>
</body>
</html>
```

<img width="585" alt="Screen Shot 2020-07-22 at 3 01 52 PM" src="https://user-images.githubusercontent.com/1271364/88154097-5088ee80-cc2c-11ea-89fe-6efcf956a692.png">

**Comment by Ahm3d-A** [comment]
thanks works perfectly
