### ISSUE TITLE
<object type="application/pdf" /> and <iframe /> not showing PDF in Chrome headless mode

### ISSUE THREAD

**Issue by croraf** [cypress-io/cypress#8053]
### Test code to reproduce

I have the following code in the app which renders a PDF document using Chrome's built-in  PDF renderer.

```html
<object 
  type="application/pdf"
  data="http://www.africau.edu/images/default/sample.pdf"
  width="100%"
  test-id="embedded-preview"
  style="height: calc(100vh - 120px);"
>
   Document preview
</object>
```

### Current behavior:

When running through the cypress app everything works fine. But, when running using `cypress run --browser chrome --headless` or `cypress run --browser chrome` the test fails and later checking the video, I see that the PDF is not rendered. Instead, for the headless mode it shows the alternative text (`Document preview` string in the above case) and for the headed mode nothing is shown.

### Desired behavior:

I want a PDF to be rendered when running the tests using `cypress run` same as how it gets rendered when using "cypress open".

### Versions

Cypress 4.9.0
Google Chrome, Version 84.0.4147.89 (Official Build) (64-bit)
OS: Ubuntu 20.04, 5.4.0-40-generic #44-Ubuntu

**Comment by jennifer-shehane** [comment]
I can recreate this behavior, when running in Chrome headless or Electron headed/headless. This works properly in Firefox. 

`spec.js`

```js
it('PDF', () => {
  cy.visit('index.html')
})
```

```html
<html>
<body>
<object type="application/pdf" data="http://www.africau.edu/images/default/sample.pdf">
  Document preview
</object>
</body>
</html>
```

### Chrome/Electron headed

<img width="745" alt="Screen Shot 2020-07-22 at 2 20 55 PM" src="https://user-images.githubusercontent.com/1271364/88149830-9cd13000-cc26-11ea-953a-c69b82dc3438.png">

### Chrome headless/Electron headed or headless

<img width="1001" alt="Screen Shot 2020-07-22 at 2 19 10 PM" src="https://user-images.githubusercontent.com/1271364/88149957-c68a5700-cc26-11ea-9c68-e446b9d17305.png">

**Comment by croraf** [comment]
I made a minimal example now with Cypress 4.11.0. and I get the same results as you do. (@jennifer-shehane You just made a typo above in above the first image. The first image is behavior in `Chrome headed / Firefox headless and headed` as you said above in the text)

Minor (not that important) difference from what I originally reported in my real case is that in my real case with Cypress 4.9.0 the Chrome headed didn't show anything (nor the PDF nor the alt text). But this might be due to test commands.

**Comment by vijaychandra24** [comment]
This is happening to me as well . I have tried in all 3 browser - browsers: Array (3)
0:Chrome
1:Firefox
2:Electron

**Comment by croraf** [comment]
Any updates on this :( . It is still happening.
Configuration:
- Cypress version 7.5.0. 
- Chrome version: Version 91.0.4472.77 (Official Build) (64-bit)
- OS: Ubuntu 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ckxddd0324** [comment]
> Any updates on this :( . It is still happening.
> Configuration:
> 
> * Cypress version 7.5.0.
> * Chrome version: Version 91.0.4472.77 (Official Build) (64-bit)
> * OS: `Ubuntu 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
> 
> It is also happening with `iframe` trying to show pdf.

Is the pdf embedded on the page? I am experience something similar as well, the Cypress runner is unable to load the PDF on the page, but if I would open the page with another one it works.

**Comment by extracker-ppetrov** [comment]
Same issue here in Cypress 12.3.0. 
Clicking on a button that opens a PDF viewer works in Chrome and Electron, when running the test in a browser, but fails when the test is run headlesss. 
If I use cy.visit() I am getting an error:
The content-type of the response we received from your web server was:

> application/pdf

This was considered a failure because responses must have content-type: 'text/html'

However, you can likely use cy.request() instead of cy.visit().

If I use cy.request() the request is successful, but that does not open the PDF viewer.
