### ISSUE TITLE
cy.wait() timeout only in headless mode

### ISSUE THREAD

**Issue by tihmatsumoto** [cypress-io/cypress#8055]
### Current behavior:

Whenever we run our tests in headless mode for nightly run or after a PR build, we get errors from Cypress stating that `cy.wait() timed out waiting 5000ms. No request ever occurred.` But when running it on Cypress Runner, such errors never happen. 

Half of my current tests are breaking because of this behavior, even though running it using Cypress Runner is not a problem. 

### Test code to reproduce

Here is a snippet of a test that always breaks. 

```js
it("Should fail when adding a duplicate account", () => {
    cy.get(submitButton).click();
    cy.wait("@createAccount", { responseTimeout: 15000 }).then(xhr => {
      assert.equal(xhr.status, 400);
      expect(xhr.response.body).not.to.be.null;
      expect(xhr.response.body.message).to.eq(
        "An account with the given email already exists."
      );
      expect(xhr.response.body.__type).to.eq("UsernameExistsException");
    });
  });
```

### Versions

Using Cypress 4.10, macOS and ubuntu-latest (for github Actions).

**Comment by Saibamen** [comment]
Try latest 4.11

**Comment by tihmatsumoto** [comment]
Still breaking. Even though responseTimeout is set for 15000. I keep getting: 

>      CypressError: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `createAccount`. No request ever occurred.

Happening with 20+ tests in this suite.

**Comment by jennifer-shehane** [comment]
@tihmatsumoto Do you have anything in your application that would trigger on `onbeforeunload`? There is a known issue where requests will timeout in Electron (the default browser during `cypress run` if there is an `onbeforeunload` event. You can read more here: https://github.com/cypress-io/cypress/issues/2118

Outside of this, I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

We'll need a reproducible example to investigate further to determine why this is happening.

**Comment by tihmatsumoto** [comment]
@jennifer-shehane I think this issue can be closed. I was looking out for other issues using Cypress and came around this issue: #7903. After I removed service worker, all xhr are capture successfully even in CL. It isn't the best solution but at least, we can keep tests running with less flaky tests :)

**Comment by jennifer-shehane** [comment]
Yeah, a clear example of why the XHRs perform differently with service workers would be nice since this isn't clearly documented yet.
