### ISSUE TITLE
how to assert if this text contain at least one words from one statement in cypress.

### ISSUE THREAD

**Issue by leenItg** [cypress-io/cypress#8058]
how to assert if this text contain at least one words from one statement in cypress.

for example

```js
cy.get('.stitle').contains('learning table',{ matchCase: false })
```

this statement will get true if the `.stitle` have the full of `learning table`,
but I want if `.stitle` have `learning` just, or `table` just, to be true if it is contain at least one words.

without use `learning || table` because I want it to be reusable for any statement

**Comment by jennifer-shehane** [comment]
`.contains()` accepts Regular Expressions. Depending on what you want to match, if its more complex that matching text exactly, I'd use that. See the documentation for [`.contains()`](https://on.cypress.io/contains#Arguments)

```js
cy.get('.stitle').contains(/(learning|table)/, { matchCase: false })
```
