### ISSUE TITLE
Cypress failed to make a connection to Firefox: Running Firefox as root in a regular user's session is not supported

### ISSUE THREAD

**Issue by heinzhang** [cypress-io/cypress#8067]
### Current behavior:

**Tried to run the following command:** 
```
 DEBUG=cypress:* ~/cypressWork/node_modules/.bin/cypress run --browser firefox
```

**Got errors below:**
```
Cypress failed to make a connection to Firefox.
This usually indicates there was a problem opening the Firefox browser.

Error details:
Error: connect ECONNREFUSED 127.0.0.1:51642 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
```

Debug log:
```
cypress:launcher launching browser { 
  browser: { 
    name: 'firefox', 
    family: 'firefox', 
    channel: 'stable', 
    displayName: 'Firefox', 
    version: '78.0.2', 
    path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', 
    info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', 
    majorVersion: 78, 
    isHeadless: false, 
    isHeaded: true 
  }, url: 'about:blank' } +642ms
cypress:launcher spawning browser with args { 
  args: [ 'about:blank', '-marionette', '-new-instance', '-foreground', '-start-debugger-server', '-no-remote', '-profile', '/Users/user/Library/Application Support/Cypress/cy/production/browsers/firefox-stable/run-8752' ] 
  } +0ms
cypress:network:connect received error on connect, retrying { 
  iteration: 0, 
  delay: 100, 
  err: Error: connect ECONNREFUSED 127.0.0.1:54088     
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) { 
      errno: 'ECONNREFUSED', 
      code: 'ECONNREFUSED', 
      syscall: 'connect', 
      address: '127.0.0.1', 
      port: 54088 
    } 
  } +329ms
```

From the fuill log it seems having found firefox but could not connect to the port. 
Full log is here [firefox.log](https://github.com/cypress-io/cypress/files/4963869/firefox.log)
### Desired behavior:

Should open firefox and run the script. 

### Versions

Cypress 4.11.0
Firefox 78.0.2 (64-bit)
macOS Catalina 10.15.6 

Thanks.

**Comment by jennifer-shehane** [comment]
There's an error thrown from Firefox visible in the logs. After this is when it fails connecting over and over again.

```
cypress:launcher firefox stderr: Running Firefox as root in a regular user's session is not supported.  ($HOME is /Users/tester which is owned by tester.)
cypress:launcher firefox exited: { code: 1, signal: null }
```

This is intentional from Firefox, disallowing it to launch from root.

>If a user runs Firefox as root but using their own home directory, many things become broken for that user, sometimes permanently. We should refuse to launch Firefox like this.

So this seems related to your root permissions or how you originally installed Firefox. There are a few suggestions online on how to fix this depending on your situation.

**Comment by heinzhang** [comment]
@jennifer-shehane Thanks for the quick response. I ran from the current user instead of root it solved the issue.

**Comment by Xiaogen-liu** [comment]
HI @heinzhang 
Could you help to share more detail about his solution ? because i encountered the same issue in jenkins.
