### ISSUE TITLE
fx/fixture shortcut does not call overwritten cy.fixture command

### ISSUE THREAD

**Issue by jbjhjm** [cypress-io/cypress#8069]
For optimal usability it would be great if fx:/fixture: shortcuts would use overwritten fixture command.

### Current behavior:

```ts
Cypress.Commands.overwrite('fixture', (originalFn, path) => {
	console.log('load fixture '+path)
	return originalFn(path)
})
// logs 'load fixture fixture1'
cy.fixture('fixture1').then(fixture=>{
	cy.route('POST','api/users/authenticate',fixture).as('authRequest')
})
// logs nothing
cy.route('POST','api/users/authenticate','fixture:fixture2').as('authRequest')

```

### Desired behavior:

This should log 'load fixture fixture2':

```ts
cy.route('POST','api/users/authenticate','fixture:fixture2').as('authRequest')
```
I'm not familiar with the Cypress source code yet so I'm not sure how complex this would be to fix.
However for intuitive use of command overwriting it would make sense if the shortcut calls cy.fixture to support overwriting.

### Versions

Cypress 4.10

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
