### ISSUE TITLE
Remove unintentionally exposed private properties from `Module API`

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#8076]
we have several properties on `Module API` test run results that are not useful to users:
`timings`
`testId`
`failedFromHookId`

reasons for removing:
- these properties were not created for use by end users 
- unintentionally couples public `Module API` to dashboard API 
- when we make changes to dashboard API,  we don't want to affect public API

**Comment by bahmutov** [comment]
Nooo, not the timings
