### ISSUE TITLE
Cypress experimentalShadowDomSupport - Unable to Type in paper-textarea (Polymer)

### ISSUE THREAD

**Issue by shaunswales** [cypress-io/cypress#8077]
Using the new experimental feature for ShadowDOM support it's not working correctly with some Polymer elements.

Specifically in this example the `paper-textarea`.

Log Output: 
<img width="382" alt="Screenshot 2020-07-23 at 18 41 58" src="https://user-images.githubusercontent.com/17008391/88319657-607bfd80-cd14-11ea-89b1-d9628a12dc8f.png">

Page Screenshot: 
![123](https://user-images.githubusercontent.com/17008391/88319631-578b2c00-cd14-11ea-86e4-53a18775d430.png)

### Current behavior:
When trying to type into the `paper-textarea` Cypress say's it has done but it's not actually done so, nothing can be seen or is picked up as a value.

### Test code to reproduce

Page DOM:
```html
<!-- Title -->
<paper-textarea data-testid="collection-title-textarea" id="title" placeholder="Enter a title for your Collection" autofocus="" no-label-float="" class="flex title fs--lxl fw--sb block " tabindex="0" aria-disabled="false" style=""></paper-textarea>

<!-- Description -->
<paper-textarea data-testid="collection-description-textarea" id="description" placeholder="Write a description for your Collection" class="flex wake__description block" no-label-float="" tabindex="0" aria-disabled="false" style=""></paper-textarea>
```

Cypress Code:
```javascript
// Enter Title
cy.get('paper-textarea[data-testid='collection-title-textarea']', {
    includeShadowDom: true,
  }).type('Test Title', { force: true, deplay: 50 });

// Enter Description
cy.get('paper-textarea[data-testid='collection-description-textarea']', {
    includeShadowDom: true,
  }).type('This is a test description ... ', { force: true, deplay: 50 });
```
Helpful Links: https://www.webcomponents.org/element/@polymer/paper-input

### Versions
`4.11.0`

**Comment by jennifer-shehane** [comment]
I'm not sure you are targetting the correct element to type into here. I can't get the `paper-textarea` to render properly for me for some reason, but when I type into a `paper-input`, targetting `paper-input` shows the element as disabled (you should remove the `force` option to see these errors). 

Is there an error when you remove the `force` option?

I have to target the actual `input` to type into. 

```html
<html>
<head>
  <script type="module">
    import '@polymer/paper-input/paper-input.js';
  </script>
</head>
<body>
  <paper-input id="input" always-float-label label="Floating label"></paper-input>
</body>
</html>
```

```js
it('test', () => {
  cy.visit('http://127.0.0.1:8081')
  cy.get('input', {
    includeShadowDom: true,
  }).type('Test Title');
})
```

```json
---

I'm having issues with the paper elements in polymer on their demo, but I don't think it's the same issue being described above. 

```js
it('test', () => {
  cy.visit('https://www.webcomponents.org/element/@polymer/paper-input/demo/demo/index.html')
  cy.get('#textarea', { timeout: 10000, includeShadowDom: true})
})
```

<img width="513" alt="Screen Shot 2020-07-27 at 12 13 48 PM" src="https://user-images.githubusercontent.com/1271364/88507536-a67ddd80-d002-11ea-87d8-7d9adaa9351e.png">

**Comment by shaunswales** [comment]
Thank you for the response, for some reason GitHub didn't ping me a notification about the reply.

So right now I'm targeting the `textarea` or `input` within the paper wrapper, and it types but nothing is updating, please see the screenshots below:

This is when I manually type in the box in Chrome:
<img width="956" alt="Screenshot 2020-08-06 at 08 40 01" src="https://user-images.githubusercontent.com/17008391/89505752-04a87e80-d7c2-11ea-82fb-0df2feea9cc3.png">

However when I'm using Cypress:
<img width="845" alt="Screenshot 2020-08-06 at 08 35 50" src="https://user-images.githubusercontent.com/17008391/89505795-14c05e00-d7c2-11ea-846d-bb831c2637b5.png">

-----

As you can see it's not actually updating the DOM like when I do it manually.

**Comment by shaunswales** [comment]
Ended up creating a new command to resolve the issue:
```
Cypress.Commands.add('wType', (locator, text) => {
  const input = cy.get(locator, {
    includeShadowDom: true,
  });
  input.type(text, { force: true, delay: 150 })
  input.then((el) => {
    cy.window().then(win => {
      el[0].dispatchEvent(new win.Event('input', {composed: true}));
    });
  });
});
```
