### ISSUE TITLE
cy.server force404 intercepts nextjs dev server calls

### ISSUE THREAD

**Issue by uriel-sf** [cypress-io/cypress#8078]
### Current behavior:

* We have a `cy.server` running  in the background w/ `force404` enabled
- We noticed that it now 404s certain nextjs-dev-server requests. For example,  this call to load a webpack file (`/book-room/_next/static/webpack/6b5b700709ba922b21a9.hot-update.json`): 

![image](https://user-images.githubusercontent.com/48688613/88331181-2b5eb380-ccf2-11ea-91d3-23cba91843f3.png)

- this in turn causes the page to re-load (also visible  in the screenshot), which in turn increases test flakiness

### Desired behavior:

- force404 should allow nextjs-dev-server calls to go through

### Test code to reproduce

- sorry it's a private repo :(

### Versions

- cypress: 4.1.0
- nextjs: 9.4.5

**Comment by jennifer-shehane** [comment]
@uriel-sf I think you'll want to `whitelist` this request from the `cy.server()` as explained here so it won't log or be stubbed: https://on.cypress.io/server#Change-the-default-filtering

As you can see in the docs, we ignore certain request types that we believe to be static resources, like `.js`, `.html` - `.json` would not be one that we would ignore or know to ignore as this could be any legitimate XHR request.

**Comment by uriel-sf** [comment]
Right... digging  into the docs, it's also possible to specify a `route` without a callback or response. This is what I ended up doing:

```
 cy.route('**/data/development/*json');
 cy.route('**/_next/static/**');
```

This made the nextjs webpack requests for our app pass through.
