### ISSUE TITLE
Whitelisted cookies preserved over runs, clearCookies() does not clear whitelisted cookies

### ISSUE THREAD

**Issue by sand3r** [cypress-io/cypress#808]
- Operating System:
OSX 10.12.5
- Cypress Version:
Cypress package version: 1.0.2
Cypress binary version: 1.0.2

- Browser Version:
Canary 64

### Is this a Feature or Bug?
Bug

### Current behavior:
Having the following test code:

```js
describe('Example', () => {

  Cypress.Cookies.defaults({
    whitelist: /SESSION_COOKIE/
  });

  before('we should log in first', () => {
    cy
      // clearCookies() does not clear whitelisted cookies
      .clearCookies()
      .visit('application_url, which sets a NEW SESSION_COOKIE to use throughout the following tests');
  });

  it('should still have SESSION_COOKIE', function() {
    cy
      .visit('application_url/subpage')
      .wait(5000); 

      // .wait() was just added so you can inspect the list of cookies.
      // Notice that SESSION_COOKIE stays the same over several runs.
  });

  it('should really still have SESSION_COOKIE', function() {
    // More tests.
    cy
      .visit('application_url/subpage')
      .wait(5000);
  });

  it('should really really still have SESSION_COOKIE', function() {
    // More and more tests.
    cy
      .visit('application_url/subpage')
      .wait(5000);
  });
});
```

In the current phase my tests keeps failing, because the first run logs in and because I preserve the cookie, it is persisted throughout every test that runs.

Technically I'm not able to clear cookies between runs/during tests.

### Desired behavior:
Few suggestions :)
- clearCookies() should be able to remove all cookies, even whitelisted cookies (to avoid a breaking change, it can be an option to clearCookies(), e.g. clearWhitelisted: true ?)
- Next to 'preserveOnce()' I'd also rather see a 'preserve' that will at least preserve the cookies throughout the test suite (test suite = 1 file). If I want to achieve what I actually want right now I have to call preserveOnce() in every single test.

### How to reproduce:
Use the above code, start coding on the test and press Save. Cypress will run the test, but preserve the whitelisted cookie even though it says 'clearCookies()'. Also when you use the 'Run all tests'. 

#### Test code:
See above :)

**Comment by brian-mann** [comment]
Also if you want to clear a cookie even if its been preserved you can just do `cy.clearCookie('nameOfCookie')`

That will blow it away no matter what.

**Comment by sand3r** [comment]
Thanks Brian!

I was a bit unsure whether I was really missing something, but your answer clarifies. I'll keep track of #686. 

Furthermore just wanted to share that Cypress.io is just amazing - I am just really enthusiastic about it and spreading the message here at the office. It really helps while developing; which is what I try to use it mainly for currently.

**Comment by brian-mann** [comment]
Going to close this then - its referenced in the other issue now.

**Comment by MacGyver27** [comment]
> Also if you want to clear a cookie even if its been preserved you can just do `cy.clearCookie('nameOfCookie')`
> 
> That will blow it away no matter what.

On `3.5.0` and does not work using `cy.clearCookie('nameOfCookie')`..

When I try to change defaults to empty array or undefined, still wont delete the cookie..
```
Cypress.Cookies.defaults({
    whitelist: [] / undefined
});
```
Any other ideas??

Thanks

**Comment by bvdr** [comment]
And here is my workaround to clear cookies that are set using `whitelist` regex and set them again:
``` js
it("Clear browser cookies and localstorage", function(){
  
  //Visit URL
  const host_url = Cypress.env('host_url');
  cy.visit(host_url)

  // Empty defaults
  Cypress.Cookies.defaults({
    whitelist: []
  });

  //Clear localStrage
  cy.clearLocalStorage()

  //Clear Cookies
  cy.clearCookies()

  // Set defaults
  Cypress.Cookies.defaults({
    whitelist: /wordpress_.*|woocommerce_.*|wp_woocommerce_.*/
  })
})
```

**Comment by jennifer-shehane** [comment]
We released [`cy.session()`](https://on.cypress.io/session) as an experimental command (set `experimentalSessionSupport` to `true` in config) in Cypress 8.2.0. This command can be used to cache and restore cookies, `localStorage`, and `sessionStorage`. We especially see this command as being useful for testing Auth flows and recommend giving it a try to replace your existing tests around authentication and login.

If you have any feedback about `cy.session()` for general UX improvements, new features, or unexpected behavior, please leave your feedback in our [Cypress Session Experimental Feedback Discussion](https://github.com/cypress-io/cypress/discussions/17887).
