### ISSUE TITLE
Tests code interpreted differently in test runner vs cli run

### ISSUE THREAD

**Issue by vbrundic** [cypress-io/cypress#8087]
### Current behavior:
A test contains the following piece of code for uploading a video file:

```js
cy.get('input[type="file"]').then((subject) => {
  cy.fixture(videoPath, "base64").then((front) => {
    Cypress.Blob.base64StringToBlob(front, mimeType).then(function (blob) {
      var testfile = new File([blob], filename, { type: mimeType });
      var dataTransfer = new DataTransfer();
      var fileInput = subject[0];

      dataTransfer.items.add(testfile);
      fileInput.files = dataTransfer.files;

      cy.wrap(subject).trigger("change", { force: true });
    });
  });
});
cy.get("button").contains("Upload").click({ force: true });
cy.wait(15000);
```

When starting the test runner with ' npx cypress open ' and executing this test, it passes and the file is uploaded:
![image](https://user-images.githubusercontent.com/18590594/88437389-ac0ed400-ce06-11ea-9993-205b320e0634.png)

When running the exact same configuration from CLI (npx cypress run --browser chrome --headed) the test fails, and trigger is never executed.
![image](https://user-images.githubusercontent.com/18590594/88437511-e24c5380-ce06-11ea-8bca-c6db3a5a016c.png)

This error only appears when using npx cypress run version:
![image](https://user-images.githubusercontent.com/18590594/88437756-75858900-ce07-11ea-8c3e-c708891495ce.png)

### Desired behavior:

Code should be interpreted the same, since its the same setup

### Test code to reproduce

Stated in current behaviour, video.mp4 file used with mimeType defined as video/mp4.
Wait was used for random debugging purposes, doesn't affect the test in any way.

### Versions

Cypress 4.10.0
Chrome Version 84.0.4147.89 (Official Build) (64-bit)
OS: Fedora Linux release 32 (Thirty Two) x86_64

**Comment by LeJeanbono** [comment]
What is this `GET /api/v2.0/videos` which is not call in the second time ?

**Comment by vbrundic** [comment]
Thats basically the video upload already starting, looks something like this
![image](https://user-images.githubusercontent.com/18590594/88475820-9814c080-cf33-11ea-969c-cfac8a72b15a.png)

**Comment by jennifer-shehane** [comment]
I can't actually recreate the issue as given. Can you provide the HTML to run the code against?

Just as a guess since I can't recreate, you might want to move the `trigger` outside of the `Cypress.Blob` function. You're missing async and sync code, so there's not gaurantee when you call the trigger that the code above has finished executing. If there's variability in the run, you may get unexpected results. 

```js
cy.get('input[type="file"]').then((subject) => {
  cy.fixture(videoPath, "base64").then((front) => {
    Cypress.Blob.base64StringToBlob(front, mimeType).then(function (blob) {
      var testfile = new File([blob], filename, { type: mimeType });
      var dataTransfer = new DataTransfer();
      var fileInput = subject[0];

      dataTransfer.items.add(testfile);
      fileInput.files = dataTransfer.files;
    });
  });
})
cy.get('input[type="file"]').trigger("change", { force: true });
cy.get("button").contains("Upload").click({ force: true });
cy.wait(15000);
```
