### ISSUE TITLE
Whoops, there is no test to run, even if already have test

### ISSUE THREAD

**Issue by leenItg** [cypress-io/cypress#8088]
### Current behavior:

my code

```js
/// <reference types="Cypress" />

describe('Post Resource', () => {
  it('Creating a New Post', () => {
    cy.viewport("macbook-15")

    cy.visit('https://www.ebay.com/');

    const search_Item = cy.get('#gh-ac').should('be.visible').should('be.enabled').clear().type('adidas shoes')
    search_Item.should('have.value', 'adidas shoes');
    const Value_Category = cy.get('#gh-cat').select('11450').should('have.value', '11450');
    cy.get('#gh-btn').should('be.visible').click()
    cy.get('#gh-ac').should('have.value', 'adidas shoes');
    cy.get('#gh-cat').should('have.value', '11450');
    cy.get('.s-item[data-view="mi:1686|iid:1"]').click();// here the issue
    cy.get('select[id="msku-sel-2"]').should('be.visible').contains('- Select -').select('10');
    cy.get('a[id="atcRedesignId_btn"]').should('be.visible').click();
    cy.get('.vi-overlayTitleBar').contains('1 item added to cart');
    cy.get('a[class="btn btn-scnd vi-VR-btnWdth-XL"]').contains('Go to cart').click();
  })
})
```

after my test reach this and open new page 

```js
cy.get('.s-item[data-view="mi:1686|iid:1"]').click();// here the issue
```
this error occurud 

![image](https://user-images.githubusercontent.com/66993565/88485666-3c245900-cf80-11ea-8963-b043ef6965ff.png)
 I tried chrome 84, firefox 78, electron 80 ,edge 84
and i get the same error 

### Desired behavior:

I want it to complete the test
### Versions
 Cypress: 4.10.0,
 operating system: windows 10
, browser: chrome 84, firefox 78, electron 80 ,edge 84
  

and I add this to  support index.js file

```js
import './commands'
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})
```

**Comment by leenItg** [comment]
problem solved by adding this to cypress.json
"experimentalSourceRewriting": true

**Comment by leenItg** [comment]
"experimentalSourceRewriting": true
should be **false** for all my project, and should be true just for this test,
and i have one cypress.json I'm ,u project, so all other files will fail if i put it true,
just this test will pass if i put it true
so I need another solution,
or how to get 2 cypress.json in one project

**Comment by jennifer-shehane** [comment]
@leenItg You'll need to restart the browser in between resetting `experimentalSourceRewriting`, so you'd have to run separate configuration or configuration file when running the specific file where this fix is needed. Some info here also on strategies: https://www.cypress.io/blog/2020/06/18/extending-the-cypress-config-file/#plugins-file 

```
cypress run --spec post-resource.spec.js --config-file source-rewrite.json
```

or 

```
cypress run --spec post-resource.spec.js --config experimentalSourceRewriting=true
```

Then run your other specs without this config.
