### ISSUE TITLE
Critical - Jira API call failing with 403 error

### ISSUE THREAD

**Issue by gitsaquib** [cypress-io/cypress#8091]
We are trying to update results in Jira from Cypress execution. Same API call is working fine from PostMan and RestAssured when I am trying to call same from Cypress it fails with 403 error - XSRF check failed

```js
var http = require("https");

describe('Launch Application', () => {
  it('WOX-4277', () => {
	var options = {
	  "method": "PUT",
	  "hostname": "jira.xxx.com",
	  "port": null,
	  "path": "/rest/zapi/latest/execution/41288/execute",
	  "headers": {
		"Content-Type": "application/json",
		"Authorization": "Basic XXXX",
		"Cache-Control": "no-cache"
	  }
	};

	var req = http.request(options, function (res) {
	  var chunks = [];

	  res.on("data", function (chunk) {
		chunks.push(chunk);
	  });

	  res.on("end", function () {
		var body = Buffer.concat(chunks);
		console.log(body.toString());
	  });
	});

	req.write(JSON.stringify({ status: '1' }));
	req.end();
 })
})
```

Same code is working fine from Postman and RestAssured

**Comment by Narretz** [comment]
This sounds like a problem with the JIRA API. Maybe this issue: https://confluence.atlassian.com/jirakb/rest-api-calls-with-a-browser-user-agent-header-may-fail-csrf-checks-802591455.html?

**Comment by gitsaquib** [comment]
Probably not, cypress is overriding User-Agent.

**Comment by jennifer-shehane** [comment]
Cypress doesn't override the User-Agent header, we send along the User-Agent header provided by the browser unless it is overridden in the `request` options or `userAgent` configuration. 

But yes, a User-Agent header is present in the request given in the original example, which may be the difference between requests initiated from Postman/RestAssured.

**Comment by gitsaquib** [comment]
I found the root problem, I am using baseURL cy.visit('https://jira.myjira.com'); and then calls API at the end then it works fine because Referer: https://jira.myjira.com/__cypress/iframes/integration/WebSample/iTest.js. While in case of cy.visit('https://google.com') Referer: https://google.com/__cypress/iframes/integration/WebSample/iTest.js

**Comment by jennifer-shehane** [comment]
Yeah, setting the `baseUrl` will change the top domain of the Test Runner - so that we can properly bypass CORS issues and other security checks. Can we close this as resolved then? 

This kind of explains some of that mechanism, but it doesn't really explain how this would affect calls inside the test if you never navigate to that url. https://on.cypress.io/best-practices#Setting-a-global-baseUrl

**Comment by gitsaquib** [comment]
This is not correct explanation though. I am run a test on my web application (http://myworld.myapp.com) and in after method I am trying to update result in Jira. Able to update results now using cy,request. I am facing error with POST cy.request for uploading screenshot in Jira. Here is sample code

cy.readFile('C:\\Users\\Dev\\Downloads\\screen1.jpg', 'base64').then(result => {
					cy.request({
						method: 'POST',
						preambleCRLF: true,
						postambleCRLF: true,
						url: `${apiBaseUrl}/attachment?entityId=${executionId}&entityType=EXECUTION`,
						multipart: [
						{ 
							body: '----headers'+result+'----headers'
						}
						],
						body: '----headers'+result+'----headers',
						headers: {
							'Authorization': 'Basic xxxx',
							'Cache-Control': 'no-cache',
							'Content-Type': 'multipart/form-data;boundary=----headers',
							'mimeType': 'multipart/form-data;boundary=----headers',
							'X-Atlassian-Token': 'nocheck',
							'User-Agent': 'test-agent',
							'encoding': 'base64',
							'Content-Length': '141226'
						}						
					  },
					  function (error, response, body) {
						if (error) {
						  return console.error('upload failed:', error);
						}
						console.log('Upload successful!  Server responded with:', body);
					  })
					}); 

This passes with 200 but nothing gets uploaded

**Comment by gitsaquib** [comment]
@jennifer-shehane pls review its urgent

**Comment by gitsaquib** [comment]
@jennifer-shehane any help pls

**Comment by gitsaquib** [comment]
Any one please reply

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.

This seems to be an issue with not sending the expected data to Jira in the format expected. I'm not familiar enough with Jira's API to say what the issue is. I see some issues in Jira when searching 'xsrf check failed jira' though.

**Comment by Ahmar828** [comment]
> I found the root problem, I am using baseURL cy.visit('https://jira.myjira.com'); and then calls API at the end then it works fine because Referer: https://jira.myjira.com/__cypress/iframes/integration/WebSample/iTest.js. While in case of cy.visit('https://google.com') Referer: https://google.com/__cypress/iframes/integration/WebSample/iTest.js

Can you please share your entire code?

**Comment by Suryakd143** [comment]
Add 'User-Agent': 'test-agent', in headers

**Comment by hakim1901** [comment]
> This is not correct explanation though. I am run a test on my web application (http://myworld.myapp.com) and in after method I am trying to update result in Jira. Able to update results now using cy,request. I am facing error with POST cy.request for uploading screenshot in Jira. Here is sample code
> 
> ```js
> cy.readFile('C:\\Users\\Dev\\Downloads\\screen1.jpg', 'base64').then(result => {
>   cy.request({
>     method: 'POST',
>     preambleCRLF: true,
>     postambleCRLF: true,
>     url: `${apiBaseUrl}/attachment?entityId=${executionId}&entityType=EXECUTION`,
>     multipart: [
>       {
>         body: '----headers' + result + '----headers'
>       }
>     ],
>     body: '----headers' + result + '----headers',
>     headers: {
>       'Authorization': 'Basic xxxx',
>       'Cache-Control': 'no-cache',
>       'Content-Type': 'multipart/form-data;boundary=----headers',
>       'mimeType': 'multipart/form-data;boundary=----headers',
>       'X-Atlassian-Token': 'nocheck',
>       'User-Agent': 'test-agent',
>       'encoding': 'base64',
>       'Content-Length': '141226'
>     }
>   },
>     function (error, response, body) {
>       if (error) {
>         return console.error('upload failed:', error);
>       }
>       console.log('Upload successful!  Server responded with:', body);
>     })
> }); 
> ```
> 
> This passes with 200 but nothing gets uploaded

Can you please share entire code to integrate cypress with Jira, I have used cypress-zapi-util, but not able to update result on Jira

**Comment by poponuts** [comment]
I am having this issue too. It works on Postman but not on Cypress. With automated integration nowadays - especially with JIRA, this seems like an important functionality that can be addressed.

**Comment by jeremyLi1990** [comment]
this.headers.put("X-Atlassian-Token", "no-check");
this.headers.put("User-Agent", "api-agent");

这样修改headers生效了
