### ISSUE TITLE
TypeError: fs.existsSync is not a function even when using Tasks

### ISSUE THREAD

**Issue by kzaiwo** [cypress-io/cypress#8098]
I am using Cypress to test my Electron application.
Since Cypress uses the browser mode, ```FS``` is not supported.

So I am getting this error:
```
Error in mounted hook: "TypeError: fs.existsSync is not a function"
```

I know Electron is not yet fully supported, but specifically for my need to use ```fs```, I found this on the documentation:

> https://docs.cypress.io/api/commands/task.html#Event

So I added this on my test:
```js
it('Sample test', () => {
  cy.task('readSettingsJson', settingsFolder).then((content) => { 
    // This can print the JSON file contents correctly
    console.log('content = ' + content) 
  })
})
```

And on my ```plugins/index.js```:
```js
 on('task', {
    readSettingsJson(foldername) {
      if (!fs.existsSync(foldername)) {
        fs.mkdirSync(foldername, { recursive: true })
        // some command to copy the file
      } else {
        // This is what I am testing at this moment
        return fs.readFileSync(path.join(filename, '/settings.json'), 'utf8')
      }

      return null
    }
 })
```
However, it doesnt seem to work. I still get the error:
```
Error in mounted hook: "TypeError: fs.existsSync is not a function"
```
And despite the test printing (console.log in the test) the json file correctly, my app still can't load the JSON file.

Am I missing anything? Help please! Thank you!

**Cypress Version:** 4.3.0
**Browser:** Electron

**Comment by jennifer-shehane** [comment]
This seems isolated to your running and testing within Electron app (or some other variable in your project) - as this is not reproducible with the code provided. Some comments in Electron mention changing the require statements maybe helping. https://github.com/electron/electron/issues/7300#issuecomment-274269710

Closing as we don't support testing Electron apps out of the box.
