### ISSUE TITLE
.not() command performs differently from :not() selector

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#81]
I am trying to chain the `.not()` command off of a subject with 2 elements. One of the elements will be removed from the DOM (my expected behavior). I wanted to ensure that the remaining element did not have class `empty`. An error throws on the `.not` command due to the first element being removed and the `.not` command is never run on the second element. 

**Example Code I want to write**
```coffeescript
    it "adds row on click of link in empty [1yo]", ->
      cy
        .get("[data-js='destroy-selection']:first").click()
        .get(".empty").find("[data-js='new-selection-empty']").click()
        .get(".selections-table>tbody>tr") ## returns 2 trs
          .not(".empty").should("have.length", 1) ## want to target tr without class .empty
```

**Command Log Result**
<img width="525" alt="screen shot 2015-11-09 at 10 20 50 am" src="https://cloud.githubusercontent.com/assets/1271364/11037424/a8ba84c0-86cb-11e5-9a94-42340c95d47a.png">

If I change my code to use a `:not()` selector, the desired behavior results. This is the behavior I was expecting with the `.not` command. 

**Code with `:not` selector**
```coffeescript
    it "adds row on click of link in empty [1yo]", ->
      cy
        .get("[data-js='destroy-selection']:first").click()
        .get(".empty").find("[data-js='new-selection-empty']").click()
        .get(".selections-table>tbody>tr:not(.empty)") ## returns 1 tr
            .should("have.length", 1)
```

**Command Log Result**
<img width="534" alt="screen shot 2015-11-09 at 10 26 28 am" src="https://cloud.githubusercontent.com/assets/1271364/11037571/60cc904e-86cc-11e5-86c0-0a954ae4e430.png">

Am I just improperly using `.not()` or is this unexpected behavior of Cypress?

**Comment by brian-mann** [comment]
This is the expected behavior of Cypress. It does not allow you to continue to chain methods on DOM objects which become detached.

There is a **chance** that after your click, the existing row is removed, and therefore when `cy.not` is invoked it sees the current subject has been detached and throws an error.

When this situation happens you need to implement a guard to prevent Cypress from continuing until the state is what you expect.

```coffeescript
it "adds row on click of link in empty [1yo]", ->
      cy
        .get("[data-js='destroy-selection']:first").click()
        .get(".empty").find("[data-js='new-selection-empty']").click()
         
         ## do not resolve until the tr's have a length of 1
        .get(".selections-table>tbody>tr").should("have.length", 1) 
```
