### ISSUE TITLE
Missing widely supported ES2017 features

### ISSUE THREAD

**Issue by fluffywaffles** [cypress-io/cypress#810]
- Operating System: Linux kernel 4-something
- Cypress Version: 1.0.2
- Browser Version: Electron 53 (? that version number doesn't make sense to me, since Electron releases usually follow semver)

### Is this a Feature or Bug?

Hard to say. Seems like Electron is out of date. Could be that my system is configured incorrectly.

Cypress fails to open Chrome stable 62 at all, although the behavior does not reproduce in my own testing in Chrome stable 62.

### Current behavior:

TypeError thrown in console when attempting to use `Object.getOwnPropertyDescriptors()`. In fact, ES2017 features in the [kangax compat table](http://kangax.github.io/compat-table/es2016plus/) are all missing.

### Desired behavior:

Cypress is up-to-date with browsers (which support all of ES2017 except shared memory, even a couple versions back).

### How to reproduce:

Run cypress and try to run `Object.getOwnPropertyDescriptors({ a: 5 })` in the console

#### Test code:

N/A

**Comment by brian-mann** [comment]
We call it Electron 53 and provide an explanation inside of the GUI.

![screen shot 2017-10-25 at 12 53 56 pm](https://user-images.githubusercontent.com/1268976/32011723-9762e086-b983-11e7-82f5-31aab316c49f.png)

53 is the version of Chromium that it is. The number of ES* features a browser supports is always based on what version its running.

I don't think there's anything to do here - if Chromium 53 doesn't support it, then it simply doesn't support it.

There is going to be a new release of Electron relatively soon which will bump up the Chromium version into the 60's. When that comes out we'll update to that.

We chose not to use the actual version of Electron because its irrelevant - we turn off every single Electron feature to make it behave exactly like a real desktop browser - and therefore the version of Chromium is the only thing that matters.

I'm not sure if there is a polyfill for this method, but you'd likely need to do that anyway to support other browsers.

Could you elaborate on why Cypress fails to open Chrome 62? Electron is simply the bundled / default browser that you don't have to install on your own. Cypress can launch any Chrome browser.

https://docs-staging.cypress.io/guides/core-concepts/launching-browsers.html#

**Comment by fluffywaffles** [comment]
I can't really elaborate on its not being able to open Chrome 62. It just hangs, spinning forever. The terminal does not provide any messages. I am trying to run the `google-chrome-stable` binary on linux. It works fine when I run it myself, but not when Cypress tries. Is there a way to increase log verbosity?

**Comment by brian-mann** [comment]
https://docs.cypress.io/guides/guides/debugging.html#Debug-the-Command-Line
https://docs.cypress.io/guides/guides/command-line.html#Debugging-Commands

**Comment by fluffywaffles** [comment]
Cypress finds my browser:
```
  cypress:launcher checking one browser Google Chrome Stable +1ms
  cypress:launcher looking up Google Chrome Stable on linux platform +0ms
  cypress:launcher looking using command google-chrome-stable --version +0ms
  cypress:launcher Google Chrome 62.0.3202.62 +44ms
  cypress:launcher setting major version for {name:Google Chrome Stable,version:62.0.3202.62,path:google-chrome-stable} +1ms
```

Then logs:
```
cypress:server launching project in browser Google Chrome Stable +3ms
```

Then the following messages repeat on a loop until I kill the process:
```
  cypress:server:timers child received timer id 6 +2ms
  cypress:server:files looking for test files in the integration folder xxx/cypress/integration +1ms
  cypress:server:files found test file xxx/cypress/integration/spec.js +4ms
  cypress:server:files found 1 spec files +1ms
  cypress:server:files [ { name: 'spec.js',
  cypress:server:files     path: 'cypress/integration/spec.js',
  cypress:server:files     absolute: 'xxx/cypress/integration/spec.js' } ] +0ms
  cypress:server:timers child sending timer id 6 +3s
  cypress:server:timers clearing timer id 6 from queue { '6': { args: [], ms: 2500, cb: [Function: cb] } } +3s
  cypress:server:timers queuing timer id 6 after 2500 ms +1ms
  cypress:server:files looking for test files in the integration folder xxx/cypress/integration +0ms
```

Nothing else happens.

**Comment by fluffywaffles** [comment]
Strangely, if I run
```
λ npx cypress run --browser Google Chrome Stable
```

the command executes, but then the same TypeError occurs. This doesn't make much sense, seeing as [Chrome 62 supports 100% of ES2017+](http://kangax.github.io/compat-table/es2016plus/#chrome62).

**Comment by brian-mann** [comment]
Put a debugger in front of `getOwnPropertyDescriptors` in your app code and go inspect it. Could be something else causing this.

Also do this in your console inside and outside of Cypress - to verify that method is available.

![screen shot 2017-10-25 at 1 44 23 pm](https://user-images.githubusercontent.com/1268976/32013950-a8a9b6d8-b98a-11e7-8873-433e4c250076.png)

**Comment by fluffywaffles** [comment]
The application works as intended in Chrome 62. Object.getOwnPropertyDescriptors is available.

Inside of the cypress GUI nothing actually loads. Only by using `cypress run` do I get any output, and that output occurs without any windows rendering to the screen. It is as if `cypress run --browser Google Chrome Stable` runs headlessly, which would seem unlikely. Placing a `debugger` statement does not cause `cypress run --browser Google Chrome Stable` to hang; in fact, it behaves exactly the same. Nothing is rendered, and the terminal reports a single test failure due to the TypeError.

**Comment by brian-mann** [comment]
Right. When you use `cypress run` its running Electron headlessly which does not have that method.

I thought you were saying passing the `--browser` option was launching Chrome. But I understand now it is not.

I think the only problem here is that its not launching the Chrome installed on your computer. Nothing else is wrong.

**Comment by fluffywaffles** [comment]
I believe that's the correct diagnosis. But, as stated, Cypress *finds* the binary, even going so far as to list it as an option in the GUI. I'm not sure what I can do to convince it to actually *run* the binary.

**Comment by brian-mann** [comment]
Maybe just restart... who knows...

**Comment by brian-mann** [comment]
I'm going to close this issue - you can open a separate one for not being able to launch Chrome. The code to do all of that is here:

https://github.com/cypress-io/cypress/tree/develop/packages/launcher

My guess is that its some sort of weird linux issue.
