### ISSUE TITLE
Detect and capture env vars from AWS CodeBuild including ciBuildId

### ISSUE THREAD

**Issue by danbroooks** [cypress-io/cypress#8101]
The documentation lists CodeBuild under "CI environment variables" in this list here:

https://github.com/cypress-io/cypress-documentation/blame/develop/source/guides/guides/parallelization.md#L246

Which was recently changed in the last month. However, when running cypress with the `--parallel` flag in this environment cypress (`4.11`) puts out this error:

```
962 | You passed the --group or --parallel flag but we could not automatically determine or generate a ciBuildId.
963 |  
964 | The --group flag you passed was: admin
965 | The --parallel flag you passed was: true
966 |  
967 | In order to use either of these features a ciBuildId must be determined.
968 |  
969 | The ciBuildId is automatically detected if you are running Cypress in any of the these CI providers:
970 |  
971 | - appveyor
972 | - azure
973 | - bamboo
974 | - bitbucket
975 | - buildkite
976 | - circle
977 | - codeshipBasic
978 | - codeshipPro
979 | - concourse
980 | - drone
981 | - githubActions
982 | - gitlab
983 | - goCD
984 | - googleCloud
985 | - jenkins
986 | - semaphore
987 | - shippable
988 | - teamfoundation
989 | - travis
990 | - netlify
991 |  
992 | Because the ciBuildId could not be auto-detected you must pass the --ci-build-id flag manually.
```

And in the cypress code it does not list `CodeBuild`:

https://github.com/cypress-io/cypress/blob/4054e72c3bc1ecfb5308156b5c782077d96358dc/packages/server/lib/util/ci_provider.js#L82-L105

I am confused why this documentation has been changed like this when it does not appear to be a supported CI provider?

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-172) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Yeah, this should not have been added to that portion of the docs since this is not built into Cypress to automatically detect this build ID. 

- I will revert this docs change. 
- We can leave this issue open for Cypress to automatically detect AWS CodeBuild, and pull in it's env variables for use in the Cypress Dashboard including the `CODEBUILD_BUILD_ID`. https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

**Comment by danbroooks** [comment]
Would implementing a PR for this simply be mirroring something like this change https://github.com/cypress-io/cypress/commit/3c37b8be8cc76b3add2de262d37e7aedda137b11 only for CodeBuild and the code build env value mentioned in those erroneous docs? I guess whoever updated that documentation assumed codebuild was simply missing and listed codebuilds build is env var in that list or something? If the change is as straightforward as that I would be happy to male this PR

**Comment by jennifer-shehane** [comment]
@danbroooks Pretty much, except you'd do a check to ensure it's codebuild similar to the check for `isConcourse` - that there's an env var present that starts with `CODEBUILD_`. A PR would be great!

**Comment by estefafdez** [comment]
One question about this one, if I'm using AWS CodeBuild with a Docker container, should the --parallel flag works even when I'm not running the tests against the Cypress Dashboard? thanks!

**Comment by jennifer-shehane** [comment]
Using the `--parallel` flag allows Cypress to parallelize tests during `cypress run`. It requires recording to the Dashboard (passing the `--record` key). 

If you're talking about running parallel builds in AWS CodeBuild, that would be outside of Cypress.

**Comment by estefafdez** [comment]
Yes, it's outside Cypress (considering Cypress the Cypress Dashboard and not having record key). 

Any plan to release the parallelization of tests outside Cypress to be able to run the test in parallel locally (in a Docker container) for example or in Jenkins/AWS? Thanks.

**Comment by danbroooks** [comment]
@jennifer-shehane ah I see, so this `--parallel` flag is related to use with the cypress dashboard, I was thinking this flag was required in order to get the tests to run in parallel for these CI providers, but I see how it explains this in the documentation. This is my bad for skim reading thfsae docs :joy: 

I have thrown together this suggested PR now, so happy to submit it still. However, do you think it may also be worth making this more obvious on the parallelisation page of the documentation? Something like a warning box like on this page? https://docs.cypress.io/guides/guides/cross-browser-testing.html#Continuous-Integration-Strategies

I'd be happy to do a PR for this also, but also fine if it just serves me right skim reading documentation :joy:

**Comment by estefafdez** [comment]
thanks @jennifer-shehane , I will have a look :)
