### ISSUE TITLE
On Button click File download successfully, but script does not continue with next steps due to this error

### ISSUE THREAD

**Issue by CypressDashboard** [cypress-io/cypress#8107]
### Desired behavior:

Hope you are doing good.
I am facing issue in Cypress.
On Button click File download successfully, but script does not continue with next steps due to this error.
I am Stuck and I want to get out of it, could you please help me.
### Test code to reproduce
```js
cy.get('[data-puppeteer="dlgPrintOptions_ToolBar_pbPrint"]').click()
cy.wait(5000)
cy.get('[data-puppeteer="SalReportPreview_ToolContainer_pdf"]').click()
cy.get("div[name='maximize-button']").click()
cy.wait(15000)
```

### Versions

"cypress": "^4.0.2",

![image](https://user-images.githubusercontent.com/68445518/88681383-25f8d300-d10f-11ea-97a1-eded08f9bfe6.png)

**Comment by jennifer-shehane** [comment]
Cypress doesn't natively support downloading files. I would refer to #949 for workarounds.

**Comment by hhaidar** [comment]
Adding `target="_blank"` to links might help.

**Comment by jennifer-shehane** [comment]
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).
