### ISSUE TITLE
iFrame elements that focus, when calling `.type()` are actually blurred (when Test Runner is not focused)

### ISSUE THREAD

**Issue by martynchamberlin** [cypress-io/cypress#8111]
### Current behavior:
Currently if you load a page that has an iFrame, and that iFrame has an input that you programmatically `focus`, attempting to focus via Cypress testing causes the input to blur instead. 

### Desired behavior:
When focusing on an input that is already focused, a blur should not occur; it should remain focused. 

### Test code to reproduce
https://github.com/cypress-io/cypress-test-tiny/pull/61

### Versions
macOS Catalina, version 10.15.5
Chrome version 84.0.4147.89
Cypress package version: 4.10.0
Cypress binary version: 4.10.0

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-190) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
I can recreate this with the following code - have to defocus the window in order for the test to fail.

`spec.js`

```js
it('fails if you focus off the Cypress window', () => {
  cy.visit('index.html')
  cy.get('iframe')
    .its('0.contentDocument.body').should('not.be.empty')
    .then(cy.wrap)
    .find('#input')
    .type(42)
    .should('have.value', 42);
});
```

`index.html`

```html
<html>
<body>
  <iframe src="iframe.html">
</body>
</html>
```

`iframe.html`

```html
<html>
<body>
  <input id="input" />
  <script>
    document.querySelector('#input').focus();
  </script>
</body>
</html>
```

<img width="722" alt="Screen Shot 2020-07-29 at 2 38 27 PM" src="https://user-images.githubusercontent.com/1271364/88774243-33629b80-d1a9-11ea-9fc0-38bce2d5aa89.png">

**Comment by jennifer-shehane** [comment]
The code for this is done in [cypress-io/cypress#8112](https://github.com/cypress-io/cypress/pull/8112), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
