### ISSUE TITLE
Documentation/recipes to obtain same screenshot in different browsers/modes/platforms

### ISSUE THREAD

**Issue by askirmas** [cypress-io/cypress#8118]
### Current behavior:
Material-icons font gives the same result everythere, Roboto makes troubles. I tried with and without anti-aliasing properties and `@font-face { src: local('Roboto') }` but looks like no difference after these 4 runs.

1. Firefox headless(expected) vs headed (actual)

https://github.com/askirmas/no-js/blob/master/minimal-material/cypress/integration/elevation.ts#L12-L13
![cypress window](https://user-images.githubusercontent.com/5372643/88792336-be409780-d1a3-11ea-8eee-0eba975e7aa3.png) 

Diff:
![elevation 0 #0 diff](https://user-images.githubusercontent.com/5372643/88794027-7707d600-d1a6-11ea-8347-e5f4fef08ca3.png)

2. Firefox headless vs Chrome headless

https://github.com/askirmas/no-js/blob/master/minimal-material/cypress/integration/typography.ts#L12-L13
![cypress firefox chrome](https://user-images.githubusercontent.com/5372643/88792364-c993c300-d1a3-11ea-81e5-b1c0aa73054c.png)

### Desired behavior:
Keep precision of comparison as high as possible with documented hints how to do it. Maybe browser flags?

### Test code to reproduce
Appeared during work in https://github.com/askirmas/no-js/blob/master/minimal-material/package.json#L9-L10 

It is not small - later can prepare minimal example

### Versions

Ubuntu 18, Cypress 4.11, Firefox 78, Chrome 84

**Comment by jennifer-shehane** [comment]
I wouldn't recommend comparing screenshots across different environments - so comparing Firefox screenshots with Chrome screenshots or Firefox headless screenshots with Firefox headed screenshots or Chrome in Windows screenshots with Chrome in Mac screenshots. 

There are just so many variables involved - that they will never be identical. I'd recommend setting a baseline of what you want the screenshots to be for each environment and then comparing future screenshots against that baseline - per environment. 

I very much agree that we need to improve our docs for strategies on visual testing - there is an issue here in our docs: https://github.com/cypress-io/cypress-documentation/issues/2160 

If you can, please comment in that issue. This issue will be closed in this repository as this repo is solely for Cypress bugs and feature requests in the product.
