### ISSUE TITLE
Check downloaded binary file size

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#812]
When downloading binary, it might be corrupted / intercepted by a proxy. Sometimes even CDN has a hiccup like shown below from a test project run
```
Instead we will install version: https://cdn.cypress.io/beta/binary/1.0.3/win64/appveyor-develop-7b4c223233ca8eb6e147dc5e89b30a01061f6581-11678682/cypress.zip
Note: there is no guarantee these versions will work properly together.
Installing Cypress (version: https://cdn.cypress.io/beta/binary/1.0.3/win64/appveyor-develop-7b4c223233ca8eb6e147dc5e89b30a01061f6581-11678682/cypress.zip)
[?25l[18:21:09]  Downloading Cypress     [started]
[18:21:16]  Downloading Cypress     [completed]
[18:21:16]  Unzipping Cypress       [started]
[18:22:16]  Unzipping Cypress       [completed]
[18:22:16]  Finishing Installation  [started]
[18:22:16]  Finishing Installation  [completed]
[?25h
You can now open Cypress by running: node_modules\.bin\cypress open
https://on.cypress.io/installing-cypress
[?25h
> node-sass@4.5.3 postinstall C:\projects\cypress-test-example-repos\cypress-example-piechopper\node_modules\node-sass
> node scripts/build.js
Binary found at C:\projects\cypress-test-example-repos\cypress-example-piechopper\node_modules\node-sass\vendor\win32-ia32-57\binding.node
Testing binary
Binary is fine
npm ERR! path C:\projects\cypress-test-example-repos\cypress-example-piechopper\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall lstat
```

Need to validate downloaded zip file size. If it < 50 MB something went terribly wrong.

**Comment by brian-mann** [comment]
This is why we should use a checksum / sha like other big files do :P

You would just verify the integrity of that and boom, done.

**Comment by bahmutov** [comment]
yeah, but where do we get the checksum from - the only way I see is embed it into NPM package json file for example.

**Comment by brian-mann** [comment]
You put it in the zip or you add another request to the NPM package which
downloads it from our server alongside the zip. You definitely do not want
to embed it in the NPM package itself!

**Comment by bahmutov** [comment]
yeah, this is secondary then - because if zip is corrupted or we cannot download it, we cannot validate the checksum. If we cannot download the binary zip, we might be able to download a separate checksum file either. So checking filesize might be the fastest way to determine if download failed.

**Comment by MarcLoupias** [comment]
> You definitely do not want to embed it in the NPM package itself!

That's maybe a stupid question but i don't understand why you could not add something like this at binaries build time in your `package.json` : 

```javascript
"cyBinariesChecksums": {
    "darwin": "34dc8e1804c0a14aeb717e91af443219be617042",
    "linux": "ba324ca7b1c77fc20bb970d5aff6eea9377918a5",
    "win32": "d09fffb5db2d7f631ba43ccc256617b444056d2e"
}
```

then hash the downloaded binary at install time and compare it to the right platform checksum.

Is adding custom metadata in a `package.json` file considered a bad practice ? Or maybe the checksum duration that could be too long ?

**Comment by bahmutov** [comment]
We could but then we would have to build package json after all binaries are built which introduces CI ordering difficulty
