### ISSUE TITLE
Drag shift select with cypress not working

### ISSUE THREAD

**Issue by wasiqkhan786** [cypress-io/cypress#8129]
### Current behavior:

This is protractor code which i am trying to convert

```js
return browser.actions()
  .mouseMove(element(by.id("map")), { x: left, y: top })
  .keyDown(protractor.Key.SHIFT)
  .mouseDown()
  .mouseMove(element(by.id("map")), { x: right, y: bottom })
  .mouseUp()
  .keyUp(protractor.Key.SHIFT).perform()
```

### Desired behavior:

below code i converted to cypress from above code protractor but its not giving any error neither selecting the given range(rubber band)

```js
return cy.get('#map')
  .trigger('mousedown', { button: 0, force: true, release: false })
  .trigger("keydown", { keycode: 16, force: true, release: false })
  .trigger('mousemove', { clientX: left, clientY: top })
  .trigger('mousemove', { clientX: right, clientY: bottom }).click();
```

**Comment by jennifer-shehane** [comment]
We wouldn't be able to help with this code without the provided application code to run against. Can you provide the application or a sample HTML code to run the tests against?

If you're trying to press the SHIFT key, you'd want to use the `{shift}` modifier key as part of `.type()` https://on.cypress.io/type#Modifiers

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by wasiqkhan786** [comment]
yes i cant use the type shift key it gives me an error that it should be some typeable but in my case iam calling on ''#map'.So i use trigger keydown.is there any way i can use type with map?

**Comment by wasiqkhan786** [comment]
i tried with this ass well but its not working either
            cy.get("#map").trigger('mousemove', left, top, {which: 1, force: true,delay:10});
            cy.wait(1000);
            cy.get('body').type('{shift} ',{release:false});

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example and we will consider reopening the issue.
