### ISSUE TITLE
Add ability to point installed Cypress app at staging environment

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#813]
### feature

We have official "production" API but also we have cutting edge "staging" API. When using Cypress app installed as a dependency, the "production" is hardcoded in the `app/index.js` that Electron loads

```js
process.env.CYPRESS_ENV = 'production'
require('./packages/server')
```
We should only set this variable if it is not set already.
```js
if (!process.env.CYPRESS_ENV) {
  process.env.CYPRESS_ENV = 'production'
}
require('./packages/server')
```
This will allow us to test staging environment better and deploy API changes with confidence.

```
npm install
CYPRESS_ENV=staging $(npm bin)/cypress run
```

Note: check how `ts/register.js` decided when to load `ts-node` hook. Right now it assumes that in production we do not need TypeScript transpile. With above change we might need to transpile even in production and staging (when we develop locally and want to use remote API)

**Comment by brian-mann** [comment]
Fixed in [`1.0.3`](https://docs.cypress.io/guides/references/changelog.html#1-0-3).
