### ISSUE TITLE
Adding "pass/fail" on video recording filename

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#8131]
### Current behavior:

For now, the video recording filename is locked to `videos/**/*.mp4`

### Desired behavior:

It would be nice to do something similar with the screenshot `screenshots/**/*(failed).png`

Such as `videos/**/*(fail 2/5).mp4`

So we can do targeted uploading to save some CI time.

**Comment by jennifer-shehane** [comment]
Duplicate of #6998
