### ISSUE TITLE
Test crash while using yarn cypress run --headed

### ISSUE THREAD

**Issue by Hatamleh** [cypress-io/cypress#8139]
### Current behavior:

The test will crash when I run the test using --headed and I maximize the window to full screen on mac.

![cypress crash](https://user-images.githubusercontent.com/49985030/89015733-d46f6480-d317-11ea-946c-edcf76eb024c.gif)

![cypress crash 2](https://user-images.githubusercontent.com/49985030/89016150-87d85900-d318-11ea-848a-314d06505a40.gif)

### Desired behavior:

It should work as expected

### Test code to reproduce

1- Run the test using `yarn cypress run --headed`
2- Maximize the window to full screen
--> The test will crash with an error "The Test Runner unexpectedly exited via an exit event with signal SIGSEGV"

### Versions

Cypress: 4.11.0

**Comment by jennifer-shehane** [comment]
I can't recreate the issue as described. I've included a video of running Cypress Electron headed and maximizing the screen. I tried running via terminal and VSCode terminal.

Likely there is something specific to your project outside of just a normal test run that is making this crash when you maximize. Please provide a fully reproducible example - a repo to run exhibiting the behavior. 

![](http://g.recordit.co/8W9ZvJfxa0.gif)

My test code

```js
it('visit', () => {
  cy.visit('https://example.cypress.io')
})
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
