### ISSUE TITLE
cypress is not running error is spawn EPERM 

### ISSUE THREAD

**Issue by piyushetech** [cypress-io/cypress#8142]
I have installed cypress it is not running

<img width="506" alt="error" src="https://user-images.githubusercontent.com/12976195/89030448-1a471f80-d34e-11ea-9136-ddae96589c66.PNG">

**Comment by jennifer-shehane** [comment]
EPERM is a permissions error. Opening Cypress will require write permissions, you'll need to verify the correct permissions are set.

Duplicate of #7640
