### ISSUE TITLE
Cypress start-up is extremely slow when using OpenVPN connection

### ISSUE THREAD

**Issue by anjhinz** [cypress-io/cypress#8149]
### Current behavior:

While on an OpenVPN connection, when we start the cypress UI using cypress open for a test that only calls `cy.visit('https://www.google.com');` (or any Url) before all tests, then checks for the existence of a button, the start up time for the cypress UI is over 1 minute 15 seconds (at that point, the test times out after 60 seconds because the `visit()` call has not completed).

If you keep the test window open and re-run the test, the test completes in only 3 seconds.

If we disconnect from the VPN, and close Cypress and do the same steps, it only takes about 10 seconds for the first run, and the same ~ 3 seconds for repeating the test in the already opened window.
 
Our `cypress.json` file is empty except for setting `baseUrl` to `https://www.google.com`. We can reproduce this with an empty project and any URL.

I don't have any data, but this didn't seem to be an issue with earlier versions of cypress, say around 3.x. If we had started building our suites and it was this slow, we would probably would have chosen a different framework, but at the time it was extremely speedy and a huge improvement over Protractor, so we have re-written many of our end to end tests. In the past 6 months or so, it seems like this start up time has gotten worse, even though our VPN situation has remained the same.

Thank you for any help you can provide for us, and I can give you full output logs of both tests (with or without OpenVPN connection)  if you need them.  

### Desired behavior:

Running a test suite in cypress while using OpenVPN should not take any longer than running it without VPN, especially because running the test itself is not significantly slower - but the initial start up of the browser window is 7-8 times slower.

This sounds petty, but when we are developing tests, having to wait this long on each iteration is really a pain, and we have to make sure to have a special timeout of 100 seconds for the first visit call of all of our test suites.

### Test code to reproduce

```js
describe('VPN Test', () => {
    before(() => {
        cy.visit('https://www.google.com/');
    });

    it('should load', () => {
        cy.get('input[name="btnK"]').should('be.visible')
    });
});
```

### Versions

This is using Chrome 84 on Windows 10 and Cypress 4.11.0 (latest).

**Comment by ericand1** [comment]
I work alongside anjhinz and thought it may be worth noting that I've noticed it seems to get hung up on the initial connection/SSL stage in network requests.  Cypress seems to wait for that initial connection when you blacklist resources, so that has not be a viable workaround for us.

![image](https://user-images.githubusercontent.com/65682749/89068081-c298bc00-d32d-11ea-9d09-d6d82fc2c2cb.png)

**Comment by jennifer-shehane** [comment]
I'm not using OpenVPN specifically, but using a VPN, I haven't seen this slowdown. These tests finish in 6 seconds for me. 

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here? This may show where the timing is going. 

Is this happening during `cypress open`, `cypress run` or both.

**Comment by anjhinz** [comment]
Hi Jennifer!

Attached the logs, hopefully the filenames are self-explanatory.

I also bumped to 4.12.0 before running these tests.

[cy_vpn_test_logs.zip](https://github.com/cypress-io/cypress/files/5018943/cy_vpn_test_logs.zip)

Thanks!
-Andy

**Comment by ericand1** [comment]
I have not noticed this when using `cypress run` and a few quick tests runs today ran in the 5 - 8 seconds we're seeing. It's pretty consistent when running `cypress open` though.

**Comment by jennifer-shehane** [comment]
Yah, I am able to reproduce this during `cypress open` on the first run behind a VPN. I don't understand what it's spending it's time doing. I can't always recreate it for some reason.

### Not behind VPN

<img width="674" alt="Screen Shot 2020-08-18 at 2 34 30 PM" src="https://user-images.githubusercontent.com/1271364/90487316-4f31df80-e160-11ea-9529-55e3f22b3bf4.png">


### Behind VPN (first run)

<img width="676" alt="Screen Shot 2020-08-18 at 2 36 20 PM" src="https://user-images.githubusercontent.com/1271364/90487328-55c05700-e160-11ea-81cd-f2e59551d8fc.png">


### Behind VPN (refresh)

<img width="677" alt="Screen Shot 2020-08-18 at 2 36 35 PM" src="https://user-images.githubusercontent.com/1271364/90487341-59ec7480-e160-11ea-961e-58cbc4fb7985.png">

**Comment by samueldcs** [comment]
Any news on this?
Works perfectly on Linux, but my colleague using Windows struggles with this.

**Comment by anjhinz** [comment]
Any chance there is any progress on this?

**Comment by radhakrishnanakireddy** [comment]
yeah, we have same issue with openvpn with MAC.
