### ISSUE TITLE
Fetch mock doesn't work with severals requests

### ISSUE THREAD

**Issue by bonomiandreia** [cypress-io/cypress#8158]
### Current behavior:
I have two requests doing different things, for some reason all requests are being "mock". The Second request stopped working when I used fetch mock.
<img src="https://user-images.githubusercontent.com/39713034/89124137-f6e5b700-d4aa-11ea-9957-15f9f9e1766c.png" width="500" height="300">
Console log on cypress in second request
<img src="https://user-images.githubusercontent.com/39713034/89124233-c5b9b680-d4ab-11ea-813a-2e8f00cd4f09.png" width="500" height="300">

(in localhost, they are working perfectly). I saw all examples on internet with only one request.

### Desired behavior:
I guess should have some way to do it separately. It isnt clear if I can mock `checkIfUrlIsAvailable` because this fetch doesn't bring information on screen, only check if service is online, would be cool if I can mock, because my test is testing if after service is online, my screen works well.
### Test code to reproduce

```js
it('click on button continue if service is online', () => {
  cy.fixture('mock-names').then((list) => {
    mock = list;
  });
  cy.visit('/payment', {
    onBeforeLoad(win) {
      cy.stub(win, 'fetch').resolves({
        json: cy.stub().resolves(mock),
      })
    }
  })
});
```
I tried:
```js
cy.stub(win, 'fetch', "nameFunctionHere").resolves({
  json: cy.stub().resolves(mock),
})
```
and tried:
```js
it('click on button continue if service is online', () => {
  cy.fixture('mock-names').then((list) => {
    mock = list;
  });
  cy.fixture('mock-service-online').then((list) => {
    mockService = list;
  });
  cy.visit('/payment', {
    onBeforeLoad(win) {
      cy.stub(win, 'fetch').resolves({
        json: cy.stub().resolves(mock),
        json: cy.stub().resolves(mockService),
      })
    }
  })
});
```
My inicial code on svelte bring data:
```js
onMount(() => {
  getNames();
  checkIfUrlIsAvailable();
})
```

first fetch is bring me names and second are checking if other service is online.
I guess should have some way to do it separately.

### Versions

Running Chrome 84
"cypress": "^4.9.0"
Mac Catalina 10.15.5
"sapper": "^0.27.16",
"svelte": "^3.23.2"

**Comment by jennifer-shehane** [comment]
@bonomiandreia Have you looked at this example? You can use the `withArgs` to be more specific about what you match in stubbing. https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__window-fetch/cypress/integration/stub-fetch-spec.js

**Comment by bonomiandreia** [comment]
![image](https://user-images.githubusercontent.com/39713034/91338251-0951c880-e7ab-11ea-9df6-e9f13cb8bfe9.png)
![image](https://user-images.githubusercontent.com/39713034/91338338-28e8f100-e7ab-11ea-9965-b22e3ba18593.png)
```
 before(() => {
        cy.visit('/payment?number=300', {
            onBeforeLoad (win) {
              cy.stub(win, 'fetch').withArgs('/seller/?number=300')
              .resolves(
                Cypress.Promise.resolve({
                  ok: true,
                  json: () => [
                    {
                        /*json here*/
                    }
                ],
                }).delay(2000)
              )
            },
          })
    })
```

I cant understand, why fetch seems works but in console is undefined. I cant see an example when a button is clicked and fetch event happens.

**Comment by jennifer-shehane** [comment]
I would suggest trying our new `cy.intercept()` command to intercept FETCH requests in our more recent versions of Cypress. If you're still experiencing an issue when switching over, please open a new issue.
