### ISSUE TITLE
Issue on installing cypress on heroku pipeline

### ISSUE THREAD

**Issue by erwanriou** [cypress-io/cypress#8163]
### Current behavior:

`-----> Installing dependencies
       Installing node modules (package.json)
       
       > cypress@4.11.0 postinstall /tmp/build_b0dc22d4_/node_modules/cypress
       > node index.js --exec install
       
       Installing Cypress (version: 4.11.0)
       
       [13:12:55]  Downloading Cypress     [started]
       [13:12:55]  Downloading Cypress      0% 0s [title changed]
       [13:12:55]  Downloading Cypress      2% 5s [title changed]
       [13:12:55]  Downloading Cypress      5% 4s [title changed]
       [13:12:56]  Downloading Cypress      8% 3s [title changed]
       [13:12:56]  Downloading Cypress      11% 3s [title changed]
       [13:12:56]  Downloading Cypress      14% 3s [title changed]
       [13:12:56]  Downloading Cypress      17% 3s [title changed]
       [13:12:56]  Downloading Cypress      20% 3s [title changed]
       [13:12:56]  Downloading Cypress      21% 3s [title changed]
       [13:12:56]  Downloading Cypress      21% 3s [failed]
       [13:12:56] → The Cypress App could not be downloaded.`

### Desired behavior:

To download Cypress in heroku pipeline...

### Test code to reproduce

deploy a project with cypress 4.11 in heroku

This problem was not existing last week. I check ur code and see that you are constantly updating your currently version 4.11 so that probably why its happen.
Its the 2nd time this bug appear (in previous other version it did also once)

**Comment by leo-mendoza-qatalog** [comment]
FWIW, this was happening to me, on our CI linux boxes. Turns out the checksum for the linux binary was corrupt.

```
URL: https://download.cypress.io/desktop/4.11.0?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 4c529cc216f9ccaa98d1cefedbd54f12fc8df836c02ad437beeb0cad4a43e08be7d8fcce125e74749875f7b46e3a9caac993b83404579084101639fe47e4bc0c
Computed checksum: d01b9e037853255a6b6bd075d8bdd97bce43622959b31fe4ba19e52930c6e2b7ac54c791c62fa48310b1622ca2abd3ae810ac5e72a2a301b85ff8adaa7369db6

Expected downloaded file to have size: 188115863
Computed size: 188115863
```

Upgrading to `cypress@4.12.0` seems to have fixed it for us.

**Comment by jennifer-shehane** [comment]
@erwanriou 

>I check ur code and see that you are constantly updating your currently version 4.11

This is completely inaccurate. When Cypress releases a version, we package it as an executable. **This never changes after it is released.** It is impossible for the Cypress product to change underneath within the same version. 

If the download begins failing, it could have something to do with the download server being unavailable (ie - npm or something could be down) or something in your environment has changed which makes Cypress download differently.

@leo-mendoza-qatalog This can happen if you began downloading Cypress and this somehow got interrupted - or if you are downloaded 2 versions of Cypress that override each other (like in yarn monorepos).

@erwanriou Please provide any setup necessary to reliably reproduce the issue and we will consider reopening the issue to investigate.
