### ISSUE TITLE
Stubbing large JSON responses fails in UI runner

### ISSUE THREAD

**Issue by CodingItWrong** [cypress-io/cypress#8164]
### Current behavior:
Stubbing JSON responses around 3 MB in size fails in UI for Cypress 4.3.0 and above, giving the error:

```
GET http://localhost:3000/__cypress/xhrs/https://example.com/large.json net::ERR_CONNECTION_RESET
```

It succeeds in Cypress 4.2.0. Running Cypress via the command line succeeds for all Cypress versions 4.2.0 and above.

Screenshots of failing in Cypress 4.3.0:

![Screen Shot 2020-08-03 at 12 18 29 PM](https://user-images.githubusercontent.com/15832198/89205224-6334e900-d585-11ea-9602-64d36399a67a.png)
![Screen Shot 2020-08-03 at 12 21 58 PM](https://user-images.githubusercontent.com/15832198/89205228-65974300-d585-11ea-9fec-495c2ad87cc2.png)
![Screen Shot 2020-08-03 at 12 22 14 PM](https://user-images.githubusercontent.com/15832198/89205235-67610680-d585-11ea-9c26-791409dbdc83.png)
![Screen Shot 2020-08-03 at 12 22 24 PM](https://user-images.githubusercontent.com/15832198/89205242-69c36080-d585-11ea-839f-f9edcf1f1645.png)

Screenshot of failing in Cypress 4.11.0:

![Screen Shot 2020-08-03 at 12 23 40 PM](https://user-images.githubusercontent.com/15832198/89205259-71830500-d585-11ea-82c3-859cd09f1994.png)

Screenshot of succeeding in Cypress 4.2.0:

![Screen Shot 2020-08-03 at 12 17 40 PM](https://user-images.githubusercontent.com/15832198/89205208-5d3f0800-d585-11ea-85e7-32c1a75c4509.png)

### Desired behavior:
Stubbing JSON responses at least several megabytes in size succeeds in both UI and command line runner.

### Test code to reproduce
https://github.com/CodingItWrong/cypress-network-stub

### Versions
Problem occurs in Cypress 4.3.0, 4.11.0. I tried several other versions in the range as well.

Problem does NOT occur in Cypress 4.2.0.

**Comment by CodingItWrong** [comment]
Update: this problem appears to be related to me loading the fixture via `cy.fixture()`:

```
    cy.fixture('large.json').then(largeJson => {
      cy.route({
        method: 'GET',
        url:
          'https://example.com/large.json',
        response: largeJson,
      });
    });
```

When I change it to pass a string to `response` with the `fixture:` prefix, as is currently recommended in the docs, it succeeds:

```
    cy.route({
      method: 'GET',
      url:
        'https://example.com/large.json',
      response: 'fixture:large.json',
    });
```

This certainly lowers the priority of this issue in my mind, as the documented approach works 👍

**Comment by jennifer-shehane** [comment]
This is fun because I think your workaround could no longer work in 4.12.0 due to this issue (if your file were even larger): https://github.com/cypress-io/cypress/issues/8181

Your code is actually wrongly aliasing off of the fixture instead of the route. But moving it to the route chain doesn't change the bug.

I'd need to narrow down which PR this was introduced in because it's not immediately obvious.

### 4.2.0

<img width="659" alt="Screen Shot 2020-08-07 at 4 53 56 PM" src="https://user-images.githubusercontent.com/1271364/89636424-9bfaf800-d8ce-11ea-8e87-934efc03f80a.png">

### 4.3.0

<img width="663" alt="Screen Shot 2020-08-07 at 4 49 20 PM" src="https://user-images.githubusercontent.com/1271364/89636022-f9db1000-d8cd-11ea-96fb-5f1f0c2ccabe.png">

**Comment by CodingItWrong** [comment]
> This is fun because I think your workaround could no longer work in 4.12.0 due to this issue (if your file were even larger): #8181

If I'm understanding you and #8181 correctly, you're saying that the ~3MB file size I reported _should_ continue to work in 4.12.0, but a _larger_ file (you gave the example of 11MB) may not work. I updated my repro locally to the `fixture:` string approach and to 4.12.0 and it seems to continue to work, which is expected. Wanted to share that data point 👍 

For my client project I don't anticipate the JSON file growing significantly larger, so I don't think #8181 will negatively impact us.

**Comment by jennifer-shehane** [comment]
The given example works now with `cy.intercept()`. `cy.route()` has been deprecated, so no fixes or new work will be spent on issues with it. We recommend migrating to `cy.intercept()`.

<img width="564" alt="Screen Shot 2021-08-09 at 8 44 29 AM" src="https://user-images.githubusercontent.com/1271364/128716336-9577b63c-c919-4803-a437-8f9870cc390b.png">


Closing as resolved.
