### ISSUE TITLE
Not respecting --silent flag on install

### ISSUE THREAD

**Issue by HugoGiraudel** [cypress-io/cypress#817]
- Operating System: Mac OS
- Cypress Version: 1+
- Browser Version: n/A

### Is this a Feature or Bug?

A bug.

### Current behavior:

When running `npm install` in silent mode (`--silent`), Cypress installs itself in verbose mode (installing, unzipping, checking printed out).

### Desired behavior:

If `npm install` is run in silent mode (`--silent`), Cypress sticks to it and doesn’t output anything upon installation.

### How to reproduce:

`npm install --silent`

### Additional Info (images, stack traces, etc)

This is a problem in logs because we end up with thousands of lines of Cypress installing then unzipping itself. Avoiding these kind of logs is why we run `npm install` in silent mode in the first place.

**Comment by cameronc56** [comment]
npm install --quiet and --silent suppresses the excessive cypress logs on Ubuntu xenial, but NOT debian jessie

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).

**Comment by Bkucera** [comment]
On second thought, we shouldn't blanket-disable all of our logging, we should just make sure to keep logging to a minimum. For example, if Cypress is downloading a ~300mb binary, we should tell the user regardless.

Here's puppeteer when installing with `--silent`
![pup](https://user-images.githubusercontent.com/14625260/47869445-5c3fdc00-dddd-11e8-9223-42af7447c527.png)
