### ISSUE TITLE
Firefox Dev Edition is installed but Cypress can't detect it

### ISSUE THREAD

**Issue by codinghedgehog-python** [cypress-io/cypress#8174]
Bug

### Current behavior:

I know support for Firefox is in beta which in this case I'm not sure what it means since it simply isn't working on my machine.
I'm using Firefox Dev Edition but when I run `./node_modules/.bin/cypress run --config-file cypress_dev.json --browser firefox` or with `--browser firefox:dev` I get this error output:

```
Can't run because you've entered an invalid browser name.

Browser: 'firefox' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox (Cypress support in beta)

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- electron
```

### Desired behavior:

Firefox being detected as available browser

### Versions

Cypress 4.12
Ubuntu 20.04
Firefox Dev Edition 80

**Comment by jennifer-shehane** [comment]
@codinghedgehog-python Cypress tries to find installed browsers on the machine, but if it's installed in an unexpected location (or perhaps renamed), then we have trouble finding. I suggest following this troubleshooting guide: https://on.cypress.io/troubleshooting#Launching-browsers

Also running `DEBUG=cypress:* cypress info` will give more information about browsers, where we looked and what we found.

**Comment by codinghedgehog-python** [comment]
Well, what can I say. I didn't install the browser into some exotic location within my system. I just went with the defaults when installing so I would've thought Cypress would pick up on default location when checking for browsers. Thank you anyway Jennifer.

**Comment by lordrip** [comment]
Just pasting this if someone else it's looking for a similar thing around the Firefox Developer edition

Following the steps that @jennifer-shehane mention, I saw that Firefox Developer Edition in Linux is looked upon as a binary in the path as `firefox-developer-edition`.

I found [this debug example](https://github.com/cypress-io/cypress/issues/15258#issuecomment-788029383) from another issue
