### ISSUE TITLE
"Cannot set property 'err' of undefined" error occurs in place of other errors during automatic test-reruns on file save (4.12.1).

### ISSUE THREAD

**Issue by threehams** [cypress-io/cypress#8189]
Current behavior:
This is a reopen of https://github.com/cypress-io/cypress/issues/7874, since the issue is not fixed after upgrading to 4.12.1. The behavior is the same, but the test code branch is different and this can be reproduced at least 50% of the time.

When running tests locally through cypress open by saving files (forcing a re-run), any failures occurred during the run can trigger this message:

```
The following error originated from your application code, not from Cypress.

  > Cannot set property 'err' of undefined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event. Learn more
```

Desired behavior:
The test fails with the normal readable stack trace.

Test code to reproduce
https://github.com/primitiveconcept/ludumdare46/tree/cypress/err-of-undefined-4-12-1/client

Run `npm run cy:dev` for server + Cypress
Run the `infostealer.spec.ts` spec
Save the `infostealer.spec.ts` while the test is running. Note that 50% of the time, this error occurs, and 50% of the time, the test is cut short and passes when it should fail. This may or may not be caused by a separate issue.

Versions
Cypress versions: Can reproduce on 4.12.1. Cannot reproduce on 4.5.0. Other versions are unstable for various reasons on the example project.
OS: MacOS + Windows
Browser: Chrome + Electron

**Comment by todd-m-kemp** [comment]
I too have continued to experience this problem in version 4.12.1 even though it was supposed to have been fixed in this version.

**Comment by Bkucera** [comment]
thanks for letting us know, I'm looking into this (again)

**Comment by thaianalps** [comment]
> I too have continued to experience this problem in version 4.12.1 even though it was supposed to have been fixed in this version.

me too

**Comment by jennifer-shehane** [comment]
This will be fixed in our next release.
