### ISSUE TITLE
Missing Slack info on AWS CodeBuild using Cypress Dashboard

### ISSUE THREAD

**Issue by milan-easykad** [cypress-io/cypress#8192]
After Cypress tests are executed on AWS CodeBuild and recorded under Cypress Dashboard, slack notification is created.

### Current behavior:

Aws CodeBuild runId (I guess??) is missing.

![image](https://user-images.githubusercontent.com/68648172/89464738-3e04ce00-d771-11ea-8b9a-5c76754ea1b5.png)

### Versions

Cypress 4.12.0

**Comment by jennifer-shehane** [comment]
I'll have to check with our API team to see what this number is exactly meant to reflect. We actually just began collecting this data automatically in 4.12.0, but there may be some data still missing there. https://github.com/cypress-io/cypress/pull/8159

For my Slack integration, I can see the CircleCI number:

<img width="261" alt="Screen Shot 2020-08-06 at 11 29 15 AM" src="https://user-images.githubusercontent.com/1271364/89492665-257bce80-d7d8-11ea-8f4a-059a1b1d5d62.png">

These then correlate to the CircleCI numbers shown in the top right of the run when clicking through to the Dashboard.

<img width="407" alt="Screen Shot 2020-08-06 at 11 28 59 AM" src="https://user-images.githubusercontent.com/1271364/89492878-b2bf2300-d7d8-11ea-9fc9-c396b364865a.png">

**Comment by milan-easykad** [comment]
@jennifer-shehane  Yes, and I think that number after CircleCi is not shown on Dashboard Service for AWS  CodeBuild.
This is how it looks like:
![image](https://user-images.githubusercontent.com/68648172/89592035-f69f4000-d84b-11ea-9a6d-44d0eb36644c.png)

**Comment by jennifer-shehane** [comment]
Hey @milan-easykad, the team did confirm that this is meant to be the build id, but is showing null instead. They have a PR open to fix this issue, so the fix should be released sometime soon.

I'm going to close this issue and I will try to update when I see they've released, but be on the lookout for this fix.
