### ISSUE TITLE
Support REPL

### ISSUE THREAD

**Issue by tom10271** [cypress-io/cypress#8195]
### Current behavior:
I need to write steps I want cypress to run then execute test and wait for minutes to see if cypress is doing what I want or not. If cypress is not working or misinterpreted the command. I need to make another guess and wait for another few minutes again and again. It is time wasting.

### Desired behavior:
![Screenshot 2020-08-06 at 10 43 54 AM](https://user-images.githubusercontent.com/5089629/89484754-bb602b00-d7d1-11ea-8713-969fe4819dcf.png)
Support REPL in browser, add an input field in the bottom left corner. When developer input a cy.xxx() command, it tries to run it and return result or error.

### Versions
Cypress 4.1

**Comment by jennifer-shehane** [comment]
You can use `cy.now()` to run commands directly in the Developer Tools, although this is undocumented. 

For every command, you shift the args by one and pass in the command name as the first argument. For example, if there is `.doubleclick()` command signature of:

```js
.dblclick(position, options)
```

Then the `cy.now()` signature would be.

```js
cy.now('dblclick', position, options)
```

This applies to every single command.

Also the Selector Playground does support querying via `cy.get()` and `cy.contains()` directly in the application under test. https://on.cypress.io/test-runner#Selector-Playground

Do either of these solutions not meet what you are asking for?

**Comment by tom10271** [comment]
Great to know we can use `cy.now()`, this is what I am asking for. I will give it a try. Thank you for helping

**Comment by navmed** [comment]
I would love to see a REPL too. This looks promising, but I can't figure out how to use, it would be great to document this with some examples.

**Comment by tom10271** [comment]
> I would love to see a REPL too. This looks promising, but I can't figure out how to use it, it would be great to document this with some examples.

It is pretty troublesome, in your test you can write `cy.wait(500).find('.target').click();` but with cy.now you need to nest them like:

```
cy.now('wait', 500).then(
() => {
cy.now('find', '.target').then(
() => {
cy.now('click');
})
```

**Comment by viesti** [comment]
Can `cy.now` be used to chain commands? E.g. `get` followed by `type` onto what `get` command found, at the JS console?

**Comment by tom10271** [comment]
> Can `cy.now` be used to chain commands? E.g. `get` followed by `type` onto what `get` command found, at the JS console?

https://github.com/cypress-io/cypress/issues/8195#issuecomment-751927977

No.

**Comment by viesti** [comment]
Right, actually I had a problem with my small example where `get` was returning null even though Cypress command log UI showed that an element was matched.

Anyways, got a "select" working, might be that I only had lousy HTML in my test page :)

**Comment by Strajk** [comment]
For the Googlers arriving here after searching for "Cypress REPL", this is my current workflow – I'm unhappy with it, but it works... 

But I really hope there's a better way

![image](https://user-images.githubusercontent.com/697301/145870652-d6a76bef-2eda-460b-bacc-933b04705aec.png)

**Comment by itsalaidbacklife** [comment]
> You can use `cy.now()` to run commands directly in the Developer Tools, although this is undocumented.
> 
> For every command, you shift the args by one and pass in the command name as the first argument. For example, if there is `.doubleclick()` command signature of:
> 
> ```js
> .dblclick(position, options)
> ```
> 
> Then the `cy.now()` signature would be.
> 
> ```js
> cy.now('dblclick', position, options)
> ```
> 
> This applies to every single command.
> 
> Also the Selector Playground does support querying via `cy.get()` and `cy.contains()` directly in the application under test. https://on.cypress.io/test-runner#Selector-Playground
> 
> Do either of these solutions not meet what you are asking for?

The only issue with cy.now() is that it does not support chaining commands, so any commands that for example rely on `cy.its()` to grab data off of the window object can't be executed this way. For example, I'm using vue + vuex in my application and I expose the store to cypress through the window object so my commands can do things like this:


```
Cypress.Commands.add('somethingADifferentUserDoes', () => {
	return cy
		.window()
		.its('app.$store.state.game') // Grab data from vuex store
		.then((game) => {
                         // Use that to fetch a request body for my request
			const someStoreData = game.players[game.myPNum].id;
			return axios.post('/game/something', {
				someStoreData,
			});
		});
});
```

Unfortunately I need store data in order to have the appropriate params for many of the requests that I use helpers for, especially when it comes to simulating other users. Having a deeper `cy.now()` that allowed me to run command **chains** instead of single commands would be an enormous boon for interacting fluidly with my application on behalf of multiple users.
