### ISSUE TITLE
Cypress Update throw error that dependencies are missing

### ISSUE THREAD

**Issue by Gabalth** [cypress-io/cypress#8197]
Update Cypress via npm install --save-dev cypress@4.12.1

Error thrown
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@cypress%2frequest - Not found
npm ERR! 404
npm ERR! 404  '@cypress/request@^2.88.5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'cypress'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by gustaferiksson** [comment]
There is an issue with npm atm [https://status.npmjs.org/](https://status.npmjs.org/)

**Comment by Gabalth** [comment]
Oh, ok. I didn't knew that. Thank you for the update
