### ISSUE TITLE
Cypress 4.5.0 doesn't refresh the page on hashchange

### ISSUE THREAD

**Issue by antonioaltamura** [cypress-io/cypress#8199]
### Current behavior:
My [LitElement](https://lit-element.polymer-project.org/) based-project has an extremely simple routing mechanism: the application listens for `hashchange` events and update the main class property `this.config.enabledComponents` to track which page to show in any moment.

### Desired behavior:

I want to see the application correctly reflect the clicked menu item. The browser in Cypress correctly changes the hash, but the page is not refreshed. This happens in Cypress 4.5.0, yet everything works fine in 4.12.1 (current version). I would like to know why this problem happens and what has been fixed between 4.5.0 and 4.12.1 that may be related to this. It is a strange bug and I want to make sure to know the reason of it for the sake of future debug hours, days (or weeks..).

This is the bug visually explained. The right state of `enabledComponents` after I click on "home" menu item is the one in js console. You can see the page the application shows is the "login" one, not the "home".
![Screenshot from 2020-08-06 14-33-56](https://user-images.githubusercontent.com/6325475/89534841-7813b580-d7ed-11ea-8fd2-6738b6243d89.png)

### Test code to reproduce

I prepared a minimal example here https://github.com/antonioaltamura/LitElementCypress 
To install and reproduce just do
- yarn install
- yarn serve
- yarn e2e
- run `login.js` test

(more info in [README.md](https://github.com/antonioaltamura/LitElementCypress/blob/master/README.md))

### Versions

Cypress 4.5.0
FF 79, Chrome 83
Ubuntu 18

**Comment by jennifer-shehane** [comment]
We make lots of bug fixes during every release which are extensively documented in our changelog. You're welcome to look through the changelog to find where this issue was fixed and run it on each cypress version to narrow down which version it was fixed: https://github.com/cypress-io/cypress/releases 

Please feel free to open a new issue if you are experiencing a bug in our current version.
