### ISSUE TITLE
Cypress failed to start Error - Cypress version 4.12.1

### ISSUE THREAD

**Issue by ratnakarbellary** [cypress-io/cypress#8200]
Getting Cypress failed to start error 

OS : Windows 10
![Capture](https://user-images.githubusercontent.com/68541248/89538003-aad2a380-d817-11ea-8a3b-0f0dc85d5179.PNG)

**Comment by erangeles** [comment]
getting same issue but with a different dependency 

`/home/user/.cache/Cypress/4.12.1/Cypress/Cypress: error while loading shared libraries: libPrlDRI.so.1: cannot open shared object file: No such file or directory`

**Comment by jennifer-shehane** [comment]
@ratnakarbellary EPERM is a permissions error. Opening Cypress will require write permissions, you'll need to verify the correct permissions are set and rerun. Duplicate of #7640
