### ISSUE TITLE
Component tests not run when clicking 'Run n specs' button

### ISSUE THREAD

**Issue by jasonatball** [cypress-io/cypress#8203]
### Current behavior:
I'm using the cypress-vue-unit-test via cypress-experimental. My tests show up in the Dashboard under COMPONENT TESTS. However when I click "Run All Tests" none of the component tests run. When I use the Search box to narrow down my list to just component tests and click "Run X specs" I get "No tests found in your file:"

### Desired behavior:
COMPONENT TESTS run just like INTEGRATION TESTS.

### Test code to reproduce
Add a component tests and try to run it with the Run All Tests button. See https://github.com/bahmutov/cypress-vue-unit-test

### Versions
Cypress 4.12.1
Windows 10
Chrome 78

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-221) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Running component tests with the 'Run all Specs' button is not currently supported. As this is still experimental, the work for this has yet to be done. 

The reasoning behind this is that component tests run completely differently integration tests, so if the filter were to match some integration tests and component tests combined - they cannot run back to back together. 

We'll leave this open as feature work to do for component testing.

**Comment by jasonatball** [comment]
Thank you for the explanation. What's interesting is that using the command line "cypress run --record ..." actually DOES run all the component tests (which is great!). Looking forward to additional support as I think this is an awesome way to test VueJS components.

**Comment by bahmutov** [comment]
@jennifer-shehane is right, we don't know how to run component tests mixed with the integration specs, so we postponed this feature until we figure it out.

**Comment by ambrt** [comment]
> @bahmutov until we figure it out

Until its possible, allow OR situation - "Run all components OR all integration tests".

That would allow those who use components only to test all of their specs, and wouldn't interfere with those who do integration tests.

**Comment by bahmutov** [comment]
I wish but for now we can’t even concat unit tests like that, so it requires some planning and thinking

**Comment by ambrt** [comment]
> I wish but for now we can’t even concat unit tests like that, so it requires some planning and thinking

Ok,np.
