### ISSUE TITLE
Error even after the test pass

### ISSUE THREAD

**Issue by sheetaljes** [cypress-io/cypress#8205]
### Current behavior:

My test is passing after I added "chromeWebSecurity": false in cypress.json, but even after that I am getting Error: EISDIR: illegal operation on a directory.

### Desired behavior:

No error is displayed after my test run successfully and pass

### Test code to reproduce

```js
describe('when user clicks on user id dropdown and then logout option', () => {
  before(() => {
    cy.get('.dropdown.ebfda-user').click()
    cy.get('.dropdown-item').children().eq(4).click()
  })

  it('should redirect to login page', () => {
    cy.url().should('include', '/login')
  })
})
```
### Versions

<img width="1344" alt="Screenshot 2020-08-06 at 17 48 12" src="https://user-images.githubusercontent.com/60046494/89554355-0a788100-d80f-11ea-8603-1d71b2b532b7.png">

**Comment by sheetaljes** [comment]
<img width="742" alt="Screenshot 2020-08-06 at 18 05 19" src="https://user-images.githubusercontent.com/60046494/89554696-7b1f9d80-d80f-11ea-97e0-6840f016a522.png">

**Comment by jennifer-shehane** [comment]
Duplicate of #1244 

You can try this as a workaround: https://github.com/cypress-io/cypress/issues/1244#issuecomment-631933197
