### ISSUE TITLE
Cypress videos freeze during playback

### ISSUE THREAD

**Issue by you1anna** [cypress-io/cypress#8210]
### Current behavior:

I frequently see the Cypress videos completing processing, but freezing at arbitrary points. This happens both locally and in CI, and has been occurring since v4.10.0. 

I am unable to attach examples as the content is commercially sensitive, so any hints on debugging would be appreciated. Is this a known issue? Happy to provide more info.

### Desired behavior:

Videos play normally

### Versions

Locally: OSX Catalina / 4.10.0, 4.11.0, 4.12.0
CI: Centos 7.0

**Comment by jennifer-shehane** [comment]
Typically when we see the issue of freezing frames on the video, it is a matter of underpowered CPU on the machine, as explained here: https://github.com/cypress-io/cypress/issues/5061

There's an issue to detect frozen frames here: https://github.com/cypress-io/cypress/issues/5061

You can log memory and CPU usage with the following instructions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage If you see the CPU maxing out, you'll need to increase the CPU of the machine running the specs.

If you can isolate this to solely 4.10.0 (rolling back to 4.9.0 fixes the issue completely), then I would be happy to look at a reproducible example so we can narrow down why this may have started happening in that version.

**Comment by you1anna** [comment]
Thanks @jennifer-shehane I have run the profiler locally and it peaks at 230% CPU, however the videos generated are all fine on this run (Cypress 4.10.0)

```
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │    'Electron'     │      1       │    '10655'     │    94.2    │      91.7      │  282.54  │    441.72    │   1020.25   │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │     '9316'     │     86     │     76.71      │   225    │    226.53    │   312.66    │
  cypress:server:util:process_profiler │    2    │ 'electron-shared' │      2       │  '9331, 9341'  │    25.3    │     24.15      │  161.37  │    129.45    │   161.37    │
  cypress:server:util:process_profiler │    3    │     'ffmpeg'      │      1       │    '10654'     │    25.4    │     48.65      │  78.69   │    85.41     │   270.71    │
  cypress:server:util:process_profiler │    4    │     'plugin'      │      1       │     '9369'     │     0      │       0        │  20.81   │    25.29     │    74.39    │
  cypress:server:util:process_profiler │    5    │      'other'      │      2       │ '10683, 10684' │     0      │      0.21      │   1.91   │     1.91     │    1.98     │
  cypress:server:util:process_profiler │    6    │      'TOTAL'      │      8       │      '-'       │   230.9    │     234.17     │  770.33  │    878.36    │   1441.6    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
```

To isolate the issue will take significant time - so we may just try increasing CPU in CI. Have all avenues to optimise video encoding/prevent erroring been explored from the Cypress end? This isn't really my area so not sure what else to suggest.

**Comment by jennifer-shehane** [comment]
There's a way to change the compression which would improve on the encoding step of the video https://on.cypress.io/screenshots-and-videos#Videos, but I don't think this is where you are maxing out.

But, yes, it just takes CPU resources to run Cypress, Electron, and ffmpeg together in order to record video.

**Comment by vicwomg** [comment]
In case anyone is struggling with Freezing videos on Github Actions, the default ubuntu-latest runner results in frozen videos for us. The fix was to use the cypress container and run on Chrome instead of Electron. 

```
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
```

```
   - name: Cypress e2e run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
```
