### ISSUE TITLE
cy.visit hangs in Electron

### ISSUE THREAD

**Issue by HealQA** [cypress-io/cypress#8212]
### Current behavior:

cy.visit() hung in Electon.  Working in Chrome & Edge Beta.

Screen Shots:
![ss1](https://user-images.githubusercontent.com/51144089/89575224-5234e380-d7e2-11ea-8258-42f0864a035c.png)
![ss2](https://user-images.githubusercontent.com/51144089/89575238-582ac480-d7e2-11ea-930c-3fe8a694205b.png)
![ss3](https://user-images.githubusercontent.com/51144089/89575246-5cef7880-d7e2-11ea-99a4-3211b373c0ac.png)

### Desired behavior:

cy.visit should open the page in the "Test2" test.

### Test code to reproduce

--- Begin Code ---
```js
context("Test Suite", () => {
    it("Test1", () => {
        cy.visit("https://partner.qa.heal.com/");
        cy.get('[data-tid="inp_username"]').type(
            "curt.hesher+cypressbug@heal.com"
        );
        cy.get('[data-tid="inp_password"]').type("ElectronCypressBug123456789");
        cy.get('[data-tid="btn_login"]').click();

        cy.get('[data-tid="inp_search"]').type("curt hesher");
        cy.get("div").contains("curt hesher").click();

        cy.contains("curt hesher").click();
    });

    it("Test2", () => {
        cy.visit("https://partner.qa.heal.com/");
    });
});
```
--- End Code ---

### Versions

Cypress 12.4.1, Mac OSX 10.15.5, npx 6.13.4, node 12.14.1,  Electon (80), Chrome (84), Edge Beta (85)

**Comment by qws777** [comment]
probably related to #8146

**Comment by jennifer-shehane** [comment]
I'm not able to run the code as provided. Please provide all configuration in cypress.json / any other test code (support/plugins) that is required to run the test code. Thanks!

**Comment by HealQA** [comment]
@jennifer-shehane 
TY.  I attempted to make the test self-contained.  Not sure what I missed.  FWIW, I tried running this in a fresh install of cypress (under /tmp) and was able to run the code and see the issue of the hanging cy.visit() in Test2.  That was with an unmodified cypress.json file.  Here's the cypress.json I normally run with,
```
"chromeWebSecurity": false,
 "ignoreTestFiles": "*.md",
 "defaultCommandTimeout": 30000
"reporter": "cypress-multi-reporters",
 "reporterOptions": {
    "configFile": "reporterOpts.json"
  }
```

**Comment by jennifer-shehane** [comment]
I don't see the page normally loading for the first test in Chrome or any browser. There are a lot of errors in the console. 

Are you sure you don't have extra code in your support file that's required to run? Please run the code to see that it runs independently. 

What version of Cypress are you running in?

<img width="1307" alt="Screen Shot 2020-08-18 at 1 21 45 PM" src="https://user-images.githubusercontent.com/1271364/90480122-cf9f1300-e155-11ea-8e2d-1a1c6e4b058e.png">

**Comment by HealQA** [comment]
@jennifer-shehane 
TY for looking.  I'm able to run the provided test code in a new install of Cypress 4.12.1.  I do not get any console errors.  On top of that, the test passes.  It was reliably failing when I filed this ticket, and now it reliably passes.  I have no idea why, but my guess is there's something outside of Cypress impacting the behavior.  I will close this ticket for now and reopen if I'm able to recreate the failing behavior.  TY.
