### ISSUE TITLE
Select <input> by its label

### ISSUE THREAD

**Issue by jdhines** [cypress-io/cypress#8213]
### Current behavior:

The recommended way to select an input element is with `data-testid`

### Desired behavior:

I agree with Kent C. Dodds ([Making Your UI Tests Resilient To Change](https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change)) that a good way to select inputs is by their labels, which is just the way a user would find the input, and these end-to-end tests should mimic how a user would use the application in order to give you the maximum confidence it's working correctly. 

One may argue, "Yeah, but if your label changes, your test breaks; that wouldn't happen with `data-testid`" but this is a case where I'd be fine updating my test, because maybe the label just changed, but maybe there's a bug and the labels aren't displaying at all. I'd want my test to break in the latter case.

So it would be great to have something like `cy.getByLabel()` for inputs.

**Comment by jdhines** [comment]
Found out that this feature is available with @testing-library/cypress (https://testing-library.com/docs/cypress-testing-library/intro). Good enough for me.

**Comment by oh-bala** [comment]
This is how I do without additional library

```
cy
.get('form')
.contains('label', 'Name')
.parent()
.find('input')
.invoke('val', 'Some value')
```
