### ISSUE TITLE
Being able to reset browser history

### ISSUE THREAD

**Issue by quentinus95** [cypress-io/cypress#8219]
Hello, I'm looking for a solution to be able to validate that my app do not push pages in the browser history. Sadly, I can't find a way to reset it properly before testing.

### Current behavior:

I'm currently reading the history length using the following piece of code:

```ts
 cy.window().then(window => {
    cy.wrap(window.history.length).should("equal", 2)
})
```

The main issue with this approach is that browser history is shared between tests. Consequently this test is now dependent of what was run before it.

### Desired behavior:

I would expect two possible behaviors:

- the browser history is reset between tests (to me it's a bug that Cypress does not do that by default)
- Cypress provides a `cy.clearHistory()` method to clear tab history. It can be useful to run it before doing the assertion

### Versions

Cypress 3.8.3.

**Comment by jennifer-shehane** [comment]
Likely should be a part of #686

**Comment by jennifer-shehane** [comment]
The team has confirmed that this is planned work as part of #686 - will be closing as duplicate.
