### ISSUE TITLE
Cypress does not appear to process support/index.js sometimes when multiple cypress run commands are run in parallel

### ISSUE THREAD

**Issue by PersonThing** [cypress-io/cypress#8222]
### Current behavior:

We're experimenting with parallelizing our tests on a single (very powerful) machine, and having really good results so far, but have run into an issue with custom commands not being found intermittently (maybe 1 in 20 tests will fail with `cy.[command name] is not a function`.

### Code to reproduce
We're splitting specs into 4-8 groups, and running them in separate child processes using `child_process.spawn`, where each spawn is running a node script that uses the cypress module API to call cypress.run.

Our actual approach is a bit more sophisticated than this, but I'll try to boil it down as much as possible...

**cypress-ci.js:**
```
const { spawn } = require('child_process')

const groups = [
  [ 'spec1.spec.js', 'spec2.spec.js' ],
  [ 'spec3.spec.js', 'spec4.spec.js' ]
]

groups.forEach(specs => {
  spawn('node', ['cypress-ci-run.js', specs.join(',')])
})
```

**cypress-cli-run.js**
```
const args = process.argv.slice(2)
const specs = args[0]
const cypress = require('cypress')
cypress.run({ spec: specs })
```

**support/commands.js** (imported from `support/index.js`)
```
Cypress.Commands.add('sample', { prevSubject: 'optional' }, (subject, arg) => {
  // implementation not relevant to the problem.. just console log the arg or something
  console.log(arg)
})
```

**spec1.spec.js**
```
describe('spec 1', () => {
  it('test 1', () => {
    cy.sample('i am in test 1')
  })
})
```

Other specs not important, command itself is not important.  Tests that use _any_ of our commands are occasionally failing with `cy.[command name] is not a function`.  Maybe there's some resource sharing / caching going on where subsequent cypress run calls don't think they need to handle index.js and/or commands.js?

We considered just not using Cypress.Commands.add, and instead using helper functions directly, but then realized it was also not using the plugins registered in `support/index.js`, like `cypress-plugin-retries`.  More info available on that if necessary.

### Versions

Cypress version 4.12.1
Node version 14.7.0

**Comment by PersonThing** [comment]
Figured it out.  Needed unique port passed to `cypress.run({ port: ... })`.  And didn't realize module API starts its own child process anyway, so we didn't need to do that part.

**Comment by bahmutov** [comment]
Good finds

**Comment by muhammad-st** [comment]
I'm having the same issue since a while. Are you sure it got resolved only by setting a different port? I tried to do so, no difference.

**Comment by itsdela** [comment]
I have the same issue using the [cypress-parallel](https://www.npmjs.com/package/cypress-parallel) library
