### ISSUE TITLE
since 4.11.0, POST sockjs call appears in network each 2 seconds

### ISSUE THREAD

**Issue by inseredamus** [cypress-io/cypress#8223]
### Current behavior:

since 4.11.0, it appears each 2 seconds these 2 lines in the cypress user interface : 
```
(xhr) POST (aborted) / sockjs-node/999/abcdefg0/xhr_streaming?t=123456789456
(xhr) GET200 /sockjs-node/info?t=123456789456
```
In browser network too. And in browser console : 

```
Invalid Host/Origin header , [WDS] Disconnected!, WebSocket connection to 'ws://localhost:420 ....failed: Websocket is closed before the connection is established.
```

### Desired behavior:

in 4.10.0 and before, those lines didn't appear at all.

### Test code to reproduce

With or without VPN, I can't reproduce it in the standard cypress examples. 
I reproduce it by visiting localhost:4200. The 2 lines appears within the execution of integration tests and e2e tests.
```js
cy.visit('/url')
cy.pause()
```

### Versions

problem with 4.11.0, 4.12.0 and 4.12.1
no problem with 4.10.0

![Bildschirmfoto 2020-08-07 um 22 38 59](https://user-images.githubusercontent.com/30667806/89686644-03c93700-d8ff-11ea-9179-282818fa1d90.png)

### Note

I can imagine that the description in "test code to reproduce" is not good enough for the understanding. I hope with this ticket that someone could have the same issue and could add some information. Thanks

**Comment by jennifer-shehane** [comment]
There isn't currently any known regressions in [4.11.0](https://docs.cypress.io/guides/references/changelog.html#4-11-0). 

There was some work done in 4.11.0 regarding `Websocket is closed` errors though.
>Fixed an issue where Cypress tests in Chromium-family browsers could randomly fail with the error “WebSocket is already in CLOSING or CLOSED state.”
>https://github.com/cypress-io/cypress/pull/7981

Yeah, we'll need a reproducible example in order to investigate more.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
