### ISSUE TITLE
Click() command does not trigger XHR requests from time to time

### ISSUE THREAD

**Issue by OlenaVakulenko** [cypress-io/cypress#8224]
### Current behavior:

The `click()` command does not trigger XHR requests from time to time. 
After `cy.get('selector').click()` the XHR is not being triggered even after 30 seconds.
The issue is reproduced on several websites only when using cypress, it is not reproduced when the real user performs the same actions.

### Desired behavior:

Click() command triggers the same XHR-requests as user actions would do.

### Test code to reproduce

There is a public e-commerce website which provides the opportunity to add some goods to comparison and compare them by their characteristics. 

```ts
//support/commands.ts:
//function that adds an item to comparison list and returns item's title
Cypress.Commands.add("addToComparison", function (index) {
  cy.server();
  cy.route("GET", "/response/compare.php?add*").as("data");
  cy.get(".vit-item").eq(index).find(".tovar-compare").click();
  cy.wait("@data", { requestTimeout: 30000 });
  return cy
    .get(".vit-item")
    .eq(index)
    .find(".vit-name")
    .invoke("text")
    .then((title) => {
      return title;
    });
});

```

/integration/smoke.spec.js

```js
describe("Add 2 items to comparison", () => {
  it("Add 2 items to comparison", () => {
    cy.visit("https://elmir.ua/cell_phones/");
    cy.get("#logo").should("be.visible");
    cy.addToComparison(0).then((item1) => {
      cy.addToComparison(1).then((item2) => {
        cy.get("#top-paging .compare-link").click();
      });
    });
  });
});
```
When user manually does the same actions on the site, after clicking 'Add to comparison' link (`cy.get(".vit-item").eq(index).find(".tovar-compare").click()` in the a`ddToComparison` function), XHR GET-request to URL `https://elmir.ua/response/compare.php` is triggered, but when I run my test with cypress, the GET-request is being triggered from time to time and the test fails randomly.

Stack trace
```
CypressError: `cy.wait()` timed out waiting `30000ms` for the 1st request to the route: `data`. No request ever occurred.
    at cypressErr (https://elmir.ua/__cypress/runner/cypress_runner.js:170677:16)
    at Object.throwErr (https://elmir.ua/__cypress/runner/cypress_runner.js:170573:11)
    at $Cy.retry (https://elmir.ua/__cypress/runner/cypress_runner.js:162994:19)
    at checkForXhr (https://elmir.ua/__cypress/runner/cypress_runner.js:158976:17)
    at https://elmir.ua/__cypress/runner/cypress_runner.js:158977:28
From previous event:
    at tryFn (https://elmir.ua/__cypress/runner/cypress_runner.js:163481:24)
    at whenStable (https://elmir.ua/__cypress/runner/cypress_runner.js:163522:12)
    at https://elmir.ua/__cypress/runner/cypress_runner.js:163040:16
From Your Spec Code:
    at Context.eval (https://elmir.ua/__cypress/tests?p=cypress\support\index.js:9:6)
```

![image](https://user-images.githubusercontent.com/14077302/89691568-e6ea2f00-d911-11ea-813a-7c369ea61b52.png)

Note, that the piece of code with waiting for the response of XHR was added by me after numerous attempts to fix the problem, but it didn't solve the issue entirely.

### Versions

Cypress Version 4.12.1, Windows 8.1, all browsers

**Comment by przemuh** [comment]
Hi @OlenaVakulenko :)

I don't know if it is exactly your case, but I guess that wildcard `*` in `"/response/compare.php?add*"` may be a problem. We had a similar problem when url query param contained a slash character `/`.

Example: `/response/compare.php?add&refPage=something/abc`

Try to use double star `**`. Or be more strict in case of specific a route url

To verify that string will match a pattern you can use `Cypress.minimatch` method:

![image](https://user-images.githubusercontent.com/3865478/89828288-235b9c00-db59-11ea-9d7b-0f8954640c29.png)

For more details see the docs page: https://docs.cypress.io/api/commands/route.html#Wait-on-url-matching-glob

**Comment by jennifer-shehane** [comment]
It looks like the test is rerouting to `https://elmir.ua/__/` earlier in the test when it fails. I'm not exactly sure how the application works when the click event happens, but may be some async issue - where it's not ready for click at that time yet. https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/

### Pass

<img width="495" alt="Screen Shot 2020-08-11 at 1 20 06 PM" src="https://user-images.githubusercontent.com/1271364/89866887-4c6e4200-dbd6-11ea-8e3f-b46b96c68fc9.png">

### Fail

<img width="497" alt="Screen Shot 2020-08-11 at 1 20 46 PM" src="https://user-images.githubusercontent.com/1271364/89866901-555f1380-dbd6-11ea-9d90-9d8dc2641b86.png">

**Comment by OlenaVakulenko** [comment]
Thank you @jennifer-shehane !
After I rewritten my function so that `click()` method is retried until the `'add-link'` class is not present (it means that the response to `/response/compare.php` has been 200), the test passes robustly:
```
Cypress.Commands.add("addToComparison", function (index) {
  const click = ($el) => $el.click();
  cy.get(".vit-item")
    .eq(index)
    .find(".add-link")
    .should("be.visible")
    .pipe(click)
    .should(($el) => {
      expect($el).to.not.have.class("add-link");
    });

  return cy
    .get(".vit-item")
    .eq(index)
    .find(".vit-name")
    .invoke("text")
    .then((title) => {
      return title;
    });
});
```
So, I guess the issue can be closed. Thank you for your time and patience.

**Comment by jennifer-shehane** [comment]
Great to hear!
