### ISSUE TITLE
No version of Cypress is installed :

### ISSUE THREAD

**Issue by Tarun39** [cypress-io/cypress#8228]
### Current behavior:
Hi Team,
I am facing issue since i installed new version of cypress 4.12.1 on my windows 10 machine.
After running code once i am getting below error again and again .I tried to re-install the version but it is not resolving the issue and even i tried to install old version ie.4.11 but facing same issue.I am not able to find any specific issue as previously everything was working fine before installing 4.12.1. I am attaching screenshot .
![image](https://user-images.githubusercontent.com/64144587/89727067-39753980-da3f-11ea-8003-1aaffd8d5dc9.png)

### Desired behavior:

It should be run my test 

### Test code to reproduce

I am running a usual code "npx cypress open" or "npx cypress run"

### Versions
Node version -14.2.0
Windows- win32 (10.0.19041)
Cypress version -4.12.1

**Comment by Tarun39** [comment]
I found the problem the exe was getting deleted by McAfee Antivirus .I am not sure if cypress team can do something on this so i am closing this  issue.

**Comment by tgelu** [comment]
Thanks @Tarun39! - had the same issue and was going crazy
