### ISSUE TITLE
Combinations with {shift} and {cmd}/{ctrl} do not work

### ISSUE THREAD

**Issue by yourpchelp** [cypress-io/cypress#8231]
### Current behavior:
Combinations with `{shift}` and `{cmd}/{ctrl}` do not work.
For example,
- `.type('{shift}v)` types 'v' instead of 'V'.
- `.type('{ctrl}v')` types 'v' instead of clipboard's content.

I tried `{cmd}` instead of `{ctrl}`, but the same problem exists.

### Desired behavior:

`.type('{shift}v)` must type 'V'.
`.type('{ctrl}v')` must type the clipboard's content.

### Test code to reproduce
```js
cy.get("input").type('{shift}v);
cy.get("input").type('{ctrl}v');
```

### Versions
Cypress package version: 4.12.1
Cypress binary version: 4.12.1
Browser: Version 84.0.4147.105 (Official Build) (64-bit)
OS: macOS Catalina, Version 10.15.6

**Comment by przemuh** [comment]
Hi @yourpchelp :),

This is an expected behaviour. See the docs: https://docs.cypress.io/api/commands/type.html#Modifier-effects

```
// app code
document.querySelector('input:first').addEventListener('keydown', (e) => {
  // e.shiftKey will be true
})

// in test
cy.get('input:first').type('{shift}a')
```

> In the example above, a lowercase a will be typed, because that’s the literal character specified. To type a capital A, you can use .type('{shift}A') (or .type('A') if you don’t care about the shiftKey property on any key events).

------------------

In case of copy-paste from clipboard there are some related issues:

https://github.com/cypress-io/cypress/issues/2386
https://github.com/cypress-io/cypress/issues/2851

**Comment by jennifer-shehane** [comment]
Agree with what @przemuh said above. Closing.
