### ISSUE TITLE
File names not included in testcase tags in junit output

### ISSUE THREAD

**Issue by aub** [cypress-io/cypress#8237]
### Current behavior:

I'm using CircleCI to run my tests and trying to split tests based on timing data. To do this, I need JUnit output, and CircleCI needs to know the filename for each test in order to know how to run them. I've tried various options for getting the JUnit data, including:

* Calling cypress with `--reporter junit`
* Adding `mocha-junit-reporter` and configuring cypress to use that
* Adding the `cypress-multi-reporters` package configured to use `mocha-junit-reporter`

Running these for a single spec file produces output like this:

```html
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="10.8280" tests="1" failures="0">
  <testsuite name="Root Suite" timestamp="2020-08-10T17:44:31" tests="0" file="cypress/integration/editAccountSpec.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Editing my account" timestamp="2020-08-10T17:44:31" tests="1" time="10.8280" failures="0">
    <testcase name="Editing my account Successfully updates my data" time="10.8280" classname="Successfully updates my data">
    </testcase>
  </testsuite>
</testsuites>
```

Note that the only place where the file is listed is in the first `testsuite`, and I'm not even sure why that's there. For CircleCI to use this file for timings, the files need to also be on the other `testsuite` tag and each individual `testcase` tag. Here is an example from RSpec:

```html
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="rspec" tests="10" skipped="0" failures="0" errors="0" time="2.076701" timestamp="2020-08-10T12:18:35-04:00" hostname="ahwork.local">
<properties>
<property name="seed" value="13449"/>
</properties>
<testcase classname="spec.api.v1.admin.attachments_spec" name="Admin Attachments API /api/v1/admin/attachments get Allowed for admins returns a 200 response" file="./spec/api/v1/admin/attachments_spec.rb" time="0.632563"></testcase>
<testsuite>
```

I've been digging into the code for the `mocha-junit-reporter`, and it looks to me like the data passed to it does not include the file, so it's not a problem with that library, but I am not 100% sure.

**** Edit: the `mocha-junit-reporter` package makes no attempt to add the file to the individual `testcase` tags, so a change in cypress couldn't correct that. But when it is passed the suite directly from cypress in its `this._runner.on('suite', function(suite) {` the file is `null` for the one that represents the actual test suite. ****

### Desired behavior:

The file for each spec needs to be included in the `testcase` tags within the JUnit output.

### Test code to reproduce

```
cypress run --spec {spec} --reporter junit --reporter-options "mochaFile=cypress/results/my-test-output.xml,toConsole=true"
```

### Versions

```
Cypress package version: 4.12.0
Cypress binary version: 4.12.0
MacOS 10.15.6
Various browsers
```

**Comment by aub** [comment]
In mocha-junit-reporter, I added logging to print out the suite it receives in its `this._runner.on('suite', function(suite)` handler.  It first receives this one, which looks like it's the Root Suite:

```
Suite {
  title: '',
  ctx: {},
  suites: [
    Suite {
      title: 'Editing my account',
      ctx: {},
      suites: [],
      tests: [Array],
      pending: false,
      _beforeEach: [],
      _beforeAll: [],
      _afterEach: [],
      _afterAll: [],
      root: false,
      _timeout: 2000,
      _enableTimeouts: true,
      _slow: 75,
      _bail: false,
      _retries: -1,
      _onlyTests: [],
      _onlySuites: [],
      delayed: false,
      _events: [Object: null prototype],
      _eventsCount: 1,
      parent: [Circular],
      file: null,
      id: 'r2'
    }
  ],
  tests: [],
  pending: false,
  _beforeEach: [],
  _beforeAll: [],
  _afterEach: [],
  _afterAll: [],
  root: true,
  _timeout: 2000,
  _enableTimeouts: true,
  _slow: 75,
  _bail: false,
  _retries: -1,
  _onlyTests: [],
  _onlySuites: [],
  delayed: false,
  _events: [Object: null prototype] { newListener: [Function] },
  _eventsCount: 1,
  file: 'cypress/integration/editAccountSpec.ts',
  id: 'r1',
  type: 'suite'
}
```

and then it gets this one. Note that here the file is null. If it were passed a value for the filename then it would add it to the tag.

```
Suite {
  title: 'Editing my account',
  ctx: {},
  suites: [],
  tests: [
    Test {
      title: 'Successfully updates my data',
      fn: [Function],
      body: '---snip---',
      async: undefined,
      sync: undefined,
      _timeout: 2000,
      _slow: 75,
      _enableTimeouts: true,
      timedOut: undefined,
      _retries: -1,
      _currentRetry: 0,
      pending: false,
      type: 'test',
      duration: undefined,
      state: 'skipped',
      parent: [Circular],
      id: 'r3'
    }
  ],
  pending: false,
  _beforeEach: [],
  _beforeAll: [],
  _afterEach: [],
  _afterAll: [],
  root: false,
  _timeout: 2000,
  _enableTimeouts: true,
  _slow: 75,
  _bail: false,
  _retries: -1,
  _onlyTests: [],
  _onlySuites: [],
  delayed: false,
  _events: [Object: null prototype] { newListener: [Function] },
  _eventsCount: 1,
  parent: Suite {
    title: '',
    ctx: {},
    suites: [ [Circular] ],
    tests: [],
    pending: false,
    _beforeEach: [],
    _beforeAll: [],
    _afterEach: [],
    _afterAll: [],
    root: true,
    _timeout: 2000,
    _enableTimeouts: true,
    _slow: 75,
    _bail: false,
    _retries: -1,
    _onlyTests: [],
    _onlySuites: [],
    delayed: false,
    _events: [Object: null prototype] { newListener: [Function] },
    _eventsCount: 1,
    file: 'cypress/integration/editAccountSpec.ts',
    id: 'r1',
    type: 'suite'
  },
  file: null,
  id: 'r2',
  type: 'suite'
}
```

**Comment by chooban** [comment]
I have the same problem, and I've worked out a workaround for now. It seems to be working for me, or at least, I get the line `Autodetected filename timings` instead of a warning about not finding any timings.

It uses the [`yq` package](https://pypi.org/project/yq/) in XML mode to merge the two `testsuite` nodes in the test output.

If you have individual XML files for each test in a directory, then...:

```sh
for f in ~/my-test-results/test-results-*xml; do xq -x '. | { testsuites: { name: .testsuites."@name", time: .testsuites."@time", tests: .testsuites."@tests", failures: .testsuites."@failures", testsuite: [ .testsuites.testsuite[0] * .testsuites.testsuite[1] ] } }' "$f" | sponge "$f" ; done
```

I'm using custom docker images for the tests, so installing the extra packages required wasn't much an issue, I just needed to run `python3 -m pip install py` (probably works directly with `pip3` as well).

**Comment by Jonne** [comment]
I ran into the same issue, the [junit report github action](https://github.com/marketplace/actions/junit-report) couldn't parse the junit report files because of this. Inspired by @chooban, I created a [simple nodejs script](https://gist.github.com/Jonne/837caa9206a08b63cb35c21c542c1182) to fix the report.

**Comment by DanaGoyette** [comment]
For me, that fixup script just loses ALL the tests, thanks to multiple suites.  Really, they should all have the file set (and the nesting naming is incorrect too).

With a sample test (cypress/integration/sample.test.ts):
```typescript
context('Outer', () => {
  beforeEach(() => {})
  context('Inner', () => {
    beforeEach(() => {})
    it('Should be correct', () => {
      expect(false).to.be.true
    })
  })
})
```

I get the following junit xml file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2022-02-02T02:21:00" tests="0" file="cypress/integration/sample.test.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Outer" timestamp="2022-02-02T02:21:00" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Inner" timestamp="2022-02-02T02:21:00" tests="1" time="0.0000" failures="1">
    <testcase name="Outer Inner Should be correct" time="0.0000" classname="Should be correct">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:101:32)]]></failure>
    </testcase>
  </testsuite>
</testsuites>
```

Result of the fixup script:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Outer" timestamp="2022-02-02T02:21:00" tests="0" time="0.0000" failures="0" file="cypress/integration/sample.test.ts"/>
</testsuites>
```
