### ISSUE TITLE
Support storing record key in cypress.env.json

### ISSUE THREAD

**Issue by DonnyNavarro** [cypress-io/cypress#8243]
### Current behavior:

When a user stores their record key in `cypress.env.json` and then runs `npx cypress run --record`, the user receives an error:

> You passed the --record flag but did not provide us your Record Key

### Desired behavior:

A user would like to store the record key for a particular project in the project files, such as cypress.env.json, and then launch `cypress run --record` without specifying the key.

### Test code to reproduce

`npx cypress run --record`

### Versions

Cypress 4.12.1
OSX 10.15.6

**Comment by jennifer-shehane** [comment]
The `cypress.env.json` file is meant to store Cypress level [environment variables](https://on.cypress.io/environment-variables), not OS level env vars and not basic Cypress [CLI options](https://on.cypress.io/command-line#cypress-run). These environment variables are for whatever usage you want and don't match up to CLI options in Cypress. 

We don't recommend checking any record keys into source control as outline here: https://on.cypress.io/projects#Record-key

You'll need to look into a way to store secrets for reuse in your project to pass through the CLI or as operating system level environment variables `CYPRESS_RECORD_KEY`.
