### ISSUE TITLE
UI Issues: Selector playground with long selector does not display correctly / pushes UI off of view

### ISSUE THREAD

**Issue by hs8907** [cypress-io/cypress#8247]
![Screenshot 2020-08-11 at 3 36 51 PM](https://user-images.githubusercontent.com/55075778/89885421-a5df6c80-dbe8-11ea-83d5-6b9268ce7d08.png)

**Comment by jennifer-shehane** [comment]
Yah, this is not great. My long selector pushed the top UI off the screen.


<img width="1092" alt="Screen Shot 2020-08-12 at 1 36 03 PM" src="https://user-images.githubusercontent.com/1271364/89985269-cf5bcf00-dca0-11ea-8dcf-7143e4fb3e5d.png">
