### ISSUE TITLE
Uncaught Exceptions should clearly indicate where they originated from

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#825]
Currently when an uncaught exception causes a test to fail we only print the error.

This is confusing because Cypress fails the test for any kind of reason

- maybe there was an error in the test code itself
- maybe a command failed
- maybe your application threw an uncaught exception

In the cases of uncaught exceptions originating from your application we should **CLEARLY** indicate that is from your application code.

Bonus points for also doing the same thing when test code is the culprit.

**Comment by brian-mann** [comment]
Also we need a link to the Cypress Events to tell you how to turn this off

**Comment by jennifer-shehane** [comment]
Example of an error from my application under test. The *actual* stack trace is below a lot of messaging. I think most people see the error being thrown from `cypress_runner` and assume it's an error *in* `cypress_runner`

![screen shot 2017-11-15 at 1 49 24 pm](https://user-images.githubusercontent.com/1271364/32854237-f7744efe-ca0b-11e7-9334-b3c9829c3353.png)

**Comment by brian-mann** [comment]
When there are uncaught exceptions from your application...

![screen shot 2017-12-04 at 12 46 15 am](https://user-images.githubusercontent.com/1268976/33537949-99bb0df4-d88c-11e7-946c-934ac6d16550.png)

**Comment by brian-mann** [comment]
When there are uncaught exceptions from your test code...

![screen shot 2017-12-04 at 12 45 57 am](https://user-images.githubusercontent.com/1268976/33537953-a298f0d0-d88c-11e7-8179-c305cabfc5e2.png)

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/999

**Comment by brian-mann** [comment]
Released in [`1.1.3`](https://docs.cypress.io/guides/references/changelog.html#1-1-3).

**Comment by sayedit09** [comment]
Hi,
Please help .i'm getting this error
<img width="442" alt="Screenshot 2019-05-20 at 10 03 14 AM" src="https://user-images.githubusercontent.com/17846301/57996938-cd2fb280-7ae7-11e9-8223-e7ec1ec7b3ca.png">

**Comment by jennifer-shehane** [comment]
Hey @sayedit09, this error is coming from your application code - not Cypress. Click on the error with DevTools open and look at the stack trace to determine where this is being thrown in your application.
