### ISSUE TITLE
Cypress doesn't respect `Cypress.config('defaultCommandTimeout', n)` set within hooks or tests

### ISSUE THREAD

**Issue by Naren-Hub** [cypress-io/cypress#8250]
## Current behavior: 

Here is my piece of code:
```js
before(function () {
  Cypress.config("defaultCommandTimeout", 20000);
  cy.log(Cypress.config("defaultCommandTimeout"));
  cy.visit(Cypress.env("base_url"), {
    timeout: 60000
  })
  cy.get("button[tabindex='-1']").click();
});  
```

What I am trying to achieve is set the default command time out to 20 secs because my nextJS application takes more than the usual time during CI to load the content of the page.

Once the page is loaded, I expect Cypress to respect the timeout that I set, but it continues to wait for just 4sec which is the default time out. Refer to below screenshots.
Screenshot-1: Cypress started looking for element "button[tabindex='-1']" after 14.00 sec of execution
![image](https://user-images.githubusercontent.com/30796059/89890958-9592b600-dc17-11ea-9609-fa5cf55502eb.png)

Screenshot-2: Cypress threw exception that the element is not found within 4 secs (@ 19 seconds)
![image](https://user-images.githubusercontent.com/30796059/89890997-a6dbc280-dc17-11ea-8b9e-b985e6413013.png)

In the same screenshot, I have logged the timeout which is 20000 (see the log statement)

### Desired behavior:
Follow user settings.

### Test code to reproduce
Code is attached above.

### Versions
Cypress : 4.9.0

**Comment by jennifer-shehane** [comment]
Yeah, this is a bit weird. The `defaultCommandTimeout` does not appear to be taking effect when set in a `before` hook. 

### Doesn't set `defaultCommandTimeout` 

It doesn't set the new timeout if the timeout is set in a `before`, `beforeEach`, `afterEach`, or `after` hook or the `it` definition itself.

```js
before(() => {
  // doesn't work
  Cypress.config('defaultCommandTimeout', 20000)
  cy.log(Cypress.config('defaultCommandTimeout'))
  cy.get('button')
});  

it('test', () => {})
```

<img width="506" alt="Screen Shot 2020-08-12 at 1 17 31 PM" src="https://user-images.githubusercontent.com/1271364/89983761-33c95f00-dc9e-11ea-8afb-11db26ff2d70.png">

### Does set `defaultCommandTimeout` outside of hooks and test.

```js
// works
Cypress.config('defaultCommandTimeout', 20000)

before(() => {
  cy.log(Cypress.config('defaultCommandTimeout'))
  cy.get('button')
})

it('test')
```

Another workaround would be to set this value in the suite configuration - to apply across a suite of tests, but I know this isn't equivalent. 

```js
describe('tests', {
  defaultCommandTimeout: 20000
}, () => {
  it('test', () => {
    cy.log(Cypress.config('defaultCommandTimeout'))
    cy.get('button')
  })
})
```

**Comment by Naren-Hub** [comment]
@jennifer-shehane , both the workarounds worked for me and I used the latter one since it looks cleaner :)
Also, I haven't checked for the other config items but for me, it appears that the 'Cypress.config("foo": "bar")' changes will not take effect if set in hooks; I could be wrong as well.

Anyways, thank you for the workaround. Cheers!
