### ISSUE TITLE
Fetch problem with Firefox and {"experimentalFetchPolyfill": true}

### ISSUE THREAD

**Issue by Fanch-** [cypress-io/cypress#8262]
### Current behavior:

Using "experimentalFetchPolyfill": true, it seems calls (stub or not) are ignored on FF (it works fine on Chrome)

### Desired behavior:

To work also on Firefox.
Our prod link will be given for the example. I hope you could reproduce.

Goal -> get this fetch request :
![image](https://user-images.githubusercontent.com/7208988/90038788-1b6d3a80-dcc6-11ea-97d9-d5e9338b55a9.png)

### Test code to reproduce

```js
  it.only('should call /api/ad-geoloc/v1/autocomplete for city autoCompletion ', () => {
    cy.visit('https://www.leboncoin.fr/compte/pro/creation/')
    cy.get('#location').type('75015')
    cy.get('[data-qa-id="cta-locations_suggestion"]').should('be.visible')
  })
```
with ` {  "experimentalFetchPolyfill": true}` (removing it, we can observe that the call passes)

Reproducible with cypress open.

### Versions
Ubuntu 18.04.4
node : v12.14.1
npm : 6.14.7
**cypress: 4.12.1**
chrome: 84
**firefox: 79**

Thank you for your time.

**Comment by jennifer-shehane** [comment]
Most of the time trying to load the page, I get a 403 forbidden response trying to run the code provided. 

I also keep running into a bot check trying to run the code. 

<img width="1602" alt="Screen Shot 2020-08-14 at 2 13 29 PM" src="https://user-images.githubusercontent.com/1271364/90226051-6b6c0e80-de38-11ea-81f1-6e8379cc817e.png">



Please provide all code required to run (including any cypress.json, support, plugins, etc) reliably each time to demonstrate the failing test. 

<img width="511" alt="Screen Shot 2020-08-14 at 2 14 46 PM" src="https://user-images.githubusercontent.com/1271364/90226117-88084680-de38-11ea-9cf9-7a0cd9e0f02f.png">


<img width="523" alt="Screen Shot 2020-08-14 at 2 08 08 PM" src="https://user-images.githubusercontent.com/1271364/90225623-b20d3900-de37-11ea-9edb-494724b3bbc1.png">

**Comment by Fanch-** [comment]
I didn't think about the bot protection.

Well I tried to reproduce on several websites in the same condition but it worked fine, so I guess it's something related to our app. Closing then, thank you for taking a look.
