### ISSUE TITLE
Cannot select browsers except Electron on new cypress installation on Windows 10

### ISSUE THREAD

**Issue by folkman345** [cypress-io/cypress#8263]
### Current behavior: 
The Cypress is not recognizing any other browsers except the Electron 80 even thought I have chrome, firefox, edge, brave, etc...

Here is the picture showing all the browsers I have on my PC:
![Screenshot (76)](https://user-images.githubusercontent.com/58590419/90048720-2c24ad00-dcd4-11ea-997d-e62030f150b9.png)

Here is the picture showing the cypress and that it is missing the drop-down option near the browser name:
![cy1](https://user-images.githubusercontent.com/58590419/90048746-3777d880-dcd4-11ea-853c-288fcc2ef898.JPG)

### Desired behavior:
I need to be able to select all of the available browsers for testing various web sites and currently I cannot select any other than Electron 80.

### Versions
Cypress version: 4.12.1
Windows 10 Pro - 10.0.18363 Build 18363
Edge: 84.0.522.59
Firefox: 79.0
Chrome: 84.0.4147.125

**Comment by jennifer-shehane** [comment]
Please see our [troubleshooting guide on Launching Browsers](https://on.cypress.io/troubleshooting#Launching-browsers)

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) specifically logging `cypress:launcher` logs and run `cypress info` - this will help you in troubleshooting why the browsers are not currently found.
