### ISSUE TITLE
Updates to 'set up project' dialog needed for future billing.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#827]
There are a few things that need to be updated in the desktop-gui when billing is released in the Dashboard.

- Remove line "Free while in beta, but will require a paid account in the future" 
- If org selected is over their private projects limit (dependent on [cypress-api#249](https://github.com/cypress-io/cypress-api/issues/249)), display "In order to make this project private, you need to [upgrade your account]()." - link should go to `dashboard.cypress.io/organizations/:id/billing`. 
- Display banner within 'runs' tab when project's org is over it's recorded tests limit. This would require polling the GET org endpoint (which I don't think we are doing currently).

**Comment by jennifer-shehane** [comment]
@chrisbreiding @brian-mann Need `ipc.getUsage(id)` to return GET `organizations/:id/usage`

Branch: https://github.com/cypress-io/cypress/tree/issue-827

**Comment by chrisbreiding** [comment]
@jennifer-shehane I added `ipc.getUsage(id)` and added respective unit/integration tests. I have *not* tested it IRL hooked up to `cypress-api` though.

**Comment by jennifer-shehane** [comment]
- [ ] Need to poll for GET `orgs` in dialog (maybe only if one is selected?) so that if their plan changes, the dialog options will refresh.
- [ ] When selecting `org` that allows private projects, 'does not allow' flashes in real quick then disappears.

**Comment by jennifer-shehane** [comment]
Todo: remove restriction on # of private projects.

**Comment by brian-mann** [comment]
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).
