### ISSUE TITLE
Error "GtkDialog mapped without a transient parent"

### ISSUE THREAD

**Issue by einfallstoll** [cypress-io/cypress#8270]
### Current behavior:

When I run Cypress 4.12.1 in a GitHub Action a CPU intense test case generates the following errors in the log and the will fail afterwards:

```
Gtk-Message: 20:04:36.510: GtkDialog mapped without a transient parent. This is discouraged.

(Cypress:3769): dconf-WARNING **: 20:04:36.629: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”

(Cypress:3769): dconf-WARNING **: 20:04:36.665: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”
```

The test case does run on my machine _(the old classic)_ in both headless and non-headleass mode.

### Desired behavior:

No idea? I don't even understand the problem. Maybe the resources are exhausted, maybe it's a bug, or something else.

### Test code to reproduce

If **you** understand the error message, you can tell me what it means and I could try my best to create a reproducible example for you. Maybe this isn't even needed because it's super clear to you and you know the error?

### Versions

4.12.1, GitHub Action Runner on Ubuntu 18.04, I guess.

**Comment by jennifer-shehane** [comment]
No, I haven't seen this error. Someone in our chat previously mentioned encountering this error when they were trying to download a PDF. 

Unfortunately we'll have to close this issue if there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example.

**Comment by einfallstoll** [comment]
@jennifer-shehane This is interesting. However, I do not download any PDF. Could this be due to a "tab not responding" dialog? The test is _very_ heavy and due to the speed of Cypress, I assume, it's just exhausting browser resources.

**Comment by jennifer-shehane** [comment]
@einfallstoll You can log the memory and CPU usage of Cypress by following these instructions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage This will help determine if Cypress is running out of resources and whether the machine requires more.

**Comment by einfallstoll** [comment]
Apparently the errors have no direct influence to my failing builds and they *sometimes* pass. The log entries are ugly, but I can live with them. Fixing my build is another story, but none of your business. Thanks for your help!
