### ISSUE TITLE
If NPM config's `noproxy` is set, `NO_PROXY` rules will apply incorrectly

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#8287]
### Current behavior:
After merging #7900, changes in `proxy-from-env` cause the `npm_config_noproxy` environment variable to be considered above `NO_PROXY`. This is problematic because internally, we set `NO_PROXY` to contain the user's original `NO_PROXY` settings, as well as things which should never be proxied like `localhost`. The end result is bad behavior, like requests for `localhost` being sent through the proxy.

### Desired behavior:
`npm_config_noproxy` acts as a fallback for `NO_PROXY`.

### Workaround
Ensure that NPM config's `noproxy` setting is empty when launching Cypress, so that `NO_PROXY` is preferred. This can be done [via environment variables](https://docs.npmjs.com/misc/config).

For example (Linux/macOS):

```
npm_config_noproxy= npm run cypress:run
```

Or on Windows, using `cross-env`:

```
cross-env npm_config_noproxy= npm run cypress:run
```

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-251) by [Unito](https://www.unito.io/learn-more)

**Comment by flotwig** [comment]
For now I think it's best to just revert the dep update, and wait to see if Rob--W/proxy-from-env#13 is chosen, in which case we can use that version.

**Comment by jennifer-shehane** [comment]
>this update shouldn't affect users

Famous last words
