### ISSUE TITLE
cy.writefile is not writing the excel properly in a readable format

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#8289]
### Current behavior:
`cy.writefile` is writing the excel file in a non-readable format in spite of doing the encoding. Below is the line of code

```js
cy.writeFile('test.xls',response1.body,'UTF-8');
```

### Desired behavior:

Should write the excel in a proper readable format.

![2020_08_15_12_29_35_test_Excel](https://user-images.githubusercontent.com/68634900/90307445-c9a9f780-def3-11ea-978c-bb28b07cba9e.png)

 Cypress, operating system, browser - 4.12.1,Windows 10,Chrome

**Comment by jennifer-shehane** [comment]
Can you provide the data that would represent `response.body1` so that we can run the code? Thanks!

**Comment by sudheer-cypress** [comment]
[Order_Summary_Report_08-13-2020_00-58-42.xlsx](https://github.com/cypress-io/cypress/files/5083631/Order_Summary_Report_08-13-2020_00-58-42.xlsx)

That's actually a xls file,since your attachment allows only xlsx i changed it from xls to xlsx and attached for your reference.

Here my requirement is to convert the excel data to json and make use of the converted json data at some other place.

**Comment by jennifer-shehane** [comment]
@sudheer-cypress Have you taken a look at this recipe? https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__csv-table

You may need some other plugin to help read in / out the data so that it's properly formatted for use.

**Comment by sudheer-cypress** [comment]
@jennifer-shehane  There are two things that i am looking here
1) write the contents from excel(which i am getting from API response to a file)
2)Read the contents from the created file from step 1.Here i am stuck at step1.

The solution you gave me above applies to step 2 i.e for parsing the excel file. I am stuck at step 1 where i am unable to write contents to excel in an readable format.

**Comment by sudheer-cypress** [comment]
@jennifer-shehane Could you please update on this?we see this as most important feature in our project.If cypress could not handle this we may have to move to other tools. pls look into this asap

**Comment by jennifer-shehane** [comment]
I would probably suggest running a task - and handling writing the contents back to the Excel file using some other node module that specifically writes to Excel files. https://on.cypress.io/task

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
