### ISSUE TITLE
Get the list of all the server requests and its response properties 

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#8290]
Get all the server request list that happens while performing the actions of either navigation or the button click by the scripts. 
Here, we are not talking about the cy.request  done. That we can easily track and get the response details. But, the request that happens when executing some actions or navigating to different pages when cypress scripts is executed.

This is the Request to include this feature. 

We want to track and log the time taken for each actions from client to server and server to client when running the scripts. 
So, for this we have to track each server call which requests during script execution.

**Comment by jennifer-shehane** [comment]
There's a plugin where you can export the har - which would be a log of all the network requests: https://github.com/NeuraLegion/cypress-har-generator

There's also a blog about how to log the time each command/test takes - with examples of how you can capture that: https://www.cypress.io/blog/2020/05/22/where-does-the-test-spend-its-time/

Would either/both of these provide what you're looking to capture?

**Comment by Prashant-Kan** [comment]
Thx @jennifer-shehane for the Reference

I will look into both and let you know then

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
