### ISSUE TITLE
Cypress incorrectly scrolls element under other element - making it fail visibility check to click

### ISSUE THREAD

**Issue by dtom90** [cypress-io/cypress#8292]
### Current behavior:
I'm writing a test in which I navigate to this page:

![](https://user-images.githubusercontent.com/911671/90334576-9ec7ae00-df9c-11ea-85f0-e0c4b5080598.png)

and then I try to click the green **Start Workout** button. 

However, when I do `cy.get('.button').contains('Start Workout').click()`, Cypress scrolls to here:

![](https://user-images.githubusercontent.com/911671/90334609-e0585900-df9c-11ea-9477-ebb611a3e902.png)

where the button is barely visible.

So when I try to do a standard click, I get:

![](https://user-images.githubusercontent.com/911671/90334687-72f8f800-df9d-11ea-9515-bff14788fcdb.png)

I believe that this is probably due to the navbar changing size during the scroll, as can be seen from the images. However, as can be seen from the first image, no scrolling is needed to click the button.

I tried several workarounds without success, including scrolling manually before the `click`. It seems that the `click` itself is trying to scroll to the element, offsetting it from the visible area. The only workaround that worked was the following:

```js
cy.get('.button')
  .contains('Start Workout')
  .click('bottom')
```

since the bottom edge of the button is still visible.

### Desired behavior:
It would be nice to not have to click an edge of a button during tests, especially when no scrolling is necessary. If the test could pass with:

```js
cy.get('.button')
  .contains('Start Workout')
  .click()
```

that would be great.

### Test code to reproduce
Relevant test:
https://github.com/dtom90/cypress-test-tiny/blob/master/cypress/integration/activeWorkout.spec.js

### Versions

* `Cypress package version: 4.12.1`
* `macOS 10.15.6`
* `Google Chrome Version 84.0.4147.125`

**Comment by jennifer-shehane** [comment]
@dtom90 Thanks for providing a reproducible example! I see this has been failing all the way back to 3.4.0, so I don't think this is a regression.

### Repro

I narrowed the example down to the following HTML, where the anchor link slides underneath the 'navbar' at the top, saying it cannot be clicked.

`index.html`

```html
<html>
<body style="width: 100%; overflow: hidden; margin: 0;">
  <div style="position: absolute; z-index: 500; width: 100%; height: 64px; background-color: blue;"></div>
  <div style="overflow: auto; height: 100%;">
    <div style="height: 300px;"></div>
    <a style="background-color: red; position: relative;">Start</a>
    <div style="height: 2000px;"></div>
  </div>
</body>
</html>
```

```js
it('should click anchor', () => {
  cy.visit('index.html')
  cy.get('a').click()
})
```

<img width="856" alt="Screen Shot 2020-08-17 at 12 46 16 PM" src="https://user-images.githubusercontent.com/1271364/90362908-aa43d380-e087-11ea-9440-ce73624944d1.png">

### Workaround

Pass `force: true` to the click to avoid our auto scrolling behavior.

**Comment by jennifer-shehane** [comment]
I thought this may be related to this issue, but I'm not so sure since there are no sticky elements in the example here: https://github.com/cypress-io/cypress/issues/4233

**Comment by sainthkh** [comment]
By default, Cypress scrolls the screen until the element is at the top of the view before sending click events. You can change this behavior by setting [`scrollBehavior`](https://docs.cypress.io/guides/references/configuration.html#Actionability):

```js
it('should click anchor', () => {
  cy.visit('index.html')
  cy.get('a').click({ scrollBehavior: 'center' })
})
```

In your case, just setting `scrollBehavior` to `false` would work.
