### ISSUE TITLE
Unable to scroll a container 

### ISSUE THREAD

**Issue by borecz** [cypress-io/cypress#8293]
### Current behavior:

After I reach the page, open the filter menu I am unable to scroll down to access further filters.

### Desired behavior:

I should be able to scroll the current element.

### Test code to reproduce
```js
describe('Try to scroll', () => {
  it('simple test', () => {
    cy.viewport('samsung-s10')
    cy.visit('https://m.aboutyou.de/frauen/bekleidung/kleider', {
      headers: {
        'user-agent':
          'Mozilla/5.0 (Linux; Android 10; SM-N970F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36',
      },
    })
    cy.get('[data-cy="floatingActionButtonContainer"]')
      .should('be.visible')
      .click()
    // here
    cy.scrollTo('bottom')
  })
})
```

### Versions
MacOS, Cypress 4.12.0

Can you please provide an example of how to use the `trigger` doing: swipe up and down with 2 fingers?

**Comment by jennifer-shehane** [comment]
With the code provided, the webpage never loads. Please provide all code to run the example tests - including any `cypress.json`, support or plugins code required and we will consider reopening.

<img width="565" alt="Screen Shot 2020-08-17 at 11 42 48 AM" src="https://user-images.githubusercontent.com/1271364/90359381-d018aa80-e07e-11ea-8065-c00dc7121cdc.png">


Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by borecz** [comment]
@jennifer-shehane jennifer-shehane here attached you can find the repo with only the test mentioned above.

Hope you can help finding out a solution to that.
[cypress-example-scrolling-issue.zip](https://github.com/cypress-io/cypress/files/5083851/cypress-example-scrolling-issue.zip)
