### ISSUE TITLE
Add configuration option to disable/enable multiple commands logging

### ISSUE THREAD

**Issue by Max-Strick** [cypress-io/cypress#8296]
This issue relates to the #3087

### Current behavior:

I have many commands that are not desired to be logged: setting states, clearing fields, etc. Mostly it relates to the negative cases when I do smth repeatable. For example,  iterate through the array with invalid characters and type them into the input field: 

```js
cy.get('@fullname').then(input => {
  credentials.invalid.fullname.IncorrectSymbolsArray.forEach((incorrectSymbol) => {
    cy.wrap(input, { log: false }).clear({ log: false }).type(`${credentials.valid.fullname.default}${incorrectSymbol}`)
  });
}).clear({ log: false })
```
_(some assertions will be added)_

In this case, if logging is not turned off, the left side log looks very "crowded".  I need information only about characters that are typed.

So, about 70% of commands have `{log: false}` option in my tests. It takes time to add this option and code looks not so pretty.

### Desired behavior:

I have a proposition:

1. Provide a global logging setting in the configuration file. By default, it should be true.
2. Provide `{log: }` option for `context()` and `it().`
3. Priority order: command() > it() > context() > global configuration

So, then users have the ability to enable/disable logging in different scopes.

### Versions
 4.12.1

**Comment by jennifer-shehane** [comment]
I don't think adding a global configuration would be something we would explore. Logging commands is a core part of our product, so turning them off completely would mean there is nothing shown in the test runner. 

I could maybe see this being available in the test configuration (it() level), but I also see this as being a very small use case. 

Assuming you are generating [custom commands](https://on.cypress.io/custom-commands#Syntax) for each of these actions (which is what I would recommend), I could see allowing some kind of setting there to disable all logging of commands within it, as I see this as a pretty common use case. But also, I'm not sure how this would be implemented exactly with how the current API is designed. 

We'll leave this open to see if there is any more support for this. It's not high priority now for us however.

**Comment by kumzme** [comment]
`Logging commands is a core part of our product, so turning them off completely would mean there is nothing shown in the test runner.`
I did not know how petty or idiotic software designers [ or any other designers ] could be .. way to go cypress.

**Comment by jennifer-shehane** [comment]
Please be mindful of our Code of Conduct when interacting with our team and other commenters in our issues. https://github.com/cypress-io/cypress/blob/develop/CODE_OF_CONDUCT.md

**Comment by jennifer-shehane** [comment]
Since this request hasn’t gotten a lot of interest over the years, we’ll close this issue.
