### ISSUE TITLE
fs.readFileSync is not a function error  while reading data from properties file

### ISSUE THREAD

**Issue by ratnakarbellary** [cypress-io/cypress#8298]
```js
const PropertiesReader = require('properties-reader');
```
![error](https://user-images.githubusercontent.com/68541248/90400539-41c21a00-e0ba-11ea-8628-90598cfd506a.PNG)

```js
When('I Search {string} in search field', (searchText) => {

  commonORFile = PropertiesReader('./common-or.properties');

  console.log("commonORFile " + commonORFile.get("homepage.searchfield"))

})
```
![error](https://user-images.githubusercontent.com/68541248/90400593-54d4ea00-e0ba-11ea-8bef-a9702409c222.PNG)

**Comment by jennifer-shehane** [comment]
This error is being thrown from within the `properties-reader` node_module. You can see this by the stack trace we provide - `at PropertiesReader.append (node_modules/properties-reader/src/properties-reader.js:75:1`

I suggest referring to their documentation or opening an issue in their module if you believe this to be a bug.
