### ISSUE TITLE
Favicon isn't retina-ready

### ISSUE THREAD

**Issue by BrunoBernardino** [cypress-io/cypress#83]
My eyes!!!!

<img width="192" alt="screen shot 2015-11-16 at 21 48 30" src="https://cloud.githubusercontent.com/assets/1239616/11195799/cdb1675e-8cab-11e5-96d2-2970f47df231.png">

**Comment by brian-mann** [comment]
Will be fixed in the next release.

**Comment by brian-mann** [comment]
Fixed in [`0.12.4`](https://github.com/cypress-io/cypress/wiki/changelog#0124-11192015).
