### ISSUE TITLE
Add `session` API for snapshotting/restoring session related data (cookies, localStorage, sessionStorage)

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#8301]
## Summary

We would like to implement solutions for authentication and switching between user sessions.

To accomplish those objectives, we need to save checkpoints that represent the browser’s state at the end of some steps the user has performed. After saving the state we will be able to go back and forth between points in time.

For the time being we will call this a **Session**, though the name is up for debate.

---

Currently, if your tests rely on having set session related data (e.g. cookies, localStorage, sessionStorage), you have two choices:

- "build up" session data through UI interactions (similar to Page Object Pattern). For multiple tests that use the same session data, this leads to either slower tests (steps done in `beforeEach` every test) or leads to tests that can't run in isolation (requiring previous tests to build up state).
- use `cy.request`/`cy.setCookie` to programmatically set session data. For multiple tests, this reduces execution time drastically compared to Page Object Pattern. However this requires more knowledge about your app's auth to setup, can potentially be a maintenance burden, and covers less your app.

`cy.session` is meant to merge the simplicity of Page-Object-Pattern to the execution speed of programmatic auth. With `cy.session`, you'll be able to perform UI interactions before taking a "snapshot" of all the session related data and "restore" it before each test. 

### Defining a Session 
Sessions should be defined at the root level of your Cypress project, within `cypress/sessions.js`. A best practice is to define all of your sessions here instead of in individual spec files.

### Defining a Single Session

The proposed API for defining a single Session looks like this:

```ts
export const admin = cy.defineSession({
  name: 'admin',
  steps() {
    cy.get('#username').type('my-username')
    cy.get('#password').type('my-password')
    cy.get('#login').click()
  },
})
```

### Defining Multiple Sessions

Some alternate syntaxes utilize a `Cypress.defineSessions()` method to add many sessions at once. The keys in this object are the session names, and the value can either be a function or a Session Object.

```ts
// The keys in this map to session names
// The values may either be Session object or a Steps function
export const sessions = cy.defineSessions({
  admin() {
    cy.get('#username').type('admin-username')
    cy.get('#password').type('admin-password')
    cy.get('#login').click()
  },
  regularUser: {
    steps() {
      cy.get('#username').type('basic-username')
      cy.get('#password').type('basic-password')
      cy.get('#login').click()
    }
  }
}
```

### Assuming a Session

Assuming a session will be done in either a `beforeEach` or within a block (`it`/`describe`), so that each test starts from a single session, or programmatically whenever a user wants.

There are two ways to assume a session. One takes advantage of per-test configuration and the other is a method on the `cy` object. The API design goal is for sessions to be real Type-able objects that can be used. We will still support string-lookup of sessions by name, but using real JavaScript objects is preferred.

### Programmatic API

By reference

```ts
import { admin } from './sessions'

// Switch between sessions programmatically using the Session's object
cy.useSession(admin)

// Remove previous state, rebuild and then use the session
cy.useSession(admin, { fresh: true })
```

By string
```ts
// Switch between sessions programmatically using Session.name
cy.useSession('admin')
```
Per-test configuration
By reference

```ts
import { admin } from './sessions'
describe('As an administrator', { session: admin }, () => {
  /* ... */
})
By string
describe('As an administrator', { session: 'admin' }, () => {
  /* ... */
})
```
### Retrying Corrupt Sessions

When assuming a session throws an error, it is considered corrupt. Sessions may be corrupt for a number of reasons: Bugs in the Steps logic, corrupt state from previous tests, invalid login tokens, or general flake.

If this happens, the session’s internal state will be invalidated, and it will be rebuilt from scratch. After this, the test run will proceed as normal.

### Composition with Sessions

Because sessions are simply a set of steps and a starting state, it is possible to compose with them by reusing `cy.useSession`

To create a new user with many cart items, you’d do

```ts
const seedDb = () => cy.task('create:user')

// prefer by-function steps because adding onto
// state will possibly pollute any backends
const loginSteps = () => { /* login steps */ }
export const newUser = cy.defineSession({
  steps() {
    //  seedDb()
    /* signup */
    loginSteps
  },
  before() { seedDb() } // always exec
})

export const userWithItems = cy.defineSession({
  steps() {
    loginSteps()
    // add an item to the cart, etc
  } 
})
```

Or to create a user who opts out of tracking before signing up, you’d do: 
	
```ts
export const privacyConsciousUser = cy.defineSession({
  steps() {
    // opt out of setting cookies
    // This assumes the backend or cookies would persist this info
    // window state is NOT stored with the session.
    cy.window()
      .then((win) => win.optOut = true)

    cy.useSession(newUser)
  }
})
```

The combined state at the end of the steps function is stored as that Session’s state

**Comment by LookRain** [comment]
does this approach cover the case that needs to redirect to a different domain for authentication, such as Google Auth?

**Comment by Bkucera** [comment]
@LookRain this doesn't enable visiting more than one domain per test, however we are working on a solution for that as well.

**Comment by LookRain** [comment]
> @LookRain this doesn't enable visiting more than one domain per test, however we are working on a solution for that as well.

Hi @Bkucera , thanks for the reply. Is the "solution" [this PR](https://github.com/cypress-io/cypress/pull/8765)?
