### ISSUE TITLE
Testing an empty attribute value fails

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#831]
This code fails

```js
it "inputs", ->
  cy.visit("/index.html")

  cy.get("input[type=file]").should("have.attr", "title", "")
  cy.get("input[type=email]").should("have.attr", "title", "")
  cy.get("input#t").should("have.attr", "title", "")
```

```html
<html>
  <input type="file" title="" />
  <input type="email" title="" />
  <input id="t" title="" />
</html>
```

![screen shot 2017-10-26 at 6 36 42 pm](https://user-images.githubusercontent.com/1268976/32080280-cb028cf8-ba7c-11e7-810e-8fe27162c5b3.png)

**Comment by danielneri-accesso** [comment]
+1

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/1480

**Comment by Karrar-Naqvi** [comment]
Hello,
I am having same kind of issue. I am trying to verify an error message, but cypress is unable to read that message and says that value is empty.

**My Piece Of Code:**

cy.get('#mat-input-0').type('abc@xyz.com')
        cy.get('#mat-input-1').type('123456')
        **cy.get('#mat-error-0').should('have.value', ' Please enter the correct pattern. ')**
        cy.get('button').click()

Message of Cypress:

![CypressIssue2](https://user-images.githubusercontent.com/49785432/56424665-b882b380-62ca-11e9-9865-2378c99d777b.jpg)

Page Details:

![CypressIssue](https://user-images.githubusercontent.com/49785432/56424508-fe8b4780-62c9-11e9-8461-46f476121607.jpg)

Here it should verify the error/alert message but I am unable to do so ... Help Required.

**Comment by jennifer-shehane** [comment]
`.should('have.value'` asserts on the actual `value` attribute of an `input` DOM element. Your error is displaying within a `mat-error` DOM element, not being set as the `value` of the input. 

You should be able to write something like 

```js
cy.get('#mat-input-0').type('abc@xyz.com')
cy.get('#mat-input-1').type('123456')
cy.get('#mat-error-0').should('contain', 'Please enter the correct pattern.')
cy.get('button').click()
```
