### ISSUE TITLE
Cypress installs critical security vulnerabilities, preventing it from running in CI pipeline

### ISSUE THREAD

**Issue by filipemir** [cypress-io/cypress#8314]
Hey folks,

I've been trying hard to integrate Cypress into our our CI pipeline. We deploy our services in docker containers and  then analyze the resulting image against a list of know vulnerabilities. Critical vulnerabilities fail the build, well before we ever get to run the end-to-end tests. I suspect this applies to a lot of folks out there who would want to use Cypress in their CI pipeline Unfortunately, Cypress is installing a module with a critical vulnerability (in the `server` package) that has been known since 2015: the `tar@0.1.20` module. See https://www.npmjs.com/advisories/57. As a result, we can't currently use Cypress in our CI pipeline

I dug a little into this and realized that the dependency is brought in by `node-webkit-updater`, a defunct project that you have forked. Here's the offending line: https://github.com/cypress-io/cypress/blob/9a32d226bbd2fabf27266a8d143b1a71e6eb2826/packages/server/package.json#L92

I should note that Cypress is also bringing in a number of other vulnerabilities. Currently, those aren't an issue for us because we are only failing on critical vulnerabilities, but they may be for other people with stricter security requirements. Here's the list:
High 
* `qs@5.1.0`: also introduced by `node-webkit-updater` ([advisory](https://www.npmjs.com/advisories/1469))
* `minimatch@2.0.10`: introduced by `babel-core` [(advisory)](https://www.npmjs.com/advisories/118)
* `http-proxy@1.18.0`: ([advisory](https://www.npmjs.com/advisories/1486))

Moderate:
* `tunnel-agent@0.4.3`: also introduced by `node-webkit-updater` ([advisory](https://www.npmjs.com/advisories/598))
* `hoek@2.16.3`: also introduced by `node-webkit-updater` ([advisory](https://www.npmjs.com/advisories/566))

### Current behavior:
Installing Cypress installs a version of `tar` below `2.0.0`

### Desired behavior:
Installing Cypress should not install a version of `tar` below `2.0.0`

### Test code to reproduce
Pull this repo, install dependencies with `yarn`, and then run `yarn why tar`. Result should indicate that `tar@0.1.20` was installed:
```
...
=> Found "tar.gz#tar@0.1.20"
info This module exists because "_project_#@packages#server#node-webkit-updater#tar.gz" depends on it.
info Disk size without dependencies: "220KB"
info Disk size with unique dependencies: "468KB"
info Disk size with transitive dependencies: "956KB"
info Number of shared dependencies: 17
...
``` 

### Versions
At least `14.7.1`

**Comment by jennifer-shehane** [comment]
There's not any great reason that we've kept `node-webkit-updater`. This can be replaced. We're open to PRs to replace this dep.

**Comment by pverdile** [comment]
I'd like to start working on this.

**Comment by fedebertolini** [comment]
hi everyone, I saw no movement on this topic so I went ahead and created a PR addressing the main issue with the `node-webkit-updater` dependency: https://github.com/cypress-io/cypress/pull/8807
