### ISSUE TITLE
cypress.run() raise error - fs.existsSync is not a function

### ISSUE THREAD

**Issue by hyunjoo-sue** [cypress-io/cypress#8316]
### Current behavior:

`require('cypress')` is not working 

I was trying to test the script from cypress document. 
https://on.cypress.io/module-api#Example

very simple testing.

This raised error like this

---

![cypresserror](https://user-images.githubusercontent.com/59125573/90586528-84efca80-e22b-11ea-9779-59bdb3645241.JPG)
)

### Desired behavior:

This is a simple test followed the sample, so I think it should work.

### Test code to reproduce
My script is like this.

----
```js
const cypress = require('cypress')

cypress.run({
  spec: 'C:/Work/ecoPortal/source/ecoPortal/cypress/integration/Testing/sample.spec.js'
})
.then((results) => {
  console.log(results)
})
.catch((err) => {
  console.error(err)
})
```

---

The error seem to be from `require('cypress')`, because I removed other script and only left the first line, the error was the same. 
Like this

----
```js
const cypress = require('cypress')

describe('cypress test',()=>{
  it('is this work?', ()=>{
    cy.log('working')
  })
})
```
---

Still it shows the same error. How can I fix this?

### Versions
4.4.1

Windows 7, chrome

**Comment by jennifer-shehane** [comment]
Cypress cannot be required from within the spec files themselves - these files execute within the context of the browser, so have no Node.js which causes this error where fs will not exist. You do not need this included in any files within `cypress/integration/*` - remove it. 

To run via the Module API, you require cypress within a file that is then executed in Node.js. So if you have the require statement file at `script.js`, you would run `node script.js` to execute the file and get Cypress running. 

I'll update the docs to be more clear about how to execute this file.

**Comment by jennifer-shehane** [comment]
I opened a PR to update the instructions in the doc here: https://github.com/cypress-io/cypress-documentation/pull/3079

**Comment by hyunjoo-sue** [comment]
It works. Thank you. :+1:
