### ISSUE TITLE
Add browser + version to stdout

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#833]
Users are confused we are launching Electron headlessly instead of Chrome.

We should print out the browser + version in stdout prior to the `(Tests Starting)` message, and then also include it in the `(Tests Finished)` message.

**Comment by bahmutov** [comment]
Agree, this is great basic info to print by default with CI

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/1722
