### ISSUE TITLE
Retry mechanism of 'should' can erroneously cause the arguments to .should() to be null when cy.log() in fn

### ISSUE THREAD

**Issue by GCHQDeveloper911** [cypress-io/cypress#8346]
### Current behaviour:
If I want to assert an element doesn't exist in the DOM, I have the option of simply doing something like:
```js
cy.get('#notFound').should('not exist');
```

However, in the logging, this simply returns a rather crude `Expected null not to exist`. In my view, a better way of doing the assertion is:
```js
cy.get('#notFound').should((elem) => {expect(elem).to.not.exist})
```

Which produces a log of `Expected #notFound to not exist` - which is far more informative.

However, I've discovered that if I then try and do more within the 'should' block, Cypress fails, reporting that it DID expect to find the element:

```js
cy.get('#notFound').should((elem) => {expect(elem).to.not.exist; cy.log('As we thought, it is not there')})
```

This produces 'Timed out retrying: Expected to find element: #notFound , but never found it.'

Similarly, the following works:
```js
cy.get('#thisElemIsFound').should((elem) => {expect(elem).to.exist})
```

Yet the following returns 'expected null to exist'
```js
cy.get('#thisElemIsFound').should((elem) => {expect(elem).to.exist; cy.log('As we thought, it is there')})
```

### Desired behavior:

All the following statements should pass - the only difference being, the last two should produce the `cy.log` statements. In summary, it should be possible to do more than just a simple expect statement within the should block.

```js
cy.get('#notFound').should((elem) => {expect(elem).to.not.exist;})
cy.get('#thisElemIsFound').should((elem) => {expect(elem).to.exist;})
cy.get('#notFound').should((elem) => {expect(elem).to.not.exist; cy.log('As we thought, it is not there')})
cy.get('#thisElemIsFound').should((elem) => {expect(elem).to.exist; cy.log('As we thought, it is there')})
```

### Test code to reproduce

Please see above - obviously you'll need to substitute the selectors as appropriate!

### Versions

Cypress 12.1, CentOS 8, Chrome 83.

**Comment by jennifer-shehane** [comment]
Yeah, this is definitely incorrect behavior. Just to remove the concept of negating the assertions, the code below demonstrates the problem with just checking existence alone. 

This seems to have always been the behavior, went back to Cypress 3.4.1.

### Repro

```html
<html>
<body>
  <div id="thisElIsFound">El</div>
</body>
</html>
```

```js
it('test', () => {
  cy.visit('index.html')

  cy.get('#thisElIsFound').should((el) => { 
    expect(el).to.exist // passes, element exists
  })

  cy.get('#thisElIsFound').should((el) => {
    expect(el).to.exist // fails, expected null to exist
    cy.log('As we thought, it is there')
  })
})
```

<img width="560" alt="Screen Shot 2020-08-20 at 3 40 18 PM" src="https://user-images.githubusercontent.com/1271364/90750898-783aa780-e2fb-11ea-8b16-745c7325b26f.png">

The `el` is initially defined, but then on the next retry, the `el` is `null`.

<img width="709" alt="Screen Shot 2020-08-20 at 3 45 56 PM" src="https://user-images.githubusercontent.com/1271364/90751557-4e35b500-e2fc-11ea-8357-3d5ef56964cb.png">

**Comment by jennifer-shehane** [comment]
Another example of this bug found in https://github.com/cypress-io/cypress/issues/9435

The cy.log() runs twice.

```js
it('test', () => {
  cy.get('div').should(($element) => {
    cy.log($element)
  })
})
```

<img width="290" alt="Screen Shot 2020-12-03 at 3 23 53 PM" src="https://user-images.githubusercontent.com/1271364/100986429-93b08200-357b-11eb-858b-7903c62e7d54.png">

**Comment by sainthkh** [comment]
The command is run twice because the `should` callback function uses `Promise` internally. It returns `Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.` error. 

The workaround is to use [`Cypress.log()` function](https://docs.cypress.io/api/cypress-api/cypress-log.html) directly like below: 

```js
it('test', () => {
  cy.visit('fixtures/a.html')

  cy.get('#thisElIsFound').should((el) => {
    expect(el).to.exist
    Cypress.log({
      displayName: 'log',
      message: 'As we thought, it is there',
    })
  })
})
```
