### ISSUE TITLE
Can't access alias via 'this.value' syntax

### ISSUE THREAD

**Issue by denis-domanskii** [cypress-io/cypress#8349]
### Current behavior:

I am trying to count founded 'button' elements on a page and get the result via two syntax constructions: '@value' and 'this.value':

```js
describe('page', () => {
  it('two aliases', function() {
    cy.visit('https://example.cypress.io')
    cy.get('h2')
        .its('length')
        .as('num');
    cy.get('@num').then(num => cy.log(`num via '@num' is: ${num}`))
    cy.log(`num via 'this' is: ${this.num}`)
  })
})
```
An output is a little unclear for me:
![image](https://user-images.githubusercontent.com/61494460/90665224-6ce07100-e254-11ea-915f-4b192d3a53aa.png)

### Desired behavior:

I expect that I can access the value both ways:  via '@value' and via 'this.value'. Just like in documentation:
https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context
```js
beforeEach(() => {
  // alias the $btn.text() as 'text'
  cy.get('button').invoke('text').as('text')
})

it('has access to text', function () {
  this.text // is now available
})
```

### Test code to reproduce

https://github.com/denis-domanskii/cypress-test-tiny-8349

### Versions
OS: Mac 10.15.5
Browser: Chrome 84
Cypress: 4.1.0, 5.0.0

**Comment by jennifer-shehane** [comment]
`this.num` evaluates immediately, before the asynchronous Cypress commands have run. You'll have to ensure the `this.num` is called *after* the alias has evaluated.

```js
describe('page', () => {
  it('two aliases', function () {
    cy.visit('https://example.cypress.io')
    cy.get('h2')
      .its('length')
      .as('num');
    cy.get('@num').then(num => {
      cy.log(`num via '@num' is: ${num}`)
      cy.log(`num via 'this' is: ${this.num}`)
    })
  })
})
```

I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).

**Comment by denis-domanskii** [comment]
@jennifer-shehane thank you for an explanation, seems I was confused by the example from here:
https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context - maybe will be better to add 'get' there.
