### ISSUE TITLE
[Feature Request]Allow passing search filter from cli before open desktop-gui

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#8352]
### Current behavior:
Feature request, no current behavior

### Desired behavior:
Our folder structure is component based.
For example,
```
- cypress
  - login-page
    - tests
    - page-objects
    - util
    - ...
  - register-page
    - tests
    - page-objects
    - util
``` 
This cause a mess to view our specs in desktop gui because all the files are displayed regardless if they are test files or not

The proposal is to allow passing search filter at cli
`cypress open --search "-test.ts"` or `SEARCH="-test.ts" cypress open`
so by default it will populate filtered spec list on open and it is much cleaner.

code from `packages/desktop-gui/src/specs/specs-list.jsx`
```html
<input 
  id='filter' 
  className='filter' 
  placeholder='Search...' 
  value={specsStore.filter || '' } 
  ref={this.filterRef}
  onChange={this._updateFilter} 
  onKeyUp={this._executeFilterAction} />
```
Maybe adding more func to specsStore from `value={specsStore.filter || ''}` will do the trick

**Comment by jennifer-shehane** [comment]
You can filter the files shown within the Cypress desktop-gui by setting `testFiles` in your configuration to the glob pattern you want matching. It accepts a glob or array of globs. https://on.cypress.io/configuration#Folders-Files

```
cypress open --config '{"testFiles": "**/*test.ts"}'
```
