### ISSUE TITLE
Non Promise version of Cypress.Blob.binaryStringToBlob can't be used within a Promise in 5.0

### ISSUE THREAD

**Issue by saschwarz** [cypress-io/cypress#8353]
### Current behavior:

Converting tests from 4.x to 5.x my old code was:
```js
it('Successfully uploads an Operating Statement file', () => {
  cy.route('POST', '/properties/**/line-item-sources/').as(
    'postLineItemSource'
  )
  cy.get('@createdPropertyId').then((id) => {
    cy.visit(`/properties/${id}`)
  })
  cy.findAllByText('Import a Document').first().click()
  cy.fixture('simple_2017.xlsx', 'binary')
    .then(Cypress.Blob.binaryStringToBlob)
    .then((fileContent) => {
      cy.get('input[data-testid=pnl-input]').attachFile({
        fileContent,
        fileName: 'simple_2017.xlsx',
        mimeType:
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        encoding: 'utf8',
      })
    })
// ...
```

I converted to the non-Promise version of `Cypress.Blob.binaryStringToBlob` as follows:

```js
it('Successfully uploads an Operating Statement file', () => {
  cy.route('POST', '/properties/**/line-item-sources/').as(
    'postLineItemSource'
  )
  cy.get('@createdPropertyId').then((id) => {
    cy.visit(`/properties/${id}`)
  })
  cy.findAllByText('Import a Document').first().click()
  cy.fixture('simple_2017.xlsx', 'binary').then((binaryData) => {
    const fileContent = Cypress.Blob.binaryStringToBlob(binaryData)
    cy.get('input[data-testid=pnl-input]').attachFile({
      fileContent,
      fileName: 'simple_2017.xlsx',
      mimeType:
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      encoding: 'utf8',
    })
  })
// ...
```

But I'm still getting the error:
```
cypress_runner.js:199987 CypressError: `binaryStringToBlob()` no longer returns a `Promise`. Update the use of `binaryStringToBlob()` to expect a returned `Blob`.
```

### Desired behavior:

Allow `Cypress.Blob.*` to be used within in Promise when used as a standard function.

### Test code to reproduce

Please see above.

### Versions

5.0.0 Linux

**Comment by mustafawm** [comment]
I think you need to return 

`return cy.get('input[data-testid=pnl-input]').attachFile({`

**Comment by saschwarz** [comment]
@mustafawm Thank you for that suggestion, but I'm still getting the same error. I'm guessing `attachFile` treats the `fileContent` argument as a Promise; because apparently `fileContent.then()` is being called somewhere and raising that exception. I tried wrapping the call with a resolved Promise:

```
        const fileContent = Promise.resolve(
          Cypress.Blob.binaryStringToBlob(binaryData)
        )
``
But I still get the error. I'll look at the source of `attachFile` in the morning.

**Comment by jennifer-shehane** [comment]
Assuming you are using the `cypress-file-upload` plugin (which has this `attachFile` method), their plugin will need to be updated to account for the change in 5.0.0. It looks like they already have a PR open to fix this: https://github.com/abramenal/cypress-file-upload/issues/214

Closing as an external issue with `cypress-file-upload` - please comment if you are not using this plugin and include the code of the `attachFile` method so we can have a look at it again.

**Comment by jennifer-shehane** [comment]
This was fixed in cypress-file-upload's latest release: https://github.com/abramenal/cypress-file-upload/releases/tag/v4.1.0
