### ISSUE TITLE
Cannot upgrade to 5.0.0 version

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#8357]
### Current behavior:
Error during upgrade to 5.0.0 version.
![obraz](https://user-images.githubusercontent.com/34089686/90726690-65f04780-e2c2-11ea-89c5-868bc29271ab.png)

Log:
[2020-08-20T06_45_23_079Z-debug.log](https://github.com/cypress-io/cypress/files/5101167/2020-08-20T06_45_23_079Z-debug.log)

### Desired behavior:

Cypress should upgrade properly.

### Versions

upgrade from 4.12.1 to 5.0.0

**Comment by jennifer-shehane** [comment]
Installing Cypress requires Node.js 10+ version: https://on.cypress.io/migration-guide#Node-js-10-support. I can see from the logs you are using Node.js version 9.4.0. This is no longer supported as this Node.js version has reached its end of life.

Please carefully review our [migration guide](https://on.cypress.io/migration-guide#Migrating-to-Cypress-5-0) before/while updating to 5.0.0.
