### ISSUE TITLE
iframe wrap fail when iframe className is 'iframe'

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#8358]
iframe wrap fail when iframe className is 'iframe' , and not find element on iframe.
and if className is another，it's success。

```js
cy
    .get('iframe.iframe')
    .its('0.contentDocument.body')
    .should('not.be.empty')
    .then(cy.wrap);
```
html:
```html
<iframe class="iframe" src="">
</iframe>
```

### Versions
cypress: 4.7.0
system: mac
browser：chrome

**Comment by jennifer-shehane** [comment]
I'm not able to recreate this issue in 4.7.0 given the information provided.

Please make sure to include all code in `cypress.json`, support files, plugins files, etc required to recreate the issue. There may also be something specific to your application code that's required to recreate it. Providing a repo is ideal.

The code I ran is below and is passing.

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('iframe.iframe')
    .its('0.contentDocument.body')
    .should('not.be.empty')
    .then(cy.wrap)
})
```

```html
<html>
<body>
  <iframe class="iframe" src="iframe.html"></iframe>
</body>
</html>
```

**Comment by mingyixu** [comment]
@jennifer-shehane :  sorry, I also succeed in wrapping, but I can't click buttons and other operations in iframe.

**Comment by jennifer-shehane** [comment]
Added the `cy.wait()` in between the `.then()` and the `.find()` is causing the issue. Removing that line fixes the error for me. 

If you need to wait some period of time for the iframe to load, it'd be better to do that before querying the iframe. 

```js
it('test', () => {
  cy.visit('index.html')
  cy.wait(5000)
  cy.get('iframe.iframe')
    .its('0.contentDocument.body')
    .should('not.be.empty')
    .then(cy.wrap).find('button').click();
})
```
