### ISSUE TITLE
reading JSON[x] Undefined Cypress v5.0, OK en 4.11

### ISSUE THREAD

**Issue by Cedric-Brunel** [cypress-io/cypress#8362]
Hello 

### Current behavior:
Since version 5.0 

![image](https://user-images.githubusercontent.com/62300093/90771852-29d5da80-e2f4-11ea-8d7e-c81f6f30fee7.png)

### Desired behavior:

On version 4.11 it's worked!

![image](https://user-images.githubusercontent.com/62300093/90771837-24789000-e2f4-11ea-8c8c-de1762a93b10.png)

```typescript

import * as json from "../test-nocommit/test.json"

function textElement(element: string): Cypress.Chainable {
  return cy.get(element).should("be.visible").invoke("text");
}

function controlMessage(elementMessage: string, labelMessage?: string): Cypress.Chainable {
  return textElement(elementMessage).and("contain", json[labelMessage]);
}

describe("Test json", () => {
  it("Test json", () => {
    cy.visit("www.cypress.io");
    controlMessage("[data-cy=tag-line] > div", "title")
  });
});

```

test.json 

```json
{
    "title": "The web has evolved."
}
```

For me json[] not worked on 5.0

### Versions

5.0

Thanks for watching this

**Comment by Cedric-Brunel** [comment]
Sorry it's my bad. Isn't invoke("text"). but reading of json

**Comment by Cedric-Brunel** [comment]
Aucune idée ?

**Comment by jennifer-shehane** [comment]
This is working for me. Are you sure you're referencing the json file correctly? Is there anything else in your project that is relevant to reproducing? cypress.json, support, plugin files?

`cypress/fixtures/test_data.json`

```js
{
  "title": "The web has evolved"
}
```

`cypress/integration/spec.ts`

```js
import * as json from "../fixtures/test_data.json"

function textElement(element: string): Cypress.Chainable {
  return cy.get(element).should("be.visible").invoke("text");
}

function controlMessage(elementMessage: string, labelMessage?: string): Cypress.Chainable {
  return textElement(elementMessage).and("contain", json[labelMessage]);
}

describe("Test json", () => {
  it("Test json", () => {
    cy.visit("www.cypress.io");
    controlMessage("[data-cy=tag-line] > div", "title")
  });
});
```

<img width="550" alt="Screen Shot 2020-08-27 at 3 47 30 PM" src="https://user-images.githubusercontent.com/1271364/91422026-a597d000-e87c-11ea-88c1-03ddad497f7f.png">

**Comment by Cedric-Brunel** [comment]
I'm beginner in Cypress world
It doesn't work for me, the problem is "json[labelMessage]" 

@jennifer-shehane, if I code json.title it works but i want to use un parameter.
Do you have any solution ? I don't understand.


index.js in plugins folder is empty
I've only commands.ts 

```typescript
import 'cypress-file-upload';

declare global {
  namespace Cypress {
    interface Chainable {
      login(user?: string, password?: string): Chainable<Element>;
      dataCy(value: string): Chainable<Element>;
    }
  }
}

cypress.json
{
  "reporter": "mochawesome",
  "reporterOptions": {
    "reportDir": "cypress/results/json",
    "overwrite": false,
    "html": false,
    "json": true
  },
  "video": false,
  "restartBrowserBetweenSpecFiles": true,
  "chromeWebSecurity": false,
  "defaultCommandTimeout": 10000,
  "pageTimeLoad": 10000,
  "trashAssetsBeforeRuns": false
}

**Comment by jennifer-shehane** [comment]
You can use our [`cy.fixture()`](https://on.cypress.io/fixture) command to read in JSON or [`cy.readFile()`](https://on.cypress.io/readfile). 

Sorry, I'm just not able to reproduce - the json[labelMessage] works fine for me in 5.0.

**Comment by Cedric-Brunel** [comment]
Ok merci quand même

**Comment by Cedric-Brunel** [comment]
It's good I use cy.readFile and it's worked

cy.readFile(frMessage)
          .its(labelMessage)
          .then((message) => {
            return textElement(elementMessage).should("contain", message.substring(0, 30));
          });
        break;
