### ISSUE TITLE
Retries hangs on failed assertions

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#8363]
### Current behavior:
Sometimes Cypress hangs to eternity on failed assertions while Retries functionality is active.
I described it once in this ticket:
https://github.com/Bkucera/cypress-plugin-retries/issues/64#issuecomment-675498787

Now I'm experiencing similar issue in 5.0.0 version.
It's probably a problem with `.should('contain', xxx)` assertion.

![obraz](https://user-images.githubusercontent.com/34089686/90758337-2552f700-e2df-11ea-96ca-7f417efb40d9.png)

### Versions
5.0.0

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? We have quite a few tests we run through, so there’s likely something specific about the way the tests are written or run that will trigger this. 

This will be hard to track down without that, especially if it only fails sometimes. Thanks!

**Comment by crazyricardo** [comment]
Same happened for us. Usually our test suite finished in about 3 or 4 minutes max (success/failure). Nothing changed, we just enabled retries `runMode: 3` and then our last CI cypress run lasted ran for 01:32:22 according to the Cypress Dashboard, but actually the Github Action was still running after 4h 34m.

It hits the first failure and then just hangs forever, it literally does nothing else:

(Attempt 1 of 4) test name omitted here
(Attempt 1 of 4) test name omitted here
(Attempt 2 of 4) test name omitted here

this happened on all of our CI runners for parallel tests (each one just hit the first error and then the same thing like above happens).

**Comment by lukeapage** [comment]
Same is happening for us, both with the plugin and with 5.0.0.

I did an investigation to track down what was hanging, you can see the issue on cypress plugin retries for that, assuming it’s the same problem, but I wasn’t able to work out the exact problem only what was happening.

Some of the failed tests hang, whilst others are able to retry 3 times and then fail so I think it is something specific to certain tests. I’ve already spent way too long this week debugging cypress but if I find a reproduction case I will post it.

**Comment by jennifer-shehane** [comment]
I'm unable to recreate this with a `.should('contains', 'foo')` assertion alone. 

We will really need a reproducible example to be able to track this down - there could be a lot of things contributing, such as other defined hooks or thing in the project support/plugins. 

**My test code**

`index.html`

```html
<html>
  <body>
    <div>bar</div>
  </body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('div').should('contain', 'foo')
})
```

`cypress.json`

```json
{
  "retries": {
    "runMode": 3,
    "openMode": 3
  }
}
```

Runs 4 times and correctly ends the test.

<img width="469" alt="Screen Shot 2020-08-21 at 11 23 09 AM" src="https://user-images.githubusercontent.com/1271364/90853735-fbfa9f80-e3a0-11ea-8f6f-91689bc1674a.png">

**Comment by lukeapage** [comment]
1. It only happens in run mode and I have a test case I can reproduce fairly consistently locally and on the build server.
2. Its failing on the first attempt to retry (test runs once, fails and then stalls). But once I start removing code from the test it starts failing on 2nd retry.
3. my test that is failing does not have `should('contain', 'foo')` assertion in it.
4. no additional hooks
5. I'm trying to make a test case but its very fragile - remove one assertion or another and it starts working or fails on 2nd retry - its like the length of the test makes a difference on whether retry will work

**Comment by zbigniewkalinowski** [comment]
Today my test hanged on `click` also.

![obraz](https://user-images.githubusercontent.com/34089686/90871096-cfdc2000-e39a-11ea-8e46-6e2c4ee7b0cc.png)

**Comment by jennifer-shehane** [comment]
It is, but it's going to take a lot longer to determine the cause with such a large example.

**Comment by Roger-Fang-CS** [comment]
> Same happened for us. Usually our test suite finished in about 3 or 4 minutes max (success/failure). Nothing changed, we just enabled retries `runMode: 3` and then our last CI cypress run lasted ran for 01:32:22 according to the Cypress Dashboard, but actually the Github Action was still running after 4h 34m.
> 
> It hits the first failure and then just hangs forever, it literally does nothing else:
> 
> (Attempt 1 of 4) test name omitted here
> (Attempt 1 of 4) test name omitted here
> (Attempt 2 of 4) test name omitted here
> 
> ^ this is the very last line, there is nothing else. edit: The duplicate "Attempt 1 of 4" is also for the same test, which is weird.
> 
> this happened on all of our CI runners for parallel tests (each one just hit the first error and then the same thing like above happens).
> 
> edit: Just removed the retries from our cypress config, and the test execution finished again in 4 minutes.

-----------------------------------------------------------------------------


I meet the similar problem. after upgrade to 5.0.0, deprecate cypress-plugin-retries and use built-in retry function, my test cases fail all the time then hang for serveral hours when run github action. 
 
print like below
     (Attempt 1 of 3) tset1 name
      (Attempt 2 of 3) test1 name
      1) test1 name
      ........
      (Attempt 1 of 3) tsetn name
      (Attempt 2 of 3) testn name
      n) testn name

but my code runs well on local machine. the only change is upgrade 
I close the function about snapshot by adding "numTestKeptInMemory: 0" to cypress.json, so the reason  can't be out of memory.

**Comment by jennifer-shehane** [comment]
@lukeapage I narrowed down the reproducible example to this single spec file. I think the issue is with your overwriting `cy.get()`. We really don't recommend doing this - you should be using `overwrite` to overwrite commands. 

https://github.com/cypress-io/cypress-test-tiny/pull/62/files#diff-05da80f0f815af9c2b8279ce29b86790

**Comment by lukeapage** [comment]
There’s only a single spec file and spec in that Pr isn’t there?

How did you narrow it down to overwriting get ? I can try refactoring that.

Unfortunately we got so many issues with overwrite that we don’t use it.

**Comment by lukeapage** [comment]
Sorry I see what you did now. I will take a look later.

**Comment by lukeapage** [comment]
@jennifer-shehane I pushed some commits that simplify it further. I've removed the overwrite of get and also I replaced the "waitForTimers" with a simpler pause - I added the commits in stages because a 1s pause is more likely that it might suddenly stop reproducing.. but for me I still reproduce with the simplified example.

**Comment by jennifer-shehane** [comment]
@lukeapage K, thanks, thats helpful.

**Comment by Bkucera** [comment]
I think  I found the source of the issue, hoping to get a patch out in the next release.

**Comment by Bkucera** [comment]
what reproduces the bug is having a test that fails and retries with an existent DOM node as the subject of an assertion e.g.:

```js
cy.get('.element-exists').should('not.exist')
```

our logic only pretty formatted err.actual on test failure, not retry, so the browser hangs trying to serialize an entire DOM node.
