### ISSUE TITLE
Cypress 4.12/5.0 runs 3 times slower than 4.9.0 locally

### ISSUE THREAD

**Issue by kpioro** [cypress-io/cypress#8368]
Since 4.12 and also in 5.0 I have a problem with Cypress running locally.
The main issue is that Cypress became terribly SLOW.

I runned same test on 4.9.0, it took 230 seconds.
To compare, same test on 5.0 took 700+ seconds.

Also some of test became flaky.

I only updated package.json with newset version of Cypress.
Do you have any ideas why Cypress, since 4.12 runs like tortoise?

**Comment by jennifer-shehane** [comment]
You can search possibly related performance issues here: https://github.com/cypress-io/cypress/labels/type%3A%20performance%20%F0%9F%8F%83%E2%80%8D%E2%99%80%EF%B8%8F

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
