### ISSUE TITLE
cypress Error: Cannot find module 'npm-run-path' opening cypress after updating version in package.jon

### ISSUE THREAD

**Issue by gorru** [cypress-io/cypress#8370]
### Current behavior:
Errors opening cypress
```
npm-run-path module missing in some cypress dependencies
```
I changed at least: `launcher/execa`, `shell-path/execa` copying manually `npm-run-path` into the dependency `node_module folder` that throw the error

for example (this is the last I fixed) 
[Content]
```
Uncaught Exception:
Error: Cannot find module 'npm-run-path'
Require stack:
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\shell-path\node_modules\execa\index.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\shell-path\node_modules\shell-env\index.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\shell-path\index.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\fix-path\index.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\lib\util\find_system_node.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\lib\config.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\lib\util\args.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\lib\cypress.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\index.js
- C:\Users\TEMP\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\index.js
```
### Desired behavior:
Cypres opened without errors

### Test code to reproduce
Update cypress `package.json` version manually to 
"cypress": "^5.0.0", from previous release

### Versions
Cypress 5.0.0
Windows 10
Chrome

**Comment by jennifer-shehane** [comment]
Can you include a project that reproduces this error? It's likely dependent on your preprocessors, plugins/support, or other deps when trying to run the tests. We'll need that to investigate this error. Thanks!

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
