### ISSUE TITLE
Add an easy way (on the final report with all the specs) to see the retries tests. 

### ISSUE THREAD

**Issue by estefafdez** [cypress-io/cypress#8372]
### Current behavior:
On the new release 5.0 the retries functionality was added and it works really great. I would love an easy way to see how many tests needed a retry (not the number of retries I have set but the current test failures that needed a retry) on the final report. The only way I have it now is to look on the logs for the screenshots (or have a look on the report folder) and see how many screenshots were done to know exactly the number of tests that failed on the first attempt. 

### Desired behavior:
It will be great to add an extra column or just a note at the end with the tests failed that needed retries. 

### Test code to reproduce
Any project with the new version applied and the retries functionality active on the run mode. 

### Versions
5.0

**Comment by jennifer-shehane** [comment]
Just as a side note, the Dashboard now displays the screenshots and errors from each attempt of a test that retried. The test results are also filterable by whether they retried.

**Filter by whether test retried**

<img width="1470" alt="test-retries-filter copy" src="https://user-images.githubusercontent.com/1271364/91129249-afc89b80-e6cf-11ea-8618-6876e4b40d16.png">

**See screenshot and error for each attempt when clicking on test**

<img width="1470" alt="test-results-attempts" src="https://user-images.githubusercontent.com/1271364/91129281-c1aa3e80-e6cf-11ea-91d9-e5253b278d7a.png">

**Comment by estefafdez** [comment]
Having the attempts on the Dashboard is great @jennifer-shehane but it will be great to at least have the number on the final report for the people who don't have the possibility to use the Dashboard :)

**Comment by ismail-codinglab** [comment]
![91372039-e3600e80-e812-11ea-8997-119cef368b1f](https://user-images.githubusercontent.com/48755937/91441072-df160e80-e86f-11ea-91da-225f557adae7.png)

Yeah in the report to console option I would love to see retries per file

**Comment by ismail-codinglab** [comment]
@jennifer-shehane 

Hope you didn't oversee our comment that we are **not** talking about the cypress dashboard

**Comment by cmcnicholas** [comment]
An extension to this would be reporting, it would be really useful to see the flakiest tests across all test runs in analysis e.g. the tests that retry the most consistently

**Comment by jennifer-shehane** [comment]
@ismail-codinglab Yes, this issue is open for the feature request to show retries in the stdout report. Just wanted to note the Dashboard feature.

**Comment by jennifer-shehane** [comment]
We are implementing better display of retries with changes to flake detection that are going in. Some of it can be seen in experimentalRetries, but some redesigns are also planned. Closing since this is already prioritized.
