### ISSUE TITLE
Start Cypress server through the CLI in the monorepo

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#838]
## dev feature

When working inside this repo we can start the server (the Cypress app itself) without building the binary. This is great of course, no need to build Electron binary, which saves a LOT of time.

```
npm start
```
which calls `node scripts/start.js`
But this is different from the way it runs in user projects, where the execution goes through the CLI first (`cli/bin/cypress` script)

Thus small differences in parsing CLI arguments are hard to catch. For example, server had `--group` and `--group-id` support for a while, but CLI did not allow these options until #836 

## proposal

CLI should detect when it is inside the monorepo and there is no Cypress app in the `dist` subfolder. Then instead of spawning something like `dist/Cypress/Resources/Cypress.app` it should spawn `node scripts/start.js ...` from the CLI code, parsing the command line arguments the same way as a production app would do.

**Comment by brian-mann** [comment]
Released in [`1.4.1`](https://docs.cypress.io/guides/references/changelog.html#1-4-1).
