### ISSUE TITLE
Cypress doesn't stub the test's Date, only the application under test's Date

### ISSUE THREAD

**Issue by lucasfcosta** [cypress-io/cypress#8386]
First of all, thanks for your amazing work ✨ 

I absolutely love the product and I'm very glad you've been using Chai and Sinon 💖 

### Current behavior:

Currently, when I use `cy.clock` to install fake timers, I won't get the "fake `Date`" within my tests. Only the application under test will have access to the fake date.

For example:

1. Assume you have an appplication which uses `Date` to update a header with the current time:
    ```js
    document.getElementById("header").innerHTML = (new Date().toISOString());
    ```
2. Install fake timers (a global hook is a good example because it implies you don't have access to the time used in the fake timer)
    ```js
    beforeEach(() => cy.clock(new Date(2020, 8, 24, 11, 0, 0)))
    ```
3. In your tests, use the `Date` constructor to obtain the expected value for the header.
    ```js
    it("has the correct ISO string", () => {
      // Fails because `new Date()` within the test is the current time, not the fake time
      cy.get("#header").contains(new Date().toISOString());
    })
    ```

### Desired behavior:

I can understand why `Cypress` would want to avoid mocking timers within the test's code, but I _think_ that this behaviour should either be explicitly documented or it should remain consistent.

I'd propose picking one of the two:
* Documenting that in this circumstance timers would not be mocked within the test's code
* Installing fake timers everywhere

Probably I'd more inclined towards the first since it would protect users from having to save original timer methods to use them throughout tests. Furthermore, it's easy to work-around this problem, so the behaviour doesn't necessarily need to be changed.

```js
cy.clock.then((c) => {
  cy.get("#header").contains(new Date(c.details().now).toISOString());
});
```

Documenting it, however, would be great because then you can avoid users misunderstanding the scope of this API.

Please let me know if I've made any incorrect assumptions here or if I have misunderstood these APIs/am misusing them.

### Test code to reproduce

Besides the test code I've used above, you can also see a reproducible at https://github.com/lucasfcosta/cypress-date-within-test (here, more specifically https://github.com/lucasfcosta/cypress-date-within-test/blob/master/cypress/integration/time.spec.js).

### Versions

* Cypress: 5.0.0
* Happens in all browsers

**Comment by BlueWinds** [comment]
Going to close this after two years of inactivity + 6 major versions of Cypress. Please feel free to open another issue if this is still a problem and we'll try and do better about looking into things!
