### ISSUE TITLE
cy.get() is not working with URL containing special characters

### ISSUE THREAD

**Issue by hbuddaraju-CLGX** [cypress-io/cypress#8389]
**Current behavior:**

Running something like `cy.get('https://www.google.com/')` yields an error.

```
Error: Syntax error, unrecognized expression: https://www.google.com/ 
```

**Desired behavior:**

URLs with valid characters such as / or . should work.

**Test code to reproduce**

Write a spec that contains URL containing special characters, for example: `cy.get('https://www.google.com/')`.

 **Versions:**
Cypress 5.0.0
Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Windows 10 64bit

**Comment by jennifer-shehane** [comment]
`cy.get()` accepts any valid sizzle selector, just like jQuery. This is not a valid selector. Please see the docs for appropriate usage of `cy.get()`: https://on.cypress.io/get

<img width="829" alt="Screen Shot 2020-08-24 at 4 51 33 PM" src="https://user-images.githubusercontent.com/1271364/91033892-1f844b00-e62a-11ea-9d54-319f180868fc.png">


If you're looking to visit a url, see [`cy.visit()`](https://on.cypress.io/visit) or get some element by it's text see [`.contains()`](https://on.cypress.io/contains).

**Comment by hbuddaraju-CLGX** [comment]
Thank you for your quick response.
