### ISSUE TITLE
Upgrade cy.visit-> stop reloading the tests(when web security is off)

### ISSUE THREAD

**Issue by xStoneriderx** [cypress-io/cypress#839]
When cypress changes the superdomain the local scope of data you've created gets nuked.

**proposal**
To upgrade cy.visit to be smart when web security is off and stop reloading the tests.

**Comment by jennifer-shehane** [comment]
Brief example use case from gitter chat:
```js
cy.visit(localhost:3000)
// save some ID and NAME
cy.visit(localhost:3001/ID)
// and after this visit ID and NAME is undefined
```

**Comment by leonid-panich** [comment]
+1

**Comment by kevinpainchaud** [comment]
+1
