### ISSUE TITLE
Improve error message when this binary file does not have executable permissions

### ISSUE THREAD

**Issue by kpittman-securus** [cypress-io/cypress#8397]
### Current behavior:

After `npm install cypress@5.0.0` and `npx cypress open` I get:

```
Cypress cannot run because this binary file does not have executable permissions here:

/Users/me/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/MacOS/Cypress

Reasons this may happen:

- node was installed as 'root' or with 'sudo'
- the cypress npm package as 'root' or with 'sudo'

Please check that you have the appropriate user permissions.

----------

Platform: darwin (19.6.0)
Cypress Version: 5.0.0
```

### Desired behavior:

Cypress should open - works fine with version 4.12

### Test code to reproduce

Cypress installed via NPM

### Versions

Cypress: 5.0.0
OS: MacOS Catalina 10.15.16
Node: Tested on 12.18.2 and 14.8.0 using NVM

The same thing happens if I use `./node_modules/cypress/bin/cypress open` instead of `npx cypress`. Both commands work if I revert back to Cypress 4.12.1

**Comment by jennifer-shehane** [comment]
I can't see why anything involving the executable would have changed in 5.0.0. 

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

But ultimately this seems to throw if the executable is not executable based off of running it through this npm module: https://github.com/kevva/executable#readme 

So, I would suggest double checking the permissions on your node and cypress npm package.

**Comment by kpittman-securus** [comment]
@jennifer-shehane I resolved it by manually doing `rm -rf /Users/me/Library/Caches/Cypress/` and it fixed itself after reinstalling. No idea why!

Possible enhancement would be to have an error/warning message that instructs user how to clear cache and reinstall. I didn't see a way to manually clear out the cache in the docs, just a way to set alternate cache dir.

**Comment by jennifer-shehane** [comment]
You can clear cache by running [`cypress cache clear`](https://on.cypress.io/command-line#cypress-cache-clear)

**Comment by kpittman-securus** [comment]
Yes - but only if you were to know you needed to :D
