### ISSUE TITLE
Experimental fetch polyfill has different prototype than webpage

### ISSUE THREAD

**Issue by bhgsbatista** [cypress-io/cypress#8398]
### Current behavior:

Results from fetch calls when using `experimentalFetchPolyfill` have a different prototype than `Object.prototype` in the browser context. This breaks the `isPlainObject` check in Mobx: https://github.com/mobxjs/mobx/blob/6ec6499fb8b55a17fe65f42b14d1188fd7fa1ba1/src/utils/utils.ts#L85

![image](https://user-images.githubusercontent.com/47303296/91098257-28c3e680-e62f-11ea-8beb-8256a23c54da.png)

### Desired behavior:

When running in the browser without Cypress, we can see that the fetch response behaves correctly:

```js
fetch('/test')
  .then(response => response.json())
  .then(data => Object.getPrototypeOf(data) === Object.prototype); // this evaluates to true in the browser, false in cypress
```

![image](https://user-images.githubusercontent.com/47303296/91098370-56a92b00-e62f-11ea-85ef-d423f4a01e72.png)

### Test code to reproduce

https://github.com/bhgsbatista/cypress_fetch_prototype

### Versions

Cypress: 5.0.0
Browser: Chrome 84
OS: Windows 10.0.19041 Build 19041

**Comment by jennifer-shehane** [comment]
I can recreate the issue from the repo provided https://github.com/bhgsbatista/cypress_fetch_prototype

### With experimentalFetchPolyfill: true

<img width="1017" alt="Screen Shot 2020-08-25 at 1 57 46 PM" src="https://user-images.githubusercontent.com/1271364/91145105-f96ab380-e6da-11ea-8390-c45d28d1b857.png">

### With experimentalFetchPolyfill: false

<img width="1012" alt="Screen Shot 2020-08-25 at 1 58 25 PM" src="https://user-images.githubusercontent.com/1271364/91145169-11423780-e6db-11ea-844a-7a1595c493cb.png">

How is this behavior actually exhibiting in your application tests? I'd like to understand how this was affecting your application and tests in general.

**Comment by bhgsbatista** [comment]
> How is this behavior actually exhibiting in your application tests? I'd like to understand how this was affecting your application and tests in general.

We do fetch calls and pass the resulting JSON JS objects to mobx which is a library that wraps the objects with proxies and monitors inserts / changes to its fields in a nested way. This library assumes / checks to make sure the objects that are made observable are simple JS objects, and it does this by comparing the prototype to `Object.prototype`: https://github.com/mobxjs/mobx/blob/mobx6/src/utils/utils.ts#L82

The result of this bug is that my app throws errors when my objects are passed to mobx to become observable.

**Comment by bahmutov** [comment]
Cypress spec code and application under test are placed into two iframes

<img width="989" alt="Screen Shot 2020-09-15 at 4 17 46 PM" src="https://user-images.githubusercontent.com/2212006/93260800-de3a1380-f76f-11ea-807c-301acb2e9fb4.png">

Every iframe has its own `window` object and separate global objects, like `window.Object`. 

<img width="363" alt="Screen Shot 2020-09-15 at 4 20 04 PM" src="https://user-images.githubusercontent.com/2212006/93260865-f6aa2e00-f76f-11ea-8a73-bed180573314.png">

What I think happens here is that the mock object from spec is constructed using `spec window Object.prototype` and Mobx is comparing it against `aut window Object.prototype`.

Could you as a workaround try [cy.route2](https://on.cypress.io/route2) for now?

**Comment by bahmutov** [comment]
Ok, here are the workarounds that I pushed to https://github.com/bahmutov/cypress_fetch_prototype

- use [cy.route](https://on.cypress.route)
- use [cy.route2](https://on.cypress.route2)
- stub `window.fetch` directly, but use `window.eval` to return an object constructed from the window's prototype

```js
/// <reference types="Cypress" />

// fails because the prototypes from two iframes are not the same
it.skip('Verify the prototype of fetch result is the same as Object.prototype',
  { experimentalFetchPolyfill: true }, function () {
  cy.visit('/')
  cy.get('#result').should('have.text', 'true');
})

// this works - we can observe / spy on the network call
// yet the prototype is correct
it('try cy.route2',
  { "experimentalNetworkStubbing": true }, function() {
  cy.route2('/test')
  cy.visit('/')
  cy.get('#result').should('have.text', 'true');
})

// this works too
it('try cy.route', function () {
  cy.server()
  cy.route('/test')
  cy.visit('/')
  cy.get('#result').should('have.text', 'true');
})

it('stub window.fetch', function() {
  cy.visit('/', {
    onBeforeLoad(w) {
      cy.stub(w, 'fetch').resolves({
        json() {
          // make sure the object is constructed
          // using the window under test's objects
          return w.eval('({})')
        }
      })
    }
  })
  cy.get('#result').should('have.text', 'true');
})

it('stub window.fetch with stringified object', function () {
  const myData = {
    foo: 'bar',
    baz: 42
  }
  cy.visit('/', {
    onBeforeLoad(w) {
      cy.stub(w, 'fetch').resolves({
        json() {
          // make sure the object is constructed
          // using the window under test's objects
          return w.eval('(' + JSON.stringify(myData) + ')')
        }
      })
    }
  })
  cy.get('#result').should('have.text', 'true');
})
```

Since the experimental `fetch` polyfill is a temporary measure while we are working on the `cy.route2` API, I don't think we will do any more work on it.

**Comment by bhgsbatista** [comment]
Thank you for going through the trouble to set up a demo for me. I fully plan on using `route2` as it seems like the best way to future proof my tests.

**Comment by jennifer-shehane** [comment]
`experimentalFetchPolyfill` has been deprecated in Cypress 6.0.0. We will not be addressing any new work on this feature. We encourage you to use [`cy.intercept()`](https://on.cypress.io/intercept) to intercept requests using the Fetch API instead.
