### ISSUE TITLE
cy.route() is wrongly matching urls other than url defined (throwing status on other url)

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#84]
If I define `.route()` and pass in a `status` BEFORE another `.route()` defined in short form (which should always defaults to `status: 200`), my shorthand route actually ends up being the status of the previously defined route (which is incorrect).

**Example Code**
```coffee
  it "foos [2a4]", ->
    cy
      .server()
      .route({
          method: "GET"
          url: /answers/
          status: 503
          response: {}
        })
      .route(/forms/, "fixture:form_requires_asset").as("getForm")
      .wait("@getForm").then ->
         expect(true).to.be.true
```

**Command Log**
<img width="518" alt="screen shot 2015-11-23 at 2 14 06 pm" src="https://cloud.githubusercontent.com/assets/1271364/11346859/c5f1f6a0-91ec-11e5-9db2-98cd8f6ca63a.png">

**Comment by brian-mann** [comment]
Fixed in [`0.12.6`](https://github.com/cypress-io/cypress/wiki/Changelog#0126-11292015).
