### ISSUE TITLE
Internal test, percy snapshot doesn't have css loaded

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#8402]
[https://github.com/cypress-io/cypress/pull/8469](https://github.com/cypress-io/cypress/pull/8469|smart-link) 

### Current behavior:
Sometimes the CSS doesn't load by the time the screenshot is taken, so we get snapshots like this to compare against in our internal runner tests.

[https://percy.io/cypress-io/cypress/builds/6625916](https://percy.io/cypress-io/cypress/builds/6625916)

![width=200,height=183](https://user-images.githubusercontent.com/1271364/91145808-089e3100-e6dc-11ea-8bdd-70161bc1e72a.png)

**Comment by bennymeade** [comment]
@jennifer-shehane I'm seeing this issue too. This ticket status says pending release since October 2020, but the linked ticket says merged. Is this fix part of the master release?

![image](https://user-images.githubusercontent.com/1033474/118822416-6e5cc980-b8b8-11eb-85eb-931f2d2418b6.png)

**Comment by Bkucera** [comment]
@bennymeade this isssue was internal only, no changes are user facing

**Comment by bennymeade** [comment]
@Bkucera do you have any suggestions how I can overcome this issue? I did add a few seconds wait before every screenshot (as a temporary check) was taken to allow the CSS extra time to load, but that didn't help. I have 163 snapshots and every one of them show with no CSS, when running on a Sanity.io website. Running on other CMS websites and the snapshots are working fine.
CI is GitHub Actions using cypress-io/github-action@v2.
