### ISSUE TITLE
My tests are working fine in chrome browser with Cypress open command but thorwing error in cypress run

### ISSUE THREAD

**Issue by wasiqkhan786** [cypress-io/cypress#8403]
My tests are working fine in chrome browser with Cypress open command but throwing error in Cypress run.it even dont visit the application in run and also recorded video doesnt contain all the information.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, screenshots of the errors you are seeing, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
