### ISSUE TITLE
expose current retry attempt with test / hook to programatically handle retries

### ISSUE THREAD

**Issue by mattrlong** [cypress-io/cypress#8404]
### Current behavior:

Prior to v5.0.0 and using `cypress-retries-plugin` the retry attempt could be programmatically obtained through `Cypress.currentTest.currentRetry()`

Have tried using Mocha's `this.test._currentRetry` but this is only usable within the tests (.it) and not the hooks where much of our test setup resides. 

Interestingly keeping the plugin installed as a dependency seems to be working, although not sure what other consequences this might cause. 

### Desired behavior:

The same feature being made available natively through Cypress. Would be great to be made available on the Cypress global as before. 

### Test code to reproduce

Previous usage documented [here](https://github.com/Bkucera/cypress-plugin-retries/issues/32).

### Versions

Cypress v5.0.0

**Comment by Bkucera** [comment]
It's undocumented, but you may use `cy.state('test').currentRetry()` to get the current retry number.

I agree we should add a better api for accessing this and document it.

**Comment by mattrlong** [comment]
Thanks @Bkucera, `cy.state('test').currentRetry()` looks to fulfil our requirements as this can also be used in support files.

**Comment by emilyrohrbough** [comment]
This was exposed as [`Cypress.currentRetry()`](https://docs.cypress.io/api/cypress-api/currentretry) in 12.3.0.
