### ISSUE TITLE
Types not supported for retries passed through as test options

### ISSUE THREAD

**Issue by ismail-codinglab** [cypress-io/cypress#8405]
### Current behavior:
![image](https://user-images.githubusercontent.com/48755937/91199702-85da9d80-e6fe-11ea-93d2-cd9f8cdd818f.png)

### Desired behavior:
Autocomplete & no errors

### Test code to reproduce
1. install cypress
1. use typescript
1. add retries to describe

### Versions
v5.0.0
Vscode

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-292) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Yah, this was an oversight on release. I've opened a PR here: https://github.com/cypress-io/cypress/pull/8408
