### ISSUE TITLE
Cypress cannot select Vuetify checkbox without { force: true }

### ISSUE THREAD

**Issue by Mikilll94** [cypress-io/cypress#8416]
### Current behavior:

I am using Vue + Vuetify

I have noticed that Cypress cannot check Vuetify `v-checkbox` without `{ force: true }`

![image](https://user-images.githubusercontent.com/17653648/91319333-8f2a3f80-e7bc-11ea-83fa-4a9237d76c1f.png)

I receive the error that the checkbox is covered by another element but as you can see on the screenshot, the checkbox is not covered.

### Desired behavior:

Cypress should be able to check the Vuetify checkbox without `{ force: true }` 

### Test code to reproduce
[cypress-vuetify-test.zip](https://github.com/cypress-io/cypress/files/5130607/cypress-vuetify-test.zip)

In order to launch the app you need to run these commands:
```
npm install
npm run serve
```

In order to launch cypress you need to run:
```
npm run cypress:open
```

### Versions

Cypress: 5.0.0
Operating system: Windows 10
Browser: Chrome 84.0.4147.135

**Comment by jennifer-shehane** [comment]
If you set a breakpoint on the click handler, you can see that vuetify registers the click handler on the div above the input. This input *is* covered by the div and you can't physically click on the input itself. The click when you manually click is being registered on the div.v-input__slot

<img width="551" alt="Screen Shot 2020-08-27 at 2 01 10 PM" src="https://user-images.githubusercontent.com/1271364/91411193-ff44ce00-e86d-11ea-89e4-4b1f5fb78c0b.png">

The code below will work:

```js
it('closes the v-select', () => {
  cy.visit('/')
  cy.get('.v-input__slot')
    .click()
})
```

There has to be some understanding of which element to actually click on currently, but we do hope that Native Events will fix this confusion in the future. #311
