### ISSUE TITLE
Video and screenshot recording consumes way too much CPU, causing Cypress to freeze.

### ISSUE THREAD

**Issue by miladmikeal** [cypress-io/cypress#8421]
I ran into a problem recently where Cypress began freezing towards the end of my tests. The problem was even worse when I upgraded to Cypress@5.0. Also, others seemed to run into the same exact problem on the gitter chat.

![Screen Shot 2020-08-26 at 3 17 05 PM](https://user-images.githubusercontent.com/26511068/91362459-62bbf680-e7af-11ea-9a00-437f7bf6fb6d.png)

Obviously that is not enough information on its own, so with the help of my team, we did a little digging and discovered that the process responsible for video and screenshot upload would shoot up to over 500% of CPU usage. There is absolutely no reason for it to be consuming that much CPU. That feature specifically caused cypress to freeze. 

When I turned off video and screenshot recording, my tests passed with flying colors, Cypress didn't freeze, and not a single process shot up to 500% CPU usage. 

Keep in mind, I have over 20 specs in my tests. This is a fairly large application I'm working with. So for small apps, you probably won't have Cypress freezing on you. With that said, process to record videos and screenshots should still not be consuming that much CPU, and I believe it's something you guys should look into.

<img width="979" alt="Screen Shot 2020-08-26 at 1 31 37 PM" src="https://user-images.githubusercontent.com/26511068/91362350-28eaf000-e7af-11ea-984b-edf858eb30a4.png">

**Comment by ismail-codinglab** [comment]
My pipelines start to freeze and have a 60min timeout
Some tests cap the video capture to 10s

**Comment by jennifer-shehane** [comment]
@miladmikeal Are you running your specs in parallel on your machine? Or is it running each spec file sequentially? 

You can log the memory and CPU usage of Cypress by following these instructions also: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage

**Comment by miladmikeal** [comment]
> @miladmikeal Are you running your specs in parallel on your machine? Or is it running each spec file sequentially?
> 
> You can log the memory and CPU usage of Cypress by following these instructions also: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage

I am not running the specs in parallel. Each spec file is running sequentially.

**Comment by harunurhan** [comment]
I have a issue on CI, which could be similar.

I see `cypress:server:video capture stderr` logs and profiler logs below where CPU usage is near 100%, then it hangs. Keeps printing the profiler logs forever.

```bash
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                      pids                       │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'Chrome'      │      7       │ '297, 308, 309, 311, 332, 322 ... 1 more items' │   63.37    │     34.05      │  590.14  │    526.15    │   590.14    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │                      '52'                       │    9.89    │     18.13      │  263.77  │    300.1     │   407.41    │
  cypress:server:util:process_profiler │    2    │ 'electron-shared' │      3       │                 '58, 208, 228'                  │     0      │       0        │  137.57  │    126.37    │   137.57    │
  cypress:server:util:process_profiler │    3    │     'plugin'      │      1       │                      '282'                      │    6.37    │      5.25      │  78.56   │    104.65    │   193.28    │
  cypress:server:util:process_profiler │    4    │     'ffmpeg'      │      1       │                      '296'                      │    9.36    │     18.97      │  77.53   │    65.73     │    77.53    │
  cypress:server:util:process_profiler │    5    │      'other'      │      2       │                   '567, 568'                    │     0      │      0.22      │   3.35   │     3.35     │    3.42     │
  cypress:server:util:process_profiler │    6    │      'TOTAL'      │      15      │                       '-'                       │     89     │     70.15      │ 1150.91  │   1048.96    │   1255.2    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
```
