### ISSUE TITLE
Fixtures not working in beforeAll in 5.0.0

### ISSUE THREAD

**Issue by AwarePL** [cypress-io/cypress#8422]
### Current behavior:
Using `cy.fixture` same as on code sample provided in docs/api i get following error:
![image](https://user-images.githubusercontent.com/21012825/91363065-0d5a0680-e7fc-11ea-80e0-6eddda992eed.png)

### Test code to reproduce

```js
const landingPageView = require("./pageObjects/landingPagePageObjects");
const landingPage = require("./selectors/landingPageSelectors");

describe("Landing Page Smoke Test", () => {
  beforeAll(() => {
    cy.fixture("consts")
    .then((consts) => {
      this.consts = consts
    })
    

    cy.visit("");
  });

  it("Check first section content, expect section title, subtitle, start page button", () => {
    landingPageView.checkSectionTitle(landingPage.sectionHero, this.consts.static.landingPage.sectionHeroH1[0]);
    landingPageView.checkSectionTitle(landingPage.sectionHero, this.consts.static.landingPage.sectionHeroH1[1]);
    landingPageView.checkSectionSubtitle(landingPage.sectionHero, this.consts.static.landingPage.sectionHeroP);
    landingPageView.checkSectionStartWebsiteButton(landingPage.sectionHero, this.consts.static.landingPage.startPageButton);
    landingPageView.checkSectionImages(landingPage.sectionHero, this.consts.static.landingPage.sectionHeroMobileAlt, this.consts.static.landingPage.sectionHeroTabletAlt, this.consts.static.landingPage.sectionHeroDesktopAlt);
  });
});
```

### Versions
Chrome 84
Windows 10
Cypress 5.0.0

**Comment by jennifer-shehane** [comment]
If you want to share context across tests, you'll want to use the standard function definition, instead of arrow functions: https://on.cypress.io/variables-and-aliases#Avoiding-the-use-of-this

```js
before(() => {
  this.consts = 'foo'
})

// function definition, not arrow function
it("test", function () {
  expect(this.consts).to.be.ok
})
```

I feel like this was likely a bug fix from the previous version. 🤔

**Comment by AwarePL** [comment]
sure,
in my other project currently at 4.10 arrow function still works. You are saying it was faulty all along in prev versions? 

 example:
`describe('sample End to end test suite', () => {
  before(() => {
    cy.fixture('testsParms').then((parms) => {
      this.parms = parms
    })
  })

  beforeEach(() => {
    cy.visit('')
  })

  it('test', () => {
    step1()
    step2(this.parms.fixture.node[0])
    })
`

**Comment by Bkucera** [comment]
I'm guessing this is related to us defaulting to `webpack-preprocessor`, which handles `this` differently. (in the working code, I think `this` is the global `window`). So yes, that code working in previous versions wasn't intended

**Comment by AwarePL** [comment]
OK, thanks for clarification. ;)
