### ISSUE TITLE
Cypress can't locate Chrome 85 exe in Windows

### ISSUE THREAD

**Issue by tyler36** [cypress-io/cypress#8425]
### Current behavior:
```cypress open``` does not show Chrome as a browser option. This occured after update to Chrome 85, released 2020-08-25.

I'm pretty sure this comes down to how Cypress is checking for the browser. While debugging, I came across a claim that cypress uses the following line to detect Chrome:

```
wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value
```

If this is true, Cypress won't work with Chrome 85 because it defaults to a x64 version (at least on my PC) which has a different default directory on Win10 x64 version: 

```
C:\Program Files\Google\Chrome\Application\Chrome.exe
```

### Desired behavior:
I would like the ability to use Chrome 84 x64 as a browser.

### Test code to reproduce
```cypress open```

### Versions
OS:  ```Windows 10```
Cypress: ```4.9.0``` and ```5.0.0```

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) specifically logging `cypress:launcher` logs and run `cypress info` and print the entire set of logs here?

**Comment by tyler36** [comment]
I ran 
```
set DEBUG=cypress:*
cypress run
```

```you will see a LOT of messages when running with DEBUG=... setting```
I see no specific debug info in the console. Just the test runner information, time taken and finished.
```
 Cypress:    5.0.0                                                                              │
  │ Browser:    Electron 83 (headless)                                                             │
  │ Specs:      1 found (examples\window.spec.js)
```

**Comment by tyler36** [comment]
```
Displaying Cypress info...

Detected 2 browsers installed:

1. Edge
  - Name: edge
  - Channel: stable
  - Version: 84.0.522.63
  - Executable: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
  - Profile: C:\Users\xxx\AppData\Roaming\Cypress\cy\production\browsers\edge-stable

2. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 79.0.0.7506
  - Executable: C:\Program Files\Mozilla Firefox\firefox.exe
  - Profile: C:\Users\xxx\AppData\Roaming\Cypress\cy\production\browsers\firefox-stable

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox
- cypress run --browser edge

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: C:\Users\xxx\AppData\Roaming\cypress\cy\development
Browser Profiles: C:\Users\xxx\AppData\Roaming\cypress\cy\development\browsers
Binary Caches: C:\Users\xxx\AppData\Local\Cypress\Cache

Cypress Version: 5.0.0
System Platform: win32 (10.0.18363)
System Memory: 8.46 GB free 1.42 GB
```

**Comment by jennifer-shehane** [comment]
Run:

```
set DEBUG=cypress:launcher
cypress run
```

**Comment by tyler36** [comment]
❯ set DEBUG=cypress:launcher
❯ cypress run


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    5.0.0                                                                              │
  │ Browser:    Electron 83 (headless)                                                             │
  │ Specs:      1 found (examples\window.spec.js)                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  examples\window.spec.js                                                         (1 of 1)


  Window
    √ cy.window() - get the global window object (9487ms)
    √ cy.document() - get the document object (12482ms)
    √ cy.title() - get the title (10776ms)


  3 passing (44s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     44 seconds                                                                       │
  │ Spec Ran:     examples\window.spec.js                                                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
    Compression progress:  83%
  -  Finished processing: I:\code\temp\cypress\cypress\videos\examples\window.spec.js   (11 seconds)
                          .mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  examples\window.spec.js                  00:44        3        3        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    √  All specs passed!                        00:44        3        3        -        -        -

**Comment by jennifer-shehane** [comment]
Yah, your debug logs aren't logging for some reason. 😞  I've seen this occur with permissions issues with setting the environment variable in the terminal/shell. You may need to run your terminal in administrative mode or review your permission settings.

**Comment by LaurensLeeuwis** [comment]
(I didn't get debug logging either, but running `export DEBUG=cypress:launcher` instead of `set DEBUG=cypress:launcher` did the trick for me)

**Comment by LukeBalsiger** [comment]
We are having the same issue since chrome 85 on a ci machine. Here's the output from our log
[cypress-launcher-log.txt](https://github.com/cypress-io/cypress/files/5137783/cypress-launcher-log.txt)

**Comment by tyler36** [comment]
As stated in the original post, Chrome 85 uses a different default installation directory.  
Solution: Create a symlink. Powershell example below:
```powershell
New-Item -ItemType SymbolicLink -Path "C:\Program Files (x86)\Google\Chrome" -Target "C:\Program Files\Google\Chrome"
```

The site documentation does mension this but the original post was intended a problem for Chrome uses on Windows.  If Google has defaulted to x64 version for Windows users, documentation should be updated to reflect this. Better yet, Cypress should be updated to look to this path for Windows x64 users.

**Comment by jennifer-shehane** [comment]
The code for the locations of browsers on Windows can be found here: https://github.com/cypress-io/cypress/blob/develop/packages/launcher/lib/windows/index.ts#L11:L11

We're open to a pull request to fix the executable location in Windows.
