### ISSUE TITLE
Pages from CodeSandbox urls are blank on `cy.visit()`

### ISSUE THREAD

**Issue by aravind-qe** [cypress-io/cypress#8428]
### Current behavior:

I'm trying to naviage to an app using cy.visit. The app url is *use any csb test app/. However cy.visit loads the page as a blank white page.

### Desired behavior:

The page should actually load and display items.

### Test code to reproduce

```js
describe('random test',function(){
  it('Logins in to sandbox',function(){
    cy.visit("https://ky998.csb.app/")
  })
})
```

### Versions

Cypress 5 , MacOS and Windows, Google Chrome, Electron and Firefox

**Comment by jennifer-shehane** [comment]
I'm able to recreate this behavior. There seem to be a lot of requests that are not happening within Cypress that are happening outside of it. 

Do you have any code in the application that would prevent it from running within an iframe?

**Comment by aravind-qe** [comment]
@jennifer-shehane Many thanks for your prompt response.

Nope. Funnily enough I've seen this exact page run within an iframe without any issues. I have also asked my team to confirm if we have anything that could possibly cause this from our end but as far as I'm aware this is not the case.

**Comment by aravind-qe** [comment]
Hi @jennifer-shehane , we do not have any code on our side to prevent the app being loaded in an iframe. However, we found that when we hosted the application at Google Firebase, it loaded fine on Cypress.
So it could be that for some reason Cypress is unable to fetch applications that are running in CodeSandBox.

This should ideally be fixed.

**Comment by dwineknott** [comment]
@jennifer-shehane I'm facing a similar dilemma.  Our apps login and create account pages recently stopped rendering when run in Cypress.  Outside of a test run the pages load fine.

Example code:

```
describe('Smoke Test - Login Feature', () => {

     Cypress.on('uncaught:exception', (err, runnable) => {
        // returning false here prevents Cypress from
        // failing the test
        return false
      }); 

 it('Login in successfully', () => {
    cy.visit('app.songtrust.com/login/');

// header and footer load, but page content does not

});

});
```

**Comment by jennifer-shehane** [comment]
@dwineknott I am not encountering an error loading the page in Cypress 5.0.0 with the test code provided. Please open a separate issue with a fully reproducible example.

<img width="1529" alt="Screen Shot 2020-08-28 at 1 43 14 PM" src="https://user-images.githubusercontent.com/1271364/91532595-8d838780-e934-11ea-9086-353db4d16117.png">

**Comment by jennifer-shehane** [comment]
@aravind-qe Yes, this absolutely has something to do with hosting on [CodeSandbox](https://codesandbox.io/).

I can run a test on some of CodeSandbox's featured projects https://codesandbox.io/explore and get the same result - the Test Runner is blank:

```
it('test', () => {
  // blank white page. 
  cy.visit('https://j0y0vpz59.csb.app/')
})
```

**Comment by codylindley** [comment]
Cypress will load the sandbox url (e.g. https://codesandbox.io/s/goodbye-daft-punk-ti2os?from-embed), even the sandbox embed URL (https://codesandbox.io/embed/goodbye-daft-punk-ti2os), but it won't load the output of the sandbox (e.g. https://ti2os.csb.app/).

**Comment by codylindley** [comment]
Heads up, the following code sandbox url works fine in cypress 

'https://ti2os.csb.app?standalone'

Note the use of `?standalone` on the preview URL from the codesandbox.
