### ISSUE TITLE
Variables declared outside "it" are reset between tests if different domains are visited

### ISSUE THREAD

**Issue by mclogan** [cypress-io/cypress#8431]
### Current behavior:

Variables that were declared outside "it" and changed during a test are reset to their original values in the next test if different domain is visited.

### Desired behavior:

Variables declared outside "it" are saved between tests no matter the domains visited.

### Test code to reproduce

    let a = 1

    it('Value of variable "a" is changed in this test.',() => {

        cy.visit('https://facebook.com')
        a = 2
        cy.log(a) // logs 2
    })

    it('Different domain, variable "a" has returned to it's original value.',() => {

        cy.visit('https://google.com')
        cy.log(a) // logs 1
        a = 3
        cy.log(a) // logs 3
    })

    it('Same domain as in previous test, value of "a" set in the previous test was saved.',() => {

        cy.visit('https://google.com')
        cy.log(a) // logs 3
    })

### Versions

Cypress: 4.12.1
browser: Chrome 85.0.4183.83 
operating system: Ubuntu 18.04.5 LTS

**Comment by jennifer-shehane** [comment]
Please follow this workaround: https://on.cypress.io/task#Save-a-variable-across-non-same-origin-URL-visits
