### ISSUE TITLE
Facing issue while upload image

### ISSUE THREAD

**Issue by dinesh0705** [cypress-io/cypress#8435]
In our application, we have 2 screen to upload an image.

Manually how i achieve image upload:
Steps:
- 1st screen -> Click on "Upload an image" -> Select image from drive -> After selecting image I land on 2nd screen
- 2nd screen -> Use this photo button (To submit user image)

Cypress script : 
```js
const yourFixturePath = 'din.jpg';
cy.get('#upload-image').attachFile(yourFixturePath);
```
![gitHut](https://user-images.githubusercontent.com/70335191/91464140-de01d300-e8a9-11ea-8e3e-773a17cc0441.png)
![gitHubScreen](https://user-images.githubusercontent.com/70335191/91464409-2de09a00-e8aa-11ea-920e-260bafd00797.png)

Through this script, i could upload image (Confirmed by checking cypres console)
But to navigate to 2nd screen i have to click, "Upload an image" without clicking i cant navigate to 2nd screen.
Here is the issue Im facing. When i click on "Upload an image", it is opening drive to select a image to upload.

Any suggestion how can i navigate to 2nd screen after Upload script?

Thanks in advance

Cypress version : 4.8.0

**Comment by jennifer-shehane** [comment]
Image upload is not natively supported within Cypress. See #170 for workarounds. Using the [cypress-file-upload](https://github.com/abramenal/cypress-file-upload) is a popular choice among current users of Cypress.
