### ISSUE TITLE
Duration of dashboard is wrong

### ISSUE THREAD

**Issue by bvanderneut** [cypress-io/cypress#8439]
# Current behavior:

The time shown in the dashboard does not reflect the real total time of the group.

![image](https://user-images.githubusercontent.com/44266055/91543905-38894680-e91f-11ea-9b71-dd508c840b31.png)

### Desired behavior:

The time shown should for a group should be the sum of all underling specs. So in the example 00:46 + 00:08 = 00:54. 

### Test code to reproduce

Do a run with grouping. Now you see it will show in the topbar the max time instead of the sum.

### Versions

5.0

**Comment by jennifer-shehane** [comment]
The duration of the group reflects the time is took the group to finish running - not adding the total durations of all specs together. This may reflect the time of the longest running spec, for example, if the specs ran in parallel. 

Can you click on the 'Machines' tab to show how the specs executed in parallel?

**Bar Chart**

<img width="1071" alt="Screen Shot 2020-08-28 at 4 05 03 PM" src="https://user-images.githubusercontent.com/1271364/91546321-47d0ba00-e948-11ea-8d37-c0e9605285ec.png">

**Machines**

<img width="1073" alt="Screen Shot 2020-08-28 at 4 04 53 PM" src="https://user-images.githubusercontent.com/1271364/91546385-5a4af380-e948-11ea-8a8c-9d8cc41780ca.png">

**Comment by bvanderneut** [comment]
Ok that make sense :) I could not find any information explaining the dashboard column's.
