### ISSUE TITLE
Types erroneously doesn't take into account JQuery-wrapping

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#8440]
# Current behavior:

A HTML-element returned in `.then(..)` will be wrapped in a JQuery-object by Cypress, but the types doesn't take this into account.

```
cy.get("div")
  .then($div => $div[0])
  .then($div =>
    $div // The type is erroneously reported as HTMLDivElement.
  );
```

### Desired behavior:

```
cy.get("div")
  .then($div => $div[0])
  .then($div =>
    $div // $ExpectType JQuery<HTMLDivElement>
  );
```

### Test code to reproduce

[Here](https://github.com/badeball/cypress-reproducible-issues/tree/master/erroneous-types). Run `dtslint types` and watch it fail.

### Versions

Cypress v5.0.0, Arch Linux.

**Comment by sainthkh** [comment]
Confirmed that there's an error in types with the code below: 

```js
it('t', () => {
  cy.get('div')
  .then(($div) => $div[0])
  .then(($div) => {
    console.log($div) // returns jquery.fn.init

    return $div
  })
})
```

**Comment by sainthkh** [comment]
Close this in favor of #14875.
