### ISSUE TITLE
experimental Fetch Polyfill - 'getReader' of undefined

### ISSUE THREAD

**Issue by DanieleDiLucido** [cypress-io/cypress#8441]
### Current behavior:
Is impossible to reproduce video contents with Shaka Player when experimentalFetchPolyfill is enabled. 
Shaka player throws the following error: 
> ERROR: Shaka Error NETWORK.HTTP_ERROR (https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd,TypeError: Cannot read property 'getReader' of undefined,0)

- experimentalFetchPolyfill: true
      ![KO](https://user-images.githubusercontent.com/25788837/91561788-72b51100-e93c-11ea-9f5c-288eec0788e7.png)

- experimentalFetchPolyfill: false
   ![OK](https://user-images.githubusercontent.com/25788837/91561763-6a5cd600-e93c-11ea-958c-746bde646cdc.png)

### Test code to reproduce

``` javascript
describe('Test player', () => {
  it('VOD', () => {
    cy.visit('https://shaka-player-demo.appspot.com/demo/#audiolang=it-IT;textlang=it-IT;uilang=it-IT;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=HOME;build=uncompiled');
    cy.wait(60000);
  });
});
```

### Versions
Cypress v5.0.0

**Comment by bahmutov** [comment]
@DanieleDiLucido the experimental fetch polyfill does not support streaming responses, see https://www.cypress.io/blog/2020/06/29/experimental-fetch-polyfill/#limitations 

I suggest waiting a few days when we release the new network stubbing API with `cy.route2` that might solve mocking needs without the fetch polyfill. The PR https://github.com/cypress-io/cypress/pull/4176 has already been merged into `develop` and will be released within a day or two.
