### ISSUE TITLE
App forms not loading in test runner

### ISSUE THREAD

**Issue by dwineknott** [cypress-io/cypress#8443]
@jennifer-shehane I'm facing a similar dilemma.  Our apps login and create account pages recently stopped rendering when run in Cypress.  Outside of a test run the pages load fine.

I reinstalled a fresh instance of Cypress, thinking maybe a plugin or something specific to my config was the culprit, but this hasn't resolved the issue.  If this is not an internal cypress bug, ANY guidance you can provide would be appreciated.

I see the HTML in console being returned.  It looks like the class on the element is using a class that hides the form within the test runner:

> Command:  assert
> cypress_runner.js:199982 Subject:  jQuery.fn.init [input#email.form-control]
> cypress_runner.js:199982 Message:  expected <input#email.form-control> to be visible
> cypress_runner.js:199982 Error:    AssertionError: Timed out retrying: expected '<input#email.form-control>' to be 'visible'
> 
> This element `<input#email.form-control>` is not visible because its parent `<div#v-login-form.row.hide>` has CSS property: `display: none`

Example code:

```js
describe('Smoke Test - Login Feature', () => {

     Cypress.on('uncaught:exception', (err, runnable) => {
        // returning false here prevents Cypress from
        // failing the test
        return false
      }); 

 it('Login in successfully', () => {
    cy.visit('app.songtrust.com/login/');

// header and footer load, but page content does not

});

});
```
Failing in Chrome, Electron, Firefox within the test runner.
Cypress 5.0.0
Mac OS X 10.15.6

Within the test runner:

![Screen Shot 2020-08-28 at 12 22 41 PM](https://user-images.githubusercontent.com/11638121/91591166-7c357d80-e92a-11ea-8e65-88a08c39fbe3.png)

Outside of the test runner:

![Screen Shot 2020-08-28 at 12 33 05 PM](https://user-images.githubusercontent.com/11638121/91591279-adae4900-e92a-11ea-9a45-e9d5df06c150.png)

_Originally posted by @dwineknott in https://github.com/cypress-io/cypress/issues/8428#issuecomment-682343278_

**Comment by dwineknott** [comment]
Figured it out.  I disabled "experimentalSourceRewriting", and the page was able to load successfully in the test runner.

Curious as to why this is the case.

**Comment by flotwig** [comment]
@dwineknott probably the source rewriting is corrupting something, are there any other errors in the console?

There are several open issues with the source rewriting experiment: https://github.com/cypress-io/cypress/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22experiment%3A+source+rewriting%22

**Comment by dwineknott** [comment]
Uncaught TypeErrors within the console with the "experimentalSourceRewriting" enabled:

[app.songtrust.com-1598650225290.log](https://github.com/cypress-io/cypress/files/5144272/app.songtrust.com-1598650225290.log)

**Comment by flotwig** [comment]
@dwineknott can you share the line where this error is thrown according to the stack trace?

**Comment by dwineknott** [comment]
Screen shots of source code:

> VM23 main.77590bda2863.js:formatted:7890 Uncaught ReferenceError: The following error originated from your application code, not from Cypress.
![Screen Shot 2020-08-31 at 12 17 28 PM](https://user-images.githubusercontent.com/11638121/91742321-1ba17d00-eb84-11ea-87f1-451802ee3726.png)


> (index):55 Uncaught TypeError: The following error originated from your application code, not from Cypress.

![Screen Shot 2020-08-31 at 12 26 02 PM](https://user-images.githubusercontent.com/11638121/91743083-42ac7e80-eb85-11ea-8249-af870259dd30.png)
