### ISSUE TITLE
Video stuck on first test

### ISSUE THREAD

**Issue by mosofsky** [cypress-io/cypress#8444]
### Current behavior:

There are multiple tests in my test suite but the cypress.io video is stuck at the end of the first test.  Also the same video is shown for each of my tests.  Let me explain in more detail with an example:

Test1 - clicking video and the play marker is set at 20 seconds at the end of the first test, rewinding shows some of that test running but it seems like a lot of frames are missing.  The video from 20 seconds through the end of the video is the same frame basically as if nothing happened for a half hour.

Test2 - shows exactly the same thing at Test1 except the play marker is set to 30 seconds.  Fast forwarding does not show Test2, like I said above it's the same frame for a half hour.

Test3 - same as Test1 but play marker is at 40 seconds.

etc.

### Desired behavior:

I would like the video to show what happened when each test was run.  Also, when I click a test, I want it to place the play marker at the point in the video where that test began.

### Test code to reproduce

The problem is with the video, not the test.

You can see evidence of the problem in the test's recording:

Here's the video https://dashboard.cypress.io/projects/3ypjsw/runs/53/test-results/a40cc19b-a138-4553-853f-648dacb72bde/video associated with run 53.

If you can access it or something, I have uploaded the video to youtube: https://youtu.be/XWc-jkmEcG8

For what it's worth, the test file contains around 50 tests.  I'm not using describe() blocks.  Each test is an it() block.

### Versions

"cypress": "5.0.0"
"@percy/cypress": "^2.3.1",
"eslint-plugin-cypress": "^2.11.1",

In case it's useful, here is my Gitlab CI job template for running testing:

.jb_integration_test_template:
  stage:
    stg_integration_test
  image: cypress/base:10
  variables:
\#    LOG_LEVEL: debug
  script:
    - yarn install
    - $(yarn bin)/print-env PERCY
    - yarn run cy:verify
    - yarn run cy:info
    - yarn run e2e:record
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 7 days

Here's my scripts section of my package.json:

  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jest-environment-jsdom-sixteen",
    "eject": "react-scripts eject",
    "servelocal": "yarn run build; firebase serve",
    "serveremote": "yarn run build; firebase deploy",
    "e2e:record": "percy exec -- cypress run --record --key f9d8f374-7e24-4e5e-9e84-0877805c4a58 --parallel --group \"Electron browser on GitLab CI\"",
    "cy:verify": "cypress verify",
    "cy:info": "cypress info",
    "cy:version": "cypress version",
    "cy:cache:list": "cypress cache list",
    "cy:run": "cypress run",
    "cy:run:record": "cypress run --record",
    "cy:open": "cypress open"
  },

**Comment by jennifer-shehane** [comment]
Sorry for the delay in responding. The videos in this issue are no longer available. I hope your issue has been resolved. We'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
