### ISSUE TITLE
Hello, I need some tutorial on how to configure the cypress to run in the continuous integration of the bitbucket pipeline

### ISSUE THREAD

**Issue by henrique-barbase** [cypress-io/cypress#8445]
Hello, I need some tutorial on how to configure the cypress to run in the continuous integration of the bitbucket pipeline

**Comment by metalmini** [comment]
First hits in Google
https://www.cypress.io/blog/2018/08/30/setting-up-bitbucket-pipelines-with-proper-caching-of-npm-and-cypress/

https://medium.com/@simphiwesithole/cypress-bitbucket-pipelines-ab6b1f590d0e

https://tsh.io/blog/bitbucket-pipelines-configuration-for-test-automation/

**Comment by bahmutov** [comment]
Thank you @metalmini
