### ISSUE TITLE
High CPU Usage Even When Not Automating UI

### ISSUE THREAD

**Issue by cmcnicholas** [cypress-io/cypress#8446]
### Current behavior:

When running our test suite we have a number of before hooks that perform some setup making use of `cy.request` A LOT.

When our tests run we experience super high CPU usage even when not automating the UI (performing the requests). My machine is no slouch but cypress utilises all 4 cores for a http request, this behaviour seems very odd.

![image](https://user-images.githubusercontent.com/41394833/91656554-833ac800-eab1-11ea-8719-c8476dd5f973.png)

![image](https://user-images.githubusercontent.com/41394833/91656567-acf3ef00-eab1-11ea-8502-6044cfb7836f.png)

I am only running cypress, chrome and a music player. Even if I shut down all other apps cypress is very greedy.

### Desired behavior:

Cypress should not use 100% CPU for performing a HTTP request when the automation is idle.

### Test code to reproduce

```ts
// the reason we do this chaining is to store the complete output into an object (a string array in this case but that's just for example)
// rather than using some static global
function lotsOfApi(): Cypress.Chainable<string[]> {
  let chain: Cypress.Chainable<null | Cypress.Response> = cy.wrap(null);
  const testData: string[] = [];
  for (let i = 0; i < 1000; i++) {
    chain = chain.then(() => {
      return cy.request('https://dummyapi.io/data/api/user').then((response) => {
        // store some values from response
        testData.push(response.statusText);
      });
    });
  }
  return chain.then(() => testData);
}

describe('lots of api tests', () => {

  let testData: string[] | null = null;

  before(() => lotsOfApi().then((d) => (testData = d)));

  it('should have data', () => assert.isArray(testData));

});
```

### Versions

Cypress: `v4.12.1`
OS: Windows 10
Browser: Electron (or chrome)

**Comment by shwarcu** [comment]
Performance issues in Cypress is something quite common. In my case on Macbook Pro 16 with 32GB of ram, after running a suite of tests I can barely select commands in the preview and see snapshots of the page from that point of time. It takes a lot of time for Cypress to update view of test runner. It's very very slow, sometimes unusable.

**Comment by cmcnicholas** [comment]
> Performance issues in Cypress is something quite common. In my case on Macbook Pro 16 with 32GB of ram, after running a suite of tests I can barely select commands in the preview and see snapshots of the page from that point of time. It takes a lot of time for Cypress to update view of test runner. It's very very slow, sometimes unusable.
> 
> I have run your code, result was identical. Cypress processes entirely occupied CPU and my mac started to heat up. I will try to run this snipped at home with Ryzen 2700X and see if Cypress will also consume entire cpu with this task.

Thanks for confirming, a work colleague has the same Ryzen and posts the same results as me, we also have server grade CPU's in the office we have ran this on which yield the same results.

**Comment by WORMSS** [comment]
I am seeing the same problem.
i7-7700K using 100% CPU
It seems it even sometimes misses the response of the request itself.
I can tell from external networking logs that the request and response was successful and quick.
Less than 1 second. But cypress indicates that it was a timeout fail of over 60000 ms

@shwarcu do you know of any workarounds that could be put in place?
Any secret tricks to flattening out a very deep chainage link?

**Comment by WORMSS** [comment]
Just to add to this.. if you do 
```ts
cy.request({
  url: ...
  log: false
});
```
It doesn't cause the CPU overload.
I am guessing it's all the creating snapshots that is causing this.
Is it possible to keep logging turned on but turn snapshot off?

**Comment by shwarcu** [comment]
@WORMSS  sorry I don't have any workaround :( Performance is even worse recently, after running a simple test most of the time I can't click on anything in the runner, it just freezes.

**Comment by francisu** [comment]
If you are using Typescript and CRA 4.x, this might be your problem: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/655

**Comment by rajutandukar** [comment]
i am also having same issue . i use macOs 2GHz core intel core i5, 16GB. Cypress get hung and have to force quit even nothing were ran.
