### ISSUE TITLE
Cypress navigates to a different URL cause of different pageObject vlaues.

### ISSUE THREAD

**Issue by gauravknoldus** [cypress-io/cypress#8448]
### Current behavior:

I have an chrome extension which will pick the page URL based on the window object of the current active tab. Extension is working as expected in normal usage, but when I try to execute the same with Cypress some of the internal network calls are failing and make the extension non functional. As per our RCA this is all happening cause Cypress navigates to a different URL, as its test run within an i frame with a specifically defined URL. These URLs do not match and thus cause an error when trying to retrieve data from the APIs. 

### Desired behavior:

Window object values should be same.

### Test code to reproduce
To reproduce the same,just fire the URL 'https://www.theglobeandmail.com/' and check the value of  window.location.pathname variable in normal manual test vs cypress tests.

![Screenshot from 2020-08-31 17-45-32](https://user-images.githubusercontent.com/5989845/91718875-e3189800-ebb1-11ea-8426-bf4c21127e52.png)

### Versions

Cypress 5.0, operating system: Ubuntu 18.04, browser Chrome 84

**Comment by bahmutov** [comment]
@gauravknoldus the web application under test executes in an iframe. You evaluated the `window.location.pathname` in the context of the _top_ Cypress-controlled window. Switch the context to the application under test to see the pathname of the `window` object that belongs to that iframe
