### ISSUE TITLE
Opening Cypress... yielding no visible result

### ISSUE THREAD

**Issue by rowbot-weisguy** [cypress-io/cypress#8454]
### Current behavior:
![image](https://user-images.githubusercontent.com/4230333/91769021-6f679280-eb93-11ea-98eb-3fe43d6091af.png)

DEBUG logs on repeat:
![image](https://user-images.githubusercontent.com/4230333/91769412-30860c80-eb94-11ea-8f0f-34fcee9ccf83.png)

### Desired behavior:

When running `npx cypress open` I expect the test runner (Electron app, I presume? First time trialing this) to open

### Test code to reproduce
* Check out https://github.com/rowbot-weisguy/cypress-test-tiny
* Clear Cypress cache (I used `rm -rf ~/.cache/Cypress`. Not sure if this step is required at all, I just did it to be sure)
* Install dependencies `npm install`
* Run `npx cypress open`

### Versions
Cypress: 5.0.0
Windows 10 but running Cypress inside of Ubuntu 20.04 using WSL
Node: 14.8.0
Chrome: 84.0.4147.135

**Comment by darylthornhill** [comment]
Did you have any luck with this? Are you running on wsl?

**Comment by brantchoate** [comment]
same issue
