### ISSUE TITLE
AssertionError: Timed out retrying: expected 'chrome-error://chromewebdata/'

### ISSUE THREAD

**Issue by LMPrashkbk** [cypress-io/cypress#8457]
### Current behavior:

Login to website 
1.Run login page
2.Run another page with login
 

### Desired behavior:

Both pages should run but I'm getting this error

Already added chromewebsecurity:false still getting this error

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/4220
