### ISSUE TITLE
cy.route() is ignored by <img> and <a> tags in the rendered page

### ISSUE THREAD

**Issue by unikitty37** [cypress-io/cypress#8459]
### Current behavior:

Stubs configured with `cy.route()` are ignored by`<img>` and `<a>` tags on the page.

In the first test, the `fillmurray.com` stub is ignored, and an image of Bill Murray is rendered.

In the second test, the contents of `page2.html` are rendered rather than the string returned by the stub.

![image](https://user-images.githubusercontent.com/139183/91841660-a64caf80-ec4a-11ea-82df-33c2b317c544.png)

The documentation does not make it clear that `cy.route()` has these restrictions, nor does it mention how to work around them.

### Desired behavior:

The stubs are respected:

* in the first test, an image of a kitten is rendered instead of Bill Murray.
* in the second test, the stubbed string `SAUSAGE` is rendered rather than `page2.html`.

If that is not possible (whether by design or not), the limitations should be documented, ideally with instructions on a workaround.

### Test code to reproduce

https://github.com/unikitty37/cypress-test-tiny

### Versions

Cypress: 5.0.0
OS: macOS 10.14.6 (18G6020)
Browser: Chromium 84.0.4147.0 (Developer Build) (64-bit)

**Comment by bahmutov** [comment]
Hi,

The documentation page https://on.cypress.io/route starts with noting that only Ajax requests are intercepted. We will remove this limit in the near future when `cy.route2` is released

<img width="828" alt="Screen Shot 2020-09-01 at 9 37 28 AM" src="https://user-images.githubusercontent.com/2212006/91858110-c2465600-ec36-11ea-8188-e00291e180cb.png">
