### ISSUE TITLE
Retries at suite and test level give a type error

### ISSUE THREAD

**Issue by bloodmadridista** [cypress-io/cypress#8461]
### Current behavior:
Currently, your documentation says that retries can be added at a Global level,  at a suite level, and at a test level. Unfortunately, when trying to add at a suite or test level typescript gives an error.

```
Argument of type '{ retries: { runMode: number; openMode: number; }; }' is not assignable to parameter of type 'TestConfigOverrides'.
Object literal may only specify known properties, and 'retries' does not exist in type 'TestConfigOverrides'.ts(2345)
```

Looking at the code in your master branch seems like there was an attempt to add this to the interface but it was not completed. I could be missing something but retries is just a comment. 

```
interface TestConfigOverrides extends Partial<Pick<ConfigOptions, 'baseUrl' | 'defaultCommandTimeout' | 'taskTimeout' | 'animationDistanceThreshold' | 'waitForAnimations' | 'viewportHeight' | 'viewportWidth' | 'requestTimeout' | 'execTimeout' | 'env' | 'responseTimeout'>> {
    // retries?: number
    browser?: IsBrowserMatcher | IsBrowserMatcher[]
  }
```

However, in the ResolvedConfigOptions interface is definitely defined correctly.

`  /**
     * Number of times to retry a failed test.
     * If a number is set, tests will retry in both runMode and openMode.
     * To enable test retries only in runMode, set e.g. `{ openMode: null, runMode: 2 }`
     * @default null
     */
    retries: Nullable<number | {runMode: Nullable<number>, openMode: Nullable<number>}>`

### Desired behavior:

Retries should work as it is specified in your documentation, where the retry can be added at the suite and test level as well.

### Test code to reproduce

Using typescript.

 Using your own example from your documentation:

```
// Customizing retry attempts for a suite of tests
describe('User bank accounts', {
    retries: {
      runMode: 2,
      openMode: 1,
    }
  }, () => {
    // The per-suite configuration is applied to each test
    // If a test fails, it will be retried
    it('allows a user to view their transactions', () => {
      // ...
    });
  
    
  });
```

<img width="614" alt="Screen Shot 2020-09-01 at 9 59 42 AM" src="https://user-images.githubusercontent.com/59067465/91860619-e2c3df80-ec39-11ea-8200-9035c06acd86.png">

<img width="902" alt="Screen Shot 2020-09-01 at 9 52 47 AM" src="https://user-images.githubusercontent.com/59067465/91859855-ec991300-ec38-11ea-8d6c-cbf7e7c4d5cb.png">

### Versions

Cypress version 5.0.0, any browser.

**Comment by bahmutov** [comment]
We have noticed it in https://github.com/cypress-io/cypress/issues/8405 and fixed in https://github.com/cypress-io/cypress/pull/8408 to be released in v5.1.0
