### ISSUE TITLE
cy.setCookie times out

### ISSUE THREAD

**Issue by cellog** [cypress-io/cypress#8464]
### Current behavior:
when running Cypress in CI environment inside Docker, cy.setCookie in an `after()` times out consistently.

### Desired behavior:
As the docs say "this should never happen"

### Test code to reproduce
Create a test that runs cy.setCookie() during the test, and then in an after() runs cy.setCookie with the same cookie name

**Comment by BlueWinds** [comment]
We're reworking how cy.cookie works in Cypress 12 - it should be more reliable across environments and uses. Going to close this, feel free to open another issue if you still run into issues!
