### ISSUE TITLE
Documentat cy.route2() response function example

### ISSUE THREAD

**Issue by clintharris** [cypress-io/cypress#8468]
The API docs seem to be missing an example of how to use response functions with `cy.route2()`: https://docs.cypress.io/api/commands/route2.html#Response-functions

In other words, the current examples under "Response Functions" don't actually show a function being used to handle the route.

### Versions

Cypress 5.1.0

**Comment by bencodezen** [comment]
A PR has been issued here: https://github.com/cypress-io/cypress-documentation/pull/3128
