### ISSUE TITLE
Retries custom configuration on test/test suites not recognized in TS

### ISSUE THREAD

**Issue by Ineth** [cypress-io/cypress#8472]
### Current behavior:

Adding retries configuration as described in https://docs.cypress.io/guides/guides/test-retries.html#Custom-Configurations
gives a `Argument of type '{ retries: { runMode: number; openMode: number; }; }' is not assignable to parameter of type 'TestConfigOverrides'` warning in VS Code.

### Desired behavior:

No type error and correct representation of the available options.

### Test code to reproduce

Create the example seen in the documentation in an TS setup.

```TS
// example.spec.ts

describe(
  'User bank accounts',
  {
    retries: {
      runMode: 2,
      openMode: 1
    }
  },
  () => {
    // The per-suite configuration is applied to each test
    // If a test fails, it will be retried
  }
);
```

I noticed that in the `cypress.d.ts` for `TestConfigOverrides` the retries is set in comment (line 2586).
Although the `ConfigOptions` contains the `retries` type structure

### Versions

cypress 5.0.0
"@cypress/webpack-preprocessor": "^5.4.5",
"ts-loader": "^6.2.1",
"tslint": "^5.20.1",
"tslint-config-prettier": "^1.18.0",
"tslint-plugin-prettier": "^2.1.0",
"typescript": "^3.7.5",

**Comment by coffee-mug-jk** [comment]
Check the newest version, it should be fixed: [Related ticket](https://github.com/cypress-io/cypress/issues/8405)

**Comment by bahmutov** [comment]
Agree with @coffee-mug-jk closing as resolved
