### ISSUE TITLE
Include HTTP Headers for each request in cypress tests

### ISSUE THREAD

**Issue by saigoutham7** [cypress-io/cypress#8475]
### Current behavior:
- I need to add headers to the initial `cy.visit()` request and all the subsequent requests made in my tests.
- I have tried using `onAnyRequest`, which isn't working.
  `Cypress.Server.defaults({
    onAnyRequest: (route,  proxy) => {       
        proxy.xhr.setRequestHeader("auth-token-1", "abc"),
    }
});`
- Is there any other workaround to add headers to initial url and and subsequent requests?

### Desired behavior:

- headers should be added for all the requests made in my tests.

### Versions
Cypress: 4.11.0

**Comment by Mathieuu** [comment]
Same here, `onAnyRequest` doesn't seem to be called

**Comment by gustawx** [comment]
[Here ](https://github.com/cypress-io/cypress/issues/5289) is a defect for this. Pretty old, hope it will be fixed
