### ISSUE TITLE
Can't close Lon in prompt

### ISSUE THREAD

**Issue by Pavlo-git** [cypress-io/cypress#8476]
Hello! I have log in JS prompt with two fields. And didn't find any solution how to close it with cypress. Can you help please?

![image](https://user-images.githubusercontent.com/61518906/91982532-0fa7ed80-ed33-11ea-93d3-2f9a730059b8.png)

**Comment by sainthkh** [comment]
Sorry for the late replay. 

It's hard to provide the right answer because there's not much information here. But I guess `cy.get('cancel button selector').click()` might do the job if clicking it closes the modal.
