### ISSUE TITLE
TS error: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'

### ISSUE THREAD

**Issue by IlCallo** [cypress-io/cypress#8477]
### Current behavior:

After update to Cypress 5.1, tests breaks throwing `TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.`
If I set `inlineSourceMap` to `false`, the error persist.
If I set `sourceMap` to `false`, test start working again.

Given that the default for `inlineSourceMap` is `false`, that I do not set it, and that it breaks only on newer versions, I'd say the new webpack preprocessor forces the `inlineSourceMap` option to `true` somewhere.

This is strange because it seems like you have a whole file in place to manage this scenario: https://github.com/cypress-io/cypress-webpack-preprocessor/blob/master/lib/typescript-overrides.ts

### Desired behavior:

Tests should keep working without problems

### Test code to reproduce

Using a `tsconfig` with `sourceMap: true` option do the trick.

---
Edited to add repro:
https://github.com/IlCallo/cypress-test-tiny/tree/ts-sourcemap-conflict

- clone locally
- `yarn install`
- `yarn cypress:open`
- click on "spec.ts" test
- witness the error

### Versions

Cypress: 5.1.0
OS: Ubuntu 18.04

**Comment by bahmutov** [comment]
Could you please prepare a repository that we can run with a reproducible example?

**Comment by IlCallo** [comment]
@bahmutov 
Here it is: https://github.com/IlCallo/cypress-test-tiny/tree/ts-sourcemap-conflict

- clone locally
- `yarn install`
- `yarn cypress:open`
- click on "spec.ts" test
- witness the error

**Comment by Rafsonic** [comment]
I have the same issue as well. Any feedback?

Cypress: 5.1.0
OS: Ubuntu 20.04

**Comment by Kocal** [comment]
As a workaround until this issue is fixed, did someone know if it is possible to specify which `tsconfig.json` Cypress should use?

E.g. a `tsconfig-cypress.json`: 
```json
{
  "extends": "./tsconfig.json",
  "sourceMap": false
}
```

Thanks

**Comment by IlCallo** [comment]
AFAIK you can only do this via the webpack loader which takes care of checking TS files.
Example on Quasar: https://github.com/quasarframework/quasar-testing/blob/dev/packages/e2e-cypress/src/index.js

**Comment by cellog** [comment]
I see this with Cypress set up in a subdirectory, it is unable to find tsconfig.json

**Comment by aelmekeev** [comment]
We see this issue when cypress imports some code from other subproject with its own `tsconfig.json`. I don't want to set `sourcemap` to `false` in there so it's blocking us completely from migrating to 5.x.

**Comment by haf** [comment]
Place the tsconfig.json file here to override the parent folder's tsconfig.json file. https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json

**Comment by aelmekeev** [comment]
> Place the tsconfig.json file here to override the parent folder's tsconfig.json file. https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json

@haf we do have `tsconfig` in `cypress` folder with `"sourceMap": false` but it doesn't help.

**Comment by haf** [comment]
Not in your repro https://github.com/IlCallo/cypress-test-tiny/tree/ts-sourcemap-conflict/cypress

I found this by googling the same problem. Then read the docs. Then I configured it like the docs say, and it started working. https://github.com/logary/logary-js/blob/master/cypress/tsconfig.json

**Comment by jennifer-shehane** [comment]
I can recreate the issue with the repo provided. Introduced in 5.0.0. 

### Repro

`spec.ts`

```ts
it('works', () => {})
```

`tsconfig` at project root

```json
{
  "compilerOptions": {
    "sourceMap": true,
    "types": [
      "cypress"
    ]
  },
  "include": [
    "**/*.ts"
  ]
}
```

`package.json`

```json
{
  "devDependencies": {
    "cypress": "^5.5.0",
    "typescript": "^4.0.2"
  }
}
```

<img width="1140" alt="Screen Shot 2020-10-28 at 12 47 11 PM" src="https://user-images.githubusercontent.com/1271364/97399535-b9fb5600-191b-11eb-9bc8-8c2da34aa4be.png">

**Comment by IlCallo** [comment]
@haf that's a minimal repro, my use case have the tsconfig as suggested by the docs, but that wasn't needed to show the broken behaviour

**Comment by unbugx** [comment]
Look at https://www.cypress.io/blog/2019/05/13/code-create-react-app-v3-and-its-cypress-tests-using-typescript/ It helps me a lot and everything works ok

My current cypress/tsconfig.json

```
{
  "extends": "../tsconfig.json",
  "include": [
    "../node_modules/cypress",
    "**/*spec.ts"
  ],
  "compilerOptions": {
    "noEmit": false,
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"]
  }
}
```

**Comment by guiedugt** [comment]
Thanks @unbugx! Your answer helped me to fix the issue. I had to disable `sourceMap` as well, though

```json
{
  "extends": "../../tsconfig.json",
  "include": [
    "../../node_modules/cypress",
    "**/*.ts"
  ],
  "compilerOptions": {
    "noEmit": false,
    "sourceMap": false,
    "types": ["cypress"]
  },
}
```
