### ISSUE TITLE
Issue with styles in dom snapshot

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [cypress-io/cypress#8480]
### Current behavior:
The DOM Snapshots are failing, this since the beginning of the project (+- 3 months ago), for all the tests.

when we hover any test:
![image](https://user-images.githubusercontent.com/1098243/92003161-fc038380-ed40-11ea-82d7-a92f3a4307a7.png)

### Desired behavior:
well yeah, having correct snapshots would be nice

OS: Windows 10
Angular 9 Webapp, running locally with ng serve

**Comment by bahmutov** [comment]
I am not sure what the expected DOM snapshot should be here. Can you prepare a public repo with a reproducible example and expected snapshot images?

**Comment by LanderBeeuwsaert** [comment]
Hi @bahmutov ,

I won't get the green light here (I'm on a project for an outside company) to take the time to prepare a repo; apologies.
However I can give you a screenshot of what the styling is like during the run:

![image](https://user-images.githubusercontent.com/1098243/92084736-1d5b8280-edc8-11ea-9ee1-b15f15bed504.png)

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Unfortunately, this issue should be closed because it is inactive and there is no reproducible example. I hope the problem has been solved with the latest Cypress. If the problem is still happening, please open a new issue with a reproducible example.
