### ISSUE TITLE
Getting cross-domain access error during the test

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8485]
### Current behavior:

A test that redirects from `index.html` to another domain gets cross-domain access error

Test loads `index.html` which redirects to another domain

```js
// spec.js
/// <reference types="cypress" />
describe('page', () => {
  it('works', () => {
    cy.visit('index.html')
    cy.contains('h1', 'Utilities').should('exist')
  })
})
```

The index.html is
```html
<body>
  Hello there
  <script>
    setTimeout(() => {
      console.log('going to utilities')
      window.location = 'https://example.cypress.io/utilities'
    }, 1000)
  </script>
</body>
```

See the following error

![image](https://user-images.githubusercontent.com/2212006/92039692-7cc37f00-ed43-11ea-9a3e-62c3d96e18d3.png)

### Desired behavior:

Correctly wait for the new site to load

### Test code to reproduce

In https://github.com/cypress-io/cypress-test-tiny/tree/load-page

### Versions

Cypress v5.1.0

### Background

I was looking at this screenshot sent by the user trying to recreate this error

![image](https://user-images.githubusercontent.com/2212006/92040142-4b977e80-ed44-11ea-9ef6-04ac44a1a0a4.png)

and stumbled across the above error first

**Comment by BlueWinds** [comment]
Since the introduction of cy.origin, and a general rework of how cross-origin errors and testing work in Cypress 12, going to close this as a bit outdated now.
