### ISSUE TITLE
Differentiate betwee failure screenshots and .screenshot() results

### ISSUE THREAD

**Issue by alexkrolick** [cypress-io/cypress#8486]
### Current behavior:

We have the following config option

Option | Default | Description
-- | -- | --
screenshotsFolder | cypress/screenshots | Path to folder where screenshots will be saved from cy.screenshot() command or after a test fails during cypress run

The trouble is that screenshots after failure are different than screenshots taken during a test. Failure reports are test artifacts that don't get checked into source control, but `cy.screenshot()` calls should be under source control so they appear in pull requests for review.

### Desired behavior:

`cy.screenshot()` would write files in a (configurable) directory next to the test file that generated the screenshot, similar to Jest snapshots. (`__screenshots__/my_test__it_should_look_good_1.png`)

Alternatively, you could use a static location for screenshots, but keep failure screenshots and videos separate in .gitignore-able location (say `cypress/failure/screenshots|videos` by default)

### Test code to reproduce

n/a

### Versions

4.11.0

**Comment by Bkucera** [comment]
Hi, this should already be possible today using a `pluginsFile` (cypress/plugins/index.js):
```js

module.exports = (on) => {
  on('after:screenshot', (details) => {
    // only rename if it's a call to cy.screenshot()
    if (!details.testFailure) {
      return {
        path: replacementPath,
      }
    }
  })
})
```

Since this can already be done via plugins, I'm going to close this.
