### ISSUE TITLE
cy.route2 documentation: delay/throttle function examples not right?

### ISSUE THREAD

**Issue by yonigibbs** [cypress-io/cypress#8489]
In the documentation for `cy.route2` there's [this example](https://docs.cypress.io/api/commands/route2.html#Simulate-delay) of the `delay` function:

```
cy.route2('/users', (req) => {
  req.delay(200)
})
```

When I tried that I got a compilation error: `Property 'delay' does not exist on 'InocmingHttpRequest'`. From looking at the code, looks like it's on `IncomingHttpResponse`, not on the request itself.

Same thing applies to the `throttle` function. The `redirect` one does seem to compile OK though.

There's a couple of other minor issues too (let me know if you want separate issues logged for these):
1. [One of the code snippets](https://docs.cypress.io/api/commands/route2.html#Making-multiple-requests-to-the-same-route) talks about `beetle` items in a response - it's not really clear what this is referring to.
2. The section about multiple requests isn't quite clear in terms of how to stub a single route, and give it a different response every time it's called (particularly required for GraphQL endpoints). For example, can you call `cy.route2` multiple times in a test, to set up a different way to handle the call each time?

**Comment by flotwig** [comment]
Yeah, there's a typo, `.delay` and `.throttle` should be documented on `res`, not `req`.

> For example, can you call cy.route2 multiple times in a test, to set up a different way to handle the call each time?

There's not an API for counting requests yet, but you can set up the counting yourself, for example:

```js
let hitCount = 0

cy.route2('/someRoute', (req) => {
	hitCount++
	switch (hitCount) {
		case 1: // do something
		case 2: // do something else
		default: // do something for all further requests
	}
})
```
