### ISSUE TITLE
Don't make multiple commits when testing new versions of Cypress

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#849]
Currently each CI provider kicks off a build for each distro - but does it by committing to each internal `test` project.

The problem is that this ends up re-running on the each provider N number of times - which creates excessive builds.

<img width="1020" alt="screen shot 2017-10-29 at 11 52 21 pm" src="https://user-images.githubusercontent.com/1268976/32154049-5573b414-bd04-11e7-91de-9abfb16812c1.png">
<img width="598" alt="screen shot 2017-10-29 at 11 51 45 pm" src="https://user-images.githubusercontent.com/1268976/32154050-5596eff6-bd04-11e7-84a7-d0d5867ca874.png">

**Comment by bahmutov** [comment]
Except for piechopper and phonecat (which require starting the server), other projects are "smart" enough to skip building for a different platform. For example Linux binary on Circle skips most of the tests when a new windows or mac binary appears

<img width="901" alt="screen shot 2017-11-03 at 12 14 07 pm" src="https://user-images.githubusercontent.com/2212006/32384298-d2473cba-c090-11e7-8d2a-4be1234ace85.png">

Similar on AppVeyor (windows) and Buildkite (Mac)

<img width="881" alt="screen shot 2017-11-03 at 11 20 37 am" src="https://user-images.githubusercontent.com/2212006/32384311-ddccc474-c090-11e7-8407-a18806ea18de.png">

Remaining: do not bump environment variables in test projects, only use `commit-install-message` there

**Comment by bahmutov** [comment]
all CI builds going through the commit messages, so they are pretty fast if the operating system is not matching
