### ISSUE TITLE
check status code and response body with `experimentalNetworkStubbing`

### ISSUE THREAD

**Issue by bengry** [cypress-io/cypress#8493]
### Current behavior:
I'm unable to validate the response's status code or body when using the `route2` API.

With `cy.route()` the following code would work:
```js
cy.server();
cy.route({ method: 'POST', url: '/api/login' }).as('login');
cy.wait('@login').its('status').should('equal', 200);
```

However, changing to the new `route2` API (after having enabled the `experimentalNetworkStubbing` flag of course) does not work (see test code below).

If I chain a .debug() before the .its() I get an object that looks like this:
```js
{
  id: "interceptedRequest9" // number changes each run
  log: {...},
  request: { headers: { ... }, url: 'https://localhost:3000/api/login', method: 'POST', ... },
  requestWaited: true,
  responseWaited: true,
  state: "Complete"
}
```
which does indeed not have a status property. I'm wondering how I can validate the status code of the response, or even look at it, as well as the response's body.

### Desired behavior:
Waiting on the response should work, and allow inspecting the status code, and  the response's body (previously done via `.its('responseBody')`).

### Test code to reproduce
```js
cy.route2({ method: "POST", url: '/api/login' }).as("login");
cy.wait("@login").its('status').should('equal', 200);
```

### Versions
Cypress 5.1.0
Chrome 85

**Comment by vivekbwaj** [comment]
I am facing the same issue

**Comment by bahunov** [comment]
My question is:
Does 
```
responseWaited: true,
  state: "Complete"
```
it mean that response was awaited until state Complete?

**Comment by sainthkh** [comment]
Sorry for the late reply. 

In the new `cy.intercept()` api (former `cy.route2()`), the status code could be checked with the code below:

```js
// assert that a request to this route received a response with HTTP status 500
cy.wait('@someRoute').its('response.statusCode').should('eq', 500)
```

For more information, please check [the documentation](https://docs.cypress.io/api/commands/intercept.html)
