### ISSUE TITLE
Blobs used as MediaSource references fail to load

### ISSUE THREAD

**Issue by subvertallchris** [cypress-io/cypress#8495]
### Current behavior:

When playing a video using [hls.js](https://github.com/video-dev/hls.js) or what I can assume would be any code that uses a blob + MediaSource, Cypress encounters errors when trying to load. Strangely, the video still plays but it's possible that this is hls.js using some kind of workaround.

You'll see that the page loaded within Cypress, https://hls-js.netlify.app/demo/, does not encounter errors when loading the blob from your own browser.

https://user-images.githubusercontent.com/4097271/92143370-31f94400-ede3-11ea-87b9-c15c05cfb70d.png

### Desired behavior:

When using a blob as a MediaSource reference, the data should load without network errors.

### Test code to reproduce

Please see https://github.com/subvertallchris/cypress-test-tiny/tree/bug/blob-errors. The README file contains the information. Tests do not fail but you can see the errors throughout the Network tab in your inspector.

### Versions

Cypress 4.8+
Chrome 85
Mac OS 10.15.4

**Comment by Bkucera** [comment]
Strange, seems like something is looking at the src of the video tag and making requests for it. Of course the video is a blob: url so the requests fail. I still think hls.js is working as intended since I assume the video tag src is set to the blob url is there and the video is playing.

**Comment by subvertallchris** [comment]
Yeah, hls.js appears to be doing everything correctly.

Could this be related to #8491? Both deal with unexpected failing requests.
