### ISSUE TITLE
After update Cypress 5.1.0，the https request fail in chrome

### ISSUE THREAD

**Issue by candy-Tong** [cypress-io/cypress#8498]
### Current behavior:

I update cypress to 5.1.0，all the https request fail when I use chrome browser that cypress open to test. 
I install the cypress 5.0.0 again, the https request is ok.

### Desired behavior:

the https request is ok.

### Test code to reproduce

1. install cypress 5.1.0 and run command
```
set http_proxy=127.0.0.1:8899 && set https_proxy=127.0.0.1:8899 && cypress open
```
I use [whistle](https://github.com/avwo/whistle). And in whistle, i can not see the https request record. I think the https request has been fail in cypress and it can not reach whistle.

2. use chrome  to test and new tab to access a https page.
![image](https://user-images.githubusercontent.com/20377280/92195405-7e09be80-ee9f-11ea-9065-a5ec52116970.png)

无法访问此网站：Unable to access this site
意外终止了连接：The connection was accidentally terminated

### Versions

cypress 5.1.0, 
win10, 
84.0.4147.89 (正式版本) （64 位） (cohort: 84_Win_89)

**Comment by janhocevar** [comment]
Happened the same to our project when upgrading Cypress. Simple POST HTTP request that passes in version 4.9.0, fails in 5.1.0. Not sure if it helps you, but here is the response:

```
{
  headers: {
    normalizedNames: {},
    lazyUpdate: null,
    headers: {}
  },
  status: 0,
  statusText: "Unknown Error",
  url: "http://localhost:8950/...",
  ok: false,
  name: "HttpErrorResponse",
  message: "Http failure response for http://localhost:8950/...: 0 Unknown Error",
  error: {
    isTrusted: true
  }
}
```

This happened in an Angular project version 9.1.6.

**Comment by BlueWinds** [comment]
Going to close this after a couple years of inactivity and the release of 6 major Cypress versions. If you're still running into problems with a more recent release, please feel free to open a new issue and we'll try to be better about looking at things.
