### ISSUE TITLE
cy.route2() with delay Option Fails Often

### ISSUE THREAD

**Issue by todd-m-kemp** [cypress-io/cypress#8504]
### Current behavior:

When using `cy.route2()` with a delay (with `experimentalNetworkStubbing` enabled of course 😄 ), I keep getting errors about `res.delay` not being a function.

I am following the example provided [here](https://docs.cypress.io/api/commands/route2.html#Simulate-delay) with the required alteration noted [here](https://github.com/cypress-io/cypress/issues/8489#issuecomment-686526821) that I should be using `res` and not `req`. If I am somehow misinterpreting that comment, please let me know.

### Desired behavior:

`cy.route2()` with the delay option consistently does not throw errors.

### Test code to reproduce

```js
context('Apple', function () {
  beforeEach(function () {
      cy.route2(`https://www.apple.com/search-services/suggestions/defaultlinks/`, (res) => {res.delay(5000)}).as('getLinkOptions');
      cy.visit('https://www.apple.com/ca/');
    });

  it('Using delay with cy.route2()', function () {
    cy.title()
      .should('contain', 'Apple')
  });
});
```

This test will fail often, though not every time.

![image](https://user-images.githubusercontent.com/62152998/92241844-e4391600-ee8c-11ea-90ee-64dee4fcdb0f.png)

Without using `res) => {res.delay(5000)}` the test seems to pass every time.

### Versions

Cypress version 5.1.0 on macOS 10.14.6 with Chrome 85.

**Comment by flotwig** [comment]
Glad that you are using the experimental network stubbing :)

To access the `res` object, you first need to send the request outgoing with `req.reply`, then you can receive `res` in the callback.

Your example:

>       cy.route2(`https://www.apple.com/search-services/suggestions/defaultlinks/`, (res) => {res.delay(5000)}).as('getLinkOptions');

should be:

>       cy.route2(`https://www.apple.com/search-services/suggestions/defaultlinks/`, (req) => 
>         req.reply(res => 
>           res.delay(5000)
>         )
>       ).as('getLinkOptions')

Once #8109 is merged, it will make it possible to throttle/delay the response without sending an outgoing request as well.

**Comment by todd-m-kemp** [comment]
Thank you @flotwig ! That was definitely not clear from the documentation that is available at the moment. I am glad to hear that things will be getting updated soon in #8109 ; this should better match what is currently documented. 😄
