### ISSUE TITLE
Cypress 5.X tests are hanging when using "host" only baseUrl without domain extension (headless Chrome and Electron)

### ISSUE THREAD

**Issue by DanailMinchev** [cypress-io/cypress#8508]
### Current behavior:

Using **cypress/included:5.0.0** Docker image and Docker Compose to run the tests with **Electron** browser,
the tests are hanging indefinitely when navigating to the app using the internal Docker DNS of the app.

### Desired behavior:

The tests should not hang when using **Electron** browser and Docker with the internal docker DNS name.
The old Cypress version `4.12.1` was working fine.

### Test code to reproduce

Repository to reproduce the problem: https://github.com/DanailMinchev/cypress-docker-compose-bug
Please see the README how to reproduce: https://github.com/DanailMinchev/cypress-docker-compose-bug/blob/master/README.md

I suspect that this can be related to the upgrade of the Electron browser which changed between versions

### Versions

Cypress 5.X with Docker and Docker Compose

**Comment by DanailMinchev** [comment]
Looks like it doesn't work when we use host-only `baseUrl` (without domain).

For example:
- the tests are hanging if `baseUrl` is set to `http://app/`
- the tests are executed successfully if `baseUrl` is set to `http://app.local/`

It is failing now in Chrome headless as well since Cypress 5.3.0

**Comment by DanailMinchev** [comment]
Probably related issue - https://github.com/cypress-io/cypress/issues/5912

**Comment by BlueWinds** [comment]
Going to close this after a couple years of inactivity and the release of 6 major Cypress versions. If you're still running into problems with a more recent release, please feel free to open a new issue and we'll try to be better about looking at things.
