### ISSUE TITLE
Error on not finding `cy.focused()` is not very clear.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#851]
- Cypress Version: 1.0.3

### Current behavior:
If Cypress does not find a focused element, it displays this error: `Expected to find element: 'focused', but never found it.`

<img width="475" alt="screen shot 2017-10-30 at 12 41 33 pm" src="https://user-images.githubusercontent.com/1271364/32183521-eae812ae-bd6f-11e7-8163-bbfb40299834.png">

### Desired behavior:

We could probably improve this error to say it could not find any DOM element with focus or something. I'm not sure where this string 'focused' comes from essentially.

### How to reproduce:
`cy.focused()` on app with no focused el.

### Additional Info (images, stack traces, etc)
cy.focused() code: https://github.com/cypress-io/cypress/blob/issue-803/packages/driver/src/cy/commands/querying.coffee#L26

**Comment by brian-mann** [comment]
It's because `focused` borrows querying code from elsewhere which is bound to that type of error message.

The problem is that if there is no element in focus then there's really nothing to print about the element.

What error message would you like?

**Comment by jennifer-shehane** [comment]
Yeah, so when it finds no element - and their assertion does not conflict with this state, have a specific error message that says:

```
Expected to find an element with focus, but never found it.
```

It's really the `to find element: 'focused'` that seems weird.
