### ISSUE TITLE
Not able to use the variables of first super domain after visiting second super domain even after declaring the variables globally

### ISSUE THREAD

**Issue by hbuddaraju-CLGX** [cypress-io/cypress#8517]
### Current behavior:

I am visiting two super domains in different it blocks and fetching some text in each super domain then storing each text in different global variables. When trying to display those variables, not getting the text from variable of first super domain.

### Desired behavior:

As the variables are declared global they must be having access to entire spec, irrespective of different super domains.

### Test code to reproduce
```js
let var1, var2
describe('Test ', function () {
    it('Get value from first superdomain and store it in a global variable', function () {
        cy.viewport(1480, 1280)
        cy.visit('https://www.google.com')
        cy.contains('Gmail').then($text1 => {
            var1 = $text1.text()
        })
    })
    it('Display superdomain1 variable value', function () {
        cy.log(var1)
    })
    it('Get value from second superdomain and store it in another global variable', function () {
        cy.viewport(1480, 1280)
        cy.visit('https://github.com/')
        cy.get('a[href="/login"]').then($text2 => {
            var2 = $text2.text()
        })
    })
    it('Display superdomain2 variable value', function () {
        cy.log(var2)    
    })
    it('Display both superdomain variable values', function () {
        cy.log(var1)// no text is getting displayed
        cy.log(var2)// working as expected
    })
})
```
### Versions

Cypress 5.1.0
Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Windows 10 64bit

**Comment by hbuddaraju-CLGX** [comment]
Can anyone please update me on this?

**Comment by jennifer-shehane** [comment]
See this workaround: https://docs.cypress.io/api/commands/task.html#Save-a-variable-across-non-same-origin-URL-visits
