### ISSUE TITLE
getVideoPlaybackQuality function returns empty object for video element

### ISSUE THREAD

**Issue by viraxslot** [cypress-io/cypress#8519]
### Current behavior:
Function [getVideoPlaybackQuality](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/getVideoPlaybackQuality) for video element returns {}

### Desired behavior:
It should return [VideoPlaybackQuality](https://developer.mozilla.org/en-US/docs/Web/API/VideoPlaybackQuality) object, example in DevTools with the [same site](https://webrtc.github.io/samples/src/content/capture/video-video/)
![image](https://user-images.githubusercontent.com/20737672/92477043-999aff00-f1e8-11ea-89cb-502dd0927def.png)

### Test code to reproduce
```javascript
context('Video test', () => {
    beforeEach(() => {
        cy.visit('https://webrtc.github.io/samples/src/content/capture/video-video/');
    });

    it('video test', () => {
        const leftVideo = '#leftVideo';
        cy.contains('WebRTC samples');

        cy.get(leftVideo).then(($video) => {
            const video = $video.get(0);
            video.muted = true;
            video.play();

            cy.wait(2000);

            cy.log(video.videoWidth);
            cy.log(video.videoHeight);
            cy.log(video.getVideoPlaybackQuality());
        });
    });
});

```
Result
![image](https://user-images.githubusercontent.com/20737672/92477004-8720c580-f1e8-11ea-8483-05b99f6f3b4f.png)

### Versions
Cypress 5.1.0
Chrome 85 
MacOS Catalina 10.15.6

**Comment by bahmutov** [comment]
Cy log prints an empty object because the video object does not have own enumerable properties

```js
console.log(Object.getOwnPropertyNames(video.getVideoPlaybackQuality()))
// []
```

Thus Cypress log gets an empty object. You can pick your own properties to print using Lodash

```js
cy.log(Cypress._.pick(video.getVideoPlaybackQuality(),
  ['corruptedVideoFrames', 'creationTime', 'droppedVideoFrames', 'totalVideoFrames']));
```

BUT this will print `Object{4}` since Cypress automatically collapses objects with more than two properties. So the best scenario here is to stringify the object before printin

```js
cy.log(JSON.stringify(Cypress._.pick(video.getVideoPlaybackQuality(),
  ['corruptedVideoFrames', 'creationTime', 'droppedVideoFrames', 'totalVideoFrames'])));
```

![image](https://user-images.githubusercontent.com/2212006/92480386-d1874f80-f1b2-11ea-993b-0ae7687e5ef5.png)

**Comment by viraxslot** [comment]
@bahmutov thanks a lot!
