### ISSUE TITLE
Reduce Memory Usage with window.gc()

### ISSUE THREAD

**Issue by CoryDanielson** [cypress-io/cypress#8525]
I recently discovered that a method can be exposed in Chrome and Electron to trigger garbage collection, and it seems to improve memory consumption significantly during test runs.

**I'm wondering if adding this functionality to cypress by default (rather than a plugin) would be worthwhile, to hopefully reduce the number of crashes and improve performance.**

| Browser | Flag/Switch |
|----|----|
| Chrome | --js-flags=--expose-gc |
| Electron | --js-flags=--expose_gc |

Once enabled, you can simply call `window.gc()` within javascript code.

I ran the same Cypress test with and without calling `window.gc()` in a global `afterEach` and [saw a **30-50%** reduction in peak memory usage](https://github.com/cypress-io/cypress/issues/350#issuecomment-688969443) from the same tests.

I suspect that this will also reduce the number of crashes due to hitting the max memory. For a large and complex app with lots of requests, I think the CPU is too busy and never has the downtime required for javascripts garbage collector to clean up stale references. GC does occur occasionally, but not often enough, and that eventually becomes a fatal mistake as the cypress process gets closer to the max memory threshold and GC is not run. In my case, starting a new test could increase memory usage by 100-300mb, and put the app over the 2gb limit.

To enable `win.gc()` for election, run cypress with the following with this environment variable set:

```console
ELECTRON_EXTRA_LAUNCH_ARGS=--js-flags=--expose_gc cypress run
```

**cypress/plugins/index.js**

* enable `win.gc()` for chrome

```js
// enables win.gc() for chrome

module.exports = (on, config) => {
	on('before:browser:launch', (browser, launchOptions) => {
		if (browser.name === 'chrome') {
			// exposes window.gc() function that will manually force garbage collection
			launchOptions.args.push('--js-flags=--expose-gc');
		}

		return launchOptions;
	});
};
```

**cypress/support/index.js**

```js
afterEach(() => {
	cy.window().then(win => {
		// window.gc is enabled with --js-flags=--expose-gc chrome flag
		if (typeof win.gc === 'function') {
			// run gc multiple times in an attempt to force a major GC between tests
			win.gc();
			win.gc();
			win.gc();
			win.gc();
			win.gc();
		}
	});
});
```

**Comment by CoryDanielson** [comment]
I have not been able to find a way to expose the garbage collector in Edge or FireFox. In the past there were a lot of different APIs for causing GC - the documentation around all of them is pretty sparse, or no longer exists.
- https://www.npmjs.com/package/js-gc
- https://github.com/natewatson999/js-gc/blob/master/index.js

It's possible to "force" garbage collection by manually increasing memory pressure (creating tons of objects/keys). It's probably going to be slower though. I'm not sure if this is worth implementing as a fallback, but it may provide some benefit for browsers where the a GC method is not available.
- https://github.com/WebKit/webkit/blob/89c28d471fae35f1788a0f857067896a10af8974/LayoutTests/http/wpt/resources/gc.js

**Comment by CoryDanielson** [comment]
There's a chance that tests for low-memory apps would run slower with this, because calling `gc` is expensive.

I'm not sure if high memory apps also run slower too, in my case the tests would crash vs not crash so the performance hit was not noticeable.

**Comment by flotwig** [comment]
> There's a chance that tests for low-memory apps would run slower with this, because calling `gc` is expensive.

@CoryDanielson that's the reason why forced GC has not been implemented in Cypress as a whole - it is expensive, and causes user tests to pause/stutter during garbage collection.

When Cypress initially introduced Firefox support, code was introduced that used the Firefox driver protocol to force garbage collection after tests (`Cypress.on('test:before:run:async', ...)`). This was necessary because Firefox <= 79 had a memory leak that was not getting GC'd properly unless we manually forced GC: https://docs.cypress.io/guides/references/configuration.html#firefoxGcInterval

You can manually trigger the Firefox GC routine (even in FF >= 80) by using `Cypress.backend('firefox:force:gc')`.

The reason why forced GC was removed as soon as Firefox 80 became available was because it was causing user tests to run much more slowly than if we didn't force GC.

With this in mind, I still think that the functionality you're proposing is a good idea, because users do run into memory issues that can be helped with the use of forced GC. However, it is probably better-suited to being a user plugin than to being in Cypress core.

**Comment by CoryDanielson** [comment]
Thanks for the info! Does it make sense to expose chrome/electron gc in the same way as FF, or are you planning on removing the `firefox:force:gc` feature?

**Comment by flotwig** [comment]
`firefox:force:gc` will be around for the foreseeable future, since people will still be using versions of Firefox older than 80 for a while. 

If you want to, you can open up a PR to add the `--expose-gc` flag by default, it doesn't seem to have any side-effects. Or users can pass `ELECTRON_EXTRA_LAUNCH_ARGS=--expose-gc` if they want to use `window.gc` in Electron.

Closing since this feature request will not be implemented in Cypress core.

**Comment by bahunov** [comment]
> I recently discovered that a method can be exposed in Chrome and Electron to trigger garbage collection, and it seems to improve memory consumption significantly during test runs.
> 
> **I'm wondering if adding this functionality to cypress by default (rather than a plugin) would be worthwhile, to hopefully reduce the number of crashes and improve performance.**
> 
> Browser	Flag/Switch
> Chrome	--js-flags=--expose-gc
> Electron	--js-flags=--expose_gc
> Once enabled, you can simply call `window.gc()` within javascript code.
> 
> I ran the same Cypress test with and without calling `window.gc()` in a global `afterEach` and [saw a **30-50%** reduction in peak memory usage](https://github.com/cypress-io/cypress/issues/350#issuecomment-688969443) from the same tests.
> 
> I suspect that this will also reduce the number of crashes due to hitting the max memory. For a large and complex app with lots of requests, I think the CPU is too busy and never has the downtime required for javascripts garbage collector to clean up stale references. GC does occur occasionally, but not often enough, and that eventually becomes a fatal mistake as the cypress process gets closer to the max memory threshold and GC is not run. In my case, starting a new test could increase memory usage by 100-300mb, and put the app over the 2gb limit.
> 
> To enable `win.gc()` for election, run cypress with the following with this environment variable set:
> 
> ```
> ELECTRON_EXTRA_LAUNCH_ARGS=--js-flags=--expose_gc cypress run
> ```
> 
> **cypress/plugins/index.js**
> 
> * enable `win.gc()` for chrome
> 
> ```js
> // enables win.gc() for chrome
> 
> module.exports = (on, config) => {
> 	on('before:browser:launch', (browser, launchOptions) => {
> 		if (browser.name === 'chrome') {
> 			// exposes window.gc() function that will manually force garbage collection
> 			launchOptions.args.push('--js-flags=--expose-gc');
> 		}
> 
> 		return launchOptions;
> 	});
> };
> ```
> 
> **cypress/support/index.js**
> 
> ```js
> afterEach(() => {
> 	cy.window().then(win => {
> 		// window.gc is enabled with --js-flags=--expose-gc chrome flag
> 		if (typeof win.gc === 'function') {
> 			// run gc multiple times in an attempt to force a major GC between tests
> 			win.gc();
> 			win.gc();
> 			win.gc();
> 			win.gc();
> 			win.gc();
> 		}
> 	});
> });
> ```

Thanks alot @CoryDanielson  !! I tried this fix in our jenkins-docker pipeline.. it seem to have fixed the stuck runs.

**Comment by CoryDanielson** [comment]
> @CoryDanielson how can I check that flag is set in browse?

If it's working properly you can open the browse and type "`window.gc`" into the console. It should display a function.
![Screen Shot 2021-02-05 at 5 30 06 PM](https://user-images.githubusercontent.com/1461792/107096028-d12dc780-67d7-11eb-8411-104778acbba0.png)

**Comment by MarcusElevait** [comment]
> I recently discovered that a method can be exposed in Chrome and Electron to trigger garbage collection, and it seems to improve memory consumption significantly during test runs.
> 
> **I'm wondering if adding this functionality to cypress by default (rather than a plugin) would be worthwhile, to hopefully reduce the number of crashes and improve performance.**
> 
> Browser	Flag/Switch
> Chrome	--js-flags=--expose-gc
> Electron	--js-flags=--expose_gc
> Once enabled, you can simply call `window.gc()` within javascript code.
> 
> I ran the same Cypress test with and without calling `window.gc()` in a global `afterEach` and [saw a **30-50%** reduction in peak memory usage](https://github.com/cypress-io/cypress/issues/350#issuecomment-688969443) from the same tests.
> 
> I suspect that this will also reduce the number of crashes due to hitting the max memory. For a large and complex app with lots of requests, I think the CPU is too busy and never has the downtime required for javascripts garbage collector to clean up stale references. GC does occur occasionally, but not often enough, and that eventually becomes a fatal mistake as the cypress process gets closer to the max memory threshold and GC is not run. In my case, starting a new test could increase memory usage by 100-300mb, and put the app over the 2gb limit.
> 
> To enable `win.gc()` for election, run cypress with the following with this environment variable set:
> 
> ```
> ELECTRON_EXTRA_LAUNCH_ARGS=--js-flags=--expose_gc cypress run
> ```
> 
> **cypress/plugins/index.js**
> 
> * enable `win.gc()` for chrome
> 
> ```js
> // enables win.gc() for chrome
> 
> module.exports = (on, config) => {
> 	on('before:browser:launch', (browser, launchOptions) => {
> 		if (browser.name === 'chrome') {
> 			// exposes window.gc() function that will manually force garbage collection
> 			launchOptions.args.push('--js-flags=--expose-gc');
> 		}
> 
> 		return launchOptions;
> 	});
> };
> ```
> 
> **cypress/support/index.js**
> 
> ```js
> afterEach(() => {
> 	cy.window().then(win => {
> 		// window.gc is enabled with --js-flags=--expose-gc chrome flag
> 		if (typeof win.gc === 'function') {
> 			// run gc multiple times in an attempt to force a major GC between tests
> 			win.gc();
> 			win.gc();
> 			win.gc();
> 			win.gc();
> 			win.gc();
> 		}
> 	});
> });
> ```

I exactly tried this and i also tried to set the ELECTRON_EXTRA_LAUNCH_ARGS=--js-flags=--expose_gc with export on my linux system, but neither can i use window.gc in the developer tools console nor does the gc work on the tests.
I'm using chrome version: 104.0.5112.101 (Official Build) (64-bit) 
Does anyone of you know if this is not supported by chrome anymore?

**Comment by bahunov** [comment]
Yes, win.gc() definitely helped me too.

**Comment by CoryDanielson** [comment]
> actly tried this and i also tried to set the ELECTRON_EXTRA_LAUNCH_ARGS=--js-flags=--expose_gc with export on my linux system, but neither can i use window.gc in the developer tools console nor does the gc work on the tests.
> I'm using chrome version: 104.0.5112.101 (Official Build) (64-bit)
> Does anyone of you know if this is not supported by chrome anym

window.gc still works fine for me in Chrome 104

<img width="1135" alt="Screen Shot 2022-08-30 at 12 48 59 PM" src="https://user-images.githubusercontent.com/1461792/187494304-c0c950e7-272c-4532-b4ed-67633b2b1cd8.png">

**Comment by CoryDanielson** [comment]
@MarcusElevait in the latest version of Cypress, **cypress/plugins/index.js** does not work the same as it used to. If you copy/pasted the code from this ticket into plugins/index.js that may be the problem

See https://docs.cypress.io/guides/references/migration-guide#Plugins-File-Removed

**Comment by JohnSmithyy** [comment]
What is the command to collect garbage in chrome 105? Window/win.gc() no longer work for me :?

**Comment by CoryDanielson** [comment]
@JohnSmithyy `window.gc()` works fine for me in Chrome 105. Have you followed the steps from the [original post in this thread](https://github.com/cypress-io/cypress/issues/8525#issue-696149834) to enable `window.gc()`?


<img width="811" alt="Screen Shot 2022-08-30 at 11 00 53 PM" src="https://user-images.githubusercontent.com/1461792/187583306-52cb3172-b1b4-43f9-99a3-ebc1ff479e9c.png">

**Comment by JohnSmithyy** [comment]
> @JohnSmithyy `window.gc()` works fine for me in Chrome 105. (see screenshot below)
> 
> Have you followed the steps from the [original post in this thread](https://github.com/cypress-io/cypress/issues/8525#issue-696149834) to enable `window.gc()`?
> 
> <img alt="Screen Shot 2022-08-30 at 11 00 53 PM" width="811" src="https://user-images.githubusercontent.com/1461792/187583306-52cb3172-b1b4-43f9-99a3-ebc1ff479e9c.png">

I have and i get undefined errors but my cypress still crashes too :/

**Comment by CoryDanielson** [comment]
You'll have to debug and see if that plugin change to enable GC is being run, as you expect.

I'm on Cypress 9.3 still, so I can't give you exact code for how to load it in Cypress 10

**Comment by CoryDanielson** [comment]
You may want to file a bug for window.gc not working. If you're using the code I provided in this GitHub threat, it should work in Cypress 9 and below, but I don't know the exact code for Cypress 10

**Comment by MarcusElevait** [comment]
Okay now i managed to make it work. I guess it just works with cypress run, not with cypress open, right? 
So we're using nx to run our cypress tests and i always tried it with the --watch option. But without it, it works fine. 

Thanks for the help here. 
Maybe some smaller related question. If i want every spec file to run the gc command after each test, is there a way to configure this? I don't want to add the afterEach in every spec file.

**Comment by CoryDanielson** [comment]
It works with Cypress open too. Maybe try `-b chrome`?

**Comment by MarcusElevait** [comment]
This was the command i've tried `ELECTRON_EXTRA_LAUNCH_ARGS=--js-flags=expose_gc nx e2e explorait-e2e --browser=chrome --watch` and it didn't work.

With this it worked `ELECTRON_EXTRA_LAUNCH_ARGS=--js-flags=expose_gc nx e2e explorait-e2e --browser=chrome`

But it's fine for me, i don't need it in the watch mode.

**Comment by CoryDanielson** [comment]
@MarcusElevait ELECTRON_EXTRA_LAUNCH_ARGS are for electron, not Chrome. Electron is a different browser. To set these flags for Chrome, you'll need to do it in your cypress.config.js (for Cypress 10)

Based on [this example](https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless), it should look something like this
```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
    // setupNodeEvents can be defined in either
    // the e2e or component configuration
    e2e: {
        setupNodeEvents(on, config) {
            on('before:browser:launch', (browser = {}, launchOptions) => {
                // Chrome is used by default for `cypress open`
                // Electron is used for `cypress run` but the command line flags are modified by ELECTRON_EXTRA_LAUNCH_ARGS environment variable
                if (browser.name === 'chrome') {
                    // exposes window.gc() function that will manually force garbage collection
                    launchOptions.args.push('--js-flags=--expose-gc');
                }

                return launchOptions;
            })
        }
    }
})
```

**Comment by MarcusElevait** [comment]
@CoryDanielson so much thanks for your help. I finally managed to make it work for our project and it really helps us a lot with damn bitbucket pipelines ;-)

**Comment by praveenpandey02** [comment]
This was my plan B. Nice thread!

**Comment by CoryDanielson** [comment]
My browser still crashed even with window.gc being called. I ran all my tests with `cypress open` and it crashed after a few minutes. We don't have any issues with our tests running in Jenkins/CI where they are parallelized though.

Really just need to avoid this issue with the specific Chrome versions, until it's fixed by Chrome.

**Comment by praveenpandey02** [comment]
I believe it is not a good idea to run all your tests in `cypress open`. It is actually not meant for it. I tried with a very simple solution first which was: break my spec file into smaller ones will less `it` blocks in them. Memory is flushed out when spec files are loaded but not when individual `it` blocks are loaded.
