### ISSUE TITLE
Unable to select a file from explorer

### ISSUE THREAD

**Issue by mansiadoshi** [cypress-io/cypress#8528]
### Current behavior:

After I click a button, it opens file explorer. Currently I am unable to select a file without manually selecting the file to upload from the explorer.

### Desired behavior:

I want to write a test that selects the file from the explorer and click Open from Explorer or double click to add that file .

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Cypress can only interact with the website, not the OS explorers. To test uploading files, [`cypress-file-upload`](https://www.npmjs.com/package/cypress-file-upload) can be a good solution.
