### ISSUE TITLE
cy.intercept() logs do not display as expected

### ISSUE THREAD

**Issue by vivekbwaj** [cypress-io/cypress#8540]
```javascript
describe("Test mocking of api requests using route2", () => {
    it("Launch Website and mock meta.json api using route2", () => {
        cy.fixture("meta.json").as("meta.json.mock.response");
        // cy.route2("GET","**/meta.json","@meta.json.mock.response");
        cy.route2(
            "GET",
            "**/meta.json",
            `{
            "loggedIn": true,
            "displayName": "vivek",
            "clubActive": false,
            "flybuysLinked": false,
            "cartItemCount": "100",
            "wishlistItemCount": 1,
            "messageCount": 0
        }`
        );
        homePage.navigateToUrl("https://www.catch.com.au/");
        //WHEN PAGE IS LOADED THE CART COUNT SHOULD BE = 100
    });
});
```

So couple of issues here:
1) When I supply the mock json file using alias, the mocking of "/meta.json" doesn't happen. However when I supply the whole response body it works.
2) As can be seen in the attached image, when the mocking happens by supplying the response explicitly, the time travel doesn't indicate it as a (xhr stub)

![](https://user-images.githubusercontent.com/20886136/92688426-a5b9c480-f380-11ea-9530-4304457124e3.PNG)
});

**Comment by GCHQDeveloper911** [comment]
Without knowing for sure it looks to me like route2 simply isn't intercepting the request. This looks similar to a problem I'm finding:
```
  beforeEach(() => {
    cy.visit('http://localhost:9005')
    cy.injectAxe();
  })

let url1 = 'http://localhost:7777/something'
let url2 = 'https://some.domain/url/path'

it('Mocks Signatory unavailability', function () {
    cy.route2(url1, {statusCode: 500, body: {some: 'response'}}); //this gets intercepted and rejected with a 500
    cy.route2(url2, {statusCode: 500, body: {some: 'response'}}); //this doesn't get intercepted and the usual request from some.domain gets processed as normal
});
```
FWIW - In my scenario, 'GET' calls to both url1 and url2 show as type 'fetch'. 

I know that route2 is experimental, but could someone investigate the cause of these two similar issues please and if appropriate, explain where @vivekbwaj and I are going wrong? Or are we right in thinking route2 isn't successfully intercepting all calls?

**Comment by GCHQDeveloper911** [comment]
Just seen this: https://github.com/cypress-io/cypress/issues/8487 .... Certainly I think that explains my comment above, not sure if @vivekbwaj 's issue above is linked or not.

**Comment by flotwig** [comment]
@vivekbwaj (1) is expected - `cy.route2` does not support stubbing by fixture alias. The new way to do that would be like this:

```js
cy.fixture("meta.json").then(json => {
	cy.route2("GET", "**/meta.json", json)
})
```

In general, we are trying to move away from using aliases in cases where plain Javascript objects would work just as well.

---

For (2), can you clarify what the expected behavior is?

**Comment by vivekbwaj** [comment]
Thanks so much @flotwig , this worked perfectly.
wrt the second part, the issue is that in the time travel window if an xhr is stubbed it shows (xhr stub). However even on successfully stubbing using the solution you provided the time travel window doesn't depict that the request has been stubbed. As you can see in the attached snapshot it simply says (xhr) for /meta.json call. It should depict (xhr stub)

<img width="940" alt="route2Issue" src="https://user-images.githubusercontent.com/20886136/92823236-663ab900-f410-11ea-8b76-2dc3f30f2767.PNG">

**Comment by flotwig** [comment]
@vivekbwaj Ok, thank you for clarifying. We do plan on improving the logging experience around `cy.route2` in a future release, so I will keep this issue open to track that.

**Comment by vivekbwaj** [comment]
Thanks @flotwig

**Comment by flotwig** [comment]
Created issue to track specific implementation https://github.com/cypress-io/cypress/issues/14843
