### ISSUE TITLE
Cypress Runner doesn't show options to run in different browsers on Windows 8

### ISSUE THREAD

**Issue by gitbhat** [cypress-io/cypress#8541]
### Current behavior:

Cypress Runner doesn't show options to run in different browsers 

### Desired behavior:

once we get the Test runner , on the right hand side we see a drop down which allows us to select different browsers but i dont see this option 

Set up:
refering to the below link 
https://docs.cypress.io/guides/references/troubleshooting.html#Windows

i see that my program files have the chrome exe in the expected path, this has not solved the issue

Screen shots are attached 
[
![cypress runner](https://user-images.githubusercontent.com/52409950/92692754-3e8d1780-f362-11ea-8d0b-92c1a1bb5704.JPG)
![chrome](https://user-images.githubusercontent.com/52409950/92692756-4056db00-f362-11ea-9293-f3eae7be0b70.JPG)

](url)

**Comment by JorgeRamosZavala** [comment]
I am having the exact same problem and I have spent so many hours on this because I need to run a  script headed using chrome from CI, by any chance are you opening it from another server?
For me when I run the command to open cypress locally works just fine and i see chrome but when I run the exact same command from Jenkins then I only see Electron listed

**Comment by gitbhat** [comment]
> I am having the exact same problem and I have spent so many hours on this because I need to run a script headed using chrome from CI, by any chance are you opening it from another server?
> For me when I run the command to open cypress locally works just fine and i see chrome but when I run the exact same command from Jenkins then I only see Electron listed

i run it from the test runner directly, but when i tried to run using command headless it worked but headed didn't work for me

**Comment by bahmutov** [comment]
Cypress tries to detect the installed browsers (it comes only with Electron), and if it cannot detect a browser, it is not listed. Could you look at the advice we give for launching browsers and try debugging it https://docs.cypress.io/guides/references/troubleshooting.html#Launching-browsers

**Comment by gitbhat** [comment]
i tried this and i got the below error , i have all browsers in the system still i get this error , can some one help

[
![error](https://user-images.githubusercontent.com/52409950/93302757-1bf27700-f818-11ea-80f4-265eebc530f2.JPG)
](url)

**Comment by bahmutov** [comment]
Please read our debugging browser detection guide and run Cypress with those flags and paste here the debug log https://github.com/cypress-io/cypress/issues/8541#issuecomment-692961334

**Comment by JorgeRamosZavala** [comment]
> Cypress tries to detect the installed browsers (it comes only with Electron), and if it cannot detect a browser, it is not listed. Could you look at the advice we give for launching browsers and try debugging it https://docs.cypress.io/guides/references/troubleshooting.html#Launching-browsers

In my case I just solved it by adding **C:\\Windows\\System32\\wbem** in my PATH in Jenkins using withEnv, I do have it in the environment variables of the remote server but for some reason that alone did not work.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by sunilkumar-git14** [comment]
i tried this and i got the below error , i have all browsers in the system still i get this error , can some one help

![image](https://user-images.githubusercontent.com/71269904/159275579-ce42b1ea-c03a-4217-86e6-e64af518e131.png)

**Comment by nik-hil1995** [comment]
@jennifer-shehane, i have installed cypress freshly and facing the same issue again, i have tried below step for this 

- Open test runner.
- File->view app data.
- delete every thing from here, and relaunch.

**Actual**- not helped me, still showing the same electron browser.

![image](https://user-images.githubusercontent.com/86007988/161427630-d3021cf2-3bd3-40fe-b0b9-9f67c690e40b.png)
