### ISSUE TITLE
Unable to Read Data from the fixture File

### ISSUE THREAD

**Issue by piyush1984** [cypress-io/cypress#8542]
I have used the following code to read the data from the example.json file from the fixture folder

**before(function ()** {
  // "this" points at the test context object
  
  **cy.fixture('example').then(function(data)** {
             this.data = data
    })
})

I am getting the following error while executing the code

Cannot read property 'data' of undefined

Note - I used the before function in the describe block and outside the describe block but same issue exist.
![image](https://user-images.githubusercontent.com/27740418/92748830-8bb5bd00-f353-11ea-80bf-e420b7e99415.png)

Can someone share there thoughts on the same how can this work

Thanks
Piyush

**Comment by bahmutov** [comment]
I am running Cypress v5.2.0

```
before(function () {
  // "this" points at the test context object
  cy.fixture('example').then(function(data) {
    this.data = data
    debugger
  })
})

it('works', () => {})
```

<img width="596" alt="Screen Shot 2020-09-15 at 3 53 52 PM" src="https://user-images.githubusercontent.com/2212006/93258033-b6e14780-f76b-11ea-9041-ad0fd7c49c73.png">

**Comment by lokeshparcel** [comment]
Hi, I have used the following code to read the data from the 'example.json' file from the fixture folder 

describe('My Test suite', function(){

    before(function () {
        cy.fixture('example').then(function(data) {
          this.data = data
        })
      })

beforeEach(function(){
    cy.visit("https://www.google.com");
})

it('Tc-1', function(){
    cy.log("name is"+this.data.name)
    cy.get('.gLFyf').type(this.data.name)
})

it('Tc-2', function(){
    cy.log("name is"+this.data.name)
    cy.get('.gLFyf').type(this.data.name)
})
}) 

'Tc-1' is passed, but for the second test-case 'Tc-2' i am getting the error as 'Cannot read property 'name' of undefined'.
cypress version: 5.2.0
![readData](https://user-images.githubusercontent.com/42172810/93854054-afbdba80-fcd2-11ea-93a0-cc84c43c5a3e.png)
![example](https://user-images.githubusercontent.com/42172810/93854068-b3514180-fcd2-11ea-92ac-653a1a3821a6.png)
![output](https://user-images.githubusercontent.com/42172810/93854077-b77d5f00-fcd2-11ea-9e90-8e18fbde3e2a.png)

Please find the attached screenshot and let me know how to fix this issue. Thank you.

**Comment by bahmutov** [comment]
closing, assuming resolved

**Comment by Rilvi-myob** [comment]
@piyush1984, Have you fixed the issue. if so, could you please share the solution, I am also facing the same sort of issue.

**Comment by rastogi86** [comment]
@Rilvi-myob, If one happens to use arrow function "=>" instead of "function()" in the "it" block, this issue seems to appear.

This might be relevant (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this)

Arrow function expressions
An arrow function expression is a compact alternative to a traditional function expression, but is limited and can't be used in all situations.

Differences & Limitations:

Does not have its own bindings to this or super, and should not be used as methods.

**Comment by Kanak100** [comment]
this is not resolved yet

**Comment by mackoypatz** [comment]
same on my part , unable to read fixture data 

/// <reference types="cypress" />

describe(' My first fixtures', function(){ 

                    before( function() {
                        //access fixture data
                        cy.fixture('example').then(function(data){
                            
                           this.data=data
                    })

        })
    
        it('FixturesDemoTest',() =>
        
         {

            cy.visit('https://demo.nopcommerce.com/login')
            cy.wait(3000)
            cy.get('#Email').type('this.data.email')
            cy.get('#Password').type('this.data.password')
            cy.get('form > .buttons > .button-1').click()

        })

})

this is my example.json
{

   "email": "superhero101@gmail.com",
   "password": "Test@123"

}

**OUTPUT**
it will input "this.data.email' instead of email same goes to password

**Comment by mayurbojappa** [comment]
> 

As suggested above, use function() instead of () => inside the it block

**Comment by Premsing** [comment]
> > 
> 
> As suggested above, use function() instead of () => inside the it block

Nope, doesn't seem to be working for me neither. Take a look at my code.
`describe('Login Feature Validation', () => {

    before(() => {


        cy.fixture('example').then(function (data) {
            globalThis.data = data
        })
    })

    it('Login with correct credentials', function () {

        cy.visit('https://teamworksnew.devitsandbox.com')


        Cypress.on('uncaught:exception', (err, runnable) => {
            return false;
        });

        cy.origin('https://adfs.corpnet.co.in', function () {

            cy.get('#userNameInput').type(globalThis.data.username)
            cy.get('#passwordInput').type(globalThis.data.password)
            cy.get('#submitButton').click()
        })`

Now, checkout the error I am getting.
Cannot read properties of undefined (reading 'username')
![image](https://github.com/cypress-io/cypress/assets/24648098/2516925d-e197-46cd-963d-9efb8282730e)
