### ISSUE TITLE
Cypress.automation is rejected but does not show an error

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8547]
Cypress v5.1.0 with Electron browser on Mac

```js
beforeEach(() => {
  // allow downloads in Electron
  Cypress.automation('remote:debugger:protocol',
    { command: 'Page.setDownloadBehavior',
      params: { behavior: 'allow' } })
})
```

for https://github.com/cypress-io/cypress-example-recipes/issues/560

![blocked](https://user-images.githubusercontent.com/2212006/92779528-20c6af00-f370-11ea-908e-35acaa6d2507.gif)

silently fails and only the DevTools shows an error later in the console

<img width="1013" alt="Screen Shot 2020-09-10 at 2 16 18 PM" src="https://user-images.githubusercontent.com/2212006/92779613-350aac00-f370-11ea-9b8b-5a52d9eefc14.png">

## Proposal

If `Cypress.automation` rejects, fail the test and show the error

**Comment by brian-mann** [comment]
this is not a command - its just a regular promise and it needs to be returned, and then it'll fail the test. all regular promises work this way.

**Comment by brian-mann** [comment]
there's a separate issue i opened not too long ago suggesting we tap into the `unhandledrejection` global event and then possibly fail the test: https://github.com/cypress-io/cypress/issues/8236

it goes way back to another issue i opened years ago: https://github.com/cypress-io/cypress/issues/243

**Comment by bahmutov** [comment]
Workaround
```js
beforeEach(() => {
  // The next command allow downloads in Electron, Chrome, and Edge
  // without any users popups or file save dialogs.
  if (Cypress.browser.name !== 'firefox') {
    // since this call returns a promise, must tell Cypress to wait
    // for it to be resolved
    cy.wrap(
      Cypress.automation('remote:debugger:protocol',
        {
          command: 'Page.setDownloadBehavior',
          params: { behavior: 'allow', downloadPath: downloadsFolder },
        }),
      { log: false }
    )
  }
})
```
