### ISSUE TITLE
cy.clock() is not restting broswer date.

### ISSUE THREAD

**Issue by sanjayupasi** [cypress-io/cypress#8549]
### Current behavior:
cy.clock(Date.UTC(2018, 10, 30), is not restting broswer date to specified one. 

### Desired behavior:
cy.clock(Date.UTC(2018, 10, 30), is expected to reset broswer date to Oct 30, 2018. 

### Test code to reproduce
 cy.clock(Date.UTC(2018, 10, 30), ["Date"]).then(() => {
      cy.log(new Date().toLocaleString());
    });

### Versions
cypress: 5.1, 4.12.1
browser: chrome
os:  ubuntu 16.4

![image](https://user-images.githubusercontent.com/57387252/92788728-d244ff00-f3c7-11ea-9d97-230b31feed9f.png)

**Comment by bahmutov** [comment]
The `cy.clock` sets the clock _in the application's iframe_, not in the spec's iframe. If your website's code calls `new Date()` you would see the date you have set 

- https://example.cypress.io/commands/spies-stubs-clocks
- https://on.cypress.io/clock
