### ISSUE TITLE
Npm run --spec with path to 1 test start every test in integration folders

### ISSUE THREAD

**Issue by sebb94** [cypress-io/cypress#8553]
### Current behavior:
Command npm run cy:run --spec "cypress/integration/examples/login.spec.js" start every test in 2 folders:

![image](https://user-images.githubusercontent.com/23727403/92920465-985d1280-f432-11ea-9c83-2f1e863e487e.png)

![image](https://user-images.githubusercontent.com/23727403/92920358-78c5ea00-f432-11ea-8150-a7a535c8e113.png)

### Desired behavior:

I want to start only 1 test - login.spec.js

### Test code to reproduce

2 folders with some examples inside

npm run cy:run --spec "cypress/integration/examples/login.spec.js"

  "scripts": {
    "cy:open": "cypress open",
    "cy:run": "cypress run"
  },

### Versions

5.1.0

**Comment by jennifer-shehane** [comment]
To run a single spec, it requires you pass the spec arg to the —spec flag. I can see in your screenshot it simply ran ‘cypress run “my/spec.js”, without the —spec flag. This will not work. Update the command to use the —spec flag.
