### ISSUE TITLE
CYPRESS_PROJECT_ID seems to be a reserved environment variable

### ISSUE THREAD

**Issue by stefanbuck** [cypress-io/cypress#8554]
### Current behavior:

I expected that the same way I can pass `CYPRESS_FOO` that `CYPRESS_PROJECT_ID` will also automatically be added to Cypress environment variables. It looks like this is a reserved env, which is not mentioned in the docs. There is only a notice about [CYPRESS_INTERNAL_ENV being reserved](https://docs.cypress.io/guides/guides/environment-variables.html#Option-3-CYPRESS). 

So I guess this is just a documentation issue. However, `PROJECT_ID` is commonly used and therefore might be better to use a different name or even better another "namespace" for such reserved env vars. 

```
CYPRESS_FOO=bar CYPRESS_PROJECT_ID=123
```

```js
Cypress.env('FOO') // => bar
Cypress.env('CYPRESS_PROJECT_ID') // => undefined
```

### Desired behavior:

```
CYPRESS_FOO=bar CYPRESS_PROJECT_ID=123
```

```js
Cypress.env('FOO') // => bar
Cypress.env('CYPRESS_PROJECT_ID') // => 123 
```

### Test code to reproduce

```bash
CYPRESS_PROJECT_ID=123 yarn cypress run
```

```js
cy.should(Cypress.env('PROJECT_ID'), 123);
```

### Versions

Cypress 5.1.0
Node v12.16.1

**Comment by olore** [comment]
I did a little digging. Here is what I found - 

There is a reference to `CYPRESS_PROJECT_ID` in the documentation [here](https://github.com/cypress-io/cypress-documentation/blame/develop/source/guides/dashboard/projects.md#L73) 

Adding it to the "reserved" section on the [page mentioned above](https://docs.cypress.io/guides/guides/environment-variables.html#Option-3-CYPRESS) might be even more confusing.

Maybe adding a warning in the cli similar to CYPRESS_INTERNAL_ENV [here](https://github.com/cypress-io/cypress/blob/develop/cli/lib/cli.js#L355)

I like @stefanbuck's idea on using another namespace for "internal" Cypress variables. I think it would be helpful
