### ISSUE TITLE
Feature request: add ability to assert that a route was not accessed

### ISSUE THREAD

**Issue by unikitty37** [cypress-io/cypress#8556]
### Current behavior:

As documented in #937, I can assert that a route was accessed using

```js
cy.route('http://example.com/', 'EXAMPLE').as('exampleRoute')

// action that should make a request to http://example.com/ here

cy.wait('@exampleRoute')
```

but there does not seem to be a way to assert that the route was *not* accessed, as a timeout causes a failure.

Coming from an RSpec/Capybara/WebMock background, I'm looking for an equivalent to

```ruby
expect(WebMock).not_to have_requested(:get, feed.url)
```

### Desired behavior:

Ideally, I would be able to write something like

```js
cy.wait('@exampleRoute').should('timeout')
```

to indicate that the route is not expected to have been called. 

### Test code to reproduce

(is this applicable for a feature request? :)

### Versions

Cypress: 5.1.0
OS: macOS 10.14.6 (18G6020)
Browser: Vivaldi 3.3.2022.39 (Stable channel) (64-bit)

**Comment by flotwig** [comment]
Hi @unikitty37 this is supported with the `cy.intercept()` API. You can add an intercept and assert it has been called 0 times: 

```js
cy.route('http://example.com/', 'EXAMPLE').as('exampleRoute')

// action that should make a request to http://example.com/ here

cy.get('@exampleRoute.all').should('have.length', 0)
```

**Comment by unikitty37** [comment]
Thanks, but I have a test which calls that route multiple times earlier in the test. Rather than hard-code the number of previous calls, I'd like to get the value of `cy.get('@exampleRoute.all')`'s length before performing the action, then check it's unchanged afterwards.

Of course, the async nature of Cypress makes that a bit more challenging, as `cy.get('@exampleRoute.all').length` comes back as `undefined`.

It seems like the `change` assertion might help, but I can't work out how to useit from the example `expect(fn).to.change(obj, 'val')` — is `fn` a Cypress call, or just a regular JavaScript function, and  is the `val` what it changes *to*, or what it changes *by*?

Coming to Cypress from Ruby and RSpec, the equivalent would be

```
expect { «action» }.not_to change { exampleRoute.length }
```

but is something like that possible with Cypress?
