### ISSUE TITLE
.its() no longer works correctly in v 5.1.0, asserts false even though it is true.

### ISSUE THREAD

**Issue by tmonteith** [cypress-io/cypress#8562]
### Current behavior: 

`cy.its()` no longer correctly finds properties even though it exists on a specified DOM element.

#### v5.1.0 
Error:
<img width="389" alt="Screen Shot 2020-09-12 at 12 12 45 PM" src="https://user-images.githubusercontent.com/22229966/93003202-96a65400-f4f1-11ea-99c1-ed9107061414.png">

#### v5.0.0
Same code, passing:
<img width="385" alt="Screen Shot 2020-09-12 at 12 15 56 PM" src="https://user-images.githubusercontent.com/22229966/93003224-c5bcc580-f4f1-11ea-997e-9b800a660c96.png">

DOM element: 
<img width="515" alt="Screen Shot 2020-09-12 at 12 13 07 PM" src="https://user-images.githubusercontent.com/22229966/93003205-a6259d00-f4f1-11ea-8344-2ab53685f3ce.png">

### Test code to reproduce
I ran this from your https://github.com/cypress-io/cypress-test-tiny example: Running v5.0.0 the test will pass, running v5.1.0 the test will fail.
```js
/// <reference types="cypress" />
describe('page', () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')
    cy.get('li').first().within(($li) => {
      cy.get('a').first().its('role').should('be', 'button')
    })
  })
})
```

### Versions

Cypress v5.1.0, MacOS v10.15.6, Chrome v85

**Comment by jennifer-shehane** [comment]
‘be’ is not an actual assertion, it’s a chainable getter. Chainable getters don’t actually do anything, but they enable you to write clear, english sentences.

You want to replace ‘be’ with an actual assertion like ‘eq’. https://docs.cypress.io/guides/references/assertions.html#BDD-Assertions

This was always incorrectly passing before, regardless of the actual value.
