### ISSUE TITLE
Hardcoded config file names used by `validateFile()` inside `config.get()`

### ISSUE THREAD

**Issue by drptbl** [cypress-io/cypress#8565]
**Versions**
Cypress 5.1.0

This will probably cause issues if someone uses custom config file name (`cypress run --config-file anything.json`):
https://github.com/cypress-io/cypress/blob/1244dd136965bf64235aef087f98e9530b5af3d7/packages/server/lib/config.js#L206-L207

Looks like name of config files are hardcoded, so `validateFile` function won't be triggered on proper file and fail.

**Comment by BlueWinds** [comment]
Going to close this after a couple years of inactivity and the release of 6 major Cypress versions. If you're still running into problems with a more recent release, please feel free to open a new issue and we'll try to be better about looking at things.

**Comment by BlueWinds** [comment]
Going to close this after a couple years of inactivity and the release of 6 major Cypress versions. If you're still running into problems with a more recent release, please feel free to open a new issue and we'll try to be better about looking at things.
