### ISSUE TITLE
FR: verify temp file before attempting download

### ISSUE THREAD

**Issue by Vultraz** [cypress-io/cypress#8570]
This is a pretty niche thing, but I've been banging my head over it for hours. Basically, I'm trying to install the dependencies for a project that includes cypress. For some reason (perhaps due to my connection), the download keeps stalling out. I was able to download the install zip manually after many, *many* attempts, but when I move it to the temp folder (`AppData\Local\temp` for me) and try to run `yarn` again, cypress just overwrites the zip and attempts to download it again. 

Perhaps the download script could run the verification step on the temp file before it attempts to download it again?

**Comment by BlueWinds** [comment]
Going to close this after a couple years of inactivity. If you're still running into problems with a more recent release, please feel free to open a new issue and we'll try to be better about responding to things.
