### ISSUE TITLE
Please, clarify browser multi-browser support

### ISSUE THREAD

**Issue by jradom** [cypress-io/cypress#8573]
Please, clarify browser multi browsers support now and target date support in the future for browsers not supported now.
We need to support
Edge, FF, Chome for Windows and Mac OS  Safari, FF, Chome including all versions of each 6 months back.
Also, are you providing support for the above browsers using Saucelabs or your own cloud grid.  Do you currently have full support for Typescript

Thanks

Jeff

**Comment by flotwig** [comment]
Hi @jradom 

As of Cypress 4.0.0, Edge, Firefox, and Chrome are supported on all platforms.

You can track Safari support here: #6422 

> Also, are you providing support for the above browsers using Saucelabs or your own cloud grid

Currently the browsers run in your CI provider, no Saucelabs or other

> Do you currently have full support for Typescript

Yes

**Comment by jradom** [comment]
I still haven't gotten an answer to this question
"Edge, FF, Chome for Windows and Mac OS Safari, FF, Chome including all versions of each 6 months back."
For example, is Edge "legacy" (not based on Chromium supported), older versions of FF(72, 73, 74, etc), older version of Chrome (75, 76, 77, 78, etc).  Like I said we have a requirement to support all current browser and 6 months back 
Please, let me know


Thanks

Jeff

**Comment by flotwig** [comment]
Non-Chromium Edge is not supported and is not planned to be supported. Yes, all of those versions of FF and Chrome should be supported.
