### ISSUE TITLE
Compression video always reaches 100% CPU and Chrome process isn't released intermittently using Cypress 5.1, Chrome 85, Chrome Driver 85

### ISSUE THREAD

**Issue by tminhtuan** [cypress-io/cypress#8574]
### Current behavior:
When suite's execution is completed. Compression video stage will be processed. This process always reaches 100% CPU (PC: I5, RAM 8G, Window 10)
After some suite are executed completed, Chrome UI is closed successfully but Chrome process still be running. 

### Desired behavior:
CPU Usage should be less than 100%

### Versions

Cypress: 5.1
Chrome: 85
Chrome Driver: 85.0.0
OS: Windows 10, i5, RAM 8G

![image](https://user-images.githubusercontent.com/62825697/93187607-2bb38200-f76a-11ea-91aa-ef63dec95a9d.png)

[IntermittentlyChromeProcessNoteReleased.zip](https://github.com/cypress-io/cypress/files/5223644/IntermittentlyChromeProcessNoteReleased.zip)

**Comment by flotwig** [comment]
@tminhtuan Video compression will always use as much CPU as it can so it can complete as quickly as possible. Check out the `videoCompression` config setting if you'd like to disable compression: https://docs.cypress.io/guides/references/configuration.html#Videos

**Comment by tminhtuan** [comment]
@flotwig thanks so much for your response. And one concern about not being released intermittently of Chrome process? it also used much CPU  and Memory that leads to PC is hung. Hope to receive your response about this. Thanks

**Comment by tminhtuan** [comment]
@flotwig, And one thing i faced today, after some suites were completed, cmd's CPU is always high until cypress was stopped unexpectedly. Could you please help me take a look on this?

![HighCPU](https://user-images.githubusercontent.com/62825697/93307562-51549000-f82b-11ea-93fa-e03322f92047.png)
