### ISSUE TITLE
Not Found Issue with Visit Page

### ISSUE THREAD

**Issue by NilamR** [cypress-io/cypress#8575]
### Not Found:
The requested URL/_/was not found on this server

### Desired behavior: Need Page to Load

 describe("Loading First Page", () => {
    it("Test1", () => {
     
       cy.visit('http://localhost:1234');
       cy.contains('type').click()
     })
  }
![Error](https://user-images.githubusercontent.com/71128391/93188379-3148a200-f741-11ea-9281-9d33a1daedbf.PNG)

**Comment by bahmutov** [comment]
Please fill all information from our [new issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md). Without enough information we cannot investigate and solve the problem

```
<!-- Is this a question? Questions WILL BE CLOSED. Ask in our chat https://on.cypress.io/chat  -->

### Current behavior:

<!-- A description including screenshots, stack traces, DEBUG logs, etc -->

### Desired behavior:

<!-- A clear description of what you want to happen -->

### Test code to reproduce

<!-- If we cannot fully run the tests as provided the issue WILL BE CLOSED -->
<!-- Issues without a reproducible example WILL BE CLOSED -->

<!-- You can fork https://github.com/cypress-io/cypress-test-tiny repo, set up a failing test, then link to your fork -->

### Versions

<!-- Cypress, operating system, browser -->
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
