### ISSUE TITLE
Properties in the cypress.run result type show up as TS errors

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8580]
### Current behavior:
New project with Cypress v5.2.0 (same for v5.1.0) uses `cypress.run` to execute tests, then looks at the resolved object

```js
cypress.run(options)
.then((runResults) => {
  // see https://on.cypress.io/module-api
  if (runResults.failures) {
    console.error(runResults.message)
    process.exit(1)
  }
  ...
})
```

VSCode shows red squiggles all over

![](https://user-images.githubusercontent.com/2212006/93235085-19761b80-f74b-11ea-85d5-e2fb393848b8.png)

![](https://user-images.githubusercontent.com/2212006/93235099-1da23900-f74b-11ea-966e-e1bcfa621772.png)

![](https://user-images.githubusercontent.com/2212006/93235107-20049300-f74b-11ea-8fec-013781826b23.png)

### Desired behavior:
The resolved object has type from https://github.com/cypress-io/cypress/tree/develop/cli/types cypress-npm-api.d.ts

```
interface CypressFailedRunResult {
  failures: number
  message: string
}

run(): Promise<CypressCommandLine.CypressRunResult | CypressCommandLine.CypressFailedRunResult>
```

So I expect checking for properties from one or the other types to work

### Test code to reproduce
Repo https://github.com/bahmutov/cypress-expect
Clone
Install dependencies with `npm i`
Open the `index.js` in VSCode

### Versions
Mac, Cypress v5.2.0

**Comment by alvipeo** [comment]
Just hit this myself!
