### ISSUE TITLE
Cypress detected a cross origin error happened on page load

### ISSUE THREAD

**Issue by lugus** [cypress-io/cypress#8581]
### Current behavior:

I searched but don't find related issue, sorry if it's the case.

After updating to 5.2.0 some tests failed because of:

```
Cypress detected a cross origin error happened on page load:

  > Blocked a frame with origin "https://localhost:8080" from accessing a cross-origin frame.

Before the page load, you were bound to the origin policy:

  > https://localhost:8080
```

### Desired behavior:

Test should pass as before i think, but can be fixed temporarily by disabling chrome security in this case.

### Test code to reproduce

Running test on a domain with specified port i think? Not sure.

### Versions

Cypress: 5.2.0

**Comment by bahmutov** [comment]
Is the test consistently failing now in v5.2.0 but was consistently passing before? (I assume in v5.1.0)?

**Comment by lugus** [comment]
> Is the test consistently failing now in v5.2.0 but was consistently passing before? (I assume in v5.1.0)?

Exactly

**Comment by bahmutov** [comment]
I don't see anything that might affect the `cy.visit` in the [changelog for v5.2.0](https://github.com/cypress-io/cypress/releases/tag/v5.2.0) Is this a public repo or a repo you could share with us?

**Comment by lugus** [comment]
Test older versions and reinstall 5.2.0 => it's now working don't know why 🤷🤔
