### ISSUE TITLE
 Configuration "scale: false" do not work in docker 

### ISSUE THREAD

**Issue by NikitaAmchyslavskyi** [cypress-io/cypress#8585]
### Current behavior:

I am trying to run screenshot tests in docker conteiner
Using the cypress run command in the container
But when specifying the parameter in the configs "scale: false" when executing the test, this field is ignored

### Desired behavior:

"scale: false" should work in a docker container

### Test code to reproduce
here my cypress.json
```json
{
    "integrationFolder": "e2e/integration",
    "fixturesFolder": "e2e/fixtures",
    "testFiles": "**/**/*.e2e.spec.ts",
    "ignoreTestFiles": [
        "**/__snapshots__/*",
        "**/__image_snapshots__/*"
    ],
    "baseUrl": "https://live.dev.testpro.com.ua:4200",
    "viewportHeight": 1020,
    "viewportWidth": 1980,
    "video": false,
    "requestTimeout": 10000,
    "responseTimeout": 60000,
    "defaultCommandTimeout": 10000,
    "env": {
        "cypress-plugin-snapshots": {
            "imageConfig": {
                "threshold": 0.01
            }
        },
        "screenshotConfig": {
            "scale": false
        }
    }
}
```

### Versions

5.0.0

**Comment by bahmutov** [comment]
Can you create a reproducible example showing the problem?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
