### ISSUE TITLE
Is there a workaround other than using API to login a page that uses OKTA redirects to completely different domain on the fly 

### ISSUE THREAD

**Issue by jradom** [cypress-io/cypress#8588]
Is there a workaround other than using API to login into a page that uses OKTA redirects to a completely different domain on the fly and comes back.  And then logs into the site

Please, let me know

Thanks

Jeff

**Comment by bahmutov** [comment]
Not at the moment, and please ask questions like this either in our https://on.cypress.io/chat or by searching our documentation at https://docs.cypress.io
