### ISSUE TITLE
Old issue where Snapshot is missing, config changed to "numTestsKeptInMemory": 51

### ISSUE THREAD

**Issue by jslokker** [cypress-io/cypress#8589]
### Current behavior:

I have a test with two it's and cy.visit(url) and cypress is not storing the first snapshot, only the last one. And the cypress.json contains "numTestsKeptInMemory": 51 (just to be sure that the default value was not the problem)

### Desired behavior:

I want cypress to show the snapshot

### Test code to reproduce

describe("My First Test Suite", function() 
{
    it('My First Test Case', function() {
        cy.visit("https://rahulshettyacademy.com/seleniumPractise/#/");
        
    })

    it("My Second Test Case", function()
    {
        cy.visit("https://www.telegraaf.nl");
    })
})

### Versions

Cypress 5.2.0
Mac OS Catalina 10.15.6
VS Code 1.49.0

**Comment by bahmutov** [comment]
When running your test
```js
it('My First Test Case', function() {
  cy.visit("https://rahulshettyacademy.com/seleniumPractise/#");
})

it("My Second Test Case", function()
{
  cy.visit("https://www.telegraaf.nl");
})
```

Cypress encounters 2 different domains (origins) and has to reload the spec file _completely_ to work with the second origin. This causes the first DOM snapshot to be cleared from memory, thus it is unavailable.

<img width="1440" alt="Screen Shot 2020-09-16 at 4 42 12 PM" src="https://user-images.githubusercontent.com/2212006/93390477-be702180-f83b-11ea-98fc-680b660a36ea.png">

This is a technical limitation in the way Cypress works with origins https://on.cypress.io/trade-offs#Same-origin and you can avoid it by testing these origins from different spec files that you click on from the Desktop GUI (and avoiding "Run all specs" button)
