### ISSUE TITLE
prop or invoke not giving full attribute value

### ISSUE THREAD

**Issue by ratnakarbellary** [cypress-io/cypress#8592]
I have accordion in my appliacation and am checking the collapse and expand functionality based on the class attribute value.

But when try to get the class attribute value using prop or invoke, it is not giving the full value of the attribute instead it is giving only the first value from the attribute.

**Accordion Element:**
`<div class="c-accordion c-accordion-active collapsed" id="accordion">`

**Cypress Code:**
`let accordionstatus = accordion().prop('class')`
`let accordionstatus = accordion().invoke('attr', 'class')`

accordionstatus is having only the first part of the class **"c-accordion"**

expectation: I should get the full attribute value **"c-accordion c-accordion-active collapsed"**

**Comment by bahmutov** [comment]
Please provide the full HTML and test code that we can run ourselves to investigate your issue, since `prop` is not a Cypress command, neither is `accordion()`. Without this code, it is impossible for us to suggest what is going on.

**Comment by ratnakarbellary** [comment]
App Code:

```
<div class="profiler__header">
    <div class="c-accordion c-accordion-active collapsed" id="accordion">
        <div class="container"><div class="row">
            <div class="col-4 col-md-12 c-accordion__heading">Take the quiz <span aria-hidden="true">
                <svg class="c-svg" viewBox="0 0 32 32">
                    <use xlink:href="/build/sprites/sprite.svg#icon_ arrow_ down"></use>
                </svg>
                </span>
            </div>
            </div>
        </div>
    </div>
</div>
```

Cypress Code:

```
cy.get('.profiler__header')
  .find('div')
  .should(($div) => {

    const className = $div[0].className

    console.log("class name: "+ className)
  })
```

When i ran this code am getting only the first part of the class "**c-accordion**".

**_Expectation:_**

It should return full class attribute value "**c-accordion c-accordion-active collapsed**"

Using Cypress Version 5.1.0 on widows 10

**Comment by bahmutov** [comment]
What I think is happening here is that your accordion is not collapsed yet when the code runs since you don't check (assert) for it. I have created a simple test here https://github.com/cypress-io/cypress-fiddle/commit/a8f1e3eb09ae23c1aa6abffba04f59ca894095d9 and it returns the full class name.

<img width="1063" alt="Screen Shot 2020-09-17 at 2 34 35 PM" src="https://user-images.githubusercontent.com/2212006/93512983-25044680-f8f3-11ea-960e-abe1dbde82d7.png">

Suggestion: read https://on.cypress.io/retry-ability and add an assertion around the element to check if it gets the expected class

```
cy.get('#accordion').should('have.class', 'collapsed')
// now you can get the element
  .then($div => {
    // the element is collapsed by this point
    // and the jQuery element should have className
    // with all expected classes
  })
```
