### ISSUE TITLE
unable to upload picture

### ISSUE THREAD

**Issue by akashtippa123** [cypress-io/cypress#8593]
hi 
I am unable to upload a picture with the below code, can anybody help me
installed cypress upload  npm install --save-dev cypress-file-upload
added command  import 'cypress-file-upload';   in  cypress/support/commands.js
Code

it('upload picture', function() {

const yourFiturePath = 'cypress\fixtures\hd4.jpg'                                  //hd4.jpg file is present in the fixture folder
cy.get('.upload-button').attachFile(yourFiturePath)

![tile](https://user-images.githubusercontent.com/61974824/93307198-595a0300-f81e-11ea-939f-05b78f20802f.png)

**Comment by kiranparajuli589** [comment]
:peace_symbol:  We're testing upload successfully like this. Hope this helps:
```js
cy.fixture(pictureName).then((fileContent) => {
      cy.get(this.profileEditIconSelector).attachFile({
        fileContent: fileContent.toString(),
        fileName: pictureName,
        mimeType: 'image/*'
      })
    })
```

**Comment by akashtippa123** [comment]
yes I tried this before, this won't work it not giving any error but the picture is not uploaded

**Comment by bahmutov** [comment]
Seems the original error is coming from `cypress-file-upload` plugin and not from Cypress. Please open an issue in the plugin's repo and maybe ask a question in the chat at https://on.cypress.io/chat
