### ISSUE TITLE
Hooks should either allow config browser options or error nicely

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8594]
Cypress v5.1.0

After using `context('no firefox', {browser: '!firefox'}, () => {...})` I noticed that my `beforeEach` hook also has logic for browser filter

```js
beforeEach(() => {
  cy.task('clearDownloads')

  // The next command allow downloads in Electron, Chrome, and Edge
  // without any users popups or file save dialogs.
  if (Cypress.browser.name !== 'firefox') {
    // since this call returns a promise, must tell Cypress to wait
    // for it to be resolved
    cy.wrap(
      Cypress.automation('remote:debugger:protocol',
        {
          command: 'Page.setDownloadBehavior',
          params: { behavior: 'allow', downloadPath: downloadsFolder },
        }),
      { log: false }
    )
  }
})
```

So I foolishly thought: maybe hooks too allow filtering by browser, so I tried this

```js
beforeEach(() => {
  cy.task('clearDownloads')
})

beforeEach({ browser: '!firefox' }, () => {
  cy.wrap(
    Cypress.automation('remote:debugger:protocol',
      {
        command: 'Page.setDownloadBehavior',
        params: { behavior: 'allow', downloadPath: downloadsFolder },
      }),
    { log: false }
  )
})
```

and it tried to run in Firefox

<img width="619" alt="Screen Shot 2020-09-16 at 9 39 46 AM" src="https://user-images.githubusercontent.com/2212006/93345235-8f888a00-f800-11ea-890a-de9076fc012f.png">

## What I think should happen

1. It would be nice if hooks allowed filtering by browser just like suites and tests

or

2. when trying to call `beforeEach(object, hook)` it did NOT run and instead threw a nice message

**Comment by jennifer-shehane** [comment]
Yah, I could see this being useful.

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
