### ISSUE TITLE
Issue with cy.server() in before

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#86]
I'm getting this error on every file using `cy.server()` after a test file has specified `cy.server()` in a `before` after other assertions have run before it.

`CypressError: The XHR server is unavailable or missing. This should never happen and likely is a bug. Open an issue if you see this message.`

**Example Code**
```javascript
describe("Base Describe", function() {
  return it("bars", function() {
    return expect(true).to.be.true;
  });
});

describe("Next Describe", function() {
  before(function() {
    return cy.server();
  });
  return it("foos", function() {
    return expect(true).to.be.true;
  });
});
```

**Command Log Screenshot**
<img width="535" alt="screen shot 2015-11-24 at 8 35 19 am" src="https://cloud.githubusercontent.com/assets/1271364/11368194/53e2f13c-9286-11e5-9394-378589103c0a.png">

**Comment by brian-mann** [comment]
Fixed in [`0.12.6`](https://github.com/cypress-io/cypress/wiki/Changelog#0126-11292015).
