### ISSUE TITLE
electron: -max-http-header-size=1048576 is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by GHermet** [cypress-io/cypress#8601]
### Current behavior:

It seems like one of the `NODE_OPTIONS` attributes is wrongly set using `-max-http-header-size` instead of `--max-http-header-size` in electron

![Screenshot 2020-09-17 at 14 03 10](https://user-images.githubusercontent.com/11071350/93467938-8970d700-f8ee-11ea-9de0-45ea2d6fc5c3.png)

### Desired behavior:

When running `yarn cypress run` in the terminal, the tests should run.

### Test code to reproduce

```
// run from where the cypress dependency is located (package.json)
yarn install
yarn cypress run
```

### Versions

```
Cypress: 5.2.0
OS: macOS Catalina 10.15.6
```

**Comment by FDiskas** [comment]
Try run this command not in vscode integrated terminal

**Comment by bahmutov** [comment]
Yes, try using terminal outside of the editor

**Comment by ghiscoding** [comment]
Oh wow I've been struggling to find a solution for this on my work laptop and that was it... thanks guys.

However doesn't anyone have a solution to get it working in VSCode or we're stuck having to always start it from outside? 
I would rather be able to run it through VSCode, it's much quicker and I have an npm script to open it from there

**Comment by FDiskas** [comment]
Are you using beta vscode version?
For some time it was working in my vscode but after some uodates it's stoped.

Or - wait a sec. My last changes was running tests with --browser electron
Instead of chrome. Is it related?

**Comment by ghiscoding** [comment]
@FDiskas 
Thanks you made me think I should try in stable VSCode and it actually works on that version, I kept trying on VSCode insiders and it doesn't work there but I'm assuming it's because the MS team is trying the latest Electron version in VSCode insiders... so all that to say, VSCode Stable is OK but VSCode Insiders is not and it's because of the new Electron version from VSCode itself.

**Comment by GHermet** [comment]
> Are you using beta vscode version?
> For some time it was working in my vscode but after some uodates it's stoped.
> 
> Or - wait a sec. My last changes was running tests with --browser electron
> Instead of chrome. Is it related?

Yes I'm using VSCode Insider

**Comment by ghiscoding** [comment]
@GHermet 
is that a confirmation that this bug is just with VSCode insiders not stable? 
On my side, I tried with 3 different computers and they all have the problem **only** with the VSCode **insider**.

**Comment by dtinth** [comment]
> However doesn't anyone have a solution to get it working in VSCode or we're stuck having to always start it from outside?
> I would rather be able to run it through VSCode, it's much quicker and I have an npm script to open it from there

Workaround for PowerShell

```pwsh
$env:NODE_OPTIONS = ''
yarn cypress open
```

Workaround for UNIX-like

```pwsh
env NODE_OPTIONS= yarn cypress open
```
