### ISSUE TITLE
cypress run with firefox 80 fails with --headless but passes without --headless. fails both on firefox 66

### ISSUE THREAD

**Issue by jpita** [cypress-io/cypress#8610]
### Current behavior:

Running [this](https://github.com/wikimedia/wikipedia-kaios/pull/275/files#diff-daaac0f21a7615da47769c0c7b13f4bd) test with 

`npx cypress run --browser firefox --headless --spec cypress/integration/references-popup.js` fails ❌

but with 

`npx cypress run --browser firefox --spec cypress/integration/references-popup.js` passes ✅.
This happens on my machine (mac 10.15.6) with firefox 80.
In circleci with firefox 66 it fails ❌  both commands

### Desired behavior:

all commands should have the same outcome so I can see the test fail while running the test on the browser.

### Test code to reproduce

https://github.com/wikimedia/wikipedia-kaios/pull/275/files#diff-daaac0f21a7615da47769c0c7b13f4bd

### Versions

tried with cypress 4.1.12, 5.1.0 and 5.2.0

**Comment by jpita** [comment]
the test is now with the `skip` flag to not fail the build but you can still run it on your machine by removing the skip word

**Comment by dvkruchinin** [comment]
Similar situation with Firefox 85 and Cypress 5.3.0, 6.4.0.
The test succeed without headless mode and fail in headless mode. In particular when interacting with popover antd4.

**Comment by GabrielGarro92** [comment]
Was this issue fixed?

**Comment by YukiKitaoka** [comment]
I can replicate this issue with Cypress 9.3.1/ Firefox version (98.0.2).
This issue seems to be open for a while while the official page https://docs.cypress.io/guides/guides/cross-browser-testing#Continuous-Integration-Strategies clearly states it should work with firefox.

**Comment by dotwork** [comment]
I am also having this issue at my job. We use Jenkins, and when it updated from Firefox version 99 to 102, it began failing tests that try to click a select box dropdown. The select box opens normally and passes when I run it with the browser open, but it fails when I run the test suite headless, and the screenshots show that the select box was selected (has a dotted line around it) but never opened. These select boxes are rendered by React, and work normally on Chrome and have worked normally on Firefox until the recent update to 102.
