### ISSUE TITLE
Workflow proposal to make tests extremely easy to write and maintain

### ISSUE THREAD

**Issue by aalexgabi** [cypress-io/cypress#8615]
This is a draft. I don't have time now to write a full specification. I will improve the specification of this ticket if there is enough interest.

This is my attempt to make tests extremely easy to write and maintain. Debugging is already pretty good with cypress.
The proposed workflow is different way of working with tests but please hear me out.

The proposed workflow:
- Create an new test case in the UI and give it a name
- Record user interactions in the browser and store them either as reusable actions or directly in the test case
- You can name sequences of actions such as "login", "go to profile", "go to user settings" etc.
- One action can call other actions
- When the login page changes, changing the login action will fix all test cases that depend on login action
- This makes composing tests easy and allows re-usability which makes tests easily maintainable
- Those actions will be stored as data and not as code to allow editing them later (maybe standardized json file format)
- You can also write actions manually in a text-area which highlights the code and does syntax checking
- Add simple assertions to actions by
  - right click on selected text and click "assert presence of this text"
  - right click on any element and click "assert presence of element"; maybe some settings pop-up allows finer tuning of the assertion
- Of course instead of right click a modifier key can be used (Ctrl, Alt etc.)
- If you need to write a complex assertion that require code you can add a manual assertion and paste the assertion code in a text-area which highlights the code and does syntax checking
- Cypress can read this json file and execute it. Looping through all the test groups, test cases, actions and executing them calling the cy API
- The UI allows replaying a test case up to any breakpoint
- You can insert or overwrite user interactions at breakpoint in the action sequence by recording in insert or overwrite mode
- The json file can be comitted in git the diff of the file can be read
- You can use multiple json files when they get too big
- One json file can include another one to simplify sharing of actions
- You have a working history of the file using Ctrl + Z etc.

Example test case:
- login (action)
  - go to login page
  - put email
  - put password
  - click submit
- remove user photo (action)
  - go to profile page
  - click on remove photo
  - click submit
- go to profile page
- assert photo is not present

Actions like "login" and "remove user photo" can be reused.

What are your thoughts on this? Why this is not the way we do testing today?
Don't get me wrong you will still need to write code for some assertions and for simulating some interactions but this solution does not force you to write code if you don't have to.

cc: @flotwig @chrisbreiding

**Comment by Bkucera** [comment]
This issue (#73) is basically what you are asking about, will defer to it and close this issue as duplicate. Please add your comment there if you have something unique to add. Thanks!

**Comment by aalexgabi** [comment]
@Bkucera The issue you referenced proposes a different solution that I propose here. Here are some drawbacks of that solution:
- Generating test case does not allow modifying the test afterwards; This is important to keep the same speed when maintaining the tests and to allow simple testing without writing code
- There is no way to generate assertions; This is important to confirm that a given feature actually works and to speed up writing assertions
- There is no way to reuse actions and assertions; This is important because maintaining recorded tests would be very time consuming and a lot of code duplication would occur
- Test cases are not stored in files automatically

I would like to start a discussion about the advantages and disadvantages of the proposed approach.
