### ISSUE TITLE
Error: Cannot find module (When running cypress in pre push + Visual Studio Code)

### ISSUE THREAD

**Issue by joicesena** [cypress-io/cypress#8616]
### Current behavior:
I have Husky configured in an Angular project for run Cypress in pre push. When I run git push in Visual Studio Code terminal, everything went ok. But if I run git push using the build-in Version Control in the IDE, I get an Error: Cannot find module '--run-project' in the Git output console.

### Desired behavior:

It would work without throwing an error about "Cannot find module" when I run git push using the build-in Version Control in the Visual Studio Code.

#### How to reproduce it

- Start the project at the port expected by Cypress 

- Run git push using the build-in Version Control in the IDE

![image](https://user-images.githubusercontent.com/23310284/93589651-85db5f80-f983-11ea-9a24-12e181808526.png)

- Wait the push fail and see the Git output console

![image](https://user-images.githubusercontent.com/23310284/93589856-e23e7f00-f983-11ea-8e1a-9d2421e08adb.png)

#### My code

Inside Package.json I have 

- Cypress run command

![image](https://user-images.githubusercontent.com/23310284/93590861-a86e7800-f985-11ea-88de-c3e03b2287bb.png)

- Husky command

![image](https://user-images.githubusercontent.com/23310284/93590908-be7c3880-f985-11ea-96eb-e5006a075bc0.png)

### Versions
- Cypress: "cypress": "^4.12.1"
- Husky: "husky": "^4.3.0"
- Visual Studio Code: version 1.49
- Operating system: Windows 10

**Comment by longcui** [comment]
Experienced the same.  so now I manually run `git push` in Powershell in order to trigger cypress.

**Comment by jennifer-shehane** [comment]
I think this is more an issue with husky rather than Cypress. Saw this anyway which was an issue with husky 4.0 https://stackoverflow.com/questions/61196309/husky-4-x-not-working-with-visual-studio-git

**Comment by Netz-pixel** [comment]
Did you find a solution for this? I have the exact same problem.
