### ISSUE TITLE
Custom Reporter written in TS does not work since 5.x

### ISSUE THREAD

**Issue by Konstruktour** [cypress-io/cypress#8617]
### Current behavior:
A custom reporter written in Typescript does not work anymore since the introduction of cypress 5.x. It only allows custom reporters written in JS.
Running a ts reporter ends with the following error:
``` 
Could not load reporter by name: ./cypress/support/test-reporter.ts

We searched for the reporter in these paths:

- cypress\support\test-reporter.ts
- node_modules\cypress\support\test-reporter.ts

The error we received was:

cypress\support\test-reporter.ts:1
exports = module.exports = (runner: any, options: any): void => console.log('Reporter ->', options);
                                  ^

SyntaxError: Unexpected token ':'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

### Desired behavior:
A custom reporter should also be possible to be written in TS (like eg in version 4.12.0 )

### Test code to reproduce
the reporter (test-reporter.ts)
```javascript
exports = module.exports = (runner: any, options: any): void => console.log('Reporter ->', options);
```

Run via JS (or TS)
```javascript
const cypress = require('cypress/index');

cypress.run({
    reporter: './cypress/support/test-reporter.ts',
});
```

### Versions
Cypress 5.2.0

**Comment by josephzidell** [comment]
Am experiencing the same issue on Cypress 6.4.0

**Comment by andrecrimb** [comment]
Same issue on 7.1.0

**Comment by lbergeron** [comment]
Experiencing the same issue with Cypress 8.5.0

**Comment by bvandercar** [comment]
also experiencing this issue.

**Comment by BlueWinds** [comment]
Similar to - https://github.com/cypress-io/cypress/issues/18922 - it looks like our code to load custom reporters doesn't go through the same module resolution / webpack process other code cypress imports. I suspect the same fix would resolve both these issues.

**Comment by jonathonherbert** [comment]
We're also experiencing this issue at https://github.com/guardian/editorial-tools-integration-tests when attempting to migrate from Cypress 4.x

**Comment by hkk2018** [comment]
Still can't work on Cypress 10.1.0.
Any working example?

**Comment by MateusRodriguesCosta** [comment]
Same experience here with Cypress 10.3.0.
