### ISSUE TITLE
Cypress waiting for a new page to load and throwing timed out error

### ISSUE THREAD

**Issue by sudheer-cyp** [cypress-io/cypress#8619]
**Current behavior:**

This is my test - Navigate to a page, make some selections on the page and click on a link. So, when i click on a link a file will be downloaded to my local machine. My test should end here. But cypress is waiting for a new page to load for long time and throwing a timed out error. Logging  this issue since i could not find a viable solution for this problem in chat or over the web and this is holding my lot of work

**Stack Trace:**
```
   at timedOutWaitingForPageLoad (http://ecpphxsit.uscold.com:9083/__cypress/runner/cypress_runner.js:156859:14)
    at <unknown> (http://ecpphxsit.uscold.com:9083/__cypress/runner/cypress_runner.js:157118:15)
From previous event:
    at run (http://ecpphxsit.uscold.com:9083/__cypress/runner/cypress_runner.js:169779:20)
    at $Cy.cy.<computed> [as visit] (http://ecpphxsit.uscold.com:9083/__cypress/runner/cypress_runner.js:170232:12)
From Your Spec Code:
    at eval (webpack:///cypress/integration/smokesuite/xpathdemo.js:41:12)
    at itCallback (webpack:///cypress/support/index.js:65:5)
    at Context.eval (webpack:///cypress/support/index.js:90:34)
From Your Spec Code:
    at eval (webpack:///cypress/integration/smokesuite/xpathdemo.js:41:12)
    at itCallback (webpack:///cypress/support/index.js:65:5)
    at Context.eval (webpack:///cypress/support/index.js:90:34)
```
### Desired behavior:
When the file is downloaded, cypress should pass/fail based on the assertions i put. I don't want it to wait for anything else. Logging
![Wait issue](https://user-images.githubusercontent.com/70509792/93602226-fb751900-f9df-11ea-9ec9-8fd369a44fa3.png)
![Timedout](https://user-images.githubusercontent.com/70509792/93602249-0039cd00-f9e0-11ea-9c13-030537f29b8a.png)

**### Test code to reproduce**
```js
/// <reference types="Cypress" />
describe("Verify Inventory Summary Report with default selections",function() {
    Cypress.on('fail', (error, runnable) => {
    
        throw error 
     
      })

      Cypress.on('uncaught:exception', (err, runnable) => {
                return false
      })
    
      const { softExpect } = chai;

    it('Obtaining inventory summary group by with  in 9083',function(){
        cy.visit('http://ecpphxsit.uscold.com:9083/eUSCOLD/jsp/index.jsp')
        cy.get('input[name="userId"]').type('SMANI')
         cy.get('input[name="password"]').type('Welcome1')
         cy.get('[type="image"]').click()
        cy.contains('Inventory Report').click({force: true})
        cy.get('#inventoryReportSel_customerNames').select('511600000100950')
        cy.get('#productCode').invoke('val',1007)
        cy.xpath("//input[@id='inventoryReportSel_groupByC']").click()
        cy.xpath("//input[@id='inventoryReportSel_htmlFormat']").click()
        cy.xpath("//input[@id='inventoryReportSel_csvFormat']").click()
        cy.wait(10000)
        cy.xpath("//span[contains(text(),'View CSV')]").click()
        cy.wait(5000)
        cy.xpath("//span[contains(text(),'Ok')]")
         
         cy.xpath("//a[contains(text(),'Summary Report - CSV')]").click()
       
        cy.xpath("//span[contains(text(),'Ok')]").click()

            })
})
```
### Versions
5.2.0

Windows 10 64bit,Chrome

**Comment by sudheer-cyp** [comment]
@jennifer-shehane Any update

**Comment by jennifer-shehane** [comment]
There's currently no way to prevent the page load from happening within Cypress itself once the application under test has initiated a page load - so the tests won't continue until that new page fires its load event. 

This thread may be helpful for testing downloading a file - as this is not completely supported in Cypress yet. https://github.com/cypress-io/cypress/issues/949

**Comment by jennifer-shehane** [comment]
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).
