### ISSUE TITLE
route2 stub for img elements using Fixtures returns text/plain as content type

### ISSUE THREAD

**Issue by TonyHernandezAtMS** [cypress-io/cypress#8623]
### Current behavior:
route2 when configured with image fixtures returns content text/plain.

![image](https://user-images.githubusercontent.com/9831944/93639159-2ea6b080-f9be-11ea-99fa-6cf87700e00d.png)

### Desired behavior:
route2 configured with fixtures should return images with correct content type.

### Test code to reproduce
Here is a repo with a set of tests.
https://github.com/TonyHernandezAtMS/cypress-test-tiny/
I have found that when I first run this test in Chrome, the first test ends up in a loop requesting the image over and over. If I perform a Empty Cache and Hard Reload in the browser then the tests will progress through all of them.

### Versions
5.2.0, Windows, all browsers

**Comment by TonyHernandezAtMS** [comment]
@flotwig Hoping you can take a look at this.

**Comment by flotwig** [comment]
@TonyHernandezAtMS as a workaround, you can specify the content-type manually for responses. Using your example:

```js
    cy.fixture("fixture1/pictures/category.jpg").then((pic) => {
      cy.route2("images/category.jpg", { body: pic, headers: { 'content-type': 'image/jpeg' } });
    });
```

---

I'm pretty sure this problem also exists for the `fixture` API:

```js
// this probably also sends the wrong content-type, but can be fixed
cy.route2('images/category.jpg', { fixture: 'fixture1/pictures/category.jpg' })
```

I'm not sure if there is going to be a way to fix the pattern you've provided in the OP, but we can definitely fix this usage.

**Comment by TonyHernandezAtMS** [comment]
@flotwig 
I tried your snippet:
```javascript
    cy.fixture("fixture1/pictures/category.jpg").then((pic) => {
      cy.route2("images/category.jpg", { body: pic, headers: { 'content-type': 'image/jpeg' } });
    });
```
It didn't work. The browser still shows a blank placeholder. I've attached the HAR file and have [updated the repo with this snippet](https://github.com/TonyHernandezAtMS/cypress-test-tiny/tree/workaround1).

**Comment by flotwig** [comment]
@TonyHernandezAtMS try this maybe:

```js
cy.route2('images/category.jpg', { fixture: 'fixture1/pictures/category.jpg', headers: { 'content-type': 'image/jpeg' } })
```

**Comment by bahmutov** [comment]
You know we have https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__route2 where you could try and show how it is working or not working without guessing

**Comment by bahmutov** [comment]
Tried the image spying and stubbing, so far no luck, see https://github.com/cypress-io/cypress-example-recipes/pull/570#issuecomment-699119158

**Comment by bahmutov** [comment]
No update on this, if there was any work in progress there would be a pull request linked to this issue

**Comment by TonyHernandezAtMS** [comment]
Thanks for the info.

**Comment by flotwig** [comment]
This was actually a 2-part bug - the wrong Content-Type was getting assigned, /and/ the fixture body was getting incorrectly encoded to base64, which is why https://github.com/cypress-io/cypress/issues/8623#issuecomment-697576422 didn't work.
