### ISSUE TITLE
Cannot pass config-file option to parseRunArguments 

### ISSUE THREAD

**Issue by bjowes** [cypress-io/cypress#8632]
### Current behavior:
When passing `--config-file cypress.json` as part of the command line arguments to parseRunArguments, cypress fails with the following error:
```
The "path" argument must be of type string. Received type boolean
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean
```

### Desired behavior:
The --config-file argument should be properly parsed also when using the node module API.

### Test code to reproduce
```javascript
const cypress = require('cypress');
async function reproduceError() {
  const runOptions = await cypress.cli.parseRunArguments(['cypress', 'run', '--config-file', 'cypress.json']);
  const results = await cypress.run(runOptions);
}
reproduceError();
```

### Versions
Cypress 5.2.0
Windows 10

### Analysis
With debugging it is clear where the issue appears:
```
  cypress:cli:cli parsing args: [ null, null, 'run', '--config-file=myConfigFile.json' ] +3ms
  ...
  cypress:cli parsed cli options { configFile: 'myConfigFile.json' } +0ms
  cypress:cli:cli parsed options { configFile: 'myConfigFile.json' } +46ms
  cypress:cli:cli casted options { configFile: true } +1ms
```
`
Looking through the code, there is a coercion function applied to the configFile property when parsing arguments, since this argument may be a string or false. However, the coercion function always returns a boolean
https://github.com/cypress-io/cypress/blob/ef2363ea7837cf55f88a4ba59615ad2b7d0b3b71/cli/lib/cli.js#L25-L27

### Suggested fix
If the coercion function is replaced with
```javascript
const coerceFalse = (arg) => { 
   return arg !== 'false' ? arg : false;
} 
```
it should work as expected.

**Comment by bahmutov** [comment]
Good catch @bjowes - do you mind opening a pull request with this fix and a corresponding unit test?

**Comment by bjowes** [comment]
Sure, why not. Would be nice to be able to claim that I have contributed to the cypress code base :)

**Comment by bahmutov** [comment]
That’s the spirit ❤️
