### ISSUE TITLE
Preprocessor opens another Cypress instance when bundling

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8634]
This issue happens in Cypress v5.0.0 and does not occur in v4.12.1

If you try to run Cypress tests in https://github.com/eggheadio/egghead-next then a curious thing happens: it pops a new Cypress instance while trying to bundle.

Recording: https://jumpshare.com/v/v5mfJi5QlSbsd7IpBFAb

**Comment by ctorresDespegar** [comment]
I have the same problem in cypress v5.0.2. It always opens multiple windows but never it run the tests.

**Comment by bahmutov** [comment]
Narrowed it down to these dependencies
```
  "dependencies": {
    "next": "^9.5.3"
  },
  "devDependencies": {
    "cypress": "5.2.0",
    "jest": "^26.4.2"
  }
```

and .babelrc file

```
{
  "presets": ["next/babel"],
  "plugins": ["istanbul"]
}
```

```
$ npm ls babel-plugin-istanbul
egghead-io-nextjs@0.1.0 /Users/gleb/git/egghead-next
└─┬ jest@26.4.2
  └─┬ @jest/core@26.4.2
    ├─┬ @jest/transform@26.3.0
    │ └── babel-plugin-istanbul@6.0.0 
    └─┬ jest-config@26.4.2
      └─┬ babel-jest@26.3.0
        └── babel-plugin-istanbul@6.0.0  deduped
```

**Comment by bahmutov** [comment]
Reproducible example in https://github.com/cypress-io/cypress-test-tiny/tree/open-global

- clone repo
- npm install
- npx cypress open
- click on the spec

See the second instance of Cypress open!

Relevant portion of the debug log

```
 cypress:server:cypress starting cypress with argv [ '/Users/gleb/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/MacOS/Cypress', '/Users/gleb/git/cypress-test-tiny/node_modules/babel-plugin-istanbul/lib/load-nyc-config-sync.js', '/Users/gleb/git/cypress-test-tiny' ] +0ms
  cypress:server:args argv array: [ '/Users/gleb/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/MacOS/Cypress', '/Users/gleb/git/cypress-test-tiny/node_modules/babel-plugin-istanbul/lib/load-nyc-config-sync.js', '/Users/gleb/git/cypress-test-tiny' ] +0ms
  cypress:server:args argv parsed: { _: [ '/Users/gleb/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/MacOS/Cypress', '/Users/gleb/git/cypress-test-tiny/node_modules/babel-plugin-istanbul/lib/load-nyc-config-sync.js', '/Users/gleb/git/cypress-test-tiny' ], invokedFromCli: false, cwd: '/Users/gleb/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/Resources/app/packages/server' }
```

**Comment by bahmutov** [comment]
Traced it inside `babel-plugin-istanbul` to the function that loads the config like this
```
function loadNycConfig(cwd, opts) {
  ...
  const result = JSON.parse((0, _child_process.execFileSync)(process.execPath, args));
  ...
  return config;
}
```

Which in our case starts Cypress pointing at the args! For example if we print the args
```
console.log('about to execute')
console.log(process.execPath, args.join(' '))
```

we get
```
about to execute
/Users/gleb/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/MacOS/Cypress 
  /Users/gleb/git/cypress-test-tiny/node_modules/babel-plugin-istanbul/lib/load-nyc-config-sync.js 
  /Users/gleb/git/cypress-test-tiny
```
Because it thinks it is executing inside Node, thus uses exec process to load other scripts as child processes. Should we separate every bundler better into a child process to solve this - because this one executes a child process _inside a require_.

**Comment by bahmutov** [comment]
Note: using system Node is NOT a workaround. The setting below still opens Cypress while loading babel options

```json
{
  "nodeVersion": "system"
}
```

**Comment by johnlindquist** [comment]
Is there any movement on this? Kinda waiting on it so we can switch back to v5...

**Comment by chrisbreiding** [comment]
@johnlindquist I'm planning to look into this sometime in the next few days. Sorry for the inconvenience!

**Comment by nhynes** [comment]
@chrisbreiding thanks for looking into this. I'm getting the same issue using TS and Parcel without any explicit babel-plugin-istanbul. I'm also using `route2`, so I can't go back to 4.x.

**Comment by chrisbreiding** [comment]
> @bahmutov: Should we separate every bundler better into a child process to solve this - because this one executes a child process inside a require.

That's exactly what we need to do. We do this for user-registered preprocessors, but when the user has not registered a preprocessor, we register our own default preprocessor _in the main Cypress process_. I'm fixing this in #8826 by now registering the default preprocessor in the plugins child process as well.

**Comment by bahmutov** [comment]
👏 👏 👏
