### ISSUE TITLE
"should" using a callback does change the subject

### ISSUE THREAD

**Issue by SimoneGianniHNP** [cypress-io/cypress#8638]
### Current behavior:

On version 4.11.0 but seens also on some previous versions.

```js
cy.get("#something")
    .should($el => null)
    .click();
```

Will fail complaining that click was called not on a DOM element:

```
CypressError: `cy.click()` failed because it requires a DOM element.

The subject received was:

  > `Object{3}`

The previous command that ran was:

  > `cy.should()`

      at ensureElement (http://localhost:4200/__cypress/runner/cypress_runner.js:159904:24)
      at validateType (http://localhost:4200/__cypress/runner/cypress_runner.js:159728:16)
      at Object.ensureSubjectByType (http://localhost:4200/__cypress/runner/cypress_runner.js:159770:11)
      at pushSubjectAndValidate (http://localhost:4200/__cypress/runner/cypress_runner.js:167481:15)
      at Context.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:167809:18)
```

The "Object{3}" above is a jquery object.

This is caused by two problems:
1. "should" with a callback is documented not to change the subject, but looks like it wraps it in jquery object (to pass it as a parameter) and from that moment on the subject is the jquery object, so it is changed
2. "click" does not handle properly a jquery object as a subject (?), the isElement test fails and throws the exception.

### Desired behavior:

The above lines should work, or be documented as not working.

### Test code to reproduce

See the three lines above.

### Versions

4.11.0 electron linux

**Comment by bahmutov** [comment]
Please try Cypress v5.2.0 where this test passes

```js
describe('page', () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')
    cy.get("h1")
      .should($el => null)
      .click();
  })
})
```

<img width="1440" alt="Screen Shot 2020-09-22 at 3 14 00 PM" src="https://user-images.githubusercontent.com/2212006/93926988-40ea5c80-fce6-11ea-9315-68d858e0c2d6.png">

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example, including the DOM to test against with the get command that should be passed to should and we will consider reopening the issue.
