### ISSUE TITLE
User is unable to re-run tests

### ISSUE THREAD

**Issue by DariaAndrushchenko** [cypress-io/cypress#8639]
### Current behavior:
I run my test, it works properly
<img width="1175" alt="main_run" src="https://user-images.githubusercontent.com/52241327/93867239-6d47ae00-fcd1-11ea-8ce6-0cb7b8bf0ac1.png">

After the first test re-run, it throws a  **_Blocked a frame with origin "https://app.oppizi.com" from accessing a cross-origin frame._** error.
<img width="1185" alt="first_re_run" src="https://user-images.githubusercontent.com/52241327/93867320-8ea89a00-fcd1-11ea-81db-20e9563feb4d.png">

After the second test re-run, it throws **_No test found in your file_**
<img width="1189" alt="second_re_run" src="https://user-images.githubusercontent.com/52241327/93867345-95371180-fcd1-11ea-9c95-0502fc25d045.png">

It works only after full app reload. 
Same issue after test file was changed and saved, it can't be re-run

### Test code to reproduce
My test:

```js
describe('My First Test', () => {
    it('Gets, types and asserts', () => {
        cy.visit('https://app.oppizi.com/login')
        cy.get('#username').type('aaaaaa')
        cy.get('#password').type('qqqqqq')
        cy.get('#login-submit').click()
    })
})

```

### Versions

Version 5.2.0

**Comment by DariaAndrushchenko** [comment]
<img width="1185" alt="first_re_run" src="https://user-images.githubusercontent.com/52241327/93867121-49846800-fcd1-11ea-9f58-5ea4de3bf3ec.png">
<img width="1185" alt="first_re_run" src="https://user-images.githubusercontent.com/52241327/93867136-4e491c00-fcd1-11ea-9afe-6e6560919da4.png">
<img width="1189" alt="second_re_run" src="https://user-images.githubusercontent.com/52241327/93867138-4e491c00-fcd1-11ea-8ac5-7ce634044a7a.png">
<img width="1175" alt="main_run" src="https://user-images.githubusercontent.com/52241327/93867151-51dca300-fcd1-11ea-90b6-ec66b858ee46.png">
<img width="1189" alt="second_re_run" src="https://user-images.githubusercontent.com/52241327/93867163-54d79380-fcd1-11ea-80d4-b24126d509f4.png">

**Comment by sainthkh** [comment]
Sorry for the late reply. Confirmed that the provided code somehow breaks Cypress.

**Comment by DariaAndrushchenko** [comment]
Thanks for your reply

**Comment by jennifer-shehane** [comment]
@DariaAndrushchenko Can you try disabling Service Workers and see if the rerunning of tests works after that? There are some workarounds detailed in this issue: https://github.com/cypress-io/cypress/issues/702#issuecomment-435873135
