### ISSUE TITLE
How to write data in cypress in text file ,line by line

### ISSUE THREAD

**Issue by sumabala9** [cypress-io/cypress#8641]
I want to write some run-time values in a text file in cypress using cy.write() line-by-line. But my text file is writing only last value, actually it is getting ovveriden in the text-file. IN
![textfile](https://user-images.githubusercontent.com/65771070/93887605-8e75c200-fd04-11ea-957d-2784eb3a5d5d.PNG)
![writefileissue](https://user-images.githubusercontent.com/65771070/93887614-903f8580-fd04-11ea-846e-347f519135f1.PNG)

 this case how to move control in my text file to next line using the script?
Please see the below code and screen-shots. I want to get all values line-by-line in my txt file.
   var i = 0;   
              for(i=0;i<5;i++) 
             {
                  cy.get('.number').eq(2).then((xhr)  => {
                      cy.log(xhr.text())
                      cy.writeFile('cypress/fixtures/file1.txt',xhr.text())
                  })
             }

**Comment by Bkucera** [comment]
cy.writeFile() overwrite the file if it exists. You'll have to read the file contents and create a new file with the appended contents.

**Comment by bahmutov** [comment]
See documentation in https://on.cypress.io/writefile
