### ISSUE TITLE
contains(), get(), url(), occasionally returns null

### ISSUE THREAD

**Issue by brandonc** [cypress-io/cypress#8644]
# Current behavior
get(), contains(), and url() will occasionally yield null, which doesn't appear to be documented. When do these methods yield null? My reading of the docs is that get() and contains() methods yield DOM elements or throws an error. Here is an example:

```
CypressError: cy.clear() failed because it requires a DOM element.

The subject received was:

  > null
```

And here is the code that triggered it:

```js
cy.get('[placeholder="Filter by Name or Monitoring ID"]')
          .clear()
          .type("whatever");
```

or in the case of url(), I know that a page is loaded yet I occasionally receive this error:

`AssertionError: expected null to equal 'http://localhost:4000/blah'`

on this assertion:

```js
cy.url().should("equal", Cypress.config().baseUrl + "/blah");
```

### Desired behavior

In the case of get() or contains(), I expect an error indicating that no DOM elements were found, not a chaining error

In the case of url(), I expect to receive the url and never null

### Test code to reproduce

I can't provide test code that reliably produces this error. It seems to be intermittent. I can provide cypress dashboard links with test results as shown above.

**Comment by bahmutov** [comment]
Ok, let's track this down. If this is intermittent we could try using https://github.com/bahmutov/cypress-repeat to get it to crash. I would be interested in seeing video / screenshot for the failed run: I think we might have to add additional check there to retry the selector if we get `null`

**Comment by brandonc** [comment]
@bahmutov Thanks for your attention on this. Here are some details:

Here is the console, screenshot, and video of a reproduction:
https://github.com/brandonc/brandonc.github.io/raw/master/null-get.zip

I tried to do a minimal repro with just the static HTML from the page state at the moment of failure. You can see this HTML at http://brandonc.github.io

But I could never get this project to fail. It always behaved as expected:

```
describe("test-cypress-null", () => {
  it("fails", () => {
    cy.visit("/");

    cy.get('[data-cy="emptyState"]', {
      timeout: 60000,
    }).should("exist");
  });
});
```

The app where we see the failure is React, and the DOM elements are sometimes removed from the page which results in some mismatch. However, usually we see a different error when the matched DOM elements are removed.

I also opened a PR against cypress-repeat that allowed me to use cypress run arguments: https://github.com/bahmutov/cypress-repeat/pull/3 - cypress-repeat will be a very helpful tool for me... thanks for providing that!

Let me know what you think and if I can provide more details.

**Comment by BlueWinds** [comment]
I believe this issue should be reduced or resolved entirely in Cypress 12, with the introduction of queries and the changes in Cypress' retry logic. Going to close this, please feel free to open a new issue if you're still experiencing problems with the latest version.
