### ISSUE TITLE
Cy.select doesnot  work 

### ISSUE THREAD

**Issue by srilatha444** [cypress-io/cypress#8645]
### Current behavior

 
HTML Code below 
<select class="state-select " name="sign-up-agency-state-id" placeholder="Select State">
<option>Select State</option>
<option value="3">AL - Alabama</option>
<option value="4">AK - Alaska</option>
<option value="8">AZ - Arizona</option>
<option value="9">AR - Arkansas</option>
</select>

I have tried the below examples  

Example  1- 
cy.get('select[class="state-select "]').should('have.value', '3')  fails although the examples in Cypress documentation show that its easy . 

Timed out retrying: Expected to find element: 3, but never found it.
cypress/support/commands.js:120:6
  118 | Cypress.Commands.add('select',(formClass,label,selectText,_options ={})=>{
  119 |     cy
> 120 |     .get(formClass)
      |      ^
  121 |     .each(($el, _index, _$list) => {
  122 |       if ($el.find("label").text() === label) {
  123 |         cy.wrap($el).find('.react-select').click()

Example 2: - 
 This never actually selected the option in the UI but the code itself succeeds

 cy.get('select[class="state-select "]').then(function($select){
       $select.val('3')
   })

Example 3 - 
 This is very interesting one where the selection did happen in the UI but Cypress throwed  same error as in example 1 
cy.get('select[class="state-select "]').then(function($select){
       $select.val('3')
   })

cy.get('select[class="state-select "]').should('have.value', '3')
### Desired behavior

I want the option 3 to be selected in the UI 

### Test code to reproduce
The  above code is under the xpath  as below 
//*[@id="app-content"]/div/div/div/div[8]/div[1]/div/select
<select class="state-select " name="sign-up-agency-state-id" placeholder="Select State">
<option>Select State</option>
<option value="3">AL - Alabama</option>
<option value="4">AK - Alaska</option>
<option value="8">AZ - Arizona</option>
<option value="9">AR - Arkansas</option>
</select>

**Comment by bahmutov** [comment]
Read our documentation at https://on.cypress.io/select
See examples at https://example.cypress.io/commands/actions
Read blog post https://www.cypress.io/blog/2020/03/20/working-with-select-elements-and-select2-widgets-in-cypress/
