### ISSUE TITLE
return false doesn't finish the each loop if cypress commands was added

### ISSUE THREAD

**Issue by rockthis13** [cypress-io/cypress#8652]
### Current behavior

action in "if" condition is performed, but "return false" doesn't finish the each loop

### Desired behavior

"return false" finish the each loop with cypress commands inside

### Test code to reproduce

```js
cy.get('[class*=CardContentTitle]').each(agency =>{
  cy.wrap(agency).invoke('text').then(function(text) {
    if (text !== 'Sprout Therapy') {
      cy.wrap(agency).click()
      return false
    }
  })
})
```

### Versions

cypress 5.0.1

**Comment by bahmutov** [comment]
One quick thing - you are calling `return false` not from the `.each` callback, but from the `.then` callback.

**Comment by bahmutov** [comment]
Unfortunately, you cannot use other Cypress commands while inside `cy.each`, but you could achieve the same using jQuery synchronous commands here

``js
// iterate through all fruits
cy.spy(console, 'log').as('console')
cy.get('li').each(($el) => {
  console.log($el.text())
  // prints "Apples", "Bananas", "Grapes"
})
cy.get('@console').should('have.been.calledThrice').invoke('resetHistory')

// iterate over fruits, but stop when reach Bananas
cy.get('li').each(($el) => {
  if ($el.text() === 'Bananas') {
    // stop iteration
    return false
  }
  console.log($el.text())
  // prints "Apples"
})
cy.get('@console').should('have.been.calledOnce').invoke('resetHistory')
```

<img width="908" alt="Screen Shot 2020-09-23 at 3 13 04 PM" src="https://user-images.githubusercontent.com/2212006/94058731-6b541c80-fdaf-11ea-8cd7-a1f1ffc130dd.png">

I pushed this example in this commit https://github.com/cypress-io/cypress-fiddle/commit/1dee36d33ecbf558b8b2abbf5203dbc591f66daa

**Comment by rockthis13** [comment]
@bahmutov Thank you for clarifying!
