### ISSUE TITLE
Manage specs groups in cypress.json

### ISSUE THREAD

**Issue by ronenmalka** [cypress-io/cypress#8657]
### Feature Request
Allow to group specs in the cypress.json file

### Versions
Cypress 5.2.0

### Feature
It would be very helpful to allow arrange/categorize specs in groups in the cypress.json file.
I know it is possible to use package selectors to select test group, but not always it is possible to arrange related specs in the same package.
Sometimes there are other criteria to group tests, for example, you would like to group tests by test run duration, 
so you can split tests in more efficient way for parallel run, or any other logic.

So, instead (or additionally) of providing array in `'testFiles'` we should accept an object:

```js
"testFiles": {
		group1: [
			"test1",
			"test8",
			"test3", ],
		group2: [
			"test2",
			"test9",
			"test6",],
		group3: [
			"test1",
			"test4",
			"test5",]
	}
```

Then, we can run: `cypress run --record --group group2`

Once this implemented, it will be nice to have the tests in the 'cypress open' arranged in a tree view, so at development time we can select specific group.

**Comment by jennifer-shehane** [comment]
We already have a —group flag that serves another purpose. https://docs.cypress.io/guides/guides/command-line.html#cypress-run-group-lt-name-gt

**Comment by ronenmalka** [comment]
Yes. I know that there is already a way to group specs, but as I wrote:

> Sometimes there are other criteria to group tests, for example, you would like to group tests by test run duration,
so you can split tests in more efficient way for parallel run, or any other logic.

And the current grouping method dose not cover all grouping possibilities.

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
