### ISSUE TITLE
Error: Can't walk dependency graph: Cannot find module 'pg-native'

### ISSUE THREAD

**Issue by jdiegosierra** [cypress-io/cypress#8659]
### Current behavior
 const pg = require('pg'); gives the following error when I run the tests.

`Error: Can't walk dependency graph: Cannot find module 'pg-native' from '/test-e2e/node_modules/pg/lib/native'
    required by /test-e2e/node_modules/pg/lib/native/client.js` 

### Desired behavior
I'm trying to use pg in order to create some data in postgresql before test cases.

### Versions
OS: Ubuntu 20.04
Node: v12.18.0
pg: 8.3.3

**Comment by bahmutov** [comment]
You are trying to load a native module from the browser (that's where the Cypress tests run). Thus the bundler cannot find / bundle it. Try pushing this to the plugins file and use `cy.task` to work with the database, see https://docs.cypress.io/guides/tooling/plugins-guide.html#cy-task
