### ISSUE TITLE
Guidance on when to use Commands vs. generic functions

### ISSUE THREAD

**Issue by dclowd9901** [cypress-io/cypress#8660]
### Current behavior

Docs don't have much guidance on the boundaries of usage of Commands.

### Desired behavior

More guidance on when we should use Commands vs. exporting/importing generic functions.

### More description

Commands seem to be central to the Cypress development experience, but with commands being all in one namespace, there is an inherent concern with overusing them.

In documentation, there doesn't seem to be any guidance around the usage of commands, or what would warrant their usage over simply importing a defined function. It would be nice to get more guidance in this regard, as we don't want to have made a bad decision from the get-go on this matter.

**Comment by bahmutov** [comment]
I can offer these slides https://slides.com/bahmutov/page-objects-in-cypress and say that if you have a reusable series of commands you want to use in all or almost all of your tests - make it into a custom command.

You can see examples of such commands in our https://github.com/cypress-io/cypress-realworld-app

**Comment by dclowd9901** [comment]
Thanks for your help @bahmutov
