### ISSUE TITLE
Can't able to set an alias inside the 2 nested request

### ISSUE THREAD

**Issue by elycisjasa123** [cypress-io/cypress#8670]
### Current behavior

[Screen record Link](https://gitlab.com/elycisjasa123/infotek/uploads/f335f85408d96be80743a653aaeaab41/bandicam_2020-09-25_13-02-55-188.mp4)

### Desired behavior
- I must able to set an alias inside the 2 nested request

### Test code to reproduce
- Using this test structure
```js
    it.only('should create a first module', () => {
      cy.log('create a module');
      cy.dataTest('create-module').click();
      cy.dataTest('module-name').type('Module 1');
      cy.dataTest('module-description').type('This is module 1');
      cy.dataTest('save-module').click();
      cy.wait('@moduleCreation')
        .its('status')
        .should('eq', 201);
      cy.request({
        url: '/api/me/courses?role=instructor&type=all&page=1',
        method: 'GET',
        headers: {
          Authorization: `Bearer ${Cypress.env('INSTRUCTOR_TOKEN')}`,
        },
      }).then(getCourses => {
        const courseId = getCourses.body[0].id;
        cy.request({
          url: `/api/courses/${courseId}/modules?role=instructor`,
          method: 'GET',
          headers: {
            Authorization: `Bearer ${Cypress.env('INSTRUCTOR_TOKEN')}`,
          },
        }).then(getCreatedModule => {
          const moduleId = getCreatedModule.body[0].id;
          cy.server();
          cy.log(moduleId);
          cy.route('GET', `/api/modules/${moduleId}`).as('selectedModule');
        });
        cy.wait('@getCourseMaterials')
          .its('status')
          .should('eq', 200);
      });
    });
```

### Versions
**`Cypress version 5.2.0`**
![Cypress Version](https://user-images.githubusercontent.com/36752375/94229584-84d1a180-ff32-11ea-9329-fa7fe2c04499.png)

**`Chrome Version 85.0.4183.121`**
**`OS: Windows 10`**
**`Terminal: Git Bash`**

**Comment by bahmutov** [comment]
The recording is unavailable

**Comment by elycisjasa123** [comment]
Hello I already updated the recording link

**Comment by bahmutov** [comment]
Why do you call `cy.server()` again in the second request? You have already called it somewhere else right, because you waited for `cy.wait('@moduleCreation')` right?

```js
cy.server();
cy.log(moduleId);
cy.route('GET', `/api/modules/${moduleId}`).as('selectedModule');
```

Also, have you tried [cy.route2](https://on.cypress.io/route2) by any chance, it will be more reliable since it proxies things in the network layer

**Comment by elycisjasa123** [comment]
I used `cy.server();` for the `cy.route('GET', `/api/modules/${moduleId}`).as('selectedModule');` so that I can reuse in `wait('@selectedModule').its('status').should('eq', 200)`, but it seems it can't set the alias to selectedModule
For the `cy.route2()` I will try to use it later.

**Comment by elycisjasa123** [comment]
Right now I currently using this one and it works.
Code Structure
```
it.only('should create a first module', () => {
      cy.log('create a module');
      cy.dataTest('create-module').click();
      cy.dataTest('module-name').type('Module 1');
      cy.dataTest('module-description').type('This is module 1');
      cy.dataTest('save-module').click();
      cy.dataTest('snack-bar').should('have.text', 'Module Created');
      cy.wait('@moduleCreation').then(xhr => {
        const moduleId = xhr.response.body as any;
        cy.route('GET', `/api/modules/${moduleId.id}`).as('getSelectedModule');
      });
      cy.wait('@getSelectedModule')
        .its('status')
        .should('eq', 200);
      cy.wait('@getCourseMaterials')
        .its('status')
        .should('eq', 200);
    });
```
[Video Recording Link](https://gitlab.com/elycisjasa123/infotek/uploads/a19cf8ac5e7a4f5b10ba945922889bc8/bandicam_2020-09-25_22-22-11-738.mp4)

**Comment by jennifer-shehane** [comment]
@elycisjasa123 Has your issue been resolved? Can this be closed?

**Comment by elycisjasa123** [comment]
I found a new way but, Still can't able to read an alias in 2 nested  requests

**Comment by elycisjasa123** [comment]
Can you find a way that can set an alias inside the 2 nested route?
```
it.only('should create a first module', () => {
      cy.log('create a module');
      cy.dataTest('create-module').click();
      cy.dataTest('module-name').type('Module 1');
      cy.dataTest('module-description').type('This is module 1');
      cy.dataTest('save-module').click();
      cy.wait('@moduleCreation')
        .its('status')
        .should('eq', 201);
      cy.request({
        url: '/api/me/courses?role=instructor&type=all&page=1',
        method: 'GET',
        headers: {
          Authorization: `Bearer ${Cypress.env('INSTRUCTOR_TOKEN')}`,
        },
      }).then(getCourses => {
        const courseId = getCourses.body[0].id;
        cy.request({
          url: `/api/courses/${courseId}/modules?role=instructor`,
          method: 'GET',
          headers: {
            Authorization: `Bearer ${Cypress.env('INSTRUCTOR_TOKEN')}`,
          },
        }).then(getCreatedModule => {
          const moduleId = getCreatedModule.body[0].id;
          cy.server();
          cy.log(moduleId);
          cy.route('GET', `/api/modules/${moduleId}`).as('selectedModule');
        });
        cy.wait('@getCourseMaterials')
          .its('status')
          .should('eq', 200);
      });
    });
```

**Comment by jennifer-shehane** [comment]
@elycisjasa123 Sorry, I'm not exactly clear on which part of this code is not working. Additionally the video provided shows all tests passing. Please provide a clear example of a failing test, exhibiting a bug within Cypress and we can reopen this issue and investigate it.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
