### ISSUE TITLE
Mock network issue

### ISSUE THREAD

**Issue by swatantra15081986** [cypress-io/cypress#8678]
Mock Testing Issue (Network Response)

Request URL is :-

https://api-docker.com/supplychain-staging/63/e2e/listing/movement/order?movement=Deli&page_number=1&page_offset=10&order_create_date__start=2020-08-01%2000:00:00&order_create_date__end=2020-08-25%2023:59:59&order_update_date__start=2020-08-01%2000:00:00&order_update_date__end=2020-08-25%2023:59:59&order_status=VRF&order_status=ALC&order_status=TBP&order_status=PIK

Using Code :-
```js
 it('XHR: No Mocking', function(){

cy.server()
cy.route('GET','**/63').as('login')
const tabName = $e1.text()
if (tabName === tab) {
$e1.click();
           cy.wait('@login',{timeout:15000}).its('status').should('eq',200)
            cy.get('@login').then(function (xhr) {
               //expect(xhr).property('status').to.equal(200)
                expect(xhr.status).to.eq(200)
                expect(xhr.method).to.eq('GET')
                expect(xhr.request.body.success).to.have.property(true)
               })
```
       

Error after run :- enter image description here Please help.
![Screenshot_2020-09-26-15-47-08-77_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/70620835/94338427-a50c6980-ffe1-11ea-9baa-51633fa4bffd.jpg)

**Comment by flotwig** [comment]
`cy.route()` was removed in [Cypress 12.0.0](https://docs.cypress.io/guides/references/changelog#12-0-0), please try using [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept) instead. Closing this issue since the relevant API has been deprecated and removed.
