### ISSUE TITLE
Cypress >= 5.0 doesn't recognise paths with exclamation mark

### ISSUE THREAD

**Issue by gregid** [cypress-io/cypress#8683]
### Current behavior

If a path to a file has exclamation mark `!` it will result in Webpack Compilation Error:
```
Error: Webpack Compilation Error
multi ./cypress/integration/app2.spec.js
Module not found: Error: Can't resolve 'E:\Projects\' in 'E:\Projects\!Current\morpho'
Looked for and couldn't find the file at the following paths:
[E:\Projects\package.json]
[E:\Projects\index\package.json]
[E:\Projects\index]
[E:\Projects\index.js]
[E:\Projects\index.json]
```

It is documented that question marks `?` won't work with the upgrade but no mention of exclamation mark `!`.

### Desired behavior

Ideally it should work correctly with these paths. If this is not possible it should be properly documented

### Test code to reproduce

Tested only on Windows. Create a path for the spec file with exlamation mark, e.g. `E:\Projects\!Current\myProject\app.spec.js` and run `cypress open`

### Versions

Cypress >= 5.0
OS Windows 10
Browser All

**Comment by jennifer-shehane** [comment]
I can recreate this on Mac also. Not sure if this was expected or not - will have to check with the team.

```
mkdir !Current
cd !Current
mkdir foobar
cd foobar
npm init
npm i --save-dev cypress
cypress open
```

### 4.12.1

<img width="1273" alt="Screen Shot 2020-09-29 at 8 00 21 AM" src="https://user-images.githubusercontent.com/1271364/94502436-25bda680-022a-11eb-93d7-a7fe44475cbc.png">


### 5.0.0

<img width="1275" alt="Screen Shot 2020-09-29 at 7 55 48 AM" src="https://user-images.githubusercontent.com/1271364/94502096-61a43c00-0229-11eb-9a7e-c9d3c59eea00.png">

**Comment by jennifer-shehane** [comment]
Webpack uses `!` for “inline loaders”: https://webpack.js.org/concepts/loaders/#inline

So, yeah, it looks like we will not be supporting `!` within pathnames in Cypress. We will update our documentation accordingly to reflect this. We suggest removing the `!` from any pathnames.
