### ISSUE TITLE
minimum viewport size for desktop-gui needs to be increased

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#869]
The nav overlaps with the project name displaying in lefthand corner.

<img width="570" alt="screen shot 2017-11-03 at 2 11 42 pm" src="https://user-images.githubusercontent.com/1271364/32389467-10aab080-c0a1-11e7-838d-8844b71758c7.png">

~I think this can be fixed in the `packages/desktop-gui` css, but we could also~ set a `minWidth` on the window itself here https://github.com/cypress-io/cypress/blob/code-of-conduct/packages/server/lib/gui/windows.coffee#L129

**Comment by brian-mann** [comment]
Needs to be done in the GUI code (not in CSS).

**Comment by chrisbreiding** [comment]
Is increasing the minimum width the right solution? What if someone has a project name longer than `cypress-example-kitchensink`? 

I think a better solution is to make the desktop-gui more responsive to width changes. Right now, there are too many hard-coded values for how tall certain elements are assumed to be. We could utilize flexbox to help with situations like this.

**Comment by jennifer-shehane** [comment]
^ that's why I mentioned css in desktop-gui at first. I'd have to look back at what we're doing for the nav to remember, but most definitely flexbox is a good solution here.

**Comment by jennifer-shehane** [comment]
- Nav view: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/src/app/nav.jsx
- Nav css: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/src/app/nav.scss
- Nav test: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/nav_spec.coffee#L1
