### ISSUE TITLE
Cannot opens in global mode with duplicate icons

### ISSUE THREAD

**Issue by yassermouahid** [cypress-io/cypress#8690]
### Current behavior
When I lunch the tests using `cypress run ` I get 3 duplicated icons and a window displayed that informs about how to get started 

<img width="803" alt="Screen Shot 2020-09-29 at 5 36 22 PM" src="https://user-images.githubusercontent.com/37110183/94587317-50cfe680-027a-11eb-9fc8-5f3017b4f2f8.png">

When I select the project and click on one of the specs, chrome window is displayed and I get another three cypress icons with the same window shared on this description, It seems like an infinite loop 

### Versions
Cypress: 5.30
Operating system: macOS Mojave
Browser: Chrome

**Comment by jennifer-shehane** [comment]
How did you download Cypress? We recommend downloading using a package manager like npm or yarn. 

Can you send a video of the behavior exactly?

**Comment by yassermouahid** [comment]
I downloaded Cypress using yarn

**Comment by jennifer-shehane** [comment]
May be related to #7393. A video would be helpful here to see what's happening. It appears that cypress is opening in global mode. How are you running Cypress? Are you passing any flags to `cypress open`? 

Does this issue occur when you run our kitchen-sink tests https://github.com/cypress-io/cypress-example-kitchensink? Or does this only occur when testing your project?

**Comment by yassermouahid** [comment]
it is the same problem as #6524, I installed `babel-plugin-istanbul@5.2.0` and it works now
