### ISSUE TITLE
Are the types in net-stubbing correct?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8694]
Cypress v5.3.0

Trying to write a test that shows how to modify the response from the server

```js
cy.route2('styles.css', (req) => {
  req.reply((res) => {
    res.send(`${res.body}
      li {
        border: 1px solid pink;
      }
    `)
  })
})
```

Looking at IntelliSense suggested here

![image](https://user-images.githubusercontent.com/2212006/94605521-3f311380-0267-11eb-8b66-9facb7e745c0.png)

Ok, no JSDoc, fine, let's look at d.ts

![image](https://user-images.githubusercontent.com/2212006/94605571-4fe18980-0267-11eb-8a87-4751c940786a.png)

So we have `reply(interceptor)` I guess, since we want to add to the response from the server

```
export type HttpResponseInterceptor = (res: CyHttpMessages.IncomingHttpResponse, send?: () => void) => void | Promise<void>
```

Ok, so `res` and optional `send`...

```
req.reply((res, send) => {
  console.log(res)
  console.log(send)
```

![image](https://user-images.githubusercontent.com/2212006/94605774-920acb00-0267-11eb-9346-97ef05986176.png)

Ohhh, `res.send` is a function, there is no second parameter

**Comment by flotwig** [comment]
yeah, `send` was from an earlier version of the API design, it is always going to be `undefined` and should be removed:

https://github.com/cypress-io/cypress/blob/857fcf904cffae8d83812f9b12e1235dfdea07ff/packages/net-stubbing/lib/external-types.ts#L69-L70

and these could use some tsdocs:

https://github.com/cypress-io/cypress/blob/857fcf904cffae8d83812f9b12e1235dfdea07ff/packages/net-stubbing/lib/external-types.ts#L49-L55

does that cover it?
