### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8697]
Cypress v5.3.0

```js
/// <reference types="cypress" />
describe('page', () => {
  it('works', () => {
    cy.visit('index.html')
    // check CSS for that div
    cy.get('.example').invoke('css', 'border').should('include', 'solid')
    // throws an error "Cannot read property 'replace' of undefined"
    cy.get('.example').invoke('css')
  })
})
```

The `invoke('css')` throws

<img width="871" alt="Screen Shot 2020-09-29 at 5 08 57 PM" src="https://user-images.githubusercontent.com/2212006/94615951-98547380-0276-11eb-97ed-85a37227d64e.png">

Stack
<img width="661" alt="Screen Shot 2020-09-29 at 5 10 15 PM" src="https://user-images.githubusercontent.com/2212006/94616000-aa361680-0276-11eb-9279-9caf497bf495.png">

Seems to be jQuery problem not checking if `name` is defined

<img width="783" alt="Screen Shot 2020-09-29 at 5 10 45 PM" src="https://user-images.githubusercontent.com/2212006/94616072-ccc82f80-0276-11eb-878a-66838016e9ce.png">

<img width="286" alt="Screen Shot 2020-09-29 at 5 11 07 PM" src="https://user-images.githubusercontent.com/2212006/94616079-d05bb680-0276-11eb-954a-b36e0351827d.png">

Reproduction https://github.com/cypress-io/cypress-test-tiny/tree/css-error

Seems even the latest jQuery 3.4.1 just fails on empty argument :(

![Screen Shot 2020-09-29 at 5 16 09 PM](https://user-images.githubusercontent.com/2212006/94617427-89ba8c00-0277-11eb-9ca0-03a3af53dc08.png)

**Comment by bahmutov** [comment]
Why I would want to invoke `css()` - to see all available properties on the element

**Comment by fralvarop** [comment]
Cypress 5.2 here, getting the same error with this piece of code.

`function rechargeCompletePageDisplayed() {
  cy.wait('@recharges', { timeout: 10000 }).then((xhr) => {
    assert.equal(xhr.status, 200)

    cy.getByDataHook('price-selected-succeed').should('be.visible')
    cy.getByDataHook('phone-recharge-succeed').should('be.visible')
  })
}`

**Comment by bahmutov** [comment]
@fralvarop are you sure this is the same error from jQuery? Could you verify this by posting a screenshot of the error stack? What happens when you comment you `cy.getByDataHook` lines?

**Comment by fralvarop** [comment]
> @fralvarop are you sure this is the same error from jQuery? Could you verify this by posting a screenshot of the error stack? What happens when you comment you `cy.getByDataHook` lines?

Thereis the screenshoot with `cy.getByDataHook` lines commented

![image](https://user-images.githubusercontent.com/40148790/95049737-a6791880-06ea-11eb-8a47-3205f7c213f1.png)

**Comment by bahmutov** [comment]
Now open the DevTools console and click on the "Print to console" to see the stack trace
