### ISSUE TITLE
FAQ - Install on Wheezy

### ISSUE THREAD

**Issue by MathRobin** [cypress-io/cypress#87]
If you try to install Cypress on wheezy, you'ill have an error which suggest you you use glibc 2.13 (last stable version available on Wheezy) and cypress needs 2.14. To fix this, you have to add

    deb http://ftp.debian.org/debian experimental main
    deb http://ftp.debian.org/debian sid main

to you /etc/apt/sources.list

After do an ``sudo apt-get update`` and try ``sudo apt-get -t experimental install libc6-dev``.

Now it's fix and you can run ``cypress install `` again

**Comment by brian-mann** [comment]
Thanks. Added to a new troubleshooting section of the wiki guides.

https://github.com/cypress-io/cypress/wiki/troubleshooting#installation

**Comment by MathRobin** [comment]
Question apart : How to get early access ? I submit to the form but really want to deploy cypress for my company.

**Comment by brian-mann** [comment]
Come into the [gitter channel](https://gitter.im/cypress-io/cypress) and message me
