### ISSUE TITLE
504 should be treated as a Network Error

### ISSUE THREAD

**Issue by bjowes** [cypress-io/cypress#8707]
### Current behavior

Cypress puts all request errors in two categories: "status code errors" and "network errors". These result in different behavior. For instance, they have different aspects of retry configuration and retry defaults. When running Cypress behind a proxy, and the proxy is alive, all upstream network errors will be transformed into status codes (HTTPS tunnels are an exception).

One simple example where this causes undesired behavior is during startup. Cypress will check if the site configured in baseUrl is available. When running behind a proxy it will be considered alive despite the proxy replying with 502 or 504, essentially meaning that the target site cannot be reached. Hence, the test suite will execute. When there is no proxy in the way, Cypress will correctly detect that the site is down, and stop before executing the suite.

### Desired behavior

When using Cypress behind a proxy, some status codes would make more sense to treat as network errors. The typical examples being 502 (Gateway Error) and 504 (Gateway Timeout). These signal that the target server could not be reached, typically caused by the proxy receiving a ECONNREFUSED, or no response at all. Wether 502 or 504 is used for these scenarios depends on the proxy implementation. 

From my perspective, when running behind a proxy, the fact that the proxy itself is responding isn't sufficient to rule out network errors. They just need to be detected in a different manner.

This should apply to the startup alive check, but also to all network requests during test execution.

### Test code to reproduce

I can provide a test repo if desired. But my point is not to show highlight specific issue, but rather discuss the principle of handling 502 and 504 status codes. 

### Versions

Cypress 5.3.0
Windows 10, Mac OS

### Help offered

I have started investigating the source to implement this, and will be happy to do that if this suggestion makes sense to the maintainers.

**Comment by flotwig** [comment]
Hey @bjowes, you've probably found the code for the retry logic by now, but if not, it's all in `packages/server/lib/request.js`

The way we originally came up with the rules around when it's appropriate to retry a request, and when a failure should propagate through to the client, was by observing Google Chrome's behavior. We noticed that starting Google Chrome with the Cypress proxy changed the Chrome's retry behavior, so the retry logic in `request.js` was added to compensate for that. The goal was to make the retry behavior inside of Cypress match the retry behavior of a real-world browser.

There are end-to-end tests that are `.skipped` that we use to verify the behavior of Google Chrome in these cases: https://github.com/cypress-io/cypress/blob/f33f8bae20a99c044ff4e0563369561576094894/packages/server/test/e2e/8_network_error_handling_spec.js#L255-L349

You can see towards the end, that there are test cases that show that inside of Google Chrome, 502/503 are not retried by Chrome when /no/ proxy is set.

I also did some testing of my own, to see if a 502/503/504 is retried by Chrome when a proxy IS set: https://github.com/flotwig/google-chrome-behavior-tests/blob/master/src/network-error-handling.spec.ts#L52-L71

My tests show that, even when an HTTP proxy is used with Chrome, Google Chrome does not retry on a 502/503/504 response from the server.

I think this makes sense - while proxies can technically send 502/504, so can reverse proxies like `nginx` or Cloudflare, which you presumably wouldn't want to retry.

Additionally, an HTTP proxy is more than capable of destroying the TCP connection between proxy and client upon an upstream network error, which is what Cypress's proxy does. That /is/ retried by Chrome, and is also retried by Cypress. I think this might be the "more correct" behavior for an HTTP proxy, compared to sending a 502 or 504, which is indistinguishable from the real server's response.

In light of this, I don't think it makes sense for the Cypress proxy to retry 502's and 504's. Please let me know if I've missed anything.

**Comment by bjowes** [comment]
Hi @flotwig, thanks for the detailed answer. Impressive that you have put so much effort into investigating this already!

I fully agree that mimicking Chrome is probably the best approach for Cypress, so if this is the behavior of Chrome then we shouldn't change it. From a theoretical perspective, 502/504 are indeed network errors and could be treated as such. However, as you point out, they are also used in many other cases, and it is virtually impossible for the client to tell if it is a type of error that should be retried or not.

I have been looking for some kind of official documentation for how a HTTP proxy should behave, but I haven't found any good comprehensive resources. The background is that I am working to improve the behavior of the ntlm-proxy in my plugin (cypress-ntlm-auth). 502/504 felt like the most clean way to handle upstream connectivity issues, but I will consider the approach you suggest with simply mimicking the error on the client socket instead. Since Cypress handles this gracefully and does retries in that scenario I think it would make sense. This would also resolve the site connectivity check on startup issue that I described. 

However, I still think most proxies doesn't behave this way, meaning that the connectivity check gives a false positive when Cypress is behind a proxy. In that particular case, I still think it would make sense to fail the connectivity check on 502/504. Maybe not retry it if you don't think that makes sense, but at least fail the check. I think it is very unlikely that the tests can run properly if the baseUrl returns 502/504.
