### ISSUE TITLE
Replace Moment.js within the Cypress project.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#8714]
### Current behavior

Cypress requires Moment.js in the desktop-gui, cli, driver, and server packages.

Moment.js is now considered legacy and is in maintenance mode. They recommend moving to other projects. See https://momentjs.com/docs/#/-project-status

### Desired behavior

Replace Moment.js with other smaller, more up to date package(s). See their [recommendations](https://momentjs.com/docs/#/-project-status/recommendations/). We would be open to PRs that replace parts of Moment.js one piece at a time. Also - using newer libraries for any new Date uses is recommended.

### Versions

5.3.0

**Comment by osamajandali** [comment]
I want to start working on this 🔥

**Comment by pufuleterau** [comment]
Hello, could i work on this ?

**Comment by CarlyRaeJepsenStan** [comment]
I can work with this!  I have had experience converting my own projects from Moment.js to Day.js.

**Comment by jennifer-shehane** [comment]
Yes we are open to PRs - even ones that partially replace some of the moment deps are fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by jonstone904** [comment]
So will `Cypress.moment` still be exposed after replacing moment.js or is best practice moving forward to not use it?

**Comment by bahmutov** [comment]
It is still bundled and exposed but we plan to remove it starting with version 7 because the moment.JS itself is deprecated

**Comment by jonstone904** [comment]
Thanks, @bahmutov! I'll start looking into migrating to one of their recommendations.

**Comment by jennifer-shehane** [comment]
dayjs has been pretty comparable for what we use moment for and is likely what we will move Cypress internal code to use.

**Comment by jonstone904** [comment]
Thanks, @jennifer-shehane! dayjs it is then

**Comment by JohnnyFun** [comment]
Out of curiosity, what's the purpose of `cy.[datelibrary]`? Why not just load it in separately from cypress? That's what we do with dayjs and works fine. I must be missing something.

**Comment by jennifer-shehane** [comment]
We are internally using these libraries within Cypress, so the library is already there. When we first created Cypress we just exposed the methods as a convenience. I agree that this doesn't feel as necessary anymore as it did at the time.
