### ISSUE TITLE
not possible to get aws credentials using cypress

### ISSUE THREAD

**Issue by johanneslundin** [cypress-io/cypress#8715]
### Current behavior
It doesn´t seem possible to get my local credentials from aws.
If i run the test outside cypress, it work just fine. I can of course add the credentials in a config file in the cypress project but I´m not allowed to do that.

![image](https://user-images.githubusercontent.com/43027282/94786456-4a07b780-03d1-11eb-8051-70313d95d31c.png)

### Test code to reproduce
This code can be tested if an message and topicArn is added. I can not paste mine. The below params is just an example
```ts
//commands.ts
import { SNS } from 'aws-sdk';
const sns = new SNS({
  region: 'eu-central-1'
});

Cypress.Commands.add('SendSnsMessage', params => {
  return sns.publish(params).promise();
});
```

```ts
//integration-test.spec.ts
const params = {
  Message:
    '{ <add your message here> }',
  TopicArn:
    '<add your topic here>',
};

 cy.SendSnsMessage(params).then(data => {
cy.wrap(data.MessageId)
      .should('not.be.undefined')
      .then(() => {
        cy.log(
          `Message ${params.Message} send sent to the topic ${params.TopicArn}`,
        );
});
```

### Versions
Cypress 5.2

**Comment by johanneslundin** [comment]
I found that the reason seems to be that below is fetched in the commands file which is run in cypress. If i extracted it into a js fil and fetched it from the plugins file using cy.task, it worked.

 `import { SNS } from 'aws-sdk';
const sns = new SNS({
  region: 'eu-central-1'
});`

**Comment by Qaleem1** [comment]
Could you provide an a example please

**Comment by joephilanthropi** [comment]
I just ran into the same issue. I can confirm that putting the SDK logic inside of a Cypress task resolves the problem

**Comment by AlexSdet** [comment]
@joephilanthropi Can you please show example how to do it, Im very new to this Cypress task stuff, but need to solve the same issue. Thank you!
