### ISSUE TITLE
Cypress tests doesnt run in Gitlab CI

### ISSUE THREAD

**Issue by taiwoobe** [cypress-io/cypress#8716]
Hello,

I am currently running the test on the Gitlab CI and it doesn't run.. It basically just freezes and after the 1hrtimeout, the pipeline fails.
I have attached a screenshot to this effect.

I am making use of the 5.2.0 version of Cypress. 

I added this to my `plugin/index.js` file but still doesn't work

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--disable-dev-shm-usage');
      return args
    }
    return args
  });
}
```

 [
![Screenshot 2020-10-01 at 10 48 24](https://user-images.githubusercontent.com/9431878/94788485-e92dae80-03d3-11eb-9c07-1006ec9cca26.png)
](url)

Hoping to get a feedback on this please.

**Comment by peterlazzarino** [comment]
Does it stop before any of the tests run, and it just times out after an hour with no execution? I was able to fix similar lock-up issues with the --disable-dev-shm-usage flag but it would usually happen after many tests had ran. Might help to see what this test looks like, and your plugin / support files.

**Comment by taiwoobe** [comment]
It stops before any of the tests run at all.. 

Here is the test I am running. I have configured the baseUrl in the cypress.json file.  It runs perfectly locally. but on the CI, it doesnt run at all. 

/// <reference types="Cypress" />

context("Login Page", () => {
  beforeEach(() => {
    cy.visit(Cypress.config().baseUrl);
  });

  it("Should fill login form and redirect to dashboard", () => {
    // Fill the email
    cy.get("#email")
      .type("eve.holt@reqres.in")
      .should('have.value', "eve.holt@reqres.in");

    // Fill the password
    cy.get("#password")
      .type("cityslicka")
      .should("have.value", "cityslicka");

    // Locate the login button and submit the form
    cy.get(".login-button").click();
    
    // Verify the app redirected you to the dashboard
    cy.location("pathname", { timeout: 50000 }).should("eq", "/dashboard");
  });
});

**Comment by jennifer-shehane** [comment]
Using `console.log` in a spec file will just log to the browser's console, not to the stdout. You can use this recipe to log a value to the stdout console: https://docs.cypress.io/api/commands/task.html#Usage

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by taiwoobe** [comment]
This is the command I executed 

/home/node/.npm-global/bin/DEBUG=cypress:* cypress run

but then I get an error saying 
/bin/bash: line 142: /home/node/.npm-global/bin/DEBUG=cypress:*: No such file or directory

But without the debug command, cypress runs normally.

**Comment by taiwoobe** [comment]
So I configured my app using the curl command to run on http://app:9000 and I can validate that the app is fine cos on the terminal in the CI, I see the html code of the home page outputted and fine. In my cypress.json file, I have configured the baseUrL to be the same http://app:9000. and in the beforeEach function of the cypress test, i did this - 

**beforeEach(() => {
    cy.visit(Cypress.config().baseUrl);
  });**

The CI doesnt complain of server not running but then the test doesnt pass that stage.. It just keeps loading.

**Comment by DanailMinchev** [comment]
If you downgrade to Cypress `4.12.1` does it work?
Seems like it is similar problem to https://github.com/cypress-io/cypress/issues/8508 which I created.

**Comment by JessicaSachs** [comment]
@taiwoobe the DEBUG flag is an environment variable, not an executable. You want to run `DEBUG=cypress:* cypress run`

**Comment by taiwoobe** [comment]
@JessicaSachs Yeah I later figured out and the result from the debug log was quite a lengthy one so I couldn't paste it here. I think it has something to do with the web security because in the logs, I can see that it's trying to access HTTPS instead of the HTTP that I set in the baseURL. This might be the same issue @DanailMinchev is having. I intend to build a new docker image for my CI that allows me configure my baseURL to have https. Once I do and test it, I would post the outcome here.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
