### ISSUE TITLE
.click/dblclick() should support extra event properties

### ISSUE THREAD

**Issue by dwelle** [cypress-io/cypress#872]
- Cypress Version: `1.0.2`

### Is this a Feature or Bug?

Feature

### reasoning

Currently, there's no other way to specify e.g. `shiftKey` when issuing a `.click()` command. IMO, it should work same as `.trigger()` and thus allow to supply `shiftKey` and others in `options`.

**Comment by jennifer-shehane** [comment]
You should be able to achieve this with a combination of `.type()` and `.click()`. Documentation: https://on.cypress.io/type#Global-Shortcuts

Code:
```js
// execute a SHIFT + click on the first <li>
// {release: false} is necessary so that
// SHIFT will not be released after the type command
cy.get('body').type('{shift}', {release: false}).get('li:first').click()
```

Let us know if this does what you expect.

**Comment by dwelle** [comment]
Wow, that wouldn't have ever occured to me. Apart from being obscure, it's pretty clumsy to do this:

```
cy.get("body").type("{shift}", { release: false });
cy.get(selector).click();
cy.get("body").type("{shift}");
```

or using trigger (emulating similar behavior as `click` does):

```
cy.get(selector).trigger("mousedown", { shiftKey: true, which: 1 });
cy.get(selector).trigger("focus");
cy.get(selector).trigger("mouseup", { shiftKey: true, which: 1 });
cy.get(selector).trigger("click", { shiftKey: true, which: 1 });
```

Main point of this issue - should the API of mouse-event-based commands (trigger, click, blclick) be aligned? I don't see any reason why not to support the same `options` as `trigger()` does.

**Comment by brian-mann** [comment]
I agree in spirit and can't remember the reason we didn't do it this way in the first place.

@chrisbreiding may remember.

I agree that the `{ release: false }` is pretty clumsy. Maybe we missed the mark on this one.

**Comment by dwelle** [comment]
Being able to hold and not release a meta key can be useful, and being able to specify meta keys when `type`ing is good too. It's just not very suitable for this purpose, I'd say.

**Comment by chrisbreiding** [comment]
I don't think we had a terribly good reason. I think we were mostly focused on `cy.type` and considered changing `cy.click` to be an extra feature for another day.
