### ISSUE TITLE
Spammers

### ISSUE THREAD

**Issue by dsaul** [cypress-io/cypress#8734]
I love how you losers keep on spamming my inbox with your trite marketing bullshit, if people unsubscribe, YOU UNSUBSCRIBE THEM. So much disrespect coming from your team.

**Comment by dsaul** [comment]
Guess what is NOT going to happen? Me ever giving you people money. Good job failing.

**Comment by dsaul** [comment]
You have been reported as being in violation of CASL, in a perfect world you people would be fucked coming over the border :) We know that that will never happen, but at least there is record now.

**Comment by jennifer-shehane** [comment]
Please be mindful of our Code of Conduct when interacting in our issues. https://github.com/cypress-io/cypress/blob/develop/CODE_OF_CONDUCT.md
