### ISSUE TITLE
Cypress tests are failing after upgrading to v5.3.0

### ISSUE THREAD

**Issue by aartisoni1** [cypress-io/cypress#8746]
### Current behavior
I have following cypress tests passing in 4.7.0 without any errors but I'm getting a failure after upgrading cypress to any version after 4.7.0. 
![image](https://user-images.githubusercontent.com/47206631/95028031-b51afc00-06f9-11eb-9bd3-231edd70c6bd.png)

### Desired behavior
In cypress 4.7.0 I was able to connect to the database and look for url in message table and visit the URL. This test is failing in every cypress version after 4.7.0.

### Test code to reproduce
cypress.json has following:
```json
"env": {
        "db": {
            "userName": "test",
            "password": "test",
            "server": "sqlserver",
            "port": 1433,
            "type": "mssql",
            "options": {
                "database": "testDB",
                "encrypt": true,
                "rowCollectionOnRequestCompletion": true
            }
        }
    }
```

plugins\index.js:
```js
  const sqlServer = require('cypress-sql-server');
  module.exports = (on, config) => {
     tasks = sqlServer.loadDBPlugin(config.env.db);
     on('task', tasks);
   }
```
support\index.js

```js
  import sqlServer from 'cypress-sql-server';
  sqlServer.loadDBCommands();
```

cypress test:

```js
  import DbAccess from "../Database/DbAccess.js";
   it("visit url", () => {
      let urlForTest = getUrl();
      cy.visit(urlForTest);
   });
```

getUrl() function:

```js
   async function getUrl() {
      let urlToVisit = await DbAccess.getQuery('SELECT TOP(1) [Message] FROM [dbo].[Message] ORDER BY ID DESC');
      return urlToVisit;
   }
```
DBAccess class:

```js
  class DbAccess{ 
    static getQuery(sqlQuery) {
        return new Promise((resolve) => {
           cy.sqlServer(sqlQuery).then((result) => {
              resolve(result);
           });   
        });
     };
  };
module.exports = DbAccess;
```

### Versions
All cypress versions 4.7.0

**Comment by Lusitaniae** [comment]
log the result of `await DbAccess.getQuery('SELECT TOP(1) [Message] FROM [dbo].[Message] ORDER BY ID DESC');`

**Comment by sainthkh** [comment]
Sorry for the late reply.

It's not working because the return type of `getUrl()` is not a string or a plain JavaScript object. It's a `Promise`. 

The code below would solve the problem. 

```js
it("visit url", async () => {
      let urlForTest = await getUrl();
      cy.visit(urlForTest);
   });
```

**Comment by shivanijamadar** [comment]
Hello, in which file do we have to use the getUrl() function mentioned above ?
