### ISSUE TITLE
Chrome 81 - Cypress 5.2.0: "The automation client disconnected. Cannot continue running tests."

### ISSUE THREAD

**Issue by mariesheilag** [cypress-io/cypress#8748]
### Current behavior

We did an upgrade for cypress from `4.12.1->5.1.0->5.2.0`.
Before doing the major upgrade, everything is working fine but we're now getting the following error:

"The automation client disconnected. Cannot continue running tests."

We already did the following workaround from the documentation:

1. Disable usage of `/dev/shm:`

```
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.name === 'chrome') {
      launchOptions.args.push('--disable-dev-shm-usage')
    }
    return launchOptions
  });
};
```

2. Since we are using docker-compose, we set the `ipc` to `host`

```
version: '3.5'
services:
  cypress_1:
    image: ${CYPRESS_IMAGE}
    ipc: host
```

### Desired behavior

Specs should run just fine and pass as expected.

### Versions

Cypress 5.2.0
Chrome 81
Base Image cypress/browsers:node12.14.1-chrome85-ff81

**Comment by SonaliQA** [comment]
I am having the issue while running Scripts on local machine by cypress UI. 
**Chrome : 91 , cypress: 7.5.0**
![image](https://user-images.githubusercontent.com/62263280/122601154-e1379c80-d03e-11eb-9b10-7acac1b87000.png)

**Comment by ChristusArulanantham** [comment]
I am facing the same issue with Cypress 7.6.0. 
I am not running this on docker but on my windows machine and have tried the above suggestion and it did not resolve the issue.
If there is a fix then it would be great.

**Comment by IMLaoJI** [comment]
I am also facing the same problem with Cypress 7.6.0.

**Comment by genehynson** [comment]
I am also facing this issue with version `8.2.0` on firefox

**Comment by wliao008** [comment]
we're on v8.5 having the same issue.on our Jenkins that's running on AWS ECS.

All tests run fine locally via container when I set ipc to host. We've disabled shm (via the index.js) and set ipc to host (via the ECS task definition). We've also updated the ECS plugin for Jenkins, but so far still getting this err.

**Comment by pwkip** [comment]
same problem here. Using docker. Everything worked fine with my test suite. The problem occured after I switched to a new mac.

**Comment by nagash77** [comment]
hi @pwkip, I am going to close this issue as it is quite old at this point.  If folks are seeing this behavior in current versions of Cypress please open a new ticket with a reproducible example and we will be happy to investigate.
