### ISSUE TITLE
Add project editorconfig

### ISSUE THREAD

**Issue by dwelle** [cypress-io/cypress#875]
Add a project [`.editorconfig`](http://editorconfig.org/) file, to make it easier for contributors.

Suggested (`/.editorconfig`):

```
root = true

[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
```

Not sure if those apply project-wide.

**Comment by Saibamen** [comment]
Why not Prettier?

**Comment by jennifer-shehane** [comment]
Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by Saibamen** [comment]
PR: https://github.com/cypress-io/cypress/pull/15791
