### ISSUE TITLE
Show aliases for all matched route interceptors

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8752]
Take the test that sets up 3 matchers for `/favorite-fruits` Ajax call

```js
it('matches all routes that do not respond', () => {
  cy.route2('**/*-fruits').as('fruits')
  cy.route2('**/favorite-*').as('favorite')
  cy.route2('**/favorite-fruits').as('favorite-fruits')

  cy.visit('/')
  // matches all 3 routes
  cy.wait('@fruits')
  cy.wait('@favorite')
  cy.wait('@favorite-fruits')
})
```

The app executes `GET /favorite-fruits` call and all 3 match

![](https://user-images.githubusercontent.com/2212006/95089608-5605b900-06f2-11eb-8e0d-ebf3c347eede.png)

Look at the screenshot though: it shows only the first alias `fruits` matched 3 times, which is incorrect. Instead, we probably should show labels for all matched network aliases: `fruits`, `favorite`, `favorite-fruits`

## Reproduction
Run test "matches all routes that do not respond" from https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__route2/cypress/integration/matching-spec.js

**Comment by jennifer-shehane** [comment]
Repro outside of repo

```js
it('matches all routes that do not respond', () => {
  cy.route2('**/*-fruits').as('fruits')
  cy.route2('**/favorite-*').as('favorite')
  cy.route2('**/favorite-fruits').as('favorite-fruits')

  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/favorite-fruits')
    xhr.send()
  })
  // matches all 3 routes
  cy.wait('@fruits')
  cy.wait('@favorite')
  cy.wait('@favorite-fruits')
})
```

**Comment by sainthkh** [comment]
![Peek 2020-10-27 15-50](https://user-images.githubusercontent.com/8130013/97266672-346c9d00-186c-11eb-8dd3-d64522fe26b7.gif)

By clicking the small triangle on the left, we can see all 3 aliases happened (check the gif above). But this triangle is small and hard to recognize it's clickable. 

My suggestion is:

* Don't show alias name when it's matched multiple times. Only show them when the req is expanded. 
* Expand the req when the alias times number is clicked. 

I also thought about expanding req by default. But showing the same req url multiple times might not be a good idea. 

I want your thoughts.

**Comment by jennifer-shehane** [comment]
Yah, I see how it's collapsed because it's the exact same request. 

I'm kind of wondering how prevalent this problem is. What's the use case? Why is someone setting up 3 aliases for the same request - or is this a mistake, you didn't mean for it to match and you'd like to see the actual requests to debug why?
