### ISSUE TITLE
No requests appear in Cypress app (chrome on macOS)

### ISSUE THREAD

**Issue by Count174** [cypress-io/cypress#8757]
### Current behavior
Usually, to check a certain test case, I just run it via Cypress app. 
I have some `cy.wait(@trsatus)`'s that waits for the response from API
The problem is that when I run test case for the first time, cypress app doesn't show any requests

<img width="699" alt="cypress 2020-10-06 15-14-23" src="https://user-images.githubusercontent.com/55132369/95190006-1a4d1b00-07e8-11eb-9bf0-868ff8b079b0.png">

When I reload this test case (by clicking "R" button), requests appear in cypress and everything looks fine
<img width="675" alt="cypress 2020-10-06 15-17-23" src="https://user-images.githubusercontent.com/55132369/95190012-1d480b80-07e8-11eb-8490-329888fce3d4.png">

### Desired behavior
It's supposed that requests appear in cypress app after every run, especially the first one

### Test code to reproduce

```js
describe('Transactions', function(){
  describe('Adds new income #smoke #transactions', function() {

before(function() {
    cy.login() 
    cy.server()
    cy.route({
        method: 'GET',
        url: 'https://example.ru/api/transactions?*',
         status: [200]
    })
    .as('trstatus')
})


      it('adds income', function() {

      

    cy.get('.scroll-wrapper > .menu-items')
    // cy.get('.sidebar-header-controls').click({force: true})
    cy.get('[ng-class="{\'active\': includes(\'app.transactions\')}"] > .icon-thumbnail').click()
    cy.wait('@trstatus');
......
......
}}
})
})
```

### Versions
Cypress 5.0.0
macOS Catalina 10.15.7
Chrome 85.0.4183.121

**Comment by Count174** [comment]
UPD1: Updated Cypress to 5.3.0 - issue still can be reproduced
UPD2: Noticed that `cy.login()` that executed before test body has XHR requests displayed, but requests in test body are not displayed until I re-run this test.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Doesn't it work with the new `cy.intercept()` API? As `cy.route()` is deprecated, the problem might not be fixed.

**Comment by Count174** [comment]
> Sorry for the late reply.
> 
> Doesn't it work with the new `cy.intercept()` API? As `cy.route()` is deprecated, the problem might not be fixed.

Yep, seems like `intercept` fixed this issue, I haven't experienced that for quite long time after that.
