### ISSUE TITLE
SRI integrity attribute fails to get rewritten when a redirection page ends up with a different domain 

### ISSUE THREAD

**Issue by yunj** [cypress-io/cypress#8769]
### Current behavior
Our test app starts with `zero.com` and redirects to a page with the different domain `zero-test.com` in the middle of the workflow. 
According to https://github.com/cypress-io/cypress/issues/2393#issuecomment-611645822, I have set `experimentalSourceRewriting` to `true`. I did see the integrity attribute gets rewritten when the runner container's iframe src has the same domain as the running page, but it does not when the redirection page has a different domain.

The iframe src is set to domain `zero.com` at the beginning of the test.
![runner_container_iframe_src](https://user-images.githubusercontent.com/18545475/95314356-b280f800-08ed-11eb-9883-95646eff5292.PNG)

If the redirection page's domain is different, e.g., `zero-test.com`, integrity attribute does not get rewritten.
![integrity](https://user-images.githubusercontent.com/18545475/95314383-b876d900-08ed-11eb-94fe-b0e1f28c03e3.PNG)

### Desired behavior
The integrity attribute gets rewritten to `cypress:stripped-integrity` even if domains are different otherwise resources are blocked.

### Versions
Cypress: 5.3.0
Chrome: 85
Windows: 10

**Comment by yunj** [comment]
Hi @jennifer-shehane could you please confirm if this is the expected behavior? Thanks.

**Comment by jennifer-shehane** [comment]
Can you explain how this redirection is happening? How are you navigating to a different domain other than the domain in the Cypress window?

**Comment by yunj** [comment]
Hi @jennifer-shehane thanks very much for your reply. Redirecting to a different domain after SSO login happens. Is it correct that integrity attribute cannot be rewritten if the redirection ends up with a different domain?

**Comment by yunj** [comment]
Hi @jennifer-shehane could you please verify if integrity attribute cannot be rewritten if the redirection ends up with a different domain? Thanks.

**Comment by yunj** [comment]
Hi @jennifer-shehane do you need more information? Thanks.

**Comment by jennifer-shehane** [comment]
From my memory, I think we do not strip integrity properties from cross domain redirects.

**Comment by yunj** [comment]
Hi @jennifer-shehane could you please add this feature? Thanks.

**Comment by yunj** [comment]
Hi @jennifer-shehane and @flotwig  could we strip integrity attributes from cross domain redirects? Thanks.
