### ISSUE TITLE
Feature request: Trash screenshots folder before running tests via UI (cypress open)

### ISSUE THREAD

**Issue by jauggy** [cypress-io/cypress#8776]
### Current behavior
1. Add cy.screenshot() to your test case
2. npx cypress open
3. Press the button to run your test. Repeat.
4. Your screenshot folder will have multiple screenshots

### Desired behavior
1. Have a config to allow you to trash the screenshots folder before tests are run. There is a config value that does work with npx cypress run but not when running tests with cypress open

### Test code to reproduce
See above

### Versions
cypress@5.3.0

**Comment by jennifer-shehane** [comment]
I’m thinking that the same config could be extended to remove screenshots during open when the ‘rerun’ button is pressed. Although the concept of ‘run’ is different here comparing `cypress run` to `cypress open`.

**Comment by jauggy** [comment]
> I’m thinking that the same config could be extended to remove screenshots during open when the ‘rerun’ button is pressed. Although the concept of ‘run’ is different here comparing `cypress run` to `cypress open`.

Yes it makes more sense that it trashes when the top right button pressed as opposed to when cypress open is called.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
