### ISSUE TITLE
Add PR review/merging process to contributing.md

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress#878]
Document a standardized process for reviewing and merging PRs

**Comment by jennifer-shehane** [comment]
Here are my overly detailed notes on editing open PRs before merging using solely GUI interfaces (not `git` in terminal):

- Make sure you've been given edit access (edit icon on a committed file is there)
- Open SourceTree in `cypress`
- Add a new remote (repository->add remote in main menu)
- call 'name' the name of contributor / paste url of contributors remote (this can be found in the PR at the bottom within command line instructions)
- after adding remote, fetch (right click on new remote) - you should see all of his branches now
- double click on the corresponding branch that was named in the PR
- hit OK in the dialog - this creates a new local branch of the same name
- The local branch should now show up in GitHub Desktop App
- DO NOT PUSH IN GITHUB DESKTOP OR SYNC IN GITHUB DESKTOP!
- when you are done with your work and ready to push, click PUSH at the top of the SourceTree
- under 'push to repository' change 'origin' to the remote branch you previously created, press OK.
- when you're ready to MERGE the PR, click on the little dropdown and click 'Squash and merge' on the PR in GitHub website.
