### ISSUE TITLE
Asserts and Errors not failing test within cy.route2

### ISSUE THREAD

**Issue by kirstydarragh** [cypress-io/cypress#8793]
### Current behavior
I'm trying to get a download test to work. Am doing this by intercepting a graphql call (so the page load timeout issue does not occur) and while I am at it, I would like to verify stuff in the request. I found this page https://glebbahmutov.com/blog/smart-graphql-stubbing/ which is super helpful. However whenever I do an assert within the route handler function (and it fails) it does not fail the test. Sorry if this is already known about but the documentation in route2 seems to indicate that you can do assertions within there. To get around this I have to do .as('saveRequest') and then do cy.wait(). . .. several times until I hit the right request as there are lots of graphql calls going on which are only distinguishable by their operationName, once I find the one with the right operationName, then I can do the assertion I need to do in there.

### Desired behavior
As there are lots of graphql calls, it would be preferable to be able to do any required assertion within the route2 routeHandler instead.

### Test code to reproduce
cy.route2(
        {
          method: 'POST',
          url: 'xxxxxxxx/graphql',
        },
        (req) => {
          const g = JSON.parse(req.body)
          if (g.operationName === 'xxxGraphqlOperationIWantToCheck') {
            expect(g.variables.someArray.length).to.equal(3); // Can see Cypress is failing this line, but the test is passing
            req.reply({
              body: {
                data: {},
              },
              headers: {
                'access-control-allow-origin': '*',
              },
            });
          }
        },
      )

### Versions
Cypress 5.3.0
Mac
Chrome

**Comment by bahmutov** [comment]
@flotwig I thought we could do assertions inside the handlers, but not `cy` commands?

**Comment by bahmutov** [comment]
@kirstydarragh can you post a screenshot of the error message, please?

**Comment by kirstydarragh** [comment]
[
<img width="643" alt="passing-test-issue" src="https://user-images.githubusercontent.com/46343745/95511188-099ad180-09af-11eb-8d92-892a2d59bfb1.png">
](url)

**Comment by kirstydarragh** [comment]
(sorry not sure if that helps!)

**Comment by bahmutov** [comment]
Gotcha - so the test finishes before the assertion runs (and fails, but by then the test is already finished). Read https://www.cypress.io/blog/2020/01/16/when-can-the-test-stop/ and wait for the network call from the test, ensuring it waits for the assertion to execute.

**Comment by flotwig** [comment]
There is also a bug that affects errors thrown in `cy.route2` res/req callbacks - failed assertions there will not necessarily fail the test, due to this bug: #8802
