### ISSUE TITLE
Command Log's click displays Object{9} and other nonsense when click({multiple: true})

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#88]
Whenever you pass options `{multiple: true}` to `cy.click()`, each click command in the command log displays nonsense data like `Object{9}` or `{interval: 16}`, etc.

**Example Code**
```
cy.get("[data-js='remove-form-template']").click({multiple: true})
```

**Command Log Screenshot**
<img width="572" alt="screen shot 2015-11-30 at 11 14 08 am" src="https://cloud.githubusercontent.com/assets/1271364/11477027/cd20d934-9753-11e5-8452-b82cd0cefc07.png">

**Comment by brian-mann** [comment]
Fixed in [`0.12.7`](https://github.com/cypress-io/cypress/wiki/Changelog#0127-11302015).

**Comment by ntgussoni** [comment]
@jennifer-shehane  @brian-mann  HI! Im having a similar issue when passing force to .click
this is my code. Could this be happening again?

```javascript
Cypress.Commands.add('dropdownSelectByText', (selector, text = '', force = false) => {
  cy.get(selector).click({ force: force });
  cy.contains('some-other-selector', text).click({ force: true});
]});
```
for some reason the second force is logged properly but not the first.

![image](https://user-images.githubusercontent.com/10161067/49042504-1d683080-f1a7-11e8-9777-882be203b9ee.png)

**Comment by ntgussoni** [comment]
After some digging around, I can say that this happens when you pass `{ force: false }` which is the default. The console message drove me crazy though.
The issue seems to be around here https://github.com/cypress-io/cypress/blob/dd56faf97ad6e4713e785c0bf800f3a1463d7a1a/packages/driver/src/cypress/utils.coffee#L140

**Comment by jennifer-shehane** [comment]
Hey @ntgussoni, can you open up a new issue and reference this comment there? This definitely should not be printing this. It's probably trying to print all default options? Not sure.

**Comment by ntgussoni** [comment]
> Hey @ntgussoni, can you open up a new issue and reference this comment there? This definitely should not be printing this. It's probably trying to print all default options? Not sure.

@jennifer-shehane  Created this https://github.com/cypress-io/cypress/issues/2847 
We can discuss it there, and I'll try to get a PR to fix that when we come up with a solution.
