### ISSUE TITLE
Some asynchronously thrown spec errors do not fail test

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#8802]
### Current behavior

Uncaught rejections thrown in tests that use `done` will not fail the test when no `cy` chain is active:

https://github.com/cypress-io/cypress/blob/f65fd61d1e81597cb8b1e3e3d95c73a5ce869dac/packages/server/test/support/fixtures/projects/e2e/cypress/integration/caught_async_sync_test_spec.coffee#L89-L95

Similar behavior exists for other unhandled rejections:

https://github.com/cypress-io/cypress/blob/f65fd61d1e81597cb8b1e3e3d95c73a5ce869dac/packages/server/test/support/fixtures/projects/e2e/cypress/integration/caught_async_sync_test_spec.coffee#L70-L73

Potentially related: some asynchronous test failures are incorrectly attributed to the AUT, not the spec window.

### Desired behavior

Correctly attribute unhandled rejections and exceptions to the spec or the AUT, do not miss handling any errors.

### Test code to reproduce

See #8221

**Comment by flotwig** [comment]
This affects `cy.route2` req/res callbacks pretty hard - failing assertions in those callbacks will display in the command log, but will not cause the test to be failed.

**Comment by Andarist** [comment]
Wouldnt this be just a matter of binding correctly `unhandledrejection` listener in those places:
https://github.com/cypress-io/cypress/blob/9ccc7a6bd56dfce779cda9864c8c857c42334876/packages/driver/src/cy/listeners.js#L52-L53
https://github.com/cypress-io/cypress/blob/3e52df042ba6a987cf83d34d3a81238967e8697f/packages/driver/src/cypress/runner.js#L923
https://github.com/cypress-io/cypress/blob/052892d79f95f9792e00d426722a9d904b572df4/packages/driver/src/cypress/cy.js#L95

If that's the answer then I could work on fixing this.
