### ISSUE TITLE
Unable to see preview for pdf upload document in Electron browser

### ISSUE THREAD

**Issue by 86SUSHIL** [cypress-io/cypress#8806]
I'm able to upload pdf document but getting window pop up to save document with blob link at header. not able to see preview for uploaded document
![doc](https://user-images.githubusercontent.com/6176323/95655554-ecd4da00-0b25-11eb-9bcd-8eff5ab507d1.png)

cy.fixture(fileName , "UTF-8").then(fileContent => {
cy.get('input[type=file]').attachFile({ fileContent, fileName, mimeType: 'application/pdf' }, { subjectType: 'input' });
cy.wait(2000)
});

I tried with binary and base64 as well

Cypress 4.9.0
Electron 80

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/2835
