### ISSUE TITLE
Ability to control quiet mode without a command-line flag

### ISSUE THREAD

**Issue by rkrisztian** [cypress-io/cypress#8813]
There is a schematic for Angular CLI that allows us to replace Protractor with Cypress:

https://github.com/briebug/cypress-schematic/

However, it does not let me pass command-line flags arbitrarily:

https://github.com/briebug/cypress-schematic/blob/master/src/builders/cypress/schema.json

Would it be possible to add support for an environment variable instead, which lets me do the same as what the `--quiet` command-line option does?

Thanks in advance.

*Edit:* Sadly, I was unable to set env var `CYPRESS_REPORTER` to value `spec` either with that approach. :( It might not be able to control Cypress options that way but just pass variables to the test script. At least I can still put the env var override into my `package.json`.

**Comment by jennifer-shehane** [comment]
I would suggest opening an issue with https://github.com/briebug/cypress-schematic/ for them to accept command line flags. 

It doesn’t make sense for us to expose everything that are command line flags as also env vars (see configFile arg for instance). This seems like a pretty big loss of features that they don’t allow this. It looks like someone’s already opened a similar issue. https://github.com/briebug/cypress-schematic/issues/67

**Comment by rkrisztian** [comment]
OK, thank you.
