### ISSUE TITLE
Changing download directory in chrome is not working when run from "cypress run --spec <spect.js> --browser chrome

### ISSUE THREAD

**Issue by sashan4u007** [cypress-io/cypress#8814]
When execute testscript from "cypress run" then File is not getting download in cypress project directory. It gets download in default download directory of chrome browser. Below is command:

`cypress run --spec "cypress/integration/filedownload.spec.js" --browser chrome`

### Current behavior

Changing download directory in chrome headed browser is not working. File downloads in default download folder of chrome browser.

### Desired behavior

Download directory should get changed and file should get downloaded in download folder of cypress

### Test code to reproduce

Used below code in **plugin/index.js** file to change directory 

```js
const path = require('path')

module.exports = (on) => {
  on('before:browser:launch', (browser, options) => {
    const downloadDirectory = path.join(__dirname, '..', 'downloads')
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      options.preferences.default['download'] = { default_directory: downloadDirectory }
      return options
    }

    if (browser.family === 'firefox') {
      options.preferences['browser.download.dir'] = downloadDirectory
      options.preferences['browser.download.folderList'] = 2
      // needed to prevent download prompt for text/csv files.
      options.preferences['browser.helperApps.neverAsk.saveToDisk'] = 'text/csv'
      return options
    }
  })
}
```

Add below line of code in **filedownload.spec.js** 

```js
describe("Download file - Suite", function() {

    it("Download file testing", function() {
        cy.visit("https://file-examples.com/index.php/sample-documents-download/sample-doc-download/")
        cy.wait(10000)
        cy.get('table[id="table-files"]>tbody>tr:nth-child(1)>td.file-link>a:nth-child(1)').click()
    })
})

```

Add following lines in **support/index.js** to handle uncaught-exception- 

```js
  Cypress.on('uncaught:exception', (err, runnable) => {
    debugger
    return false
    })
    
    Cypress.on('fail', (err) => {
    debugger
    })

```

### Versions
**Cypress**  - 5.1.0
**Operating system** - Linux Ubuntu 18.04.5 LTS (Bionic Beaver)
**Browser** - Google Chrome - Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by stanislavgeorgiev** [comment]
Same here using the above official recipe. It does work ok with `cypress open` but not with `cypress run --browser chrome`

Cypress - 5.1.0
Operating system - MacOS Catalina 10.15.7
Browser - Google Chrome - Version 86.0.4240.75 (Official Build) (x86_64)

**Comment by jennifer-shehane** [comment]
I'm not seeing this actually. It saved the file within `cypress/downloads` for me. 🤔 

I ran with the `--browser` flag and with the `--spec` flag.

<img width="296" alt="Screen Shot 2020-10-16 at 4 19 35 PM" src="https://user-images.githubusercontent.com/1271364/96244185-bdade500-0fcb-11eb-9f81-0b4d51ca58c0.png">

**Comment by sashan4u007** [comment]
Thank you @jennifer-shehane for your response. Would you please share command ?

**Comment by elv1n** [comment]
@jennifer-shehane seems it's working well in headed mode but not in a headless one.

**Comment by bahmutov** [comment]
We have "File download" recipe in https://github.com/cypress-io/cypress-example-recipes#testing-the-dom and there is a command to run this recipe in headless mode with `npm run test:ci:chrome:headless`. Can you take a look and see how this recipe differs from your test setup?

**Comment by elv1n** [comment]
File download recipe working well, thanks!
Is the chrome headless doesn't accept preferences from setup in 'before:browser:launch'?

**Comment by shreeti91** [comment]
@jennifer-shehane
I have been trying to download a pdf file in firefox. For this, I referred to the below link:
https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__download/cypress/integration/local-download-spec.js#L95

I want to download the pdf in "Cypress.config('downloadsFolder')" folder. I also used firefox browser preferences also to avoid pop-up and download directly inside my project. But even after multiple trials, I could not. Everytime, i can download only inside default download folder or on Desktop location based on values (0,1) of ['browser.download.folderList'] . Below is the `before:browser:launch` options that I used in `plugins/index.js`
```
module.exports = (on, config) => {
 
  on('before:browser:launch', (browser = {}, options) => {
    
         const downloadDirectory = process.cwd()+"\\cypress\\downloads"
        // prevents the browser download prompt
        if (browser.family === 'firefox') {
          options.preferences['browser.download.dir'] = downloadDirectory
          options.preferences['browser.download.folderList'] = 2
          options.preferences['browser.download.panel.shown'] = true
          options.preferences['browser.download.manager.focusWhenStarting'] = false
          options.preferences['browser.helperApps.neverAsk.saveToDisk'] = 'application/pdf','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
          options.preferences['browser.download.manager.useWindow'] = false
          options.preferences['pdfjs.disabled'] = true
          options.preferences['devtools.console.stdout.content'] = true
          options.preferences['intl.accept_languages'] = 'en-US'
        return options
             
        }  
  })
```

Is it possible to download the pdf inside `cypress/downloads` by using the firefox browser?

Thanks in advance

**Comment by gurudattgd04** [comment]
Hello,

I'm trying to update the default download directory via plugin/index file

on('before:browser:launch', (browser, launchOptions) => {
// eslint-disable-next-line no-param-reassign
// eslint-disable-next-line no-param-reassign
launchOptions.preferences.default['download'] = {
// eslint-disable-next-line no-undef
default_directory: path.join(__dirname, '..', 'NewDownloads'),
}
// console.log('launch options are:', launchOptions.preferences.default)
return launchOptions
})

even after specifying the above code, i see the download is directing to default cypress/downloads folder

any suggestions will helps a lot

i'm trying for chrome browser at the moment

Thanks

**Comment by gurudattgd04** [comment]
@jennifer-shehane I checked the above case with example recipe repo https://github.com/cypress-io/cypress-example-recipes and I can confirm that above change I made is not working.

If you have any example repo which is working, could you please point me to that.

Thanks,
Gurudatt
