### ISSUE TITLE
Cypress not being able to connect to Chrome 86

### ISSUE THREAD

**Issue by DogaruRaluca** [cypress-io/cypress#8821]
Hi, I am facing the same issue of Cypress not being able to connect to Chrome. If I try to run my tests using Firefox Beta or Electron, it works. What's the problem with Chrome?

```
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.
This usually indicates there was a problem opening the Chrome browser.
The CDP port requested was 52419.
Error details: Error: could not find CRI target
```

I have added the following code, but the problem persists. I mention the fact that everything worked fine until yesterday.
```js
module.exports = (on, config) => {
on('before:browser:launch', (browser, launchOptions) => {
if (browser.name === 'chrome' && browser.isHeadless) {
launchOptions.args.push('--disable-gpu');
return launchOptions
}
});
}
```

**Comment by jennifer-shehane** [comment]
Duplicate of #7450, if it was working yesterday I would suggest tracking down what's changed between yesterday and now to help narrow down what introduced the error.

**Comment by DogaruRaluca** [comment]
I have made no changes since yesterday. It's clear that is a problem with the new version of Chrome(86) and Cypress. Everything is working fine with Electron.
