### ISSUE TITLE
.should() should fail when only chainer getters supplied

### ISSUE THREAD

**Issue by dwelle** [cypress-io/cypress#883]
### Current behavior:

If user writes `.should( chainer, value )` where `chainer` consists **only of** a chainer getter (e.g. `to`, `be`, `is`...), the command silently passes.

### Desired behavior:

Instead, it should throw/fail because it's not a valid assertion. It's the same as if the user wrote `expect( value ).be( value )` which is invalid chai assertion.

### How to reproduce:

```js
cy.wrap( 42 ).should('be', 100);
```

- Cypress Version: 1.0.3

**Comment by flotwig** [comment]
This is pretty confusing, just ran into another user having this issue: https://stackoverflow.com/questions/56690772/how-do-i-wait-for-the-callback-passed-to-a-cypress-custom-command-to-finish-befo/56690824#56690824
