### ISSUE TITLE
[Occasional] string typing in the wrong place during cy.type()

### ISSUE THREAD

**Issue by yehaow** [cypress-io/cypress#8838]
### Current behavior
i cannot upload the picture . the detail as bellow:
when I use `cy.type()` to input username and password for login ,password cannot type correct after username typed successfully
|+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +   |
|TEST BODY                                                                                                                                                           |
|...                                                                                                                                                                           |
|get         #personalAcconutInputId input                                                                                                             |
|(new url)   https://xxx/login.html                                                                                                                          |
|- type    _username_                                                                                                                                             |
|-assert    expected <input.tiny-input-text> to have value _username1_                                                             |
|get        #personalPasswordInputId input                                                                                                            |
|-type     _pwd@123!_                                                                                                                                            |
|-assert    expected <input.tiny-input-text> to have value _pwd@123!_, but the value was''                              |
|+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +|

            |+ + + + + + + + + + + + + + + + + + + + + + + + |
                                     Account Login
            |          userneme:_username1@123!__                         |
                       password:______________________         
                                                                                                
            |                             Log In                                             |
             
            |+ + + + + + + + + + + + + + + + + + + + + + + + |

### Desired behavior
username and password can be typed in correct

### Versions
Debian 8 and cypress@5.3.0

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
