### ISSUE TITLE
waitForAnimations is not a valid option for .click TS type 

### ISSUE THREAD

**Issue by mariotsi** [cypress-io/cypress#8854]
### Current behavior
`cy.get('body').click({ waitForAnimations: false })` gets TS error because `waitForAnimations` is not a valid option on the Type even if is a suggested command https://docs.cypress.io/guides/references/error-messages.html#cy-failed-because-the-element-is-currently-animating

### Desired behavior
`cy.get('body').click({ waitForAnimations: false })` will not throw TS error

### Versions
5.3.0 MacOS

**Comment by jennifer-shehane** [comment]
Yah, I can see how this error message is very confusing. ~This should be updated. You're meant to pass the `waitForAnimations` or `animationDistanceThreshold` options to your Cypress configuration - not within the command itself.~ 

Disregard - this is accurate.

**Comment by lukeapage** [comment]
I noticed this and fixed it already in https://github.com/cypress-io/cypress/pull/8837

**Comment by jennifer-shehane** [comment]
Nice.

**Comment by mariotsi** [comment]
Thank you very much
