### ISSUE TITLE
Cannot set property response of undefined

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8858]
Cypress v5.4.0 but might happen earlier

![route2-flake](https://user-images.githubusercontent.com/2212006/96174984-2f1c6380-0ef8-11eb-99ec-b2f078dbd1a8.gif)

Reproducible example in https://github.com/cypress-io/cypress-example-recipes

Spec examples/stubbing-spying__route2/cypress/integration/image-spec.js

Test

```js
  it('redirects static image', () => {
    // instead of serving an image from a fixture
    // we can redirect the request for the image
    // to another route
    cy.route2({
      method: 'GET',
      url: '/images/tiger.jpg',
    }, (req) => {
      // /__root/* is a special URL that can serve a file from the
      // project's root. Normally this is used during bundling
      // but here we are using it to serve another image
      req.redirect('/__root/cypress/fixtures/roo.jpg')
    })

    cy.visit('/pics.html')
  })
```

Error screenshot

![](https://user-images.githubusercontent.com/2212006/96175048-4eb38c00-0ef8-11eb-880d-1ce6cf461de7.png)

Last stack frame

![](https://user-images.githubusercontent.com/2212006/96175077-583cf400-0ef8-11eb-9b82-c71a0fb6419d.png)

`request` is undefined

![](https://user-images.githubusercontent.com/2212006/96175097-5ecb6b80-0ef8-11eb-8876-f29600cf10b7.png)

Previous stack frame

* checks if `request` is undefined and calls `sendContinuationFrame` (where it crashes trying to set `request`)

![](https://user-images.githubusercontent.com/2212006/96175134-6db21e00-0ef8-11eb-8949-894ed8035d70.png)

**Comment by msmps** [comment]
@bahmutov 

I can also confirm! 🐛 

Bumped into this issue in **v5.3.0** and **v5.4.0** when using `.route2` attempting to add custom headers to all requests!

![image](https://user-images.githubusercontent.com/64437301/96750225-9e47fb00-13c3-11eb-816e-9934dc15423a.png)
