### ISSUE TITLE
Framebusting on 3rd party sites break Cypress automation

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#886]
This is about to be fully documented in the [Trade Offs](https://on.cypress.io/trade-offs) section.

I'm opening an issue here to point users to.

Eventually this issue can be resolved, and we'll be able to track it on our Roadmap.

**Comment by brian-mann** [comment]
A study of common framebusting / clickjacking techniques.

https://seclab.stanford.edu/websec/framebusting/framebust.pdf

We will likely implement enough to cover the bases described here on page 3

**Comment by brian-mann** [comment]
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).

**Comment by miohtama** [comment]
I have encountered a script that is not correctly fixed by the current Cypress network layer modification. What would be the best place to discuss how to update the framebuster support to cover this? 

Specifically, it is a Xsolla login iframe https://xsolla.com/products/login

**Comment by jennifer-shehane** [comment]
@miohtama Please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
