### ISSUE TITLE
No network response when multiple cy.route2 matches

### ISSUE THREAD

**Issue by superwesker1988** [cypress-io/cypress#8866]
When I was trying to do conditional network interception in suite hook, the network request will not get response if one of the matches has `req.reply`. Below is what my code looks like:
```js
if (shouldInjectHeader === true) {
  cy.route2('<myUrl>', req => {
    req['x-custom-header'] = '<something>';
  });
}
cy.route2('<myUrl>/<withSomeOtherStuff>', req => {
  req.reply(res => {
    if (res.statusCode > 399) {
      Cypress.log(....);
    }
  })
});
```

### Current behavior

if `shouldInjectHeader === true`, the Chrome (Electron as well) does not get any response from the `'<myUrl>'`

### Desired behavior

if `shouldInjectHeader === true`:

1. Outbound network should have custom header injected
2. Browser will receive response 
3. log will be generated when `statusCode` is greater than 399

### Test code to reproduce

```js
cy.route2('https://localhost:9090/', req => {
  req['x-custom-header'] = '<something>';
});
cy.route2('https://localhost:9090/index.html', req => {
  req.reply(res => {
    if (res.statusCode > 399) {
      Cypress.log({
          displayName: 'failed request',
          message: `${req.url} responded with ${res.statusCode}`,
       });
    }
  })
});
cy.visit('');
```

### Versions

MacOs Catalina v10.15.6
Cypress: 5.4.0
Chrome: 85.0.4183.102

**Comment by jennifer-shehane** [comment]
Can you provide a full example with a request? I wrote up the example below - with requests and the Cypress.log ends up being called in my case. There's likely something more specific to your requests that I'm not aware of that would cause your issue. Thanks!

```js


it('test cy.route()', () => {
  cy.route2('/folder', req => {
    req['x-custom-header'] = '<something>';
  }).as('folderMod')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('POST', '/folder', {})
    xhr.send()
  })
  cy.wait('@folderMod')

})

it('test', () => {
  cy.route2('/folder', req => {
    req.reply(res => {
      if (res.statusCode > 399) {
        Cypress.log({
          displayName: 'failed request',
          message: `${req.url} responded with ${res.statusCode}`,
        });
      }
    })
  }).as('folderMod')

  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('PATCH', '/folder', {})
    xhr.send()
  })
  cy.wait('@folderMod')
})
```

<img width="529" alt="Screen Shot 2020-10-21 at 5 23 00 PM" src="https://user-images.githubusercontent.com/1271364/96710453-1ad9da00-13c2-11eb-81ac-044906ffc1ea.png">

**Comment by jennifer-shehane** [comment]
I guess I can see when there are 2 `cy.route2()` definitions matching the same url in the same test that some strange things happen. Is this the case you're describing?

<img width="514" alt="Screen Shot 2020-10-21 at 5 26 22 PM" src="https://user-images.githubusercontent.com/1271364/96710798-93d93180-13c2-11eb-9ef4-2b7c58bbcfa3.png">

**Comment by superwesker1988** [comment]
Hi @jennifer-shehane,

The latest post does seem like what I've encountered.

**Comment by VyvIT** [comment]
Not sure if related, but having similar issue in latest 5.5.0 version - reply doesn't work, while it works in 5.4.0:
Not actual code, but have something along those lines in actual tests:

```
it("test", () => {
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest();
    xhr.open("GET", "/api/users", {});
    xhr.send();
  });

  cy.route2("POST", "/api/users").as("users");

  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest();
    xhr.open("POST", "/api/users", {
      name: "morpheus",
      job: "leader",
    });
    xhr.send();
  });

  cy.wait("@users");

  cy.route2("POST", "/api/users", (req) => {
    req.reply((res) => {
      // never reach this part
      Cypress.log("hello?");
      res.send("test!");
    });
  }).as("users2");

  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest();
    xhr.open("POST", "/api/users", {
      name: "morpheus",
      job: "leader",
    });
    xhr.send();
  });

  cy.wait("@users2"); // time outs
});

```

**Comment by flotwig** [comment]
Hi, please try updating Cypress, `cy.route2()` has been renamed to `cy.intercept()` and no longer has this issue.
