### ISSUE TITLE
Unable to install Cypress v5.4.0 with yarn

### ISSUE THREAD

**Issue by paleite** [cypress-io/cypress#8867]
### Current behavior

When installing Cypress 5.4.0 with yarn (1.22.10, but the same behaviour can be found in 1.22.5), the depencies in yarn.lock are missing and there's very few files in `node_module/cypress`. 5.3.0 is working as expected, though.

5.4.0 in `yarn.lock`:

```
    which "^2.0.1"

cypress@^5.4.0:
  version "5.4.0"
  resolved "https://registry.yarnpkg.com/cypress/-/cypress-5.4.0.tgz#8833a76e91129add601f823d43c53eb512d162c5"
  integrity sha512-BJR+u3DRSYMqaBS1a3l1rbh5AkMRHugbxcYYzkl+xYlO6dzcJVE8uAhghzVI/hxijCyBg1iuSe4TRp/g1PUg8Q==

dashdash@^1.12.0:
```

5.3.0 in `yarn.lock`:

```
    which "^2.0.1"

cypress@~5.3.0:
  version "5.3.0"
  resolved "https://registry.yarnpkg.com/cypress/-/cypress-5.3.0.tgz#91122219ae66ab910058970dbf36619ab0fbde6c"
  integrity sha512-XgebyqL7Th6/8YenE1ddb7+d4EiCG2Jvg/5c8+HPfFFY/gXnOVhoCVUU3KW8qg3JL7g0B+iJbHd5hxuCqbd1RQ==
  dependencies:
    "@cypress/listr-verbose-renderer" "^0.4.1"
    "@cypress/request" "^2.88.5"
    "@cypress/xvfb" "^1.2.4"
    "@types/sinonjs__fake-timers" "^6.0.1"
    "@types/sizzle" "^2.3.2"
    arch "^2.1.2"
    blob-util "2.0.2"
    bluebird "^3.7.2"
    cachedir "^2.3.0"
    chalk "^4.1.0"
    check-more-types "^2.24.0"
    cli-table3 "~0.6.0"
    commander "^4.1.1"
    common-tags "^1.8.0"
    debug "^4.1.1"
    eventemitter2 "^6.4.2"
    execa "^4.0.2"
    executable "^4.1.1"
    extract-zip "^1.7.0"
    fs-extra "^9.0.1"
    getos "^3.2.1"
    is-ci "^2.0.0"
    is-installed-globally "^0.3.2"
    lazy-ass "^1.6.0"
    listr "^0.14.3"
    lodash "^4.17.19"
    log-symbols "^4.0.0"
    minimist "^1.2.5"
    moment "^2.27.0"
    ospath "^1.2.2"
    pretty-bytes "^5.3.0"
    ramda "~0.26.1"
    request-progress "^3.0.0"
    supports-color "^7.1.0"
    tmp "~0.2.1"
    untildify "^4.0.0"
    url "^0.11.0"
    yauzl "^2.10.0"

dashdash@^1.12.0:
```

### Desired behavior

I would like 5.4.0 to include its dependencies in `yarn.lock`

### Test code to reproduce

I've also included a copy of the lockfile when installing v5.3.0 (`yarn-v5.3.0.lock`) so you can compare them.

https://github.com/paleite/cypress-test-yarn-5.4.0-issue-reproduction

### Versions

Cypress 5.4.0
macOS 10.15.7

**Comment by jennifer-shehane** [comment]
I am seeing this within the project you provide - where you've already provided the lockfile, but if I start a new project and run yarn with Cypress 5.4.0, it does list all the dependencies as is shown in the 5.3.0 lockfile. 

I also see the correct dependencies listed when starting a new project with Cypress 5.3.0 installed and running `yarn upgrade cypress@5.4.0 --dev`. 

Can you detail more about how you got to the current lockfile produced? Did you just run `yarn add cypress` on the project? Something else?

**Comment by paleite** [comment]
Hi, this issue seems to have been addressed in the latest release. Closing this

**Comment by jennifer-shehane** [comment]
@paleite Great to hear!
