### ISSUE TITLE
Improve overall CypressError messaging

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#887]
- Cypress Version: 1.0.3

### Is this a Feature or Bug?
Feature

### Current behavior:

Whenever a command has an error, it prints something like below:

```
CypressError: Timed out retrying: Expected to find element: '.text-input', but never found it. queried from element: <a>
```

### Desired behavior:

I think that the verbiage at the beginning may be confusing to some of our users. Almost all of our commands 'time out while retrying', and I think that this information is more confusing than helpful. All of the Cypress commands retry and if they fail, they have timed out. 

What the user really cares about is that next part of the error: `Expected to find element: '.text-input', but never found it. queried from element: <a>`. I think that some users see the `Timed out retrying` and jump to the conclusion that this is an error *with* Cypress, not a nice error *from* Cypress, that we're trying to **tell you something!**

**Comment by brian-mann** [comment]
Not all the Cypress commands retry. Each command indicates and documents its own retry behavior.

**Comment by jennifer-shehane** [comment]
I understand that this information is technically accurate, but it seems to impede more users than help. If a user wants to dive deeper into retry logic and where a command timed out, I would maybe think of exposing something to them to debug that.

**Comment by brian-mann** [comment]
There is: https://docs.cypress.io/api/events/catalog-of-events.html#Cypress-Events

**Comment by jennifer-shehane** [comment]
Closing. Was not approved. Hopefully these doc improvements help https://github.com/cypress-io/cypress-documentation/pull/1314

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close this issue.
