### ISSUE TITLE
Feature request: Add the ability to configure the server wait behavior

### ISSUE THREAD

**Issue by soullivaneuh** [cypress-io/cypress#8870]
# Concrete case

I have a project with cypress running thanks to this `test` scripts: `run-p --race dev cy:run` (see `npm-run-all` package).

I recently added some webpack compilation complexity to my project making the build a bit longer than usual.

Because of that, the cypress test suite is failing, not waiting enough time to get the server ready:

```
Cypress could not verify that this server is running:

  > http://localhost:3000

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
```

So bad, it was missing only 2 or 3 seconds to get the server up and running.

I did not find any possibility to tell cypress to try more than 3 times or wait a bit longer on each connection test.

The only workaround I found so far is to add a wait command:

```diff
diff --git a/package.json b/package.json
index 1808277..835a1e9 100644
--- a/package.json
+++ b/package.json
@@ -6,7 +6,7 @@
     "dev": "sapper dev --no-hot",
     "build": "NODE_ENV=production sapper build",
     "start": "node __sapper__/build",
-    "cy:run": "cypress run",
+    "cy:run": "wait-on tcp:3000 && cypress run",
     "cy:open": "cypress open",
     "test": "run-p --race dev cy:run"
   },
@@ -25,6 +25,7 @@
     "svelte-loader": "^2.9.0",
     "svelte-preprocess": "^4.5.1",
     "tailwindcss": "^1.9.2",
+    "wait-on": "^5.2.0",
     "webpack": "^4.44.2"
   }
 }
```

# Proposed solution

Add a configuration key and/or cli option to either increase the timeout and/or the number of retries of Cypress.

Maybe this do exist, but I didn't find anything on the documentation or help usages.

**Comment by bahmutov** [comment]
You can use start-server-and-test utility for this

**Comment by jennifer-shehane** [comment]
We recommend these modules for this use case:

wait-on: https://www.npmjs.com/package/wait-on
start-server-and-test: https://github.com/bahmutov/start-server-and-test

Adding this feature is not something we see as within our scope of feature work, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by kicktipp** [comment]
So why does Cypress wait at all and retries three times? If you see this message from cypress you are looking for configuring the wait time somewhere. I would remove retrying and waiting for the server OR have some options to configure it. 

> ...
> Cypress automatically waits until your server is accessible before running tests.
> 
> We will try connecting to it 3 more times...
> We will try connecting to it 2 more times...
> We will try connecting to it 1 more time...
> 
> Cypress failed to verify that your server is running.

**Comment by jennifer-shehane** [comment]
Yeah, I can see how that messaging implies it is configurable somewhere. We're just trying to give a final notice and retry, but maybe it's more confusing than helpful. 😞

**Comment by nurbashanghai** [comment]
any workaround? somebody?

**Comment by akauppi** [comment]
@nurbashanghai Here is my workaround: https://github.com/akauppi/GroundLevel-firebase-es/blob/next.2/dc-tools/cypress-run/Dockerfile

Also the question itself includes a work-around.

**Comment by adamalton** [comment]
I would really like to see a the ability to configure this added to Cypress. It seems odd to have this automatic check built in, but with fixed assumptions about how long it should wait or how many times it should retry. Having it configurable would be a huge help.
