### ISSUE TITLE
Cypress.route will not match any request where the url has a query param containing http://{anything}

### ISSUE THREAD

**Issue by beatthat** [cypress-io/cypress#8875]
### Current behavior

Cypress.route will fail on any request that has a query param with value `http://anything`

So if you have this in cypress:

```javascript
describe("route", () => {
  beforeEach(() => {
    cy.server();
    cy.route({
      method: "GET",
      url: `**/has-http-in-query-param**`,
      response: 'ok'
    }).as('has-http-in-query-param')
  });

  it("mocks a url with a query param containing http://a", () => {
    cy.visit("/");
    cy.wait("@has-http-in-query-param");
    cy.get("#responseText").contains("ok");
  });
});
```

...and then your app under test makes a request for `/has-http-in-query-param?x=http%3A%2F%2Fa`

Then the route *SHOULD* match but it will not

### Desired behavior
`Cypress.route('/has-http-in-query-param**')` should match `/has-http-in-query-param?x=http%3A%2F%2Fa`

### Test code to reproduce

Here is a full project that demos the bug with steps: https://github.com/ICTLearningSciences/cypress-route-bug

### Versions
5.3.0 on OSX with Chrome

**Comment by jennifer-shehane** [comment]
I can recreate the issue as described from the https://github.com/ICTLearningSciences/cypress-route-bug repo

**Comment by flotwig** [comment]
`cy.route()` was removed in [Cypress 12.0.0](https://docs.cypress.io/guides/references/changelog#12-0-0), please try using [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept) instead. Closing this issue since the relevant API has been deprecated and removed.
