### ISSUE TITLE
Test passed even though assertion failure occurs

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#8876]
### Current behavior

I am writing my test similar to this `route2` example, and cy.visit follows it. I noticed that there is an assertion failure, but how come Cypress consider test as passed (see screenshot)?

> cy.route2('POST', '/organization', (req) => {
  expect(req.body).to.include('Acme Company')
})

<img width="226" alt="image" src="https://user-images.githubusercontent.com/2043287/96325281-729bce00-0fdb-11eb-86fd-bcec63424e34.png">

I see this error message in browser's console:

> Uncaught exception from application, continuing. CypressError: The following error originated from your test code, not from Cypress.

  > A request callback passed to `cy.route2()` threw an error while intercepting a request:
expected {} to deeply equal { Object (action_type, floating, ...) }
...
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

### Desired behavior

I would assume test fails when any assertion failure occurs.

### Versions

Cypress version: 5.4.0
Browser: Chrome version 86.0.4240.80
Mac OS: version 10.15.6

**Comment by Nxtra** [comment]
On first sight, I don't know why this happens. Can you share the code?

**Comment by jennifer-shehane** [comment]
Could you please provide a full example of this throwing, but the test passing? Do you have any event listeners set up? https://on.cypress.io/catalog-of-events maybe that listen on fail of the test and handle it?

**Comment by flotwig** [comment]
Hey @quad5, this is a known issue with asynchronously thrown uncaught errors: #8802 

Closing as duplicate.
