### ISSUE TITLE
"Uncaught DOMException: Failed to set the 'domain' property on 'Document'" on cy.go('back')

### ISSUE THREAD

**Issue by amitguptagwl** [cypress-io/cypress#8883]
### Current behavior

When I'm using cy.log('back') to go on previous page, cypress refreshes the dashboard and show following error in browser's console log;

```
Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'some.domain' is not a suffix of 'localhost'.
```

> I have replaced actual domain name with `some.domain` in above error.

Same code is working fine with Cypress v3.4.1

### Desired behavior
`cy.go('back')` should load the previous page in browser.

### Test code to reproduce

Use `cy.go('back')` somewhere in the test code.

### Versions

Cypress: 4.12.1
Ubuntu 20.04

**Comment by jennifer-shehane** [comment]
Similar issue: https://github.com/cypress-io/cypress/issues/5722

I see that you are using an older version of Cypress. Can you update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you?

Probably the structure of the URL is important here. Can you give an example of what it looks like? Like... https://test.app.domain.uk ?

**Comment by amitguptagwl** [comment]
If I'm correct, the new version of Cypress require some changes in the code import export etc. So currently team is avoiding that. 

The sample URL is `www.abc.efg.hi.uk`

**Comment by flotwig** [comment]
This should have been fixed in the latest release of Cypress, we update the `parse-domain` metadata with each release now. Please open a new issue if this is still occurring.
