### ISSUE TITLE
elements are not rendered when running cypress test

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#8884]
### Current behavior
![image](https://user-images.githubusercontent.com/32042806/96428411-06e67a80-1200-11eb-975e-ba6cedfbb2e1.png)

### Desired behavior
page should be rendered properly 

### Versions
5.4

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by Amrkamel1** [comment]
@jennifer-shehane  what kind of enough information 

webside is **https://evernote.com/**

if u login with regular browser and try to create note u will find it looks like below 
![image](https://user-images.githubusercontent.com/32042806/96430227-326a6480-1202-11eb-89f4-6094c87de397.png)


if you open same url and same account this editor part will not be rendered as shown below 
![image](https://user-images.githubusercontent.com/32042806/96430356-56c64100-1202-11eb-8595-99fea8eed490.png)

**Comment by jennifer-shehane** [comment]
Can you provide the test code to run to reproduce this? (Excluding the login details of course), then we can run the steps to reproduce this exactly without having to write from scratch.

**Comment by Amrkamel1** [comment]
@jennifer-shehane 

here you are just run npm i and run the only test inside

https://github.com/Amrkamel1/code-sample.git


FYI, also same script not running properly on headless mode, i got message that website is not supporting this chrome version however its latest 86, there is attached screenshot and video in the repo for the headless mode

**Comment by Amrkamel1** [comment]
@jennifer-shehane  discard this, issue solved by setting   "chromeWebSecurity": false,
