### ISSUE TITLE
Upgrading to 5.4.0 -> "Cannot read property 'constructor' of undefined" when running any test file

### ISSUE THREAD

**Issue by jthannah** [cypress-io/cypress#8898]
### Current behavior
When running a spec file, an error is thrown. 
```
(function () {
  Cypress.action("spec:script:error", {
    type: "BUNDLE_ERROR",
    error: "TypeError: Cannot read property 'constructor' of undefined"
  })
}())
```

### Desired behavior
Tests run as expected. 

### Versions
Everything works and runs fine on version 5.3.0

**Comment by Jaakko808** [comment]
@jthannah I am facing the same issue, did you figure out what was the problem?

**Comment by jthannah** [comment]
@Jaakko808 Yes, I have Cypress installed inside the cypress directory instead of at the root of the project. So all I had to do to fix that error was change the `baseUrl` in the `tsconfig.json` file to point to the node_modules directory that contains the cypress installation. 

So `"baseUrl": ".../node_modules"` just became `"baseUrl": "node_modules"`
