### ISSUE TITLE
Cypress is not resolving XHR url's correctly when there is a <base> tag present

### ISSUE THREAD

**Issue by amaurymedeiros** [cypress-io/cypress#89]
``` html
<html lang="en">
  <head>
    <base href="/">
    <meta charset="utf-8">
  </head>
  <body>
    Hello World
  </body>
</html>
```

**url**: `http://localhost:5000/conversation/new`
**XHR**: `templates/conversation-new.html`

**Expected result**: XHR requested at `http://localhost:5000/templates/conversation-new.html`
**Actual result**: XHR requested at `http://localhost:5000/conversation/templates/conversation-new.html`

**Comment by brian-mann** [comment]
Fixed in [`0.12.7`](https://github.com/cypress-io/cypress/wiki/Changelog#0127-11302015).
