### ISSUE TITLE
Add option to disable browser cookies in `cy.request`.

### ISSUE THREAD

**Issue by cameron-martin** [cypress-io/cypress#8909]
### What would you like?

[`cy.request` automatically sends and sets browser cookies](https://docs.cypress.io/api/commands/request.html#Cookies-are-automatically-sent-and-received). I'm proposing to add an option to disable this behaviour.

### Why is this needed?

After running some actions via the UI, I would like to make an API request to the same domain as the tests are running on. However, I would like to make this API request as an external user, therefore I would not like to send and set browser cookies.

**Comment by amartinez1558** [comment]
Agreed! There is a huge need for this especially for those who use Cypress to also run API tests inbetween UI tests. Uses clearCookies isn't consistent and too overhead to run for every request. This sounds like it would be a low hanging fruit :)

**Comment by rogozind** [comment]
I have the same use case. I have a test for permissions where one user has to constantly change permissions and the other user needs to validate the effect.  Since cypress does not support multiple tabs I have to login/logout constantly. Please add this option so zi can make a request as an admin user using just the cookie.

**Comment by jennifer-shehane** [comment]
Since this has not gotten a lot of interest over the years, we’ll close this as not planned.

**Comment by fastfedora** [comment]
Actually, I just came here looking for this as I'm developing API tests using Cypress. I agree it's not needed if you're doing strict E2E testing, but with Cypress now being an option for writing API tests, this would be a valuable feature.
