### ISSUE TITLE
Option to only record video on subsequent test attempts

### ISSUE THREAD

**Issue by CScharer** [cypress-io/cypress#8910]
### What would you like?
Currently when running tests I have the option of video: true/false, etc.  What I would like is an option to only have video recorded if the test is being run in a retry.

### Why is this needed?
This is needed is to improve the efficiency of the testing as a whole.  Since there should be and likely are a significant amount of tests that don't fail it would increase the speed of all the tests and also reduce load on the node(s) running the test(s) as it would only record video on a retry after the initial test run failed.  Any screenshots captured from the initial failure would likely be significant enough to validate that the failure was for the same reason too.

**Comment by bahunov** [comment]
Yes, that would be awesome!

**Comment by caseyjhol** [comment]
I would be open to working on a PR for this if the devs would be open to it.
