### ISSUE TITLE
Cy.get failed when the target is not in the viewport

### ISSUE THREAD

**Issue by yannickdebree** [cypress-io/cypress#8911]
I'm working with Angular, Cypress and ag-grid. My project contains a scrollable board and I want to focus an element which is present in the DOM but not visible in the viewport, but Cypress throw the following error :

![Capture d’écran de 2020-10-21 18-27-29](https://user-images.githubusercontent.com/36421603/96749826-97bd8180-13cb-11eb-9edf-c792a43315e9.png)

How to fix this error ? I found nothing about this problem in the documentation. I'm sure that the element is present in the DOM because I can focus it with document.querySelector.

### Versions
Cypress Version : 5.4.0
OS: Ubuntu 18.04.5 LTS
Browsers: Firefox 82, Chromium 86, Electron 85

**Comment by sainthkh** [comment]
Sorry for the late reply. Can you provide a reproducible example? As we all know, without it, debugging cannot be started.

**Comment by sainthkh** [comment]
Closing the issue because of inactivity. If the problem is still happening, please open a new issue with a reproducible example.
