### ISSUE TITLE
Microsoft Edge (dev channel) is not detected on Linux

### ISSUE THREAD

**Issue by MattMattV** [cypress-io/cypress#8930]
### Current behavior
When Microsoft Edge Dev is installed on a Linux system, it is no recognized by the Cypress runner, and it's not available in the browser dropdown.

### Desired behavior
Microsoft Edge Dev should be detected with the binary `microsoft-edge-dev`

### Versions

Cypress 5.4.0
Microsoft Edge Dev 88.0.673.0

**Comment by bahmutov** [comment]
To detect is, create an alias like we do in our Docker image with Edge pre-installed

https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/node14.10.1-edge88/Dockerfile#L17

Then the detection works and you can run with `cypress run --browser edge`
