### ISSUE TITLE
Export results from Cypress' UI

### ISSUE THREAD

**Issue by akivajgordon** [cypress-io/cypress#8932]
### What would you like?
In short, I would like a way to export the results of my test run (especially the failures) that was run from the Cypress UI (i.e. via `cypress open`)

### Why is this needed?
Here is my use case:

I am running a suite that takes on the order of 10 minutes to complete. When a test fails, my normal process for investigating a test failure is to jump into the test file and stick a `.only` on my test case, because as I make changes to my app's code or to the test code, I want to quickly check if that issue is resolved instead of running the entire test suite over again for each change.

Now suppose I have 10 different failures scattered throughout my tests. After I fix the first test using my `.only` scheme mentioned above, I no longer remember which of the other tests failed, and neither does Cypress because the test run data is gone after re-running my test with `.only`. So now in order to find out which other tests failed, I have to re-run the entire suite again, which costs me ~10 minutes.

The workaround for me at the moment is to basically right down a list of the failures (or putting `.only` on all of them right away). I suppose I could also use the failure screenshots.

I'm not sure if any of the reporter options will satisfy this use case, but even then, changing the reporter is an after-the-fact problem. I still have to re-run the suite again. If, on the other hand, I could just export the results from the Cypress UI, I wouldn't need to change any of my reporter options. Instead I would simply refer to this exported file for a list of the failures, then fix each one individually, and finally run my entire suite again to make sure all of my tests are still passing.

**Comment by jennifer-shehane** [comment]
If your tests are 10 minutes long during ‘cypress open’, I’d suggest investigating running your suite via `cypress run`, or continuous integration to run your tests on commit, or looking at our Dashboard where you can see the list of failures or get notified of failures with GitHub integration or Slack for the run.

There are already a number of ways provided to get a list of failures for a run that we would recommend over this workflow. 

‘cypress open’ is purely meant as a developer tool, to be used during writing tests. Not as a solution to run *all* tests to review what may have broken. This feature is not really in scope with what we plan to deliver.

**Comment by akivajgordon** [comment]
@jennifer-shehane  – no problem, thanks for your analysis and reply!

**Comment by nawlbergs** [comment]
Unless I am missing something... I would argue that `cypress run` does not even provide a nice list of what error'd at the end.  There is a very nice summary table at the end... but having just a flat list of the failed test descriptions above or below it would be a super helpful printout.. as having 500 tests.. you need to scroll up and down the console to find everything that failed and compile your own list.

PS - its a great tool. Thanks for the hard work. :)
