### ISSUE TITLE
cy.route2 times out waiting for image load

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8934]
Cypress v5.4.0 and even https://github.com/cypress-io/cypress/pull/8916

Test in https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__route2/cypress/integration/image-spec.js#L4

```js
  it.only('spies on loading a static image', () => {
    cy.route2('/images').as('image')
    cy.visit('/pics.html')
    // how to check if the /image route was called once?
    cy.wait('@image')
  })
```

The image request happens, but the test fails it. Notice that the routes tab shows 1 matching request

![wait-on-image-times-out](https://user-images.githubusercontent.com/2212006/96887408-8ff4f000-1452-11eb-964c-d91837c1b01a.gif)

**Comment by sainthkh** [comment]
When I was fixing #8858, I also saw this problem (the test passes but the image loading failed). After #8965, I couldn't see this happening again. If the bug doesn't happen on your environment too, I think we can close this issue.

**Comment by bahmutov** [comment]
Check

```js
describe('route2', () => {
  it.only('spies on loading a static image', () => {
    cy.route2('/images').as('image')
    cy.visit('/pics.html')
    // how to check if the /image route was called once?
    // @see https://github.com/cypress-io/cypress/issues/8934
    cy.wait('@image')
  })
```

Still happening in 5.5.0

**Comment by sainthkh** [comment]
Sorry, I misunderstood the issue.

**Comment by flotwig** [comment]
Closing this issue, I can reproduce this, but only if the image is not cached. If it is cached, the server returns a 304 Found, which is the same issue as #8999.
