### ISSUE TITLE
2nd test does not log commands when cy.route2() included with polling XHR requests

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#8940]
### Current behavior
Reported in https://github.com/cypress-io/cypress/issues/8926, so it may be related or the same issue. In which case go ahead and close. 

With a specific set of tests using cy.route2() testing some polling XHR requests, none of the commands in the following test get logged to the Command Log.

### Desired behavior
Run and log commands in 2nd test

### Test code to reproduce
`index.html`

```html
<button id="aa">button aa</button>
<script>
  document.getElementById('aa').addEventListener('click', async () => {
    const response = await window.fetch(`/${'aa'}`)
    const { data } = await response.json()

    // Fire off a bunch of extra requests to try to trigger the error
    for (let i = 0; i < 5; i++) {
      setTimeout(() => {
        window.fetch(`/${'aa'}`)
      }, i * 20)
    }
  })
</script>
```

`spec.js`

```js
it('first test', () => {
  cy.visit('index.html')
  cy.route2({ method: 'GET', pathname: /[a-z]+/ }, (req) => {
      const data = 'aa'
      req.reply({ data })
    })
    cy.get('button').contains('aa').click()
  })

it('second test', () => {
  cy.log('command here')
})
```

![](https://user-images.githubusercontent.com/1271364/96960947-96a26680-1529-11eb-916e-603d1990bb0c.png)

### Versions
Cypress 5.4.0

**Comment by sainthkh** [comment]
When fixing #8926, I tried to reproduce it, but failed (with 5.4.0 and 5.5.0).

**Comment by jennifer-shehane** [comment]
@sainthkh I can still recreate this in 5.4.0, 5.5.0 and `develop` branch with the fix from the other issue. When expanding 'Test 2', there is no log of the `cy.log()` command in the Command Log, so you have to look at the Command Log.

```js
it('first test', () => {
  cy.visit('index.html')
  cy.route2({ method: 'GET', pathname: /[a-z]+/ }, (req) => {
    const data = 'aa'
    req.reply({ data })
  })
  cy.get('button').contains('aa').click()
})

it('second test', () => {
  cy.log('command here')
})
```

### ❌ 5.5.0

<img width="641" alt="Screen Shot 2020-11-03 at 2 04 26 PM" src="https://user-images.githubusercontent.com/1271364/97959327-83bb4c00-1ddd-11eb-939c-13d87df302c9.png">


### ❌ `develop` branch

<img width="653" alt="Screen Shot 2020-11-03 at 2 03 39 PM" src="https://user-images.githubusercontent.com/1271364/97959348-8fa70e00-1ddd-11eb-8034-a2975c973d25.png">

### ✅ Comment out `cy.route()` command

<img width="616" alt="Screen Shot 2020-11-03 at 2 05 24 PM" src="https://user-images.githubusercontent.com/1271364/97959392-aa798280-1ddd-11eb-8182-c281df073b42.png">

```js
it('first test', () => {
  cy.visit('index.html')
  // cy.route2({ method: 'GET', pathname: /[a-z]+/ }, (req) => {
  //   const data = 'aa'
  //   req.reply({ data })
  // })
  cy.get('button').contains('aa').click()
})

it('second test', () => {
  cy.log('command here') // NOW THIS LOGS
})
```

**Comment by sainthkh** [comment]
![Peek 2020-11-04 15-19](https://user-images.githubusercontent.com/8130013/98076194-27c1f780-1eb1-11eb-9ef6-fed955d71a19.gif)

I reproduced it on my system. But as you can see above, it's a bit flaky on Ubuntu 20.04. Sometimes, it shows. Sometimes, it fails.

**Comment by quad5** [comment]
Hi, any idea on when this is on the `ready-for-work` queue. I am seeing this issue also. 

Thanks.

**Comment by AlexandreBonaventure** [comment]
Chiming in here: still experiencing this in 5.6.0 (I'm using route2 in these specs)
![](https://imgur.com/3PzkXsc.png)

And to bring water to the well: not only it does not "log" command but it actually does not "run" any commands which is an even bigger problem.

**Comment by jennifer-shehane** [comment]
I think this has been fixed. I can't replicate with `cy.intercept()` on 6.1.0.
