### ISSUE TITLE
Unable to Open cypress - EEXIST error

### ISSUE THREAD

**Issue by jjacallen** [cypress-io/cypress#8947]
I installed cypress via npm on my Windows 10 machine at `C:\users\jjaca\Documents\Cypress`

1. In Windows cmd window, I change directory to `C:\users\jjaca\Documents\Cypress\node_modules\.bin>`
2. Enter "cypress open"

Cypress application window opens but displays only the error:
**Message:** `EEXIST: file already exists, mkdir 'C:\Users\jjaca\Documents\Cypress\node_modules\.bin\cypress'`

**Stack trace:**
```
Error: EEXIST: file already exists, mkdir 'C:\Users\jjaca\Documents\Cypress\node_modules\.bin\cypress'


```

**Comment by jennifer-shehane** [comment]
What happens if you run `./node_modules/.bin/cypress open` from the root of your project? https://on.cypress.io/installing-cypress#Continuous-integration

**Comment by jjacallen** [comment]
Entering `./node_modules/.bin/cypress open` in the Windows command line gives an error

> '.' is not recognized as an internal or external command,
operable program or batch file.

BTW the same error is given for '$' if you try to run `$(npm bin)/cypress open`

> What happens if you run `./node_modules/.bin/cypress open` from the root of your project? https://on.cypress.io/installing-cypress#Continuous-integration

**Comment by jjacallen** [comment]
I've just realized this issue is a duplicate of issue [1099](https://github.com/cypress-io/cypress/issues/1099) so I'm closing it.
After reading the solutions in that issue I realized that Jennifer's suggestion above actually just has the slashes going the wrong way, and if I reverse the slashes, her solutions works:
From project root folder (folder where package.json lives) enter `.\node_modules\.bin\cypress open`

The other solution mentioned in the comments of issue 1099 was very nice and also worked for me:
[Solution by Mykola Svyshch](https://github.com/cypress-io/cypress/issues/1099#issuecomment-365868891)
