### ISSUE TITLE
Update Electron to v1.8.2 (Chromium 59/Node 8.2.1)

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#895]

**Comment by brian-mann** [comment]
That's been my goto strategy but we've been waiting for months and there hasn't been any movement on this yet. Chrome 53 and more importantly our users are starting to notice and have the differences cause their tests to fail. So we should do this during the `2.x.x` update.

**Comment by brian-mann** [comment]
https://github.com/electron/electron/issues/9970

**Comment by bahmutov** [comment]
Another related work: Chromium 61 https://github.com/electron/electron/issues/10211

**Comment by brian-mann** [comment]
Yay this will be a big win for us.

**Comment by tierninho** [comment]
Are native Electron apps ever gonna be testable with Cypress? Any plans for this?

**Comment by fcurella** [comment]
Electron `v1.8.2` has been released as stable https://electronjs.org/releases#1.8.2

**Comment by brian-mann** [comment]
Yay we can finally upgrade.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/1275.

**Comment by brian-mann** [comment]
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).
