### ISSUE TITLE
Cy.visit Using URL With Variable Starting With 0 Throws Error

### ISSUE THREAD

**Issue by jst1102** [cypress-io/cypress#8953]
### Current behavior
When cy.visit has a variable starting with a 0, it throws an error. If the 0 is not leading it does not. 
![chrome_Zb1vaxWo8N](https://user-images.githubusercontent.com/17620110/97014271-1aebee00-1518-11eb-95e0-d7075aec71f9.png)

### Desired behavior
Cy.visit would be able to handle a variable if it has a leading 0 or not. Currently, it will accept a variable if there is no leading zero.

### Test code to reproduce

Does not work:

```js
cy.visit(`https://www.google.com/doodles/switzerland-national-day-2${017}`)
```

vs

Works

```js
cy.visit(`https://www.google.com/doodles/switzerland-national-day-${2017}`)
```

(Used google to reproduce as to not include test code, but works the same)
### Versions

5.4
4.12
other versions possible as well, only tested these two versions

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce the error as described. 

It looks like there may be some compilation error. Can you include a repo to reproduce the issue? Perhaps your babelrc or preprocessor options are causing this error. thanks!

<img width="1365" alt="Screen Shot 2020-10-26 at 3 44 41 PM" src="https://user-images.githubusercontent.com/1271364/97154481-4e41ad80-17a2-11eb-91b8-1013c8cb10a2.png">

**Comment by jst1102** [comment]
here's a repo

https://github.com/jst1102/cypressexample.git

check out the master branch.

**Comment by jst1102** [comment]
you'll get an error if you update cypress to the newest version too
