### ISSUE TITLE
When Cookies with the Same Name Exist, Only One of the Cookies is Preserved Across Tests

### ISSUE THREAD

**Issue by todd-m-kemp** [cypress-io/cypress#8954]
### Current behavior

When you have multiple cookies with the same name but different domains and you attempt to preserve cookies across tests, only one of the multiple cookies that share a name are preserved.

### Desired behavior

All cookies are preserved, even when there are multiple cookies with the same name.

### Test code to reproduce

With the `baseUrl` set to `"https://cypress.io"`, run the following test:

```js
context('Cookies', function () {
  it('Test 1 - Sets Cookies', function () {
    cy.setCookie('cookie', 'value 1', { domain: 'domain1.cypress.io' });
    cy.setCookie('cookie', 'value 2', { domain: 'domain2.cypress.io' });
    cy.getCookies()
      .should('have.length', 2);
  });

  it('Test 2 - Relies on Preserved Cookies', function () {
    cy.getCookies()
      .should('have.length', 2); // Fails; only 1 cookie is present.
  });

  afterEach(function () {
    cy.getCookies()
      .then((cookies) => {
        cookies.forEach((element) => {
          Cypress.Cookies.preserveOnce(element.name);
        });
      });
  });
});
```

### Versions

Cypress version 5.4.0, Chrome 86, macOS 10.15.6.

**Comment by emilyrohrbough** [comment]
In the upcoming v12.0.0 release, the deprecated `Cypress.Cookies.preserveOnce` and `Cypress.Cookies.defaults` will be removed. This has been related with [`cy.session()`](https://docs.cypress.io/api/commands/session). Closing as won't fix.
