### ISSUE TITLE
Not All Cookies are Preserved Through Multiple Tests When preserveOnce is Used

### ISSUE THREAD

**Issue by todd-m-kemp** [cypress-io/cypress#8955]
### Current behavior

When preserving cookies using `Cypress.Cookies.preserveOnce`, cookies set during the test are not saved and sent into the next test. Only cookies that were in place prior to `preserveOnce` being called are set for subsequent tests.

Possibly this is expected behaviour, but it certainly isn't clear from the documentation.

### Desired behavior

The cookies that are in place at the end of a test are preserved for the next test.

### Test code to reproduce

With the `baseUrl` set to `"https://cypress.io"`, run the following test:

```js
context('Cookies', function () {
  before(function () {
    cy.setCookie('cookie1', 'value 1', { domain: 'domain1.cypress.io' });
  })

  beforeEach(function () {
    cy.getCookies()
      .then((cookies) => {
        cookies.forEach((element) => {
          Cypress.Cookies.preserveOnce(element.name);
        });
      });
  });

  it('Test 1 - Sets More Cookies', function () {
    cy.setCookie('cookie2', 'value 2', { domain: 'domain2.cypress.io' });
    cy.setCookie('cookie3', 'value 3', { domain: 'domain3.cypress.io' });
    cy.getCookies()
      .should('have.length', 3);
  });

  it('Test 2 - Relies on Preserved Cookies', function () {
    cy.getCookies()
      .should('have.length', 3); // Fails; there is only cookie1 is still around.
  });
});
```

### Versions

Cypress version 5.4.0, Chrome 86, macOS 10.15.6.

**Comment by dereg666** [comment]
I'm also seeing this issue where I pass in all the cookies I want to preserve in beforeEach, but cookies start to disappear one by one after several runs

**Comment by emilyrohrbough** [comment]
In the upcoming v12.0.0 release, the deprecated `Cypress.Cookies.preserveOnce` and `Cypress.Cookies.defaults` will be removed. This has been related with [`cy.session()`](https://docs.cypress.io/api/commands/session). Closing as won't fix.
