### ISSUE TITLE
Clipboard works with cypress open and not cypress run (permissions)

### ISSUE THREAD

**Issue by haug1** [cypress-io/cypress#8957]
### Current behavior

I have a test that is testing clipboard functionality. When I run `cypress open --browser chromium`, my tests are passing, but when I am running `cypress run --browser chromium` they will not pass. Error is that the app (not the test) can not read the clipboard with `window.navigator.clipboard.readText()` without manually granting permission inside chromium.

![image](https://user-images.githubusercontent.com/31956036/97049868-ae570a80-157c-11eb-95ee-7d3d8496d4cd.png)

Why am I getting this behavior only with `cypress run`? How can I bypass it?

I've been debugging, passing `DEBUG=cypress:launcher` and found that the browser launch arguments are identical. I have noticed one huge difference within the chromium browser: when I go to `Settings>Security>Safe Browsing`, it is set to "Standard protection" when running `cypress run`, but it's set to `No protection` when using `cypress open`.

(Manually setting Safe Browsing to 'No protection' and re-running tests does not fix the issue)

### Desired behavior

Same browser behavior with `cypress open` and `cypress run` when the provided configuration is identical. 

### Versions

5.2.0

**Comment by haug1** [comment]
Solved like this

![image](https://user-images.githubusercontent.com/31956036/97204307-3b38d880-17b6-11eb-8f20-ec7b1327a329.png)

Now I am facing the issue that my test will not pass in headless mode or when browser is not focused.

**Comment by IoanStoianov** [comment]
Adding the following code at the beginning of my test body resolved it for me in the headless:

```js
cy.wrap(
    Cypress.automation('remote:debugger:protocol', {
        command: 'Browser.grantPermissions',
        params: {
          permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'],
          origin: window.location.origin,
        },
    }),
);
```

**Comment by ememisya** [comment]
Does this help anyone?  https://github.com/cypress-io/cypress/issues/21673#issuecomment-1484747561 

For me the same issue appears to be intermittently failing my headless tests however I have not been able to successfully test the success of something like:

```js
const setFocusEmulationEnabled = (enabled: boolean): any => {
  return cy.wrap(
    Cypress.automation("remote:debugger:protocol", {
        command: "Emulation.setFocusEmulationEnabled",
        params: {
          enabled
        },
      }),
  );
};
```
As at the moment I have been testing it, setting it false also seems to yield **document.hasFocus()** true, and subsequent tests after removing the call all together are also working (until they won't).  This involves diving deep into Chrome internals to debug it, something I am not very familiar with at this time.

**Comment by MetRonnie** [comment]
Just this in `support/index.js` worked for me (no need for `wrap`?)
```js
Cypress.automation('remote:debugger:protocol', {
  command: 'Browser.grantPermissions',
  params: {
    permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'],
    origin: window.location.origin,
  },
})
```

(Include in an `if (Cypress.browser.family === 'chromium')` block if Firefox is in your CI)
