### ISSUE TITLE
cy.go('back') broken on hash change from internal links on page

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#896]
### Current behavior:
Using `cy.go('back')` to go back to an internal link hash makes Cypress infinitely loop between the baseUrl port and the random port. 

### Desired behavior:
Being able to use `cy.go()` to go back to internal links.

#### Test code:
```js
it('cy.go() - go back or forward in the browser\'s history', function(){
  cy.visit('http://localhost:8080#visit')
  cy.visit('http://localhost:8080#reload')
  cy.go('back')
})
```

```html
<h1 id="visit">Visiting</h1>
<h1 id="reload">Reloading</h1>
```

### Additional Info (images, stack traces, etc)
![adding-go](https://user-images.githubusercontent.com/1271364/32617873-2d7c6d78-c544-11e7-8dc4-aba2657eff70.gif)

- Cypress Version: 1.0.3
- Browser Version: Chrome 61

**Comment by jennifer-shehane** [comment]
I also had an error prior to running into this error where there were React errors coming from the `pkg/reporter` about having duplicate children with the same key. And when I clicked on the `location` command, it would also snapshot the `url change`. But, now when I run this code, all I get is the infinite looping above, so...this error is hidden in there somewhere, @brian-mann saw it too, I'm perplexed.

**This was the test code that was busted**
```js
context('Navigation', function(){
  beforeEach(function(){
    cy.visit('http://localhost:8080#visit')
    cy.visit('http://localhost:8080#reload')
  })

  it('cy.go() - go back or forward in the browser\'s history', function(){
    cy.location().then(function(location){
      debugger
    })
    cy.hash().then(function(location){
      debugger
    })
    cy.go('back')
    cy.location().then(function(location){
      debugger
    })
    cy.hash().then(function(location){
      debugger
    })
  })
})
```

**Comment by spearmootz** [comment]
We sort of experienced this too. Except it was triggered by clicking a link that triggered window.history.back()

It make the tests run endlessly on headless mode.

**Comment by kapalkat** [comment]
Hey 

The same happens to me. This happens even if my tests are not sharing the same context.
My test looks like follow:
describe('TESTS', function() {
  context('Test1', function() {  
    it('Go to URL1 and do some action', function () {
      // actions
    })
  })
  context('Test2', function() {  
    it('Go to URL2 and do some action and then go back to URL1', function () {
      // actions
      cy.click('back-arrow')
      cy.url(URL1)
    })
  })
})

This test makes cypress to go in the infinite loop.

**Comment by sammenza** [comment]
Wanted to bump this issue. I was trying to go between `http://localhost:5000/#thing/subitem/7937fb4b-d8c6-4ba8-ae86-5171d85b211/details` and `http://localhost:5000/#thing/subitem` and it wasn't working either

**Comment by jennifer-shehane** [comment]
This still produces an error state in Cypress 6.4.0, but a different error than before.

```js
it('cy.go() - go back or forward in the browser\'s history', function () {
  cy.visit('https://example.cypress.io/#visit')
  cy.visit('https://example.cypress.io/#reload')
  cy.go('back')
})
```

![](http://g.recordit.co/PRSKLYW98a.gif)
