### ISSUE TITLE
GH Actions cy.type({ mod key }) not working

### ISSUE THREAD

**Issue by stoplion** [cypress-io/cypress#8961]
### Current behavior

Mod keys are not firing on GH Actions
### Desired behavior

Mod keys should fire on GH Actions

### Versions
`Cypress 5.4.0`

### Test code to reproduce
When running Cypress locally these tests work. 
`cy.get('#CalcTitle').type(`{meta}S`); // save`

The `{meta}S` key triggers the save actions.

I'm running the tests on a Mac, so the `meta` key event works.

But on GH Actions, the test runner uses Linux.

So I'm using the following snippet in the test to change the modifier key.

```
before(() => {
    if (navigator.appVersion.indexOf('Mac') != -1) {
      fKey = 'meta';
    } else {
      fKey = 'alt';
    }
  });
````

And in the apps UI, I detect the OS version and change the hotkeys based on OS.

```
const HOTKEY_MAP = {
  Linux: {
    save: ['altKey', 's'],
  },
  MacOS: {
    save: ['metaKey', 's'],
  },
  UNIX: {
    save: ['altKey', 's'],
  },
  Windows: {
    save: ['ctrlKey', 's'],
  },
};
```

On GH actions, the action is never run.

Also, I've tried to hard code the mod keys to check if it'll trigger the action.

Trying all mod keys, upper and lower case.
```
        cy.get('#CalcTitle').type(`{alt}S`); // save
        cy.get('#CalcTitle').type(`{ctrl}S`);
        cy.get('#CalcTitle').type(`{meta}S`);

        cy.get('#CalcTitle').type(`{alt}s`); // save
        cy.get('#CalcTitle').type(`{ctrl}s`);
        cy.get('#CalcTitle').type(`{meta}s`);
```

On GH actions, the action is never runs.

Is there anything I'm missing here that is preventing this from working?

**Comment by tnrich** [comment]
@stoplion you closed this, but did you ever solve your issue? I'm seeing the same thing right now and wondering how to handle it.. thanks!
