### ISSUE TITLE
Error received erroneously: 'cy.type() can only be called on a single element'

### ISSUE THREAD

**Issue by jjacallen** [cypress-io/cypress#8970]
### Current behavior
The following test gives the error 'cy.type() can only be called on a single element':
```js
describe('Login Test', () => {
    it('Logs into Hallway as Cypress Test Bot', () => {
        cy.visit('https://hallway-server-origin.auth.us-east-1.amazoncognito.com/login?client_id=3l9vimt67rs5tptkbciuamdnd8&response_type=token&scope=email+openid+profile&redirect_uri=https://hallway.com/auth/callback')
        cy.get('input[id=signInFormUsername]').type('jjacallen+cypress@gmail.com')

        // Lorem ipsum
        cy.get('input[id=signInFormPassword]').type('cypresstester123')

        cy.get('input[id=signInSubmitButton]').click()

        // After logging in, we should return to the Templates page.
        cy.url().should('include', 'templates')
    })
})

```
### Desired behavior
the test should be able to type a string in the username input and another string in the password input, and submit the form as is shown in this [screenshot](https://www.screencast.com/t/uslBC45Gqfk6) of the [documentation](https://docs.cypress.io/guides/getting-started/testing-your-app.html#Logging-in)

### Versions
I don't know where to find the Cypress version, but it's the most recent one - installed last week in October 2020

**Comment by jennifer-shehane** [comment]
Cypress is informing you properly of the error. You have 2 forms present in the DOM on your page - one modal for mobile, one for desktop - they each have duplicate email / password elements. 

<img width="746" alt="Screen Shot 2020-10-27 at 12 33 11 PM" src="https://user-images.githubusercontent.com/1271364/97263144-b5b63680-1850-11eb-9f20-79503b689496.png">

Google Chrome even warns of the duplicate IDs in the DevTools.

<img width="737" alt="Screen Shot 2020-10-27 at 12 32 01 PM" src="https://user-images.githubusercontent.com/1271364/97263169-c2d32580-1850-11eb-86d0-254c5b2ee1bd.png">

**Comment by jjacallen** [comment]
Thank you! That makes complete sense. The test runner shows the error thrown on the first of my 2 elements, so that should have tipped me off but instead it confused me; it would be very clear if the error message included a mention of the element ID. In other words:

## Current Behavior
`cy.type() can only be called on a single element. Your subject contained 2 elements.`

![image](https://user-images.githubusercontent.com/73340056/97312277-af698f80-183b-11eb-83fd-a8b3669e4dae.png)

My script was looking for 2 elements, so that's why I misunderstood the error message.

## Desired Behavior
`cy.type() can only be called on a single element. Your subject contained 2 elements with id 'signInFormUsername'.`

Also, the "Learn More" link opened up the documentation on type() command, but there wasn't any mention of this error on that page, so that was a wild goose chase. Is there a more relevant page to link to for help with this error?

**Comment by LoralieF** [comment]
im dealing with the same problem how did you handle this?

**Comment by jjacallen** [comment]
Loralie, we couldn't solve it: the solution is to give a unique ID to each of the forms, but since this form is served up by Amazon Cognito, we can't customize it.

**Comment by MoRTDooM** [comment]
Hi, I am facing the same issue with Amazon Cognito sign in form, is there a way to focus on the desired input, I tried everything and always end up with ' Your subject contained 2 elements'.
Thanks!

**Comment by GunayNematova** [comment]
Hi, I am facing the same issue. Is there any solution?

**Comment by itsmadikenzhebayev** [comment]
I have the same issue :(

**Comment by itsmadikenzhebayev** [comment]
Guys, I had the same problem. I solved it with an alternative way of adding the function eq. Here is my example -> cy.get('[]').eq(1).type('')
I hope it will help you!

**Comment by laneschmidt** [comment]
Aside from the solutions above, I'm fairly certain that this kind of thing can be caused by asynchronous re-rendering. Maybe someone who better understands Cypress under the hood can chime in :). I ran into the same issue with this line:

```
cy.get('[data-cy=user-first]').type('Sally')
```

It worked for months until I started messing around with `<Suspense>`, then some tests broke.

There is only one element with that data-cy value in the dom upon inspection, but Cypress clearly sees two, so I'm not sure what else it could be.

**Comment by mayurmahajan** [comment]
> Guys, I had the same problem. I solved it with an alternative way of adding the function eq. Here is my example -> cy.get('[]').eq(1).type('') I hope it will help you!

you are a star! thank you.

**Comment by robertchriss** [comment]
Hi. In my case I had a text box and I needed to check restricted characters individually from an array. Through iteration , cy.type gave me the single element error. 

The workaround I found, was to close the window or make a page refresh after your input/validation  , in the for loop, and select your input field again. This will cause cypress to run through each array element.


 cy.get(toolbarButtons.createFolder).click();
        const restrictedChars = [ '&', '<', '>', '$', '?' ];
        for (let i=0; i<restrictedChars.length;i++) {
            cy.get(newFolder.newFolderInput).type(restrictedChars[i]);
            cy.get(newFolder.newFolderNameValidation).should('have.text', errorValidation.folderNameCharacterValidation);
            cy.get(newFolder.newFolderCreateButton).should('be.disabled');
            **cy.get(newFolder.newFolderCancelButton).click();
            cy.get(toolbarButtons.createFolder).click();**
        }

Without the bolded lines, I get the error, with them , I have a passing test with correct validations. 
Hope this helps !
