### ISSUE TITLE
Cypress is unable to resolve alias from wrap..as

### ISSUE THREAD

**Issue by vsix27** [cypress-io/cypress#8972]
[using latest version of cypress - 5.4.0]
![image](https://user-images.githubusercontent.com/10351245/97179831-ab703b80-176f-11eb-9836-363e7d530f16.png)
`cypress is unable to resolve an alias (despite the fact that it shows that alias is created - see pic):

```js
  const nn = [number1, number2];
  // read it later as cy.get("@numbers") or this.numbers  - does not work ???
  cy.wrap(nn).as("numbers");
  cy.get("@numbers").then((xx) => {
    cy.log(`..............${xx}`);
  });

  //cy.wait("@numbers").then((xx) => {cy.log(`..............${xx}`);});
```

If I uncomment cy.wait - also has interesting message:
![image](https://user-images.githubusercontent.com/10351245/97179915-c9d63700-176f-11eb-8fc3-65f205044302.png)

**Comment by jennifer-shehane** [comment]
I'm not able to recreate the error as described. Please make sure you are surrounding `@numbers` in quotes when referencing in `cy.get()` in your code. 

```js
it("test", () => {
  const nn = [1, 2];

  cy.wrap(nn).as("numbers");
  cy.get("@numbers").then((xx) => {
    cy.log(`${xx}`);
  });
})
```

<img width="611" alt="Screen Shot 2020-10-27 at 12 47 57 PM" src="https://user-images.githubusercontent.com/1271364/97264105-acc66480-1852-11eb-808f-f3b4c00cae8a.png">

Please feel free to comment with a reproducible example and we will consider reopening.

**Comment by vsix27** [comment]
thanks, i figured, the problem was - I created custom method cy.getAlias... in commands.js and it overwrote needed functionality...
after I renamed it to cy.getAliasCustom it went back to normal..
thanks, 
sorry for confusion

**Comment by jennifer-shehane** [comment]
Yah, there's an issue for that. It's definitely confusing. https://github.com/cypress-io/cypress/issues/6146
