### ISSUE TITLE
Bin on windows does not start after npm install

### ISSUE THREAD

**Issue by lborgman** [cypress-io/cypress#8973]
### Current behavior
  Cypress version 5.4.0
  Cypress failed to start
  
### Desired behavior
Cypress should start

### Test code to reproduce
```
npm init
npm install cypress --save-dev
node_modules\.bin\cypress open
```

### Versions
Cypress 5.4.0
Windows 10
Node.js v12.18.4

**Comment by jennifer-shehane** [comment]
Can you try using backslashes?

```js
node_modules/.bin/cypress open
```

**Comment by lborgman** [comment]
@jennifer-shehane 
That does not work at all in a CMD-shell on MS Windows.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information, like the error that occurs when starting Cypress, to provide concerning the original issue and we'd be happy to reopen.
