### ISSUE TITLE
5.5.0 Regression: Cannot load script with integrity attribute

### ISSUE THREAD

**Issue by Tanuel** [cypress-io/cypress#8983]
### Current behavior

When trying to load [google recaptcha](https://www.google.com/recaptcha/api.js), it will load another script, but the integrity check will fail. This error happens since upgrading to 5.5.0
![image](https://user-images.githubusercontent.com/28950300/97292229-4558e680-184b-11eb-864f-2d9e0bc58c99.png)

### Desired behavior
captcha can be loaded correctly

### Test code to reproduce

https://github.com/Tanuel/cypress-test-tiny

* `npm install`
* `npm run test`
![image](https://user-images.githubusercontent.com/28950300/97292646-cfa14a80-184b-11eb-9dec-24400332a331.png)

### Versions

Error occured on: 5.5.0
Last working Version: 5.4.0

Let me know if you need more information

**Comment by mstreng-bhs** [comment]
Same problem after upgrading from `5.3.0`  to `5.5.0`

**Comment by jennifer-shehane** [comment]
Yes, I can recreate this from the provided repo https://github.com/Tanuel/cypress-test-tiny. This was introduced in 5.5.0. I'll have to track down which PR introduced this.

### 5.4.0

<img width="911" alt="Screen Shot 2020-10-28 at 3 51 20 PM" src="https://user-images.githubusercontent.com/1271364/97416924-74e41d80-1935-11eb-977b-64e8e1514f53.png">

### 5.5.0

<img width="902" alt="Screen Shot 2020-10-28 at 3 50 27 PM" src="https://user-images.githubusercontent.com/1271364/97416950-7b729500-1935-11eb-8d09-7ffb3dacf945.png">

**Comment by sergeyblohin** [comment]
I faced a similar problem.
When Cypress was updated from 5.4.0 to 5.5.0, my ReCaptcha was no longer displayed.
I found a workaround allowing me to display ReCaptcha on a page.
Perhaps somebody could use it.

We add the following line to cypress.json:

```json
{
  "experimentalNetworkStubbing": true,
}
```

We add the following code to cypress/support/index.js:

```javascript
before(() => {
  cy.server();
  cy.route2('**/recaptcha/api.js', {fixture: 'google/recaptcha/api.js'});
});
```

Add the following code to cypress/fixtures/google/recaptcha/api.js.txt:

```javascript
/* PLEASE DO NOT COPY OR PASTE THIS CODE. */
(function () {
  var w = window, C = '___grecaptcha_cfg', cfg = w[C] = w[C] || {}, N = 'grecaptcha';
  var gr = w[N] = w[N] || {};
  gr.ready = gr.ready || function (f) {
    (cfg['fns'] = cfg['fns'] || []);
  };
  w['__recaptcha_api'] = 'https://www.google.com/recaptcha/api2/';
  (cfg['render'] = cfg['render'] || []).push('onload');
  w['__google_recaptcha_client'] = true;
  var d = document, po = d.createElement('script');
  po.type = 'text/javascript';
  po.async = true;
  po.src = 'https://www.gstatic.com/recaptcha/releases/T9w1ROdplctW2nVKvNJYXH8o/recaptcha__en.js';
  po.crossOrigin = 'anonymous';
  // po.integrity = 'sha384-3QFmGa9WBVUnmTTGehi+1Uin1pmBuS/I5R1Ce52Aiiuviet65v+bH12eR4+kUUcx';
  var e = d.querySelector('script[nonce]'), n = e && (e['nonce'] || e.getAttribute('nonce'));
  if(n) {
    po.setAttribute('nonce', n);
  }
  var s = d.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(po, s);
})();
```

Note that in `api.js.txt` I commented line 16.

You can now work with `integrity' in Cypress 5.5.0.
