### ISSUE TITLE
Feature Request: Dropdown in cypress to easily change enviroments

### ISSUE THREAD

**Issue by Moke96** [cypress-io/cypress#8985]
### What would you like?
I would like to have a feature in which I can quickly change between Enviroments (e.g dev and e2e).
A way to achive this would be to add a dropdown (near the browser dropdown) to choose between configurable envs (and maybe set a default env).
You can configure your envs inside cypress.json (maybe make baseUrl an Object like: `baseUrl:{ dev: "www.dev.site.com", local: "localhost:8080", e2e: www.e2e.site.com"}`

![featurereq](https://user-images.githubusercontent.com/12174661/97296901-97046f80-1851-11eb-8047-9434589ecc2f.PNG)

### Why is this needed?
To change between enviroments I have to change the baseUrl in the cypress.json which is cumbersome and not very user friendly.

**Comment by jennifer-shehane** [comment]
Closing since this hasn’t gotten a lot of interest over the years. (You can change e2e vs component tests however)
