### ISSUE TITLE
Cypress failed to make a connection to the Chrome DevTools Protocol: ECONNREFUSED at TCPConnectWrap.afterConnect

### ISSUE THREAD

**Issue by Supanovas** [cypress-io/cypress#8986]
### Current behavior
I'm simply trying to run some of the tests in the Example folder under Integration and it will not run on Chrome. Runs on Electron and Edge but refuses to run on Chrome. 

My version of Chrome is Version 86.0.4240.111 (Official Build) (64-bit)

Current Cypress version is - cypress": "^5.5.0

### Versions

![Chrome error](https://user-images.githubusercontent.com/35727935/97298206-0591ff00-184b-11eb-92ac-0ad0564d899d.PNG)

**Comment by Supanovas** [comment]
Hi @flotwig I've got the same issue with Cypress failing to make a connection to Chrome DevTools Protocol similar to the one you helped resolved. 

Any help trying to resolve this will be greatly appreciated, already logged it and it appears to be a common issue yet no known fix available. 

https://github.com/cypress-io/cypress/issues/5912#issuecomment-565620441

**Comment by Supanovas** [comment]
Hi @jennifer-shehane any update on this please?

**Comment by G0lang** [comment]
we experience same error via Firefox

**Comment by dvkruchinin** [comment]
I sometimes get this error in Travis-ci. There is no periodicity.

**Comment by G0lang** [comment]
@jennifer-shehane any update on this?

**Comment by jennifer-shehane** [comment]
Can anyone provide a reproducible example?

**Comment by tcw0nw** [comment]
I have the same problem！
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
Failed to connect to Chrome, retrying in 1 second (attempt 19/62)
Failed to connect to Chrome, retrying in 1 second (attempt 20/62)
Failed to connect to Chrome, retrying in 1 second (attempt 21/62)
Failed to connect to Chrome, retrying in 1 second (attempt 22/62)
Failed to connect to Chrome, retrying in 1 second (attempt 23/62)
Failed to connect to Chrome, retrying in 1 second (attempt 24/62)
Failed to connect to Chrome, retrying in 1 second (attempt 25/62)
