### ISSUE TITLE
TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by Spijkerj** [cypress-io/cypress#8987]
Cypress 5.3  and the previous versions running fine. Hence version 5.4 and higher throw and error: `TypeError: Cannot read property 'close' of undefined` when you click on the run button.

Cypress log:
```
  cypress:server:events got request for event: get:project:status, { id: undefined, path: '/Users/me/projecten/customer-dashboard-site/ui-tests' } +10s
  cypress:server:project get project status for client id undefined at path /Users/me/projecten/customer-dashboard-site/ui-tests +10s
  cypress:server:project no project id +0ms
  cypress:server:events sending ipc data { type: 'get:project:status', data: { id: 0.3723409760226337, data: { id: undefined, path: '/Users/me/projecten/customer-dashboard-site/ui-tests', state: 'VALID' } }, originalData: { id: 0.3723409760226337, data: { id: undefined, path: '/Users/me/projecten/customer-dashboard-site/ui-tests', state: 'VALID' } } } +0ms
```

To fix ran the following command and everything started working again for me:
```
npm i --save-dev chalk@2.4.2 ansi-styles@3.2.1
```

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the environment you are using. 

The logs provided are not relevant to the error being thrown. 

Can you show where you are seeing this error exactly? In stdout? In the Test Runner? In the console? A screenshot would be ideal. 

This may also be relevant to your testing suite, so providing a reproducible example would be best.

**Comment by damian-pereira** [comment]
Not sure why, but had the same issue, and the command @Spijkerj indicated worked for me too. 

I didn't save the error log, but it was something related to Index.js and same error as above: "TypeError: Cannot read property 'close' of undefined".

As a note, in my case started happening when I configured Eslint on the project.

**Comment by michael-schoormann** [comment]
We also had he same issue, here a screenshot: 
![Bildschirmfoto 2021-01-04 um 16 39 22](https://user-images.githubusercontent.com/76960105/103552264-ed260c80-4eab-11eb-883f-ddc01b559c5b.png)

The commands @Spijkerj worked for us. Thanks.

**Comment by ejosafat** [comment]
Same here, same set of tests, in 5.0 they're ok, as soon as I upgraded to 5.6 or 6.x it fails as well (the link to the issue template seems to be broken, btw). I upgraded eslint and typescript just in case, but still got the error. Installing the packages suggested by @Spijkerj fixed the problem.

Even a test as simple as
```
describe("foo", () => {
  it("works", () => {
    expect(true).to.be.true;
  });
});
````
fails to run.

My package.json dev dependencies are:
```

    "@types/node": "^14.0.14",
    "@typescript-eslint/eslint-plugin": "^3.1.0",
    "@typescript-eslint/parser": "^3.1.0",
    "archiver": "^4.0.1",
    "cypress": "^5.6.0",
    "eslint": "^7.1.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-cypress": "^2.11.1",
    "eslint-plugin-prettier": "^3.1.3",
    "prettier": "2.0.5",
    "request": "^2.88.2",
    "typescript": "^3.9.3"
```


This is my tsconfig

```
      "compilerOptions": {
    "allowJs": true,
    "noEmit": true,
    "strict": false,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "baseUrl": "node_modules",
    "target": "es5",
    "lib": ["esnext", "dom"],
    "types": ["cypress", "node"],
    "paths": {
      "utils/*": ["../cypress/utils/*"]
    }
  },
```
![Screenshot from 2021-02-10 17-37-05](https://user-images.githubusercontent.com/160837/107548472-260e7b00-6be8-11eb-8148-fce5a5ab4338.png)
