### ISSUE TITLE
Route2.then({request} => ) doesn't have request.body

### ISSUE THREAD

**Issue by bmitchinson** [cypress-io/cypress#8990]
Using Route2 over Route has the disadvantage of not including the body of the request.

With route(1), I'm able to assert information within the request.body, but with route2, I am not.

---

#### Route
```typescript
cy.route("POST", "/api/graphql?opname=verify"}).as("verifyReq")
cy.visit(`/verify`)
cy.wait("@verifyReq").then(console.log)
```

#### Yields request:
![image](https://user-images.githubusercontent.com/33632286/97362169-962e0680-186e-11eb-8742-1d620fae3535.png)
Notice presence of "body" field

#### Route2
```typescript
cy.route2("POST", "/api/graphql?opname=verify"}).as("verifyReq")
cy.visit(`/verify`)
cy.wait("@verifyReq").then(console.log)
```

#### Yields request:
![image](https://user-images.githubusercontent.com/33632286/97362185-9dedab00-186e-11eb-9f7e-aca0d2e79a0d.png)
Missing "body" field

### Desired behavior
For cy.route2 to provide just as detailed of a `request.body` as route1 does.

### Versions
Cypress 5.3

**Comment by jennifer-shehane** [comment]
This was fixed in 5.4.0. 

Please make sure to update to the [current version of Cypress](https://on.cypress.io/changelog) before opening an issue in the future. Thanks!

**Comment by bmitchinson** [comment]
Thanks, my apologies, I didn't see it in the patch notes :(

**Comment by jennifer-shehane** [comment]
No problem!
