### ISSUE TITLE
Single video file recording

### ISSUE THREAD

**Issue by vrunoa** [cypress-io/cypress#8991]
#8044 
# What would you like?
Possibility to record a single video file. 

### Why is this needed?
Other frameworks like testcafe support this option where you can tell the test runner itself to be able to record a single file or a file per spec, or even only on fail. 
https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/screenshots-and-videos.html#basic-video-options

**Comment by jennifer-shehane** [comment]
@vrun Can I ask why you want to have a single video for the run? What would this feature allow you to do that the separate videos do not allow currently?

**Comment by Arnarkari93** [comment]
It is easier to deal with if you want to copy the video file over to s3 for example.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
