### ISSUE TITLE
Shorthand syntax for action commands: cy.click('Login')

### ISSUE THREAD

**Issue by HendrikJan** [cypress-io/cypress#8996]
### What would you like?

I am inspired by CodeCeption which we use at work. 
In CodeCeption you can use this syntax:
```PHP
// Click on an element with the text "Login"
$I->click('Login');
// Click on an element with the id "submit_button"
$I->click('submit_button');
// Fill the field with label "Username" with "Miles"
$I->fillField('Username', 'Miles');
```

A shorthand notation in Cypress could follow the following rule to achieve a similar syntax:  

**If a string is added to an action (click, type, select, ...) as the first argument, this string is read as one of:**
* **the css selector of an element (comparable with `.get()`)**
* **the textual content of an element (comparable with `.contains`)**
* **the textual content of the label `<label for="elementname">` of an input element**

**The action will be performed on the found element**

This way test code like this:

```javascript
cy.get('#username').type('John');
cy.get('#password').type('MySuperSecret');
cy.contains('label', 'Remember me').find('input[type="checkbox"]').check();
cy.contains('Login').click();
```
Can be written like this:

```javascript
cy.type('Username:', 'John');
cy.type('Password', 'MySuperSecret');
cy.check('Remember me');
cy.click('Login');
```

### Why is this needed?

It would make tests more readable.

**Comment by jennifer-shehane** [comment]
This could be created as a Cypress plugin. testing-library does something similar. https://testing-library.com/docs/cypress-testing-library/intro 

This is not likely something that is within the scope of work we have planned for the future. But we'd be open to  reconsider if we see this issue gains more 👍 or comments in support.

**Comment by HendrikJan** [comment]
Thanks for the reply.

My suggestion combines an action with a query in one statement. This would make the entry barrier lower for new users, and be more readable.

This is different from the testing library which adds more query types.

Anyway, I understand that the team has its own plans, and you are doing a great job.

**Comment by jennifer-shehane** [comment]
Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
