### ISSUE TITLE
Route returning 204 (No content) can't be waited for with route2

### ISSUE THREAD

**Issue by jraoult** [cypress-io/cypress#8999]
### Current behavior

I'm trying to wait for this route:

```ts
 cy.route2({
  method: "DELETE"
}).as("delete");
```

My server returns a response with `204` status (a valid code for delete cf.https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE). I can see the route is intercepted thanks to the _route_ section in the runner but `wait` for this route alias always times out.

If I change the server to return a `200` (even without a body) then the `wait` command passes. Interestingly, in the runner's panel, the request still shows a progress bar even after the `wait` passes:

with a 204 status:
![204](https://user-images.githubusercontent.com/2046871/97420301-0a19ee80-1903-11eb-80de-1266ac7c47d4.gif)

with a 200:
![200](https://user-images.githubusercontent.com/2046871/97420336-1736dd80-1903-11eb-88a7-062985930afb.gif)

I found a workaround by adding a route handler like this:

```ts
(req) => {
  req.reply(() => {});
  }
```

### Desired behavior

`204` should get the same behaviour as `200`

### Test code to reproduce

```js
 cy.route2({
  method: "DELETE"
}).as("delete");

// trigger the delete somehow

cy.wait("@delete");
```

### Versions

Cypress 5.5.0

**Comment by flotwig** [comment]
This seems to happen with any empty body status code, like 304 Found, has the same behavior.
