### ISSUE TITLE
When I change file extension to `.ts` Cypress stops finding `pluginsFile`

### ISSUE THREAD

**Issue by jayarjo** [cypress-io/cypress#9000]
When I change file extension to `.ts` Cypress stops finding `pluginsFile` altogether:

![Screen Shot 2020-10-28 at 1 48 58 PM](https://user-images.githubusercontent.com/150075/97420342-9f79aa80-1924-11eb-857c-3a9b6bfa3174.png)

`pluginsFile` is changed accordingly in `cypress.json` to `cypress/plugins/index.ts` and yet.

### Versions

5.5.0

**Comment by jennifer-shehane** [comment]
Did you try restarting Cypress? you need to restart Cypress after changing the name of the file - as indicated in the error message.

**Comment by jayarjo** [comment]
I did, but I cannot reproduce this anymore, so I will close.
