### ISSUE TITLE
[github app] does not submit checks to PR:s

### ISSUE THREAD

**Issue by haf** [cypress-io/cypress#9011]
I got Cypress configured to send checks on PR:s to [logary-js](https://github.com/logary/logary-js), but nothing happens when [PR:s are submitted](https://github.com/logary/logary-js/pull/348).

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/193115/97489690-27c97100-1960-11eb-9d2c-fd52c2b817cc.png">

How can I get it going again?

**Comment by jennifer-shehane** [comment]
Hey @haf, it doesn't look like you are executing `cypress run` from within your CI integration that is associated with the PR. The Cypress status checks will trigger when `cypress run` is recognized within a git commit whos SHA is associated with a PR within the GitHub repo you've connected to your account.

You'll need to add `cypress run` to your Circle config.yml file to get the tests running and recognized in a status check. You can see some examples in our docs: https://on.cypress.io/continuous-integration#Example-circleci-config-yml-v2-config-file

Please let me know if I missed where you're executing `cypress run` from your CI, I briefly looked at the CircleCI job. Thanks!

**Comment by jennifer-shehane** [comment]
Since there's been no response, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by haf** [comment]
Hi Jennifer; you were right. This would be great to document from the admin panel. A sentence would be enough. Other apps are automatic.
