### ISSUE TITLE
Desktop GUI CSS Framework

### ISSUE THREAD

**Issue by kevcodez** [cypress-io/cypress#9012]
I have noticed that the Cypress Desktop GUI is using Bootstrap 3.

Bootstrap 3 went end of life on 24th of july 2019, see [here, on the Bootstrap Blog](https://blog.getbootstrap.com/2019/07/24/lts-plan/).

Naturally, it would be the most logic choice to go for the next version of bootstrap, which is Bootstrap 4.
Bootstrap 5 is still under active development and currently in alpha.

However, this situation also allows for revisiting the choice of the CSS framework.

New modern utliity CSS frameworks have risen, like [Tailwind](https://tailwindcss.com/).

Tailwind hits the nail on the head

> Most CSS frameworks do too much.
> They come with all sorts of predesigned components like buttons, cards, and alerts that might help you move quickly at 
 first, but cause more pain than they cure when it comes time to make your site stand out with a custom design.
> Tailwind is different.
> Instead of opinionated predesigned components, Tailwind provides low-level utility classes that let you build completely custom designs without ever leaving your HTML.

I would gladly refactor the desktop UI to use Tailwind. However, if that is not an option or considered and the only choice is to continue to use Bootstrap, I'd also volunteer to make a PR.

Having worked with Tailwind in production, I highly recommend the approach. It has a thriving community. I think it would be a great fit. I can also link a few articles showing the advantages.

What do you guys think?

As mentioned before, I will gladly provide a PR for the changes, but I wanted to get a commitment for a CSS framework before doing all that work.

**Comment by jennifer-shehane** [comment]
Oh yeah, it's pretty old. We've been working on more functional things in the meantime, so haven't focused much on the CSS framework in a while. 

Will this work entail design changes to the GUI? Or will is be purely behind the scenes updates of the CSS framework?

If there will be design changes, I'd like to get our designer's input. Thanks!

**Comment by kevcodez** [comment]
It could still look very familiar or even exactly like it does right now. With the default tailwind colors, it would probably look a bit more modern.

My main concern is updating to a modern CSS framework and not restyling. I would keep the current accessibility and layout. If you are generally open for adopting another framework like Tailwind, I can provide a PR and attach screenshots when the work is done. Other small design changes/adjustments shouldn't be in issue and can be changed quickly.

**Comment by jennifer-shehane** [comment]
Yes, we're definitely open to newer CSS frameworks. @CypressAdam should be able to weigh in on any design changes/choices.

**Comment by kevcodez** [comment]
@jennifer-shehane @CypressAdam For now I'd like to upgrade to Bootstrap 4 to just be on the current version and not use a CSS framework that is EOL.

However, I'd love to introduce a more modern CSS framework and overhaul the optics a bit and make it look more modern. I'd keep the usability and accessibility. I will provide a PR at a later point in time and start with a single view and then just check with you guys and verify it is going the right direction before continuing.

For now, I am working on the migration to Bootstrap 4 in #9061

**Comment by CypressAdam** [comment]
@kevcodez appreciate your diving in head first. I'm all for better organization and a framework that's still among the living. 

I would love to match efforts in figma and lend a hand where possible on implementation. I've worked with styled-components + styled-system in the past and I'm not too familiar with Tailwind... can you speak to your preference (if just for my own edification 😁 )?

**Comment by kevcodez** [comment]
@CypressAdam There are endless CSS frameworks that come with pre-styled components. Usually, you don't want your components to look like the default. So you start restyling the components. Out of the 1000 components that come with the framework, you might use less than 10. While you can purge the unused CSS, you still need to check the documentation every time. With new major versions, components can drastically change or alter the behaviour.

Tailwind CSS is a highly customizable, low-level CSS framework that gives you all the building blocks you need to build bespoke designs without any annoying opinionated styles you have to fight to override.

A great demonstration of how Tailwind works can be seen on the [homepage](https://tailwindcss.com/).

It basically gives you all the utilities to build your own components, if you need them. It is also responsible to the core.

In the past few months Tailwind gained so much traction. It currently has almost half a million downloads on npm per week. Nearly 50k follower on Twitter. Nearly 30k Github stars. It is fully open-source. While it started as a side-project, there's a company with 4-5 members backing it now. There are many great resources and new ones are created daily. They also offer a paid version of Tailwind Components (basically just snippets that you can copy in your project) [here](https://tailwindui.com/). It is also a great source of inspiration. Check out the [preview](https://tailwindui.com/components) and the snippets.

At first it might seem overhead or a bit weird to put that many CSS classes in your HTML. While you can easily refactor them or group them using `@apply` it actually comes with advantages. The maintainability is increased because you know what it does. You don't have that magical "btn" class that comes from outside your project that applies 100 different styles and changes depending on your DOM tree. It is very straight-forward once you understand the approach. The documentation is really great, too.

There's also a [Tailwind CSS UI Kit for Figma](https://www.figma.com/community/file/768809027799962739), although I haven't worked too much with Figma.

I'd highly recommend reading the homepage (https://tailwindcss.com/) to get a quick introduction.

Regarding styled-components: First off, I have not used them in production yet. Personally, I am not a big fan of mixing JavaScript and CSS like that. I also prefer an agnostic approach that is not tied to frameworks like React or specifically designed to work with them.

**Comment by CypressAdam** [comment]
@kevcodez ty for the detailed response! 

I've been batting ideas back and forth with the devs around this and, at this particular moment, a complete and total overhaul of our styles (and adding a framework) seems like too major a commitment to implement and review. Granted the visual experiences of the GUI/Runner are showing their age, but we're putting some things together on the design side to achieve some fresher looks (and stylistic consistency).

I think, short of a complete migration to something like Tailwind, it might be better to refactor and refine the styles on hand to close gaps between treatments in the Desktop GUI and Test Runner. Thinking about how we have a functional set of `sass` partials and some stubbed variables... yet we have several dozen disparate typographic treatments in the repo. Even still, I'm two months on the job and it's still _relatively_ easy for me to figure out what's going on and it's not too onerous to add or expand styles.

Ideally I'd like to get more out of what we presently have, do some housekeeping to arrive at a useful set of primitives, adopt some better conventional styling practices (eg - use blessed token variables, limit nesting, let classnames be ..., etc.). Then making a decision as to whether a framework gets us further faster when we have a more orderly house.

**Comment by flotwig** [comment]
We've completely overhauled our design system in Cypress 10, so I'd say this issue is no longer actionable. Look out for an eventual official release of the Cypress design system to go along with the updated UI in 10.

Closing since not actionable with Cypress 10.
