### ISSUE TITLE
Ability to obtain a stack trace with relative paths

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#9016]
### What would you like?

As a preprocessor-maintainer, I would like to have the ability to programmatically obtain a stack trace with relative paths as they appear in the source map, in the test-runtime, similar to the stack traces you show upon uncaught exceptions, as shown below.

![2020-10-28-231548_5120x1440_scrot](https://user-images.githubusercontent.com/730419/97502573-a976ca00-1973-11eb-8f17-aac482507955.png)

As seen in the screenshot, Cypress is successfully able to determine the correct, relative location of the origin of the error.

### Why is this needed?

Let me give a bit of background information to begin with. I'm contributing to `cypress-cucumber-preprocessor`, which is a preprocessor for mimicking Cucumber behavior with Cypress. Cucumber is essentially a mapping between step definitions (regular expressions) and function bodies. If a step in your feature matches more than one definition, then an ambiguity error is thrown, containing the location of the matched definitions. This behavior is specified in their [tests](https://github.com/cucumber/cucumber-js/blob/master/features/ambiguous_step.feature).

I'm trying mimic this behavior. However, if I use eg. `stacktrace-parser` to parse `new Error().stack`, as seen [here](https://github.com/badeball/cypress-cucumber-preprocessor/commit/865bba6), I obviously get useless output, as shown below.

```
Multiple matching step definitions for: foo
 foo - http://localhost:5000/__cypress/tests?p=cypress/integration/foo.feature:6649
 /foo/ - http://localhost:5000/__cypress/tests?p=cypress/integration/foo.feature:6649
```

If I manually import `source-map-support/register`, they get a little better.

```
Multiple matching step definitions for: foo
 foo - http://localhost:5000/__cypress/tests?p=cypress/integration/cypress/integration/step_definitions/foo.ts:3
 /foo/ - http://localhost:5000/__cypress/tests?p=cypress/integration/cypress/integration/step_definitions/foo.ts:5
```

It's not perfect though and this is due to `source-map-support` taking the source origin into consideration, which for `http://localhost:5000/__cypress/tests?p=cypress/integration/foo.feature` is `http://localhost:5000/__cypress/tests?p=cypress/integration`. This source is prefixed to all relative paths in the source maps, making the stack a bit odd.

**Comment by jennifer-shehane** [comment]
Our team has decided that adding this feature is not currently within the scope of feature work that our team is planning to work on - although this should be possible to do. We'd be open to reviewing any PRs made implementing this.

**Comment by jennifer-shehane** [comment]
Closing since this hasn’t had a lot of interest over the years.
