### ISSUE TITLE
Vscode is not able to pick up custom command typings

### ISSUE THREAD

**Issue by konekoya** [cypress-io/cypress#9019]
### Current behavior

Vscode is not able to pick up type defined for custom command's, this is a be complicated, I'm using [cypress-real-world-project](https://github.com/cypress-io/cypress-realworld-app) as the example to describe the issue. It was originally discussed here: https://github.com/cypress-io/cypress-realworld-app/pull/607#discussion_r513135875

Import a type from another file under Cypress namesapce in [__global.d.ts__](https://github.com/konekoya/cypress-realworld-app/blob/develop/cypress/global.d.ts#L10)
```js
import { User } from "../src/models";
```

Add a new `createUser` type definition and use that `User` type we just imported in the above, as you can see in the screenshot, the `user` parameter is getting `any` as the type instead of `User`:
![Type definition in global.d.ts](https://imgur.com/hiHztQU.png)

And when using it, Vscode is suggesting that parameter user should be a type of `any` as well
![Use in the spec](https://imgur.com/S8WXQnu.png)

I even tried to type the custom command directly in [__support/commands.ts__](https://github.com/konekoya/cypress-realworld-app/blob/develop/cypress/support/commands.ts#L303-L305), but still, the `user` parameter is typed as `any` when using in a spec
![Custom command](https://imgur.com/u7cG0VL.png)

_I've also noticed that if you're using primitive like `string`, `boolean`, etc or even defined your type right under the cypress namespace. Vscode will be able to pick up that in the specs._

### Desired behavior

Vscode should able to pick up the correct typing information for custom type (user defined types)

### Test code to reproduce

I have forked cypress real-world app and added the changes that I describe in the above
https://github.com/konekoya/cypress-realworld-app

### Versions

Cypress: 5.5.0
Visual Studio Code: 1.50.1
TypeScript: 4.0.3
OS: macOS Catalina 10.15.7 (19H2)

**Comment by kevinold** [comment]
@konekoya Please complete the demonstration PR you began in https://github.com/cypress-io/cypress-realworld-app/pull/619 so that the issue is reproducible.

**Comment by kevinold** [comment]
@konekoya 

The solution to this issue is that your `import { User } from "../src/models";` inside of `global.d.ts` must be inside the `declare namespace Cypress` block like so:

```
/// <reference types="cypress" />

declare namespace Cypress {
  import { User } from "../src/models";
  import { authService } from "../src/machines/authMachine"
```

Please confirm this resolves your issue.

**Comment by konekoya** [comment]
Hmm, this seems not fixing the issue on my side. Not sure if there's anything that I missed. So this does work on your machine? I wonder if this is somehow related to OS or Vscode.

**Comment by kevinold** [comment]
@konekoya This does work on my machine.  You most likely need to reload VSCode so that TypeScript updates.

**Comment by konekoya** [comment]
> @konekoya This does work on my machine. You most likely need to reload VSCode so that TypeScript updates.

Did reload VSCode a couple of times but the issue persists. I have no idea what happened 🤷  I will report back if I ever found out the cause. Thanks for your time!
