### ISSUE TITLE
JSON fixtures format on test run

### ISSUE THREAD

**Issue by Graham42** [cypress-io/cypress#902]
- Operating System: Ubuntu 16.04
- Cypress Version: 1.0.3
- Browser Version: N/A

### Is this a Feature or Bug?
Bug

### Current behavior:
Whenever I run a test using a json fixture, the fixture file gets formatted. In my project I format all possible files using [prettier](https://prettier.io/). This includes json. The formatting that cypress applies conflicts with prettier. Specifically empty object blocks. (`{}`)

### Desired behavior:
Ideal: Format using prettier instead of whatever is used now.
Acceptable: Don't format fixtures.

### How to reproduce:
1. Create a test using a json fixture with the contents formatted by prettier.
  Example:
  https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm3mgMwEsBzXJTdKDbAXwBocscR8IIzLttcAjAQwBOZTAEZqmGhhog6ICAAcYhaAGdkoPipjJ8fADYq4sngL5gA1nBgBleWcJRiyGAICuRkABMIYHfsOyAFYqAB4AQqYWVtZ8ALZwADIOcH4GHhCuMPKZAEypASB2AoYCyCDB0DKFAg4wAOqEnjAAFsgAHAAMsoaxhM5uHioOxHpwAIquEPD5HjB8PA1NrUg5si58hHrDAMIQsbF8ZVDQKbKuhgAq82pIumk0NEA
2. Run the test.
3. Check the file for format differences.

#### Test code:

See https://github.com/Graham42/cypress-bug-format-fixures

**Comment by MarcLoupias** [comment]
Duplicate : https://github.com/cypress-io/cypress/issues/884

**Comment by Graham42** [comment]
I don't think so, #884 looks like it is specifically a windows issue with line endings

**Comment by bahmutov** [comment]
Hmm reformatting your json fixture files or imported scripts does look like something cypress should not be doing

**Comment by MarcLoupias** [comment]
I disagree that #884 is related to windows only, the issue is not about windows formatting, it is that cypress is rewriting the fixtures files instead of doing read-only.

**Comment by brian-mann** [comment]
https://github.com/cypress-io/cypress/issues/884#issuecomment-344957927

**Comment by brian-mann** [comment]
Released in [`1.1.0`](https://docs.cypress.io/guides/references/changelog.html#1-1-0).

**Comment by Graham42** [comment]
Thank you!
