### ISSUE TITLE
cy.route2() with aliased fixture

### ISSUE THREAD

**Issue by rimlin** [cypress-io/cypress#9025]
### Current behavior
I try to reproduce behavior for `cy.route2()` from https://docs.cypress.io/api/commands/fixture.html#Using-an-alias-to-access-a-fixture, but it not work.
```js
cy.fixture('users').as('usersJSON')
cy.route2('/users/**', {
  fixture: '@usersJSON'
})
```
Instead of object from *users.json* i got string *@usersJSON* in response of network request.

### Desired behavior
Return for */users/*** route object from *users* fixture.

### Versions

5.5.0

**Comment by jennifer-shehane** [comment]
I can recreate this behavior. This likely is not a bug, but just never coded to handle an alias fixture reference. I'll have to check with the team to see if they plan to implement this.

```js
it('cy.route()', () => {
  cy.visit('http://example.cypress.io/commands/files')

  cy.server()
  cy.fixture('example.json').as('comment')
  cy.route('GET', 'comments/*', '@comment').as('getComment')

  cy.get('.fixture-btn').click()

  cy.wait('@getComment').its('responseBody')
    .should('have.property', 'name')
    .and('include', 'Using fixtures to represent data')
})

it('cy.route2()', () => {
  cy.visit('http://example.cypress.io/commands/files')
  cy.fixture('example.json').as('comment')

  cy.route2('comments/*', {
    fixture: '@comment' // throws error about not recognizing path
  }).as('getComment')

  cy.get('.fixture-btn').click()

  cy.wait('@getComment').its('responseBody')
    .should('have.property', 'name')
    .and('include', 'Using fixtures to represent data')
})
```

<img width="555" alt="Screen Shot 2020-10-30 at 6 02 37 PM" src="https://user-images.githubusercontent.com/1271364/97700484-510e0c80-1ada-11eb-8692-273e09e71cc1.png">

**Comment by flotwig** [comment]
We are trying to move away from using aliases for everything, so as of now, this is not planned to be implemented.

Try this instead:

```
cy.route2('/users/**', {
  fixture: 'users'
})
```
