### ISSUE TITLE
Cypress.AUTWindow does not have openDatabase method defined in Typescript

### ISSUE THREAD

**Issue by cbruge** [cypress-io/cypress#9028]
### Current behavior
Trying to use the `openDatabase` method on the `window` Object yielded by `cy.window()` returns an Error:
"Property 'openDatabase' does not exist on type 'AUTWindow'"
![image](https://user-images.githubusercontent.com/73653560/97587832-2188d280-19fc-11eb-878e-eb5a01eae887.png)

### Desired behavior
Ideally when trying to use this method typescript would recognize it.

### Test code to reproduce

```js
cy.window().then((window) => {
    var db = window.openDatabase("localforage", 1, "Local Forage", 500000);
  });
```

Paste this in any `.ts` file. 

### Versions
Cypress v 5.5.0

**Comment by cbruge** [comment]
To elaborate: I use this to clear the WebSQL Database which is currently still supported by Chrome and therefore used by the localforage library.

Workaround:
Write the Code in a Javascript file, export the function and use it.

**Comment by jennifer-shehane** [comment]
This may be because it has limited browser support. https://caniuse.com/sql-storage Here is the types definition: https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L122:L122

**Comment by cbruge** [comment]
Thank you for the link to the typedefinitions. Adding it to the ApplicationWindow interface solved the issue. I agree it is an outdated technology and we will also switch to another solution soon. But for anyone who wants to use it:
![image](https://user-images.githubusercontent.com/73653560/97992535-14e0f180-1de3-11eb-8fcf-569b2bbbdff3.png)

**Comment by sainthkh** [comment]
AUTWindow is created for custom items added to window object in your projects. As for WebSQL functions like `openDatabase`, I recommend [@types/websql](https://www.npmjs.com/package/@types/websql). 

You can check [the code here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/websql/index.d.ts).
