### ISSUE TITLE
Brotli files fail to load in Cypress 5.5

### ISSUE THREAD

**Issue by chasemgray** [cypress-io/cypress#9029]
### Current behavior
We've been trying to upgrade to Cypress 5.5 but it will not work with our website due to the fact that we serve javascript assets with brotli encoding and do not provide a gzip version. It appears this code is what is causing the issue:
https://github.com/cypress-io/cypress/blob/64a60f4bc1b0d055431400e81c55ba525ebda6ea/packages/proxy/lib/http/request-middleware.ts#L69-L82

I'm not sure why this is only an issue in 5.5 but everything has been working for us fine with brotli encoding up until now.

### Desired behavior
We should be able to load a javascript file for our website using brotli encoding.

### Test code to reproduce
Download any brotli file from within the opened Chrome window during a cypress run.

### Versions

Cypress 5.5

**Comment by bahmutov** [comment]
Hi Chase, did it use to work previously? And if yes in which Cypress version?

**Comment by chasemgray** [comment]
Yes, it works on all versions prior to 5.5. I tested 5.0, 5.1, 5.2, 5.3, and 5.4 today to verify.

**Comment by jennifer-shehane** [comment]
The file referenced was not touched during the 5.5.0 release, so I'm not sure that's the source of the issue you're describing. 

Can you provide a reproducible example? That will help in getting this issue addressed more quickly. Thanks!

**Comment by chasemgray** [comment]
It's possible it's not that file, but my suspicion is something using those functions, not the file itself.

Anyways, if you open a cypress controlled browser, and request the following brotli encoded file, it'll fail. It will succeed on previous versions of Cypress. This file is being served directly off S3 with the correct brotli content-encoding headers, etc.

https://aurora-v2.s3.amazonaws.com/vendors~ChartJS.0.111.0.js

**Comment by chasemgray** [comment]
@jennifer-shehane is there any update on this? Were you able to reproduce it with the link I sent?
