### ISSUE TITLE
shouldn't cypress-cli automatically verify before install ?

### ISSUE THREAD

**Issue by DimaRGB** [cypress-io/cypress#903]
- Operating System: `Mac OS`
- Cypress Version: `1.0.3`
- Browser Version: `no matter`

### Is this a Feature or Bug?
question

### Current behavior:
when u write `npx cypress install` it always install `Cypress.app`.

### Question:
Shouldn't it verify before install: `if it's installed, and only if verify failed then install.`

### How to reproduce:
run twice `npx cypress install`

**Comment by brian-mann** [comment]
Hmmm I'm not sure. What is the use case for this? It seems if you don't want to install it, why say to install it?

You could probably conditionally check this yourself by asking to verify Cypress first and if that fails then install it.

**Comment by DimaRGB** [comment]
Something like this:

```
#!/usr/bin/env node

const childProcess = require('child_process');

const execCypress = (cmd, cb) => {
  const proc = childProcess.exec(
    `npx cypress ${cmd}`,
    {
      cwd: __dirname,
      maxBuffer: 50 * 1024 * 1024,
    },
    cb,
  );
  proc.stdout.on('data', data => process.stdout.write(data));
  proc.stderr.on('data', data => process.stderr.write(data));
  return proc;
};

const args = process.argv.slice(2).join(' ');

execCypress('verify', err => {
  if (err) {
    execCypress('install', err => {
      if (!err) {
        execCypress(args);
      }
    });
  } else {
    execCypress(args);
  }
});
```
