### ISSUE TITLE
cy.wait only waits for first request out of many matched requests

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#9034]
### Current behavior

<img width="654" alt="Screen Shot 2020-10-29 at 4 10 20 PM" src="https://user-images.githubusercontent.com/2043287/97642953-ae835a00-1a03-11eb-9a4f-ea49e0ebb286.png">

### Desired behavior

In our application, multiple requests may match from a single routeMatcher (ie cy.route2()). When I use `cy.wait`, it only intercepts the first request. I thought it would wait for all matched request on such routeMatcher.

### Test code to reproduce

```js
let routeAlias = 'alias1';
cy.route2({routeMatcherObject}, routeAlias);
cy.visit("url");
cy.wait(`@${routeAlias}`).then((req) => {
            cy.log(req);
            console.log(req);
        })
```

### Versions

Cypress: 5.5.0
Chrome: 86.0.4240.111
MacOS: 10.15.6

**Comment by jennifer-shehane** [comment]
@quad5 `cy.route2()` with its current API has no idea what 'all' requests are without that being predefined somewhere. We'd have no idea if 1 route or 100 routes will be coming in later to match the route you've defined and when you wanted to stop waiting with the current API. 

Likely one of these features will be helpful in testing what you're looking for: https://github.com/cypress-io/cypress/issues/7663 https://github.com/cypress-io/cypress/issues/8531 so feel free to comment in those your support and whether they would be helpful in testing the number of requests you'd like to match.
