### ISSUE TITLE
@cypress/webpack-preprocessor latest version appears not to have `dist` directory

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#9037]
### Current behavior

`@cypress/webpack-preprocessor@5.4.9` (latest one) does not have `dist` directory as specified in `main`. Cannot be used.

### Desired behavior

Deploy a new version with `dist` correctly built.

### Test code to reproduce

```
yarn add @cypress/webpack-preprocessor
```

Then just do `ls node_modules/@cypress/webpack-preprocessor` and see no `dist` is there.

### Versions

5.4.9.

**Comment by cexbrayat** [comment]
@lmiller1990 You beat me to it :) I'm encountering the same issue.

It looks like @JessicaSachs already fix it in https://github.com/cypress-io/cypress/pull/9035 just after the release.

**Comment by csvan** [comment]
As a temporary measure, you can lock your dependencies to 5.4.8

```
"@cypress/webpack-preprocessor": "5.4.8"
```
