### ISSUE TITLE
Browser: 'chrome' was not found on your system or is not supported by Cypress

### ISSUE THREAD

**Issue by sergeyKhristenko** [cypress-io/cypress#9044]
### Current behavior
We're using cypress `4.12.0` and recently updated browser image to `cypress/browsers:node12.14.1-chrome85-ff81`. Started to _sometimes_ seeing this error on CI:
```
Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox (Cypress support in beta)

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- firefox
- electron
```

### Desired behavior

Cypress can find a browser.

### Versions
cypress `4.12.0`
docker image `cypress/browsers:node12.14.1-chrome85-ff81`
OS linux
CI jenkins

**Comment by kaiyoma** [comment]
We also see this problem in our CI. We're using version 5.6.0 of Cypress and Chrome 86 in a Linux Docker image. The issue pops up very inconsistently, but it makes no sense, as nothing about our infra is changing.

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/8611
