### ISSUE TITLE
spread operator support

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#905]
Any plans to support transform-object-rest-spread plugin? It would make tests neater, whenever necessary.

**Comment by brian-mann** [comment]
This is actually done (it is a PR right now). It's part of the plugins / extensions API which is documented here: https://github.com/cypress-io/cypress/issues/684

**Comment by paulpruteanu** [comment]
Sounds good, thank you!

**Comment by brian-mann** [comment]
Released in [`1.1.0`](https://docs.cypress.io/guides/references/changelog.html#1-1-0).

**Comment by hsellou** [comment]
Can you give us a sample of a file preprocessor to use in order to have the spread operator, please  ?
I'm a little lost in webpack/babel preprocessor configuration :(

Thanks !

**Comment by dcastil** [comment]
I'd also like native spread operator support for Cypress. It's strange that I can't use syntax which is natively supported by node.

**Comment by jennifer-shehane** [comment]
I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document use of the spread operator within the preprocessor here: https://github.com/cypress-io/cypress-documentation/issues/533. Our documentation is open source and contributions are welcome.

**Comment by zebulonj** [comment]
@hsellou If you're already using webpack, this should get you where you want to be (includes examples): https://github.com/cypress-io/cypress-webpack-preprocessor
