### ISSUE TITLE
Cypress Times Out in Composed Custom Commands

### ISSUE THREAD

**Issue by vicatcu** [cypress-io/cypress#9052]
### What would you like?
When I write a Custom Command, obviously it is often composed of several lines that invoke cy methods and chains. It seems to me like these compositional custom commands time out if they contain to many composing things. I want a way to specify that the timeout for my custom command gets reset after each chain so that the overall custom command doesn't timeout prematurely even though it is plainly making progress.

### Why is this needed?
It really limits the usefulness of custom commands if I have to "keep them short" in runtime as a whole block.

**Comment by jennifer-shehane** [comment]
Can you give an example of a custom command timing out prematurely? Because this is not the design of the API, so it behaving this way is a bug or a misunderstanding in the API. 

For example, the below custom command waits as long as the commands take to finish running.

```js
Cypress.Commands.add('myCustomCommand', () => {
  cy.wait(1*60000) // 1 minute
  cy.wait(1*60000) // 1 minute
  cy.wait(1*60000) // 1 minute
  cy.wait(1*60000) // 1 minute
  cy.wait(1*60000) // 1 minute
})
  
it('test', () => {
  cy.myCustomCommand() 
  cy.get('div') // continues after 5 minutes from previous command
})
```

**Comment by vicatcu** [comment]
Thanks @jennifer-shehane, that's interesting. In that case I must be doing something wrong and I'll have to re-think / dive deeper to understand what is happening in my tests. If I can come up with a concrete example that contradicts this, I'll open a new issue. I'll close this one for now.
