### ISSUE TITLE
Support emojis in test runner

### ISSUE THREAD

**Issue by alexbjorlig** [cypress-io/cypress#9056]
### What would you like?
Emojies in the test runner (it's not there when viewing the video from the dashboard 😢) 

The emojies are replaced with `[]`

### Why is this needed?
You even ask 😂  Emojis are good at communicating emotions efficiently, and testing software with e2e tests covers a broad ranges of feelings from:

😠  --> 🛠 -->  🧐  --> 🛠  --> 😄

**Comment by jennifer-shehane** [comment]
The Cypress Test Runner does support emojis, so a situation where emojis are not shown may be specific to the machine the test runner is run within or some other more specific issue. 

Please provide the test code to run to see this issue and any other specifics, like the operating system / browser you are running within. 

`stdout`

<img width="602" alt="Screen Shot 2020-11-02 at 3 34 37 PM" src="https://user-images.githubusercontent.com/1271364/97849572-2235a780-1d21-11eb-971e-7bb0f77d4ce5.png">

Command Log screenshot from video

<img width="451" alt="Screen Shot 2020-11-02 at 3 34 56 PM" src="https://user-images.githubusercontent.com/1271364/97849610-2feb2d00-1d21-11eb-86c0-c1ca7e825c1a.png">

**Comment by alexbjorlig** [comment]
From the cypress dashboard:

![Screenshot 2020-11-02 at 10 21 23](https://user-images.githubusercontent.com/9967422/97851154-48455280-1cf5-11eb-914c-d398535b7ed9.png)

Details from CI:
![Screenshot 2020-11-02 at 10 22 31](https://user-images.githubusercontent.com/9967422/97851187-53987e00-1cf5-11eb-9add-781849273708.png)

**Comment by jennifer-shehane** [comment]
Are you using a Docker container? Do emoji's render inside of the application under test? You may need to install an emoji font on the machine like `font-noto-emoji`

The below works locally on my machine, which makes me think this is a problem localized to the machine it's running within.

```js
it('Test', () => {
  cy.log("**Testing that revisions work 😄**")
})
```

<img width="456" alt="Screen Shot 2020-11-02 at 4 28 03 PM" src="https://user-images.githubusercontent.com/1271364/97854866-67110c80-1d28-11eb-9f07-d5e01b964ed2.png">

**Comment by alexbjorlig** [comment]
Not using docker container, but the [cypress github action](https://github.com/cypress-io/github-action).

**Comment by bahmutov** [comment]
I can confirm this behavior - the default Ubuntu image does not have most emoji icons. Notice that some emoji are there, but not all

<img width="1279" alt="Screen Shot 2020-11-03 at 10 04 19 AM" src="https://user-images.githubusercontent.com/2212006/98002803-f7e4f800-1dbb-11eb-821a-62055bb25ecc.png">

<img width="1274" alt="Screen Shot 2020-11-03 at 10 03 14 AM" src="https://user-images.githubusercontent.com/2212006/98002713-da179300-1dbb-11eb-8f08-b525744342e3.png">

Project https://github.com/bahmutov/cypress-book-todomvc

**Comment by bahmutov** [comment]
Ok, I have verified locally that installing on Debian `fonts-noto-color-emoji` provides emoji 

![demo-test](https://user-images.githubusercontent.com/2212006/98012031-9b3b0a80-1dc6-11eb-97f0-91dc699a257b.png)

**Comment by bahmutov** [comment]
The workaround: install the font yourself

```yml
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1

      # https://github.com/actions/virtual-environments/issues/710
      - name: Add emoji font 🤩
        run: sudo apt-get install fonts-noto-color-emoji -y
      # run Cypress tests
```

You can see this working in action in https://github.com/bahmutov/cypress-book-todomvc and the generated image https://github.com/bahmutov/cypress-book-todomvc/blob/master/images/demo-test.png

![image](https://user-images.githubusercontent.com/2212006/98013626-98d9b000-1dc8-11eb-889d-096f5d07ca60.png)

**Comment by alexbjorlig** [comment]
> The workaround: install the font yourself
> 
> ```yaml
> jobs:
>   cypress-run:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout 🛎
>         uses: actions/checkout@v1
> 
>       # https://github.com/actions/virtual-environments/issues/710
>       - name: Add emoji font 🤩
>         run: sudo apt-get install fonts-noto-color-emoji -y
>       # run Cypress tests
> ```
> 
> You can see this working in action in https://github.com/bahmutov/cypress-book-todomvc and the generated image https://github.com/bahmutov/cypress-book-todomvc/blob/master/images/demo-test.png
> 
> ![image](https://user-images.githubusercontent.com/2212006/98013626-98d9b000-1dc8-11eb-889d-096f5d07ca60.png)

Thanks @bahmutov. Just wanted to know that we switched to parallel execution of our cypress tests, and it's magic 
 🔥 ! thanks!
