### ISSUE TITLE
cy.route2 cannot wait on the stubbed request with forceNetworkError: true

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9062]
I am trying to confirm that the application handles failed network Ajax calls

```js
cy.visit('/')
cy.route2(url, { forceNetworkError: true }).as('users')
cy.get('#load-users').click()
cy.contains('#users', 'Problem fetching users Failed to fetch')

cy.wait('@users', { timeout: 1000 }) // the network call happens
```

The wait never resolves

![forceNetworkError](https://user-images.githubusercontent.com/2212006/97928708-9bd79080-1d35-11eb-970e-2e9711154f5f.gif)

Screenshot

![](https://user-images.githubusercontent.com/2212006/97928740-a7c35280-1d35-11eb-8de9-711f8cbe8dcd.png)

Cypress v5.5.0 and `develop` at `d12676c561fbd24a47ecd846a54cfe9042402dbe` (which is AFTER `fix: improve route2 logs` commit)

Reproducible example in https://github.com/cypress-io/cypress-example-recipes/pull/581

**Comment by flotwig** [comment]
The issue is that the request never ends up in the `Complete` state for some reason. Seems to be getting stuck on `RequestIntercepted`.

**Comment by dylangarcia** [comment]
I'm running in to this too with `forceNetworkError: true` 👍
