### ISSUE TITLE
Network automation to emulate offline mode only works with DevTools open

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9063]
You can find the tests for this in https://github.com/cypress-io/cypress-example-recipes/pull/581

Imagine I want to test how the web app handles offline mode. I can turn the offline mode using CDP and confirm the `window.navigator.onLine` changes correctly

```js
const goOffline = () => {
  cy.log('**offline**')
  .then(() => {
    return Cypress.automation('remote:debugger:protocol',
      {
        command: 'Network.emulateNetworkConditions',
        params: {
          offline: true,
          latency: -1,
          downloadThroughput: -1,
          uploadThroughput: -1,
        },
      })
  })
}
```

```
cy.wrap(window).its('navigator.onLine').should('be.false')
```

This works.

![online-offline](https://user-images.githubusercontent.com/2212006/97928976-215b4080-1d36-11eb-996e-2bee94f2a826.gif)

Now imagine we actually _make_ fetch requests from the app, and in offline mode they should fail. Check this out - it works. They do fail, but only _when DevTools is open_. Once we close the DevTools, the `navigator.onLine` still changes as expected, but the network calls start all working, as if ignoring the offline mode emulation.

In the video below I run the test several times with DevTools open - it is passing as expected. But when I close the DevTools, the test fails.

![says-offline-but-request-happens](https://user-images.githubusercontent.com/2212006/97929073-5e273780-1d36-11eb-8cc7-3eced12eabbf.gif)

Browsers: Electron 85, Chrome 86, 88, Edge 86

**Comment by EtienneBruines** [comment]
Some sources, like https://github.com/cypress-io/cypress/pull/6932 use the command `Network.enable` first. Does that make any difference in your results @bahmutov ?


```js
      // This seems to be important
      Cypress.automation('remote:debugger:protocol', {
        command: 'Network.enable',
      })

      Cypress.automation('remote:debugger:protocol', {
        command: 'Network.emulateNetworkConditions',
        params: {
          'offline': true,
          'latency': 0,
          'downloadThroughput': 0,
          'uploadThroughput': 0,
          'connectionType': 'none',
        },
      })
```

**Comment by bahmutov** [comment]
OMG @EtienneBruines YES. Of course. I guess when Devtools is opened, the network events are delivered anyway. This solves the problem, bravo 👏 

![offline-workd](https://user-images.githubusercontent.com/2212006/98132678-b3745d80-1e8a-11eb-99c7-09490fa32851.gif)

**Comment by bahmutov** [comment]
done, recipe merged

**Comment by jhnns** [comment]
Unfortunately this recipe does not work anymore in more recent versions of Cypress as described [here](https://github.com/cypress-io/cypress/issues/17723#issuecomment-906152925) 😢

**Comment by gc-bianchi** [comment]
experiencing the same issue @jhnns mentioned.

**Comment by plewkowycz** [comment]
Any solution how we can use offline network mode?

**Comment by yorch** [comment]
Same boat, haven't been able to find a solution or a workaround, stuck in 8.2.0 and can't update to 10 because of this

**Comment by arneevertsson** [comment]
Here is a workaround:

		
```
// cy.goOffline();
cy.intercept(url, request =>
{
    request.destroy()
})

// Now we are "offline"

// cy.goOnline();
cy.intercept(url, request =>
{
    request.continue()
})

// Now we are back online!
```

Just substitute the correct url for your application.
