### ISSUE TITLE
Cannot start server after combining the extension: args.findIndex is not a function is not a function

### ISSUE THREAD

**Issue by Wanda-Jih** [cypress-io/cypress#9067]
**Current behavior:**
I follow the steps from this [website](https://www.npmjs.com/package/cypress-browser-extension-plugin) to load chrome extension in Cypress
Click on test to run in Cypress UI
**Desired behavior:**
Chrome opens and runs the test. I can see the extension icon on the top right.
**Actual behavior**
<img width="799" alt="截圖 2020-11-03 下午4 53 42" src="https://user-images.githubusercontent.com/43124480/97966256-8f673c80-1df6-11eb-83e2-4d9e8f069628.png">

**Comment by jennifer-shehane** [comment]
This is an issue with the plugin, not Cypress. Please see the issue in the cypress-browser-extension-plugin repo: https://github.com/ejoubaud/cypress-browser-extension-plugin/issues/5

That plugin looks very old and hasn't had any updates in 2 years, so it likely doesn't work well with recent versions of Cypress.
