### ISSUE TITLE
Running CI on Bitbucket Pipeline does not update Cypress Dashboard

### ISSUE THREAD

**Issue by pmoon87** [cypress-io/cypress#9074]
### Current behavior

When running CI Integration in Bitbucket Pipeline, and key is set correctly to show on dashboard and record is also set, the results are not displayed on dashboard. 

When I run locally using same commands and keys, the dashboard shows the results. 

### Desired behavior

When running in Bitbucket Pipeline, the run and results should be published to Dashboard.

**Comment by jennifer-shehane** [comment]
There's no reason this shouldn't report to the Dashboard when passing --record with --key and the projectId that you have access to. 

- Is it possible that this projectId is part of a project you don't have access to in the Dashboard? 
- Is there a dashboard url printed at the end of the run output in Bitbucket?

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode in Bitbucket and print the entire set of logs here?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had a response, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
