### ISSUE TITLE
5.5.0 Regression net::ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by garryyao** [cypress-io/cypress#9076]
Hi Cypress team 
I have encountered some errors in attempt to upgrading to Cypress 5.5.0. I suspect the issue is caused by some new experiment you have with `cy.route2`?

# Current behavior
```
VM6059 otBannerSdk.js:1 GET https://cdn.cookielaw.org/vendorlist/iabData.json net::ERR_CONTENT_DECODING_FAILED 200 (OK)
(anonymous) @ VM6059 otBannerSdk.js:1
```
Reproduced on various browsers:
 - Google Chrome Version 86.0.4240.111 (Official Build) (x86_64)
 - Ms Edge 84
 - Firefox 72

### Desired behavior
This was fine when running in Cypress 5.4.0 when trying to load the script.

### Test code to reproduce
Would be unable to share the code, but what the application does is simply trying to load 3rd party scripts.
```js
    <Helmet>
      <link
        rel="preload"
        href="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"
        as="script"
      />
      <script
        async
        src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"
        data-domain-script={oneTrustDomainScript}
        data-document-language="true"
      />
    </Helmet>
```

### Versions

Works in 5.4.0 while failing 5.5.0.

Cypress config:
```json
{
  "baseUrl": "https://localhost:3002",
  "video": false,
  "chromeWebSecurity": false,
  "viewportWidth": 1280,
  "viewportHeight": 720,
  "numTestsKeptInMemory": 0,
  "watchForFileChanges": false,
  "projectId": "pjpqjb",
  "retries": {
    "runMode": 1
  }
}
```

**Comment by jennifer-shehane** [comment]
Can you try our pre-release version to see if this has already been fixed? There are some instructions here: https://github.com/cypress-io/cypress/commit/26e70f5b564dd6b64d881ee051ffcb074415cd6d#comments

**Comment by garryyao** [comment]
Thanks Jen, looks like cannot reproduce anymore in v5.6.0, happy to close it up.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
