### ISSUE TITLE
Including native modules in plugins file fails on Mac

### ISSUE THREAD

**Issue by belzner** [cypress-io/cypress#9078]
### Current behavior
When referencing a native module (for example, `sqlite3`) from the `plugins/index.js` file, cypress is unable to process the plugins file and thus unable to run tests. The error is as follows:

```
Error: dlopen([path]/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
	[path]/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node: code signature in ([path]/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> ([path]/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

If I try ad-hoc signing the package (`codesign --force --deep -s - node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node`) or signing it with a personal certificate, it still fails, but with `mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)` instead of `mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed`.

I found another issue that sounds similar (https://github.com/cypress-io/cypress/issues/8258) but it seems that person may have found a workaround and closed the ticket. I believe this is still an issue overall (I see nothing suggesting issues with node version in my case), so I'm opening a fresh issue.

### Desired behavior
I should be able to use any node module that I can use in my app itself in the plugins file. I was able to work around it in this case, but it required a substantial reshuffling of functionality.

Of note - referencing the `sqlite3` library worked just fine in cypress version 3.4.1, which I recently upgraded from.

Some googling led me to https://github.com/electron-userland/electron-builder/issues/3940, which suggests that a potential fix would be to add `com.apple.security.cs.disable-library-validation` to https://github.com/cypress-io/cypress/blob/develop/scripts/entitlements.mac.inherit.plist - however, I don't know what other implications adding that would have/whether it's intentionally not included/whether there's another approach that would be better. I'd be happy to submit a PR to add this, if it makes sense.

### Test code to reproduce
- Make a new npm project (`npm init`)
- Install cypress (`npm install cypress`)
- Install sqlite3 (`npm install sqlite3`)
- Add the line `const sqlite3 = require('sqlite3');` to the freshly-generated `cypress/plugins/index.js`
- Run `cypress run`, and see that it fails with the above error.
- To ad-hoc sign the package as suggested, run `codesign --force --deep -s - node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node`. Re-run `cypress run`, and see the new variation on the same error.

### Versions
Cypress: 5.5.0 (last known working version, 3.4.1)
Sqlite3: 5.0.0
Node: 12.19.0
NPM: 6.14.8
OS: MacOS Catalina (10.15.7)

**Comment by bahmutov** [comment]
Can you try setting `nodeVersion: system` in your config file https://docs.cypress.io/guides/references/configuration.html#Node-version ? Then Cypress will use your system Node, which allows native extensions to load if you have installed them.

**Comment by belzner** [comment]
ahhhhh yes that worked 😅 thank you!
