### ISSUE TITLE
Removing Test Configuration requires browser refresh

### ISSUE THREAD

**Issue by mccataldo** [cypress-io/cypress#9082]
### Current behavior
It's possible to set Test Configuration as described [here](https://docs.cypress.io/guides/references/configuration.html#Test-Configuration), but if the second parameter is removed (and assuming the file is being watched by the runner), the test will run with the config still applied. If I refresh the browser ( or stop the spec run and select it again), the config is no longer applied as intended.

### Desired behavior
The expectation is when I remove the configuration, that the spec runs without the configuration.

### Test code to reproduce
pull down [my fork (`Day-5` branch) of RWA](https://github.com/iheartjs-dev/cypress-realworld-app/tree/Day-5), 
serve the app (`npm start`), run `npx cypress open` and run the `my-account.spec.js`
take note of the user that's logged in
add a new user with username `user` and password `s3cret` 
add test config to the top-level `describe` like this: 
```js
describe('My Account', { env: { username: 'user' } }, () => {
```
saving the changes will trigger a test run
the new user should be logged in
undo the change to the test config 
saving changes will trigger a run again
notice how the new user is still logged in
refresh the browser (or click `Stop` in the runner and start the spec again)
notice how it no configuration is applied as expected

Note: it doesn't seem to matter if the config is applied to the suite (`describe`) or the test (`it`).
### Versions
Cypress 5.2.0
Chrome

**Comment by jennifer-shehane** [comment]
The example you've given in the `my-account.spec.js` has the `email` data statically coded within the file. So, I don't see where it would normally be reading in environment variables set within the test configuration reading `Cypress.env()`. 

Let me know if I'm missing something, I pulled down the `Day-5` branch.

<img width="551" alt="Screen Shot 2020-11-04 at 12 26 08 PM" src="https://user-images.githubusercontent.com/1271364/98074580-166cf100-1e99-11eb-890e-46e357b030cd.png">

**Comment by mccataldo** [comment]
@jennifer-shehane add test config to the top-level describe like this:
```
describe('My Account', { env: { username: 'user' } }, () => {
...
})
```
