### ISSUE TITLE
Make cy.wait trigger immediate response for delayed cy.route requests

### ISSUE THREAD

**Issue by daiscog** [cypress-io/cypress#9094]
Provide a mechanism for a 'respond now' trigger for a delayed `cy.route` response from within a test.  For example:

```js
cy.route({
  ...whatever,
  delay: 3000
}).as('getShoes');

// Either make `cy.wait` cause a delayed route response to immediately return...
cy.wait('@getShoes'); // getShoes should now return ASAP regardless of the delay configured above

// ...OR add an optional boolean property to the cy.wait options to allow opting-in to this
// timeout short-circuiting behaviour...
cy.wait('@getShoes', { respondNow: true }); 

// ...OR introduce some other dedicated respondNow mechanism, e.g.:
cy.respondNow('@getShoes');
```

### Why is this needed?

Currently we have many tests that verify a loading spinner is shown while waiting for a response which do something like this:

```js
cy.route({
  method: 'GET',
  url: '/api/shoes',
  response: {},
  delay: 3000
}).as('getShoes');

cy.visit('/page-that-gets-shoes');

cy.get('#loadingSpinner').should('be.visible');

cy.wait('@getShoes'); 

cy.get('#loadingSpinner').should('not.be.visible');
```

We have to delicately choose an appropriate delay time here; too short and our tests become flaky (sometimes the response returns before the test for the loading spinner runs, and so the spinner gets hidden too quickly and the test fails), too long and our many loading-spinner tests waste countless seconds in the `cy.wait` step after we've verified the spinner is visible.

The fact we're calling `cy.wait` is an indication that we are no longer interested in the in-flight state, and wish to move on to test the response-received state.  It therefore makes no sense to keep a delayed stubbed request 'in flight' at this stage, as there's nothing else we can do whilst `cy.wait` is waiting.

Therefore, it would speed up our tests if `cy.wait` were to cause a stubbed but delayed request to respond immediately, regardless of the value of the configured 'delay'.

Additionally, if we had a mechanism like this for triggering a stubbed response programmatically, we could then pass `Infinity` as a delay time to indicate to the reader that we do not want this response to return until we are ready to test the response-received state.

**Comment by jennifer-shehane** [comment]
We generally write a specific test for loading states. So, the test completes after the loading state is found and can move on to another assertion. 

Would this structure work in your use case?

```js
it('shows loading spinner', () => {
  cy.route({
    method: 'GET',
    url: '/api/shoes',
    response: {},
    delay: 5000
  }).as('getShoes');

  cy.visit('/page-that-gets-shoes');
  cy.get('#loadingSpinner').should('be.visible');
})

it('loads page', () => {
  cy.route({
    method: 'GET',
    url: '/api/shoes',
    response: {}
  }).as('getShoes');

  cy.visit('/page-that-gets-shoes');
  cy.wait('@getShoes'); 
  cy.get('#loadingSpinner').should('not.be.visible');
})
```

We're moving our HTTP request handling API to the api used now in `cy.route2()`, so there may be something in there that would make this easier also. https://on.cypress.io/route2

**Comment by daiscog** [comment]
Hi @jennifer-shehane, thanks for the response.

We try to minimise the amount of `cy.visit()` calls in our tests because they involve full page reloads, so are relatively slow.  Also, the [best practices](https://docs.cypress.io/guides/references/best-practices.html#Creating-%E2%80%9Ctiny%E2%80%9D-tests-with-a-single-assertion) advocate avoiding writing multiple small tests like this.

I've read a little about route2 although not tried using it yet.  On the face of it, it does look like we might be able to use request interception callbacks to prevent the response until we're ready for it.  However, it appears that we'll still need to do most of the heavy lifting there ourselves.  Something built-in and simple would be preferred, but I guess I could always write a library or similar that wraps route2 and delivers the required functionality with a simple API. :)

I'd understand if you'd rather focus your efforts on getting route2 to GA than take on any new feature work for the existing cy.route mechanism, so happy for you to consider this a "won't fix" if you're confident route2 will make it out of the experimental state and into core in the near future.  (Any ETA on that, by the way?)

**Comment by jennifer-shehane** [comment]
I think you should be able to achieve this by overwriting the `cy.intercept()` now. Check out our new intercept docs: https://on.cypress.io/intercept

**Comment by daiscog** [comment]
Hi @jennifer-shehane 

Yes, thanks, intercept solves this for me.  I even wrote [a block post about it](https://blog.dai.codes/cypress-loading-state-tests/). :)

Thanks!
