### ISSUE TITLE
Redirect with status 307 not working in Cypress

### ISSUE THREAD

**Issue by glennremar** [cypress-io/cypress#9098]
I was trying to automate login to our application using Cypress.  If I tried without ports, it worked.  If I tried with ports, test fails in Cypress 4.02 with Chrome message - url "didn't send any data.".  When I look in Chrome and compare to Cypress, it looks like it could not get past a redirect with status of 307.  The code was redirecting from http to https with same url.   I checked code and it was doing a forward for request.  Have there been any fixes in more recent versions of Cypress that may handle this or are there any workarounds without having to change production code?

**Comment by jennifer-shehane** [comment]
We're not currently aware of any issues with redirects on 307.

When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
