### ISSUE TITLE
throw error when attempting to .select() an option that doesn't exist or is disabled.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#91]
**Description**
When using the `.select()` command, you can pass in a value or text that doesn't exist in the select's options. The command log performs normally as if the option was selected, although it was not.

**Code**
```html
<select>
  <option value="foo">Foo</option>
</select>
```

```javascript
cy.get("select").select("baz")
```

No error will be thrown with the above code.

**Additional Info**
It is additionally possible to set `<option>` as `disabled`. The `.select()` command should thrown an error if attempting to select a disabled option.

**Comment by brian-mann** [comment]
Fixed in [`0.13.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0133-12252015).
