### ISSUE TITLE
Fail tests that have unexpected API requests

### ISSUE THREAD

**Issue by Graham42** [cypress-io/cypress#910]
### Is this a Feature or Bug?
Feature

### Desired behavior:
I'd like a way to fail a test for any XHR calls that are not expected (ie. that no `cy.route()` has been set for). Current there's a `force404`, but that's not enough to be able to actually cause a test to fail

I had thought of using the `onResponse` option but it gets bypassed for the requests that `force404` handles.

```js
cy.server({
  force404: true,
  onResponse: xhr => {
    if (xhr.status === 404) {
      expect(true).to.equal(false);
    }
  }
});
```

**Comment by bryantabaird** [comment]
Still wasn't able to find a way to cause a test to fail if the `force404:true` is invoked, any updates on this issue?

**Comment by TomPradat** [comment]
Any news about this, I'd love to see this happen. Is there a lot of work ? I can work on if not

**Comment by AlexDaniel** [comment]
So, am I missing something, or is there actually no way to check that no request during the test returned with 500 status code? If my backend responds with 500, then there's definitely an issue that I'd like to fix, so I want the test to fail.

**Comment by nwalters512** [comment]
I also ran into this. In my case, I had a test that was submitting a form, but due to a bug in the backend code under test, the server replied with a 403. Because I didn't actually assert anything about the response HTML, that test was passing when it shouldn't have. I can update the test to look for something specific in a correct response, but it'd be great to have the test automatically fail in that scenario.

**Comment by flotwig** [comment]
Hi everyone, this is possible to do with [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept), because intercepts are matched in reverse order, it's possible to block all HTTP requests and only allow certain ones:

```ts
// block all HTTP requests
cy.intercept('*', (req) => {
  throw new Error(`Received an unexpected request to ${req.url}!`)
})
// allow some expected requests
cy.intercept('/api', (req) => {
  // call `req.continue()` to stop the request from propagating to the block handler
  req.continue()
})
```

Closing since this is now possible.
