### ISSUE TITLE
cookie not getting deleted

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#9100]
### Current behavior

It is hard to debug when this [issue](https://github.com/cypress-io/cypress/issues/9099) exists.

So to avoid logging in via UI, we make an authentication API request then set appropriate cookie for it. After that, we visit the site then log out of the account. Once we log out of such account, our application deletes such cookie, but somehow cookie still exists.

Does Cypress recreate such cookie again or persist permanently by default?

<img width="328" alt="Untitled3" src="https://user-images.githubusercontent.com/2043287/98174832-5a1c2680-1eaa-11eb-9461-1d2adb29606f.png">
### Test code to reproduce

```js
  it('request', function() {
        cy.createUserAndLoginViaAPI(); //(generate necessary authentication information and set cookie)
        cy.goTo('url');
        cy.getCookie("au").should('exist');
        // the following is the steps to take to log out of our application
        cy.get('.dots').click();
        cy.get('.side-nav-link.secondary-nav-logout').click();
        cy.get('.button.button.btn-primary').eq(1).click();
        // our application deletes `au` cookie once account is logged out
       // checking that account is logged out by checking `au` cookie doesn't exist any more. (From UI, account is logged out but somehow cookie still exists)
         cy.getCookie("au").should('not.exist');
    })
```

### Versions

Cypress: 5.5.0
Chrome: 86.0.4240.111
MacOS: 10.15.6

**Comment by EtienneBruines** [comment]
Some debugging pointers:

You may want to check devtools, to see if any of those four xhr-requests `POST 201, POST 200, GET 200, POST 200` returns any cookies. 

If you are deleting the cookie in javascript, you can check if that line of code is called by doing `console.log` and see if it pops up.
