### ISSUE TITLE
Runs in PHP server but do not in Apache server

### ISSUE THREAD

**Issue by opslon** [cypress-io/cypress#9101]
### Current behavior
**Hey guys, hope you all doing well.**

I'm building a "front-end" so our PO's can run cypress tests just clicking in a button when they desire.
So I've been struggling with an error that claims me to install a already installed cypress.

We are running a Apache server with PHP interpreter, and we did a real-time terminal log update on screen.
![image](https://user-images.githubusercontent.com/2319660/98191297-a2ae0100-1ef7-11eb-901d-12cfbda90f4f.png)

As in the screenshot upwards, the test runs fine, but in this case I was using a local php server only (php -S localhost:3000) in a Ubuntu, which isn't ideal, only for checking purposes.

The issue begins when I tried to run in a Apache server.
![image](https://user-images.githubusercontent.com/2319660/98191620-5ca56d00-1ef8-11eb-9c9b-98fb584e91f5.png)
It claims that cypress is not installed.

I'm using the same build also the same directory of the project test, I can run booth PHP only or Apache server, _not at the same time obviously._
I verified if PHP was responding in Apache server as it needs a PHP module installed to run PHP scripts in Apache server, and it's all fine, the results went well.

**Hilight:**
The project directory is ->
/var/www/html/php_app_prod/Cy/SetBrasil_automato/node_modules/.bin/

Well, I couldn't find any help in the web, related to it.

My final build will run in a Apache server, and I'm afraid it will fail.

### Desired behavior
Apache server should run as in PHP server, can anyone help me?

### Test code to reproduce

This is my PHP code, it will be inside a "div" tag
``` PHP
<?php
    $cmd = 'npm run --prefix ./Cy/SetBrasil_automato cypress'; // Comando Customizado
    while (@ ob_end_flush()); // termina os output buffers se qualquer um existir

    $proc = popen($cmd, 'r'); // cria um pipe para receber os outputs do $cmd
    echo '<pre class = "grey lighten-3 px-3 mb-0 line-numvers">';
    while (!feof($proc))
    {
        echo fread($proc, 4096); //tamanho do buffer em 4096kb
        @ flush(); // limpa o log depois do limite do buffer
    }
    echo '</pre>';
    echo 'Finalizado o processo de execução...';

?>
```
These are my scipts from package.json
``` JSON
  "scripts": {
    "clean-reports": "rm -rf cypress/results",
    "test": "npx cypress run",
    "merge-report": "npx mochawesome-merge --reportDir cypress/results/*.json > cypress/results/full_report.json",
    "generate-report": "npx mochawesome-report-generator --reportDir cypress/results cypress/results/full_report.json",
    "after:tests": "npm run merge-report; npm run generate-report",
    "cypress": "npm run clean-reports; npm run test; npm run after:tests"
  },
```

### Versions

I'm using:
PHP 7.4.3
Apache2
Ubuntu 20.04.1 LTS x86_64 
Cypress 5.5.0

----
If any information is required, please feel free to ask me.
Also I'm a new programmer so I might be missing something.

Best regards!

**Comment by EtienneBruines** [comment]
Just a dumb question, but:

Is there anything within `/var/www/.cache/Cypress/5.5.0/Cypress/Cypress`? 
Is it a binary marked executable by the apache/httpd/www-data user?

```
$ ls -lh /var/www/.cache/Cypress/5.5.0/Cypress/Cypress
```

You may want to run `npx cypress info` both on apache and PHP, to see what's the difference. Preferably the same way you'd want to do `npx cypress run`.

**Comment by opslon** [comment]
> Just a dumb question, but:
> 
> Is there anything within `/var/www/.cache/Cypress/5.5.0/Cypress/Cypress`?
> Is it a binary marked executable by the apache/httpd/www-data user?
> 
> ```
> $ ls -lh /var/www/.cache/Cypress/5.5.0/Cypress/Cypress
> ```
> 
> You may want to run `npx cypress info` both on apache and PHP, to see what's the difference. Preferably the same way you'd want to do `npx cypress run`.

@EtienneBruines ,
Thank you that opened my eyes.

Running "npx cypress info" the responses show that the Binary was in "/home/opslon/.cache/Cypress"
I just copied the Cypress directory after the /.cache and pasted in my /var/www/.cache/
After that Cypress asked me to install dependencies such as "xvfb".

I've done all that before but I had to do it again so Cypress could run in Apache's directory.

Maybe, It's possible I have two instances of Cypress in my machine?
Any way, following this path it was able to run Cypress in Apache server.

Thanks again, that helped a lot.
