### ISSUE TITLE
Chrome and Electron errors when using clipboard API

### ISSUE THREAD

**Issue by penx** [cypress-io/cypress#9105]
### Current behavior

When this code is executed in a Cypress test:

```js
if (navigator?.clipboard?.write) {
  navigator.clipboard.write([new window.ClipboardItem({
    'text/html': new Blob(['<div>Some HTML</div'], { type: 'text/html' }),
    'text/plain': new Blob(['Text Fallback'], { type: 'text/plain' }),
  })])
}
```

Chrome 86 throws the error:
`DOMException: Document is not focused`

(this is specific to Chrome running within Cypress, the code works in Chrome normally)

Electron throws the error:
`DOMException: Type text/html not supported on write`

### Desired behavior

I should be able to write a test that executes this code without it throwing an error, or else use feature detection to alter the behaviour of the code depending on the browser capabilities.

### Versions

Cypress 5.5.0.490272
Mac OS X 10.15.7

**Comment by sainthkh** [comment]
There are 2 types of `window`s in Cypress:

* AUT window: It's the app in iframe. You can see this on the right side of the screen.
* Runner window: It's the entire app with the status report on the left and AUT window on the right. 

When calling `window` without `cy.window`, you're calling the Runner window. That's, why it should be called like this: 

```js
it('t', () => {
  cy.visit('fixtures/dom.html')

  cy.window((window) => {
    if (navigator?.clipboard?.write) {
      navigator.clipboard.write([new window.ClipboardItem({
        'text/html': new Blob(['<div>Some HTML</div'], { type: 'text/html' }),
        'text/plain': new Blob(['Text Fallback'], { type: 'text/plain' }),
      })])
    }
  })
})
```
