### ISSUE TITLE
Issue with iframes in version 5.5

### ISSUE THREAD

**Issue by nevetsmik** [cypress-io/cypress#9108]
### Current behavior
Cypress isn't passing all available iframes to our application code which checks on iframes to validate selected elements.

### Desired behavior
All available iframes should be passed to our application code.

### Versions
Current behavior is in version 5.5
Desired behavior is in version 5.4

https://dashboard.cypress.io/projects/x5jiv3/runs/5520/specs
https://dashboard.cypress.io/projects/x5jiv3/runs/5539/specs

**Comment by vitalyk** [comment]
@nevetsmik I double this issue. Recently I've found strange behaviour in version 5.5.0 while 5.4.0 it still works fine.
my test app has stripe payment section which represents on UI text fields for the card details. Every text filed is located within separate iframe. In v.5.5.0 structure is completely different and brakes my tests.

**Comment by amolinaalvarez** [comment]
same issue here!

**Comment by jennifer-shehane** [comment]
There was a regression in 5.5.0 that I think is likely related to your issues. https://github.com/cypress-io/cypress/issues/8992 It's hard to completely verify without a reproducible example, but that was the biggest issue introduced in 5.5.0.

There is a fix for it that should go out in the next release. https://github.com/cypress-io/cypress/pull/9018

**Comment by amazza-bg** [comment]
This doesn't seem to be resolved in 5.6.0 either. I am utilizing the following method:

https://medium.com/@you54f/configuring-cypress-to-work-with-iframes-cross-origin-sites-afff5efcf61f

 which is related to this issue and the the issue started with 5.5.0 and is still occurring in 5.6.0

**Comment by DBLaci** [comment]
FYI: i had this issue with Google Recaptcha. It was working fine in 5.3 (for sure), and failed because iframe hasn't loaded. In my case, the problem is solved in 5.6.0.

**Comment by vitalyk** [comment]
The issue is gone for me too.
