### ISSUE TITLE
Generic for cy.request response body

### ISSUE THREAD

**Issue by dimazuien** [cypress-io/cypress#9109]
Having a type of response body would be more convenient for TypeScript users

Currently, I see that request and response type annotations look like
```ts
request(url: string, body?: RequestBody): Chainable<Response>

interface Response {
  allRequestResponses: any[]
  body: any
  duration: number
  headers: { [key: string]: string }
  isOkStatusCode: boolean
  redirectedToUrl: string
  requestHeaders: { [key: string]: string }
  status: number
  statusText: string
}
```

If we change it to
```
request<T = any>(url: string, body?: RequestBody): Chainable<Response<T>>

interface Response<T = any> {
  allRequestResponses: any[]
  body: T
  duration: number
  headers: { [key: string]: string }
  isOkStatusCode: boolean
  redirectedToUrl: string
  requestHeaders: { [key: string]: string }
  status: number
  statusText: string
}
```
then a user will be able to specify the response body type in their code.

**Comment by jennifer-shehane** [comment]
We would be open to reviewing any Pull Requests made trying to improve the typings. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by dimazuien** [comment]
@jennifer-shehane, could you take a look at [PR](https://github.com/cypress-io/cypress/pull/9152) and let me know if there's anything else you need
