### ISSUE TITLE
Illegal invocation TypeError after xhr request when upgrading to 5.5.0

### ISSUE THREAD

**Issue by yunj** [cypress-io/cypress#9112]
### Current behavior
After a HTTPS xhr request, an illegal invocation TypeError appears in the console after upgrading to 5.5.0.
![TypeError](https://user-images.githubusercontent.com/18545475/98325406-98a11500-2053-11eb-850c-823f399032dd.PNG)

### Desired behavior
Our tests work well in 5.3.0 and 5.4.0. No TypeError caused by upgrading to 5.5.0.

### Versions
Cypress 5.5.0
Windows 10
Chrome 86

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by yunj** [comment]
Hi @jennifer-shehane it's very complex application and it's not easy to provide a reproducible example. Do you think cypress log is helpful or do you have a rough idea what's the potential issue since the changes between 5.4.0 and 5.5.0 are manageable? Thanks.

**Comment by yunj** [comment]
Hi @jennifer-shehane Cypress 5.6.0 somehow fixes the issue.
