### ISSUE TITLE
testId should not have been hidden in ModuleAPI

### ISSUE THREAD

**Issue by c32hedge** [cypress-io/cypress#9119]
### Current behavior

#8076 indicates that the `testId` field was removed from the Module API test run results in 5.0.0, with the rationale that they were "not useful to end users".

While this may be true of the other fields, I disagree about `testId`, and in fact I _was_ using it. My use case is postprocessing test results to compare them with previous results for the same tests. The `testId` allowed me to conclusively compare two tests, and also gave me an indication of when additional tests had been added prior to the test in question, which might invalidate the comparison. The `title` field is not sufficient since two tests could have the same title.

### Desired behavior

The `testId` field is restored in the Module API test run results.

### Test code to reproduce

N/A, see linked PR where field was removed.

### Versions

5.0.0

**Comment by jennifer-shehane** [comment]
@c32hedge Thanks for taking the time to explain the feature you'd like. The `testId` was never a stable ID, so would not have been reliable to use. We just auto-incremented the `testId` - so the testid generation would be something like below:

First run:

```js
it('test', () => {})         // testId: t1
it('another test', () => {}) // testId: t2
```

Second run:

```js
it('test', () => {})                // testId: t1
it('oh, lets add a test', () => {}) // testId: t2
it('another test', () => {})        // testId: t3
```

If you're running postprocessing to compare `t2` in the first run with `t2` in the second run - they're completely different tests. I'm not sure with a larger test suite how you would determine where the new test was added exactly with this generation.

Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by c32hedge** [comment]
@jennifer-shehane I was aware that the ID wasn't stable, but combine with the test `title` it gave me higher confidence that I was comparing apples to apples across test runs. That is, I used _both_ the ID and the title to identify a test. If a new test was added earlier in the suite, I expected that combination to no longer match for a given comparison for the reason you mentioned. However, I still felt that was better than using `title` alone and the possibility of not being able to guarantee I could uniquely differentiate between tests.

**Comment by c32hedge** [comment]
As another data point, I had actually added the `testId` to the file name for the `cypress-failed-log` plugin as part of https://github.com/bahmutov/cypress-failed-log/pull/196 to help ensure uniqueness when truncating save file names, which Gleb recently had to remove as part of https://github.com/bahmutov/cypress-failed-log/pull/240
