### ISSUE TITLE
Installing Cypress for every project I work on takes too much space

### ISSUE THREAD

**Issue by nwwells** [cypress-io/cypress#912]
- Operating System: Mac OS X
- Cypress Version: 1.0.3
- Browser Version: N/A

### Is this a Feature or Bug?
Bug

### Current behavior:
`npm install cypress` installs the Electron app for every project i do it on. It's heavy: 320MB. Which means that since I have it installed on 4 projects, almost a gig of disk space is wasted on an electron app duplicated 4 times :(

### Desired behavior:
Make the primary method of installing the cypress app system or user global

### How to reproduce:
```
npm install cypress
```

#### Test code:
```js
du -hs node_modules/cypress/
```

**Comment by nwwells** [comment]
Sorry I didn't respond quickly, I haven't had time to test this. But all the documentation suggests that installing per-project is correct. Even if I do install "globally", it will only be global per node version (I use nvm). I tried downloading the Cypress app, but wasn't clear on how to make it work, so I read the docs, which lead me to install per-project.

**Comment by bahmutov** [comment]
So even single global npm install is too much because there are multiple versions managed by NVM? You could potentially install cypress locally then copy the folder from Node modules into a global folder, create an alias and have a truly global tool. We highly not recommend this though because you are loosing versioning and have to do this on every box and CI provider!

**Comment by brian-mann** [comment]
If you're on OSX you could just manually download and unzip into your `~/Applications` folder. Then you'll always use it in global mode and not have it installed via `npm` at all. You'd lose access to the command line, but you could at least use it across all projects.

Really the only solution around this is to generate a "headless" version of Cypress without Electron bundled in - so no GUI and no Electron browser. This would also work from the command line, but you would still get the browser launching + GUI interface in there. Everything would work the same. That's the long term answer IMO.

Right now its very much off topic for us so I wouldn't bet on this being done for awhile.

**Comment by nwwells** [comment]
A headless version sounds perfect. Should I open a separate issue for that? would you be open to a PR that allows a headless version?

**Comment by brian-mann** [comment]
Sure.
