### ISSUE TITLE
Getting Session Expired error message when user is trying to click on any Title menu on home page

### ISSUE THREAD

**Issue by Spandana-test** [cypress-io/cypress#9122]
Issue Description: 
1.User logged in using creds
2.Tring to click any menu on the titlebar on the home page(sending request to server)
3.Tried using xsrf protection and sync id disabled in vaadin application.

Actual Result: Getting Session expired error
Expected Result: It should allow user to the next page

Application is built using vaadin components.

**Comment by Spandana-test** [comment]
Let us know if you need any inputs

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
