### ISSUE TITLE
5.5.0 breaks window.addListener('message', listener)

### ISSUE THREAD

**Issue by adrienharnay** [cypress-io/cypress#9127]
### Current behavior

Since upgrading from 5.4.0 to 5.5.0, this code doesn't execute anymore:

```js
    const listener = (event: MessageEvent) => {
      if (event.data.type === 'form-submit') {
        console.log('yay');
      }
    };

    window.addEventListener('message', listener);
```

### Desired behavior

When testing with Cypress 5.4.0, the event listener is called.

### Test code to reproduce

```js
    const listener = (event: MessageEvent) => {
      if (event.data.type === 'form-submit') {
        console.log('yay');
      }
    };

    window.addEventListener('message', listener);
```

This code should be called when a form is submitted (in my case I'm using typeform).

### Versions

Failing: 5.5.0
Working: 5.4.0
OS: MacOS / Linux
Env: Local / DroneCI

**Comment by jennifer-shehane** [comment]
Can you provide the test code to run against this app code that will show the error?

**Comment by adrienharnay** [comment]
Hello, sorry about the delay, it has been fixed with cypress 6.0.0

**Comment by prdarm** [comment]
armsomboon2@gmail.com​

**Comment by dasDaniel** [comment]
Seeing the same issue in v9.1.1

For the time being, moved to test "implementation detail" instead of testing integration.

FWIW, the issue appears when testing communication between a page and an iframe. The parent can send messages, but will not receive messages from the iframe via `window.addEventListener('message', listener);`

**Comment by selcukvp** [comment]
Having the same issue with v9.5.3

@dasDaniel Have you come up with any solution there?
