### ISSUE TITLE
FileObject type should extend EventEmitter

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#9132]
# Current behavior

From your [documentation](https://docs.cypress.io/api/plugins/preprocessors-api.html#File-events):

> The `file` object passed to the callback function is an [Event Emitter](https://nodejs.org/api/events.html#events_class_eventemitter).

The [types](https://github.com/cypress-io/cypress/blob/v5.5.0/cli/types/cypress.d.ts#L4985-L4989) however does not reflect this.

### Desired behavior

For the types to always correctly reflect the reality.

### Versions

Latest (v5.5.0), but I'm guessing all versions are affected.

**Comment by jennifer-shehane** [comment]
We would be open a PR to refine these typings. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by sainthkh** [comment]
@bahmutov Can I use `EventEmitter2` [here](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress-eventemitter.d.ts)?

It's not a solution because `EventEmitter2` has some functions that `EventEmitter` doesn't have. But I guess it's the only option we have.

**Comment by sainthkh** [comment]
Forget it. I solved the problem by copying the definition of `EventEmitter`.

**Comment by bahmutov** [comment]
Released in v6.2.0
