### ISSUE TITLE
Race condition when running multiple Cypress instances in CI

### ISSUE THREAD

**Issue by stevenleeg** [cypress-io/cypress#9135]
### Current behavior
We run Cypress in parallel in our CI environment. Our CI provider (Google Cloud) shares the working directory between steps (which run in parallel), and we're noticing that Cypress will occasionally fail with the following error:

```
 /workspace/app/node_modules/.bin/cypress run --record --parallel --ci-build-id [redacted] --browser chrome
[17:40:44]  Verifying Cypress can run /root/.cache/Cypress/5.5.0/Cypress [started]
[17:40:47]  Verified Cypress!       /root/.cache/Cypress/5.5.0/Cypress [title changed]
[17:40:47]  Verified Cypress!       /root/.cache/Cypress/5.5.0/Cypress [completed]

================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    5.5.0                                                                              │
  │ Browser:    Chrome 84                                                                          │
  │ Specs:      13 found [redacted]                                                                          │
  │ Params:     Tag: false, Group: false, Parallel: true                                           │
  │ Run URL:    https://dashboard.cypress.io/projects/pe6of4/runs/1316                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  [redacted].spec.js                                                        (1 of 13)
  Estimated: 43 seconds
EEXIST: file already exists, mkdir '/builder/home/.config/Cypress/cy/production/browsers/chrome-stable/run-462/CypressExtension'
Error: EEXIST: file already exists, mkdir '/builder/home/.config/Cypress/cy/production/browsers/chrome-stable/run-462/CypressExtension'


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I believe the issue here is some sort of race condition caused by both build steps executing Cypress at the same time, attempting to install this chrome extension, and failing when it realizes that the other has already installed it. The other instance of Cypress appears to run without issue, at least until our CI automatically kills the process because the other has failed.

### Desired behavior
Both instances of Cypress succeed, not showing a `EEXIST` error.

### Test code to reproduce
Begin running two instances of Cypress at the same time on the same machine in the same directory with the following command:

```cypress run --record --parallel --ci-build-id $BUILD_ID --browser chrome```

Note that this appears to be a race condition, as this is an issue that maybe affects 20% of our builds.

### Versions
We've found this to be an issue on Cypress 5.5.0.

**Comment by jennifer-shehane** [comment]
We don't recommend running 2 instances of Cypress at the same time on the same machine. There are other issues you may encounter, but the main one being that most machines are too underpowered to run multiple Cypress instances at once, so you'll often run into CPU issues. 

We recommend running each call to `cypress run` on separate machines.

**Comment by stevenleeg** [comment]
Hi Jennifer,

I'm a little confused by your response, as this is a very common CI pattern on a major cloud platform. We're running this on a higher end machine (n2-highcpu-8) and in two entirely separate Docker containers, so I don't believe performance is the issue here– I believe it to be some sort of race condition within Cypress itself.

**Comment by jennifer-shehane** [comment]
If Cypress is running on 2 completely different machines, then the Cypress applications has no way of interfering with each other to cause a race condition. They would be using completely different file systems on two different machines, 2 separate Chrome browsers, etc.
