### ISSUE TITLE
CypressError: Timed out retrying: coordsHistory must be at least 2 sets of coords

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#914]
- Operating System: Windows 10
- Cypress Version: 1.0.3
- Browser Version: 62

### Is this a Feature or Bug?
Bug

### Current behavior:
When running my tests I try to trigger a dragDrop event. Even when passing { force: true }, this exception is still encountered. This only happens on headless test runs. It worked fine in the browser.

### Desired behavior:
Ideally this exception wouldn't be thrown. Not sure why it's happening.

### How to reproduce:
This happened using anglar-file-upload code in a private respository. Not sure the best means to reproduce.

#### Test code:

```js
    it('Allows for ---- Upload', function () {
      cy.get('.my-drop-zone').first()
        .trigger('dragover', this.dropEvent)
        .should('have.class', 'nv-file-over')
        .trigger('drop', this.dropEvent, { force: true }) // this is where it fails even with force true
    })
  })
```

### Additional Info (images, stack traces, etc)

![image](https://user-images.githubusercontent.com/2848185/32797531-1b3e85e2-c940-11e7-8999-fe66b79bafbf.png)

**Comment by jennifer-shehane** [comment]
Error thrown in Cypress code can be found here: https://github.com/cypress-io/cypress/blob/issue-827/packages/driver/src/cy/actionability.coffee#L198

**Comment by chrisbreiding** [comment]
It's possible it's `trigger('dragover')` that causes the error. Does the error still occur if you put `{ force: true }` on that too?

**Comment by egucciar** [comment]
@chrisbreiding  yes the error is getting occurred when i have force: true, as can be seen with the code snippet I provided. I don't think my test code is as fault here since it works as expected in the browser, even without { force: true }

**Comment by brian-mann** [comment]
FYI passing `{ force: true }` as the 3rd argument is not a valid signature. It sounds weird but we expect you to pass that along with the event.

So `this.dropEvent.force = true`.

Didn't actually test this, and it may not have anything to do with the issue you're having.

**Comment by egucciar** [comment]
I will try with the updated code and let you know. Hope it will fix my issue.

**Comment by egucciar** [comment]
@brian-mann 

passing force along with the dropEvent in the second parameter **fixed my issue**!! thanks so much for the assistance now all my tests can pass!!

**Comment by afamee** [comment]
I am experiencing similar issues in my own test. The frustrating part is that its not consistent.

-     Operating System: Windows 10 Pro
-     Cypress Version: 3.3.2


![gitMultiClickCoordsIssue](https://user-images.githubusercontent.com/43623085/60539188-f59ef500-9cc0-11e9-8092-99539f191273.png)

Here is the piece of code:

`
andValidateMvrReport(last, valid){

    cy.get('a#Tab_DataReports').should('be.visible').then(dr => {

      cy.wrap(dr).click();

      cy.get("img[src='img/expand.gif']").click({ multiple: true, timeout: 16000 })

      cy.get("tr[id^='rowInProcess']")
      .find('td').contains('Get MVR for '+last).as('currrow').then(() => {

        cy.get('@currrow').parent().prev('tr').as('therow')
        
        cy.get('@therow').within(() => {
          cy.get("td[id$='ResultCd']").should('have.text', valid);
        })
      })
    })
    return this;
  }`
