### ISSUE TITLE
update npm with version 5.6

### ISSUE THREAD

**Issue by alexborovkov** [cypress-io/cypress#9140]
Please update npm with latest 5.6 version

![image](https://user-images.githubusercontent.com/22237897/98592285-90123e00-22e2-11eb-9117-ba5ccd12c7ba.png)

![image](https://user-images.githubusercontent.com/22237897/98592307-97394c00-22e2-11eb-8628-c8f2ee7f6c4f.png)

**Comment by jennifer-shehane** [comment]
5.6.0 has been released. Everything is coordinated to auto publish, so it may not be instantly synced with the docs or release tag for example. 

<img width="660" alt="Screen Shot 2020-11-10 at 7 56 48 PM" src="https://user-images.githubusercontent.com/1271364/98679925-16845980-238f-11eb-93f1-b8c722122735.png">
