### ISSUE TITLE
Cypress | Posting formdata not working on Electron browser or headless mode of chrome

### ISSUE THREAD

**Issue by anjalichhabra29** [cypress-io/cypress#9142]
I tried multiple things to assert API response returned from XHR request. It works completely fine when i run on Chrome GUI mode. As soon as i switch to electron browser or headless mode of chrome API response is marked are undefined. 

/////// Code from `command.js`: 
```js
Cypress.Commands.add('form_request', (method, url, formData) => {
     const xhr = new XMLHttpRequest();
     xhr.open(method, url,false);
  
     xhr.send(formData);
    if(xhr.status==400){
        return xhr.response
    }
})
```

///// Code from test case 
```js
const url=http://urlToUploadAFile
const method = 'POST';
const filePath='PathToFixtures'

methodNameXYZ(fileName, UI_response){
        return cy.fixture(filePath+fileName, 'binary').then( (excelBin) => {
                Cypress.Blob.binaryStringToBlob(excelBin).then((blob) => {
                    const formData = new FormData()
                    formData.set('prefUpdateFile', blob, fileName)
                    cy.form_request(method, url, formData).then( (response) => {

                        cy.log(response)

                        /*var a=(response.responseText).split(':')
                        expect(UI_response.text().trim()).to.eq(a[1].substring(1,a[1].length-2).trim())*/


                   })
 })

        })
    }
```

[NOTE] : Here I'm expecting 400 response from API to validate negative case. 

> When using Electron, mentioned API doesn't even called( not appear in Network logs)
> When copied command.js code in main test file - it calls mentioned API ( API call appears in network logs - with expected response) but cypress not able to read api response. -- tried using alias waits, cypress.promise, cy.wait,  xhr.onreadystatechange --- still no luck. 

Need help here for solution.
Thanks.

**Comment by flotwig** [comment]
@anjalichhabra29 it seems like you are trying to upload a file. Please use the [`cy.selectFile()`](on.cypress.io/selectfile) API available in newer Cypress versions, that should fix this issue. If you are still having issues, please open a new issue.
