### ISSUE TITLE
Incorrect config values shows for retries in App Settings Page when set from plugins file

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#9143]
### Current behavior

Similar to #7652 but this is for `retries` properties.
<img width="1417" alt="Untitled5" src="https://user-images.githubusercontent.com/2043287/98613577-5f62e200-22ab-11eb-8e5c-ee0015e84feb.png">

### Versions

Cypress: 5.5.0
Chrome: 86.0.4240.183
MacOS: 10.15.6

**Comment by jennifer-shehane** [comment]
I do see that the incorrect number of retries shows in the *Settings* tab on the Test Runner. It even correctly says that it's set from the plugins.

<img width="214" alt="Screen Shot 2020-11-16 at 1 19 36 PM" src="https://user-images.githubusercontent.com/1271364/99221154-70ad7080-280e-11eb-860a-7cbf872c00a1.png">


But I don't see this actually affecting how the tests are run. `retries` set within the plugins file does take effect and retries failing tests.

Test retries will only occur if a test fails - so it wouldn't retry the passing test that you have shown in the screenshot. 

`plugins/index.js`

```js
module.exports = (on, config) => {
  config.retries = {
    "runMode": 3,
    "openMode": 3
  }

  return config
}
```

`spec.js`

```js
it('test', () => {
  cy.log(Cypress.config('retries')).then(() => {
    expect(true).to.be.false
  })
})
```

<img width="561" alt="Screen Shot 2020-11-16 at 1 13 56 PM" src="https://user-images.githubusercontent.com/1271364/99220745-9a19cc80-280d-11eb-8cea-9cc9ceae2a24.png">

**Comment by flotwig** [comment]
In Cypress 10, the `desktop-gui` was replaced by the `launchpad` and `app` components. I've confirmed that this bug still exists in Cypress 10 with the `app`. Using Jennifer's repro: 
![image](https://user-images.githubusercontent.com/1151760/171513735-c73fe0fc-0af7-45c0-9480-ac62c9286338.png)
