### ISSUE TITLE
Cucumber not working. Got Missing Step Implementation issue

### ISSUE THREAD

**Issue by proganeshg** [cypress-io/cypress#9146]
Given
I open login page
2
then
{}, function(){}
Error
Step implementation missing for: I open login page
 );

**Comment by jennifer-shehane** [comment]
You may want to check with the cypress cucumber plugins issues: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor

When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
