### ISSUE TITLE
5.6.0 is 50% slower than 3.8.0

### ISSUE THREAD

**Issue by IMightGitIt** [cypress-io/cypress#9149]
I started noticing that running my tests locally ran slower and slower in the newer releases. So I made a test to try and proof the issue persists.
I have tested one of my .js which is filled with the most common functions:
`.visit .get .contains .find . fixture . then . invoke .trigger . eq .and`

I simply ran the exact same .js file 5 times on my machine calling the same site. There should not be any noteble network or conectivity between the tests.
![image](https://user-images.githubusercontent.com/56070221/98650260-f32ebf80-2338-11eb-96e7-9e0e8853c885.png)

I was a bit surprised to fid that on average running this file was 50% slower on the newest version (5.6.0) than the 3.8.0 I have noted to be fast and stable.

I would love to run the newest version of cypress and get the newest features, but it is simply not worth waiting 50% long with the number of tests i run when working.

I understand this is not terribly specific in terms of what is slowing my tests, but I'm hoping performance becomes much more of a focus, so at least the tests do not run slower, because some new features are packing in the releases.

Also a small sidenote: I noticed a pattern across these 5 tests. It seems the very first test after running "cypress open" is always fairly slow. I understand how some processes have to get up and running, and some stuff may even be cached when rerunning the test a second time, but maybe some of the initial boot-up should not count in the benchmark.

Also it seemed the 3rd test was pretty slow compared to the test before and after it. To be clear, I simply started testing of the .js file and reran the same file, once it ended. So I would expected at least test 2-5 to be pretty similar in speed.

**Comment by yunj** [comment]
We feel the same since 5.5.0.

**Comment by jennifer-shehane** [comment]
We are working on improvements to the rendering of the reporter that we believe will help performance overall. The work was started in this PR. https://github.com/cypress-io/cypress/pull/8805

**Comment by tobmaster** [comment]
We experience the same issue. Updated from 4.8 to 5.6 and the tests had been about 2x slower. 
Also in another project they still stick to 3.x cause every upgrade reduces the execution times drastically. If I can provide any information to help identify the reason for it I would be glad to support.
Or do you know exactly what caused the change?

**Comment by IMightGitIt** [comment]
After the release of 6.0.0 I ran the same performance test. Just in case of changes on my machine since the last test, I reran my test on both 3.8.0. and 6.0.0.
The data is improving and test2-5 on both version are a lot more consistent, which is nice.
6.0.0. still seems slower than 3.8.0. according to my test, but at least we are down from 50% to 20% more time.
 
![image](https://user-images.githubusercontent.com/56070221/100109212-e5feee00-2e6b-11eb-98b0-7f3a99fbee86.png)
I might spend a bit of time with 6.0.0 to get a feel for how snappy it feels, but at least 6.0.0 does not seem faster than 3.8.0.
Also, as in my original comment, I'm really curious about the initial test, compared to later once. In all cases test1 takes sometimes 3-4 times as long as running them a second time.
It's of course nice when testing locally, and you already have stuff running, but it does make it a bit harder to get a feel for how long the test will take when running in CI.
