### ISSUE TITLE
failures in headed tests randomly invoke debugger

### ISSUE THREAD

**Issue by dwelle** [cypress-io/cypress#916]
- Operating System: win7
- Cypress Version: 3.0.2

### Is this a Feature or Bug?

bug

### Current behavior:

Sometimes, particularly when the cypress runner browser is open for longer periods time, a failure (be it command/assertion failure, or some unhandled exception such as TypeError) causes a debugger to be invoked (i.e. it pauses the script execution).

Restarting the cypress browser window solves the issue (until it pops up again hour or sooner later -- I haven't figured out the pattern yet).

### How to reproduce:

No idea.

I've registered a handler on `fail` event which does some things and then simply rethrows the error, but I believe the debugger thing happens even when the handler isn't registered, so I don't think it's related to this at all.

Just putting it here in case someone has an idea what's going on or encounters the same thing.

**EDIT:** to elaborate, the debugger is never being invoked until some point in time, and then from that point onward, it's being invoked 100% of the time (until I restart the browser window).

**Comment by brian-mann** [comment]
It's likely this setting in your dev tools

<img width="210" alt="screen shot 2017-11-15 at 9 46 28 am" src="https://user-images.githubusercontent.com/1268976/32841973-e3f43870-c9e9-11e7-8b73-15271016b2eb.png">

**Comment by dwelle** [comment]
@brian-mann nope, that's not it. That would not cause the behavior I'm getting -- it'd be consistent. So unless cypress (browser) is keeping that setting buried down somewhere in cache, and decides to use it as it pleases, I don't think that's what's happening.

**Comment by dwelle** [comment]
I'll close this for now. We'll see if some more people are getting this, or if it happens to be some quirk of my install.
