### ISSUE TITLE
route2 should allow filtering on request body

### ISSUE THREAD

**Issue by m4dc4p** [cypress-io/cypress#9163]
### What would you like?

The `route2` method offers fantastic flexibility for working with REST-based APIs. You can filter on URL paths, query parameters, etc. However, it does not offer any options for filtering on the request *body*. I would like to be able to supply a function that inspects the body of a request, and determines if it matches a route or not.

GraphQL queries are entirely contained in the body of the request. `route2` will filter based on the URL, but (AFAICT) does not allow any filtering on the content of the request.

Ideally, I'd like to be able to write a function that can inspect the request body and indicate to `route2` whether it matches or not. 

For an asynchronous page with multiple GraphQL queries, its impossible to use `route2` to reliably match requests. If a given page makes two different GraphQL queries in indeterminate order (easy to do if those queries depend on when scripts load or previous network requests), then I can't wait on aliased results reliably or call `route2` in such a way that I can always determine if a given request was made.

### Why is this needed?

Imagine a page makes two GraphQL queries, but the order isn't deterministic. Name those queries `op1` and `op2`. Imagine my test only cares about the results of `op2`. I can't write that test in such a way that it will pass reliably.

```html
<html>
<body>
<script language="javascript">
  var amt1 = Math.random() * 4000,
    amt2 = Math.random() * 4000

  document.write("<div>sending requests ...</div>")
  window.setTimeout(function() { 
      document.write("<div>op1</div>")
      fetch("/graphql", {
        method: "post",
        body: JSON.stringify({
          operationName: "op1"
        })
      })
    }, amt1
  )
  window.setTimeout(function() { 
      document.write("<div>op2</div>")
      fetch("/graphql", {
        method: "post",
        body: JSON.stringify({
          operationName: "op2"
        })
      })
    }, amt2
  )
</script>
</body>
</html>
```

Now I want to write a test that determines if `op2` is called when the page loads:

```ts
    cy.route2("POST", "/graphql", {
      statusCode: 200,
      body: 'it worked!'
    }).as("graphql")
    cy.visit('cypress/integration/index.html')
    cy.wait("@graphql", { timeout: 10000 }).then(({ request }) =>  {
      const { operationName } = JSON.parse(request.body)
      expect(operationName).to.equal("op2")
    })
```

But that test will always be flaky, because the order in with GraphQL queries are made is indeterminate. For a full example see https://github.com/jbaileyashe/route2-filtering-feature.

**Comment by Narretz** [comment]
Already discussed here: https://github.com/cypress-io/cypress/issues/8560

**Comment by m4dc4p** [comment]
Thank you! Didn't see that when I searched.

**Comment by Narretz** [comment]
No problem. I think you can close this issue then, and add your thoughts to the other one.
