### ISSUE TITLE
unable to open cypress version 5.6.0

### ISSUE THREAD

**Issue by keerthifission** [cypress-io/cypress#9177]
### Current behavior
Unable to download or open cypress runner
![image](https://user-images.githubusercontent.com/28805200/98917680-af7fb580-24f2-11eb-967d-f17b71eb619c.png)

### Desired behavior
Cypress should be installed and folder structure should be created.

### Test code to reproduce
steps which I followed:
npm install
npm start
npx cypress install --force

### Versions

I have successfully used version 5.4.0, but facing issues with version 5.6.0

**Comment by jennifer-shehane** [comment]
Do you have any anti-malware software on your computer? If so, I would recommend disabling it for this path on your computer. It may be reading the newly created folder and locking it. https://github.com/npm/npm/issues/13461#issuecomment-282556281

**Comment by keerthifission** [comment]
I am connected to VPN ,will that affect?
