### ISSUE TITLE
[Blocker bug] Details window closed and cannot be reopened again

### ISSUE THREAD

**Issue by sgohara** [cypress-io/cypress#9181]
I closed the window showing details of test like assertions, tasks, then cannot reopen it again. There's no option for that from Cypress window.
Could you, please, help me?

**Comment by jennifer-shehane** [comment]
Likely a duplicate of https://github.com/cypress-io/cypress/issues/2132

Solution here: https://github.com/cypress-io/cypress/issues/2132#issuecomment-404561427
