### ISSUE TITLE
iFrame Support Not Working in 5.6.0

### ISSUE THREAD

**Issue by joeosburn** [cypress-io/cypress#9186]
### Current behavior
Elements within an iframe are not accessible. I am using code from your documentation here:  https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/. 

### Desired behavior
For the element(s) to be selectable.

### Test code to reproduce

```js
Cypress.Commands.add('getIframeBody', () => {
  return cy
    .get('#foo')
    .its('0.contentDocument.body').should('not.be.empty')
    .then(cy.wrap)
});

<iframe id="foo" src="{paymentGateway}"></iframe>

cy.getIframeBody().get('[name="credit-card-number"]').type('4111111111111111');
```

I get the following error:
```
Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector.
```

### Versions

Cypress version 5.6.0

**Comment by jennifer-shehane** [comment]
`cy.get()` is a parent command and cannot be chained off of another command, so it will not be trying to find the credit card input inside of the iframe, instead it will be trying to find it off of the main parent window. You need to use `.find()` command off of the command getting the iframe. https://on.cypress.io/get#Requirements

As for this error: `Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector.`, I'm not able to recreate this error, so would need a reproducible example provided to track down this issue. Please provide an example with this error and we will reopen the issue.

### working example

`index.html`

```html
<html>
<body>
  <iframe id="foo" src="iframe.html"></iframe>
</body>
</html>
```

`iframe.html`

```html
<html>
<body>
  <input name="credit-card-number" type="number"/>
</body>
</html>
```

`spec.js`

```js
Cypress.Commands.add('getIframeBody', () => {
  return cy
    .get('#foo')
    .its('0.contentDocument.body').should('not.be.empty')
    .then(cy.wrap)
});

it('test', () => {
  cy.visit('index.html')
  cy.getIframeBody()
  // cannot use .get() here, must use .find()
  .find('[name="credit-card-number"]').type('4111111111111111');
})
```

<img width="794" alt="Screen Shot 2020-11-15 at 7 23 00 PM" src="https://user-images.githubusercontent.com/1271364/99185397-ff22e300-2777-11eb-802b-03af3033ea74.png">
