### ISSUE TITLE
Question:  Mocking external API with cy.server/cy.route

### ISSUE THREAD

**Issue by CollinEstes** [cypress-io/cypress#920]
The application we are testing with cypress makes API calls to a standalone API.  So locally we have our API running on port 3000, but the application we are testing is running on 8080.

We are looking to stub our (some but not all) API requests that our app makes to "http://localhost:3000/..." but seems like we are only able to stub requests to "http://localhost:8080"  which is where cy.visit() points.

Any way to do this currently?  Or is it possible to have cy.server() accept a host option or something along those lines?

**Comment by brian-mann** [comment]
I believe this already works.

We have tests around this behavior here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/commands/xhr_spec.coffee#L349-L378

Can you post your test code?

**Comment by CollinEstes** [comment]
```

cy.visit(url)

    cy.server()
    cy.route('http://localhost:3000/api/search/artifacts?artifactType=GCAR', [{artifactName: 'fizzbuzz', artifactType: "GCAR"}])

    cy.get('.search')
      .click()

```


That click on our search button here calls our app calls the API route we are mocking there on cy.route().  "url" here is "http://localhost:9999"

Here is a screenshot of what I see:

![screen shot 2017-11-16 at 9 29 44 am](https://user-images.githubusercontent.com/1966803/32899740-61b3e07c-cab1-11e7-9bb4-1ed7f317ce76.png)

After the click there I would expect to see the stub.


I don't see what I've seen in your demos which shows the stub:

![screen shot 2017-11-16 at 9 33 40 am](https://user-images.githubusercontent.com/1966803/32899762-6fae631e-cab1-11e7-9e38-74bdfc468e3a.png)

**Comment by jennifer-shehane** [comment]
Is the route you've defined expecting a `GET` method to the url? If not, you need to define the method in the route definition.

**Comment by CollinEstes** [comment]
@jennifer-shehane Yes that is a GET method, I also tried it with the full {options} syntax as well and had the same result.

**Comment by brian-mann** [comment]
I think the problem is that you are routing too late. 

I can look at the command log and see that the XHR's are happening before the  `cy.get('.search')`.

At that point the XHR has already gone out, and there was no routing for it. So it was not stubbed. Move your `cy.route` to before you visit and they will automatically be applied to all subsequent page loads.

**Comment by CollinEstes** [comment]
So changed to:
```
it('should search and select a gcar', () => {
    cy.server()
    cy.route('http://localhost:3000/api/search/artifacts?artifactType=GCAR', [{artifactName: 'fizzbuzz', artifactType: "GCAR"}])

    cy.visit(url)

    cy.clearExportControlWarning()

    cy.get('.search')
      .click()

  })
```


Still same behavior, not hitting stub.

![screen shot 2017-11-16 at 10 39 43 am](https://user-images.githubusercontent.com/1966803/32903464-ae9f085e-caba-11e7-83ae-49df298f4dac.png)

**Comment by CollinEstes** [comment]
Also should mention we are using fetch...

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by brian-mann** [comment]
Oh I was assuming you were trying to stub the XHR's that were in the command log.

Now that I realize you're using fetch that's why its not working. This is a documented unsupported feature but it's easy to work around either by nuking `window.fetch` or by using `cy.stub`.

Here's the documentation and example workarounds.

https://github.com/cypress-io/cypress/issues/95#issuecomment-281273126

and recipe

https://github.com/cypress-io/cypress-example-recipes/blob/master/cypress/integration/spy_stub_clock_spec.js

**Comment by brian-mann** [comment]
We've opened an issue to document this better: https://github.com/cypress-io/cypress-documentation/issues/238

**Comment by benpolinsky** [comment]
404 on the above recipe, FYI. Here's the link:

https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__window-fetch/cypress/integration/spy-stub-clock-spec.js

**Comment by arun290636** [comment]
Cypress is not capturing XHR calls . My application is running on post 3000.
![image](https://user-images.githubusercontent.com/1212793/38977473-5d814c28-43ac-11e8-8c02-14f5489bf2fd.png)
below request is not captured:
![image](https://user-images.githubusercontent.com/1212793/38977664-e8299c18-43ac-11e8-957b-edd33b130639.png)

**Comment by arun290636** [comment]
@jennifer-sheha can you please help on above?

**Comment by webberwang** [comment]
I am also getting this same issue, it looks like the issue has been closed, but there doesn't seem to be a solution.
