### ISSUE TITLE
cy.request(options) always send GET

### ISSUE THREAD

**Issue by tminhtuan** [cypress-io/cypress#9202]
### Current behavior

```js
const options ={
  method: 'DELETE',
  url: url,
  headers:{
  **authorization**: auth_token
  }
}
cy.request(options) --> Always send **GET** in spite of sending **DELETE**
```

if using `cy.request('DELETE',url)`  -->**DELETE** will be sent. But i need set **authorization** field in headers 

### Desired behavior

```js
cy.request(options) -->should send DELETE when method is DELETE
```

### Versions

![Image1](https://user-images.githubusercontent.com/62825697/99239167-40c19580-282d-11eb-9f06-d89cfb7bf700.png)
![Image2](https://user-images.githubusercontent.com/62825697/99239171-41f2c280-282d-11eb-9bd3-7fac5fee24b3.png)

**Comment by vrknetha** [comment]
Its 'method', not 'mothod'

**Comment by jennifer-shehane** [comment]
Please ensure the `method` key is spelled correctly. Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by tminhtuan** [comment]
Thanks @vrknetha, @jennifer-shehane for your clarification
