### ISSUE TITLE
cy.route2 throws an error saying No response received

### ISSUE THREAD

**Issue by adityagautam** [cypress-io/cypress#9213]
I am trying to intercept a script type network call. But, Cypress does not intercept it although I can see in logs that the script call was made successfully.

GET /assets/aadbd37bui2320e5b067a70d33255c 200 205.224 ms - -

Test code:
![Screen Shot 2020-11-16 at 12 49 00 PM](https://user-images.githubusercontent.com/4173001/99288909-448ff080-280a-11eb-97eb-5e4c791228a1.jpg)

![Screen Shot 2020-11-16 at 12 49 20 PM](https://user-images.githubusercontent.com/4173001/99288921-4954a480-280a-11eb-8f6d-d1846dff6271.jpg)

What am I doing wrong here? or is it that we cannot intercept script type network calls yet with Cypress.

**Comment by flotwig** [comment]
@adityagautam it seems that the response status code is a 201, which normally has no body. I believe this may be related to another issue, where responses with no body are not correctly awaited: #8999

**Comment by adityagautam** [comment]
Thank you for the response. Also, while I am trying to intercept JS script call. It's failing 

Although I can see in logs that the script call was made successfully.

GET /_sec/cp_challenge/sec-cpt-2-9.js 200 235.511 ms - -

Test code:
![Screen Shot 2020-11-16 at 1 15 40 PM](https://user-images.githubusercontent.com/4173001/99292074-bbc78380-280e-11eb-8a83-9f885815bddd.jpg)

![Screen Shot 2020-11-16 at 1 14 49 PM](https://user-images.githubusercontent.com/4173001/99292084-bf5b0a80-280e-11eb-982f-30cd2358c797.jpg)

What am I doing wrong here? or is it that we cannot intercept script type network calls yet with Cypress.

**Comment by adityagautam** [comment]
> @adityagautam it seems that the response status code is a 201, which normally has no body. I believe this may be related to another issue, where responses with no body are not correctly awaited: #8999

That is for POST call with same url path. I am trying to intercept on GET which gives status 200. The only difference between these two call apart from method is that GET call is a script call and POST call is a XHR

**Comment by adityagautam** [comment]
Ok, I found what the issue was. Basically, the JS script calls where getting served from memory cache and as soon as I turned on disable cache option in chrome and re ran the tests it passed.

Is there an option in cypress to disable cache in browser before running the tests ?

**Comment by vrknetha** [comment]
cy.reload(true) loads the page without using the cache.

**Comment by flotwig** [comment]
@adityagautam the fix for #8999 will also fix the issue with not being able to intercept 304 responses, there is not yet a way to disable cache everywhere in Cypress

Closing since the OP was resolved. Refer to #1124 for discussion on clearing cache before tests.
