### ISSUE TITLE
Origin header not included on fetch POST requests

### ISSUE THREAD

**Issue by calvinnwq** [cypress-io/cypress#9221]
Doing a POST after visiting a page does not have the `origin` header.

### Current behavior
```
connection: close
accept-language: en-US
accept-encoding: gzip, deflate, br
referer: https://www.google.com/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
accept: */*
content-type: text/plain;charset=UTF-8
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/3.6.1 Chrome/73.0.3683.121 Electron/5.0.10 Safari/537.36
content-length: 48
host: webhook.site
```

### Desired behavior
```
connection: close
accept-language: en-US
accept-encoding: gzip, deflate, br
referer: https://www.google.com/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
accept: */*
content-type: text/plain;charset=UTF-8
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/3.6.1 Chrome/73.0.3683.121 Electron/5.0.10 Safari/537.36
origin: https://www.google.com
content-length: 48
host: webhook.site
```

### Test code to reproduce
```js
describe("Test", function () {
  it("Does a POST", function () {
    cy.visit(`https://google.com/`, {
      onBeforeLoad: (win) => {
        fetch("https://webhook.site/e13d1eb8-fc86-452c-83f2-c6180bfd75f3", { method: "POST" });
      },
    });
    expect(true).to.equal(true);
  });
});
```

### Versions
Cypress v4.12.1
Chrome v84.*

**Comment by jennifer-shehane** [comment]
Where are you inspecting the headers? I see an origin header when inspecting the fetch in the Network tab using the provided example. 

<img width="861" alt="Screen Shot 2020-11-17 at 4 35 12 PM" src="https://user-images.githubusercontent.com/1271364/99376416-4d102600-28f3-11eb-8fe3-0b0d682e26f4.png">

**Comment by mnesti** [comment]
Hi 

I have the same behavior, 

For Reproduce I propose this site https://reqbin.com/req/zvtstmpb/post-request-example

![image](https://user-images.githubusercontent.com/23173008/99393093-1d562380-28dd-11eb-912d-10d96e29013d.png)

and this api

![image](https://user-images.githubusercontent.com/23173008/99393027-00b9eb80-28dd-11eb-9b62-4601b59a6910.png)

The script 
``` javascript
   cy.visit("https://reqbin.com/req/zvtstmpb/post-request-example")
    cy.get('#submit').click()

```

#### On cypress 4.8 I have this header 

![image](https://user-images.githubusercontent.com/23173008/99393342-7a51d980-28dd-11eb-9996-9e4939558c40.png)


 #### On cypress 5.5 I have this header without origin.

![image](https://user-images.githubusercontent.com/23173008/99393397-92c1f400-28dd-11eb-8aa9-c2864d49e6e6.png)


Could you help me?

**Comment by calvinnwq** [comment]
> Where are you inspecting the headers? I see an origin header when inspecting the fetch in the Network tab using the provided example.
> 
> <img alt="Screen Shot 2020-11-17 at 4 35 12 PM" width="861" src="https://user-images.githubusercontent.com/1271364/99376416-4d102600-28f3-11eb-8fe3-0b0d682e26f4.png">

I'm seeing the headers from the webhook site where I make the fetch request to. https://webhook.site/#!/e13d1eb8-fc86-452c-83f2-c6180bfd75f3/2aa40732-5355-4cd8-9fd2-3f3e2d0f70c5/1

**Comment by jennifer-shehane** [comment]
@mnesti I am not seeing this with your example either. I see an origin header in version 5.5.0. Are you sure there is no more code required to reproduce the issue? Can you provide a repo where this can be reproduced?

<img width="1130" alt="Screen Shot 2020-12-16 at 9 57 42 AM" src="https://user-images.githubusercontent.com/1271364/102301451-30641e00-3f85-11eb-80d4-d6d5be68c1fa.png">

**Comment by mnesti** [comment]
ping @jennifer-shehane 

Thanks for your reply.

For your information This behavior was fixed after switched "chromeWebSecurity": from false to true. 

on 4.8 it was no necessary to change this variable.
