### ISSUE TITLE
cypress can not find Chromium Browser in the CI to launch

### ISSUE THREAD

**Issue by Thanoonazad** [cypress-io/cypress#9225]
@jennifer-shehane 

### I`m trying launching my Browser in the ci using Chromium but it does not work:

It tell my that the Chromium does not be found.
available Browser: chrome, Electron and firefox

I did try to install Chromium with npm and run it using the path but it did not work too!

Is there any way to add Chromium in the cypress image same like -> available Browsers

package.json:
```json
"cypress:run": "cypress run --browser chromium"
```

run:
```
npm run cypress:run
```

cypress version: 5.6.0

cypress/plugins/index.ts:
![image](https://user-images.githubusercontent.com/45563133/99381639-a82e2280-28cb-11eb-8d07-bccd3e2dcccb.png)

(from chrome)it is also a problem when i use the 1920 X 1080 I do not get the same image resolution. when I use the 1920 X 1196 I get then the image resolution in CI what i wanted to be (1920 X 1080).

Thank you!

**Comment by jennifer-shehane** [comment]
Check over the `browser` keys to make sure `browser.name` is what you're really wanting to match on: https://on.cypress.io/browser-launch-api You may be wanting `browser.family === 'chromium'`

Why do you need to download Chromium? Are you trying to pass options to an existing Chrome download? If so, you can pass `browser.name === 'chrome'`

**Comment by Thanoonazad** [comment]
![image](https://user-images.githubusercontent.com/45563133/99510114-ef2d1e00-2986-11eb-97a1-7106224167a3.png)

**Comment by jennifer-shehane** [comment]
@Thanoonazad Why are you trying to run Chromium instead of just using Chrome?

**Comment by Thanoonazad** [comment]
@jennifer-shehane 

I want to use Chromium instead of Chrome because the full screen capture on Chromium is better then chrome!

for example: I`m writing a ui test and the full-HD image capture does not work good with chrome and it capture for me the scroll menu too, but Chromium does not do that for me

By the way I did install chromium and I tried to start it with (launchOptions.extensions) but it did not work for me!

Is there any way that cypress support any kind of Chromium version!

Thank you!

**Comment by jennifer-shehane** [comment]
@Thanoonazad Did you check our troubleshooting guide for launching browsers? Likely it's installed at a path we don't look for. https://on.cypress.io/troubleshooting#Launching-browsers

**Comment by Thanoonazad** [comment]
Yes, I did but the problem is for me is the CI! :(

**Comment by Thanoonazad** [comment]
@jennifer-shehane  Why does cypress not have the Chromium browser included?

**Comment by Thanoonazad** [comment]
@jennifer-shehane 

![image](https://user-images.githubusercontent.com/45563133/99521982-61a4fa80-2995-11eb-98b2-fd0e982dc889.png)

that is why it does not work for my in the CI!

It will be really great if cypress does support Chromium browser!

**Comment by jennifer-shehane** [comment]
@Thanoonazad Cypress does support Chromium browser when it is installed in the default path. We recently fixed some issues concerning browser launching, so this may be resolved for you. 

Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by jeromedoss** [comment]
Hi @jennifer-shehane can you guide me on this issue?

https://github.com/cypress-io/cypress/issues/28441

**Comment by the-homeless-god** [comment]
I think the main reason to do it is an attempt to setup for example disabled policies like that https://dev.to/richardbray/fix-samesite-cookie-issue-in-cypress-by-installing-an-older-version-of-chromium-43if or like that https://www.tomoliver.net/posts/cypress-samesite-problem regarding  `The web application that I am currently working on uses several 3rd party auth providers as part of its authentication flow. Manually testing the application I could see that everything was working. However, when running Cypress tests I was getting a strange warning mark on the header of the response from my auth provider. This header was asking my browser to set the session cookie but it was refusing to do so.`
