### ISSUE TITLE
Why not use lodash.set when creating a new command?

### ISSUE THREAD

**Issue by leobastiani** [cypress-io/cypress#9230]
What about prefer
```javascript
_.set(cy, name, fn);
```
over
https://github.com/cypress-io/cypress/blob/052892d79f95f9792e00d426722a9d904b572df4/packages/driver/src/cypress/cy.js#L1051

I think it would be awesome being able to have something like
```javascript
Cypress.Commands.add("modal.close", () => {...});
// ...
cy.modal.close();
```
How about you guys?

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding this feature is not currently within our scope of feature work. This change would cause some unintended consequences in its execution. You could probably execute an API similar to this, doing something like `cy.modal = cy` during the time you want to call these commands.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by leobastiani** [comment]
Thank you very much.

To achieve this, I patched somewhere after adding all commands:
```javascript
const keysWithDot = Object.keys(cy).filter((key) => key.match(/[\.\[]/));
for (const key of keysWithDot) {
  const fn = cy[key];
  delete cy[key];
  _.set(cy, key, fn);
}
```
