### ISSUE TITLE
Content-encoding header can not be overridden for JSON responses mocked by `intercept`

### ISSUE THREAD

**Issue by shanear** [cypress-io/cypress#9232]
### Current behavior

When `route2` returns a JSON response, it appears to ignore any attempt to override the `content-encoding` header, like in the example below:
```js
cy.route2('POST', '/records/search', {
  body: { hits: 0 },
  headers: {
    'content-encoding': 'identity',
  }
});
```

This is the request when inspected inside of the cypress runner:
<img width="430" alt="Screen Shot 2020-11-17 at 2 59 38 PM" src="https://user-images.githubusercontent.com/1596259/99460923-a1140e00-28e5-11eb-8f89-38d67e88efae.png">

For some reason this only seems to affect JSON requests. If I change the command to return a string, then the `content-encoding` override is successful:
```js
cy.route2('POST', '/records/search', {
  body: "CONTENT",
  headers: {
    'content-encoding': 'identity',
  }
});
```

This is the request when inspected inside of the cypress runner:
<img width="437" alt="Screen Shot 2020-11-17 at 3 00 16 PM" src="https://user-images.githubusercontent.com/1596259/99460967-b5580b00-28e5-11eb-8713-091a6a1f831f.png">

### Desired behavior

The `content-encoding` header should be overridable via the `headers` option in `route2`

### Test code to reproduce

```js
cy.route2('POST', '/records/search', {
  body: { hits: 0 },
  headers: {
    'content-encoding': 'identity',
  }
});
```

### Versions
5.6.0

**Comment by jennifer-shehane** [comment]
I can reproduce the described behavior with the following code. 

### Reproducible example.

```js
it('test cy.route2()', () => {
  cy.route2('POST', '/records/search', {
    body: { hits: 0 },
    headers: {
      'content-encoding': 'identity',
    }
  })
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('POST', '/records/search')
    xhr.send()
  })
})
```

**Comment by flotwig** [comment]
Still happens in 7.0.1.
