### ISSUE TITLE
Invalid index.js file issue in plugin file

### ISSUE THREAD

**Issue by ShankarArunodhayam** [cypress-io/cypress#9234]
Hi, 

I am trying to run my tests in cypress and im getting the error 

![image](https://user-images.githubusercontent.com/68418346/99497741-586b5c00-299c-11eb-8fbb-4e220f9fc9f1.jpg)

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

Specifically, in your case - provide the contents of the `cypress/plugins/index.js` file.

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.

**Comment by henrik242** [comment]
@jennifer-shehane We have the same problem.  It happens with 5.4.9, but not 5.4.8.  Here's our plugins/index.js:

```
/* eslint-disable */
const webpack = require('@cypress/webpack-preprocessor');
const browserify = require('@cypress/browserify-preprocessor');
const { addMatchImageSnapshotPlugin } = require('cypress-image-snapshot/plugin');

module.exports = on => {
    addMatchImageSnapshotPlugin(on);
    
    const options = {
        webpackOptions: {
            resolve: {
                extensions: ['.ts'],
            },
            module: {
                rules: [
                    {
                        test: /\.ts$/,
                        exclude: [/node_modules/],
                        use: [
                            {
                                loader: 'ts-loader',
                            },
                        ],
                    },
                ],
            },
        },
    };

    on('file:preprocessor', file => {
        if (file.filePath.endsWith('.ts')) {
            return webpack(options)(file);
        } else {
            // Hard to get cypress-axe (in ppA11y.js) to run with webpack so run it through default preprocessor
            return browserify()(file);
        }
    });
};
```

**Comment by henrik242** [comment]
But it seems to have been fixed in https://github.com/cypress-io/cypress/issues/9037#issuecomment-719707355.  We'll check it out.
