### ISSUE TITLE
UX Improvement for Confusingly Highlighted Commands

### ISSUE THREAD

**Issue by CypressJosh** [cypress-io/cypress#9237]
### What would you like?
The Command Log will highlight commands red when an assertion fails for legitimate reasons. This can sometimes be confusing in the case where a DOM element is found with `cy.get()`, but is still highlighted red. For example, below:

![Screen Shot 2020-11-18 at 11 19 28 AM](https://user-images.githubusercontent.com/62314672/99558666-f73e8b00-2991-11eb-856c-7420b42db496.png)

Reproducible example:

`index.html`

```html
<a href data-test-id="empty-href">This anchor has an empty href</a>
```

`spec.js`

```js
it('shows the dom element in red confusingly', () => {
  cy.visit('index.html')
  cy.get('[data-test-id="empty-href"]')
    .should('have.prop', 'href')
    .and('equal', '/')
})
```

### Why is this needed?
The test above should fail because the anchor element has an empty href attribute. However, as seen in the screenshot above the `get` command for the DOM selector `[data-test-id="empty-href"]` is red, which is simply a confusing indication as the DOM element was actually found. We should think about potentially styling it differently to better indicate the issue. (*Note: the error dialog correctly points to the failed assertion. The issue here is more around UX improvements to be more clear.)

@chrisbreiding @CypressAdam

**Comment by jennifer-shehane** [comment]
This is likely more of a programmatic fix than a UI fix. I think we automatically mark the parent command as failed if any of the child commands are a `.should()` or `.and()` and fail. The Command Log has always shown this way - checked that this is not a regression in behavior.
