### ISSUE TITLE
Do I have to do cy.visit before each test within a spec file?

### ISSUE THREAD

**Issue by kunsinha79** [cypress-io/cypress#9246]
In my application, we have two different api endpoints for auth and application APIs respectively. 
I have set the base URL to deployed application url.

When I visit the root of the application, the call to auth passes thru even the first call to application api also passes.
In the next test case, within the same spec, these is another post call to application API endpoint. This call fails.

If I club the second case with the first (where cy.visit()) is mentioned then the API gets its context and passes.

(cy.request() is not used. The cases rely on the underlying application calls that happen during button clicks)

 ```js
 it('should initiate the journey ', () => {
    cy.login('dfgkfdkgk');  // **the post call to oauth also passes (https://some-site/token)**
    cy.wait(2000);

    cy.visit('/journey');  //**The api call happening from here passes (get call - https://some-site/context/question)**
    cy.url().should('include', 'info');

    cy.get('some-element)
      .find('#flow-step > first')
      .shadow()
      .find('.radio-group')
      .selectNth(3)
      .parent()
      .parent()
      .find('div > .action')
      .click();
  });

  it('should now go to the next step', () => {
    cy.url().should('include', 'info2');

    cy.get('some-element')
      .find('#flow-step > isecond')
      .shadow()
      .find('.radio-group')
      .selectNth(1)
      .parent()
      .parent()
      .find('div > .action')
      .click(); // **the post call to save happens here and it  fails (https://some-site/answer iso https://some-site/context/answer)**
  });
```

Now, if I combine the two cases, then the failing post call also pass.

 ```js
it('should initiate the journey ', () => {
    cy.login('dfgkfdkgk');  // **the post call to oauth also passes**
    cy.wait(2000);

    cy.visit('/journey');  //**The api call happening from here passes (get call)**
    cy.url().should('include', 'info');

    cy.get('some-element)
      .find('#flow-step > first')
      .shadow()
      .find('.radio-group')
      .selectNth(3)
      .parent()
      .parent()
      .find('div > .action')
      .click();
 
    cy.url().should('include', 'info2');

    cy.get('some-element')
      .find('#flow-step > isecond')
      .shadow()
      .find('.radio-group')
      .selectNth(1)
      .parent()
      .parent()
      .find('div > .action')
      .click(); // **the post call to save happens here and it  passes (hits appropriate endpoint https://some-site/context/answer)**
  });

```
Cypress 4.12.0

Question:
Is it related to cy.visit? Do I have to write cy.visit() in all the cases or in before each?

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which issues are reserved for.
