### ISSUE TITLE
Click is not working for the Div with role="button" after version 5.3 of cypress

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#9247]
Code to execute the click event of the div
```js
cy.get("[data-id='uniqueId']").click()
```
Out Div element structure
```js
<div role="button" data-id="uniqueId">
     <div>
              <span>
                          Button Text
              </span>
     </div>
</div>
```

### Current behavior
The script of clicking the div as mentioned above is executed without any error but the event bind to it is not triggered

### Desired behavior
Click should happen and the event bind to that div should get executed. 
The event is to call the react method when the div is clicked

i.e When, we click on the div as describe above - the react event to execute the Method should be triggerred. 

### Test code to reproduce
```js
cy.get("[data-id='uniqueId']").click()
```
```js
<div role="button" data-id="uniqueId">
     <div>
              <span>
                          Button Text
              </span>
     </div>
</div>
```
### Versions

Cypress v 5.4,5.5 and 5.6

**Comment by jennifer-shehane** [comment]
Can you include the event listeners you have setup on the button on click? We won’t be anle to recreate the issue without that - as it’s likely very dependent on how the event listeners are setup and hit. We already have tests around clicking in general which works. Thanks!

**Comment by Prashant-Kan** [comment]
Hi @jennifer-shehane 

We are binding the click in react application (onPress, onPressIn, onMouseEnter, onMouseLeave are teh event bind to the button 

Click event of the div and span tag which is used as a button.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
