### ISSUE TITLE
Issue with client certificates in version 5.6.0

### ISSUE THREAD

**Issue by klmlfl** [cypress-io/cypress#9249]
I'm having an issue loading the secure version of any website using Cypress 5.6.0. 
For example, attempting to navigate to https://www.amazon.com returns the non-https version.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
