### ISSUE TITLE
App not loading after sign in by Amplify Authentication. 

### ISSUE THREAD

**Issue by lmend22** [cypress-io/cypress#9251]
When I sign on after  Amplify Authentication the screen goes black and Cypress fails because of timeout.  
<img width="1275" alt="Screenshot 2020-11-19 133433" src="https://user-images.githubusercontent.com/69525449/99721444-7902e700-2a6c-11eb-969e-5a9846ce7fb8.png">

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
