### ISSUE TITLE
Cypress recordings of failed tests fail to process

### ISSUE THREAD

**Issue by astraljames** [cypress-io/cypress#9253]
I'm investigating test flakiness, so I've been running our suite on repeat for most of the day.

I've been taking the video recordings and making a catalog of flaky test failures. After a few dozen runs, my recordings of failures started being an appropriate length video of black screen, even though the tests have been proceeding properly. It's worked fine all day, and no changes were made to code or on my Mac, I've just been recording failures and categorizing.

_Edit - The failure is happening when the video starts processing. The compression step takes 0 seconds, when previously it'd take 30-45 seconds_

Steps I've taken so far: 
- Close terminal, vscode, and reboot Mac
- Getting debug logs as per https://docs.cypress.io/guides/guides/screenshots-and-videos.html#Video-encoding

In debug logs, I've found the following info:

```
cypress:server:video compression stderr log { message: '[ffmetadata @ 0x7ffe11800000] Expected chapter end timestamp, found END=null.' } +5ms

```
After this all other processes for the compresson takes +0 ms, which I think means they are being skipped
```
cypress:server:video compression stderr log { message: '[mp4 @ 0x7ffe12804000] Application provided duration: -264 / timestamp: 13737 is out of range for mov/mp4 format' } +0ms
cypress:server:video compression stderr log { message: '[mp4 @ 0x7ffe12804000] pts has no value' } +0ms

```
As a last ditch effort, I've tried `rm -rf node_modules && yarn`

**Comment by astraljames** [comment]
To update:
It appears to be a chrome update that's caused the issue. I'm going to be trying to downgrade to the previous version of Chrome, before the 11/18 release. Specifically version `86.0.4240.75`.

I'm running on a Macbook Pro using Mojave 10.14.6

**Comment by kaiyoma** [comment]
We're seeing the same thing. Chrome 87 on any OS (Windows, macOS, Linux) is causing Cypress videos to no longer be rendered correctly. This is a pretty major issue! Videos are one of the few reasons we use Cypress to begin with.
