### ISSUE TITLE
ESOCKETTIMEDOUT error only in Codebuild

### ISSUE THREAD

**Issue by bildungsroman** [cypress-io/cypress#9257]
I'm experiencing the `ESOCKETTIMEDOUT` error, but only when running Cypress in a CodeBuild job.

I was initially experiencing the error locally, but after I found #943 I added 
```
      headers: {
        "Accept-Encoding": "gzip, deflate"
      }
```
to my `cy.visit` command and that worked great locally.

### Current behavior
I'm running my tests in CodeBuild, and getting the `ESOCKETTIMEDOUT` error every single time.

### Desired behavior
My tests run in CodeBuild the same as they do locally.

### Test code to reproduce
This is the only spec in my integration directory:
```js
describe('Costco Xbox scraper', () => {
  it('Checks to see if Xboxes are out of stock at Costco', () => {
    cy.visit('https://www.costco.com/xbox-series-x-1tb-console-with-additional-controller.product.100691493.html', {
      headers: {
        "Accept-Encoding": "gzip, deflate"
      }
    });
    cy.get('.oos-overlay')
  });
});
```

### Versions

5.6.0

**Comment by jennifer-shehane** [comment]
When you run in CodeBuild, do you run the tests with the `--browser` flag pointing to Chrome? If not, the tests could be running in Electron in CI and Chrome locally. That may be the difference. 

I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

**Comment by bildungsroman** [comment]
I initially used `--browser chrome` but that was failing, so I tried electron, which is still failing.

**Comment by bildungsroman** [comment]
I wanted to give an update: locally, all browsers work when running normally, it's the `--headless` mode that fails locally for chrome and firefox, and succeeds for electron. 

However, headless electron is still failing in CodeBuild. I've tried using both Amazon Linux and Ubuntu as the environment, and both are failing.

**Comment by bildungsroman** [comment]
Any help on this would really be appreciated. This is completely blocking my project at the moment.

**Comment by sabrina-s** [comment]
@bildungsroman Hello! Did you manage to figure this one out? 🙏 

I'm facing the same `ESOCKETTIMEDOUT` error on my **CircleCI**. Everything works fine when I run it locally, even on headless Electron. I also tried that `"Accept-Encoding": "gzip, deflate"` trick, but it didn't seem to make a difference.

**Comment by bildungsroman** [comment]
@sabrina-s Unfortunately, no. I'm running into multiple failures in Codebuild that don't happen at all locally in several repos and it's been a pretty frustrating process.

**Comment by fseee** [comment]
Did anyone get rid of this issue? I'm getting same in Jenkins pipeline
