### ISSUE TITLE
cy.contains() does not locate text outside of the body element

### ISSUE THREAD

**Issue by meerkat-citronella** [cypress-io/cypress#9268]
### Current behavior

The function cy.contains() will not locate text outside of the `<body>` element. I thought this was a feature, and not a bug, until I tried cy.get() and it's able to grab DOM elements from outside of `<body>` just fine. I recognize this is an extreme edge case, as putting page content outside of `<body>` is bad practice. 

<img width="1060" alt="Screen Shot 2020-11-20 at 9 35 18 PM" src="https://user-images.githubusercontent.com/57840235/99865522-5eb62f80-2b78-11eb-921b-12688f1a9718.png">

I created this quick demo repo to show the behavior: https://github.com/meerkat-citronella/cypress-body-test. When you run the test, you can see that cy.get() is able to locate the out-of-body element, while cy.contains() cannot. 

### Desired behavior

I would like cy.contains() to have access to the same scope as cy.get().

### Test code to reproduce

Repo: https://github.com/meerkat-citronella/cypress-body-test . Clone and run. 

Here is some relevant code showing how I am rendering an element outside of the document's `<body>` tag: 
index.js: 
```js
// render inside of the <body> element
ReactDOM.render(
  <React.StrictMode>
    <InBody />
  </React.StrictMode>,
  document.getElementById("root")
);

// render outside of the <body> element
const insertionPoint = document.createElement("div");
insertionPoint.id = "insertion-point";
document.body.parentNode.insertBefore(insertionPoint, document.body);
ReactDOM.render(
  <React.StrictMode>
    <OutBody />
  </React.StrictMode>, // <---- cy.contains() won't be able to locate the text in <OutBody />
  insertionPoint
);
```

### Versions

My package.json:
```json
{
  "name": "cypress-body-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "cypress": "^5.6.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.0",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
Chrome version: 86.0.4240.198
OS: macOS Catalina 10.15.7

**Comment by Narretz** [comment]
Why do you have content outside the body? It will work in most browsers, but is not valid HTML. Or what stops you from rendering the component inside the body? I don't think Cypress should support this use case, personally.

**Comment by meerkat-citronella** [comment]
We are building a Chrome extension, and don't want to fight the existing styles on the page so we render outside of the body tag. We found this approach very useful for bypassing 'z-index wars' between our extension and the existing styling on the page.

**Comment by jennifer-shehane** [comment]
This is intentional. Previously (before [0.6.8](https://on.cypress.io/changelog#0-6-8)) we would search the entire document, but then `cy.contains()` would return matches from arbitrary things in the <head> like `title`, which is really unexpected. 

You can get the entire document and assert whatever you want off of its contents using JavaScript. 

```js
describe("cy.contain() Does Not Work Outside of Body Tag", () => {
  it("does not work", () => {
    cy.visit("localhost:3000"); // first spin up the app on port 3000

    // inside of body
    cy.get("#inbody");
    cy.contains("hello from inside of the body tag");

    cy.document().then((doc) => {
      expect(doc.getElementById('outbody')).to.have.text('hello from outside of the body tag')
    })
  })
})
```

<img width="509" alt="Screen Shot 2020-12-08 at 7 20 51 PM" src="https://user-images.githubusercontent.com/1271364/101486083-8257e300-398a-11eb-99be-791a2e6cb19e.png">

**Comment by meerkat-citronella** [comment]
Thanks Jennifer! Very helpful :)
