### ISSUE TITLE
On making changes to spec file / adding commands the changes are not being picked up by test runner

### ISSUE THREAD

**Issue by RajuJosephK** [cypress-io/cypress#9269]
On making changes to spec file / adding commands the changes are not being picked up by test runner.

I am writing test for this website  'https://snipcart-react-gatsby.netlify.app/' . The issue is specific to this website.  

After making changes to the spec file the changes are not being picked up.  I have to rename the file for the changes to be picked up by test runner.

I have to import the commands into the spec file to use them.

When testing with other websites, the changes are automatically picked up by test runner.

Link to the project files github https://github.com/RajuJosephK/dhtest

**Comment by jennifer-shehane** [comment]
Is the application under test reliant on Service Workers? If so, there is a known issue with watching file changes and a workaround here: https://github.com/cypress-io/cypress/issues/702

**Comment by RajuJosephK** [comment]
Thanks, the workaround did the magic.

**Comment by RajuJosephK** [comment]
The workaround fixed the issue
