### ISSUE TITLE
Overriding type

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#927]
- Operating System: MacOS Sierra 10.12.6
- Cypress Version: 1.0.3
- Browser Version: Chrome 62

### Is this a Feature or Bug?
Bug

### Current behavior:
It throws an error whenever I'm doing

### Desired behavior:
Allow me to set a custom delay when typing. Preferably at a cypress.json configuration level.

### How to reproduce:
```js
Cypress.Commands.overwrite("type", (originalFn, string) => originalFn(string, { delay: 1 }))
cy.get('foo').type('bar')
```

#### Test code:
```js
cy.get('foo').type('bar')
```

### Additional Info (images, stack traces, etc)
<img width="320" alt="screen shot 2017-11-17 at 18 51 49" src="https://user-images.githubusercontent.com/8288389/32963715-c7d1bc68-cbc8-11e7-919c-38d63c0eb0f7.png">

**Comment by brian-mann** [comment]
This isn't a bug. You've overriding a child command which yields you the current subject as the 2nd argument. The `type` must know what element it's typing into. You basically provided it a `string` as the element, and an object as to what to type.

`Cypress.Commands.overwrite("type", (originalFn, subject, string, options) => ...`

**Comment by paulpruteanu** [comment]
```js
Cypress.Commands.overwrite(
    "type",
    (originalFn, subject, string, options) => originalFn(
        string,
        Object.assign({}, options, {delay: 1})
    )
)

cy.get('input[name="mainPhoneNo"]').type('07070707070')
```
now throws
<img width="323" alt="screen shot 2017-11-17 at 19 04 33" src="https://user-images.githubusercontent.com/8288389/32964166-32c82970-cbca-11e7-9417-8e231e1821a7.png">

**Comment by brian-mann** [comment]
Because you're not actually passing `subject` to type. Type must be called with the subject as its first argument.

**Comment by paulpruteanu** [comment]
Thank you! This works:
```js
Cypress.Commands.overwrite(
    "type",
    (originalFn, subject, string, options) => originalFn(
        subject,
        string,
        Object.assign({}, options, { delay: 1 )
    )
)
```
