### ISSUE TITLE
cypress even I  simulate  wap ua page elements still cannot be clicked

### ISSUE THREAD

**Issue by wwxiu** [cypress-io/cypress#9274]
cypress even I  simulate  wap ua page elements still cannot be clicked

url : https://zhinan.sogou.com/?ch=ww.dh.zn 

ua:     "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B202 Safari/604.1"

no response to homepage element click, what should I do?

**Comment by wwxiu** [comment]
cy.visilt('https://zhinan.sogou.com/?ch=ww.dh.zn')
cy.get('li:nth-child(1) > a').click()

**Comment by wwxiu** [comment]
cy.visit('https://zhinan.sogou.com/?ch=ww.dh.zn')
cy.get('li:nth-child(1) > a').click()

**Comment by sainthkh** [comment]
It's a bit hard for me to understand the purpose of your tests because the provided code is too short. But I got `multiple elements to click` failure message and it can be solved with `first()` like below:

```js
it('t', () => {
  cy.visit('https://zhinan.sogou.com/?ch=ww.dh.zn')
  cy.get('li:nth-child(1) > a').first().click()
})
```

If the problem is still happening, please open a new issue with a reproducible example.
