### ISSUE TITLE
Unable to install cypress in ubuntu

### ISSUE THREAD

**Issue by nitsaw09** [cypress-io/cypress#9277]
![image](https://user-images.githubusercontent.com/18691537/99944817-89330300-2d99-11eb-9f32-460000da6856.png)

**Comment by bahmutov** [comment]
I suspect there is some kind of disk hiccup during the install. We go through a lot of test runs on Ubuntu and have no errors are reported.

**Comment by nitsaw09** [comment]
Already fixed
