### ISSUE TITLE
error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RobFl4** [cypress-io/cypress#9278]

**Comment by bahmutov** [comment]
If you search our documentation for "libdbm" you will see that this library is required for Cypress v5 to work (it is required by Electron)

<img width="458" alt="Screen Shot 2020-11-23 at 8 04 48 AM" src="https://user-images.githubusercontent.com/2212006/99965292-a9939b00-2d62-11eb-80a9-8d8cda4a7936.png">
