### ISSUE TITLE
cy.type() adhere to maxlength on text input

### ISSUE THREAD

**Issue by JosiahRooney** [cypress-io/cypress#928]
### Is this a Feature or Bug?
Feature

### Current behavior:
cy.type ignores maxlength attribute on an input element.

### Desired behavior:
cy.type() should not ignore maxlength attribute on an input. After .type() reaches the maxlength, it should ignore the rest of the input string.

### How to reproduce:
Use cy.type() on a text input with a maxlength attribute, passing a string to .type() that is longer than the maxlength.

**Comment by jennifer-shehane** [comment]
Can confirm - is a bug in v1.0.3. On typing over maxlength, the input displays more than maxlength and the assertions fail, returning the value beyond the allowed maxlength. 

**HTML**
```html
<input type="text" class="wait-input1" maxlength="5">
```

**Test code**
```js
it('Type over maxlength', function(){
  cy.visit('http://localhost:8080/commands/waiting')
  cy.get('.wait-input1').type('123456789')
    .should('have.value', '12345')
    .and('not.have.value', '123456789')
```

**Result in Cypress**
<img width="1275" alt="screen shot 2017-11-18 at 9 57 25 am" src="https://user-images.githubusercontent.com/1271364/32981697-f4f4894a-cc46-11e7-93f0-fe4d08738cb4.png">

**For solution, PRs welcome**
- w3spec for `maxlength`: https://www.w3.org/TR/html5/forms.html#the-maxlength-and-minlength-attributes
- https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/type.coffee#L23

**Comment by JosiahRooney** [comment]
I'd love to submit a PR here. This is the first time I have contributed to a project on github (outside of my own). I will carefully read the contributing.md doc and get started. Please let me know if there's anything outside of that doc that I should know. Thanks!

**Comment by jennifer-shehane** [comment]
Awesome @josiahrooney, feel free to open a WIP PR if you get stuck or have questions at all. 👍

**Comment by JosiahRooney** [comment]
I'm wondering if this would suffice (adding to line 115 of packages/driver/src/cy/commands/actions/type.coffee):

```javascript
if options.$el.attr("maxlength") and chars.length > options.$el.attr("maxlength")
        chars = chars.slice(0, options.$el.attr("maxlength"))
```

**Comment by JosiahRooney** [comment]
I made a WIP PR here: https://github.com/cypress-io/cypress/pull/930

**Comment by JosiahRooney** [comment]
@jennifer-shehane I think this is all finished up. Do I close the issue now or do you guys do that? Thanks

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/930

**Comment by brian-mann** [comment]
Released in [`1.1.1`](https://docs.cypress.io/guides/references/changelog.html#1-1-1).

**Comment by RobertRiviera** [comment]
I'm very new to all this, but I just wanted to ask if someone could verify whether the fix that was included in 1.1.1 considers special character sequences like {selectall} and {backspace} when respecting the maxlength attribute.

**Comment by brian-mann** [comment]
That's a good point. It likely does not. A quick test would confirm this.

**Comment by RobertRiviera** [comment]
I upgraded to 1.1.1 yesterday but had to roll back to 1.1.0 because several of my tests that used textboxes with a maxlength attribute started failing.  The cy.clear() command was also affected for obvious reasons.
