### ISSUE TITLE
I am trying to click on 'Click Photo' button then getting Timed out retrying: cy.click() failed because this element is not visible:

### ISSUE THREAD

**Issue by pardeeprj90** [cypress-io/cypress#9282]
![image](https://user-images.githubusercontent.com/37590015/99988334-85be6c80-2dd7-11eb-8da5-601b8c0ba1f7.png)

I have to use camera functionality in this scenario, but now able to do so. Kindly help me out.

**Comment by bahunov** [comment]
read the error message:
`or use {force: true}`

add: .click(force: true)

**Comment by pardeeprj90** [comment]
> read the error message:
> `or use {force: true}`
> 
> add:
> `.click({force: true})`

I tried this option but it get failed in FInal Validations.

**Comment by sainthkh** [comment]
Can you provide a reproducible example, please? As we all know, debugging cannot be started without it.

**Comment by sainthkh** [comment]
Closing the issue because of inactivity. If the problem is still happening, please open a new issue with a reproducible example.
