### ISSUE TITLE
Cypress is crazy

### ISSUE THREAD

**Issue by IgorDePaula** [cypress-io/cypress#9296]
None form the cypress access my route, but it exists.

cypress: 5.6.0
node: 12.19.0

Sorry but I search in all google and not found anything.

![Captura de tela de 2020-11-23 20-21-07](https://user-images.githubusercontent.com/2833993/100026879-59e8ba00-2dca-11eb-867a-6ed32715539c.png)

![Captura de tela de 2020-11-23 20-21-17](https://user-images.githubusercontent.com/2833993/100026877-59e8ba00-2dca-11eb-97c2-9388a44a047d.png)

![Captura de tela de 2020-11-23 20-23-45](https://user-images.githubusercontent.com/2833993/100026874-58b78d00-2dca-11eb-95ce-48cbbeec0b85.png)

**Comment by jennifer-shehane** [comment]
The error shown is coming from your application code, not Cypress. Open your DevTools to see the error in your console. 

You can ignore this error, and not fail the test when this error occurs by following these instructions: https://on.cypress.io/catalog-of-events#To-turn-off-all-uncaught-exception-handling

**Comment by IgorDePaula** [comment]
The cypress said the error is from my application, but how you see, the route exists and was accessed in my app.

**Comment by IgorDePaula** [comment]
Ignore errors is better solution?

**Comment by jennifer-shehane** [comment]
If you open DevTools, the error should be printed to your console with the stack trace. Ignoring errors is an option.
