### ISSUE TITLE
In chrome webpage resources are failed to load while executing in cypress 

### ISSUE THREAD

**Issue by Vivek-Jai** [cypress-io/cypress#9297]
Chrome: 86
Windows:10
Cypress version: 5.6.0

While load the webpage in chrome browser using cypress the webpage resources are failed to load. Causing cypress to throw error states that unable to find the element.

But it works fine in Firefox browser

Refer screenshot: 

![remote](https://user-images.githubusercontent.com/1271364/100073702-3aa26900-2e6c-11eb-89f6-1722c00f66b8.png)

![local system](https://user-images.githubusercontent.com/1271364/100073765-4e4dcf80-2e6c-11eb-817e-0cfef258dfd6.png)

Application url:  http://182.76.145.115:50505/tzTestCVSafety/

**Comment by sainthkh** [comment]
Sorry for the late reply.

I checked with Cypress 6.4.0 + Chrome 88 + Ubuntu 20.04, but it works. 

Is the problem still happening?

**Comment by Vivek-Jai** [comment]
No it was our internal server issue. Now it's working fine. Thanks for the
response
