### ISSUE TITLE
Cypress 6.0.0 can't verify locator that is not exist

### ISSUE THREAD

**Issue by tminhtuan** [cypress-io/cypress#9299]
I've just updated Cypress to 6.0.0 and faced an issue - Cypress can't verify a locator that is not exist or visible. Because Cypress 6.0.0 will find the locator first (the locator is exist or visible) and can't find out the locator. And command is failed

### Current behavior

User wants to verify a locator is not exist/visible. But Cypress 6.0.0 must try to find out that locator first then check not exist/visible later. The command is always failed because Cypress can't find out that locator 

### Versions
Cypress: 6.0.0
Chrome: 87

**Comment by jennifer-shehane** [comment]
@tminhtuan Please read through our migration guide when upgrading to 6.0.0. https://on.cypress.io/migration-guide#Migrating-to-Cypress-6-0

It sounds like you're seeing the first breaking change we describe in detail here: https://on.cypress.io/migration-guide#Non-existent-element-assertions

You will need to be more specific in your tests about whether you want to assert that an element does not exist or is not visible (in the DOM but hidden). You likely want to update your code like below:

```js
// cy.get('selector').should('not.be.visible') // This will fail, the el is not in the DOM
cy.get('selector').should('not.exist') // This will pass ✅
```

**Comment by tminhtuan** [comment]
@jennifer-shehane  you're right. It works well with "not.exist". Thanks so much for your support

**Comment by abidshah-TP** [comment]
@jennifer-shehane in my case .should('not.exist') not working i have cypress 6.0.1

**Comment by jennifer-shehane** [comment]
@abidshah-TP It depends on the exact example what you're want to replace the assertion with - I can't say without seeing your test case. If you think you're experiencing a bug in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run.

**Comment by abidshah-TP** [comment]
@jennifer-shehane "cy.get(':nth-child(3) > :nth-child(2) > .locker-footer__links > :nth-child(2) > a').should('not.exist')"
this is the main line where I am getting the error

**Comment by jennifer-shehane** [comment]
Please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
