### ISSUE TITLE
[Cypress 6.0.0] cy.screenshot marked as deprecated

### ISSUE THREAD

**Issue by benjick** [cypress-io/cypress#9303]
### Current behavior
When using `cy.screenshot` my editor warns me that it's deprecated and refers to `cy.intercept`. I tried looking at the release blog post and the docs for these two function but it doesn't seem this should be deprecated.

![](https://user-images.githubusercontent.com/430872/100082754-eb970c80-2e48-11eb-9789-0a0a8a36375c.png)

Diving into the type definitions it looks like this:

    /**
     * @deprecated Use `cy.intercept()` instead.
     *
     * Take a screenshot of the application under test and the Cypress Command Log.
     *
     * @see https://on.cypress.io/screenshot
     * @example
     *    cy.screenshot()
     *    cy.get(".post").screenshot()
     */
    screenshot(options?: Partial<Loggable & Timeoutable & ScreenshotOptions>): Chainable<null>### Desired behavior
To not have this flagged as deprecated or instructions in the docs on how to use intercept for screenshots.

### Test code to reproduce
```js
/// <reference types="Cypress" />

context('e2e', () => {
  it('can render', () => {
    cy.visit('/');
    cy.screenshot();
  });
});
```

### Versions
6.0.0

**Comment by jennifer-shehane** [comment]
Yah, this warning is supposed to be on cy.route, but likely got associated with the wrong command’s types.

**Comment by jennifer-shehane** [comment]
PR open for this https://github.com/cypress-io/cypress/pull/9323
