### ISSUE TITLE
cy.get('@aliasOfIntercept) return null

### ISSUE THREAD

**Issue by kamiloski** [cypress-io/cypress#9306]
### Current behavior
Till now (before v6) i could get data eg `request.body` using `cy.get(aliasOf cy.route)` if request occurs.  Now I get on the same code which works before.

```
Timed out retrying: cy.its() errored because your subject is: null. You cannot access any properties such as request on a null value.
If you expect your subject to be null, then add an assertion such as:
cy.wrap(null).should('be.null')
```

### Desired behavior
I should get data from request

### Test code to reproduce
```js
 cy.intercept('PATCH', ${uriPatch}`).as('update_success')
 cy.wait('@update_success').its('response.statusCode').should('eq', 200)
        if (Array.isArray(bodyJson)) {
            cy.get('@update_success').its('request.body').should('deep.equal', bodyJson)    <- here I get this null, works till v6
        } else {
            cy.get('@update_success').its('request.body').should('deep.include', bodyJson)  <- here I get this null, works till v6
        }
```

### Versions
6.0.0

**Comment by jennifer-shehane** [comment]
Yeah, this is a bug. 

### Reproducible example

```js
it('test cy.intercept()', () => {
  cy.intercept('url').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/url')
    xhr.send()
  })
  
  cy.wait('@getUrl').should((interception) => {
    expect(interception).to.not.be.null
    expect(interception).to.not.be.null
  })
  cy.get('@getUrl').should((interception) => {
    expect(interception).to.not.be.null
  })
})
```

<img width="638" alt="Screen Shot 2020-11-25 at 4 05 17 PM" src="https://user-images.githubusercontent.com/1271364/100209249-08f6d400-2f38-11eb-8371-bf07f27d06f5.png">

**Comment by pete-om** [comment]
Hi @jennifer-shehane is it safe to assume that when this bug is fixed, the extra dot commands like cy.get('@alias.all') will also work again?

Cheers!

**Comment by FrancisBourgault** [comment]
I don't know if this is related, but I found that when using cy.wait (instead of cy.get), then the interception object is null only when the request is aborted. Otherwise, the interception object has both the request and the response.

There doesn't seem to be a replacement for "xhr.aborted" for the cy.wait() from version <6.0.0. Will there be an implementation for that in a future release?
