### ISSUE TITLE
Cypress sending cookies in request headers that are not present.

### ISSUE THREAD

**Issue by eXpLoD96** [cypress-io/cypress#9307]
### Current behavior
Cypress send cookies in request headers that it should not sent. We just recently added XSRF-TOKEN protection to our Java backend for POST/PUT/DELETE requests, which waits for an XSRF-TOKEN cookie to be sent in the request, along with an X-XSRF-TOKEN header that must match. Upon sending a GET request to any endpoint in the api, the cookie must be returned, so it can be used on further requests.

I am trying to implement this behavior in my Cypress tests, but am having an issue with Cypress sending cookies in the request headers that it should not send. In this example, I have enabled Cypress.Cookies.debug so it should log in the console any changes to the cookies, also before the request I am clearing all cookies and all local storage, but still in the request headers there are two cookies present, that should not be there.

![eZLA2uC](https://user-images.githubusercontent.com/1271364/102302053-94d3ad00-3f86-11eb-943b-d5ed1f70ec21.png)

This is the only test that is being run and even if I close and run the test again the cookies sent will be the same.

### Desired behavior
There shouldn't be any cookies in the request headers, since this is the first request to the endpoint and thus cookies must be returned from it.

**Comment by jennifer-shehane** [comment]
`cy.clearCookies()` will 

>Clear all browser cookies for current domain and subdomain.

Since you have not visited a site in your test, there is no current domain/subdomain known to clear the cookies from.

**Comment by eXpLoD96** [comment]
Thanks, did not think of that. Closing the issue.

**Comment by agborkowski** [comment]
in spring boot cokie xsrf-token must be put into hader with name x-xsrf-token=cokie(xsrf-token)

**Comment by emil14** [comment]
> Since you have not visited a site in your test, there is no current domain/subdomain known to clear the cookies from.

do we have this information in the docs?

**Comment by emil14** [comment]
It would be great to have sort of notification if we call `clearCookies` and no domain is set. Because otherwise calling `clearCookies` completely meaningless
