### ISSUE TITLE
Alias is undefined after spec-file reloads

### ISSUE THREAD

**Issue by ItsWasteD** [cypress-io/cypress#9310]
### Current behavior
When trying to use alias in Cypress sometimes the browsser in which Cypress is run just reloads the spec-file ("Your tests are loading...") therefore the alias isn't there anymore. And some other thing I noticed if I use arrow-functions with aliases they are not working for me. So I had to use `function() {}`

Here is the recording of the reload it happens at the last tesst of the suite: https://streamable.com/obhr5h
### Desired behavior
Cypress shouldn't reload the spec-file in the middle of the test and therefore reset variables set in tests before in the same suite.

### Test code to reproduce
```js
var dmsUser = "XXX"
var pw = "XXX"
var testfolder = "URL"
describe("BASIS29 - Ordner erstellen - Prio 1", () => {

    it("DMS Login", () => {
        cy.dmsLogin(dmsUser, pw); 
    })

    it("Visits the test folder.", () => {
        cy.visit(testfolder, {timeout: 10000}).contains("Testbereich");
    })

    it("Create folder.", function() {
        cy.get(".ico-folder-add").click();

        cy.contains("Add: Folder");
        var folderName = "Testfolder " + new Date().toISOString().replace(/[:\.T]/gi, '-').replace(/Z$/, '')
        cy.wrap(folderName).as("folderName")

        cy.get("#name")
        .type(folderName)
        .should("have.value", folderName);

        cy.get("#addButton").click();
    })

    it("Checks if folder was created.", function() {
        cy.contains(this.folderName); //Cannot find property "folderName" of undefined
    })
})
```

### Versions

- Cypress 6.0.0
- Chrome Version 86.0.4240.198

**Comment by jennifer-shehane** [comment]
This doesn't look exactly like the test failure in the video. The test fails in the "Deletes the created file again" step. 

Typically the page would refresh in this way if you are visiting a new origin domain. But this doesn't look like what's happening here. I'm not sure why the entire page is reloading. 

There is a recipe that should work for holding variable values across page reloads here: https://on.cypress.io/task#Save-a-variable-across-non-same-origin-URL-visits. This may be a good workaround. 

As for understanding why the page is reloading, we'd need a reproducible example provided to address that.

**Comment by ItsWasteD** [comment]
@jennifer-shehane Seems like its working when I'm using that workaround for values across page reloads. Thanks! But sadly I can't give you a reproducible example because for me this is only happening in that test. Nowhere else... If I see that reload somewhere else I will add it here. Maybe its just our DMS application that does some weird redirecting.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
