### ISSUE TITLE
When opening cypress from aws codebuild I get a permission denied error

### ISSUE THREAD

**Issue by ralex7** [cypress-io/cypress#9311]
While using aws codebuild I was trying to install and open cypress but get a permission denied error every time. Here are my buildspec and error files. This seems to be a problem with cypress and not codebuild. 
![Screen Shot 2020-11-24 at 10 43 22 AM](https://user-images.githubusercontent.com/52293128/100116599-eda99d00-2e41-11eb-9b3a-8a5e9cd65fca.png)
![Screen Shot 2020-11-24 at 10 43 39 AM](https://user-images.githubusercontent.com/52293128/100116624-f601d800-2e41-11eb-88ff-63a8b3598a04.png)

**Comment by flotwig** [comment]
Hi @ralex7, `cypress open` is the wrong command, you want `cypress run`. Check out the [AWS CodeBuild docs](https://docs.cypress.io/guides/continuous-integration/aws-codebuild#Basic-Setup).
