### ISSUE TITLE
Unable to install Cypress via NPM on Rapsberry Pi OS

### ISSUE THREAD

**Issue by vaks78** [cypress-io/cypress#9317]
Strange, I am unable to install cypress.. Here are the logs:
```
1711 verbose stack Error: cypress@5.6.0 postinstall: `node index.js --exec install`
1711 verbose stack Exit status 1
1711 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1711 verbose stack     at EventEmitter.emit (events.js:315:20)
1711 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1711 verbose stack     at ChildProcess.emit (events.js:315:20)
1711 verbose stack     at maybeClose (internal/child_process.js:1048:16)
1711 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
1712 verbose pkgid cypress@5.6.0
1713 verbose cwd /home/pi/twilio-react-app/react-client
1714 verbose Linux 5.4.72-v7l+
1715 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cypress" "--save-dev"
1716 verbose node v14.15.1
1717 verbose npm  v6.14.8
1718 error code ELIFECYCLE
1719 error errno 1
1720 error cypress@5.6.0 postinstall: `node index.js --exec install`
1720 error Exit status 1
```
any advice will be helpful..

**Comment by kumarcode** [comment]
same issue 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@5.6.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@5.6.0 postinstall script.

**Comment by jennifer-shehane** [comment]
What's your use case for needing to install Cypress on Raspberry Pi OS?

**Comment by jennifer-shehane** [comment]
I don't think Cypress works on Raspberry Pi just based on the few issues I've seen involving it.

**Comment by iasonov** [comment]
> What's your use case for needing to install Cypress on Raspberry Pi OS?

Installing [Fluidd](https://docs.fluidd.xyz/development) (have Cypress as a dependency during 'npm install' step)

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.

**Comment by nellePoint** [comment]
ill just +1 for a hopeful reopenign, for now i suppose, needed it for [iceshrimp](https://iceshrimp.dev/iceshrimp/iceshrimp). was hoping to have it hosted on a low-resource intensive device.

does cypress at least support the architecture (v7l+), so i could use ubuntu or something?
