### ISSUE TITLE
cypress 6.0.0: executable not found

### ISSUE THREAD

**Issue by ruudgrosmann** [cypress-io/cypress#9330]
### Current behavior
I have been running cypress 5.3.0 and 5.6.0 for a while. Cypress suggested to upgrade to 6.0.0, so I did by
- manually installing it
- changing the package.json to contain "cypress": "^6.0.0" and running npm install (and npm ci)

With all methods I get

```
npx cypress open 
No version of Cypress is installed in: /home/rdgon/.cache/Cypress/6.0.0/Cypress
Please reinstall Cypress by running: cypress install
----------
Cypress executable not found at: /home/rdgon/.cache/Cypress/6.0.0/Cypress/Cypress
----------
Platform: linux (Ubuntu - 20.04)
Cypress Version: 6.0.0

```

Indeed, the mentioned directory .cache/Cypress/6.0.0/Cypress does _not_ contain the Cypress executable, whereas this did exist in the other cached versions.
Am I missing some critical instruction, or is this a package error?

### Download method
 

- [ ] npm
- [ ] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [ x] linux (Ubuntu - 20.04)
- [ ] Mac
- [ ] Windows

**Comment by bahmutov** [comment]
Maybe something went wrong and the `post-install` step of NPM install did not run? Could you try `npx cypress install` to install the binary?

```
$ npx cypress install -h
Usage: cypress install [options]

Installs the Cypress executable matching this package's version

Options:
  -f, --force  force install the Cypress binary
  -h, --help   display help for command
```

**Comment by ruudgrosmann** [comment]
yes, I tried so. Gave the same result, but when issued with the --force option, I got a running install.
I do not understand why npm install did not do the necessary install, but for now, I am greatly relieved cypress runs again. Thank you.
