### ISSUE TITLE
cy.intercept() is not matching endpoints that contain regex match

### ISSUE THREAD

**Issue by ipinzari** [cypress-io/cypress#9337]
### Current behavior
When we tried migrating from `cy.route()` to `cy.intercept()` the endpoints that contain regex match cannot be identified by cypress. 

### Desired behavior
All api endpoints that worked with `cy.route()` should be identifiable by `cy.intercept()`  feature.

### Test code to reproduce
Working example

```
describe('page', () => {
  it('works', () => {
    // Working
   // cy.intercept('_private/browser/stats').as('browserStat')

   // Not Working
   cy.intercept('_private/*/stats').as('browserStat')

    cy.visit('https://github.com/')
    cy.wait('@browserStat')

  })
})
```
set the cypress.json  "baseUrl":"https://api.github.com"

### Versions

6.0.0

**Comment by bahmutov** [comment]
The https://on.cypress.io/intercept documentation says the URL is either a substring match, or a regex, not a minimatch like `cy.route`. I will update the docs https://docs.cypress.io/api/commands/intercept.html#Comparison-to-cy-route for clarity
