### ISSUE TITLE
Cypress Error: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents 

### ISSUE THREAD

**Issue by nids2307** [cypress-io/cypress#9338]
Issue:
When I do a `cy.visit()` on a url which is like `http://url/xyz` , I am getting the below mentioned error . 
The response we received from your web server was:

```
> 401: Unauthorized

This was considered a failure because the status code was not '2xx'.

If you do not want status codes to cause failures pass the option: failOnStatusCode: false
```

The url within `cy.visit` is suppose to redirect me `https://xyz.com/?r=https%3A%2F%2Fabx.xyz.com%2FABC-DEF`.
When I open the page by manually typing the url in the browser it works fine.

I added the `" failOnStatusCode: false"` to my `cy.visit` and it suppressed the error but now I see the following error in the console:
```
Uncaught DOMException: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
Error: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.
```

I already have the following configured in my `index.js` for the uncaught exception

```js
Cypress.on("uncaught:exception", () => false);
```

Browser: chrom e86
cypress Version: 5.6.0
O.S: windows

![image](https://user-images.githubusercontent.com/57542472/100276903-e5c42880-2f27-11eb-95f5-1824204205cf.png)

**Comment by bahmutov** [comment]
When opening an issue, please fill out the [bug report template](https://raw.githubusercontent.com/cypress-io/cypress/develop/.github/ISSUE_TEMPLATE/1-bug-report.md) provided - it requires the necessary information we need to help you.

- please provide a reproducible code example we can run to investigate

Please make sure to update to the [current version of Cypress](https://on.cypress.io/changelog).

**Comment by nids2307** [comment]
name: "🐛 Bug report"

title: '' Failed to execute 'open' on 'Document': Can only call open() on same-origin documents

### Current behavior

When I manually visit the url, it does open up the page with the loaded fields. However, under the Dev tools-> Network tab I see the following:
![image](https://user-images.githubusercontent.com/57542472/100288509-74db3b80-2f3c-11eb-9453-0b3ccc370206.png)
![image](https://user-images.githubusercontent.com/57542472/100288679-d8656900-2f3c-11eb-9ef4-f0b3141b74ea.png)

This is what I see from the test runner console"
![image](https://user-images.githubusercontent.com/57542472/100288515-799fef80-2f3c-11eb-8421-53c5a30f4bfa.png)
### Desired behavior
The application is a login page with user name pwd, sign in and sign up buttons. The purpose of the test is to validate the login functionality.

### Test code to reproduce
describe("User is on Registration Page", function() {
  it("should have the registation required fields displayed", function() {
    cy.visit(
      "https://temp-sample.domain.com/xyz-abc",
      { failOnStatusCode: false }
    );
  });
});

### Versions
