### ISSUE TITLE
cy.intercept url change not detected during file watching in Cypress open

### ISSUE THREAD

**Issue by kevinold** [cypress-io/cypress#9340]
### Current behavior

This issue occurred migrating the Cypress RWA from `cy.route` to `cy.intercept`.

A `cy.route` with a minimatch is converted to use `cy.intercept`:

Note:  Two aliases are defined against the same path (/users)

```js
beforeEach(function () {
    cy.intercept("GET", "/users").as("allUsers");
    cy.intercept("GET", "/users/search*").as("usersSearch");
})
```

When run in open mode the test fails:

![Screen Shot 2020-11-25 at 4 26 11 PM](https://user-images.githubusercontent.com/21967/100287927-3db85a80-2f3b-11eb-8960-587fee47b51b.png)

Migrating from `cy.route` to `cy.intercept` requires a glob-match (`**`) to be added to the beginning of the route.

The glob-match is added **without stopping the current run** and the file is saved:

```js
beforeEach(function () {
    cy.intercept("GET", "/users").as("allUsers");
    cy.intercept("GET", "**/users/search*").as("usersSearch");
})
```

The browser refreshes and fails against a different alias:

![Screen Shot 2020-11-25 at 4 31 59 PM](https://user-images.githubusercontent.com/21967/100288219-d5b64400-2f3b-11eb-880b-2930515c2533.png)

**Solution** Stop the current run and start a fresh run, where the glob-match is honored and the tests pass as expected

![Screen Shot 2020-11-25 at 4 36 16 PM](https://user-images.githubusercontent.com/21967/100288474-5d03b780-2f3c-11eb-8f8d-f8d6cb49b5ff.png)

A detailed demo of the issue and the solution is in this Loom:

https://www.loom.com/share/33778ef182bd489c80efa2d941e4e9f1

### Desired behavior

When a glob-match is added to a `cy.intercept` the test runner should reflect that code change during the current run.

### Test code to reproduce

See the Loom video and this diff in the RWA against the `new-transactions.spec.ts` where it can be reproduced: https://github.com/cypress-io/cypress-realworld-app/commit/504652c4561db611d6c54a8a40cdd3fea4db6bb1

### Versions

6.0.0

**Comment by bahmutov** [comment]
I believe cy.intercept drops mini match support and only allows substring or regexp

**Comment by muratkeremozcan** [comment]
Confirmed. Have to write a regex for every url we are using minimatch with.
example:
This 
`/api/*/sites/`
becomes
`\/api\/.+\/sites`

Not very convenient.

**Comment by jonstone904** [comment]
Was just looking into this myself and it appears that `cy.intercept` does still support mini-match, but you have to pass an object with a `pathname` attribute including your glob string.

For example:

cy.intercept("GET", "/users/search*").as("usersSearch")

becomes

cy.intercept({
     method: "GET",
     pathname: "/users/search*",
}).as("usersSearch")

**Comment by joszo** [comment]
> Was just looking into this myself and it appears that `cy.intercept` does still support mini-match, but you have to pass an object with a `pathname` attribute including your glob string.
> 
> For example:
> 
> `cy.intercept("GET", "/users/search*").as("usersSearch")`
> 
> becomes
> 
> ```
> cy.intercept({
>      method: "GET",
>      pathname: "/users/search*",
> }).as("usersSearch")
> ```

It doesn't work

**Comment by jennifer-shehane** [comment]
I've confirmed what @jonstone904 found, that the matching is different went passed a `pathname` versus the matcher as an argument directly. Also that the matching is different from `cy.route()`. 

I don't think that this is intentional, but will have to check with @flotwig 

### Reproducible Example

```js
// ✅ passes
it('cy.route() passes', () => {
  cy.server()
  cy.route('/users/search*').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users/search?=Sarah')
    xhr.send()
  })
  cy.wait('@getUrl')
})

// ❗️ fails
it('cy.intercept() fails', () => {
  cy.intercept('/users/search*').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users/search?=Sarah')
    xhr.send()
  })
  cy.wait('@getUrl')
})

// ✅ passes
it('cy.intercept() with pathname passes', () => {
  cy.intercept({
    method: 'GET',
    pathname: '/users/search*'
  }).as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users/search?=Sarah')
    xhr.send()
  })
  cy.wait('@getUrl')
})
```

<img width="571" alt="Screen Shot 2020-12-07 at 6 04 43 PM" src="https://user-images.githubusercontent.com/1271364/101346264-b3ff7a00-38b6-11eb-9816-93cbe2e12f47.png">

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
