### ISSUE TITLE
debugging packages/server

### ISSUE THREAD

**Issue by chisweet** [cypress-io/cypress#9343]
Hello,I am writing some features for my own usage by modifying the "packages/server" module.At the same time,I find I can't debug this module by using WebStorm or VsCode.I can launch the Cypress when I click the "run" button on the "dev" command in in the "packages.json" but it seems nothing done when I click debug button on the "dev" command.May I ask how you guys develop and debug Cypress especially the "packages/server"?

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
