### ISSUE TITLE
should('have.css', 'border', '2px') assertion fails on firefox

### ISSUE THREAD

**Issue by maga-polito** [cypress-io/cypress#9349]
### Current behavior

when asserting a react element css on firefox I'm getting empty value for css property while on chrome value is retrieved.

Notice however that value and functionality of the element is correct on firefox and if I go to inspect the element css property is correctly set.

Example of the assertion:
```js
cy.react('Module').first().should('have.css', 'border', `2px solid rgb(247, 82, 88)`) 
```

Error received is following: 
```
You attempted to make a chai-jQuery assertion on an object that is neither a DOM object or a jQuery object.

The chai-jQuery assertion you used was:

  > css

The invalid subject you asserted on was:

  > null

To use chai-jQuery assertions your subject must be valid.

This can sometimes happen if a previous assertion changed the subject.
```
### Desired behavior

Assertion should work correctly as it works on Chrome 86

### Versions

cypress 6.0.0
cypress-react-selector 2.1.0
Fifefox 83
Chrome 86

**Comment by jennifer-shehane** [comment]
I can recreate this issue in Firefox when trying to assert on the border. It behaves differently from Chrome. This looks to have always been the case. Tested back to Cypress 4.1.0. 

I thought this may be a difference of behavior with css shorthand in Firefox, but I can't find a way to use the `css` assertion at all to assert the border value in Firefox. 

```js
it('visits the page', () => {
  cy.visit('index.html')
  cy.get('span').should('have.css', 'border') 
  cy.get('span').should('have.css', 'border-width') 
  cy.get('span').should('have.css', 'border-color')
  cy.get('span').should('have.css', 'border', '2px solid red') // fails
})
```

### Chrome

<img width="634" alt="Screen Shot 2020-11-30 at 11 26 21 AM" src="https://user-images.githubusercontent.com/1271364/100571548-d109db00-3301-11eb-9730-b3a4c79395a9.png">

### Firefox

<img width="628" alt="Screen Shot 2020-11-30 at 11 26 43 AM" src="https://user-images.githubusercontent.com/1271364/100571561-da934300-3301-11eb-8fbe-dcee02750c96.png">

**Comment by spamegg1** [comment]
@lblanch Are you doing Fullstack Open too? I have the exact same issue. Thanks a lot for the solution! I'll report this to the author of the course.
