### ISSUE TITLE
Is there an equivalent of cy.server({ignore: (xhr) => bool}) to disable logging, after moving to cy.intercept?

### ISSUE THREAD

**Issue by lephuongbg** [cypress-io/cypress#9358]
### What would you like?
I would like to continue to be able to disable logging of some routes after moving to `cy.intercept()`.

### Why is this needed?
A nice side-effect of calling `cy.server({ignore: (xhr) => bool})` to disable stubbing is that it also disables logging of matching routes. This helps decluttering the logs when we're running interactive tests.

Examples are ping-pong requests with back-end server, webpack-dev-server's sockjs route, etc.

**Comment by Yethal** [comment]
Another reason one might want to disable request logging is to declutter the test reports. For example the cypress-allure-plugin by default creates a separate test step from every Cypress command ran which cause the resulting report to be unreadable if the application under test makes a ton of http calls under the hood. Ideally we should be able to turn the loggin on and off programmatically so that requests are logged when running tests in interactive mode but hidden when tests are ran on CI

**Comment by tonivj5** [comment]
I'm looking for an equivalent of `cy.server`'s `force404` option, without this option or similar behavior I can't move to `cy.intercept`... 😞

**Comment by volkanogretmen** [comment]
> I'm looking for an equivalent of `cy.server`'s `force404` option, without this option or similar behavior I can't move to `cy.intercept`... 😞

By my understanding, that's just the `statusCode` option you can pass on.

`cy.intercept('POST', '/upload/', { statusCode: 404 }).as('upload');`

All XHR's matching `/upload/` will now be forced to a 404.

**Comment by Torresangl925** [comment]
Stop hiding fools

**Comment by slikts** [comment]
If `cy.intercept()` is used for mocking, for example, assets and not just API calls, it floods the command log and makes it difficult to overview, so a feature to hide certain intercepted requests would be very nice to have for this use case.

**Comment by NEETweeb** [comment]
> Stop hiding fools

Oi! Be nice.

**Comment by stringTrimmerMm** [comment]
One workaround:  if you have access to change the code of the application under test, you can make use of window.Cypress
[https://docs.cypress.io/faq/questions/using-cypress-faq#Is-there-any-way-to-detect-if-my-app-is-running-under-Cypress](url)

For instance the app I am working on embeds Microsoft Clarity (among other 3rd party user tracking tools), which does frequent xhr posts (polluting Cypress's command log).  So I changed the app to not include Clarity when running under Cypress.  Technically in my case Clarity was being pulled in via Google Tag Manager which I also didn't care to have active while testing with Cypress so my solution was something like:
`
function initializeTrackers() {
  if (window.Cypress) return;
  GoogleTagManager.initialize();
  ...
}
`
I'm sure you could get more fancy if you sometimes DO want those things running while testing.

**Comment by Zwimber** [comment]
The solution of @cie works nicely in the latest version `10.0.2`. Found [here](https://gist.github.com/simenbrekken/3d2248f9e50c1143bf9dbe02e67f5399)

It's also really easy to modify to your specific needs, simple example:

```js
const cypressLogOriginal = Cypress.log
const cypressLogDomainsHidden = ['fontawesome.com']
Cypress.log = function (opts, ...other) {
	const logFetchIs = ['fetch'].includes(opts.displayName)
	const logFetchDomainMatch = logFetchIs && cypressLogDomainsHidden.find((d) => opts.url.includes(d))
	if (logFetchDomainMatch) return
    
	return cypressLogOriginal(opts, ...other)
}
```

**Comment by goska-malaga** [comment]
that would really be useful as an option, I need that on cy.visit in some cases and definitely on cy.reload, the log is not workable right now

**Comment by flotwig** [comment]
Hey folks, I am consolidating this issue with #7362, please follow that issue for updates.
