### ISSUE TITLE
Whoops, there is no test to run.

### ISSUE THREAD

**Issue by mrwnmonm** [cypress-io/cypress#936]
- Operating System: Ubuntu 16.04
- Cypress Version: 1.0.3
- Browser Version: Chrome Version 61.0.3163.91 (Official Build) (64-bit)

Hi,
Why the following test gives me `Whoops, there is no test to run.` page?
```javascript
describe('Existance', function(){
  it('Nav is visible', function(){
    cy.visit('https://medium.com/m/signin')
    cy.get('[data-action="twitter-auth"]').click()
    cy.wait(5000)
    cy.get('input[name="session[username_or_email]"]').type("<email>")
    cy.get('input[name="session[password]""]').type("<password>")
    cy.get('input[type="submit"]').click()
    cy.wait(5000)
    cy.visit('https://medium.com/me/stories/public')
    cy.get("nav").should('be.visible')
  });
})

**Comment by brian-mann** [comment]
It looks like you are trying to visit an external site for oauth access. This is a common anti pattern with workarounds. You should read our best practices guide on this. 

https://docs.cypress.io/guides/references/best-practices.html#Visiting-external-sites

Also keep in mind Cypress is not a general automation tool. It’s built for testing apps under tor control. 

https://docs.cypress.io/guides/references/trade-offs.html#

**Comment by brian-mann** [comment]
It looks like you are trying to visit an external site for oauth access. This is a common anti pattern with workarounds. You should read our best practices guide on this. 

https://docs.cypress.io/guides/references/best-practices.html#Visiting-external-sites

Also keep in mind Cypress is not a general automation tool. It’s built for testing apps under tor control. 

https://docs.cypress.io/guides/references/trade-offs.html#

**Comment by brian-mann** [comment]
Also might want to check out our logging in recipes. 
https://docs.cypress.io/examples/recipes/logging-in-recipe.html#

**Comment by mrwnmonm** [comment]
Well we have an extension for Medium, and I have to go to medium to make some tests while I am logged in, how I should do that? If I requested the page it will redirect to the login page.

**Comment by eric07109** [comment]
I also ran into the same problem. 

Here is my case: I want to try Cypress on my local machine to test web app deployed to company integration test machine. This app is accessed via URL with cy.visit(URL), which is unfortunately considered by Cypress a third party website. Yet, I or the company indeed has full control of the app. 

Won't this limit the range of user for Cypress? It looks to me that only test engineer who has access to code and successfully deployed locally can fully unleash Cypress's power.

**Comment by brian-mann** [comment]
@eric07109 you'll need to provide your test code and what it is you're doing. Your issue is likely very different from the one posted.

**Comment by eric07109** [comment]
Here is my case:

```
describe('Login', function(){
	it('Login', function(){
		cy.visit('URL')
		cy.get('#j_username').type('account')
		cy.get('#j_password').type('password')
		cy.get('input[type=submit]').click()
		cy.url().should('include', '/kosmos-cockpit/index.req')
	})
})

```

**Comment by craigfo** [comment]
@brian-mann  any updates on this?

The error message "Whoops, there is no test to run" is misleading when there is a test. If the error is something else why not display it rather than a generic error.
