### ISSUE TITLE
A forward slash '/' is stripped from the query paramaters on the request

### ISSUE THREAD

**Issue by rwindt** [cypress-io/cypress#9360]
### Current behavior

When using `cy.request()` for a path without a hostname the trailing `/` is deleted from the query parameters. In test we use, we have a `baseUrl`, and per test we add the path. 

For example we have defined the `baseUrl` `www.test.url`(please use a working url, this is only used as an example) and in the test we have `cy.request('/pageOne?param1=/param/')` then the following is executed in Cypress `request GET 200 http://www.test.url/pageOne?param1=/param`. The last `/` is deleted. This test started to fail since the introduction of Cypress 5.4.0, I think it could be related to this issue https://github.com/cypress-io/cypress/issues/2101

### Desired behavior

Desired behaviour is that the trailing `/` is not deleted from the given path.

### Test code to reproduce

```js
cy.request(`/pageOne?param1=/param/`)
```

Do have a baseUrl set.

### Versions

Worked on 5.3.0
Started to fail from 5.4.0 onwards

**Comment by jennifer-shehane** [comment]
To reproduce this doesn't require having a `baseUrl` set. This behavior change was introduced in 5.4.0 in https://github.com/cypress-io/cypress/pull/8630 cc @sainthkh 

Issue present: https://github.com/cypress-io/cypress/commit/b86b26e1b6014a380e42b6e5d80d7ec2974db0dc
Issue not present: https://github.com/cypress-io/cypress/commit/d28676c43eb341aff38adfe2ccbef4253b4ba95a

```js
it('request slash', () => {
  cy.visit('index.html')
  // requests to /pageOne?param1=/param/ in 5.3.0
  // requests to /pageOne?param1=/param in 5.4.0+
  cy.request('/pageOne?param1=/param/')
})
```

### 5.3.0

<img width="558" alt="Screen Shot 2020-11-30 at 10 26 49 AM" src="https://user-images.githubusercontent.com/1271364/100567435-d7df2080-32f6-11eb-8dd6-26a4096eb7f1.png">


### 5.4.0

<img width="538" alt="Screen Shot 2020-11-30 at 10 28 22 AM" src="https://user-images.githubusercontent.com/1271364/100567443-ddd50180-32f6-11eb-938e-6d0c7f0313f8.png">

**Comment by rwindt** [comment]
Very nice! And what a speed, keep up the good work!
