### ISSUE TITLE
Cypress stops running global beforeEach's

### ISSUE THREAD

**Issue by philjones88** [cypress-io/cypress#9365]
### Current behavior

Pre cypress 6.0.0 cypress would run consistently the global before/beforeEach's in the support file.

See the passing spec has 2 beforeEach's but the failing one only has 1.

<img width="680" alt="Screenshot 2020-11-27 at 16 00 59" src="https://user-images.githubusercontent.com/677167/100467542-86eae480-30ca-11eb-9129-9bf0f7dc8ba1.png">

### Desired behavior

Run global beforeEach's for each spec. As you can see in the screenshot, the session storage has not been cleared as the global beforeEach hook has not been run!

### Test code to reproduce

Have a global beforeEach in the support file. In our case it has code to clear cookies, local storage and session storage between each spec. So the user is logged out and the state is cleared fully.
### Versions

Cypress 6.0.0
Fails on MacOS and using the docker browser image on our CI.

**Comment by vincentpalita** [comment]
I am experiencing the same issue, my beforeEach() hook is on my side here to preserve the session and the cookies that have been created in the before hook.

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? We have tests around global hook execution, so likely it is something specific to the commands your using or the other hooks that are running, etc. 

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by philjones88** [comment]
I'll try and work on a sample to reproduce. The problem I have is, my 55 specs, only 7 fail with this error. I am still trying to figure out what is so special about those particular 7 spec files.

**Comment by philjones88** [comment]
More testing results. It seems to be for all our suites, it just happens randomly.

Reverting `intercept` to `route` fixes the issue.

Is this related to https://github.com/cypress-io/cypress/issues/9362 somehow?

**Comment by philjones88** [comment]
6.1.0 seems to have fixed this issue for me, still doing tests. will close if it does.
