### ISSUE TITLE
Cypress dashboard shows multiple of the same tags

### ISSUE THREAD

**Issue by bvanderneut** [cypress-io/cypress#9375]
### Current behavior
If you go https://dashboard.cypress.io/projects/qntpiv/runs you see from version 6.0.0 that there are now multiple of the same tags beeing shown.

<img width="855" alt="Schermafbeelding 2020-11-30 om 13 48 44" src="https://user-images.githubusercontent.com/44266055/100612174-d4599280-3312-11eb-8bec-ac54a7221c7f.png">

### Desired behavior
Only show the tags that are set one time. Do not repeat.

### Test code to reproduce
Install version 6.0.0 do an run and check the dashboard: https://dashboard.cypress.io/projects/qntpiv/runs

### Versions

>= 6.0.0

**Comment by bahmutov** [comment]
Hmm @bvanderneut is that project public on the Dashboard?

**Comment by bahmutov** [comment]
@bvanderneut do you run tests in parallel? Can you share your `cypress run` command, please?

**Comment by SanderMeesterIndepender** [comment]
Let me chip in;
- the run is not public available
- the tests are run in parallel on multiple machines
- the tests run on windows
- multiple groups are combined in one run

Two examples (matching the top run in the screenshot):
"D:\snip_path1\Cypress\node_modules\.bin\cypress" run $(CYPRESS_ARGUMENTS) --spec cypress/integration/OTA/**/* --record --tag "Master,Automated" --key redacted --parallel --group Algemeen --ci-build-id "Master - 1571 - 45693 (https://master.independer.nl)" --reporter-options mochaFile=./cypress/results/junit-output.Algemeen.[hash].xml
"D:\snip_path2\Cypress\node_modules\.bin\cypress" run $(CYPRESS_ARGUMENTS) --spec cypress/integration/OTA/**/* --record --tag "Master,Automated" --key redacted --parallel --group MijnIndepender --ci-build-id "Master - 1571 - 45693 (https://master.independer.nl)" --reporter-options mochaFile=./cypress/results/junit-output.MijnIndepender.[hash].xml

Note that "$(CYPRESS_ARGUMENTS)" should have been replaced by an empty string - I do not expect that this has anything to do with the behaviour.

**Comment by tgriesser** [comment]
Hi @bvanderneut - thanks for letting us know. This looked to be a regression on the dashboard's end (unrelated to 6.0, just a coincidence you encountered while upgrading).

We identified and pushed a fixed for it, let us know if you're still having issues in newer runs.
