### ISSUE TITLE
Module Not Found : Error: Can't resolve mocha in 'path'

### ISSUE THREAD

**Issue by BhavinShah12** [cypress-io/cypress#9376]
Hi Team, 

I am facing below issue while executing my first ever cypress test case. 

![image](https://user-images.githubusercontent.com/20634170/100614636-6e820080-333c-11eb-8543-4e10ba1ffa17.png)

**Comment by bahmutov** [comment]
Could you post your `Test1.js` file?

**Comment by BhavinShah12** [comment]
describe('First Test Suite', function()
{
    it('First Test Case', function()
    {
        cy.visit('https://www.cypress.io/')
    })
})

**Comment by BhavinShah12** [comment]
Yes, Please find the test below.

describe('First Test Suite', function()
{
    it('First Test Case', function()
    {
        cy.visit('https://www.cypress.io/')
    })
})


Thanks & Regards,
Bhavin Shah
9021866799

________________________________

**Comment by sainthkh** [comment]
Sorry for the late reply.

Is the problem still happening with the latest Cypress?

**Comment by Hoxtygen** [comment]
@BhavinShah12  I started learning cypress this morning too, and had the same problem as you. In fact I had already written my response to @sainthkh to let him know the error still persists but haven't submitted when I decided to take one last look at the test.
Here's something I noticed.
`it` was automatically  imported from mocha.   I didn't do that as I don't have mocha installed.
Check if the same happened to you.

Here's my test 

```
describe('Cypress', () => {
    it('is working', () => {
      expect(true).to.equal(true)
    });

    it('visits the app', () => {
      cy.visit("http://localhost:3000");
    })
  })

```

**Comment by dolthead** [comment]
I solved it by running

`yarn add -D mocha` or `npm i mocha --save-dev`

and adding this to the top of my spec.js file:

`import { describe, it } from 'mocha';`

**Comment by tirupatibs** [comment]
This worked, thank you!

**Comment by tirupatibs** [comment]
> I solved it by running
> 
> `yarn add -D mocha` or `npm i mocha --save-dev`
> 
> and adding this to the top of my spec.js file:
> 
> `import { describe, it } from 'mocha';`

it worked, thanks!

**Comment by dasDaniel** [comment]
I keep getting this issue lots

This happens because my IDE keeps sneaking in mocha import every time I add, for example, `beforeEach`

```js
import { beforeEach } from "mocha";
```

you might think I'd learn to recognize it, but yet again I was bewildered then 🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by tik9** [comment]
How can we remove the `import` permanent in `vscode`? [On Stack](https://stackoverflow.com/a/54614569/1705829) you can find info, like `"javascript.suggest.autoImports": false`

**Comment by Ananthgithubs** [comment]
"cypress": "^13.4.0"
I am facing the same issue, as soon as I beforeEach is created, it is popping the follow:
" import { beforeEach } from "mocha"; "
I had to delete this sneaked statement to run with no errors.
