### ISSUE TITLE
6.0.1 fails on install

### ISSUE THREAD

**Issue by designfrontier** [cypress-io/cypress#9383]
### Current behavior

When installing we are getting:
```
Installing Cypress (version: 6.0.1)

25l[20:10:14]  Downloading Cypress     [started]
[20:10:14]  Downloading Cypress     [failed]
25hThe Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/6.0.1?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------
```

### Download method
 

- [x] npm
- [ ] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [x] Linux
- [ ] Mac
- [ ] Windows

### Other

- [x] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by designfrontier** [comment]
installing on an EC2 instance... this just cropped up around the time the 6.0.1 release happened and visiting the URL in the message returns a 404 for me. 

6.0.0 seems to work just fine. As a workaround we've pinned to 6.0.0

**Comment by jweingarten** [comment]
Running into the same issue. https://download.cypress.io/desktop/6.0.1?platform=linux&arch=x64 does only download every 3 or 4th time.

**Comment by bahmutov** [comment]
We have purged that Cloudflare record, should be working now
