### ISSUE TITLE
Configuring Cypress to work with iFrames & cross-origin sites (functionality change from 5.4.0 to 5.5.0+)

### ISSUE THREAD

**Issue by amazza-bg** [cypress-io/cypress#9385]
### Current behavior

I am currently using the following solution to test our internal applications run by identity server OAuth

identity server documentation: https://docs.identityserver.io/en/dev/endpoints/token.html

iFrames & cross-origin sites: https://medium.com/@you54f/configuring-cypress-to-work-with-iframes-cross-origin-sites-afff5efcf61f

After installing 5.5.0 or any of the current versions (5.6.0 or 6.0.1) my application using the above method cancels all network transitions after logging into the application and kicks off a logout session before loading the page after login.

### Desired behavior

Normal behavior is being able to log into my identity server protected application without being logged out immediately after login.

### Test code to reproduce

You would need to setup a site with identity server login then implement a boilerplate cypress project with the following documentation:

iFrames & cross-origin sites: https://medium.com/@you54f/configuring-cypress-to-work-with-iframes-cross-origin-sites-afff5efcf61f

I cannot provide the site I am currently testing on as it is an internal site.

There is an obvious change to the iFrame or Cross-Origin site changes in 5.5.0 that broke functionality of utilizing extensions or altered the way cypress interacts with these vital pieces of many sites.

### Versions

5.4.0 (working)
5.5.0+ (not working)

**Comment by amazza-bg** [comment]
I would very much like to utilize the latest versions of Cypress. This is currently blocking the progress of upgrading.

**Comment by amazza-bg** [comment]
Any update to this issue? I am currently stuck at v5.4.0 until this is resolved.

**Comment by bahmutov** [comment]
No updates on this issue since we do not have a reproducible code to see the problem

**Comment by amazza-bg** [comment]
> No updates on this issue since we do not have a reproducible code to see the problem

If possible, can you work with me to request what is needed to help find a solution? I cannot provide my internal application and the steps to reproduce due to privacy. There is an obvious change to the dynamics around utilizing something like:

iFrames & cross-origin sites: https://medium.com/@you54f/configuring-cypress-to-work-with-iframes-cross-origin-sites-afff5efcf61f

in v5.5.0 and above. Getting the same scenarios to line up may be very difficult, so I believe best option here is a bit of research into the article and possible directions we can take to troubleshoot it on my end.

**Comment by QuintilianoNery** [comment]
Estou com o mesmo problema que você @amazza-bg, nossa aplicação usa o servidor de credenciais Identity server e após o login, sou direcionado para a aplicação que usa outro domínio. Vou fornecer o código de tentativa de acesso sem o e-mail e password, ele está identificando o token tudo certo, porém ao redirecionar para a aplicação ele fica em um loop.

```
describe ('Login no Geoserviços', () => {
  it.only('Fazendo Login', () => {
      //cy.server();
       //url do identity server
      cy.request('GET', 'https://conta-t.tecsystem.online').then(response => {
          // Parses the html response to fetch the CSRF token
          const htmlDocument = document.createElement('html');
          htmlDocument.innerHTML = response.body;
          const loginForm = htmlDocument.getElementsByTagName('form')[0];
          const requestVerificationToken = loginForm.elements.__RequestVerificationToken.value;
      
             //Geoservicos.Online.Web
           //PreMatricula.WebMVC
          // Sends a valid request to thirdPartyServerUrl which sets the session cookies on a successful response
          cy.request({
            method: 'POST',
             //url do identity server
            url: 'https://conta-t.tecsystem.online' + '/account/login',
            followRedirect: false,
            form: true,
            body: {
              ReturnUrl: '/connect/authorize/callback?client_id=Geoservicos.Online.Web',
              //E-mail 
              EmailOuCpf: 'e-mail',
              //Senha
              Password: 'Password da aplicação',
              __RequestVerificationToken: requestVerificationToken
            },
          });
          //URL da aplicação
          cy.visit('http://teste.geoservicos.online')

      });

  })

})
```
![image](https://user-images.githubusercontent.com/48323097/104643567-603d3900-568b-11eb-9094-a8d505eb0a00.png)

@bahmutov eu enviei para você um e-mail com este problema também. Espero que esse trecho de código ajude a termos uma solução.

**Comment by QuintilianoNery** [comment]
Conseguimos solucionar o problema sim. Como era uma aplicação que ainda não estava em produção, mudamos o endereço de treinamento para ficar com a URL compatível com a do servidor de contas, foi mais ou menos assim.
EX:
Servidor de contas: https://conta-t.empresa.online/
Ambiente de treinamento: http://teste.sistema.online/
Mudamos o ambiente de treinamento para: https://sistema.empresa.online/

No geral, assim que configuramos a URL para ficar com o prefixo igual do sistema de contas identity server, o cypress de imediato permitiu fazer o acesso na aplicação e executar os testes.
