### ISSUE TITLE
Change the default console output

### ISSUE THREAD

**Issue by omelnik** [cypress-io/cypress#9386]
In order to make the console output more descriptive, I want to be able to change the default output.

![Screen Shot 2020-11-30 at 3 52 17 PM](https://user-images.githubusercontent.com/32174556/100679580-a54c1c80-3324-11eb-9750-5885d02cb743.png)

I want to add a test environment to this output.

**Comment by jennifer-shehane** [comment]
This table in the STDOUT is not directly editable through any interface. However, you can turn off the Cypress specific table outputs by passing the [`--quiet` flag](https://docs.cypress.io/guides/guides/command-line.html#cypress-run) and use a separate mocha reporter or generate whatever reports you'd like. 

Here's also an example on how to console.log output from within a test to the STDOUT: https://on.cypress.io/task

We would be open to potentially adding more Cypress specific info to the table if others found value in the suggestion, but have no plans to develop an interface to allow arbitrary data be added to the table.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by ThatBrianDude** [comment]
The --quiet flag does not disable the default reporter.

My output still looks like this:

  √ should preselect a dashboard from the list (13643ms)
PASS: should preselect a dashboard from the list (13643ms)

While I would expect the quiet flag to disable the first line!!
How do I disable the default reporter otherwise?
