### ISSUE TITLE
Can not capture the form data of SAML scenario

### ISSUE THREAD

**Issue by aaujayasena** [cypress-io/cypress#9387]
I have implemented test for SAML scenario. Here I want to get the SAML response received and validate it. I used cy.server() and cy.rout() methods. But getting error as mentioned below. I used the assertion url as well to rout cy.route("GET", "http://nuthouse.lk/*").as('route1'); But same issue occurred.

Can you explain a way to capture the SAML response within the test to resolve this issue

Here is my code:

```js
cy.server();
        cy.route("GET", "/logincontext?/*").as('route1');
        cy.visit("https://localhost:9443/t/cypress/samlsso?spEntityID=SampleExpressApp");
        cy.get(USERNAME_INPUT).type(username);
        cy.get(PASSWORD_INPUT).type(password,{ log : false });
        cy.contains(CONTINUE_BUTTON).click({ delay: 1500000 }).wait(['@route1'], { timeout: 15000 }).then(xhr => {
            // Do what you want with the xhr object
            cy.writeFile("cypress/fixtures/saml.json",xhr.response);
        }) ;
```

![4674066848978939795](https://user-images.githubusercontent.com/39077751/100694992-41723400-33b6-11eb-8f95-5de55f99987f.jpg)

![4382353962965469635](https://user-images.githubusercontent.com/39077751/100695001-46cf7e80-33b6-11eb-9d95-39572be3ad17.jpg)

**Comment by jennifer-shehane** [comment]
Have you tried our new [`cy.intercept()`](https://on.cypress.io/intercept) command? It's replacing `cy.route()`. 

Also, make sure that's your writing a matching glob matcher or regex, because it doesn't seem like it's recognizing `/logincontext?/*` as matching the request.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by aaujayasena** [comment]
Try with  cy.intercept() and it work as expected. Thank you @jennifer-shehane  :)
