### ISSUE TITLE
Cypress and Jest Typescript types collision

### ISSUE THREAD

**Issue by daviddelusenet** [cypress-io/cypress#9392]
### Current behavior
I can't find a setup which does a types check for both my Jest and Cypress tests at the same time without type collisions. I need to exclude the `cypress` folder from the TSC compiler to get it to work.

[The example in the documentation](https://github.com/cypress-io/cypress-and-jest-typescript-example) basically does the same: only the `src` folder is included in the root `tsconfig.json`, ignoring the `cypress` folder.

### Desired behavior
Being able to run `tsc` and not have type collisions while having the `cypress` and `src` folders included in the root `tsconfig.json`.

### Test code to reproduce
I made a small repo which illustrates the bug. You can find it [here](https://github.com/daviddelusenet/cypress-jest-typescript). Please follow the instructions in the README to replicate the bug.

### Versions
The latest and greatest of everything.

Please let me know if you need any more information, I'll be happy to provide it. Thanks in advance!

**Comment by bahmutov** [comment]
Hi,

I have updated that project to show how to do linting better https://github.com/cypress-io/cypress-and-jest-typescript-example#linting - in summary, you want to separate TS configs to be explicit and avoid types clashes.
