### ISSUE TITLE
Ability to call another spec/test in different spec file

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#9405]
### What would you like?

We are testing multiple views (ie desktopView, tabletView, and mobileView). In some cases, tests end up being the same (ie element selectors) for these view. The only thing that is different is width and height.

Each view has its own *.json config file where it specifies the width and height. 

### Why is this needed?

So to avoid writing same tests, it would be great to utilize existing ones.

**Comment by jennifer-shehane** [comment]
This should be possible within Cypress, depending on how you set up your tests. 
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
