### ISSUE TITLE
Running Cypress caused a generic node error: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by dweng0** [cypress-io/cypress#9414]
### Current behavior
When running Cypress for the first time, I got a generic Nodejs error: 
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

### Desired behavior
It turned out to be because I did not have `process.env.APPDATA` set. It would be ideal if during the verification process Cypress checks it has all the necessary variables required for it to run. It is minor but caused me a long while of

### Test code to reproduce
Remove APPDATA from your environment variables list and run cypress.

### Versions

Cypress 6.0.0

**Comment by jennifer-shehane** [comment]
- Can you provide the full stack trace of the error or a screenshot of the error?
- Did the error stop and exit Cypress or did it just print to the terminal?
- What OS are you using?
- Is the error throwing during cypress install? cypress run? or cypress open?

I wasn't able to reproduce the error from the steps provided.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
