### ISSUE TITLE
Cypress fails at wrong lines, with a wrong message, on something that others than the problem

### ISSUE THREAD

**Issue by JordyGitGuro** [cypress-io/cypress#9416]
### Current behavior

![cypressBug](https://user-images.githubusercontent.com/73442001/100865809-7fe41d80-34a0-11eb-8672-893a82ffdcf0.PNG)
as you can see, cypress fails with an 'out of the blue' error message. 

### Desired behavior
Wanted the test to succeed or show me the right error message, at the correct lines why.

### Test code to reproduce
    it("Adding a new appointment", () => {
        cy.wait(5)
       addAppointment.enterID("7383189")
       addAppointment.clickChooseSoldier()
       cy.get("#soldierRank").should('have.value', 'First Lieutenant')
       cy.get("#severities").should(($severitiesArray) => {
           expect($severitiesArray.get(0)).to.have.property('childElementCount', 6) 
       })
       .then(($severitiesArray) => { let optionVal = new Array()
       optionVal = $severitiesArray.children()
       let optionalValue = optionVal[Math.floor(Math.random() * optionVal.length) + 1]
       addAppointment.selectSeverity(optionalValue.text)
       })

       addAppointment.entertDescription("A very urgent appointment") 
       cy.get("#doctors").should(($doctorSelect) => {
            expect($doctorSelect.get(0)).to.have.property('childElementCount', 7)
       })
       .then(($doctorSelect) => {
        let optionArray = new Array()
        optionArray = $doctorSelect.children()
        let optionalValue = optionArray[Math.floor(Math.random() * optionArray.length) + 1]
        addAppointment.selectDoctor(optionalValue.text)
        addAppointment.chooseMonth(month)
        addAppointment.chooseAppointmentDate(dateValue)
        addAppointment.showAvailableAppointments()
        cy.get(("#schedule"), { timeout: 540000 }).should(($appointments) => { 
           expect($appointments.children()).to.have.length.of.at.least(1)
        })
    })
})
})

when I added the current method - 
### Test code to reproduce
    '''chooseMonth(value) {
      cy.get(".ui-datepicker-month").then((currentMonth) => {
          if(! currentMonth.text == value) {
              cy.get(".ui-datepicker-prev").click()
              this.chooseMonth(value)
          }
    })
}

cypress wasn't able to address me on what the problem is - with a wrong message, at the wrong lines, all other than the problem.

### Versions
cypress - 5.4.0 
chrome 87

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? We can't run the provided code to see and track down the error you're encountering - there's a lot of test method definitions not provided and an application to test against is not provided. 

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by JordyGitGuro** [comment]
> Can you provide a reproducible example? We can't run the provided code to see and track down the error you're encountering - there's a lot of test method definitions not provided and an application to test against is not provided.
> 
> Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
yes right away

**Comment by JordyGitGuro** [comment]
> Can you provide a reproducible example? We can't run the provided code to see and track down the error you're encountering - there's a lot of test method definitions not provided and an application to test against is not provided.

The main problem is in this method -
 chooseMonth(value) {
  cy.get(".ui-datepicker-month").then((currentMonth) => {
      if(! currentMonth.text == value) {
          cy.get(".ui-datepicker-prev").click()
          this.chooseMonth(value)
      }
})
}
when I used this method in the test-
addAppointment.chooseAppointmentDate(dateValue) // dateValue = 'November'
 the screenshot above happend, and the problem seems to be on other lines, with a nonsense error message -
"cy.contains() can only accept a string, number or regular expression.Learn more" 
> 30 |             expect($doctorSelect.get(0)).to.have.property('childElementCount', 7)

I can send you the system I'm working on, if this what you want.

- these are the test and the page - 
class NewAppointment {

    navigateToAppointmentPage() {
        cy.soldierTreatment()
        cy.get("[href='/appointments/new']").click()
    }

    enterID(value) {
        cy.get("#soldierID").type(value);
    }

    clickChooseSoldier() {
        cy.get(".btn-default").contains("בחר חייל").click()
    }
    
    selectSeverity(value) {
        cy.get("#severities").select(value)
    }

    entertDescription(value) {
        cy.get("#reason").type(value)
    }

    byClinic() {
        cy.get("#clinicDoctors").click()
    }

    byEverything() {
        cy.get("#allDoctors").click()
    }

    selectDoctor(value) {
        cy.get("#doctors").select(value)
    }

    showAvailableAppointments() { 
        cy.get(".btn-default").contains("הצג תורים פנויים").click()
    }

    chooseByDocotorAppointment(value) {
        cy.get("#schedule > tr > td").contains(value)
    }

    setAppointment(value) {
        cy.get(".btn-default").contains("קבע תור")
    }

    chooseAppointmentDate(value) {
        cy.get("[data-handler='selectDay']").contains().click()

    }

    chooseMonth(value) {
      cy.get(".ui-datepicker-month").then((currentMonth) => {
          if(! currentMonth.text == value) {
              cy.get(".ui-datepicker-prev").click()
              this.chooseMonth(value)
          }
    })
}
}
export default NewAppointment



---


import NewAppointment from '../PageObject/NewAppointment'

describe('Adding New Appointemnt', () => {
    const addAppointment = new NewAppointment()
    const dateValue = '4'
    const month = 'November'

    beforeEach(() => {
        cy.openAsisim()
        cy.login('manager','manager')
        addAppointment.navigateToAppointmentPage()
    })

    it("Adding a new appointment", () => {
       addAppointment.enterID("7383189")
       addAppointment.clickChooseSoldier()
       cy.get("#soldierRank").should('have.value', 'First Lieutenant')
       cy.get("#severities").should(($severitiesArray) => {
           expect($severitiesArray.get(0)).to.have.property('childElementCount', 6) 
       })
       .then(($severitiesArray) => { let optionVal = new Array()
       optionVal = $severitiesArray.children()
       let optionalValue = optionVal[Math.floor(Math.random() * optionVal.length) + 1]
       addAppointment.selectSeverity(optionalValue.text)
       })

       addAppointment.entertDescription("A very urgent appointment") 
       cy.get("#doctors").should(($doctorSelect) => {
            expect($doctorSelect.get(0)).to.have.property('childElementCount', 7)
       })
       .then(($doctorSelect) => {
        let optionArray = new Array()
        optionArray = $doctorSelect.children()
        let optionalValue = optionArray[Math.floor(Math.random() * optionArray.length) + 1]
        addAppointment.selectDoctor(optionalValue.text)
        addAppointment.chooseMonth(month)
        addAppointment.chooseAppointmentDate(dateValue)
        addAppointment.showAvailableAppointments()
        cy.get(("#schedule"), { timeout: 540000 }).should(($appointments) => { 
           expect($appointments.children()).to.have.length.of.at.least(1)
        })
    })
})
})

**Comment by JordyGitGuro** [comment]
> Can you provide a reproducible example? We can't run the provided code to see and track down the error you're encountering - there's a lot of test method definitions not provided and an application to test against is not provided.
> 
> Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

hey, can you check it out please? 
uploaded some solid details.
the bug is understandable

**Comment by bahunov** [comment]
You can't do:

cy.get("#doctors").should(($doctorSelect) =>

Only then would work.. I believe.
