### ISSUE TITLE
cy.visit() doesn't load fully page

### ISSUE THREAD

**Issue by nataljka17** [cypress-io/cypress#9419]
Hello,

Facing the issue loading the login page in cypress test using cy.visit(). Tested in browser and  url link is working correctly so the page is fully loading. But only in cypress test the page elements are not visible and it is impossible to input credentials and click to login. 

Error:

```
_Timed out retrying: cy.type() failed because this element is not visible:

<input autocomplete="off" class="ids-input ids-input--text ids-input--clear js-has-input-clear js-login-toggle-active-input-user" id="j_username" name="j_username" placeholder="E-Mail, ID, or Login Name" type="text" value="">

This element <input#j_username.ids-input.ids-input--text.ids-input--clear.js-has-input-clear.js-login-toggle-active-input-user> is not visible because its parent <body> has CSS property: display: none

Fix this problem, or use {force: true} to disable error checking.Learn more_
```

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

If you're trying to type within an iframe, Cypress doesn't support iframes, but there are workarounds here: https://github.com/cypress-io/cypress/issues/136 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
