### ISSUE TITLE
Blocked a frame with origin *origin* from accessing a cross-origin frame when chromeWebSecurity: false

### ISSUE THREAD

**Issue by eellnnaa** [cypress-io/cypress#9422]
### Current behavior
Getting security error "Blocked a frame with origin *origin* from accessing a cross-origin frame."
I've tried to set chromeWebSecurity: false in cypress.json, tried to change it with --config and with Cypress.config() but it didn't help.
![image](https://user-images.githubusercontent.com/75378097/100889693-1b38bb00-34c0-11eb-8289-f128c643b2e1.png)
![image](https://user-images.githubusercontent.com/75378097/100888658-0ad41080-34bf-11eb-9e83-ca3205511e8c.png)

### Desired behavior
Have an access to a cross-origin frame.

### Versions
Cypress: 6.0.1
Chrome 87
Ubuntu 20.04.1 LTS

**Comment by jennifer-shehane** [comment]
Can you include the code from your `support/index.js` file where this error is throwing? Specifically this `hasNavigated` function?

**Comment by eellnnaa** [comment]
Sorry, the problem was on our side. Thanks!
