### ISSUE TITLE
mp4 videos are corrputed

### ISSUE THREAD

**Issue by matthias-ccri** [cypress-io/cypress#9427]
### Current behavior

I'm seeing a video generated but the video doesn't work. In Ubuntu, in Videos, the message is "this file contains no playable streams". VLC fails to play, with no error message. `mpv` shows a cypress screen for a split second, then exits. Chrome shows the same cypress screen, but it doesn't play. And it looks like a premature capture.

![image](https://user-images.githubusercontent.com/18034092/100913441-ca18cf00-349f-11eb-8365-bbe11ac20233.png)

Opening the video in a hex editor shows some trailing text: the name of the cypress test. This seems wrong...

![image](https://user-images.githubusercontent.com/18034092/100913572-f3395f80-349f-11eb-96c1-c33589624a19.png)

I'm running `cypress run`, and my cypress json is `{}`.

### Desired behavior
Video files should play. I'm not too familiar with media formats.

### Test code to reproduce
Feel free to close if no one else sees this issue. If you need more information, please let me know what to gather.

### Versions

This was a fresh install (cypress 6.0.0) on ubuntu 18 (both my local dev machine and a GitLab CI server using image `cypress/base:12.19.0`).

**Comment by kaiyoma** [comment]
Versions of Cypress previous to 6.0.1 + Chrome 87 have known issues with videos being completely DOA. Try upgrading to 6.0.1. Even with that version, I'm still seeing some issues: https://github.com/cypress-io/cypress/issues/9429

**Comment by matthias-ccri** [comment]
Thanks for the info @kaiyoma . I'm closing as a duplicate of https://github.com/cypress-io/cypress/issues/9265
