### ISSUE TITLE
Video files often have the wrong length and a "dead zone" at the end

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#9429]
### Current behavior
Ever since upgrading to 6.0.1 (from 5.6.0), I've noticed that video files often have issues regarding the content length; namely, the reported length of the video is longer than the actual content. This exhibits itself in a couple ways:

1. The playback time will suddenly jump to the end of the file when playing the video normally
2. Trying to scrub to a time in the "dead zone" will cause playback to stop immediately

I've seen the "dead zone" be as short as 8-9 seconds, but also as much as nearly 50% of the entire video.

### Desired behavior
Video files should not be corrupted.

### Versions
Cypress: 6.0.1
OS: Windows 10, Linux
Browser: Chrome 87

**Comment by jennifer-shehane** [comment]
I tried running a few simple examples in both Electron and Chrome 87 and wasn't able to reproduce this. They would sit for a second after the test ran - before the browser shuts down. 

- Can you provide a set of tests to run to create this situation (especially where there are more than 2 secs of 'dead time').

##### Video was expected 32 secs

```js
it('test', () => {
  cy.wait(30000)
})
```

##### Video also ended when tests ended

```js
describe("Testing", () => {
  Array(300).fill(0).forEach((val, i) => {
    it(`test ${i}`, () => {
      expect(true).to.be.true
    })
  })
})
```

**Comment by kaiyoma** [comment]
Just to set expectations, I doubt I'll be able to come up with tests that repro this problem 100% of the time. From monitoring my CI, I can see that some Cypress videos are fine, but quite a few definitely have this problem. I'm happy to privately send you one of the video files if that would help.

**Comment by vicatcu** [comment]
I'm also seeing this happen quite often now. @jennifer-shehane would it be helpful to send you a link to such a video (or email you one)?

**Comment by jennifer-shehane** [comment]
There is an issue with Firefox videos https://github.com/cypress-io/cypress/issues/6337, but if this is in Chrome - we haven't been given a way to reproduce. I don't doubt that this is happening, so sending the video is unnecessary. Without a way to reproduce it though, we can't track down why it is happening.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by marracuene** [comment]
We are also encountering this with Cy 6.4.0, running Chrome headless on an AWS Codebuild environment.   The same tests run in a desktop environment (even headless), do not evidence the problem.    May be helpful to note that it is always associated with a failed call to cy.screenshot, see stacktrace below.

Tried upgrading to 6.8.0, still happening.   V. irritating as it hides the actual test problem from us.

N.B. our test code does NOT call cy.screenshot.

```
CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.
--
912 | at https://dev.wastebase.org/__cypress/runner/cypress_runner.js:159555:22
913 | at tryCatcher (https://dev.wastebase.org/__cypress/runner/cypress_runner.js:10609:23)
914 | at https://dev.wastebase.org/__cypress/runner/cypress_runner.js:5731:41
915 | at tryCatcher (https://dev.wastebase.org/__cypress/runner/cypress_runner.js:10609:23)
916 | at Promise._settlePromiseFromHandler (https://dev.wastebase.org/__cypress/runner/cypress_runner.js:8544:31)
917 | at Promise._settlePromise (https://dev.wastebase.org/__cypress/runner/cypress_runner.js:8601:18)
918 | at Promise._settlePromise0 (https://dev.wastebase.org/__cypress/runner/cypress_runner.js:8646:10)
919 | at Promise._settlePromises (https://dev.wastebase.org/__cypress/runner/cypress_runner.js:8722:18)
920 | at _drainQueueStep (https://dev.wastebase.org/__cypress/runner/cypress_runner.js:5316:12)
921 | at _drainQueue (https://dev.wastebase.org/__cypress/runner/cypress_runner.js:5309:9)
922 | at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues


```
