### ISSUE TITLE
ESOCKETTIMEDOUT error

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#943]
- Operating System: Windows 7
- Cypress Version: 1.0.3
- Browser Version: 62

### Is this a Feature or Bug?
Bug

The issue is occurring on my colleague's machine who is offshore (India time). I am submitting this issue on his behalf. Due to the time discrepancy, responses may be slow. However this is a blocking issue for our team since we are trying to convert to using Cypress and TDD as a team thus we need the environment to be working on all machines before beginning our new work. I've googled this issue and tried diagnosing/solving it but so far no luck.

### Additional Info (images, stack traces, etc)
Console was cleared
cypress_runner.js:136628 Command:   visit
cypress_runner.js:136628 Error:     CypressError: cy.visit() failed trying to load:

http://localhost:9000/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: ESOCKETTIMEDOUT

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (C:\Data\Testing\cypress\Cypress\resources\app\packages\server\node_modules\request\request.js:778:19)
    at ClientRequest.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:614:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:334:8)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'Enter BAC Details Wizard Forms'
cypress_runner.js:136628 Snapshot:  The snapshot is missing. Displaying current state of the DOM.

![image](https://user-images.githubusercontent.com/2848185/33078806-c7274e46-cea1-11e7-9364-d77dc4ed7487.png)

**Comment by brian-mann** [comment]
Does this happen **every single time** or intermittently? 

Can you have them refresh repeatedly, like at least 10 times to see if all 10 times it results in a socket timeout. 

Also how long are these errors taking to come back? Instantly or after like 30-60 seconds?

**Comment by egucciar** [comment]
It was every time. Ended up being some edge case issue with the developers host file and corporate settings. It is now fixed.

**Comment by ruiramos** [comment]
Hey, 
I have this happen intermittently, on a before each that's simply supposed to load the testing page. I'm trying to run cypress on my local dev environment so there's a couple of things going on here like webpack-dev-server and it's live reload WS connection... is this known to be a problem?!
Thanks,
Rui

**Comment by ruiramos** [comment]
I eventually see some of these in the console, not sure if it's a problem:
```
WebSocket connection to 'ws://webpackdevserver:8080/sockjs-node/827/ofpjio5l/websocket' failed: WebSocket is closed before the connection is established.
```

**Comment by matt212** [comment]
hey @jennifer-shehane  and @brian-mann  , i am actually facing the same issues 
with cypress 3.1.1 any updates on same

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this - with app and test code?

**Comment by willischu** [comment]
It's not consistently reproducible but I also encounter this issue as well, on several specs.

![image](https://user-images.githubusercontent.com/10055168/50045719-f2665380-0065-11e9-86b2-fe514b37c9ec.png)
![image](https://user-images.githubusercontent.com/10055168/50045722-fa25f800-0065-11e9-9346-799b95156427.png)

**Comment by MichaelrMentele** [comment]
I'm getting a similar issue running this locally against a dockerized django app. My cypress service is linked to the app.

```
cypress:
  volumes:
    - ./app:/app/app
    - ./cypress:/app/cypress
    - ./cypress.json:/app/cypress.json
    - ./wait-for-it.sh:/app/wait-for-it.sh
  build: ./cypress.Dockerfile
  container_name: cypress
  environment:
    - CYPRESS_baseUrl=http://app:8000
  links:
    - app
  command: /app/wait-for-it.sh app:8000 -t 30 -- npx cypress run --spec='./cypress/integration/**'
```
I get the following errors:
```
The request we sent was:

Method: GET
URL: http://app:8000/status/

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

RequestError: Error: ESOCKETTIMEDOUT
    at new RequestError (/root/.cache/Cypress/3.1.4/Cypress/resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/root/.cache/Cypress/3.1.4/Cypress/resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/root/.cache/Cypress/3.1.4/Cypress/resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/root/.cache/Cypress/3.1.4/Cypress/resources/app/packages/server/node_modules/request/request.js:185:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at ClientRequest.<anonymous> (/root/.cache/Cypress/3.1.4/Cypress/resources/app/packages/server/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at Socket.emitTimeout (_http_client.js:722:34)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at Socket._onTimeout (net.js:402:8)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by MichaelrMentele** [comment]
Ignore me. PEBCAK.

**Comment by chrispickford** [comment]
Could this issue be related to this SO question?

https://stackoverflow.com/questions/24320578/node-js-get-request-etimedout-esockettimedout/37946324

As per the top answer, would increasing the thread pool size be a potential fix?

**Comment by jennifer-shehane** [comment]
Hey @chrispickford, thanks for the suggestion. We already do increase the thread pool. 

We'll need a reproducible issue to really track this down. We have fixed several ESOCKETTIMEDOUT issues over recent releases, but may not have gotten them all.

**Comment by devsh4** [comment]
This happens randomly. However the only thing consistent is that it happens on cy.visit() or cy.reload() commands.

**Comment by jennifer-shehane** [comment]
@devsh4 Please comment with a reproducible example. We cannot investigate issues that we cannot reproduce.

**Comment by mxrguspxrt** [comment]
We are having same issue. Chrome + Circle CI + cy.visit('sub1.domain.com') + cy.visit('sub2.domain.com') + cy.visit('sub1.domain.com') (if 3rd visit takes longer than 3 minutes and 20 seconds, than this error seems to appear).

**Comment by Bonfipa** [comment]
Hello, sorry, my English is not fluent so I'm using google translator. After a few days suffering, doing everything I saw in the forums and could not solve the problem.

How I solved: In my tests I call a login function before each case, and there was the problem, I created a suite of tetes for login screen, and the others I do the direct access. From what I understand, since I do not log off at the end of the tests, then it raises the problem. I'm a beginner in automated testing, but that's how I can solve it.
Cypress version: 3.4.0

**Comment by leonfs** [comment]
@chrispickford We did update that environment variable, but the error would still happen every so often. Other StackOverflow threads mention setting the `maxSockets` property of the request library as an option, but I'm not sure that will help as Cypress runs within the browser. Have you end up finding the solution to the problem?

**Comment by markhicken** [comment]
I'm not sure if this helps at all, but today, I'm seeing this error when running Charles Proxy to forward our prod domain to localhost:9002. For me it happens consistently in the same place. 
![Screen Shot 2019-08-19 at 4 33 08 PM](https://user-images.githubusercontent.com/849930/63304083-0c180480-c29f-11e9-9e3f-68f7017007ff.png)

Perhaps it is some inconsistency with the proxy in different environments?

**Comment by leonfs** [comment]
We've fixed the problem by adding a request header (`Connection: "Keep-Alive"`) to the visit command.

**Comment by thomasleveil** [comment]
For me I had a webserver which failed if it could not find the "Accept-Encoding" header. 

Fixed with :

```js
                    cy.visit(url, {
                        headers: {
                            "Accept-Encoding": "gzip, deflate"
                        }
                    })
```

**Comment by sushantlokhande** [comment]
> For me I had a webserver which failed if it could not find the "Accept-Encoding" header.
> 
> Fixed with :
> 
> ```js
>                     cy.visit(url, {
>                         headers: {
>                             "Accept-Encoding": "gzip, deflate"
>                         }
>                     })
> ```

Thanks @thomasleveil for giving solution.. It really worked for me :)

**Comment by MehranShafqat** [comment]
> We've fixed the problem by adding a request header (`Connection: "Keep-Alive"`) to the visit command.

Nothing for me still facing the issue  cv 4.0.2

**Comment by karansharma3009** [comment]
> For me I had a webserver which failed if it could not find the "Accept-Encoding" header.
> 
> Fixed with :
> 
> ```js
> cy.visit(url, {
>   headers: {
>     "Accept-Encoding": "gzip, deflate"
>   }
> })
> ```

that worked ...thanks for sharing it

**Comment by jennifer-shehane** [comment]
This issue is closed.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by bildungsroman** [comment]
> For me I had a webserver which failed if it could not find the "Accept-Encoding" header.
> 
> Fixed with :
> 
> ```js
> cy.visit(url, {
>   headers: {
>     "Accept-Encoding": "gzip, deflate"
>   }
> })
> ```

Thank you, @thomasleveil ! This was driving me crazy and your suggestion worked like a charm.

**Comment by bildungsroman** [comment]
I spoke too soon. This worked for me locally, but when I ran the same test in a CodeBuild job, I got the ESOCKETTIMEDOUT error again, despite having `"Accept-Encoding": "gzip, deflate"` in the headers.

**Comment by deepsuthar76** [comment]
> 

Thank You So Much for your Solution, Its working fine for me

**Comment by sosnet** [comment]
> For me I had a webserver which failed if it could not find the "Accept-Encoding" header.
> 
> Fixed with :
> 
> ```js
> cy.visit(url, {
>   headers: {
>     "Accept-Encoding": "gzip, deflate"
>   }
> })
> ```

Is it possible to change this somewhere global or do I have to add it for each request?

**Comment by hshoja** [comment]
My on end, I tested all suggested solutions, but not succeeded 
I found it always return this error `ESCOKETTIMEDOUT` error for the first test, so I doubled the `pageLoadTimeout` but it didn't work. So finally, I sorted it with a plugin named [cypress-plugin-retries](https://www.npmjs.com/package/cypress-plugin-retries).

**Comment by RockChild** [comment]
> My on end, I tested all suggested solutions, but not succeeded I found it always return this error `ESCOKETTIMEDOUT` error for the first test, so I doubled the `pageLoadTimeout` but it didn't work. Finally, I sorted it with a plugin named [cypress-plugin-retries](https://www.npmjs.com/package/cypress-plugin-retries).
> 
> update: cypress supports it, and you can remove the package and use [this](https://docs.cypress.io/guides/guides/test-retries#Configure-Test-Retries)
> 
> ```js
> {
>   "retries": {
>     // Configure retry attempts for `cypress run`
>     // Default is 0
>     "runMode": 2,
>     // Configure retry attempts for `cypress open`
>     // Default is 0
>     "openMode": 0
>   }
> }
> ```

I don't know if you noticed but cypress core has it since 5.0.0
<img width="920" alt="image" src="https://user-images.githubusercontent.com/7795004/211844732-1e91ef1b-453c-49a9-a50e-06d39a8574c5.png">

**Comment by RockChild** [comment]
In my case, the issue was resolved after setting the docker images lifecycle period to 1day. We've had this issue for a week, and while looking for fixes, the CI stopped running tests at all because there was no free space. 
After fixing the problem with space, the original issue has gone too. 
Perhaps my solution may inspire others with their cases. 
I'm pretty damn sure, the ONLY ONE golden fix for this issue just doesn't exist :)

**Comment by zeyupan888** [comment]
I increase `pageLoadTimeout` and it's working
