### ISSUE TITLE
cypress v6.0.1 stops running when I skip a test

### ISSUE THREAD

**Issue by sumeifeng** [cypress-io/cypress#9434]
I update to 6.0.1 (6.0.1.523160),and run my test scripts, one of them will skip in some scenes
but I found that  cypress will stop running when skip a testcase ,the next testcase of it will be  blocked with「No commands were issued in this test.」
it will be ok if the case not be skipped

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
