### ISSUE TITLE
enabled_labs_experiments through Browser Launch API only working in headed mode

### ISSUE THREAD

**Issue by yunj** [cypress-io/cypress#9440]
### Current behavior
In order for the cookie to work in our Cypress tests, we need to disable some chrome flags. However, disabling chrome flags through browser launch API only works in the headed mode, as shown in the attached screenshot, and it does not work when running in the `headless` mode.
```js
on('before:browser:launch', (browser, launchOptions) => {
  if (browser.name === 'chrome') {
    launchOptions.preferences.localState.browser = {
      enabled_labs_experiments: [
        'cookies-without-same-site-must-be-secure@2',
        'same-site-by-default-cookies@2'
      ]
    }

    return launchOptions
  }
})
```
![image](https://user-images.githubusercontent.com/18545475/101000798-393b1400-35c3-11eb-8771-7a31eddd614a.png)

### Desired behavior
Disabling chrome flags works in the headless mode, the same as headed mode.

### Versions
Cypress 5.3.0
Windows 10
Chrome 87

**Comment by jennifer-shehane** [comment]
The screenshot shows the experiments as 'Disabled', so I'm not sure this setting is working in headed either. 

It seems that Chromium does not support all prefs during headless mode, so you would need to run `cypress run --browser chrome --headed` to get many preferences set. Reference last comment in this thread: https://groups.google.com/g/chromedriver-users/c/62T8gnZWzd0/m/oRl2GKeiBwAJ?pli=1

I think you can also test against this site to see if experimental flags are working for cookies. https://www.chromium.org/updates/same-site/test-debug#TOC-Testing-tips

```js
it('test', () => {
  cy.visit('https://samesite-sandbox.glitch.me/')
})
```

**Comment by yunj** [comment]
Thanks @jennifer-shehane. I just modified the title. It works only in heeded mode.

**Comment by K4r1it0** [comment]
is this problem fixed?
