### ISSUE TITLE
InvalidCharacterError Failed to execute 'atob' on 'Window'

### ISSUE THREAD

**Issue by xtroncode** [cypress-io/cypress#9442]
### Current behavior

We are getting the following error trace. This is occurring randomly on random spec files in our CI environment. We are not able to reproduce it. All the retries also fail with the same error. 

```
InvalidCharacterError: The following error originated from your test code, not from Cypress.

  > Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Object.decodeBase64Unicode (https://example.com/__cypress/runner/cypress_runner.js:177637:31)
    at base64toJs (https://example.com/__cypress/runner/cypress_runner.js:176928:28)
    at Object.extractSourceMap (https://example.com/__cypress/runner/cypress_runner.js:176894:21)
    at extractSourceMap (https://example.com/__cypress/runner/cypress_runner.js:175985:37)
    at tryCatcher (https://example.com/__cypress/runner/cypress_runner.js:10325:23)
    at MappingPromiseArray._promiseFulfilled (https://example.com/__cypress/runner/cypress_runner.js:7445:38)
    at MappingPromiseArray.PromiseArray._iterate (https://example.com/__cypress/runner/cypress_runner.js:8647:31)
    at MappingPromiseArray.init (https://example.com/__cypress/runner/cypress_runner.js:8611:10)
    at Promise._settlePromise (https://example.com/__cypress/runner/cypress_runner.js:8314:21)
    at Promise._settlePromise0 (https://example.com/__cypress/runner/cypress_runner.js:8362:10)
    at Promise._settlePromises (https://example.com/__cypress/runner/cypress_runner.js:8442:18)
    at Promise._fulfill (https://example.com/__cypress/runner/cypress_runner.js:8386:18)
    at MappingPromiseArray.PromiseArray._resolve (https://example.com/__cypress/runner/cypress_runner.js:8659:19)
    at MappingPromiseArray._promiseFulfilled (https://example.com/__cypress/runner/cypress_runner.js:7485:18)
    at Promise._settlePromise (https://example.com/__cypress/runner/cypress_runner.js:8322:26)
    at Promise._settlePromise0 (https://example.com/__cypress/runner/cypress_runner.js:8362:10)
```

### Desired behavior

The tests should not fail with this error or atleast should correct itself in retries.

### Test code to reproduce

Unable to reproduce the error consistently. 

### Versions

Cypress:    5.3.0
Browser:    Custom Chrome 86 (headless)

**Comment by sgomezcnvdev** [comment]
We are getting this error as well in our CI env and sometimes Cypress throws the following error

![image](https://user-images.githubusercontent.com/8384696/101062261-306d2280-3570-11eb-8bdf-71cc09da796c.png)


![image](https://user-images.githubusercontent.com/8384696/101063390-80001e00-3571-11eb-88b1-d885034d626e.png)

Errors are generated randomly.

Versions
Cypress: 4.12.1
Browser: Chrome 83 (headless)  (cypress/browsers:node12.18.0-chrome83-ff77)

**Comment by jennifer-shehane** [comment]
Are either of you testing file upload in your tests? Or Cypress.Blob anywhere? I've seen this error when involved with file upload before. 

Also, I see that both of you you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you.

Can you share the code around file upload where this is failing? It would be best if you could get this occurring locally in the same browser and open DevTools to see the full error and where it's originating from.

**Comment by xtroncode** [comment]
Hi @jennifer-shehane , thanks for the reply.

We are not testing file uploads in any of our tests.

From what I can understand looking at the stack trace, the error is originating [here](https://github.com/cypress-io/cypress/blob/e9143405ca1e5244497ff241c430e2eabfd77803/packages/driver/src/cypress/source_map_utils.js#L26) when it is being called from [here](https://github.com/cypress-io/cypress/blob/478e1d23618ae2d1eb587c3d167b19967b8e6649/packages/driver/src/cypress/script_utils.js#L31) when loading the spec files in the browser. As what we saw in the video that was recorded is that the tests don't even start running.

We'll be updating to the latest cypress version this week and let you know if this still persists.

**Comment by sgomezcnvdev** [comment]
Hi @jennifer-shehane ,
In our case, we don't use Cypress.Blob and there is only one test to automate upload files. It is using this library cypress-file-upload for that. Below is the code:

![image](https://user-images.githubusercontent.com/8384696/101166775-9496f180-3617-11eb-9ac5-654d02bc6513.png)

But I saw that the error happened when Cypress tried to launch Mocha JS. In this point any test has been executed yet. Is there a way to get more information about the error? I used DEBUG option but the information is not enoght to know what happend. 

Regarding the version, I started migration to Cypress 6.0.0 last week but I had some issues with new command cy.interceptor(). Some of them were already reported in other tickets and I created this question in discusion section https://github.com/cypress-io/cypress/discussions/9364. When they are fixed, I will continue with the migration. 

Thanks for your assistance.

**Comment by nikhilesh009** [comment]
we are getting a kinda similar error on the CI environment on random spec file, local works fine. not able to reproduce locally. 
![Screenshot 2021-01-21 at 13 54 07](https://user-images.githubusercontent.com/40767850/105353982-3a1a1a80-5bf0-11eb-9116-0823c2acb2f7.png)

**Comment by andreieftimie** [comment]
I started seeing these and other (similar in nature) errors when switching to running more than 1 cypress test in parallel on the same machine.

The following failures are observed:

```
InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```

```
SyntaxError: The following error originated from your test code, not from Cypress.
> Unexpected end of input
```

```
SyntaxError: The following error originated from your test code, not from Cypress.
> Invalid or unexpected token
```

All of these are _always_ visible on the first test of each chunk, which leads me to think that cypress or the browser are not properly initiated (or the app does not manage finishing loading) before the test attempts to start.

We are running cypress 5.3.0 — would really like to solve these before attempting to upgrade to the latest version since there's a non-trivial amount of work to update of the `cy.route` calls.

I am looking into issues relating to:

- resource constrains — since we are running multiple processes in parallel, the machine might not have enough resources to allow the test run to complete correctly
- resource locking — maybe one of the processes breaks one of the others that is running on the same machine

**Comment by sgomezcnvdev** [comment]
Hi @andreieftimie , I have a similar scenario (multiple cypress process in parallel) and Cypress is throwing the same errors with latest version (6.5.0). Yesterday I upgraded the version from 4.12.1 to 6.5.0 but the errors presists. Maybe Cypress does not have support to be executed in parallel in the same machine.  In my case, errors happen randomly and other time all tests passed without any errors.

**Comment by andreieftimie** [comment]
> Maybe Cypress does not have support to be executed in parallel in the same machine.

This is how it actually looks. There seem to be multiple factors at play here.

Unfortunately I am not in control over the CI infra, and can't run real parallelism at the moment.

**Comment by ggascoigne** [comment]
Mostly chiming in here to say that we see this pretty regularly on our CI system as well, and that it seems nigh on impossible to reproduce when we're specifically looking for it.

**Comment by VickyLund** [comment]
This might help. We used to run 3 parallel processes of Cypress on one server. This caused a lot of issues for us one of which was this one.
After isolating the processes via containers, we did not get this again.

**Comment by suniljaiswal01** [comment]
I am also getting the same error while uploading .svg file. I am using the latest version of cypress (7.5.0). Below is the script to upload file:
`cy.fixture(fileName).then(fileContent => {
        cy.xpath(xpath).attachFile({
            fileContent: Cypress.Blob.base64StringToBlob(fileContent.toString()),
            fileName: fileName,
        }, { subjectType: 'drag-n-drop' });
    });`

I am able to upload .jpg/.png/json file using the same script

**Comment by jennifer-shehane** [comment]
We don't recommended running more than 1 Cypress process in parallel on a single machine. There are a few issues that happen when this is done and the majority of the time, there is not enough resources on the machine to run Cypress and it still be performant.

**Comment by andreieftimie** [comment]
> We don't recommended running more than 1 Cypress process in parallel on a single machine. There are a few issues that happen when this is done and the majority of the time, there is not enough resources on the machine to run Cypress and it still be performant.

Based on the inquires in this thread there are numerous people running multiple instances on the same machine. For example we don't have full control over the CI environment (and I suspect similar constrains for other people) so a "poor man's" parallelism is achieved through running 2-3 instances on the same machine.

While proper multi-machine parallelism would be better, we did halve the running time from ~60min to ~30 min by running 3 instances in parallel.

**Comment by poponuts** [comment]
I am having same issue now with my CI. And yes, I think running parallel tests on your CI is a common standard now.

**Comment by sgomezcnvdev** [comment]
Hi folks, I had similar issues in my CI enviroment. In my case, I was able to fix it increasing the SHM size to 4 gb (args '--shm-size="4g"') in the jenkins file and assigning different temp folder by each cypress process (XDG_CONFIG_HOME=/tmp/cyhome). In my case, jenkins job is executing 6 cypress instance in parallel without errors.

jenkins file:
![image](https://user-images.githubusercontent.com/8384696/123100506-8ff62700-d409-11eb-9dc4-810e6cd6b3da.png)

![image](https://user-images.githubusercontent.com/8384696/123100734-be740200-d409-11eb-8e56-afd82aacb1d0.png)




Versions
Cypress: 7.2.0
Browser: Chrome 89 (headless) (cypress/browsers:node12.18.3-chrome89-ff86)
CI: Jenkins

**Comment by andreieftimie** [comment]
@sgomezcnvdev nice!
What are the machine specs? (CPU cores and RAM)

**Comment by sgomezcnvdev** [comment]
@andreieftimie  
* E52066 2.0Gz  CPU(s) 8 
* 16 GB
Processes consume around 85% of resources (memory/cpu). I tried to add more processes in parallel but cypress gets slower because need more resources. So I think that I will need add another build machine in the long term.

**Comment by romankhomitskyi** [comment]
@andreieftimie Solution that helped me https://davidwcai.medium.com/fix-cypress-invalid-or-unexpected-token-errors-in-parallel-runs-e887d7efa945

**Comment by BlueWinds** [comment]
@romankhomitskyi - that is really interesting, thanks for the article, and I think you've correctly identified a root cause here.

If you (or anyone else) wanted to open a PR to do something similarly inside Cypress itself, we'd definitely be interested in taking a look at it.

**Comment by romankhomitskyi** [comment]
> @romankhomitskyi - that is really interesting, thanks for the article, and I think you've correctly identified a root cause here.
> 
> If you (or anyone else) wanted to open a PR to do something similarly inside Cypress itself, we'd definitely be interested in taking a look at it.

I think there is experienced  dev at Cypress that could do this in 1-2 days

**Comment by kavehsaket** [comment]
I get the same error when I run my tests on GitHub actions. Cypress on ci is painful.

**Comment by stefangluszek** [comment]
> We don't recommended running more than 1 Cypress process in parallel on a single machine. There are a few issues that happen when this is done and the majority of the time, there is not enough resources on the machine to run Cypress and it still be performant.

@jennifer-shehane is this documented anywhere? Also in your jenkins example you do run multiple parallel cypress processes on a single agent:
https://github.com/cypress-io/cypress-example-kitchensink/blob/master/Jenkinsfile

**Comment by guychienll** [comment]
any updates ?

**Comment by lmiller1990** [comment]
Not right now -- is this still an issue in later versions of Cypress (eg Cypress 12)?

It's hard to assign someone to work on this when it's so difficult to reproduce consistently - hard to debug and fix something that's primarily a race condition, especially if it only occurs running many Cypress instances in on a single machine in parallel, which isn't something we generally recommend (parallelization via CI and separate machines, however, is definitely something we use heavily).

You could try https://github.com/cypress-io/cypress/issues/9442#issuecomment-967204203. I don't fully understand how the webpack preprocessor conflict occurs that is suggested in that article, nor how it would lead to the `atob` error.
