### ISSUE TITLE
Error lost between plugins child process and display in UI

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#945]
When there's an error in the plugins file (syntax error, module not found, etc), the path to the plugins file is displayed as `[object Object]` and the error message is not displayed. 

![screen shot 2017-11-21 at 10 54 34 am](https://user-images.githubusercontent.com/1157043/33082583-201193b4-ceab-11e7-8ede-e73de09dafba.png)

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/946

**Comment by brian-mann** [comment]
Released in [`1.1.2`](https://docs.cypress.io/guides/references/changelog.html#1-1-2).
