### ISSUE TITLE
Testing a Laravel application with Cypress: 419 insufficient space on resource

### ISSUE THREAD

**Issue by valentinogagliardi** [cypress-io/cypress#950]
I'm testing a Laravel application with Cypress.

The test for the login page looks like this:

```javascript
describe("Knowledge Base Application", () => {
  before(() => {
    cy.exec("php artisan migrate:refresh && php artisan db:seed");
  });

  beforeEach(() => {
    cy.fixture("users/admin").as("admin");
    cy.fixture("models/article").as("article");
  });

  after(() => {
    cy.exec("php artisan migrate:refresh");
  });


  it("Should be able to login: admin", function() {
    cy.visit("/login");

    cy
      .get('input[name="email"]')
      .type(this.admin.email)
      .should("have.value", this.admin.email);

    cy
      .get('input[name="password"]')
      .type(this.admin.password)
      .should("have.value", this.admin.password);

    cy.get("form").submit();

    cy.location("pathname").should("eq", "/home");
  });
});
```

The above test works fine.

Cypress recommends testing the login only once: https://docs.cypress.io/guides/getting-started/testing-your-app.html#Logging-In

For subsequent tests it is considered best practice bypassing the UI. By using `cy.request` it is possible to send a POST request directly to the backend.

They provide even a recipe: https://github.com/cypress-io/cypress-example-recipes/blob/master/cypress/integration/logging_in_csrf_tokens_spec.js

If I want to test a feature that should be accessible only after the login, I could write something like this:

```javascript
  it("Should be able to create a new article: admin (csrfToken)", function() {
    const csrfToken = Cypress.$("meta[name=csrf-token]").attr("content");

    cy.request({
      method: "POST",
      url: "/login",
      failsOnStatusCode: true,
      form: true,
      body: {
        email: "valentino@valentinog.com",
        password: "secret",
        _token: csrfToken
      },
      headers: {
        "X-CSRF-TOKEN": csrfToken
      }
    });

    cy
      .get('input[id="title"]')
      .type(this.article.title)
      .should("have.value", this.article.title);

    cy
      .get('input[id="seo-title"]')
      .type(this.article.seo_title)
      .should("have.value", this.article.seo_title);

    cy
      .get('input[id="seo-meta-description"]')
      .type(this.article.seo_meta_description)
      .should("have.value", this.article.seo_meta_description);

    cy
      .get('textarea[id="body"]')
      .type(this.article.body)
      .should("have.value", this.article.body);

    cy.get("select").select("Published");

    cy.get("#article-form").submit();
  });
```

Unfortunately the above won't work.

This is what I get:

![cypress-laravel-csrf](https://user-images.githubusercontent.com/6078736/33124115-63a5a7a6-cf7c-11e7-8efb-d4c9de3e5362.png)

I was wondering whethere someone could point me in the right direction.

Cheers!

**Comment by bahmutov** [comment]
This seems like a problem on your server, not with the Cypress itself.

**Comment by brian-mann** [comment]
Yes this is coming from your server - not Cypress.

Your code doesn't really make sense though - specifically this part...

```js
t("Should be able to create a new article: admin (csrfToken)", function() {
    const csrfToken = Cypress.$("meta[name=csrf-token]").attr("content");

    cy.request({
```

Are you already visiting your app? If so, then logging it at that point would be "too late". There's no way you could already be logged in at that point, and looking at the code beneath the request seems to assume that you're already on a UI page.

Move the `cy.request` stuff **before** you visit your app, so that upon visiting it, you're already logged in and can access the other pages.

**Comment by sarcastron** [comment]
I know this is old, but it was the first result in my Google search. If I ran into it, others probably will as well.

I ran into a few gotchas with laravel and was getting the HTTP 419 response. I was able to get log in working on Laravel 5.6 by using the following set up.

**./cypress.json**
Set a base_url and some defaults
```json
{
  "baseUrl": "http://your-domain.tld",
  "env": {
    "email": "mana.mana@do-doo-do.dudu",
    "password": "s0m3_P4ssw0rd!"
  }
}
```
I added the login as a command because I will need to log in for pretty much every test. Because we don't use the CSRF `<meta>` tag, my `login` command relies on the `XSRF-TOKEN` cookie.

**./cypress/support/commands.js**
```js
// Note that the base_url is set in the ./cypress.json file
Cypress.Commands.add("login", (email = null, password = null) => {
  email = email || Cypress.env('email')
  password = password || Cypress.env('password')
  let _token
  cy.visit('/login')
    .getCookie('XSRF-TOKEN')
    .then((cookie) => {
      cy.request({
        method: 'POST',
        url: '/login',
        form: true,
        body: {
          email,
          password
        },
        headers: {
          // Base64 encoded string was URI encoded in headers. Decode it.
          'X-XSRF-TOKEN': decodeURIComponent(cookie.value)
        }
      })
    })
})
```

Then to use it in an actual test.
**./cypress/testGroup/anyTestRequiringLogin.spec.js**
```js
describe('Generic Test Requiring Log In', () => {
  before(() => {
    // `cy.login()` uses the custom command in commands.js
    cy.login().visit('/url-that-requires-testing')
  })

  // Without this function only the first test will work.
  beforeEach(() => {
    Cypress.Cookies.preserveOnce('laravel_session', 'XSRF-TOKEN')
  })

  it('Perform some test', () => {
    cy.get([data-testid=derp-input]).type('herp derp')
      .should('contain', 'herp derp')
  })
})
```

**Comment by 76creates** [comment]
I had CSRF issues all along, _token was not right, I was foolish to generate my own random code, code bellow worked for me, I spent quite some time on this one so hope it helps here some folks:
```
var csrf
cy.server()
cy.visit("/login")
	.then(() => {
		cy.get("head meta[name=csrf-token]")
			.then((meta) => {
				csrf = meta[0].content
			})
	})
	.then(() => {
		cy.request({
			method: 'POST',
			url: '/login',
			form: true,
			body: {
				_token: csrf,
				email: username,
				password: password
			}
		})	
	})
	.then(() => {
		cy.visit("/")
	})
```

**Comment by brian-mann** [comment]
@76creates you don't need to use all of those `.then()`

The only time `.then()` is necessary is when you need access to the yielded value of a command.

In this case only the `csrf` value is necessary to nest inside of a `.then()`. Everything else can be flat. Cypress automatically awaits and handles the enqueuing part of commands for you.

```js
cy.server()
cy.visit("/login")

cy
.get("head meta[name=csrf-token]")
.then((meta) => {
  const csrf = meta[0].content

  cy.request({
    method: 'POST',
	url: '/login',
	form: true,
	body: {
	  _token: csrf,
	  email: username,
	  password: password
	}
  })
})
cy.visit("/")
```

**Comment by ntraykov** [comment]
Thanks a lot for your help!

Shouldn't it be `meta[0].getAttribute('value')` since `<meta>` has this format: 
`<meta name="csrf-token" value="bQlUxsAgtJWRsHOn1XtjGMBZNWEXDCDCmyKkMWjL">`?
