### ISSUE TITLE
Handle undefined lifecycle callbacks better: very cryptic error message

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#952]
Cypress: 1.1.1

If we pass `undefined` as a callback to `beforeEach` for example we get a very cryptic error

```js
describe('undefined beforeEach', () => {
  let foo

  beforeEach(foo)

  it('works', () => {})
})
```
Error shown 
```
TypeError: Cannot read property 'length' of undefined

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'null beforeEach'
```
Even clicking on the error and seeing the message in the console does not give any details - just cypress runner callstack.

Undefined functions often happen when importing functions from other files, renames, etc. Need to give a clear message and maybe print the callback code.

**Comment by bahmutov** [comment]
<img width="521" alt="screen shot 2017-11-22 at 10 49 02 pm" src="https://user-images.githubusercontent.com/2212006/33158456-29cae878-cfd8-11e7-8ff2-0b2e613df496.png">

**Comment by brian-mann** [comment]
Yeah, this is because we actually override mocha here and wrap their
callback functions and invoke them ourselves.

It would be trivial for us to properly catch these errors and throw a good
message.

In fact Mocha (unless there's been a recent update) does a terrible job by
default when you don't provide a callback function. Try it outside of
Cypress and you'll see what I mean.

Nevertheless we can always do better ;-)

**Comment by bahmutov** [comment]
I agree, Mocha does not handle it, but we have this information in our code. All we need to do when setting the hook in our `code driver/src/cypress/cy.coffee:915` is to check if `runnable.fn` is undefined - then have intelligent error message
```
setRunnable: function(runnable, hookName) {
      var fn, restore;
      stopped = false;
      state("promise", void 0);
      state("hookName", hookName);
      state("runnable", runnable);
      state("ctx", runnable.ctx);
      fn = runnable.fn;
```

**Comment by bahmutov** [comment]
Even simpler way to trigger this message: 
- open any test in Cypress
- from DevTools in Cypress run `Cypress.run()`
The error message appears in the reporter

<img width="672" alt="screen shot 2017-12-01 at 3 12 57 pm" src="https://user-images.githubusercontent.com/2212006/33501369-5388b7f2-d6aa-11e7-990e-dd252f18b292.png">

**Comment by jennifer-shehane** [comment]
This behavior is still happening in Cypress version 3.4.0 (the code run in the collapsed comment, however, no long errors).
