### ISSUE TITLE
Text values encoded with &nbsp; can't be asserted

### ISSUE THREAD

**Issue by IMightGitIt** [cypress-io/cypress#9531]
Reproduced on version 6.0.1

Have a page with markup like:
`<div class="myClass">hello&nbsp;World</div>`

run cypress with test like:
`cy.get('.myClass').should('have.text','hello world')`
`cy.get('.myClass').should('have.text','hello&nbsp;world')`
`cy.get('.myClass').should('contain.text','hello world')`
`cy.get('.myClass').should('contain.text','hello&nbsp;world')`
`cy.get('.myClass').contains('hello world').should('exist')`
`cy.get('.myClass').contains('hello&nbsp;world').should('exist')`

All mentioned tests fails, and there does not seem to be any way to verify the content without doing extra text manipulation first.

On top of that, both the AssertionError in the left side-bar and in the console log shows the same counterproductive message of:
> expected '<div.myClass>' to have text 'hello World', but the text was 'hello World'

**Comment by jennifer-shehane** [comment]
I wrote a few ways that you could assert on this below. 

The assertion in your tests has all lowercase 'hello world' and the Div has 'hello World' with a capital W. If you want it to not match the exact casing, then you need to pass: `{ matchCase: false }` to `.contains()`, but any other assertion would fail without the exact casing.

```js
it('text', () => {
  cy.visit('index.html')
  cy.get('.myClass').contains('hello world')

  cy.get('.myClass').invoke('text').then((text) => {
    // remove the space char
    expect(text.replace(/\u00a0/g, ' ')).equal('hello world')
  })

  cy.get('.myClass').invoke('text')
  // remove the space char
  .invoke('replace', /\u00a0/g, ' ')
  .should('eq', 'hello world')
})
```

**Comment by IMightGitIt** [comment]
Apologies on my typo in the code example. I have a much more advanced version of the example as my actual use-case, so I wanted to do a simplified version by hand, but did not account for a spelling error. I have updated the description, so it should be correct now.

The point is that when using a valid HTML Entity like the non-breaking space, I would expect Cypress to EITHER read the text value as "&nbsp;" OR " ", but somehow it currently seems to read these values as neither of them. Hence my comment that the only way to currently assert on the text value, is to do text manipulation, as you also suggest.

While it is a workaround, I would still consider the lack of working .should or .contains functions to be somewhat of a defect, or at least an area of improvement.

@jennifer-shehane Would it be possible to re-open this ticket, as I still consider it valid. If you prefer to keep the report in a different ticket, I understand but the only linked ticket #9530 has also been closed.

**Comment by jennifer-shehane** [comment]
@IMightGitIt `cy.contains()` does work in the case above though. 

```js
cy.get('.myClass').contains('hello world')
```

**Comment by kiwdahc** [comment]
`cy.contains()` does work but `and('contain', '')` does not work for some reason?

**Comment by kiwdahc** [comment]
@jennifer-shehane Why is `&nbps;` replaced inside of the `.contains()` but not inside of `.and('contain', ''` or `.filter(':contains("")')` ? The documents state that it is replaced when using contains but when using some of the chained versions you get different functionality?

The specific use case is a collection of elements that need to be filtered down by their sub elements textContent that may or may not include an `&nbsp;`. Basically I am wondering if there is a way to write the following if both `Invoice Funded` and `GBP 1.10` have `&nbsp;` inside of them.
```
cy.get('[data-testid=activity-feed__row]')
        .filter(':contains("Invoice Funded")')
        .filter(':contains("GBP 1.10")')
        .filter(':contains("11/05/2020")')
 ```

**Comment by bahmutov** [comment]
@kiwdahc I have added example for your case here https://github.com/cypress-io/cypress-fiddle/commit/9dec37dbbefa0572dcdb3c3b63bb1cfaab43eecd

<img width="962" alt="non-breaking-space" src="https://user-images.githubusercontent.com/2212006/102512357-f021a000-4057-11eb-82fd-71f2fc458724.png">

Short story: `.filter(':contains...` uses jQuery contains selector, thus you need to use the unicode character for non-breaking space entity.

```js
.filter(':contains("GBP\u00a00.50")')
```

I will add notes to your docs
