### ISSUE TITLE
`cy.intercept` doesn't seem to populate `response` with too simple of a regex, but wait does match it

### ISSUE THREAD

**Issue by JohnnyFun** [cypress-io/cypress#9533]
### Current behavior
When I do `cy.intercept('PUT', /acceptChange/i).as('accept')`

`xhr.response` is `undefined` when I do: `cy.wait('@accept').then(xhr => console.log(xhr.response))`

But if I do `cy.intercept('PUT', /\/acceptChange/i).as('accept')` (notice the leading "/" match in the regex), response is populated.

### Desired behavior
Regex without the leading "/" match should populate `response`.

### Test code to reproduce
The above should hopefully lead to the issue, but if you're not seeing anything obvious, let me know, and I can put something more formal together for you.

### Versions
Cypress@6.0.1

**Comment by bahmutov** [comment]
Hmm, I could not recreate this bug using https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__intercept/cypress/integration/spy-on-fetch-spec.js#L56

Could you provide a fully reproducible example please

**Comment by JohnnyFun** [comment]
Does it happen if you use `cy.intercept('PUT', /users/i).as('updateUser')` instead. (i.e. with a regex instead of string as the 2nd parameter?

Then using `/\/users/i` should make response get populated.

**Comment by JohnnyFun** [comment]
Otherwise, I'll clone that repo quick and see if I can get it to happen in a bit here.

**Comment by JohnnyFun** [comment]
Oh, I see you have one that does that. The link took me to a different one. I'll clone and see if this one does it or if I can get it to do it slightly modified:

```
it('can spy using URL case-insensitive regexp', () => {
      cy.visit('/')
      cy.intercept('PUT', /users/i).as('updateUser')
      cy.get('#put-user').click()
      cy.wait('@updateUser')
      .its('response.statusCode')
      .should('equal', 200)
    })
```

**Comment by bahmutov** [comment]
Yeah play with that recipe to see if you can get a problem

**Comment by JohnnyFun** [comment]
Ahhh, I think I see what happened. I had:

```
cy.intercept('PUT', /change/i).as('change')
cy.intercept('PUT', /acceptChange/i).as('accept')
```

The first regex matches for both. I confirmed that if I simply swap the order, it works. So looks like it was just because the network request was getting matched by both, and maybe the first one read the body and the next one ended up with nothing for the response or something like that.

Sorry about that. Nice work on `cy.intercept`! Was minimal pain switching over, and we can use real fetch now instead of polyfill!
