### ISSUE TITLE
click({force: true}) doesn't seem to click 

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#9540]
### Current behavior

Below shows the differences between force sets to `false` and `true`.

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/2043287/101303543-12fbbb00-37f3-11eb-9c44-661a86a896d3.png">

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/2043287/101303576-2444c780-37f3-11eb-875c-4884b6fe75c8.png">

### Test code to reproduce

> cy.visit('https://www.yummly.com/')
cy.get('.qa-ready')
cy.get('.onboarding-bubble').eq(0).click({force: true})

### Versions

Cypress: 6.0.1
Chrome: 87.0.4280.88
Mac OS: 11.0.1

**Comment by jennifer-shehane** [comment]
I do think it's strange that just firing the events wouldn't trigger all the appropriate events, the regular `click()` works. Is there a reason you need to pass `force: true`?

**Comment by quad5** [comment]
The reason to use click({force: true}) is because there is some bubbles/choices hidden in view until user clicks the right arrow to scroll to it. I was thinking of using {force: true}  to click any bubble randomly regardless it is in view or not.

https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Forcing

**Comment by tanzoniteblack** [comment]
@quad5 , is there a reason you couldn't use `scrollIntoView().click()` instead of `.click({force: true})`?

**Comment by jennifer-shehane** [comment]
Yah, I think there is something about the code of the component that will not work when the checks are skipped. If you need to scroll to have the elements visible, I'd suggest using `scrollIntoView` or `scrollTo` commands.
