### ISSUE TITLE
Cypress Github Integration Issue: Cypress Bot not commenting when GitHub Repository is renamed after Integration

### ISSUE THREAD

**Issue by rojalbati** [cypress-io/cypress#9541]
### Cypress Bot does not comment when the project name is changed in Github
- Integrate Github Repository (cypressgithubintegration-) with Cypress
- Goto Github and rename the repository to cypressgithub
- Goto Cypress Project Setting and click Github Repository Dropdown 
- Observe that the Integrated Github Repository name does not update in the dropdown i.e it still shows cypressgithubintegration-
- Send a PR and observe that Cypress bot won't comment on the PR as well after the test is completed.
![Issue](https://user-images.githubusercontent.com/54777753/101319648-6b31cc00-388a-11eb-8dbf-9d728bf03ff4.jpg)

Well, I found a solution to this issue.
- Uninstalled Github from cypress project dashboard
- Re-install Github 
- Able to select the GitHub repository with an updated repository name i.e cypressgithub
- Now sending a PR, the cypress bot comments the test summary after the test is executed.

**Comment by jennifer-shehane** [comment]
I've asked our API team about this and will update this issue once I've heard back on this.

**Comment by jennifer-shehane** [comment]
There is a sync available from the GitHub integration settings that should be available to refresh this data, but the engineering team is looking into whether there may be an issue surrounding the sync.
