### ISSUE TITLE
cy.intercept does not handle response modification where only the header is modified (redirect)

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9555]
Cypress v6.1.0 (`develop` branch)

the following redirect test changes the redirect location header 

```js
it.only('stubs the redirect', () => {
  // stub the redirect call and once it returns from the server
  // verify the target location and then change it to a safe "/"
  cy.intercept('/getout', (req) => {
    req.reply((res) => {
      expect(res.statusCode).to.equal(302)
      // the server wants to redirect us to another domain
      expect(res.headers).to.have.property('location', 'https://www.cypress.io')
      res.headers.location = '/'
      // need to provide something for the updated "res"
      // object to be used
      // res.send('stay here')
      // res.send()
    })
  })

  cy.get('#getout').click()
  cy.location('pathname').should('equal', '/') // redirect worked
})
```

## Reproduction

Branch `6.1.0` of https://github.com/cypress-io/cypress-example-recipes from https://github.com/cypress-io/cypress-example-recipes/pull/598 recipe examples/stubbing-spying__intercept spec file cypress/integration/redirect-spec.js

- install dependencies
- `cd examples/stubbing-spying__intercept`
- `npm start`

Now run Cypress with `npm run cypress:open` and pick the redirect spec

Without `res.send` or with `res.send()` the changed reply is not working

<img width="1276" alt="Screen Shot 2020-12-07 at 4 52 47 PM" src="https://user-images.githubusercontent.com/2212006/101410362-36833c00-38ad-11eb-8f44-2e77ce99e5d5.png">

With `res.send('stay here')` the updated location is working and we get redirected to `/`

<img width="934" alt="Screen Shot 2020-12-07 at 4 52 25 PM" src="https://user-images.githubusercontent.com/2212006/101410409-49960c00-38ad-11eb-8e3a-edb3597874d3.png">

I believe it should NOT be necessary to do `res.send` - the modified response header should be enough

**Comment by jennifer-shehane** [comment]
I can still recreate this issue in 6.3.0 as described above.
