### ISSUE TITLE
Cypress slows down very quickly

### ISSUE THREAD

**Issue by yourpchelp** [cypress-io/cypress#9561]
### Current behavior
When a test repeats the same action many times (about 200), Cypress slows down very quickly.
During first 15-20 iterations, the text is typed quickly enough.
At last iterations, a text is typed very slow.

### Desired behavior
Performance of text typing should be the same during  the test running.

### Test code to reproduce
1. Create this test file (e.g. test1_spec.js)

```js
describe('tests', () => {  
    before(() => {
        cy.visit('https://www.google.com');
        cy.viewport(screen.availWidth, screen.availHeight);
    })

    it('test', () => {
	for (let i = 0; i < 200; i++) {
		// type 'Hello World!' in search field
    	    	cy.get('.gLFyf.gsfi').clear().type('Hello World!');
	}
    })
})

```
2. open Cypress:
$(npm bin)/cypress open

3. run the test

### Versions
6.14.5

**Comment by bahunov** [comment]
Will it help to set numTestsKeptInMemory to 0?

**Comment by yourpchelp** [comment]
I tried "numTestsKeptInMemory": 0.
Test works a bit faster at the beginning.
But even in above simple test you can see, that Cypress slows down.
The performance problem still exists.

As a workaround, I use `.invoke('val', 'any text')` instead of `.type('any text')`.

**Comment by jmorgannht** [comment]
I am seeing similar issues where we have a single long running test that iterates over several lists.  It is not practical to split up the test, but there is a real decay in the performance when I am running headlessly.  Also seen in the GUI, but expected there.  

It is not greatly increasing memory usage during the run
numTestsKeptInMemory set to 0. 
I profiled all the command execution times and nothing sticks out as unusual.

Same set of actions:
1st iteration- 20 secs
2nd- 40 secs
3rd- 54 secs
4th- 70 secs
5th- 85 secs
By the 20th iteration it is taking over 250 secs per set of actions.  

Is there any way to avoid the bog down?  This is seen on 6.6.0 and 6.1.0.  There is no typing, just reading values and asserts. Running out of ideas to try.

**Comment by jmorgannht** [comment]
After a bit more poking around, this is the only workaround that seems to work.  
If I do all the actions in 1 spec file, 1 test, it is taking 7min 37 secs.
If I chop up the test into 1 spec, but 2 tests, I am seeing a dramatic increase in speed.  All I do in the first test is login, and then the other 99% of work was pushed to the second test.  This is cutting the run time to below 1 min.
