### ISSUE TITLE
Can't fake webcam video

### ISSUE THREAD

**Issue by thisismydesign** [cypress-io/cypress#9562]
### Current behavior

I'm on Linux, looking at https://docs.cypress.io/api/plugins/browser-launch-api.html#Use-fake-video-for-webcam-testing and https://github.com/cypress-io/cypress/issues/2704.

Can't get a fake video working. On `electron 87` it shows the default green screen, on chrome 87 and chromium 87 I get `Requested device not found`.

### Desired behavior

Fake video as described in https://docs.cypress.io/api/plugins/browser-launch-api.html#Use-fake-video-for-webcam-testing

### Test code to reproduce

`plugins/index.js`
```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    launchOptions.args.push('--use-file-for-fake-video-capture=cypress/fixtures/akiyo_cif.y4m')

    return launchOptions
  });
}
```

Also tried adding these 2 lines (from older comments):
```
launchOptions.args.push('--use-fake-ui-for-media-stream')
launchOptions.args.push('--use-fake-device-for-media-stream')
```

### Versions

`cypress 6.0.1`
browsers 87

**Comment by thisismydesign** [comment]
I checked `chrom://version` to see that the flags are indeed provided.

In the end it worked using an `mjpeg` file using `--use-file-for-fake-video-capture` and a simple relative path, so:
```
launchOptions.args.push('--use-file-for-fake-video-capture=cypress/fixtures/video.mjpeg')
```

See also https://stackoverflow.com/a/52188760/2771889

Could you clarify what the issue is `y4m` or update the docs to use `mjpeg`?

**Comment by jennifer-shehane** [comment]
I think there might be some weirdness in the `y4m` file Chrome requires. https://testrtc.com/y4m-video-chrome/ I'm not necessarily sure this is related to Cypress specifically.

**Comment by bharatentropik** [comment]
Mac OS  BigSur- 11.1 (20C69)
Chrome -91
Can't get a fake video working
I have tried all combinations.

**Comment by hamza-amami** [comment]
had the same issue, the problem is `cypress/fixtures/video.mjpeg`, you need to specify the full url, which kind of a bug since if you'll integrate your script in other servers, it won't run fyi @jennifer-shehane
