### ISSUE TITLE
webpack-preprocessor: types `Options` and `FilePreprocessor` are no longer exported

### ISSUE THREAD

**Issue by samijaber** [cypress-io/cypress#9569]
### Current behavior

No types are exported from the `@cypress/webpack-preprocessor` package.

### Desired behavior
Be able to import the argument types to annotate the object correctly in `cypress/plugins/index.js`

### Test code to reproduce

```js
// cypress/plugins/index.js
const webpackPreprocessor = require('@cypress/webpack-preprocessor');

/** @type {Cypress.PluginConfig} */
module.exports = (on, config) => {
  /** @type {webpackPreprocessor.Options} */
  const options = {
    webpackOptions: {
      resolve: {
        plugins: [],
      },
  };

  on('file:preprocessor', webpackPreprocessor(options));

  return config
}
```

### Versions

Regression from https://github.com/cypress-io/cypress-webpack-preprocessor/pull/83/files (merged in 5.2.1)

**Comment by sainthkh** [comment]
If you're using `js` file, add `/// <reference types="@cypress/webpack-preprocessor" />` at the top. 
If you're using `ts` file, change `require` to `import`.

Then, it would work like below:

![Peek 2021-07-05 15-48](https://user-images.githubusercontent.com/8130013/124429259-9b9e0200-dda8-11eb-87aa-021738270359.gif)

**Comment by sainthkh** [comment]
Closing because of the inactivity. If the problem continues to happen, please open a new issue with a reproducible example.
