### ISSUE TITLE
Seeing Memory Leak of 'Electron' group for Cypress Tests

### ISSUE THREAD

**Issue by JimLynchCodes** [cypress-io/cypress#9573]
Hi!

I'm using cypress basically for web-scraping some data off different pages of a website. 

I noticed that the amount of memory using constantly increases, even across multiple tests. 

my "run while showing memory usage" command looks like this:
```
"scrape:headless-show-memory": "concurrently \"npm run start:backend\" \"DEBUG=cypress:server:util:process_profiler cypress run --config video=false --spec ./cypress/integration/Triple-Trenders-Scraper/*.feature && exit 0\"",
```

I have included included `numTestsKeptInMemory: 0` in the `cypress.json`, and my full file looks like this:

```
{
  "testFiles": "**/*.feature",
  "baseUrl": "https://barchart.com",
  "env": {
    ...<some env vars here>
  },
  "pageLoadTimeout": 600000,
  "requestTimeout": 3600000,
  "responseTimeout": 3600000,
  "numTestsKeptInMemory": 0,
  "video": false
}
```

Initially, my memory output looks like this:
![Screen Shot 2020-12-08 at 1 59 44 PM](https://user-images.githubusercontent.com/5354163/101528057-c92ee400-395c-11eb-8be9-05fa2318441a.png)

By the end of all the tests running, it looks something like this:

![Screen Shot 2020-12-08 at 1 58 46 PM - end](https://user-images.githubusercontent.com/5354163/101528116-dba91d80-395c-11eb-930b-14fecc3c2723.png)

It's interesting to me that basically _ALL_ the additional memory used is being attributed to "Electron".

Can anyone help me understand what things contribute to "Electron" memory? If I have global javascript array with things being pushed into it, is that "Electron" memory?

Note: I am also using the "cucumber-js" plugin to allow my tests to be described as feature files and step definition files (possibly that could have something to do with the memory issues?).

Here are the versions of dependencies I am using. Running this on node v13.13.0
```js
"devDependencies": {
    "cypress": "^4.4.0",
    "cypress-cucumber-preprocessor": "^2.3.0",
    "node-cron": "^2.0.3"
  },
dependencies": {
    "concurrently": "^5.1.0"
  }
```

btw, the source code for my project can be found here: https://github.com/JimLynchCodes/Triple-Trenders

Thanks! ♥️

**Comment by jennifer-shehane** [comment]
If you're not passing a `--browser`, then the tests are running in the Electron browser that comes bundled with Cypress. So this is the browser memory used when running the test runner + your application. You could try running in Chrome to see if there's a difference. 

We've made some improvements to performance in more recent versions. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you.
