### ISSUE TITLE
Alias for intercept is not working if overwriting cy.intercept command

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9580]
Cypress v6.1.0

```js
describe('intercept', () => {
  Cypress.Commands.overwrite('intercept', (intercept, ...args) => {
    return cy.log('intercept!').then(() => {
      return intercept(...args)
    })
  })

  it('is registered too late', () => {
    cy.visit('/')
    cy.intercept('/todos').as('todos')
    cy.wait('@todos')
  })
})
```

The alias `todos` is not recognized, but the routes table is showing it

<img width="619" alt="Screen Shot 2020-12-08 at 9 35 57 PM" src="https://user-images.githubusercontent.com/2212006/101566668-5db93680-399d-11eb-8c84-80e88dd2990f.png">

Note: even putting `cy.wait` into `cy.then` does not solve it - something is really off about this alias.

**Comment by bahmutov** [comment]
Similar issue https://github.com/cypress-io/cypress/issues/3890

Another note: using `function` instead of arrow functions does not resolve the problem

**Comment by jennifer-shehane** [comment]
I think this may be related to this issue? Not sure. https://github.com/cypress-io/cypress/issues/5101

**Comment by bahmutov** [comment]
Ughh, it does not "understand" that the command returns an XHR request

```js
Cypress.Commands.overwrite('intercept', function (intercept, ...args) {
  return cy.log('intercept!').then(function () {
    return intercept(...args)
  })
})
cy.intercept('/foo', 'my value').as('netAlias')
cy.wait('@netAlias')
```

<img width="802" alt="Screen Shot 2020-12-09 at 12 28 48 PM" src="https://user-images.githubusercontent.com/2212006/101664991-787dc080-3a1a-11eb-9ae6-d650c5f23d52.png">
