### ISSUE TITLE
401:Unauthorized is taken while token is gotten succesfully

### ISSUE THREAD

**Issue by muratozcelikusa** [cypress-io/cypress#9581]
Hi 
I am trying to API test using cypress. I can get token but could not use it correcty.

**Custom command for token:**
```js
Cypress.Commands.add('getToken', () => {
  Cypress.log({
    name: 'tokeniscorrect',
  });

  const options = {
    method: 'POST',
    url: "url/token",
    body: {
      token_name: "xxx",
      grant_type: 'client_credentials',
      client_id: "xxxx",
      client_secret: "yyy",
    },
    headers: {
     'Content-Type': 'application/x-www-form-urlencoded'
    }
  };
  cy.request(options).then(resp => {
    localStorage.setItem("token", resp.body.access_token);
    return resp.body.access_token;
  });
```
**test** 
```js
describe('login', () => {
    it('should successfully log into our app', () => {
      cy.getToken()
        .then((resp) => {
          return resp.body;
        })
        .then((body) => {
          var token = JSON.stringify(body)
          cy.saveLocalStorage();
          cy.getLocalStorage("token").should("exist");   // here is good and token is available


const options = {
          method: 'POST',
          url: "my url ",         
          body: {
                  cardnum: "1234566789",
                  CVV:'11',
          },
          headers: {
            Authorization: `Bearer ${token}`,  //
            'Content-Type': 'application/x-www-form-urlencoded'
          },
         
        };
        cy.request(options).then(resp => {
          cy.log(JSON.stringify(resp))
        });
    });
  
  });
```

**Comment by jennifer-shehane** [comment]
When opening a pull request in the future, please fill out the [pull request template](https://github.com/cypress-io/cypress/blob/develop/PULL_REQUEST_TEMPLATE.md) provided - it requires necessary information we need to move forward with reviewing pull requests. 

Could you be more specific about what is not working correctly, I see this line that says the token is available fine. 

```js
cy.getLocalStorage("token").should("exist");   // here is good and token is available
```

Also what version of Cypress you are using. 

You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions).

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
