### ISSUE TITLE
'autoEnd' does not exist in type 'Partial<LogConfig>'

### ISSUE THREAD

**Issue by mccataldo** [cypress-io/cypress#9590]
Doing this:
```js
// @ts-check
function someFn() {
  const log = Cypress.log({ autoEnd: false })
}
```
...results in this:
```js
Argument of type '{ displayName: string; message: string; autoEnd: boolean; }' is not assignable to parameter of type 'Partial<LogConfig>'.
  Object literal may only specify known properties, and 'autoEnd' does not exist in type 'Partial<LogConfig>'.
```

**Comment by jennifer-shehane** [comment]
Yes, this appears to be missing. Feel free to open a PR. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by samueloakley** [comment]
@jennifer-shehane Looks like this is also missing from the API docs.
https://docs.cypress.io/api/cypress-api/cypress-log.html#Arguments
Is `autoEnd` documented somewhere else?

**Comment by jennifer-shehane** [comment]
No, I only found it used in our actual codebase.

**Comment by linkel** [comment]
I have created a PR to add the type, hope that's alright: #14220
