### ISSUE TITLE
XHR requests are not stubbed with `intercept` when server isn't running

### ISSUE THREAD

**Issue by maximedupre** [cypress-io/cypress#9599]
### Current behavior
[I posted this problem on gitter and another user (@genughaben_gitlab) confirmed he also has this problem.](https://gitter.im/cypress-io/cypress?at=5fcfded90d0bd11d72934570)

I want to stub my local REST API to test my front end in insolation. When the REST API is turned on, everything works as expected - the XHR are stubbed. When my REST API is turned off, the XHR fail and are not stubbed.

For example, here's what happens when my API is not started:

![Screen Shot 2020-12-09 at 2 20 12 PM](https://user-images.githubusercontent.com/5158181/101676909-d4037a80-3a29-11eb-9b1a-6e0fab39c2a5.png)
![Screen Shot 2020-12-09 at 2 25 51 PM](https://user-images.githubusercontent.com/5158181/101677433-92270400-3a2a-11eb-835c-399631d1fb71.png)
![Screen Shot 2020-12-09 at 2 26 29 PM](https://user-images.githubusercontent.com/5158181/101677442-9521f480-3a2a-11eb-9a6c-349db9b5f5d2.png)

And here's what happens when I simply turn on my API and re-run the tests:

![Screen Shot 2020-12-09 at 2 23 53 PM](https://user-images.githubusercontent.com/5158181/101677196-36f51180-3a2a-11eb-935f-e7cc08951591.png)

### Desired behavior
My server should not be started for XHR stubs to work

### Test code to reproduce
Unable to provide a repro, but here is test code for the test shown in the screenshot

```js
describe('Project page', () => {
    beforeEach(() => {
        helper.login(1);
    });

    describe('when the play button is clicked', () => {
        describe('when the stop button is clicked', () => {
            it.only('should stop the project', () => {
                defaultIntercepts();
                cy.visit('https://localhost:4200/projects/1');

                cy.get('#play-button').click();
                cy.get('#stop-button').click();

                const playheadLeftPosObj = { pos: 0 };

                setInitialPlayheadLeftPos(playheadLeftPosObj);
                cy.get('#playhead').should(($el: any) => {
                    expect($el[0].getBoundingClientRect().left).to.equal(
                        playheadLeftPosObj.pos
                    );
                });
            });
        });
    });
});

function defaultIntercepts() {
    cy.intercept('GET', '/users/1', {
        id: 1
    });
    cy.intercept(
        'GET',
        '/projects/1?used-space-wavs-and-videos',
        createProjectFixtures({})
    );
    cy.intercept('GET', '/projects/1/tracks', []);
    cy.intercept('GET', '/projects/1/files?is-consolidation', []);
}
```

### Versions
This issue did not occur with `cy.route`.

Cypress version: 6.1
Chrome version: Version 87.0.4280.67 (Official Build) (x86_64)
OS version: mac os 10.15.7

**Comment by bahmutov** [comment]
Can you give intercepts aliases so you can see which ones are actually intercepted?

**Comment by maximedupre** [comment]
Here is the result with aliases and my API turned on:
![Screen Shot 2020-12-09 at 2 54 45 PM](https://user-images.githubusercontent.com/5158181/101680345-8ccbb880-3a2e-11eb-95a8-39a2383e41e4.png)

**Comment by bahmutov** [comment]
could you screenshot when the API is off?

**Comment by maximedupre** [comment]
Same as in my first post:
![Screen Shot 2020-12-09 at 3 05 50 PM](https://user-images.githubusercontent.com/5158181/101681370-0b752580-3a30-11eb-8b0f-21713f2e6bd9.png)
![Screen Shot 2020-12-09 at 3 06 42 PM](https://user-images.githubusercontent.com/5158181/101681470-2e9fd500-3a30-11eb-8b8c-c9be9fb28568.png)

**Comment by bahmutov** [comment]
Hmm, in https://github.com/cypress-io/cypress-example-recipes/pull/606 I am stubbing the second API endpoint that does not exist, but it works fine. Are your requests going to the right port? I see a mixture of 4200 and 3030. Is this app public or could you create a public reproduction?

**Comment by maximedupre** [comment]
Requests are going to the right ports. API is at http://localhost:3030 and front-end is at https://localhost:4200. Unfortunately this isn't a public app and I don't have the time right now to do a repro.

I just tried "http://localhost:4200" (instead of https, to make both the api and front end http), but same problem.

![Screen Shot 2020-12-09 at 3 34 26 PM](https://user-images.githubusercontent.com/5158181/101684198-0a45f780-3a34-11eb-8263-7955a6ddd726.png)

**Comment by tgugli** [comment]
This looks very similar to the issue that I just posted: https://github.com/cypress-io/cypress/issues/9602

**Comment by katia-aa** [comment]
Having the same issue here with `intercept`. The api I'm trying to intercept is behind a proxy. When I turn off my VPN, the test fails. When I turn my VPN back on, it passes.

**Comment by kunalnagar** [comment]
Hey guys - do you think the problem may be related to pattern matching of the URL on `cy.intercept`? In my particular scenario, if I use:

```
// WORKS
cy.server()
cy.route('**/v1/answers**', 'fixture:answers.json')
```

![image](https://user-images.githubusercontent.com/2741371/101714980-a12ca700-3a68-11eb-9265-8b443743a4fb.png)

```
// DOES NOT WORK
cy.intercept('GET', '**/v1/answers**', { fixture: 'answers.json' })
```

![image](https://user-images.githubusercontent.com/2741371/101715037-b86b9480-3a68-11eb-896b-f6f5636240d6.png)

**Comment by bahmutov** [comment]
We believe this problem is related to the OPTIONS call that happens before the actual call cross domain

**Comment by maximedupre** [comment]
I do see a failed OPTIONS request for each failed GET request

![Screen Shot 2020-12-10 at 10 07 30 AM](https://user-images.githubusercontent.com/5158181/101789755-a83ad000-3acf-11eb-902a-f6582bd049b8.png)

**Comment by rhogeranacleto** [comment]
I have the same problem. My `intercept` stubs only work if my local server is running, otherwise, it fails.

**Comment by katia-aa** [comment]
I've spotted a failed OPTIONS request as well
