### ISSUE TITLE
Improve assertion matching message to when array in subject

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#96]
The assertion message for matching can be confusing when there is a match for an element that is not the first element of the array in the subject.

```javascript
cy.get('.traversal-cite').parents().should('match', 'blockquote')
```

**Command Line**
![screen shot 2016-02-05 at 11 09 37 am](https://cloud.githubusercontent.com/assets/1271364/12852043/0ea6f722-cbfb-11e5-9cc5-94a5dc530b33.png)

**Console Log**
![screen shot 2016-02-05 at 11 10 02 am](https://cloud.githubusercontent.com/assets/1271364/12852044/122f1816-cbfb-11e5-9a59-fc48cced8c6e.png)

**Suggested Wording**
`expected [<footer>, ...] to match blockquote`

**Comment by brian-mann** [comment]
Fixed in [`0.14.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0140-03082016).
