### ISSUE TITLE
Error when running 'npx cypress open'

### ISSUE THREAD

**Issue by LiamJones-87** [cypress-io/cypress#9608]
Hi,

When I'm running 'npx cypress open' I get the following error:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cypess - Not found
npm ERR! 404
npm ERR! 404  'cypess@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lijones\AppData\Roaming\npm-cache\_logs\2020-12-10T09_16_41_554Z-debug.log
Install for [ 'cypess@latest' ] failed with code 1

This has been working previously, nothing has changes in my repo - I just tried to open it this morning and I get this failure. Cypress v.5.6.0

**Comment by samueloakley** [comment]
Hi, looking at your error message it looks like you've mistyped the command with _cypess_ instead of _cypress_. Try making sure your command is definitely `npx cypress open`.

**Comment by LiamJones-87** [comment]
@samueloakley Wow - really sorry for wasting your time, it's been a long week. I looked at it so many time but just didn't see the missing 'r'. Thank you for point it out, much appreciated.
