### ISSUE TITLE
Unable to stub PUT request with intercept

### ISSUE THREAD

**Issue by FrancoisCamus** [cypress-io/cypress#9609]
### Current behavior
I'm unable to stub a PUT request with cy.intercept(). The original http call is made instead of returning the stub. I'm using cy.route() instead which works fine.

In my test, I'm first stubbing a GET request with cy.intercept() then stubbing a PUT request after a click event on a DOM element. I current have to use cy.route() for the second stubbing.

### Desired behavior

I'd like to use cy.intercept() for all my stubs setup instead of cy.route().

### Test code to reproduce

```typescript
describe('App tests', () => {
  it('successfully loads element', () => {
    // Arrange
    cy.intercept('GET', '/api/schemas', {
      statusCode: 200,
      body: {} // some data to return
    });

    // This code doesn't work
    // cy.intercept('PUT', '/api/search', {
    //   statusCode: 200,
    //   body: {} // some data to return
    // }).as('search');

    // This code works
    cy.server();
    cy.route(
      'PUT',
      '/api/search',
      {} // some data to return
    ).as('search');

    cy.visit('/');

    // Act
    cy.get('.selector').click();

    // Assert
    cy.wait('@search');
    cy.get('table tr:first-child td').eq(0).should('contain', 'some value');
  });
});
```

### Versions

Cypress version: 6.1.0
Browser: Chrome 86
OS: Windows 10

**Comment by bahmutov** [comment]
Can you open the DevTools Network tab and see if there are any failing requests there like OPTIONS for example before the Ajax requests that you stub?

**Comment by FrancoisCamus** [comment]
Hi!
Actually 2 requests are made instead of just 1:

1st call:

![first_call](https://user-images.githubusercontent.com/7439901/101886377-ab02f700-3b9b-11eb-989f-dc1241d51d2b.PNG)

2nd call:
![second_call](https://user-images.githubusercontent.com/7439901/101886396-b2c29b80-3b9b-11eb-807f-a97bdf83b11f.PNG)

But if I start my rest api server then I get an OPTIONS request in the second call:

1st call:
![first_call_server_on](https://user-images.githubusercontent.com/7439901/101886447-c7069880-3b9b-11eb-83f3-ad02a942f723.PNG)

2nd call:
![second_call_server_on](https://user-images.githubusercontent.com/7439901/101886463-cec63d00-3b9b-11eb-9091-53df5a69bbfb.PNG)

Hope this helps

**Comment by FrancoisCamus** [comment]
I've just upgraded to 6.2.1 and now the first intercept call works as expected. But if I do another intercept for the same action and alias but with different response body then the first intercept setup body is returned.
Should I create another issue and close this one?

**Comment by jennifer-shehane** [comment]
@FrancoisCamus Yes please. I do think your original issue was fixed.
