### ISSUE TITLE
`Stop` and `Run all tests` button in UI should have distinguished positions

### ISSUE THREAD

**Issue by johanbook** [cypress-io/cypress#9610]
### Current behavior

`Stop` and `Run all tests` buttons in the Cyppres test UI have same the same position, which occasionally can cause miss-clicks.
 
My main issue is that is when watching browser console logs during a test and attempting to stop the test when encountering interesting logs. If the test finishes prematurely (error or remaining tests are skipped) clicking the button instead reruns the test, which is mildly frustrating.

### Desired behavior

The buttons should have distinction positions and instead be disabled when not applicable.
### Versions

Cypress 6.1.0

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like.  I would suggest using the keyboard shortcuts for 'Run all tests' and 'Stop'. This will be faster and ensure you don't click the wrong one. 

<img width="161" alt="Screen Shot 2020-12-10 at 5 32 29 PM" src="https://user-images.githubusercontent.com/1271364/101764016-f53d9700-3b0d-11eb-9bb1-92c1e49b8cc9.png">

<img width="122" alt="Screen Shot 2020-12-10 at 5 31 22 PM" src="https://user-images.githubusercontent.com/1271364/101764013-f373d380-3b0d-11eb-8501-f948054c1c16.png">

Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
