### ISSUE TITLE
MacOs Catalina 10.15.7 - Module parse failed: acornParser.parse is not a function

### ISSUE THREAD

**Issue by VaclovasVicius** [cypress-io/cypress#9611]
### Current behavior
When running a cypress script, in typescript, we are getting:
```
Error: Webpack Compilation Error
./cypress/integration/carousel.spec.ts
Module parse failed: acornParser.parse is not a function
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
TypeError: acornParser.parse is not a function
```
This only can be reproduced on MacOS Catalina 10.15.7

### Desired behavior
Test case runs succesfully.
### Versions
6.0.0+

**Comment by bahmutov** [comment]
We would need more details to debug this issue. Can you open the browser's DevTools Console and see if there are any errors? Are there any errors in the terminal? Can you try writing your spec using JavaScript to see if it works?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
