### ISSUE TITLE
Website is not loading contents in cypress

### ISSUE THREAD

**Issue by kabrawalak** [cypress-io/cypress#9614]
### Current behavior

The website I am testing is able to work perfectly fine in chrome manually. But in cypress automation, after logging in - the modules are not visible thus its fails to click. I have tried cy.reload(), cy.clearCookies(), cy.viewport() but non of them resolve the problem. Organization do not use VPN or proxy for this website. Website is accessible from any device & any location.

![qq](https://user-images.githubusercontent.com/11547191/101782598-36f71f00-3ac7-11eb-83fa-123208e9425c.png)

### Desired behavior

I must see all of these modules when I access the site via cypress.

![q](https://user-images.githubusercontent.com/11547191/101782638-44140e00-3ac7-11eb-8b7d-b600e5ad05fc.png)

### Test code to reproduce

Login to the website as a valid user, it must display all modules. It's not being displayed. It seems to be blocked by cypress.
### Versions

6.1.0

**Comment by bahmutov** [comment]
Can you open the browser's DevTools and see if there are any error messages?

**Comment by kabrawalak** [comment]
Attached is the screenshot DevTools console, Chrome incognito vs Cypress.
![3](https://user-images.githubusercontent.com/11547191/101942120-068eae00-3bb7-11eb-96f9-35f66fb58505.PNG)
![4](https://user-images.githubusercontent.com/11547191/101942122-07bfdb00-3bb7-11eb-93f9-3a13dfff0ddd.PNG)

**Comment by jennifer-shehane** [comment]
Your application may be using "frame busting". By default Cypress modifies code it detects as frame busting so the application under test runs properly in the Cypress Test Runner (which runs your app inside an iframe itself). Can you try disabling this by setting `modifyObstructiveCode=false` in your configuration? Further explanation can be found here: https://on.cypress.io/configuration#modifyObstructiveCode

**Comment by krathina** [comment]
I was facing the same issue in my application that a part of the app was not loading which was written in iframe. Adding `modifyObstructiveCode=false` in the configuration has fixed the issue now and the tests are starting running successfully now.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by phaniyt** [comment]
Hi, How to fix problem when page is loaded, but not displayed? I have started using cypress to automate UI test cases for our health emr and, I wrote a simple script to login. But when the login click action is done, page is loaded but not displayed. I try to set up "modifyObstructiveCode": false in the cypress.json but it doesn't solve the issue. Any suggestions/Thoughts? I really apricate your help.

**Comment by sushobhanworld** [comment]
@krathina - I am facing similar issue as you mentioned. But setting up "modifyObstructiveCode": false in the cypress.json doesn't solve. It says No Test case to run.
Can you please help me here ?

**Comment by sushobhanworld** [comment]
@kabrawalak - I am facing the exact same issue. Ho did you fix the issue you facing here?

**Comment by adisatriap** [comment]
i have same issue, when using beforeEach the page can load but when not use beforeEach the page blank

**Comment by abrilmaestre** [comment]
I had the same issue. I fixed it adding a before() with this content:
![image](https://github.com/cypress-io/cypress/assets/83642384/c7863f0e-10b8-46cb-941e-e5625560bd17)

**Comment by ebrarilhan** [comment]
> Hi, How to fix problem when page is loaded, but not displayed? I have started using cypress to automate UI test cases for our health emr and, I wrote a simple script to login. But when the login click action is done, page is loaded but not displayed. I try to set up "modifyObstructiveCode": false in the cypress.json but it doesn't solve the issue. Any suggestions/Thoughts? I really apricate your help.

i have same issue how can u fixxed?

**Comment by BudarpuMadhusudhan** [comment]
I am facing the same issue, can anyone help me out please ,Thank you
