### ISSUE TITLE
Cypress could not connect to Firefox. `Error: cannot open socket` displayed at beginning of running spec

### ISSUE THREAD

**Issue by G0lang** [cypress-io/cypress#9621]
When running cypress with options '--headless --browser firefox', cypress halts at the start of the second spec with message:
```
Cypress could not connect to Firefox.

An unexpected error was received from Marionette connection:

Error: cannot open socket

To avoid this error, ensure sure that there are no other instances of Firefox launched by Cypress running.
```

This blocks running all specs in 'run' mode

it seems this problem resolved just for windows platform at #6392 but we experience same via docker and Linux.

**Comment by Narretz** [comment]
You probably should provide the versions of Cypress and Firefox (try latest if possible).

**Comment by jennifer-shehane** [comment]
Yes, please provide Cypress version, Firefox version and the environment details of your run including OS.

**Comment by G0lang** [comment]
@jennifer-shehane @Narretz 

cypress version: 5.5.0
FIREFOX_VERSION=82.0.3
Docker base image: node:14.15.1-buster which is Debian 10.6

We ran our test in parallel via 20 containers and we have around 150 specs via 700 tests. 
we understand during each test Firefox close and open before each spec which is 150 times across the 20 containers and only one time this issue happened in some test runs which means very rare issue but still makes 25% of our total runs failed because of this issue.

**Comment by G0lang** [comment]
for sure this issue not catch able via your test which in run very few tests and specs and way different than scale we use. 
I have to mention we had socket error issue even before via CentOS docker base image and chrome multiple versions which makes me believe should be some problem in cypress side. 
issues like #8986 , #8674, # #8986 and lot more if needs to be reference.

**Comment by G0lang** [comment]
Another suggestion for case like this, as we use cypress in parallel mode in CI, cypress could have some recovery method(like flaky test) since we have available machine to handle the tests and not return error(which is make any CI failed) if could not connect to Firefox.
