### ISSUE TITLE
before all hooks being called before anything else when all spec files are run sequentially

### ISSUE THREAD

**Issue by akdiam** [cypress-io/cypress#9622]
### Current behavior
I currently have a before all hook at the beginning of each of my spec files, and when i run each spec file individually everything works as expected. However, when I click 'Run x integration specs' on the top right of the Cypress GUI, it seems all of the 'before all' hooks run sequentially, rather than only running within their specific spec files. 

### Desired behavior
I'd like it so that the 'before all' hooks only run within the scope of their spec files, and not all at once/sequentially before any of the actual content of each spec file is run. 

### Test code to reproduce
```
before(() => {
    cy.visit('https://www.google.com');
});

describe('tests for error', () => {
    it('test', () => {
        cy.contains('Google');
    });
});
```

Copy this code into two separate files and run them using the 'Run 2 integration specs' button on the top right of the Cypress GUI. You should see two before all statements before either of the 'contains' commands run.

### Versions
6.1.0
****

**Comment by bahmutov** [comment]
It is expected - since when running all specs together, they are concatenated into a single "spec", read https://glebbahmutov.com/blog/run-all-specs/

I suggest you create a top-level `describe` block in each spec and place the `before` hook inside, like described in https://glebbahmutov.com/blog/run-all-specs/#solution

**Comment by akdiam** [comment]
Thank you for the explanation, everything makes sense and works as expected now.
