### ISSUE TITLE
Good Evening, issue with Dashboard configuration on .gitlab-ci.yml file

### ISSUE THREAD

**Issue by vaibhavi789** [cypress-io/cypress#9628]

**Comment by vaibhavi789** [comment]
<img width="1109" alt="Screenshot 2020-12-10 at 21 16 26" src="https://user-images.githubusercontent.com/58173901/101832596-9b4dc900-3b2f-11eb-9382-5632352154f8.png">

$ sed -ie "s/api.cypress.io/${SORRY_CYPRESS_DIRECTOR_URL}/g" "${CYPRESS_CONFIG_FILE_PATH}/app.yml"
sed: can't read /builds/jasolia1/vm-cfrontend/cache/Cypress/6.1.0/Cypress/resources/app/packages/server/config/app.yml: No such file or directory

**Comment by Narretz** [comment]
You should really follow the bug report template when opening an issue. It exists for a reason.

**Comment by vaibhavi789** [comment]
okay.. What is the solution

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
