### ISSUE TITLE
Command never runs, doesn't fail, and returns some meta data instead 

### ISSUE THREAD

**Issue by george-norris-salesforce** [cypress-io/cypress#9629]
**DEFINE COMMAND**
```js
Cypress.Commands.add('getLocalStorage', () => {
  const state = window.localStorage.getItem('state');
  return JSON.parse(state);
});

```

**USE COMMAND**

```js
const localState = cy.getLocalStorage();
```

**RESULT**

localState variable holds this value:

```
chainerId: "chainer6"
firstCall: false
specWindow: Window {parent: global, opener: null, top: global, length: 0, frames: Window, …}
useInitialStack: false
userInvocationStack: " ......"
```

**_Using version 5.5.0_**

[SO question](https://stackoverflow.com/questions/65243033/cypress-command-never-runs-doesnt-fail-and-returns-some-meta-data-instead)

**Comment by Narretz** [comment]
Custom commands are async, same as other Cypress commands, regardless of return value. Have your tried:
````cy.getLocalStorage().then(result => {
  console.log(result);
});
```

If this wasn't the case you couldn't do chaining with custom commands.

**Comment by jennifer-shehane** [comment]
As @Narretz mentioned, the command is async and not assignable in this manner. I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).

Your value will be accessible through a thenable or assignable to an alias. 

```js
Cypress.Commands.add('getLocalStorage', () => {
  const state = window.localStorage.getItem('state');
  return JSON.parse(state);
});

it('test', () => {
  cy.getLocalStorage().then(result => {
    console.log(result);
  });
})
```
