### ISSUE TITLE
Migrated to cy.intercept, but need headers on every request now, because of CORS.

### ISSUE THREAD

**Issue by idxrx** [cypress-io/cypress#9642]
I migrated to cy.intercept, but have to add headers on every request now, because of CORS.

 // old code
 // cy.server();
 // cy.route('api/Settings/BuildInformation', 'fixture:Navigation/Settings/buildversion.json').as('buildversion');

// new code
    cy.intercept('api/Settings/BuildInformation', {
      **headers: { 'access-control-allow-origin': 'http://localhost:4200', 'Access-Control-Allow-Credentials': 'true' },**
      fixture: 'Navigation/Settings/buildversion'
    }).as('buildversion');

### What would you like?
It should be nice if you can add this headers at one place (like in an interceptor), instead of adding this headers line on every request.
And it is also impossible to use a feature file for headers.
header.json
_{
    "access-control-allow-origin": "http://localhost:4200",
    "Access-Control-Allow-Credentials": "true"
}_

Code would then be:
cy.intercept('api/Settings/BuildInformation', {
      **headers: header,**
      fixture: 'Navigation/Settings/buildversion'
    }).as('buildversion');

### Why is this needed?
Less double code in Cypress tests.

**Comment by bahmutov** [comment]
I think a better and immediate way to do this similar to what you have shown is to use the plain JavaScript helper method.

```js
context('common headers', () => {
  // let's say that every intercept needs the same headers in the response
  const headers = {
    'access-control-allow-origin': Cypress.config('baseUrl'),
    'Access-Control-Allow-Credentials': 'true'
  }

  const mergeResponse = (options = {}) => {
    return Object.assign({}, { headers }, options)
  }

  it('stubs several requests and has the headers', () => {
    // the initial list of todo items
    cy.intercept(
      'GET',
      '/todos',
      mergeResponse({ fixture: 'two-items.json' })
    ).as('todos')
    cy.visit('/')
    cy.get('.todo').should('have.length', 2)
    cy.wait('@todos')
      .its('response.headers')
      .should('include', headers) // our headers are present on the response

    // let's stub posting a new item
    cy.intercept('POST', '/todos', mergeResponse({ body: {} })).as('newTodo')
    cy.get('.new-todo').type('new item{enter}')
    cy.wait('@newTodo')
      .its('response.headers')
      .should('include', headers) // our headers are present on the response
  })
})
```

If you inspect the Network panel you will see that every response includes your headers

<img width="1276" alt="Screen Shot 2020-12-11 at 9 20 02 AM" src="https://user-images.githubusercontent.com/2212006/101914371-3c6d6b80-3b92-11eb-8706-cf502dfc8501.png">
