### ISSUE TITLE
Error when passing scrollBehavior as TestConfig

### ISSUE THREAD

**Issue by pauwilk** [cypress-io/cypress#9643]
### Current behavior
on VS code I get an error:

Argument of type '{ scrollBehavior: string; }' is not assignable to parameter of type 'TestConfigOverrides'.
  Object literal may only specify known properties, and 'scrollBehavior' does not exist in type 'TestConfigOverrides'.ts

![image](https://user-images.githubusercontent.com/72187888/101909188-6ee08e00-3bbd-11eb-9183-6d39c558b887.png)

### Desired behavior
no types error, autocomplete should work as well for scrollBehavior

### Test code to reproduce
(write test in typescript)
```js
describe("Test", { scrollBehavior: "center" }, () => {
  beforeEach(() => {
    cy.reload();
  });

  cy.get("#test").click();
});
```

### Versions

cypress 6.1.0

**Comment by jennifer-shehane** [comment]
I opened a PR here to fix this: https://github.com/cypress-io/cypress/pull/14166
