### ISSUE TITLE
6.1.0 ignores base url config

### ISSUE THREAD

**Issue by poeti8** [cypress-io/cypress#9648]
### Current behavior
Passing `CYPRESS_BASE_URL` and `CYPRESS_baseUrl` doesn't change the base URL in Docker image `cypress/included:6.1.0`. I tried on local machine and still doesn't work. When I pass any value I always get the same error:

```
Cypress could not verify that this server is running:

  > http://localhost:3000

We are verifying this server because it has been configured as your `baseUrl`.
```

Doesn't work when I set in **cypress.json** either:
```
{
  "baseUrl": "http://localhost:3333"
}
```

But the same config works on `cypress/included:3.2.0` (which is used on Cypress' Docker documentations)

### Desired behavior
Be able to change the base URL.

### Test code to reproduce
```
docker run -it -v $PWD:/e2e -w /e2e -e CYPRESS_BASE_URL=http://host.docker.internal:3333 cypress/included:6.1.0
```

### Versions

cypress/included:6.1.0

**Comment by bahmutov** [comment]
You can see everything Cypress detects / parses by turning the debugging messages on, see https://github.com/cypress-io/cypress-docker-images/tree/master/included#debug

Are you sure the application IS running at that URL?

**Comment by poeti8** [comment]
Found what I did wrong, the env should have started with `REACT_APP_`. But curious how did this work on older versions... anyways, hope this issue helps my fellow confused devs in future.
