### ISSUE TITLE
Clean up style tags between tests

### ISSUE THREAD

**Issue by JessicaSachs** [cypress-io/cypress#9655]
Initially reported in cypress-io/cypress-vue-unit-test#309

Even though I destroy component after each test, the styles defined in mount are duplicated:

```js
const style = `
    .moveable {
      position: relative;
      width: 300px;
      height: 200px;
      text-align: center;
      font-size: 40px;
      margin: 0 auto;
    }`;

 // I call this function in every test (e.g.`it`)
 mount({
    template,
    data,
    components: {
      Moveable,
    },
  }, {
    style,
});
```
Results in:
![image](https://user-images.githubusercontent.com/2801156/82226691-d028d300-98f4-11ea-9a03-50adb609e86b.png)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
