### ISSUE TITLE
Feature Request: support hot reload for component instead of refresh the whole page

### ISSUE THREAD

**Issue by JimmyLv** [cypress-io/cypress#9659]
When editing component styling, could you please support hot reload for component instead of refreshing the whole page?

**Comment by lmiller1990** [comment]
Hi @JimmyLv!

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. Component testing is no longer experimental (but still in alpha, with lots of updates and improvements coming in the next few weeks). Please let us know if you find any more issues.

Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Changelog: https://docs.cypress.io/guides/references/changelog
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

The main difference is we moved from a `file:preprocessor` architecture to a dev-server architecture. Component testing is no longer experimental, and has a dedicated runner (which is build on top of an extends the existing cypress runner).

The new dev-server architecture means we (finally) support hot reload, things are nice and fast now.

Please update to 7.x (see links above). Let me know if you have any problems updating. I made a basic template anyone wants to try Cypress 7.x out now: https://github.com/lmiller1990/cypress-react-template. Note you need to run `yarn cypress open-ct` to launch the component testing + dev server runner.
