### ISSUE TITLE
An error cleaning iframe - probably ReactTooltip

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9669]
<img width="1278" alt="Screen Shot 2020-05-13 at 6 04 10 PM" src="https://user-images.githubusercontent.com/2212006/81870618-35bb3f00-9544-11ea-9a12-b58eca07188c.png">

In Happo visual testing PR https://github.com/bahmutov/cypress-react-unit-test/pull/205 if both tests run, the second test cannot clean the iframe. Seems the react tooltip component is inserting a weird child component that we don't remove correctly

**Comment by jennifer-shehane** [comment]
Closing as stale.
