### ISSUE TITLE
Cannot load webpack config when used with Yarn v2 PnP

### ISSUE THREAD

**Issue by huy-nguyen** [cypress-io/cypress#9670]
I created a minimal repro repo [here](https://github.com/huy-nguyen/temp-cypress-react-unit-test-error) with the repro steps in the README. Also, `webpack` should be listed as a peer dependency.

**Comment by jennifer-shehane** [comment]
Closing as stale. Please try component testing in Cypress 7.0 and reopen a new issue if Yann v2 PnP is still not working in that version.
