### ISSUE TITLE
Support Gatsby.js projects

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9671]
Need to find the Webpack to bundle Gatsby.js projects

**Comment by jennifer-shehane** [comment]
Closing as stale.

**Comment by shrop** [comment]
Would be great to support Gatsby projects. I talked to Gatsby and they have reported that some glue code would need to be added to a helper here at least - https://github.com/cypress-io/cypress/tree/develop/npm/webpack-dev-server/src/helpers. Any other places needed to implement Gatsby support?

Is this something the Cypress community is interested in doing? 

I am talking component testing more specifically. E2E testing works for my teams using Gatsby and Cypress.

**Comment by mike-plummer** [comment]
Hi @shrop , thanks for your interest in Cypress. As-is, any pure React components in your Gatsby project (doesn't use Gatsby APIs, components, or GQL interface) can be tested using Cypress Component Testing's "react" support, but for full integration with the Gatsby lifecycle & data layer you're correct that a new handler would be needed to teach Cypress how to bootstrap and supply those framework support items. Unfortunately there are just too many frontend frameworks for our small team to create & maintain support for, so there are no plans in the near future for us to add first-class Gatsby support.

The good news is that we recently launched support for [Third Party Framework Definitions](https://docs.cypress.io/guides/component-testing/third-party-definitions) so developers can easily add support for their framework of choice and provide it as a Cypress plugin for the community. Might this meet your need? I would recommend reaching out on [Discord](https://on.cypress.io/discord) (or even to the Gatsby team) to see if there are other developers interested in collaborating on creating one.

**Comment by shrop** [comment]
Thank you for the good advisement and next steps! This is helpful.
