### ISSUE TITLE
How to handle external React?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9677]
In some webpack configs, the React is set as an external NOT to be bundled https://github.com/bahmutov/cypress-react-unit-test/issues/425#issuecomment-693435760

Thus it would be nice to show how to provide React (and other JS libraries) somehow, maybe similar to CSS libraries list on mount?

**Comment by BlueWinds** [comment]
Going to close this as stale - we've reworked a bunch of stuff in the last couple years, especially in Cypress 10 / component testing, and there's not a ton of actionable information captured here for the future.
