### ISSUE TITLE
Browserify plugin is firing 'watched:file:changed' twice on change

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#968]
This is a bug introduced likely somewhere in the plugins refactor.

Whenever you change a spec file I'm getting two 'watched:file:changed' events.

When this happens this causes the Runner to reinstantiate Cypress and to stop the previous one. At this point `this.runner` and `this.cy` are undefined, which is why it fails. We could guard against that there, but there would be hiding the underlying problem.

![screen shot 2017-11-27 at 7 52 43 pm](https://user-images.githubusercontent.com/1268976/33297012-c55fde7e-d3ac-11e7-81ba-78e2b39fb94c.png)

and

![screen shot 2017-11-27 at 7 51 45 pm](https://user-images.githubusercontent.com/1268976/33297015-c911165a-d3ac-11e7-8e4b-9a7225378ca6.png)

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by brian-mann** [comment]
Released in [`1.1.3`](https://docs.cypress.io/guides/references/changelog.html#1-1-3).
