### ISSUE TITLE
Error: use mount or unmount functions please place the spec in component folder

### ISSUE THREAD

**Issue by SirMishaa** [cypress-io/cypress#9681]
Hello, 

When I run my test, I get the following error: 
``Error: In order to use mount or unmount functions please place the spec in component folder``
![image](https://user-images.githubusercontent.com/42717232/100499243-290cda00-3168-11eb-8839-2811195e3782.png)

The problem is that my test is already in the same folder (components).

~/components/TestCypress.spec.ts : 
```ts
import { mountCallback } from 'cypress-vue-unit-test'
import { createWrapper } from '@vue/test-utils'
import TestCypress from './TestCypress.vue'

describe('Index page', function () {
  beforeEach(mountCallback(TestCypress))
  it('should initialize', function () {
    cy.wrap(Cypress.vue)
      .should('not.be.undefined')
      .get('h1.cypress')
      .contains('Cypress is working !')

    cy.wrap(createWrapper(Cypress.vue)).should((cmp) => cmp.isVueInstance())
  })
})
```
~/components/TestCypress.vue : 
```html
<template>
  <div>
    <h1 class="cypress">Cypress is working !</h1>
  </div>
</template>

<script>
export default {
  name: 'TestCypress',
}
</script>
```

~/e2e/plugins/index.js : 
```js
import cypressNuxt from 'cypress-nuxt'
/**
 * @type {Cypress.PluginConfig}
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
module.exports = async (on, config) => {
  on('file:preprocessor', await filePreprocessor())
  return config
}

function filePreprocessor() {
  require('ts-node').register({
    compilerOptions: {
      target: 'ES2018',
      module: 'ESNext',
    },
  })
  return cypressNuxt.plugin({})
}
```

~/e2e/cypress.json : 
```json
{
  "experimentalComponentTesting": true,
  "componentFolder": "src/components",
  "fixturesFolder": "e2e/fixtures",
  "ignoreTestFiles": "test/**",
  "integrationFolder": "./",
  "testFiles": "components/*.*spec.*",
  "pluginsFile": "e2e/plugins/index.js",
  "screenshotsFolder": "e2e/screenshots",
  "supportFile": "e2e/support/index.js",
  "videosFolder": "e2e/videos",
  "nodeVersion": "bundled",
}
```

I would like to point out that when I use the "mount" method (as in the example) instead of "mountCallback", I have the same problem. 

Versions : 
- nuxt : 2.14.7
- Cypress : 6.0.0
- cypress-nuxt : 1.3.1
- cypress-vue-unit-test : 3.5.1
- node : 14.14.0
- ts-node : 9.0.0

**Comment by maxmckenzie** [comment]
I think "componentFolder": "src/components", has to point at the folder where you component tests are. Not your actual vue components. I think. I moved the test file to the same folder as the vue component and it worked.

**Comment by vahidd** [comment]
For me, this error was because of using the wrong version of `@cypress/react`. The version was `4.16.4`, which after updating to `5.3.2`, the error disappeared.
