### ISSUE TITLE
See if we can test TSDX components

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9683]
- https://twitter.com/jaredpalmer/status/1308886223839203331
- open PR to add E2E test that spins Next.js page that includes the component under test https://github.com/formium/tsdx/issues/886

**Comment by jennifer-shehane** [comment]
Closing as stale. Please update to the latest versions of Cypress and @cypress/react. If you'd like to see a new feature or bugfix, open a new issue with a reproducible example in those versions.
