### ISSUE TITLE
Not getting code coverage on single file component

### ISSUE THREAD

**Issue by smfelsher** [cypress-io/cypress#9684]
## Is this a bug report or a feature request?
Bug Report

- version
   - 1.0.0-alpha.4
- platform
    - Manjaro Linux 5.9.1
    - Node 14.2
    - Cypres 5.5.0
    - Nuxt 2.14.7
- expected behavior
My Vue single file component should be instrumented with code coverage. According to the [instructions](https://github.com/bahmutov/cypress-vue-unit-test#code-coverage), code coverage should be applied automatically.
- actual behavior
The Cypress test runner indicates that it could not find any coverage information.

1. I have configured my Cypress `plugins` preprocessor using [cypress-nuxt](https://github.com/NickBolles/cypress-nuxt).
1. I have configured my Cypress `support` to `import '@cypress/vue/dist/support'`.
1. I have enabled `experimentalComponentTesting` and defined `componentFolder` in my `cypress.json` file.

This configuration runs my test spec, but does not produce code coverage results.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
