### ISSUE TITLE
Is there a Roadmap?

### ISSUE THREAD

**Issue by gtamas** [cypress-io/cypress#9685]
I'm a bit confused about this. I can see this is still alpha, but many features are already implemented and it seems to be usable for most purposes.

About when can we expect the first "stable" version (1.0) to be released? Could you give me just a rough estimate?  Or is there a roadmap page that I could check somewhere?

We would like to use this kinda testing in a real world project which will go to prod in a few months. Is this already stable enough to be used in such a project, or should we wait for 1.0?  

Actually normal e2e testing with Cypress also fits our needs, but this would be obviously much better.  

Thanks in advance!

**Comment by jennifer-shehane** [comment]
Component Testing with @cypress/vue is now in alpha. Watch our Roadmap and Changelog for updates in our https://docs.cypress.io
