### ISSUE TITLE
Support CRA config overrides via react-app-rewired and customize-cra

### ISSUE THREAD

**Issue by Relaxe111** [cypress-io/cypress#9688]
I have set create-react-app with react app rewired absolute path like:
config-overrides.js:
![image](https://user-images.githubusercontent.com/40892030/95178487-c75f6d80-07bf-11eb-912d-9d491925c6b1.png)
also configured tsconfig.paths.json to use aboslute paths:
![image](https://user-images.githubusercontent.com/40892030/95178588-ea8a1d00-07bf-11eb-9511-e537bc68f5ca.png)
I also configured cypress to to start through react-app-rewired(overrides react-scripts without ejecting):
 package.json:
![image](https://user-images.githubusercontent.com/40892030/95178898-3d63d480-07c0-11eb-8d4f-522478297a1e.png)
I import in MyComponentToTest.tsx another component with absolute path : 
MyComponentToTest.tsx:
![image](https://user-images.githubusercontent.com/40892030/95179080-756b1780-07c0-11eb-85c7-be3728547cd8.png)
when i run yarn cypress:open and run cypress/integration/App.spec.tsx it work as expected.
However when i try to run component test MyComponentToTest.tsx  i get error that it was unable to solve the path : 
![image](https://user-images.githubusercontent.com/40892030/95179454-eb6f7e80-07c0-11eb-8bd7-00fdf68e8165.png)

My question is how i can learn cypress to use absolute paths for unit testing too?

my example app: 
[cypres-unit-test.zip](https://github.com/bahmutov/cypress-react-unit-test/files/5332425/cypres-unit-test.zip)

**Comment by tkharuk** [comment]
@bahmutov this remains as it was - no way to feed cypress the `config-overrides.js`?
we use it to initiate `addBabelPlugin('babel-plugin-transform-react-qa-classes')` which is a useful utility for us to add `data-qa` tags automatically based on component name

**Comment by MohoiNad** [comment]
Does this situation changes after v10?
For now we have some different way to config cypress's webpack.

I have similar problem with my repo here: https://github.com/MohoiNad/cypress-issue

So my cypress test failed, but testing library not

**Comment by binginsin** [comment]
I had the same issue, my solution was the following cypress.config.js file:
Note: the project structure is:
Project
-- cypress
---- tsconfig.json
-- src
-- tsconfig.json
-- config-overrides.js
-- cypress.config.js
    
```
//this doesn't work
process.env.NODE_ENV = 'development';
const path = require('path');
const { babelInclude, override } = require('customize-cra');
//Get webpack from react-app-rewired - this finds the original webpack and then uses config-overrides.json to override
const webpackOverride = require('react-app-rewired/overrides/webpack');

//our config-overrides.json has babelInclude([path.resolve('./src')]) which means our cypress files are not included in the webpack
//so override it to include both src and cypress
const overrideBabel = override(babelInclude([path.resolve('./src'), path.resolve('./cypress')]));

//Construct the new webpack
const webpack = overrideBabel(webpackOverride());

//Not sure why this is required but is false (boolean) by default and webpack wants a string
webpack.output.devtoolModuleFilenameTemplate = '[name].js';

module.exports = {
    e2e: {
        devServer: {
            framework: 'react',
            bundler: 'webpack',
            webpackConfig: webpack,
        },
        baseUrl: 'http://localhost:5000',
    },

    component: {
        devServer: {
            framework: 'react',
            bundler: 'webpack',
            webpackConfig: webpack,
        },
    },
};
```

Note that I only tested the component config as I didn't have any e2e tests setup

**Comment by bencergazda** [comment]
@binginsin Thanks for sharing your solution. Unfortunately it didn't work for me out of the box, but helped me understanding the problem and creating the final setup. It looks like this:

```javascript
import { defineConfig } from 'cypress';

/**
 * "Rewire" the webpack config before `loadWebpackConfig` accesses it through `react-scripts`
 * @see @cypress/webpack-dev-server/dist/helpers/createReactAppHandler.js:41
 */
process.env.NODE_ENV = 'test';
process.env.BABEL_ENV = 'test';
require('react-app-rewired/config/webpack.config')('development');

export default defineConfig({
  component: {
    devServer: {
      framework: 'create-react-app',
      bundler: 'webpack',
    },
  },
});
```

Ref: #22521 #8723

**Comment by Falcowoski** [comment]
> ```js
> import { defineConfig } from 'cypress';
> 
> /**
>  * "Rewire" the webpack config before `loadWebpackConfig` accesses it through `react-scripts`
>  * @see @cypress/webpack-dev-server/dist/helpers/createReactAppHandler.js:41
>  */
> process.env.NODE_ENV = 'test';
> process.env.BABEL_ENV = 'test';
> require('react-app-rewired/config/webpack.config')('development');
> 
> export default defineConfig({
>   component: {
>     devServer: {
>       framework: 'create-react-app',
>       bundler: 'webpack',
>     },
>   },
> });
> ```

Thank you so much @bencergazda! :rocket: :heart: 

I've been trying to troubleshoot webpack errors while running a component test for more than 3 hours, and I finally found this issue and its answer, which completely solved my problem!

My error was in relation to using absolute paths inside the component that was being tested.

```
Module not found: Error: Can't resolve '@lib/Animations
```

In my case, `BABEL_ENV` didn't seem to be needed, so I removed it.

Also, I replaced "**test**" with "**development**" in `NODE_ENV`.

The **TypeScript** compiler was reporting an error when assigning a value to a read only variable, which forced me to use @ts-ignore.

```ts
// @ts-ignore
process.env.NODE_ENV = 'development';
```
