### ISSUE TITLE
window.top

### ISSUE THREAD

**Issue by mqli** [cypress-io/cypress#969]
- Operating System: OSX
- Cypress Version:1.0.2
- Browser Version:builtin electron

### Is this a Feature or Bug?
Bug

### Current behavior:
The to-be-test url has been insert into test runner ui by **iframe**,when visit some app has code access window.top,like 
`window.top.location.href = 'http://www.google.com'`,the test runner ui will be redirected.

### Desired behavior:

 is there any way to use `webview` instead, or other way to work around to safely access 'window.top.location' ?

#### Test code:

```js

```

**Comment by brian-mann** [comment]
It sounds like you are either:

- Testing an application not under your control
- Visiting an application that implements security mechanisms that prevent Cypress from working

We've written about this in our docs here: https://docs.cypress.io/guides/references/trade-offs.html#

Specifically, we reference how this happens in this comment: https://github.com/cypress-io/cypress/issues/392#issuecomment-274987217

Cypress is not a general purpose automation tool - you should be using it to test your own applications. When doing so - simply disable the javascript code responsible for these security checks. It usually only 2-3 lines of code. In your case there's no reason for your code to check `window.top`. If it actually is embeddable iframe content, then it should use `window.parent` which will point to the immediate ancestor.

**Comment by brian-mann** [comment]
This cannot be generically fixed - but we can give you network traffic rewrite rules to enable you to modify the source on the fly to strip / change the way JS code works.

**Comment by jennifer-shehane** [comment]
Some updates to frame-busting changes we're making can be read here: #886
