### ISSUE TITLE
Get Webpack Compilation Error on nextjs test with component-level css

### ISSUE THREAD

**Issue by yrue** [cypress-io/cypress#9690]
Hi,

We have a nextjs project and using component-level css. I tried with the nextjs sample and it works. But it got error as below when importing `import styles from './<component>.module.scss';`. Looks mini-css-extract-plugin issue and the log similar to https://github.com/nrwl/nx/issues/2174. Any idea?

```
Error: Webpack Compilation Error
./components/Search.module.scss
Module build failed (from /Users/eur/Desktop/dev_uba/cypress-react-unit-test/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
 @ ./components/Search.jsx 5:0-42
 @ ./cypress/components/Search.spec.jsx
```

**Reproduce**
repo: https://github.com/yrue/cypress-react-unit-test/tree/issue
1. add ` "nodeVersion": "system" ` to cypress.json
2. add scss file `cypress-react-unit-test/examples/nextjs/components/Search.module.scss`
3. add `import styles from './Search.module.scss';` to `cypress-react-unit-test/examples/nextjs/components/Search.jsx`
4. run `npm test` and got error

**Comment by testplop** [comment]
Still a issue

**Comment by nagash77** [comment]
Hi @testplop please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.
