### ISSUE TITLE
Testing library for Cypress does not load correctly

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9691]
Seems Webpack chokes on `exports`

cypress/component/advanced/testing-lib-example/testing-lib-spec.js

<img width="423" alt="Screen Shot 2020-10-13 at 11 14 23 AM" src="https://user-images.githubusercontent.com/2212006/95880297-58e15900-0d45-11eb-86c7-7997ad1dc2b2.png">

Disabling this test for now

**Comment by jennifer-shehane** [comment]
Closing as stale.
