### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by skk2142** [cypress-io/cypress#9694]
Currently, every file edit leads to a reload of the selected test. This makes testing very slow while developing. Would it be possible to use hot webpack module reload, may be something like how [storybook](https://github.com/storybookjs/storybook.git) does it?

**Comment by lmiller1990** [comment]
Hi @skk2142,

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. Component testing is no longer experimental (but still in alpha, with lots of updates and improvements coming in the next few weeks). Please let us know if you find any more issues.

Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Changelog: https://docs.cypress.io/guides/references/changelog
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

The main difference is we moved from a `file:preprocessor` architecture to a `dev-server` architecture. This means you get hot reload, so things (really) fast now! There is a super basic setup [here](https://github.com/lmiller1990/cypress-react-template) if you want to try it out, or you can follow the [migration guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing) to update to Cypress 7.0 and the new dev-server architecture + component testing runner.

**Comment by skk2142** [comment]
love the speed!! I still wish it could hot reload the UI without running the test: for instance if I change the css.

**Comment by lmiller1990** [comment]
We are working on improving this...  mid-long term, we probably will have something like a "design mode" where the test does not execute, and we just use HMR to update the css.

**Comment by skk2142** [comment]
That would be perfect!! Thanks for the great work cypress team is doing!

**Comment by TimPchelintsev** [comment]
"Design mode" will be a terrific feature to have. Cypress rocks! Integration tests as a way not only to actually test things, but to develop them every day already was a game changer for me, but recreating and seeding database on each test really slows things down. So I start experimenting with component tests and immediately find them super useful. So to continue this line I am sure most Cypress users will use this component tests to develop and design them from scratch - and for this hot reload is highly desirable. Thank you cypress team!
