### ISSUE TITLE
Occasional debug mode triggerred in chrome by itself

### ISSUE THREAD

**Issue by skk2142** [cypress-io/cypress#9696]
Here's the version info:
"cypress": "^5.5.0"
"cypress-react-unit-test": "^4.16.9"
Chrome 86
OS: Macbook
I'm also using `cypress-react-unit-test/plugins/load-webpack` plugin
<img width="1792" alt="Screen Shot 2020-11-08 at 12 58 59 PM" src="https://user-images.githubusercontent.com/10248760/98472689-bc369d80-21c2-11eb-9e5c-64a7a20a07cd.png">

**Comment by jennifer-shehane** [comment]
Closing as stale. Please try updating to the latest versions of Cypress and @cypress/react. If you are still experiencing an issue, please open an issue with a reproducible example using those versions.
