### ISSUE TITLE
Add support for "focus" assertion (to work effectively as Chai jQuery assertion does)

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#97]
Chai jQuery added a [`focus`](https://github.com/chaijs/chai-jquery/commit/4551346946bb2e76c2cf6cd67f6369fd77b5da16) assertion recently.

Cypress needs support for focus assertions so I can assert whether a DOM element has or does not have focus.

**Example**

``` javascript
cy
  .get('input')
    .type('Foo').should('have.focus')
    .blur().should('not.have.focus')
```

**Comment by anniekvandijk** [comment]
Hi, I need a test for checking focus too and I think this could be a nice workaround?

Instead of checking if the element you select is focussed, you get the focussed element and check if the properties/attributes or whatever are conform expectations. In my case, I needed a focus on the field with a name
```javascript
cy.focused().should('have.attr', 'name', fieldName);
```

**Comment by Bkucera** [comment]
Hi, after this PR #3219 , you will be able to do the following assertions:

```js
cy.get('div').should('have.focus')
cy.get('div').should('not.have.focus')
cy.get('div').should('be.focused')
cy.get('div').should('not.be.focused')

expect(div).to.have.focus
expect(div).to.not.have.focus
expect(div).to.be.focused
expect(div).to.not.be.focused

```

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/3219

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/3219, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by denkristoffer** [comment]
I'm getting "CypressError: The chainer: 'focus' was not found. Could not build assertion." with Cypress 3.3.0 when I do `cy.get('search_input').should('have.focus')`. Am I using it wrong or should I create a new issue?

**Comment by ThisIsJesus** [comment]
> I'm getting "CypressError: The chainer: 'focus' was not found. Could not build assertion." with Cypress 3.3.0 when I do `cy.get('search_input').should('have.focus')`. Am I using it wrong or should I create a new issue?

I second that. Whether I use `'have.focus` or `be.focused` I always get the error. It looks as if wasn't even present in this version.

**Comment by verheyenkoen** [comment]
Same. Also tried `.should('be.focused')`.

**Comment by Bkucera** [comment]
> I'm getting "CypressError: The chainer: 'focus' was not found. Could not build assertion." with Cypress 3.3.0 when I do `cy.get('search_input').should('have.focus')`. Am I using it wrong or should I create a new issue?

Currently looking into this

**Comment by alirezamirian** [comment]
Would be nice to have another assertion to check if the element is either focus, or contains focused element.
Currently `contains.focus` or `have.focus` both check if the element has focus. the former can become broader.
