### ISSUE TITLE
Webpack typescript configuration file

### ISSUE THREAD

**Issue by jonhaddow** [cypress-io/cypress#9700]
When I have a `webpack.config.ts` file, the following will fail:

```javascript
module.exports = (on, config) => {
	config.env.webpackFilename = "webpack.config.ts";
	cypressReactUnitTests(on, config);
	return config;
};
```

with this error: `Could not load webpack config from C:\{locationOfProject}\webpack.config.ts`

Will there be support for webpack configuration files written in TypeScript?

**Comment by dmtrKovalenko** [comment]
It looks like not, webpack is using ts-node registry to load ts based config file https://webpack.js.org/configuration/configuration-languages/ 

you can do the same if you wish by putting require('ts-node').register(). Or you can basically put a comment for typings in js file using `/** @type {Webpack.Configuration } */`
