### ISSUE TITLE
How to use it when using Quasar components

### ISSUE THREAD

**Issue by aislanmaia** [cypress-io/cypress#9707]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?
Feature request 

I would like to use this along using the Quasar 1.9+ versions
The problem is I don't know how to use this and get the quasar components in the unit tests as well.

**Comment by aislanmaia** [comment]
Right now I've seen that Cypress 7.0.0 brings to the table the Component Tests. 
The docs are clear saying that we need to offer a webpack config to the cypress plugin configuration.
But Quasar projects doesn't use vue-cli but its own cli with webpack config embedded to `quasar.conf.js`. 

So if someone knows how to get that webpack config part it will be appreciated.

**Comment by Blfrg** [comment]
Ive opened a discussion around this new Cypress feature on the [quasar-testing repo](https://github.com/quasarframework/quasar-testing/issues/163)
There I've _lightly_ outlined what I suspect might be needed to make Quasar and Cypress [Component Testing] work together.

A _Cypress_ native approach might be possible (and easier) if Cypress mount() supports:
- an already instantiated localVue
- or an alternative ```mount(myMountFn)``` provider to be used for the mounting process, then wrapped by cypress

Either of these options might enable Cypress to work with various implementations which offer their own mount wrapper
(not limited to Quasar)

Note: I'm not certain if this addresses the webpack config requirements
