### ISSUE TITLE
Webpack error when used within the Rushstack ecosystem 

### ISSUE THREAD

**Issue by alfonsoar** [cypress-io/cypress#9710]
Issue: 

When using this tool within the [rushstack](https://rushstack.io/) ecosystem we observe a webpack error when trying to run the unit tests. A couple of concepts tools to keep in mind are: 

[Rush](https://rushjs.io/pages/intro/welcome/) (Monorepo tool)
[Heft](https://rushstack.io/pages/heft/overview/) (Build system, running TS)
[Rig package](https://rushstack.io/pages/heft/rig_packages/) (Helps manage Heft build)

Example error: 

<img width="1203" alt="Screen Shot 2020-12-08 at 9 06 14 PM" src="https://user-images.githubusercontent.com/22054505/101564471-3bbdb500-3999-11eb-818c-905091d47fcd.png">

Reproduction Steps: 

I have set up a fresh repository to showcase this issue https://github.com/alfonsoar/rushstack-cypress-react-unit-integration, please follow the README steps to set-up the repo and run the unit tests. 

Only the [component-1](https://github.com/alfonsoar/rushstack-cypress-react-unit-integration/tree/master/components/component-1) package has cypress configured. 

Link to [cypress.json](https://github.com/alfonsoar/rushstack-cypress-react-unit-integration/blob/master/components/component-1/cypress.json)
Link to [webpack config](https://github.com/alfonsoar/rushstack-cypress-react-unit-integration/blob/master/components/component-1/webpack.config.js). --> [rush-rig](https://github.com/alfonsoar/rushstack-cypress-react-unit-integration/blob/master/rigs/rush-rig/library/webpack-shared.config.js)
Link to[ cypress plugin configuration](https://github.com/alfonsoar/rushstack-cypress-react-unit-integration/blob/master/components/component-1/cypress/plugins/index.js)
Link to [spec file  ](https://github.com/alfonsoar/rushstack-cypress-react-unit-integration/blob/master/components/component-1/cypress/component/example-app.spec.tsx)

**Comment by dmtrKovalenko** [comment]
It looks like webpack config path that you are passing [here](https://github.com/alfonsoar/rushstack-cypress-react-unit-integration/blob/master/components/component-1/cypress/plugins/index.js) is not correct. It should point direct location of the webpack config to use


```js
const preprocessor = require('cypress-react-unit-test/plugins/load-webpack')
module.exports = (on, config) => {

config.env.webpackFilename = 'rush-rig/library/webpack-shared.config.js'
  preprocessor(on, config)
  // IMPORTANT to return the config object
  return config
}
```
