### ISSUE TITLE
Cannot test React.lazy()

### ISSUE THREAD

**Issue by cellog** [cypress-io/cypress#9711]
lazy-loaded components loaded in a webpack environment error out. The chunk is requested, but Cypress intercepts it and returns something like this:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>component/BrazeIcon/src/integration_tests/0.BrazeIcon.test.tsx.js</title>
  </head>
  <body>
    <script type="text/javascript">
      document.domain = 'localhost';

      (function(parent) {
        var Cypress = window.Cypress = parent.Cypress;
        if (!Cypress) {
          throw new Error("Tests cannot run without a reference to Cypress!");
        }
        return Cypress.onSpecWindow(window, [{"absolute":"/Users/gregory.beaver/Documents/GitHub/beacon-labs/integration-tests/cypress/support/index.js","relative":"cypress/support/index.js","relativeUrl":"/__cypress/tests?p=cypress/support/index.js"},{"absolute":"/Users/gregory.beaver/Documents/GitHub/beacon-labs/packages/BrazeIcon/src/integration_tests/0.BrazeIcon.test.tsx.js","relative":"../packages/BrazeIcon/src/integration_tests/0.BrazeIcon.test.tsx.js","relativeUrl":"/__cypress/tests?p=../packages/BrazeIcon/src/integration_tests/0.BrazeIcon.test.tsx.js"}]);
      })(window.opener || window.parent);
    </script>
  </body>
</html>
```

It would be interesting to see if the loader could be made smart enough to "know" this is a chunk and return as-is?

**Comment by lmiller1990** [comment]
Hi @cellog,

Thanks for your patience!

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. Component testing is no longer experimental (still in alpha, with lots of updates and improvements coming in the next few weeks). This should solve your problem.

Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Changelog: https://docs.cypress.io/guides/references/changelog
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

The main difference is we moved from a `file:preprocessor` architecture to a dev-server architecture. Component testing is no longer experimental, and has a dedicated runner (which is build on top of an extends the existing cypress runner).

I made a super minimal template with React + Webpack 5 + Cyprress 7. I was able to lazy-load a component: https://github.com/lmiller1990/cypress-react-webpack-5-example/blob/79988eab080b3a86e1afffab024a1faad7ac2437/src/App.jsx#L4

We also have a [test for this](https://github.com/cypress-io/cypress/blob/develop/npm/react/cypress/component/advanced/lazy-loaded/App.js#L3) so once you upgrade to 7.x and use the new component testing runner, you should be able to test `React.lazy` like any other component.
