### ISSUE TITLE
Rollup support

### ISSUE THREAD

**Issue by albertodeago** [cypress-io/cypress#9712]
### Context
Sometimes, component libraries are bundled using Rollup (especially for the better tree-shaking support).
I see in [cypress-svelte-unit-test](https://github.com/bahmutov/cypress-svelte-unit-test#install) that Rollup can be used as a bundler.

### Objective
Can we achieve the same for cypress-vue-unit-test too? Is there a way we (from the outside) can make it work or is this in plan to be built in in this package?

My dream:
```js
// cypress/plugin/index.js
const fileDefaultPreProcessor = require('cypress-vue-unit-test/dist/preprocessor/rollup')
module.exports = on => {
  on('file:preprocessor', onFileDefaultPreprocessor)
}
```
And then in the test file
```js
// components/HelloWorld.spec.js
import { mount } from 'cypress-vue-unit-test'
import { HelloWorld } from './HelloWorld.vue'
describe('HelloWorld component', () => {
  it('works', () => {
    mount(HelloWorld)
    // now use standard Cypress commands
    cy.contains('Hello World!').should('be.visible')
  })
})
```

With the possibility to use a custom rollup config

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
