### ISSUE TITLE
TS2304: Cannot find name 'Chainable' when define return type  of `mount()` Chainable<JQuery<any>> 

### ISSUE THREAD

**Issue by ryota-murakami** [cypress-io/cypress#9713]
[I created simple Recoil wrapper of `mount()` API](https://github.com/laststance/create-react-app-typescript-todo-example-2020/blob/master/src/testUtil.tsx#L26-L39) Like this.

```tsx
// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
export const mountCypressWithRecoilRoot = (
  ui: React.ReactElement,
  initialRecoilStateValue: AppState = defaultValue
) /* Chainable<JQuery<any>> output: TS2304: Cannot find name 'Chainable' */ =>
  mount(
    <RecoilRoot
      initializeState={({ set }: MutableSnapshot): void =>
        set(recoilState, initialRecoilStateValue)
      }
    >
      {ui}
    </RecoilRoot>
  )
```

Firstly I used to `void` as return type but TypeScript shows this error.

<img width="1281" alt="Screen Shot 2020-11-04 at 23 30 14" src="https://user-images.githubusercontent.com/5501268/98133415-e9ecbf80-1f00-11eb-85c0-da969757e549.png">

So I tried set `Chainable<JQuery<any>>` but TypeScript Cannot find name 'Chainable'.

[My `tsconfig.json` setting](https://github.com/laststance/create-react-app-typescript-todo-example-2020/blob/master/tsconfig.json#L3) is here.

```json
{
  "compilerOptions": {
    "types": ["cypress", "@testing-library/cypress"],
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "jsx": "react"
  },
  "include": [
    "src",
    "cypress"
  ]
}
```

I have no clue despite compile option setting correct though **"types": ["cypress", "@testing-library/cypress"]**  🤔

Thank you for making amazing library!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
