### ISSUE TITLE
Issue when loading a service used by the store module.

### ISSUE THREAD

**Issue by ericledonge** [cypress-io/cypress#9714]
I am trying to test a module (event.js) in my store.

This module uses a service (EventService.js).

I have this issue: 

`Module not found: Error: Can't resolve '@/services/EventService.js'`

How can I load my services, please? 

[Event.spec.js](https://github.com/ericledonge/learning-real-world-vue/blob/cypress-unit-test-store-issue/tests/e2e/specs/event.spec.js)
[EventService.js](https://github.com/ericledonge/learning-real-world-vue/blob/cypress-unit-test-store-issue/src/services/EventService.js)
[Store/Module/Event.js](https://github.com/ericledonge/learning-real-world-vue/blob/cypress-unit-test-store-issue/src/store/modules/event.js)
[Cypress configuration](https://github.com/ericledonge/learning-real-world-vue/blob/cypress-unit-test-store-issue/tests/e2e/plugins/index.js)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
