### ISSUE TITLE
Handle different React references better

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9716]
Seems if we directly use React from `examples/*` folder, the React from the root clashes with React from the `example/*` folder

Example: `examples/visual-testing-with-percy`

`cypress-react-unit-test` is linked from its package.json file

```
"cypress-react-unit-test": "file:../.."
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "3.4.1"
```

And inside the root package.json 

```
"react": "^16.13.1",
"react-dom": "^16.13.1",
```

We get an error

<img width="802" alt="Screen Shot 2020-10-22 at 8 21 43 AM" src="https://user-images.githubusercontent.com/2212006/96871331-20760500-1440-11eb-9fb2-4f87715e87ff.png">

If we install cypress-react-unit-test by first packing it in the root folder and installing as TGZ, then everything is fine.

**Comment by jennifer-shehane** [comment]
Closing as stale
