### ISSUE TITLE
element is not autofocusing when mounted the second(++) time

### ISSUE THREAD

**Issue by paxcodes** [cypress-io/cypress#9717]
- version
"cypress": "^3.8.3",
"cypress-vue-unit-test": "^1.11.5",

- platform
Mac OS X

- steps to reproduce: 
[Repo](https://github.com/paxcodes/cypress-vut-253) 

Given: A test/spec that is *not* the first test
When: I try to mount an element that is autofocused
Expected: the element should be focused
Actual: the element is not focused...thus, the test fails.

❌ *When the test is not the first test the element is not focused*
![Screen Shot 2020-02-01 at 2 52 58 PM](https://user-images.githubusercontent.com/13646646/73600333-8f52ad00-4503-11ea-985f-27da11a71b9b.png)

✅ *When the test is the first test the element is focused*
![Screen Shot 2020-02-01 at 2 54 18 PM](https://user-images.githubusercontent.com/13646646/73600352-d2148500-4503-11ea-916c-6e2797108062.png)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
