### ISSUE TITLE
Property 'specType' does not exist on type '{ name: string; relative: string; absolute: string; specFilter?: string | undefined; }'. 

### ISSUE THREAD

**Issue by YannickLeRoux** [cypress-io/cypress#9718]
Typescript is throwing this error after installing cypress-react-unit-test:

`Property 'specType' does not exist on type '{ name: string; relative: string; absolute: string; specFilter?: string | undefined; }'. `
Cypress v5.4.0

https://github.com/bahmutov/cypress-react-unit-test/blob/de3b9b8b61ea6deae5953aeac51ee29ca618f6cb/lib/mount.ts#L8

**Comment by lmiller1990** [comment]
Hi @YannickLeRoux ,

Thanks for your patience!

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. Component testing is no longer experimental (still in alpha, with lots of updates and improvements coming in the next few weeks). This should solve your problem.

Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Changelog: https://docs.cypress.io/guides/references/changelog
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

The main differences:
- moved from a `file:preprocessor` architecture to a dev-server architecture. 
- Component testing is no longer experimental, and has a dedicated runner (which is build on top of an extends the existing cypress runner)
- `cypress-react-unit-test` is now `@cypress/react`.

Can you try updating to 7.x follow [the migration guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing)? I am not seeing this issue anymore, so I think everything should be okay.

If you still have this issue, please ping me and I will reopen this.
