### ISSUE TITLE
window.Cypress is undefined

### ISSUE THREAD

**Issue by tomaswitek** [cypress-io/cypress#972]
- Operating System: OS-X 10.12.5
- Cypress Version: 1.1.2
- Browser Version: Chrome 62.0.3202.94
### Is this a Feature or Bug?
bug

### Current behavior:
Cypress randomly crashes after visiting website. (`cy.visit('https://url')`)

### Desired behavior:
It would be nice without the crash 😄 

#### Test code:

```js
Cypress.Cookies.debug(true);
Cypress.Cookies.defaults({
  whitelist: cookieName,
});
// -- This is a parent command --
Cypress.Commands.add(
  'login',
  (username, password) => {
    cy.request(`${domain}netcenter/nacJS/loadNacProfilesV2`).then(response => {
      if (response.redirects) {
        cy.visit(domain);
        cy.get('#login').click();
        cy.get('#username').type(username);
        cy.get('#password').type(password);
        cy.get('#submit').click();
        cy.getCookie(cookieName).then(c => {
          cy.setCookie(cookieName, c.value, {
            domain: 'localhost',
            secure: false,
          });
        });
      }
    });
  },
);
```

### Additional Info (images, stack traces, etc)
```
home:4 Uncaught Error: Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue! at home:4
```

**Comment by brian-mann** [comment]
Yeah as the error suggests this should never happen. It makes no sense how this could ever happen.

The only way for `window.Cypress` not to be defined is if you were running outside of Cypress but using the Cypress proxy, which would never be the case.

This is unfortunately not enough information to reproduce - it likely has something to do with your application. Is this happening every time? Is it intermittent? 

You may have to provide a reproducible repo if you cannot provide the URL in question.

**Comment by tomaswitek** [comment]
I tried to debug it but without a success.
It looks like it was running outside of Cypress, because the left sidebar was gone when this exception was thrown.
It's happening intermittent and funny is that I can't reproduce right now at all.
I think we can close it for now. If it happens again I'll create a reproducible repo for you.
Thx for your support I appreciate it very much.

**Comment by paulmoliva** [comment]
I'm experiencing this issue as well with a React app. Oddly, window.Cypress is only undefined when the tests are run against a`create-react-app` production build version of the app. Tests work fine with the dev build.

**Comment by eduard2014** [comment]
I'm experiencing this issue with a Vue.js app.

**Comment by tonilopezmr** [comment]
`window.Cypress` is undefined when I run `cypress run` if I run `cypress open` is working fine, in my case I know it because I set the `window.store` only when `window.Cypress` is defined and if I run `cypress run` all my tests crash because `window.store` is not set it.

**Comment by benbonnet** [comment]
No one would pay for such a missing feature.

No one would pay for a service that has such an historical feature (https://github.com/cypress-io/cypress/issues/781)

[Would you then pay for email support ?](https://github.com/cypress-io/cypress/issues/932#issuecomment-460203838)

**Comment by vinod236** [comment]
I am facing same issue in 3.4.1 cypress with ReactJS app + okta , it used to work for some days, now it has stopped all of suddenly , i dont know what has caused this issue ("We expected to find the global Cypress in the parent window but it is missing") , i dont see content on right side Iframe and at that time i get this error , we have automted our Sanity suite using cypress So Please need your suggestion to fix this issue.

**Comment by jennifer-shehane** [comment]
We were never provided a completely reproducible example. We cannot move forward with investigating a feature without a reproducible test code and application code. 

We use `window.Cypress` ourselves in all of our applications and use this information to decide whether to run some tests or mock some things so have never encountered this error. 
This issue will be closed to further comment as the exact issue here was resolved and tested. 
 
There may be a specific edge case with the issue that we need more detail to fix, so please provide that so we can fix the issue.

**Comment by tonilopezmr** [comment]
Here is an example where `window.Cypress` is not working: https://github.com/Karumi/LitElementPlayground/tree/master/web

Here is the commit where I needed to remove `if(window.Cypress)` to add the `window.store` var only in Cypress tests. https://github.com/Karumi/LitElementPlayground/pull/11/commits/7dcb7cbf3faca3bc76bd0d5e6ce9151ed6206a01

**Comment by jennifer-shehane** [comment]
@tonilopezmr Running this in your tests shows that `window.Cypress` is defined. 

```
cy.window().its('Cypress').should('be.an', 'object')
```

You'll want to make sure that you are checking for the Cypress object after the window has loaded and it is present, not before. 

<img width="530" alt="Screen Shot 2020-01-03 at 3 55 01 PM" src="https://user-images.githubusercontent.com/1271364/71715955-8eb1f280-2e41-11ea-8e07-926e3da04e7d.png">

**Comment by tonilopezmr** [comment]
I was checking it on my `index.js` like I show you here https://github.com/Karumi/LitElementPlayground/pull/11/commits/7dcb7cbf3faca3bc76bd0d5e6ce9151ed6206a01#diff-1fdf421c05c1140f6d71444ea2b27638L48, also I added logs but didn't display it.

Maybe in tests `cy.window()` adds the variable but not in the execution of the tests or something like that.

@jennifer-shehane Thanks 👏 !

**Comment by kbaala88** [comment]
Any solutions for this and I face this consistently. 

_<head> <script type='text/javascript'> document.domain = '***.org'; var Cypress = window.Cypress = parent.Cypress; if (!Cypress) { throw new Error('Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!'); }; Cypress.action('app:window:before:load', window); </script>_

**Comment by kbaala88** [comment]
Also, any help that we can mock/stub a "doc" (document) type of call in the browser?Thanks!!!

**Comment by bahmutov** [comment]
@kbaala88 you are commenting on an unrelated closed issue. Please open an issue with detailed description and reproducible steps we can run to see the problem.

**Comment by paulmoliva** [comment]
This issue should not be closed, as it was never resolved. I suggest reopening the issue until it is resolved.

**Comment by kbaala88** [comment]
@bahmutov : Such a quick response, Thanks much for your response. As mentioned, opened a new issue ##15161 for this and looking for an help to get this resolved since this poses to be a blocker for us as we couldn't proceed with the flow beyond 2nd page consistently.

**Comment by bahmutov** [comment]
I am sorry, but we cannot investigate an issue without a reproducible example. I welcome someone to create a new public repo with code showing the problem, or clone https://github.com/cypress-io/cypress-test-tiny or https://github.com/cypress-io/cypress-example-recipes to demonstrate it, then we can reopn the issue.

**Comment by kbaala88** [comment]
Unfortunately couldn't share the code due to restrictions. If possible, i can demo the issue on call.

**Comment by kbaala88** [comment]
@bahmutov : Added additional details in ##15161 . Looks to be some basic trouble that cypress couldn't recognize and there is no workaround to move to next step , hence halting the complete execution. Thanks in advance for your help !

<img width="391" alt="1" src="https://user-images.githubusercontent.com/60440677/108556070-6e324980-731c-11eb-87d8-821c65b4cc5f.png">
<img width="401" alt="2" src="https://user-images.githubusercontent.com/60440677/108556076-6ffc0d00-731c-11eb-9b72-9105b2a624ec.png">
<img width="404" alt="3" src="https://user-images.githubusercontent.com/60440677/108556079-7094a380-731c-11eb-9936-8642d7584eee.png">

**Comment by kbaala88** [comment]
@bahmutov : Also with your expertise, if you can show a sample if we can mock the "Doc" type of network call shown in the snapshot also might help to resolve this as a workaround.

<img width="391" alt="1" src="https://user-images.githubusercontent.com/60440677/108556190-a46fc900-731c-11eb-93df-4b4c2773d410.png">

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
