### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by sundowndev** [cypress-io/cypress#9720]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?
Bug report

Linux 4.18.0-20-generic cypress-io/cypress-vue-unit-test#21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Cypress 3.3.1

I created a test importing a vue file with a single test, also edited my plugins/index.js as shown in the doc :

```js
// cypress/plugins/index.js
const webpack = require('@cypress/webpack-preprocessor')
const { VueLoaderPlugin } = require('vue-loader');

const webpackOptions = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      },
      {
        test: /\.css$/,
        loader: ['style-loader', 'css-loader']
      }, {
        test: /\.styl$/,
        loader: ['style-loader', 'css-loader', 'stylus-loader']
      }
    ]
  },
  plugins: [
    new VueLoaderPlugin(),
  ],
}

const options = {
  // send in the options from your webpack.config.js, so it works the same
  // as your app's code
  webpackOptions,
  watchOptions: {}
}

module.exports = on => {
  on('file:preprocessor', webpack(options))
}
```

My test : 

```js
import App from '../../../app/src/App.vue';
import mountVue from 'cypress-vue-unit-test';

describe('App.vue', () => {
  beforeEach(mountVue(App))

  it('should succeed', () => {
    // Any Cypress command
    // Cypress.vue is the mounted component reference
  })
})
```

But I get this error in Cypress : 

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
```

Same error when running the Hello test in this repository.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
