### ISSUE TITLE
Setting up Cypress unit testing with NUXT

### ISSUE THREAD

**Issue by warheartvik** [cypress-io/cypress#9721]
Does anybody managed to set up Cypress Unit Testing with Nuxt?

For e2e testing, which I know is the main feature of Cypress, the setting up is easy, and I started writing tests 1 minute later.

I have tried setting in up for unit testing using the instructions given for vue cli 3.

[https://github.com/bahmutov/cypress-vue-unit-test#vue-cli-3](url)

But Is not working in nuxt. Any documentation on thir matter?

Best Regards!

**Comment by travis5491811** [comment]
Thanks to Nick for [another plugin](https://github.com/NickBolles/cypress-nuxt) but I think we'd be better off to know what configuration to add until we can have an official plugin. Especially when it's just a config and we can avoid worrying about [contributing to dependency hell](https://blog.appsignal.com/2020/04/09/ride-down-the-javascript-dependency-hell.html) or the security and responsiveness of the maintainer for another dependency.

[Cypress updated their docs](https://github.com/cypress-io/cypress/blob/master/npm/vue/docs/manual-install.md) to show how to do a manual setup with `vue-cli`. But after trying it, the cypress examples work in my `nuxt` project and if i update my config like the readme suggest, i get the following error (i've checked my plugin file multiple times and additionally tried `npm install --save-dev webpack-dev-server`):.


```
**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `/Users/example1/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

**Details:** Error: Cannot find module '@cypress/webpack-dev-server'
Require stack:
- /Users/example1/node_modules/@cypress/vue/dist/plugins/webpack/index.js
- /Users/example1/cypress/plugins/index.js
- /Users/travis/Library/Caches/Cypress/6.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/travis/Library/Caches/Cypress/6.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/example1/node_modules/@cypress/vue/dist/plugins/webpack/index.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/example1/cypress/plugins/index.js:19:22)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)

**Stack trace:**

Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/Users/example1/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/Users/travis/Library/Caches/Cypress/6.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:986:15)
    at EventEmitter.<anonymous> (/Users/travis/Library/Caches/Cypress/6.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:153:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/Users/travis/Library/Caches/Cypress/6.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

```

To resolve the above, install `@cypress/webpack-dev-server`. But that will result in `PeerDependencyMissing: @cypress/webpack-dev-server is missing peer dependencies Webpack Dev Server`. So you also need to install `webpack-dev-server`

Now those errors are gone, the next issue is when running test. Note the missing `.vue` lookup

```
Error: Webpack Compilation Error
Looked for and couldn't find the file at the following paths:
[/ProjectPath/components/FormInput]
[/ProjectPath/components/FormInput.js]
[/ProjectPath/components/FormInput.json]
[/ProjectPath/components/FormInput.jsx]
[/ProjectPath/components/FormInput.mjs]
[/ProjectPath/components/FormInput.coffee]
```

If i specify the import to be `.vue` i get:

```
Error: Webpack Compilation Error
./components/FormInput.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

So if someone can provide what the config looks like to get `cypress` reading `vue` files, we should be able to update the docs for manual installation that works for `nuxt` users.

**Comment by travis5491811** [comment]
For anybody still looking at this, [A Cypress Nuxt](https://github.com/cypress-io/cypress/blob/develop/npm/vue/examples/nuxt/README.md) was recently added. The example is not working for me but i'm still troubleshooting and will update once I get things working.

**Comment by travis5491811** [comment]
Huge thanks to @elevatebart for helping get this resolved! I think we can close this issue now. 

In addition to the `nuxt` example above,[ Here is an example](https://github.com/travis5491811/cypress-vue-nuxt/commits/main) of `@cypress/vue` working with `nuxt` where the commit history shows going from a fresh `nuxt` project to working with `@cypress/vue`.

**Comment by elevatebart** [comment]
Once the example is updated with your finds I will close this ticket.

Thank you for your patience.

**Comment by travis5491811** [comment]
Example is updated as of latest commit. I also updated the Readme with the exact steps users need to take to make this work in their existing `nuxt` project. I used it to get it working in our production `nuxt` project . The only thing i'm not sure of is how old of a `nuxt` project this will work for.

**Comment by lmiller1990** [comment]
We have a [nuxt example now](https://github.com/cypress-io/cypress/tree/develop/npm/vue/examples/nuxt). Is there anything else to be done here?

**Comment by elevatebart** [comment]
@travis5491811 agreed. I will try to document it more clearly what I did in there after a clean `create nuxt-app`

**Comment by jennifer-shehane** [comment]
This was released.

**Comment by annymosse** [comment]
still it doesn't work i have followed [the above links](https://github.com/cypress-io/cypress/tree/master/npm/vue) all has been change/deleted ,and this one didn't work :(
