### ISSUE TITLE
Include CSS styles test example in documentation

### ISSUE THREAD

**Issue by Rup1** [cypress-io/cypress#9722]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request? Feature Request

Reading through the documentation I found no info on how to include component's CSS in the unit test so as to test various states of the component (clicking `done` crosses out the `todo` with css rule `text-decoration: line-through`).  

So when I run my test the console shows `No styles injected for this component` How do I go about this?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
