### ISSUE TITLE
Include VueLoaderPlugin() in documentation

### ISSUE THREAD

**Issue by paxcodes** [cypress-io/cypress#9723]
## Is this a bug report or a feature request? **Bug report**

**- version**
"cypress-vue-unit-test": "^1.11.0",
"cypress": "^3.1.5",
"@cypress/webpack-preprocessor": "^4.0.3",
"vue-loader": "^15.6.4",

**- steps to reproduce**

1. Create a fresh project (in my case, I installed a fresh laravel project through composer
2. `npm install --save-dev cypress cypress-vue-unit-test`
3. `npm install` (for other project dependencies)
4. follow [manual instructions ](https://github.com/bahmutov/cypress-vue-unit-test#manual) to load and test single-file vue components

**- expected behavior**
In the following screenshots, I used [the component example](https://github.com/bahmutov/cypress-vue-unit-test#component-example).  FYI, I had to remove [the <style> tag](https://github.com/bahmutov/cypress-vue-unit-test/issues/151#issuecomment-467421879) because it was causing a similar (i.e. loader) error, but that's irrelevant to this issue.

![screenshot](https://user-images.githubusercontent.com/13646646/53410568-0dfcad00-3979-11e9-831b-ae50212f5482.png)

**- actual behavior**

![screenshot](https://user-images.githubusercontent.com/13646646/53410690-56b46600-3979-11e9-98f9-8f57ae3d5c0a.png)
`vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config.`

**- suggested fix** 
Add the VueLoaderPlugin in webpack config. I read from [this comment](https://github.com/symfony/webpack-encore/issues/311#issuecomment-390491179) that VueLoader v15 and above requires the VueLoaderPlugin to be added in the webpack config.

```
const { VueLoaderPlugin } = require("vue-loader");
const webpack = require("@cypress/webpack-preprocessor");
const webpackOptions = {
....
plugins: [
    new VueLoaderPlugin()
  ]
};

const options = {
....
```

It would be nice to add this to the documentation to save others time.

Perhaps related issue:
https://github.com/bahmutov/cypress-vue-unit-test/issues/151 - [Someone ]( https://github.com/bahmutov/cypress-vue-unit-test/issues/151#issuecomment-441649778) posted a working code that already has the VueLoaderPlugin() in but it was not explicitly pointed out.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
