### ISSUE TITLE
Running unit tests along with e2e tests

### ISSUE THREAD

**Issue by irriss** [cypress-io/cypress#9724]
Hello,

My intention is to run e2e tests and unit tests in cypress. I created a new project using vue/cli 3 and selected an option e2e tests with cypress. After project files were generated I was able to run e2e test with standard command "vue-cli-service test:e2e"

Next, I was trying to add unit tests into the runner as described in this manual. But as soon as I follow this step

> Enable the import of Vue files by uncommenting the "webpack import" and the "file:processor event" lines in tests/e2e/plugins/index.js.

the e2e test stops working: cy application runs, it sees the test, I can click on it, browser opens, but test never appears in the browser (even before I start adding my unit tests)

Is there something missing? I installed "cypress-vue-unit-test" and "@cypress/webpack-preprocessor" but it did not help.

Thank you for any guidance,
BR,
Ruslan

**Comment by lmiller1990** [comment]
Hi all.

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. 

Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Changelog: https://docs.cypress.io/guides/references/changelog
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

[Read the intro blog post](https://www.cypress.io/blog/2021/04/06/introducing-the-cypress-component-test-runner/) or the [getting start with Vue 2/3 blogpost](https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/).

The vue-cli-cypress plugin has not been updated, but you can follow the steps in the blog post (or just look at the example repo) to see how to set things up with Vue CLI. I did it and it's working great (both Vue 2 and Vue 3).

We will update the Vue CLI plugin at some point in the near future.

Let me know if you have any further issues.
