### ISSUE TITLE
@kazupon/vue-i18n-loader as Dev Dependency instead

### ISSUE THREAD

**Issue by HoraceKeung** [cypress-io/cypress#9725]
Hello,

Is it possible to have @kazupon/vue-i18n-loader as Dev Dependency instead?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
