### ISSUE TITLE
Intro Examples not working, Vue-Cli 3, fresh install

### ISSUE THREAD

**Issue by sebastianjung** [cypress-io/cypress#9727]
BUG

- version 1.11.0
package.json:
```
{
  "name": "cypress-test-3000",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:e2e": "vue-cli-service test:e2e"
  },
  "dependencies": {
    "vue": "^2.5.17"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.1.0",
    "@vue/cli-plugin-e2e-cypress": "^3.1.0",
    "@vue/cli-service": "^3.1.0",
    "cypress-vue-unit-test": "^1.11.0",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "vue-template-compiler": "^2.5.17"
  }
```

Terminal says
```
GET /__/ 200 18.770 ms - -
GET /__cypress/runner/cypress_runner.css 200 36.240 ms - -
GET /__cypress/runner/cypress_runner.js 200 281.366 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.6.3 200 1.661 ms - 71896
GET /__cypress/iframes/integration/test.js 200 6.710 ms - 709
(node:2412) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
HEAD / 500 4527.223 ms - -
HEAD / 500 4537.110 ms - -
HEAD / 500 4543.925 ms - -
```

- platform
Win 10, VS Code (Terminal is Git Bash), 
- expected behavior
to show at least the cypress logs
- actual behavior
On `cypress open` or `npm run test:e2e`, clicking the spec -> chrome opens, not showing anything but "waiting on localhost". Then after quite a while stops with "not tests found"

**Additional Information:**
fresh install with vue-cli 3,
intro examples from docs also don't work,
test.js
```
import mountVue from 'cypress-vue-unit-test';
import HelloWorld from '../../../src/components/HelloWorld.vue';

describe('HelloWorld', () => {
    beforeEach(mountVue(HelloWorld));

    describe('clicking the save button', () => {
        let spy;

        beforeEach(() => {
            spy = cy.spy();
            Cypress.vue.$on('save', spy);

            cy.get("[data-test='messageText']")
                .type('New message');

            cy.get("[data-test='saveButton']")
                .click();
        });

        it('clears the text field', () => {
            cy.get("[data-test='messageText']")
                .should('have.value', '');
        });

        it('emits the "save" event', () => {
            expect(spy).to.have.been.calledWith('New message');
        });
    });
});
```

**Comment by lmiller1990** [comment]
Hi all.

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. 

Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Changelog: https://docs.cypress.io/guides/references/changelog
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

[Read the intro blog post](https://www.cypress.io/blog/2021/04/06/introducing-the-cypress-component-test-runner/) or the [getting start with Vue 2/3 blogpost](https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/).

The vue-cli-cypress plugin has not been updated, but you can follow the steps in the blog post (or just look at the example repo) to see how to set things up with Vue CLI. I did it and it's working great (both Vue 2 and Vue 3).

We will update the Vue CLI plugin at some point in the near future.

Let me know if you have any further issues.
