### ISSUE TITLE
Better documentation and example project(s)?

### ISSUE THREAD

**Issue by electrocnic** [cypress-io/cypress#9728]
Thank you for this nice tool!

However, would you possibly be so kind as to add one or more example repos which have some example vue code including this tool configured and up and running out of the box?

The reason I ask this is, for me as a complete beginner in webdevelopment, vue, webpack, web-app-testing, I am not able to figure out currently, WHERE the examples from the README.md (Code and configuration) need to be placed in the project's file hierarchy. I am not sure what to do exactly. Example projects would really help. And a note for each code example, telling people which file this is and where it is placed, relative to the project's root, would also be a mandatory information imo.

Hope you can provide me help.

Thanks a lot!

**EDIT:** After a short time I figured all of it out, nailing it to:
A short sentence at the top of the docs, saying something like "Knowledge about cypress is a mandatory requirement in order to use this tool" would be completely sufficient. My bad.

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please see https://docs.cypress.io/guides/component-testing/introduction and https://github.com/cypress-io/cypress/blob/develop/npm/vue/README.md
