### ISSUE TITLE
Connect Remote Vue DevTools

### ISSUE THREAD

**Issue by alukos** [cypress-io/cypress#9729]
Last time I ask about it [#63](https://github.com/bahmutov/cypress-vue-unit-test/issues/63).

Now Vue DevTools support Vue instances within iframes if used [Remote instance](https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md).
And its work with [restrictions](https://github.com/cypress-io/cypress/issues/2396).

But I can't to connect with this plugin.
How to do it?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
