### ISSUE TITLE
Compare to unit testing tutorial 

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9735]
Compare to this tutorial that uses `vue-test-utils` and Jest

- Tutorial: https://alexjoverm.github.io/2017/08/21/Write-the-first-Vue-js-Component-Unit-Test-in-Jest/
- GitHub with source code: https://github.com/alexjoverm/vue-testing-series/tree/lesson-1

Great components (Message, MessageList) and unit tests

**Comment by jennifer-shehane** [comment]
Closing as stale. To be re-evaluated by our docs team.
