### ISSUE TITLE
Serve static assets

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9736]
Sometimes there are static assets included from the components, like images. `<img src="./assets/logo.png">` - the webpack dev server serves these, or can build it into a folder, but Cypress does not handle these files.

See code at https://github.com/bahmutov/vue-cli-and-cypress/issues/1

**Comment by lmiller1990** [comment]
Fixed in 7.0:

![image](https://user-images.githubusercontent.com/19196536/113806130-215be280-97a5-11eb-8330-f0a4b732a2ce.png)

Repo: https://github.com/lmiller1990/vue-cypress-template
