### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by syryl** [cypress-io/cypress#974]
It display me error when trying install
```npm install cypress --save-dev
root@syryls:/var/www/cy# npm install cypress --save-dev
npm WARN engine cypress@1.1.2: wanted: {"node":">=6.5.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'cypress/listr-verbose-renderer' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'cypress'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "cypress" "--save-dev"
npm ERR! cwd /var/www/cy
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/cy/npm-debug.log
npm ERR! not ok code ```

Debian 8

**Comment by jennifer-shehane** [comment]
Here's the bit of the error to pay attention to:
```
npm WARN engine cypress@1.1.2: wanted: {"node":">=6.5.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
```

Cypress requires a node version >=6.5.0. You will need to update node to install.

**Comment by syryl** [comment]
```
root@syryls:/var/www/cy# node -v
v9.2.0
```

**Comment by brian-mann** [comment]
Yeah this is likely a weird problem specific to your system. 

Cypress is installed successfully thousands of times every day.

The package that npm is saying isn't published is certainly published else every single installation would fail.

For reference here it is: https://www.npmjs.com/package/@cypress/listr-verbose-renderer

Unfortunately, I don't believe there's anything actionable for us to investigate with the information provided. :-(

**Comment by brian-mann** [comment]
Even though `node -v` says its higher, when `npm install` is running, its using an older version of node. That is likely your problem.

**Comment by brian-mann** [comment]
Closing unless more information can be provided that points to changes needed in the Cypress codebase.
