### ISSUE TITLE
Partial route mock

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#976]
Is there a chance to partially mock a route? What I'm interested to achieve is something like this:
```js
cy.route({
    method: 'POST',
    url: 'api/myEndpoint',
    response: this.onResponse,
    onResponse: xhr => ({
        ...xhr,
        response: {
            ...xhr.response,
            body: {
                ...xhr.response.body,
                foo: 'bar'
            }
        }
    })
})
```
so that in regression mode, I'll still allow the real endpoint to flow, but instead of seeding my database per each test, I can alter the response to suit the need of my feature under test.

What I tried was
```js
cy.route({
    method: 'POST',
    url: 'api/myEndpoint',
    onResponse: xhr => xhr.response.body.foo = 'bar'
})
```
which alters the xhr response when I'm clicking on the route and view the Logger, but this doesn't get passed into the response to be consumed.

and
```js
cy.route({
    method: 'POST',
    url: 'api/myEndpoint',
    response: {},
    onResponse: function(xhr) { this.response = {
        ...xhr,
        response: {
            ...xhr.response,
            body: {
                ...xhr.response.body,
                foo: 'bar'
            }
        }
    }}
})
```
doesn't change the response at all.

I don't think any of the [function-approach examples](https://docs.cypress.io/api/commands/route.html#Function) are suitable for this kind of need.

Thank you!

**Comment by jennifer-shehane** [comment]
No, this is not currently possible, but could potentially be added as a feature.

**Comment by brian-mann** [comment]
This is related to https://github.com/cypress-io/cypress/issues/687

When we rewrite the network layer this will be added. You can go check out all of the other referenced issues connected to this.

**Comment by kentmw** [comment]
I ran into this issue today. I'm excited it's on the roadmap

**Comment by kentmw** [comment]
@paulpruteanu Did you find a workaround?

**Comment by paulpruteanu** [comment]
Nope, just waiting for the full network layer stubbing, which will be a game changer.

**Comment by in2lag** [comment]
Hi,

this is something what's really missing. Our use case -> i need backend to create an order (i need order code) and then modify server response to skip the redirect to payment gateway. I'm sitting on this the whole day today. I don't have any workaround in mind. one callback like `onBeforeResponse(xhr)` will be great

**Comment by edudelta** [comment]
> Hi,
> 
> this is something what's really missing. Our use case -> i need backend to create an order (i need order code) and then modify server response to skip the redirect to payment gateway. I'm sitting on this the whole day today. I don't have any workaround in mind. one callback like `onBeforeResponse(xhr)` will be great

My workaround was:
1. Opening the payment page in another navigator tab
2. Perform steps through Cypress([Promise](https://docs.cypress.io/api/utilities/promise.html#Waiting-for-Promises)...)/Javascript directly to this new tab.
3. Once payment finished, opening on Cypress the page result to continue testing.
4. Close the new tab.

Hope it help.

**Comment by jennifer-shehane** [comment]
The features requested in this issue are now possible as part of `cy.route2()`. 

`cy.route2()` is currently experimental and requires being enabled by passing `"experimentalNetworkStubbing": true` through your Cypress configuration. This will eventually be merged in as part of our standard API. 

**Please see the `cy.route2()` docs for full details: https://on.cypress.io/route2**

If you encounter any issues or unexpected behavior while using `cy.route2()` we encourage you to [open a new issue](https://github.com/cypress-io/cypress/issues/new?assignees=&labels=&template=bug-report.md&title=) so that we can work out all the issues before public release. Thanks!
