### ISSUE TITLE
I cannot capture the an angular Todo input

### ISSUE THREAD

**Issue by kushanlk** [cypress-io/cypress#978]
I'm trying to go to the https://angularjs.org/ site and trying to type text on the following element 

input class="ng-pristine ng-valid ng-empty ng-touched" type="text" placeholder="Enter a name here" ng-model="yourName"

This is my Cypress script 
describe('Kushan First Test', function(){
    it('Go to google',function(){
cy.visit('http://todomvc.com/examples/angularjs/#/')
cy.get('#yourName').type('ss')
})
})
But this is not identifying the input. Please help me on this soon as possible

**Comment by bahmutov** [comment]
Is the element with this id present? Have you checked using the devtools? What's the error ? Can you please provide a screenshot?

**Comment by bahmutov** [comment]
Ok, Cypress does give you a nice message - your selector is wrong. This is the input box, it does not have an id.

```
<input type="text" ng-model="yourName" placeholder="Enter a name here" class="ng-pristine ng-untouched ng-valid ng-empty">
```

The right selector is by attribute `'[ng-model="yourName"]'` - just test the selector from the DevTools console `$('[ng-model="yourName"]')`!
