### ISSUE TITLE
clientY/clientX not calculating correctly on cy.click().

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#98]
The first set of `console.warn` shows the `clientX` and `clientY` values when `cy.click()` runs on my canvas element. 

The second set of `console.warn` shows the `clientX` and `clientY` values when I manually click in the center of my canvas element.

![screen shot 2016-02-05 at 2 36 55 pm](https://cloud.githubusercontent.com/assets/1271364/12857038/f46b045a-cc15-11e5-8c65-996d55bc319c.png)

Cypress appears to be printing the "`top` + (1/2 height of the element)" instead of calculating the "(`top` - `pageYOffset`) + (1/2 height of the element)" to get the correct `clientY`.

`clientX` is likely calculating wrong as well, but since I was only scrolling vertically, the `clientXOffset` was always 0, so did not affect the calculation.

![clientY diagram](https://i-msdn.sec.s-msft.com/dynimg/IC561970.png)

**Comment by brian-mann** [comment]
Fixed in [`0.14.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0140-03082016).
