### ISSUE TITLE
If running single spec, name output video file using spec name

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#980]
## feature

If running a single spec with `--spec <filename>` instead of random video filename like `abc123.mp4` name the video file using the spec base name.

Should especially help when we isolate running each spec (parallel work)

**Comment by brian-mann** [comment]
This is included as part of issue https://github.com/cypress-io/cypress/issues/681

By chunking runs by spec the video names will always match the spec name. 🎉 

Are we taking that issue and splitting into many smaller issues?

**Comment by brian-mann** [comment]
Fixed by PR https://github.com/cypress-io/cypress/pull/1583
