### ISSUE TITLE
Wrong result in assertion be.visible in elements inside an SVG (Electron)

### ISSUE THREAD

**Issue by Sumolari** [cypress-io/cypress#983]
### Current behavior:

Assertion `be.visible` returns `false` for elements inside an SVG node.

### Desired behavior:

Assertion `be.visible` returns real visibility of elements inside an SVG node.

### How to reproduce:

See [playground project](https://github.com/Sumolari/cypress-svg-be.visible-playground).

- Operating System: tested on macOS 10.13.1 although should fail in any OS
- Cypress Version: 1.1.2
- Browser Version: Electron (Chrome v53.0.2785.143, Electron v1.4.6)

**Comment by jennifer-shehane** [comment]
The Electron browser that Cypress uses has been updated to use Chrome 61 as of [Cypress 3.3.0](https://on.cypress.io/changelog#3-3-0), so this is no longer an issue. 

I also verified this is working by running the supplied repository through the updated Cypress.
