### ISSUE TITLE
cy.click("bottomLeft") coordinates for click can potentially exceed the element's bounding box.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#99]
Cypress' calculation for normalizing coordinates can cause `cy.click()` to occur outside of the bounds of the element for `cy.click("bottomLeft")`.

`Math.floor()` is always called on the x coordinate, but if the `left` coordinate of the element is at `615.83`, then the x coordinate will calculate to `615` which will nudge the click slightly to the LEFT of the element, leaving it outside the element's boundaries.

The use of `Math.floor()` versus `Math.ceil()` depends on the location of the coordinate being clicked.

![math-floor-vs-ceil](https://cloud.githubusercontent.com/assets/1271364/12858158/6509713c-cc1c-11e5-9845-0dc18a66b693.jpg)

**Comment by jennifer-mann** [comment]
This is fixed in the upcoming 0.14.0 release.

**Comment by brian-mann** [comment]
Fixed in [`0.14.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0140-03082016).
