### ISSUE TITLE
Error not shown in the reporter when using `document.write`

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#993]
### Current behavior

If we load HTML page that throws a JS error, it is shown in the Cypress test reporter GUI. For example here is HTLM page

```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  example loaded
  <script>
    console.log('a message')
    throw new Error('from HTML')
  </script>
</body>
</html>
```

When test just does simple 

```js
beforeEach(() => {
  cy.visit('index.html')
})

it('works', () => {})
```

Then the gui shows the error

<img width="729" alt="error-shown" src="https://user-images.githubusercontent.com/2212006/33502518-67a0032c-d6ae-11e7-9550-780841308202.png">

But if we write the same page into test iframe ourselves, the error is swallowed

```js
// as as file "index.html"
const html = `
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  example loaded
  <script>
    console.log('a message')
    throw new Error('from HTML')
  </script>
</body>
</html>
`

beforeEach(() => {
  cy.document().then(doc => {
    doc.write(html)
    doc.close()
  })
})

it('works', () => {})
```

<img width="706" alt="error-not-shown" src="https://user-images.githubusercontent.com/2212006/33502540-80c88392-d6ae-11e7-82f0-2f84e864a3c5.png">

I know this is kind of weird test case, but I accidentally discovered it when working on Codepen demo https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/blogs__codepen-demo when the page I was using was broken, and the tests just got blank screen

Example repo with these two tests: https://github.com/bahmutov/cy-document-write-exception

- Operating System: Mac
- Cypress Version: 1.1.2
- Browser Version: all

**Comment by jennifer-shehane** [comment]
This is still an issue in Cypress 3.4.0

Related: https://github.com/cypress-io/cypress/issues/2487
