### ISSUE TITLE
cy.visit behind corporate firewall

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#994]
Under my corporate firewall, I can't cy.visit "outside" websites, eg. https://cypress.io, even if it opens successfully in the browser. What I observed is that in this case, curling such an external website fails as per below
```unix
$ curl https://cypress.io
curl: (7) Failed connect to cypress.io:443; No error
```
I can cy.visit though internal resources, which curls successfully.
Any thoughts?

**Comment by bahmutov** [comment]
Seems your proxy is really preventing you from doing your job, isn't it? You can download and have cypress binary on your local network but you will only be able to test your internal sites.

**Comment by paulpruteanu** [comment]
Is there a way to specify the http and https proxies when cypress fetches the contents of a page?
I found that there is a way to curl the external resources with curl https://my.url.com --proxy http://user:pass@proxyurl.
