### ISSUE TITLE
Cleanup readme's for various packages

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#995]
Driver, runner, and probably a bunch of others all need updating.

**Comment by bahmutov** [comment]
In what sense?

**Comment by brian-mann** [comment]
Just look at https://github.com/cypress-io/cypress/pull/996/files

Many README's had factually inaccurate information in them. Commands that didn't exist, processes that don't work. Even descriptions that were false.

The Desktop GUI and the Driver both stated that there were **zero** tests for those packages - when both have hundreds (the driver has thousands).

I normalized all of their names, their sections, descriptions, even npm scripts to align to best practices.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/996

**Comment by brian-mann** [comment]
Released in [`1.1.3`](https://docs.cypress.io/guides/references/changelog.html#1-1-3).
