### ISSUE TITLE
Uncaught ReferenceError in page under test

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#997]
If I cy.visit a page that contains a Javascript error eg
```js
Uncaught ReferenceError: foo is not defined
```
the test stops there, throwing the error. Is there a way to bypass it?

**Comment by bahmutov** [comment]
We need this recipe as example in the cy.visit docs. For now search for it in the documentation and FAQ and recipes

**Comment by paulpruteanu** [comment]
Not so sure I got the answer J

**Comment by brian-mann** [comment]
I don't believe we need a recipe for this, we just need to update the error message to specify more details, including a link to error documentation - redirecting you to the catalog of events.

Anyway, what Gleb is trying to say is that had you searched our docs for the word: "uncaught"

You would have gotten an autocomplete that looks like this:

![screen shot 2017-12-02 at 8 06 22 pm](https://user-images.githubusercontent.com/1268976/33521306-5ff627fc-d79c-11e7-88f1-be4336ef4706.png)

As you can see - we not only have an FAQ about this, but we have an exact explanation in the docs of how to stop this.

Then had you clicked that link you would have been taken to an example that shows you exactly what to do:

![screen shot 2017-12-02 at 8 06 31 pm](https://user-images.githubusercontent.com/1268976/33521311-7712c198-d79c-11e7-9ea7-78f97ca04226.png)

**Comment by bahmutov** [comment]
I'm all for linking a lot more from error messages, 100%

**Comment by paulpruteanu** [comment]
Many thanks indeed. I must have slipped from my sight, as I regularly refer to the docs.

**Comment by kymark12** [comment]
Hi I'm still facing the same issue after adding the code to my script, here's a copy of my script below:
`describe('Pre-Prod testing', function() {
    it('Logging In', function() {
      cy.visit('https://amadeus-prod-staging.flyakeed.com')
      Cypress.on('uncaught:exception', (err, runnable) => {
        return false
      })
      cy.contains('Log In').click()
      cy.get('.number-en-only-np')
      .type('9054447777')
      .should('have.value', '9054447777')
      cy.contains('+966').click()
      cy.contains('+63').click()
      cy.contains('Send Verification Code').click()
      cy.wait(3000)
      cy.get('.mb30 > .form-code')
      .type('456455')`


But the test runner still fails the test every time I run It.
![image](https://user-images.githubusercontent.com/13220136/43453393-953ae1a6-94ec-11e8-9552-00f9478ac335.png)

**Comment by bahmutov** [comment]
Can you try registering the error handler before the test or at least before the visit? I wonder if it is set too late
